### ISSUE TITLE
Magento 2.0 Search using REST APIs documentation and examples

### ISSUE THREAD

**Issue by Jayme-T** [magento/devdocs#1006]
I am trying to use your magento 2.0 documentation for searches (http://devdocs.magento.com/guides/v2.0/howdoi/webapi/search-criteria.html) and I was able to set it up for both "or" and "and" searches but it says on this page you support 'in' and I can't seem to make that work. There is no sample data on how to set up an in with the various filter group and filters that are required.

  	newVendorParameters["searchCriteria[filter_groups][0][filters][0][field]"] = exp.attribute;
        newVendorParameters["searchCriteria[filter_groups][0][filters][0][value]"] = exp.value;
        newVendorParameters["searchCriteria[filter_groups][0][filters][0][condition_type]"] = "in";

where exp.attribute is something like "email" and exp.value is a list of e-mails and I can't seem to get the correct data back. I get a 200 but it won't actually return the information even if the email value is in that list. I appreciate your help. Thanks

-Jamie

**Comment by keharper** [comment]
@Jayme-T , I got this to work using the sample data:

http://<host>/rest/default/V1/customers/search?
searchCriteria[filter_groups][0][filters][0][field]=email&
searchCriteria[filter_groups][0][filters][0][value]=roni_cost@example.com,roni_cost@gmail.com,roni_cost@yahoo.com&
searchCriteria[filter_groups][0][filters][0][condition_type]=in

**Comment by keharper** [comment]
That should be 

```
http://<host>/rest/default/V1/customers/search?
searchCriteria[filter_groups][0][filters][0][field]=email&
searchCriteria[filter_groups][0][filters][0][value]=roni_cost@example.com,roni_cost@gmail.com,roni_cost@yahoo.com&
searchCriteria[filter_groups][0][filters][0][condition_type]=in
```

**Comment by Jayme-T** [comment]
Yup sorry I made a mistake on my end. You can go ahead and close this issue. Thanks for the quick response

**Comment by keharper** [comment]
I'll add a sentence to the descriptions of the `in` and `nin` conditions stating that those conditions accept a comma-separated list of values. If nothing else, you've made me aware that those conditions needed some attention, so thanks!
