### ISSUE TITLE
Risky differentiation between vendor/ & app/code/

### ISSUE THREAD

**Issue by scottsb** [magento/devdocs#1008]
*Split off of #1004 into a separate issue as requested.*

Page being addressed:
http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_file-sys-perms.html

Differentiating between contributing developers or non-contributing developers in terms of providing directions around `vendor/` and `app/code/` is misguided. Both contributing and non-contributing developers should equally protect `vendor/` and `app/code/`. While non-contributing developers won't have anything inside `app/code/` by default at install, this is the standard place to create any custom modules that aren't going to be packaged as individual composer packages, not to mention the place that many third-party modules will be installed if the third party does not support composer.

**Comment by xcomSteveJohnson** [comment]
@scottsb To be a little dense, all you're suggesting is to advise to put the same restrictions on both `app/code` and `vendor`? 

If so, I'll do it right away. Thanks for pointing it out.

**Comment by xcomSteveJohnson** [comment]
@scottsb Please confirm; this is an easy change to make.

**Comment by xcomSteveJohnson** [comment]
@scottsb This should be fixed now. Please check.

**Comment by xcomSteveJohnson** [comment]
This is fixed, closing. Please open another issue if there are remaining issues.
