### ISSUE TITLE
Clarify difference between read-only and writeable permission sections

### ISSUE THREAD

**Issue by scottsb** [magento/devdocs#1009]
*Split off of #1004 into a separate issue as requested.*

Page being addressed:
http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_file-sys-perms.html

The difference in intent between the subsections "Make files and directories read-only" and "Make files and directories writable" is unclear. The list of directories to protect provided prior to this section is not fully represented in either subsection, and it's further not clear if these two subsections are both supposed to be followed or if they are alternatives. Presumably they are alternatives, since the commands are exact opposites in points, but it's not explicit when one should be used versus the other. (Part of the issue may be the extremely ambiguous "files and directories" in the heading.)

**Comment by xcomSteveJohnson** [comment]
@scottsb Are you referring to both the one-user and two-user instructions? 

I'm pretty sure the read-only instructions are for everyday use and the writable instructions are so you can update the software and extensions.

I can certainly make that more clear. Do you think this is the source of confusion?

**Comment by scottsb** [comment]
Yes, that's what I'm referring to.

Adding direction about which option would be a first step. Right now it's not clear why you would follow the one set of directions over the other. It would also help to say "code files and directories" instead of just "file and directories," since that's really where the difference lies.

There's also a higher-level question of whether it should ever be recommended to have code files and directories writable in production. That implies that you are installing updates and extensions directly in production, which is certainly not best practice. I understand this ties into the "expert" vs. "DIY" tension we've discussed elsewhere, but at a minimum there should probably be a warning against the code-writeable option for those who have the choice.

**Comment by xcomSteveJohnson** [comment]
OK, thanks. I'll add some words to make it more clear when directories should be writable and let you know when it's done.

**Comment by scottsb** [comment]
The other issue here is that the commands in the two sections are not fully parallel right now. (For example, the "read-only" section sets permissions on `vendor/` while the "writeable" section doesn't.) That means that if you're using these commands to switch back and forth between the modes (as I assume the intent is), they will not actually reverse each other fully.

**Comment by xcomSteveJohnson** [comment]
@scottsb Both issues should be resolved. Please check; I went a little blind when trying to make sure the readable/writable commands were the same so I'd appreciate a double-check there.

**Comment by scottsb** [comment]
Looks good. The one thing you could do to make the commands a bit more transparent to the user and also help you from going blind comparing them is to sort the directories in the initial bulleted list and both commands the same way. The order won't make any difference in the command's effect.

**Comment by scottsb** [comment]
I also still think it would be worth saying "code files and directories" since that's what really matters here.

**Comment by xcomSteveJohnson** [comment]
I took your advice on code files and directories. Thanks! Closing.
