### ISSUE TITLE
Installing sample-data also requires `php bin/magento setup:upgrade`

### ISSUE THREAD

**Issue by kweij** [magento/devdocs#1012]
Feedback on page: /guides/v2.0/install-gde/install/sample-data-before-composer.html
Feedback on page: /guides/v2.0/install-gde/install/sample-data-before-clone.html

Ok, I figured it out, but installing the sample-data also requires to execute `php bin/magento setup:upgrade`. It rather trivial, perhaps, but the documentation is not complete when lacking this instruction. I propose to add this instruction and tried to do so my self, but can't find the appropriate file at https://github.com/magento/devdocs/blob/develop/guides/v2.0/install-gde/install/sample-data-before-composer.md

**Comment by xcomSteveJohnson** [comment]
@kweij I'm not sure this is correct. If you run `magento sampledata:deploy` before you install Magento, it should work. In fact, I don't think `magento setup:upgrade` will work before Magento is initialized.

Are you sure you used `magento sampledata:deploy` _before_ you installed Magento?

**Comment by xcomSteveJohnson** [comment]
@kweij Please respond, thanks.

**Comment by kweij** [comment]
I ran `magento sampledata:deploy` _after_ installing Magento. This caused no problem, it just required running `magento setup:upgrade`.

Perhaps the documentation should stated that _if_ you run magento sampledata:deploy after you've installed Magento, you need to run `magento setup:upgrade`. That seems missing in the docs.

**Comment by xcomSteveJohnson** [comment]
@kweij Thank you for clarifying.

**Comment by xcomSteveJohnson** [comment]
@kweij Pages are updated. If you're happy, please close this.

**Comment by xcomSteveJohnson** [comment]
No comments for >14 days, closing. Feel free to open a new one if there's something we can help you with.
