### ISSUE TITLE
Error in Grunt Instructions

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#1015]
On the following page

http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html

There's the following instructions

> Install (or refresh) the node.js project dependency, including Grunt, for your Magento instance. To > do this, run the following commands in a command prompt:
> cd <your_Magento_instance_directory>
> npm install
> npm update

However, when I try to run the above command with a  freshly installed 2.1.3 (from the composer create-project method), I get the following error.

    $ npm install
    $ npm WARN enoent ENOENT: no such file or directory, open '/Users/alanstorm/Sites/magento-2-1-3.dev/project-community-edition/package.json'

It seems to be looking for a local `package.json` file that doesn't exist. 

    $ ls -l package.json
    ls: package.json: No such file or directory

Not sure what the right solution here is, but a new user following along with the dev docs will be blocked here.

**Comment by hostep** [comment]
@astorm, you are looking at the wrong version of the docs again :wink:

It was changed in [Magento 2.1](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html) as to how to set it up:
> Rename the following files in your Magento root directory:
> package.json.sample to package.json
> Gruntfile.js.sample to Gruntfile.js

**Comment by astorm** [comment]
Thanks @hostep -- I'm just following the links Google throws up at me -- you might want to look into  ways of ensuring the latest version of the platform is the one Google sees ;)

Closing out.

**Comment by tanberry** [comment]
@astorm  and @hostep  I myself was actually thrown by this just yesterday; I asked Google about  indexers in Magento, and got all excited about a hit... then later realized it was a Magento 1.x document. ;-(

I'll add that to our list of things to improve about our site. Heads up, @jcalcaben ! ;-)
