### ISSUE TITLE
Broken styling on 2.0 UI Components

### ISSUE THREAD

**Issue by BenSpace48** [magento/devdocs#1016]
The styling on [this page](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/ui_components_js.html) isn't looking too good.

Spotted in Chrome Version 55.0.2883.95 (64-bit) on OSX Yosemite 10.10.2.

![using_ui_components__client-side](https://cloud.githubusercontent.com/assets/8895777/22327664/430eb932-e3b0-11e6-9d76-c3096e168007.jpg)

![using_ui_components__client-side_and_itunes](https://cloud.githubusercontent.com/assets/8895777/22327663/430e13ce-e3b0-11e6-8270-bea572e71b81.jpg)

Not sure if the console errors are related:

![screen shot 2017-01-26 at 10 15 08](https://cloud.githubusercontent.com/assets/8895777/22327679/5b72ebe2-e3b0-11e6-9c6e-590efaaca1db.png)

**Comment by tanberry** [comment]
@BenSpace48  Ouch, yes, that's a mess for sure. Thanks for alerting us, we will get that fixed asap.
 @almarchenko can you take a look please, and maybe start with examining the .md file /guides/v2.0/javascript-dev-guide/ui_components_js.md?

Pull in @jcalcaben if it turns out to be an issue with automation.

**Comment by tanberry** [comment]
we just found it. It is in the 2.0 UI Compoents book. @jcalcaben  is fixing the redirect right now. 

@almarchenko, notice how that topic is at the top of the TOC? Can you please move it to under Overview? And also, please add a Note in the Overview section of the 2.0 UI Comps Guide encouraging readers to please look at the 2.1 version of the UI Comps Guide.

**Comment by BenSpace48** [comment]
I'm impressed with the speed you're handling it, well played and thank you!

**Comment by tanberry** [comment]
;-) With a page that messed up, none of us could even have an appetite for lunch, or sleep, until it was fixed. Thank YOU for catching it!

**Comment by almarchenko** [comment]
@tanberry  Done)

@BenSpace48  Please re-open this issue if we missed something, thank you!

**Comment by BenSpace48** [comment]
Looks miles better, thanks.
