### ISSUE TITLE
Lack of reference to working sample modules in documentation

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#1019]
Feedback on page: /guides/v2.0/howdoi/checkout/checkout_carrier.html

**Why You have not added reference link to magento 2 [sample modules github repository](https://github.com/magento/magento2-samples/tree/master/sample-module-shipping-provider). I would like personally see a way how the documentation has been implemented in practical module!** Practical modules would make some of the tutorials more clearer then it would be possible by writing articles.

**Comment by almarchenko** [comment]
@user3748173 
Thank you for your comment! You are definitely right about the sample modules being a great illustration. Please give us a couple of days and we’ll get back with a comment on this particular situation.

**Comment by almarchenko** [comment]
Hi @user3748173!

We are not 100% sure that the sample-module-shipping-provider module is completely up-to-date for the last versions of Magento. 
The good news is that Magento has a new Community Engineering team, that will take action on that specific module and all of the sample modules soon. And we will definitely add links to them where appropriate.

Thanks for raising this question! Please reopen the issue if there's something else on this topic.
