### ISSUE TITLE
Shipping-method step: using form or field?

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#1027]
I have read [ these tutorials](http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_overview.html) that have risen question that has not been answered anywhere in the web. 

While customising Shipping-method step, when it is right to add input fields as form and when should be added as field? How should developer decide between those two options? 

Examples: Fields added below shipping-method block, place that is meant for it (inside shipping method form).

**Comment by xcomSteveJohnson** [comment]
@ccondra Can you help?

**Comment by ccondra** [comment]
This is really a question for a developer.  Sorry I can't help with this one!

**Comment by tanberry** [comment]
@VladimirZaets ?

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to create a new issue if necessary. Thank you for continued collaboration and assistance!
