### ISSUE TITLE
JavaScript Errors Preventing Link Click

### ISSUE THREAD

**Issue by notlee** [magento/devdocs#1030]
Feedback on page: /guides/v2.1/howdoi/bk-how-do-i.html

I'm unable to click "Edit this page on GitHub" or "Give us feedback" without removing Event Listeners because of JS errors in `analytics.js`.

**Comment by xcomSteveJohnson** [comment]
What browser do you use? Do you have developer debugging tools turned on?

Works fine for me in Chrome.

**Comment by xcomSteveJohnson** [comment]
@notlee Any update?

**Comment by notlee** [comment]
Sorry for the delay @xcomSteveJohnson. Looks like my privacy extension https://disconnect.me/ was blocking GA and Munchkin which led to this. 

David Walsh wrote about a similar issue he had with Ghostery a couple of years ago: https://davidwalsh.name/detecting-google-analytics

I've opened a PR which makes the analytics fail gracefully in such cases, although there are better solutions:
https://github.com/magento/devdocs/pull/1048

**Comment by xcomSteveJohnson** [comment]
Thanks, we'll take a look.

**Comment by xcomSteveJohnson** [comment]
@belbiy Please take a look.

**Comment by jcalcaben** [comment]
PR Link: https://github.com/magento/devdocs/pull/1048
