### ISSUE TITLE
Installing sample data instructions don't actually give you instructions

### ISSUE THREAD

**Issue by lfolco** [magento/devdocs#1036]
Feedback on page: /guides/v2.1/install-gde/install/sample-data.html

It tells you to "Modify Magento's root composer.json to enable sample data modules." but it doesn't tell you what to actually modify.

**Comment by xcomSteveJohnson** [comment]
@lfolco Sorry about that omission. While I'm fixing the topic, you can go [here](http://devdocs.magento.com/guides/v2.1/install-gde/install/web/install-web-sample-data-composer.html) to find the information you need.

Are you installing sample data _after_ installing Magento? In that case, see [this topic instead](http://devdocs.magento.com/guides/v2.1/install-gde/install/sample-data-after-composer.html)

**Comment by lfolco** [comment]
Great, thanks!

**Comment by xcomSteveJohnson** [comment]
Fixed it. Please check and close this if you're happy with the resolution.
