### ISSUE TITLE
Styles debugging page links to article on compiling with Grunt

### ISSUE THREAD

**Issue by lfolco** [magento/devdocs#1039]
Feedback on page: /guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_approach.html

Under recommended reading, the link to _Styles Debugging_ links to an article about Compiling LESS with Grunt (http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html). Is this by design?

**Comment by almarchenko** [comment]
Hi @lfolco !

Thank you for the feedback! The link itself is correct, but the text should be "Compile LESS with Grunt ".
I've corrected the doc, the change will be published soon.

**Comment by almarchenko** [comment]
It's published)
Thank you for the feedback.
