### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by ivagarfitt** [magento/devdocs#1042]
How can I fix this error?

> Error 503 Backend fetch failed
> 
> Backend fetch failed
> 
> Guru Meditation:
> 
> XID: 32771
> 
> Varnish cache server

**Comment by xcomSteveJohnson** [comment]
Need more context but also, you should consider posting this on stackexchange or the Magento 2 GitHub because you'll likely get a better response.

Have you looked at this: http://devdocs.magento.com/guides/v2.0/config-guide/varnish/tshoot-varnish-503.html

**Comment by ivagarfitt** [comment]
I did, and that is my question (sorry, not very clear).

Where in this docker can I find /etc/default/varnish?

**Comment by xcomSteveJohnson** [comment]
Are you using DevBox? If so, try posting the question [here](https://github.com/magento/magento2devbox-web/issues). I watch that repo and will update documentation accordingly.

If you're not using DevBox, I'm sorry but I don't know the answer. Try posting on a technical forum. Thanks!

**Comment by xcomSteveJohnson** [comment]
No more info or questions for >14 days, closing.
