### ISSUE TITLE
Syntax Errors between 2.0 and 2.1

### ISSUE THREAD

**Issue by DavidLambauer** [magento/devdocs#1056]
The following Site contains Syntax Errors in the Roadmap Section:

http://devdocs.magento.com/guides/v2.1/config-guide/multi-site/ms_nginx.html

<img width="617" alt="screenshot at feb 27 16-04-54" src="https://cloud.githubusercontent.com/assets/1841317/23366305/83781b02-fd06-11e6-94d6-873be3b898d9.png">

**Comment by DavidLambauer** [comment]
I tried to solve them by myself, but couldn't edit the v2.1 Site correctly.

**Comment by xcomSteveJohnson** [comment]
Fixed now, please check and close this. 

FWIW, this topic like many others, is a `.md` file in `guides/v2.0` and a symlink back to `guides/v2.0` from `guides/v2.1`. If you see this in the future and would like to submit a PR, look in the next-oldest `guides` directory for the `.md` file.

**Comment by DavidLambauer** [comment]
It's fixed as you said! Thanks! If i'll find another one, I'll follow your instructions to add a PR.
