### ISSUE TITLE
Missing curly braces

### ISSUE THREAD

**Issue by shahzisme** [magento/devdocs#1059]
Feedback on page: /guides/v2.1/install-gde/prereq/file-system-perms.html

Under 'Set ownership and permissions for two users' -> 'Step 5: Set ownership and permissions for the shared group'

Step 2 command : find var vendor pub/static pub/media app/etc -type f -exec chmod g+w \;
should be : find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;

**Comment by hostep** [comment]
I believe this will be fixed by: https://github.com/magento/devdocs/pull/1057 ?

**Comment by xcomSteveJohnson** [comment]
@shahzisme This should be fixed now. Please check and close this.

**Comment by shahzisme** [comment]
Thank you guys, it is indeed, fixed :)
