### ISSUE TITLE
Don't have plugin example default to disabled

### ISSUE THREAD

**Issue by scottsb** [magento/devdocs#1065]
The sample `di.xml` code for a new plugin on this page has the plugin disabled:
`/guides/v2.0/extension-dev-guide/plugins.html`

This is likely to confuse people who may copy & paste without noticing that and end up wondering why their new plugin isn't actually working.

**Comment by jcalcaben** [comment]
Thanks for catching this @scottsb ! I have updated the example and removed the disabled property in the example.

The change should be published within the hour.
