### ISSUE TITLE
No Nginx solution mentioned. 

### ISSUE THREAD

**Issue by valugi** [magento/devdocs#1068]
Feedback on page: /guides/v2.1/install-gde/trouble/tshoot_no-styles.html

There is a nginx.conf sample included, even that will not work out of the box.

**Comment by jeff-matthews** [comment]
@valugi, can you please clarify what you mean? Maybe the topic you reference has changed since you opened this issue, but I don't see any references to nginx.

**Comment by valugi** [comment]
@jeff-matthews I do not remember exactly after so many months, but I think the lack of nginx reference was my problem. In the page the solution assumes we all use Apache and of course this is not the case, and this is not the only server supported by M2.

**Comment by jeff-matthews** [comment]
Aha! That makes sense. Thanks for clarifying.

**Comment by jeff-matthews** [comment]
I think the lack of reference is because Magento provides a sample nginx.conf file with the code that handles rewrites. Apache server rewrites require an extra step that nginx does not require.

**Comment by valugi** [comment]
I don't think so because I was using exclusively Nginx with Magento 2 and I got the same issues and to the same debugging page - which I mentioned in the original post - that the provided nginx.conf did not suffice. For the record, about a year ago I was doing an automated install of M2 using only Ansible and M2 CLI tools. I am not sure that this is still relevant since you are now on 2.2.

**Comment by jeff-matthews** [comment]
My apologies @valugi. You're right. I forgot about that part of your description. I'll try and recreate the issue. I have a feeling that it's related to the mode. Thanks for your patience.

**Comment by valugi** [comment]
Thanks.

**Comment by jeff-matthews** [comment]
@valugi, I recreated the "no-styles" scenario in my nginx environment. Neglecting to create a virtual host file as specified [here](https://devdocs.magento.com/guides/v2.2/install-gde/prereq/nginx.html#configure-nginx-ubuntu) seemed to be the cause. Creating/configuring a virtual host seemed to fix my particular issue. 

I'm not sure how likely it is that someone else will fail to configure a virtual host file, but I think I'll add it as a solution just in case. I'll work on a PR and link it to this issue.
