### ISSUE TITLE
Problems with the https certificate?

### ISSUE THREAD

**Issue by diazwatson** [magento/devdocs#1069]
Hey guys, I just noticed this.
<img width="776" alt="common_layout_customization_tasks" src="https://cloud.githubusercontent.com/assets/1080386/24041484/99039d04-0b05-11e7-81af-8ec29f5136a2.png">

Feedback on page: /guides/v2.0/frontend-dev-guide/layouts/xml-manage.html

**Comment by xcomSteveJohnson** [comment]
Thanks. Devdocs has always been an HTTP site. Because we use a custom domain on GitHub pages, HTTPS isn't supported. We're investigating alternatives but meanwhile, if you change the scheme in your browser to `http`, everything will work.

**Comment by diazwatson** [comment]
In case it helps I came to that page clicking on a google result

**Comment by xcomSteveJohnson** [comment]
I expected so. We're also trying to figure out why HTTPS search results are returned.

**Comment by dshevtsov** [comment]
Created an internal ticket MAGETWO-70560

**Comment by jeff-matthews** [comment]
We're working with Magento devops to migrate devdocs.magento.com and docs.magento.com to SSL-enabled hosting by the end of June 2018.

**Comment by t-richards** [comment]
GitHub Pages officially supports HTTPS for custom domains as of this month: 
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

It looks like this has already been configured properly for the Devdocs site.

**Comment by jeff-matthews** [comment]
Yep! Thanks for the reminder.
