### ISSUE TITLE
This is not working as expected checkout_new_step

### ISSUE THREAD

**Issue by sunel** [magento/devdocs#1070]
Feedback on page: /guides/v2.1/howdoi/checkout/checkout_new_step.html

The Template is not getting called  as seen in 2.1.5

**Comment by SerhiyShkolyarenko** [comment]
@sunel thank you for your feedback!
Could you please attach your module here to make sure we are on the same page?

**Comment by sunel** [comment]
The module is created as per the steps give in the doc

**Comment by sunel** [comment]
@SerhiyShkolyarenko Any Update on this.

**Comment by SerhiyShkolyarenko** [comment]
@sunel I unpacked your code, updated sort order to 1 `<item name="sortOrder" xsi:type="string">1</item>` and removed all the generated static files: `rm -rf pub/static/frontend/*`
Then I added a product to cart and went to checkout. Ctrl+F5 may be necessary. I seen a new step added.
![checkout_new_step](https://cloud.githubusercontent.com/assets/15108140/24200848/099e2718-0f17-11e7-9027-0d6790dde032.png)

**Comment by dshevtsov** [comment]
Created a ticket about documentation update - MAGETWO-66538

**Comment by sunel** [comment]
@SerhiyShkolyarenko 
Did u proceed to next step

If not when you proceed to next step the template that is required for the step is not getting called.

Please do check on that  (I have mention in issue description "Template is not getting Called" )

**Comment by sunel** [comment]
@SerhiyShkolyarenko FYI
https://github.com/magento/magento2/issues/8875

**Comment by almarchenko** [comment]
I've added a recommendation to clean cache in http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_new_step.html
(see the note at very end of the doc)

**Comment by sunel** [comment]
I have already did what you have mentioned. Still Its the same. Refer the linked issue.

**Comment by SasiKiranK** [comment]
https://github.com/magento/magento2/issues/8875#issuecomment-316922684 

@sunel Did you try the above fix?

**Comment by jeff-matthews** [comment]
Closing. This doesn't appear to be a documentation-specific issue.
