### ISSUE TITLE
varnish 5 support?

### ISSUE THREAD

**Issue by valugi** [magento/devdocs#1073]
Feedback on page: /guides/v2.0/config-guide/varnish/config-varnish-magento.html
In general your docs are very specific, using Apache (neglecting Nginx) or using very specific versions like 3 and 4 for Varnish. How about Varnish 5 - current version - is that supported? From the admin I see no option to export a specific version 5 vcl but this does not mean that is not supported right?

**Comment by xcomSteveJohnson** [comment]
Varnish 5 is not supported at this time.

**Comment by valugi** [comment]
@xcomSteveJohnson thanks for the update. Any roadmap for it?

**Comment by xcomSteveJohnson** [comment]
[Here](https://github.com/magento/devdocs/blob/develop/guides/v2.2/install-gde/system-requirements-tech.md#magento-can-utilize-the-following-technologies) are the draft system requirements for Magento 2.2, where Varnish 5 is listed. I do not know the release date, however.

**Comment by valugi** [comment]
@xcomSteveJohnson thx

**Comment by tanberry** [comment]
Hi @valugi , agreed we need to be cautious in our docs with stating specific version numbers. We'll try to do some clean-up there. I'm closing this ticket now; please reopen if you are not satisfied. Thanks!
