### ISSUE TITLE
activate full page caching using Varnish from command line

### ISSUE THREAD

**Issue by valugi** [magento/devdocs#1074]
Feedback on page: /guides/v2.0/config-guide/varnish/config-varnish-magento.html

Is there a way to activate the Varnish use using the command line, not the admin interface?
I am building an Ansible script that automatises the installation and configuration of the M2EE and this step seems that has to be done manually. I would prefer a command line action than changed direct values in the mysql, but maybe you have other suggestions.

**Comment by xcomSteveJohnson** [comment]
Have you tried asking this on stackexchange, Magento forums, or the Magento 2 GitHub?

**Comment by valugi** [comment]
I will but if someone here has an idea, I appreciate it.

**Comment by hostep** [comment]
@valugi: If you are willing to install the [n98-magerun2 utility](https://github.com/netz98/n98-magerun2), you can probably use its [`config:set` command](https://github.com/netz98/n98-magerun2#set-config) to accomplish what you are trying?
Or maybe the [`script` command](https://github.com/netz98/n98-magerun2#n98-magerun-script) if you want to use `config:set` multiple times using a single call.

It is installable using `composer` btw (which isn't mentioned in the readme).

**Comment by valugi** [comment]
@hostep Thx, I will take a look.

**Comment by jeff-matthews** [comment]
@valugi: Did you successfully automate Varnish configuration via the CLI?  If so, please share details  so I can update the docs.

**Comment by valugi** [comment]
@jeff-matthews Hi
unfortunately I did not. I do not want to use external utilities and from M2 CLI is not possible. 

I am following these manual steps to activate it.

- Log in to the Magento Admin as an administrator.
- Click STORES > Configuration > ADVANCED > System > Full Page Cache
- From the Caching Application list, click Varnish Caching
- Click Save Config.

**Comment by hostep** [comment]
Magento 2.2 introduces some [new built-in commands to configure settings](http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.html#config-cli-config-set), I haven't played with those yet, but by using those you will probably be able to accomplish this.

**Comment by jeff-matthews** [comment]
@valugi: Try this command:

`bin/magento config:set --scope=default --scope-code=0 system/full_page_cache/caching_application  2`

**Comment by davidalger** [comment]
We are using the following two commands from n98-magerun2 (which we install as part of a standard ansible play under the alias `mr`) to enable this:

        mr config:set system/full_page_cache/caching_application 2
        mr config:set system/full_page_cache/ttl 604800

Given the introduction of native commands in 2.2, we'll likely switch to those at some point, but in the meantime n98-magerun2 works just fine.

**Comment by jeff-matthews** [comment]
I just realized that `config:set` is only available in v2.2, but you can accomplish the same thing using this:

```
mysql -u root -p -D magento -e "INSERT INTO core_config_data ( scope, scope_id, path, value ) VALUES ( 'default', '0', 'system/full_page_cache/caching_application', '2') ON DUPLICATE KEY UPDATE value = 2;"
```

**Comment by jeff-matthews** [comment]
I added both methods of CLI activation mentioned in this thread to the docs (i.e., v2.0, 2.1 = mysql & v2.2 = bin/magento).

**Comment by valugi** [comment]
@jeff-matthews Thanks for the suggestions, I knew about the mysql solution (see my original post) but I was looking for the CLI solution. It is good that is all possibilities are documented now.
