### ISSUE TITLE
404 not found for multi store

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/devdocs#1075]
Hello,

I did step by step : 
http://devdocs.magento.com/guides/v2.0/config-guide/multi-site/ms_websites.html
and : 
http://devdocs.magento.com/guides/v2.0/config-guide/multi-site/ms_apache.html

I have 2 websites and 3 Store views : 
**Main website (code: base) /  Main Store / Main Store View (code: default)
Europe website (code: europe) /  Europe Store / English Store View (code: english)
Europe website (code: europe) /  Europe Store / French Store View (code: francais)**

**Base url is : my-domain.com
Europe Website base url is europe.my-domain.com**

In etc/httpd/conf/httpd.conf I added : 
```
<VirtualHost *:80>
    ServerName my-domain.com
    DocumentRoot /var/www/vhosts/my-domain.com/httpdocs/pub/
</VirtualHost>

<VirtualHost *:80>
    ServerName europe.my-domain.com
    DocumentRoot /var/www/vhosts/my-domain.com/httpdocs/pub/
    SetEnv MAGE_RUN_CODE "europe"
    SetEnv MAGE_RUN_TYPE "website"
</VirtualHost>
```
I also uncommented NameVirtualHost *:80 in etc/httpd/conf/httpd.conf.

I restarted Apache

In my host file I have : 
**< ip address > europe.my-domain.com**

But I get 404 not found errors : 
**Not Found

The requested URL /francais/ was not found on this server.
Apache Server at europe.my-domain.com Port 80**

Access to admin is OK, access to base store view : my-domain.com is OK.

I'm on a Centos 6.x server, with Plesk and running Magento 2.1.5

Any idea on what I missed, or what I should do to solve this please ?

Best regards,
David

**Comment by xcomSteveJohnson** [comment]
I didn't try this using SSL but it should work. Your host file isn't complete. It must also have the IP address of your domain like this:

```
10.235.32.11 french.mysite.mg
```
Also, it looks like you're trying to go to two store views with the same website code and I don't think that will work. The tutorial shows how to go to a French store view on a French website, for example; not a German store view on a French website.

Make sure you clean the cache before you try to access the site.

**Comment by ShapesGraphicStudio** [comment]
Thank you for your answer.

Yes, sorry, < ip address > did not appear in th first post < & > were hiding it without a space between elements.

http://my-domain.com 
is working

http://europe.my-domain.com/francais
http://europe.my-domain.com/english
are not

So what you mean is I should try to delete one of the 2 store views, Europe website ?

**Comment by ShapesGraphicStudio** [comment]
I juste deleted : 
**Europe website (code: europe) / Europe Store / French Store View (code: francais)**

Cleared browser cache (Magento cache is turned off in admin), and still have no access to : 
http://europe.my-domain.com/english

**Comment by xcomSteveJohnson** [comment]
You did these two steps?

http://devdocs.magento.com/guides/v2.1/config-guide/multi-site/ms_websites.html#multi-storecode-baseurl

http://devdocs.magento.com/guides/v2.1/config-guide/multi-site/ms_websites.html#step-7-change-the-default-store-views-base-url

**Comment by ShapesGraphicStudio** [comment]
Add Store Code to Urls is set to yes in default config.

Base URLs (secure and not secure are set to : 
http://my-domain.com/ & https://my-domain.com/ in default config
http://europe.domain.com/ & https://europe.domain.com/ in Website Europe config

Store views Base URLs are set to Websites Values.

**Comment by xcomSteveJohnson** [comment]
Sorry you're having this trouble. This is a hard thing to do and it's difficult to debug like this. The only other suggestion I can make is for you to _not_ use `pub` in your Virtual Host definition. I don't know if it'll make a difference but I do not recall one way or the other if I did that when I set it up. 

IOW, try this:

```
<VirtualHost *:80>
    ServerName my-domain.com
    DocumentRoot /var/www/vhosts/my-domain.com/httpdocs/
</VirtualHost>

<VirtualHost *:80>
    ServerName europe.my-domain.com
    DocumentRoot /var/www/vhosts/my-domain.com/httpdocs/
    SetEnv MAGE_RUN_CODE "europe"
    SetEnv MAGE_RUN_TYPE "website"
</VirtualHost>
```

See if it works. I'll set up a system as soon as I can and will get back to you.

**Comment by ShapesGraphicStudio** [comment]
Thanks for the effort, I know it's a hard thing to debug without being able to put your hands in it.

I also tried to without **pub**, but I have the same error.
In the first time I forgot to add **pub**, and I thought I would solve it by adding it..

**Comment by xcomSteveJohnson** [comment]
OK, keep trying. Double-check everything. I'll get back to you as soon as I can. I have gotten this to work a couple of times, but don't have a system set up at the moment.

**Comment by ShapesGraphicStudio** [comment]
Weird thins is that when I try to get to : 
http://my-domain.com/english/
I get redirected to : 
http://europe.my-domain.com/english/?SID=123456789

So something seems to be connected right.

Regarding the 404 error, I get the browser page, not the Magento 404.

**Comment by ShapesGraphicStudio** [comment]
Yes, I tried multiple times, and rechecked, but can't seem to find out waths going on.

I'll repeat all details, so you can have a more accurate view.

**1st Website :** 
name : Website USA
code : base
order : 0
Default Store 1st Website : 
name : Boutique USA
Default Store View 1st Website : 
name : English
code : default
order : 0

**2nd Website :** 
name : Website Europe
code : europe
order : 1
Set as default : no
Default Store 2nd  Website : 
name : Boutique Europe
Default Store View 2nd Website : 
name : English
code : english
order : 1

**Comment by ShapesGraphicStudio** [comment]
I did nothing regarding the first step, as the categories stay the same between websites.

**Comment by ShapesGraphicStudio** [comment]
Is there any difference for Step 2: Create Apache virtual hosts between creating europe.my-domain.com where I manage dns in my registrar dashboard or in etc/hosts ?

I first created it in the registrar dashboard, but when I deleted the entry, to have it just in etc/hosts, I have no more access at all, on europe.my-domain.com browser can't find address or server...

Looks like the changes made in etc/hosts are not applied.

**Comment by xcomSteveJohnson** [comment]
AFAIK, if you have `etc/hosts`, this overrides anything in DNS because it sets up a static route from your machine to that IP. Also, as you know, a DNS update can take a pretty long time.

What is is your `/etc/resolv.conf`? If you modified it, you should probably comment out those changes.

**Comment by ShapesGraphicStudio** [comment]
I did not touch /etc/resolv.conf

It has : 
nameserver 127.0.0.1
nameserver xxx.xxx.xx.xx
search ovh.net

But it really seems like the changes made in etc/hosts are not working.

**Comment by ShapesGraphicStudio** [comment]
If I add back the dns entries at my registrar, access to server is OK again, but back to the : 
Not Found
The requested URL /europe was not found on this server.
if I try to get http://europe.my-domain.com/europe

http://europe.my-domain.com/ shows Plesk defaukt web server page.

That's something I get when I have multiple domains pointing to the webserver and I did not create the aliases. 

I'm getting crazy on this..

Maybe I should create the aliases.. ?

**Comment by ShapesGraphicStudio** [comment]
Well, it seems like it did the trick, I created europe subdomain with httpdos document root, and I can access http://europe.my-domain.com/europe/ (I changed english to europe to be sure I did not have a conflict there.

Must be because of the way Plesk is handling the domains, overriding apache.. ?

**Comment by ShapesGraphicStudio** [comment]
Seems to work fine, only thing I do not find is Theme configuration.

Going in Content > Design > Configuration, I only see the default website, but not the one I created..
Any idea please ?

**Comment by ShapesGraphicStudio** [comment]
OK, I figured this out ;-)

I was missing : 
**php bin/magento indexer:reindex**
command

Thanks again for your help and concern.

Best regards,
David

**Comment by xcomSteveJohnson** [comment]
@ShapesGraphicStudio Oh good, I'm glad. I was out of the office for a while. Your guess is as good as mine about domain resolution. You're probably correct.
