### ISSUE TITLE
DevDocs Page Not Found

### ISSUE THREAD

**Issue by sixtonspacefly** [magento/devdocs#1079]
On page: http://devdocs.magento.com/guides/v2.1/cloud/access-acct/first-time-setup_template.html, link for the next article http://devdocs.magento.com/guides/v2.1/cloud/before/before-setup-env-1_get-started.html returns "Page Not Found" error.

**Comment by xcomSteveJohnson** [comment]
@sixtonspacefly Should be fixed now. Please check and close this.

**Comment by sixtonspacefly** [comment]
Works. Thank you.
