### ISSUE TITLE
devbox unit testing documentation improvement suggestion

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#1101]
Feedback on page: /guides/v2.1/install-gde/docker/docker-phpstorm-test.html

How about adding this post answer to the documentation of command line.
http://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process

**Comment by jcalcaben** [comment]
Thanks for the suggestion @user3748173 !

I've created an internal ticket for this issue.

**Comment by jcalcaben** [comment]
The command for detaching from a docker container while leaving it running has been added to the page. Thanks!
