### ISSUE TITLE
Suggestion: Please provide dates on release notes

### ISSUE THREAD

**Issue by AidanThreadgold** [magento/devdocs#1102]
As a small suggestion, I think it'd be particularly helpful if you provided the date a version was released on the release notes themselves.

**Comment by jfrontain** [comment]
Great suggestion -- I am following up now. Thanks!

**Comment by z4qx** [comment]
I Agree!

**Comment by jfrontain** [comment]
Excellent! We will add the date on which we publish both the code and release notes to our next 2.x patch release notes. Thanks for the suggestion.

**Comment by AidanThreadgold** [comment]
Awesome! Thanks @jfrontain

**Comment by jfrontain** [comment]
@AidanThreadgold, thanks again for your suggestion. I've added a string to identify the date we last updated the release notes to the most recent release information files: the 2.1.6 Release Notes and recent Technical Bulletin. Check them out, and thanks again. Closing now.

**Comment by pantaoran** [comment]
I want this as well, I think it's very important.

However, on the recent (I'm trying to find out how recent exactly) 2.1.7 release notes there is again no publication date. 

It seems to me like you guys did it once for 2.1.6 but then it wasn't added to a process or template for the future. @jfrontain Can you please make sure that the date is added in all future release notes?

**Comment by jfrontain** [comment]
Good catch! Will add right now. Thanks again.

**Comment by jfrontain** [comment]
Guys, I have added the date string back into the 2.1.7 notes and republished. I will do my best to make sure all future notes have this information. Our policy is to change this date to reflect content changes (that is, we won't change the date if we simply fix a broken link, but only if we change technical content). Thanks again!

**Comment by hostep** [comment]
@jfrontain: I don't think this is what @AidanThreadgold was asking. He wants to know the exact date when a new version of Magento2 was published by Magento, this is a fixed date which never changes.
You are now adding the date when the release note page was last updated (even though that info is also very useful).

**Comment by pantaoran** [comment]
@hostep ist exactly right, and I agree with this.
Both dates should be present, like so:

_Release date: 2017-06-01
Page updated: 2017-06-03_

**Comment by jfrontain** [comment]
Just added two dates: Patch released and release notes revised.

**Comment by pantaoran** [comment]
Thanks for your efforts! However, I'm not seeing it.
We are talking about this page, correct? https://github.com/magento/devdocs/commits/develop/guides/v2.1/release-notes/ReleaseNotes2.1.7CE.md

**Comment by jfrontain** [comment]
I've published it, but it hasn't yet shown up on our public website. I'm sure it will soon. Thanks for your patience and thanks again for your excellent suggestion.

**Comment by hostep** [comment]
@jfrontain: thanks, much better now :)

**Comment by jfrontain** [comment]
Thank you for your careful reading of these notes and your excellent feedback. And please keep the suggestions coming -- we might not respond as quickly as we'd like, but we try to be prompt. :-) We want to make these Release Notes the most helpful tool we can.
