### ISSUE TITLE
Memcache and why it is preferred over Redis (sessions)

### ISSUE THREAD

**Issue by LukeHandle** [magento/devdocs#1107]
Feedback on page: /guides/v2.1/config-guide/memcache/memcache.html

> We recommend you use memcached for session storage. The Redis session handler in the phpredis PHP extension does not support session locking, which might cause issues with distributed systems and applications that rely on Ajax.

I don't see a reference to this issue on page: /guides/v2.1/config-guide/redis/redis-session.html - are we able to verify this issue and update the other page if confirmed. Linking to an appropriate bug report is available? ( https://github.com/phpredis/phpredis/issues/37 ? ) `Cm_RedisSession` seems to say it does "optimistic" locking - so I guess it makes an _attempt_ anyway?

If memcache is the recommendation for sessions, can we get this written in more places (eg.  /guides/v2.1/install-gde/system-requirements-tech.html )?

**Comment by dougkm** [comment]
I believe the session locking issue with Redis was addressed so this section may be outdated.

**Comment by davidalger** [comment]
FWIW, we deploy all our sites with redis session over at Classy Llama and have for a couple years with great success. :)

**Comment by aoldoni** [comment]
In my perspective, this is now addressed in the documentation.

- See http://devdocs.magento.com/guides/v2.0/config-guide/redis/config-redis.html - where it says: "Starting in Magento 2.0.6, you can use either Redis or memcached for session storage. Earlier issues with the Redis session handler and session locking have been resolved.".
- See http://devdocs.magento.com/guides/v2.0/config-guide/memcache/memcache.html - where it says: "Refer to Why Redis is better for a list of advantages to using Redis."

I believe this can be closed.

**Comment by jeff-matthews** [comment]
I agree. Thanks @aoldoni!

**Comment by LukeHandle** [comment]
To clarify here though, the reasons given under "Refer to Why Redis is better for a list of advantages to using Redis" are not really addressing the session storage more than just "Redis supports on-disk save and master/slave replication".

\- Or am I being overly fussy now :D
