### ISSUE TITLE
Please add info about resolving image issues using catalog:images:resize after upgrade to 2.1.6 to the release notes

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1108]
Feedback on page: /guides/v2.1/release-notes/ReleaseNotes2.1.6CE.html

Please include the following paragraph into the page:
> Please run `bin/magento catalog:images:resize` in the `magento2` directory after upgrading, if you encounter any issues with images on frontend.

(as requested on the [magento/magento2 issue #9275](https://github.com/magento/magento2/issues/9275#issuecomment-295532355))

**Comment by rip057** [comment]
personally i feel this, along with setup:di:compile and setup:static-content:deploy should all be automatically run by the setup:upgrade, but at least a mention for all the image problems, i totally agree.

**Comment by jfrontain** [comment]
Thanks for the suggestions! I am adding a note to the 2.1.6 CE and EE release notes re your suggestion, @korostii, and will pass on your observation about setup::upgrade to our dev team, @rip057. Thanks again.

**Comment by jfrontain** [comment]
Published revised release notes on April 24, 2017.  Thanks for the information!
