### ISSUE TITLE
No mention of DNS setup to enable Fastly

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1110]
Feedback on page: /guides/v2.1/cloud/access-acct/fastly.html

There is a txt record that needs to be deployed to the DNS provider in order to get Fastly to work.

This step is not described here.

**Comment by tanberry** [comment]
Thanks for the heads up, @dougkm. We will get that added.

**Comment by lorikrell** [comment]
Resolved issue - available at this link. http://devdocs.magento.com/guides/v2.1/cloud/live/go-live-checklist.html#fastly-tls. Verified with Platform.sh and Fastly.
Thank you for your feedback!
