### ISSUE TITLE
Command name change with mcc-101.6.0

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1125]
Feedback on page: /guides/v2.1/cloud/live/sens-data-initial.html

From: Yevgenii Yevtushenko

"seems the app:config:scd-dump was renamed in mcc-101.6.0 and now for generating config.local.php you have to use magento-cloud:scd-dump command. "

**Comment by tanberry** [comment]
Thanks @dougkm ; this was fixed this morning by PR https://github.com/magento/devdocs/pull/1123
I'll close this issue, but please reopen if you have further eits, etc.
