### ISSUE TITLE
SOAP API I din't get proper documentation 

### ISSUE THREAD

**Issue by allamsettiramesh** [magento/devdocs#1129]
Feedback on page: /guides/v2.0/soap/bk-soap.html

ActuallyI din't get proper documentation in M2 like M1. In M1 have proper documentation what are the parameters to should pass. 
For example i want fetch customer details according to email or customer id , here i didn't get exact way

**Comment by keharper** [comment]
Unfortunately, we don't currently plan to provide documentation in a SOAP format. You can use the REST Swagger documentation to extrapolate the information you need. In the sample you asked about, `GET /V1/customers/:customerId` would be the corresponding call in REST. 

http://devdocs.magento.com/swagger/

**Comment by allamsettiramesh** [comment]
@keharper. Actually We developed product with SOAP in magento 1 as like we are planning on magento 2 SOAP.
 I am facing issue with below script.

    `<?php
    ini_set('display_errors', 1);
    $soapTokenUri = 'http://127.0.0.1/magento2011/soap/default?wsdl&services=integrationAdminTokenServiceV1';
    $soapResourceUri = 'http://127.0.0.1/magento2011/soap/default?wsdl&services=cmsBlockRepositoryV1';
    $username = 'soapadmin';
    $password = 'test@123';
    $options = ['soap_version' => SOAP_1_2,
                'trace' => 1,
                'connection_timeout' => 120,
               ];
    // create client and get token response using username and password
    $cli = new SoapClient($soapTokenUri, $options);
    $response = $cli->integrationAdminTokenServiceV1CreateAdminAccessToken(['username' => $username,
                                                                            'password' => $password]);
    $token = $response->result;`

Error is: 

  `
Fatal error: Uncaught SoapFault exception: [SOAP-ENV:Server] SoapServer::SoapServer(): Invalid parameters in /var/www/html/magento2011/test.php:14 Stack trace: #0 /var/www/html/magento2011/test.php(14): SoapClient->__call('integrationAdmi...', Array) #1 {main} thrown in /var/www/html/magento2011/test.php on line 14`

**Comment by allamsettiramesh** [comment]
@keharper, I am getting same issue when am trying with CURL.
error: "SOAP-ENV:ServerSoapServer::SoapServer(): Invalid parameters"

script: 
   ` $data_string = file_get_contents('request.xml');
    //echo "<pre>"; print_r($data_string);
    $ch = curl_init('http://127.0.0.1/magento2011/soap/default?services=integrationCustomerTokenServiceV1');
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/soap+xml; charset=utf-8;
                                                action="integrationCustomerTokenServiceV1CreateCustomerAccessToken"',
                                                'Content-Length: ' . strlen($data_string)));
    $result = curl_exec($ch);`
   
request.xml file

  `<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://magento2.ce/index.php/soap/default?services=integrationCustomerTokenServiceV1">
<env:Body>
<ns1:integrationCustomerTokenServiceV1CreateCustomerAccessTokenRequest>
<username>soapadmin</username>
<password>test@1234</password>
</ns1:integrationCustomerTokenServiceV1CreateCustomerAccessTokenRequest>
</env:Body>
</env:Envelope>
`

**Comment by keharper** [comment]
@allamsettiramesh Before I ask Development to help out with this, would you confirm that `soapadmin` is a previously-defined admin account? (If it's not the `admin` account renamed, then it would probably have to be created from the CLI.)

Also, is the truncated part of the Error resolve to `integrationAdminTokenServiceV1CreateAdminAccessToken`?

**Comment by keharper** [comment]
I was able to get a token using a SOAP client.

http://b2b2.vg/soap/default?services=integrationAdminTokenServiceV1

Request
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://b2b2.vg/soap/default?services=integrationAdminTokenServiceV1">
   <soap:Header/>
   <soap:Body>
      <def:integrationAdminTokenServiceV1CreateAdminAccessTokenRequest>
         <username>admin</username>
         <password>123123q</password>
      </def:integrationAdminTokenServiceV1CreateAdminAccessTokenRequest>
   </soap:Body>
</soap:Envelope>

Response
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://b2b2.vg/soap/default?services=integrationAdminTokenServiceV1">
   <env:Body>
      <ns1:integrationAdminTokenServiceV1CreateAdminAccessTokenResponse>
         <result>al0jfo8pod1rigymcoqxlw5269wy3nn0</result>
      </ns1:integrationAdminTokenServiceV1CreateAdminAccessTokenResponse>
   </env:Body>
</env:Envelope>

**Comment by allamsettiramesh** [comment]
@Keharper, thanks for solution i able to generate token. Actually i am get customer details with customerId but i cant create customer with save method.

 its shows  "Un-authorized Req:SOAP-ERROR: Encoding: object has no 'customer' property".

   `    <?php
        require('vendor/zendframework/zend-server/src/Client.php');
        require('vendor/zendframework/zend-soap/src/Client.php');
        require('vendor/zendframework/zend-soap/src/Client/Common.php');

        ini_set('display_errors', 1);
        //echo "test"; exit;
        $request = new SoapClient("http://127.0.0.1/magento2011/soap/?wsdl&services=integrationAdminTokenServiceV1");
        $token = $request->integrationAdminTokenServiceV1CreateAdminAccessToken(array("username"=>"admin","password"=>"admin@123"));
        //$token = $request->integrationAdminTokenServiceV1CreateAdminAccessToken(array("username"=>"soapadmin","password"=>"admin@1234"));
        //echo "<pre>"; print_r($token->result); exit;
        $opts = array(
            'http'=>array(
                'header' => 'Authorization: Bearer '.$token->result
            )
        );
        //echo "<pre>"; print_r($opts); exit;
        $serviceArgs = array("customerId" => 1);

        $customerparams = array('email' => 'customer-mail@example.org',
                                'firstname' => 'Dough',
                                'lastname' => 'Deeks',
                                'password' => 'test@123',
                                'website_id' => 1, 'store_id' => 1, 'group_id' => 1);

        $wsdlUrl = 'http://127.0.0.1/magento2011/soap/default?wsdl&services=customerCustomerRepositoryV1';
        $context = stream_context_create($opts);
        try{
            $soapClient = new \Zend\Soap\Client($wsdlUrl);
            $soapClient->setSoapVersion(SOAP_1_2);
            $soapClient->setStreamContext($context);
            //$soapResponse = $soapClient->customerCustomerRepositoryV1GetById($serviceArgs);
            $soapResponse = $soapClient->customerCustomerRepositoryV1Save($customerparams);
            //$soapResponse = $soapClient->customerCustomerRepositoryV1GetList();
            echo "<pre>"; var_dump((array) $soapResponse);
        }catch(Exception $e){
            echo 'Un-authorized Req:'.$e->getMessage();
        }
    ?>
`

**Comment by allamsettiramesh** [comment]
@Keharper, Can you please provide the solution so we can close this issue

**Comment by keharper** [comment]
@allamsettiramesh This works, using the fields in your example.

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://b2b2.vg/soap/default?services=customerAccountManagementV1">
   <soap:Header/>
   <soap:Body>
      <def:customerAccountManagementV1CreateAccountRequest>
         <customer>
            <email>howdy@example.com</email>
            <firstname>John</firstname>
            <lastname>Smith</lastname>
            <storeId>1</storeId>
            <websiteId>1</websiteId>   
         </customer>
         <password>Password1</password>
      </def:customerAccountManagementV1CreateAccountRequest>
   </soap:Body>
</soap:Envelope>
```

Response:
```xml
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://b2b2.vg/soap/default?services=customerAccountManagementV1">
   <env:Body>
      <ns1:customerAccountManagementV1CreateAccountResponse>
         <result>
            <id>5</id>
            <groupId>1</groupId>
            <createdAt>2017-05-10 14:45:53</createdAt>
            <updatedAt>2017-05-10 14:45:53</updatedAt>
            <createdIn>Default Store View</createdIn>
            <email>howdy@example.com</email>
            <firstname>John</firstname>
            <lastname>Smith</lastname>
            <storeId>1</storeId>
            <websiteId>1</websiteId>
            <addresses/>
            <disableAutoGroupChange>0</disableAutoGroupChange>
            <extensionAttributes>
               <companyAttributes>
                  <customerId>5</customerId>
                  <companyId>0</companyId>
                  <status>1</status>
               </companyAttributes>
            </extensionAttributes>
         </result>
      </ns1:customerAccountManagementV1CreateAccountResponse>
   </env:Body>
</env:Envelope>
```

**Comment by keharper** [comment]
Oops, I skipped the `group_id`, but that's not an essential parameter.

**Comment by allamsettiramesh** [comment]
@keharper, thank you very much
