### ISSUE TITLE
error on extension-dev-guide: links to github give 404

### ISSUE THREAD

**Issue by ebaschiera** [magento/devdocs#1131]
Feedback on page: /guides/v2.0/extension-dev-guide/cli-cmds/cli-howto.html

Hi,
the links to github on that page (sample-module-command and README.md) don't work, I get a 404 error.
Apparently the sample-module-command repository is no more available on GitHub.

Thanks.
Best Regards.

**Comment by jcalcaben** [comment]
Hi @ebaschiera 
Thanks for pointing that out. I will investigate why the repo is unavailable.

**Comment by keharper** [comment]
@ebaschiera The repo has been taken offline. See https://github.com/magento/devdocs/issues/1133 for more information.
