### ISSUE TITLE
Controller Methodes

### ISSUE THREAD

**Issue by Quastenflosser** [magento/devdocs#1132]
Feedback on page: /guides/v2.1/extension-dev-guide/routing.html

I think the description for the methods inside the controller is wrong. 
I tried with Magento 2.1.5 and could not use xxxAction methods. The only thing working is the execute method.

Has this changed in 2.1? 
Why was the better way to do it with Action methods given up?
Now every action needs a seperate controller class and file. This is ugly.

**Comment by jcalcaben** [comment]
This issue has been addressed in #1161

Thanks @Quastenflosser for reporting it and @VincentMarmiesse for the PR!
