### ISSUE TITLE
Please add info about dev:urn-catalog:generate command to the "URN schema validation" page

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1136]
Feedback on page: /guides/v2.0/extension-dev-guide/build/XSD-XML-validation.html
Feedback on page: /guides/v2.0/config-guide/cli/config-cli-subcommands-urn.html

**Backround:**
It is possible to defer the schema validation to PhpStorm IDE, but it requires additional setup because XSD references in XML files that used relative paths which the PhpStorm is unable to resolve automatically.

However, there exists a very useful command which allows to generate the mappings required by IDE with little effort:
`bin/magento dev:urn-catalog:generate .idea/misc.xml`

When you edit a lot of various configuration files, seeing validation errors as soon as you type speeds up the development significantly. 

**Suggestion:**
IMHO a highlighted brief note about this command should be added to the [PHP Developer Guide > URN schema validation](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/build/XSD-XML-validation.html) page with a link to the page containing detailed info about it (which already exists but happens to be part of  a different guide: [Configuration Guide > URN highlighter](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-urn.html) ).

**Comment by michizhou** [comment]
I would be willing to take on this issue! #SQUASHTOBERFEST

**Comment by jeff-matthews** [comment]
Thanks for volunteering @michizhou!
