### ISSUE TITLE
Integration testing - Do I need to worry about cache when writing Magento 2 extensions?

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#1137]
Feedback on page: /guides/v2.0/test/integration/integration_test_setup.html

In the documentation is a sentence "The test execution will start much quicker, but as a consequence the developer has to flush the cache and the database when needed manually." I have a question about that. There is said that in integration tests cache has to be flushed manually (when disabled), but what about production websites: 
Should the module developer clean the cache after the code has run inside the code or not? 
How to test what happens, when cache exists and when does it exist? 
_(Maby adding a link where it is explained, to make that doc more clearer - Do I need to worry about cache in production websites when writing modules?)_

**Comment by korostii** [comment]
I'm sorry, but I am not completely sure I fully understood your concerns. However, I'll attempt to cover your questions as much as I can. 

Why would you run the tests on the production website?
Tests bring heavy load, wouldn't you want to run them in the staging environment instead?
Or did you mean production _mode_?

Regarding "when writing modules": in my experience having caches on saves you more time than the time spent on occasionally flushing them, especially if you're doing something frontend-specific. That's during development.

If you're worried that Magento2 caches won't play nice with your module when it's placed in a production website though... That's a valid concern. 
At the very least, I'd recommend that you read up the section of the devdocs explaining how the FPC works:
http://devdocs.magento.com/guides/v2.0/config-guide/cache/cache-priv-over.html

**Comment by user3748173** [comment]
Yes! I exactly I am worried about that Magento2 caches won't play nice with the module I am creating,  when it's placed in a production website. 

I would like to know: if there are any design patterns or any way to test my module against issues that cache might cause. 

Should I clean the cache programmatically after I have imported categories or products programmatically to Magento 2 by custom module?

**Comment by korostii** [comment]
Well the Magento's own behavior in such cases is the following: `invalidate` the cache and leave the cache flushing up to the user (a yellow alert is shown instead). Thus I assume it should be okay for you to do the same in your module.

Idea is that each additional cache flush has some impact on the performance of a large website, so the admin might want to edit multiple sections, maybe do some corrections and then clean the cache himself and just once. 

And [here's a detailed tutorial](https://www.atwix.com/development/managing-cache-programmatically/ ) on managing caches programmatically if you decide to follow that path.
