### ISSUE TITLE
Login name not specified for PuTTY SSH Tunnel

### ISSUE THREAD

**Issue by RedAtRareCandy** [magento/devdocs#1139]
Feedback on page: /guides/v2.1/install-gde/docker/docker-phpstorm-prereq.html

Please can you update the SSH Tunnel steps for PuTTY to include the addition of the username for the session in PuTTY? Or advise the username on that page for when they are prompted?

I suggest adding user "magento2" to PuTTY category:
Connection > Data > Login details > Auto-login username

**Comment by jerrylopez** [comment]
@RedAtRareCandy opened a PR adding this missing step

**Comment by tanberry** [comment]
Thanks so much to both of you, @RedAtRareCandy and @jerrylopez ! Will merge soon, thanks again for the help!

**Comment by RedAtRareCandy** [comment]
Thanks guys, just had a look and the merge looks good! I appreciate that :)
