### ISSUE TITLE
Help with writing Plugin, example in docs doesn't work

### ISSUE THREAD

**Issue by rparsi-commer** [magento/devdocs#1145]
Referring to
[http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html)

I followed the explanation, wrote Plugin that uses "around" for
\Magento\Catalog\Block\Navigation "getCategoryUrl" method.

My Plugin doesn't get invoked/used in any way.
I verified by intentionally throwing an exception in my code, page loads without error message.

I just need to know how to override the category url value.

**Comment by jcalcaben** [comment]
A few things to check:

* Is your plugin declared correctly in the `di.xml` file?
* Is your around method called `aroundGetCategoryUrl`
* Is the first method argument of type `\Magento\Catalog\Block\Navigation`?

**Comment by rparsi-commer** [comment]
@jcalcaben "Yes" to all of the above questions.

I copied my di.xml to this gist (code is in employers private repo so can't give you access):
https://gist.github.com/rparsi-commer/4a70e18aee5bcd1eb849f4f5905483bf

After each change (di.xml or php code) I run:
php bin/magento cache:clean
php -d memory_limit=-1 bin/magento setup:di:compile

I've also run:
php -d memory_limit=-1 bin/magento setup:upgrade

just in case.

**Comment by jcalcaben** [comment]
I will ask an internal developer to review the documentation to make sure there is no missing information.

**Comment by korostii** [comment]
@rparsi-commer,

Just a couple more obvious things that might've been overlooked:
- Is your module enabled and working in general?
- Where have you placed the `di.xml` file (relative to the module root)?

A bit off-topic, but as long as you don't do any changes to your `/Setup/*.php` scripts (see [here](http://inchoo.net/magento-2/setup-scripts-magento-2/) for mor info on those) and bump module version, you can skip the `setup:upgrade` part.
Besides, _if you're running in development mode_, you can just delete `var/di` and `var/generation` instead of running `setup:di:compile` and all the required files will get re-generated automatically.

**Comment by rparsi-commer** [comment]
@korostii Yes it's enabled and working.  My module adds a custom attribute to the Category entity, and makes the attribute a part of the category form (admin view), allowing user to set a value (boolean).

My `di.xml` is in my module's `etc` directory.
So full path is `app/code/Commer/Categories/etc/di.xml` where `Commer` is vendor name (in fact a short name for my employer/company) and `Categories` is the module name (in that this custom module will take care of all our custom Category entity management).

I have tried placing breakpoints in the core magento2 Category module (the places where I think the category url is generated) but none of them get triggered.

I'm at a total loss as what specific `app/code/Magento/Catalog` code generates the Category url.
I'm using the default theme, and have not modified or customized any css/js, etc.

Though the intention is to make the Category url something like '#' if my custom attribute has
a value of 'false'.

**Comment by korostii** [comment]
I think I might now what's happening
As far as I know, the default theme('luma') renders the top navigation using a different block called [`\Magento\Theme\Block\Html\Topmenu`](https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Theme/Block/Html/Topmenu.php).
And the category URL is generated by a... _(please don't laugh)_ plugin class [`\Magento\Catalog\Plugin\Block\Topmenu`](https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Catalog/Plugin/Block/Topmenu.php#L157) which in turn calls [`Magento\Catalog\Helper\Category::getCategoryUrl()`](https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Catalog/Helper/Category.php#L127). 

If I were you, I'd try plugging into the helper, because otherwise you'd probably need to replace the whole `\Magento\Catalog\Plugin\Block\Topmenu` plugin class with your own.

**Comment by rparsi-commer** [comment]
@korostii I had tried making a Plugin for `\Magento\Catalog\Helper\Category` before, didn't work.
I'm trying again now just to be sure.
So what do you recommend I do to intercept `getCategoryUrl` regardless of the theme (default or otherwise)?

**Comment by korostii** [comment]
Well, if you want "regardless", maybe you just need a plugin after\around `Magento\Catalog\Model\Category::getUrl()`?

**Comment by rparsi-commer** [comment]
@korostii My Plugin that does "around" on `\Magento\Catalog\Helper\Category` `getCategoryUrl` seems to be working.  It appears I need to wipe the cache and redeploy static content in order for my plugin to work as expected.

I think the docs should be updated with information related to Plugins that intercept code dealing with the frontend.

Thanks for the help, very much appreciated.

**Comment by rparsi-commer** [comment]
@korostii Sorry to keep bothering you but I'm so close to completing my custom module, am stuck on last step.  Within my Plugin I have instance of `Magento\Catalog\Model\Category`.
However no matter what I do it doesn't fetch the value of my custom attribute.

Calling `$category->getCustomAttribute($customAttribute);` always returns null.

In the database I see that magento2 is storing my custom attribute in the catalog_category_entity_int table.

**Comment by tanberry** [comment]
"I think the docs should be updated with information related to Plugins that intercept code dealing with the frontend." from @korostii 
@jcalcaben can you please work @jameszetlen or dev to both add this info to the docs, and hopefully get @rparsi-commer an answer? @VladimirZaets is this something that you can help with, to get the custom attribute problem solved?

**Comment by rparsi-commer** [comment]
@tanberry I suggest for now that a note like this:
When intercepting core magento2 modules that generate content for frontend,
developers will need to clean/flush cache after each code change.
It may also be necessary to run `php bin/magento indexer:reindex` for some
modules, such as `Catalog`.

I'm a noob regarding Magento2 development, so my first reading of the link below
gave me impression that just creating the Plugin and my custom module's `di.xml`
is enough.

be added to this doc:
[devdocs.magento.com/guides/v2.1/extension-dev-guide/plugins.html](devdocs.magento.com/guides/v2.1/extension-dev-guide/plugins.html)

Also, let me know if I should open new github issue for my custom Catalog attribute problem.

Thanks in advance.

**Comment by tanberry** [comment]
Thanks so much, @rparsi-commer ! If you are willing, it would be fantastic if you would open a PR against our docs and add that info. Please see our [Contributor's Guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing_docs.html) for instructions to fork & clone our public repo, and create a PR.

And Yes, agree, that is a good idea to have a separate new Issue about the custom attribute.

Thanks!

**Comment by rparsi-commer** [comment]
@tanberry @VladimirZaets Since my current problem is not directly a documentation issue, I made new ticket here
https://github.com/magento/magento2/issues/9591

However it would help noobs like myself if there was documentation giving guidance on core
Magento2 modules that don't follow standard structure.

In this particular case, I'm confused as to why the Catalog module stores attribute values in its own tables (ie `catalog_category_entity_int`) instead of `eav_entity_int`.

Thanks again for your assistance.

**Comment by antonkril** [comment]
@rparsi-commer, you don't need to redeploy static content and run reindex after adding plugins. only `bin\magento cache:clean` is required

**Comment by rparsi-commer** [comment]
@antonkril Running `bin\magento cache:clean` hasn't worked for me, but `cache:flush` seems to do the job.
By chance you know how to retrieve value of custom Category attribute given an instance of `Magento\Catalog\Model\Category`?

I tried `$category->getCustomAttribute(...)` but it always returns `null` even though I see that there's a value for it in the `catalog_category_entity_int` table.

**Comment by korostii** [comment]
@rparsi-commer, you might need to find where the collection is prepared ( I believe in this case it's done in `Magento\Catalog\Plugin\Block::getCategoryTree()` ) and invoke `addAttributeToSelect()` with your attribute code as a parameter.

**Comment by rparsi-commer** [comment]
@korostii The only class in `Catalog` module with method `getCategoryTree` is `Magento\Catalog\Plugin\Block\Topmenu`, and the method is `protected` so I can't
intercept it with my Plugin.

**Comment by korostii** [comment]
Well, duh. Naturally, you can only intercept the nearest public parent which is `beforeGetHtml()`. The only difference is the amount of code duplication.
As I mentioned earlier, you still have the alternative of disabling this whole Magento's plugin (as in `<plugin name="catalogTopmenu" disabled="true" />`) and adding your own replacement plugin instead.

**Comment by rparsi-commer** [comment]
@korostii I should've prefaced everything by saying that my team (of devs) cannot modify any code that's written by Magento.  Doing so has led to situations where we've hacked that code to the point where we couldn't merge updates from upstream (magento repo).  Thanks for the help anyway.

**Comment by korostii** [comment]
@rparsi-commer, it is possibly to disable any plugin by referencing its name while not modifying any of the core Magento code. You can just place the code in your own module's `di.xml` like the following:
```
<type name="Magento\Theme\Block\Html\Topmenu">
  <plugin name="catalogTopmenu" disabled="true" />
  <plugin name="myCatalogTopmenu" type="Company\Module\Plugin\Catalog\Block\Topmenu" />
</type>
```
And then you just need to make sure you module has a dependency declared via `module.xml` in order for the information from your configuration files to overwrite the one given by the Magento_Catalog module:
```
<sequence>
  <module name="Magento_Catalog"/>
</sequence>
```
I wonder why isn't _that_ stated in the devdocs yet. There is a [section on inheritance](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html#configuration-inheritance) but it doesn't mention if it's okay to disable a plugin from within a different module.
Anyway it's [even](https://github.com/magento/magento2/blob/ae331f5af5a2c436de1cf79e5e31796092ecf4fd/app/code/Magento/Store/etc/di.xml#L59) [used](https://github.com/magento/magento2/blob/0e3a90f75eccd98502bbb716b0f4c37bc44978d2/app/code/Magento/Backend/etc/adminhtml/di.xml#L72) in Magento CE code.
