### ISSUE TITLE
No xml example of plugin declaration in documentation

### ISSUE THREAD

**Issue by vkalchenko** [magento/devdocs#1151]
Feedback on page: /guides/v2.1/extension-dev-guide/plugins.html

I believe it was there before. Why did you remove it?

**Comment by korostii** [comment]
[This](https://github.com/magento/devdocs/commit/ac8cd8e505d0ba07c13d3db8499b5fb30c960e98) seems to be the commit where it got removed: 
Presumably [the di.xml snippet](https://github.com/magento/devdocs/commit/ac8cd8e505d0ba07c13d3db8499b5fb30c960e98#diff-f04925a2cf4318c69d2c136481d8f040L39) was embedded from someone's personal GitHub that got deleted 

The relevant snippet can still be found by using the time machine: https://web.archive.org/web/20160922202907/http://devdocs.magento.com:80/guides/v2.1/extension-dev-guide/plugins.html
Maybe it could be restored using that stored copy?

**Comment by jcalcaben** [comment]
Thanks for finding this @korostii ! I will restore this snippet on the page along with the other ones that were lost.

**Comment by jcalcaben** [comment]
I have restored the code snippet on the page. Thanks for finding it @korostii !
