### ISSUE TITLE
Documentation for MAGETWO-57343 only found in ECE docs

### ISSUE THREAD

**Issue by davidalger** [magento/devdocs#1152]
Functionality implemented in MAGETWO-57343 has been released in 2.1 (specifically 2.1.6 I believe) yet no specific mention was made of this in the release notes for CE, only for ECE. 

There was information added to the docs for ECE on how to use it: http://devdocs.magento.com/guides/v2.1/cloud/live/sens-data-over.html

The CE release command is named `app:config:dump` which differs from the above documentation. I haven't tested the use of env vars yet on CE, but the `config.local.php` definitely functions and should be documented in CE docs as well, not just ECE. 

Thanks!

**Comment by jeff-matthews** [comment]
@davidalger, the following topic covers the `app:config:dump` command: http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-export.html
