### ISSUE TITLE
Feature: Add a tutorial about upload an extension in marketplace

### ISSUE THREAD

**Issue by rafael-redstage** [magento/devdocs#1153]
Like a suggestion would be add a tutorial about how to upload a new extension and theme in Magento Marketplace.

**Comment by ccondra** [comment]
Hi Rafael,
Thanks so much for the suggestion -- although we do have a tutorial for buyers, at this time we don't have a tutorial for developers. However, have step-by-step instructions in the Marketplace user guide that outline the entire submission and review process for developers. Here's an overview of the basic steps:
The first step is to set up account as a developer. 
See: [Getting Started](http://docs.magento.com/marketplace/user_guide/getting-started-seller.html)

After your account is set up, the next step is to review our guidelines for extension developers:
See: [Guidelines](http://docs.magento.com/marketplace/user_guide/guidelines.html)

Our Extension Quality Review process can begin early in the process, even before you finish coding.  
See: [Extension Quality Program](http://docs.magento.com/marketplace/user_guide/extensions/extension-quality-program.html)

The first step in the process is to submit your idea for Business Review. 
See: [Submit for Review](http://docs.magento.com/marketplace/user_guide/submit-for-review.html)

When approved, you can submit a package with your completed code for Technical Review. When your code passes that step, you can complete the extension profile with the product description, images, and documentation, etc. When you are ready, the next step is to submit your extension or theme for Marketing Review. As a final step, your extension or theme goes through QA Review.  
After passing each stage of the review process, your extension or theme is approved for publication on Magento Marketplace.

I hope this helps you get started, and we look forward to seeing you soon as a Marketplace seller!
Claire

**Comment by jeff-matthews** [comment]
Thanks for clarifying @ccondra! Closing because it's not related to devdocs.
