### ISSUE TITLE
Installation Guide inconsitency

### ISSUE THREAD

**Issue by sgnsajgon** [magento/devdocs#1154]
Feedback on page: /guides/v2.1/install-gde/bk-install-guide.html

On aforementioned  page there is stated in "Contributing developer" section that:
> Enables you to install the Magento software and extensions using either the Web Setup Wizard or the command line.
> (...)
>You must upgrade the Magento application and extensions using Composer and GitHub commands only. You cannot use the Web Setup Wizard for upgrades.

But on page: /guides/v2.1/install-gde/install-flow-diagram.html

Point 2:
> To be able to use the Web Setup Wizard to install or upgrade the Magento software, or to manage extensions you get from Magento Marketplace, you must either get a compressed archive or a Composer metapackage.

> If you clone the GitHub repository, you cannot use the Web Setup Wizard to install or upgrade either the Magento software or extensions.

These two sections are mutually contradictory. First section states that if  you clone GitHub repository, you can use Web Setup Wizard to install software and extensions but you cannot update. The second section states that you can neither install nor upgrade.

**Comment by dshevtsov** [comment]
Thanks, @sgnsajgon !
I added a clarification to the sentence "You cannot use the Web Setup Wizard for upgrades.". Please check http://devdocs.magento.com/guides/v2.1/install-gde/bk-install-guide.html

**Comment by sgnsajgon** [comment]
Please take a look at two paragraphs below:

![image](https://cloud.githubusercontent.com/assets/9613451/26751477/a076dad4-483a-11e7-95a2-2b116f3873f2.png)

The first paragraph should be changed because it is in conflict with the second regarding Web Setup Wizard for installation.

**Comment by dshevtsov** [comment]
@sgnsajgon, yes, you are right! Thank you!
Please check how it looks now - http://devdocs.magento.com/guides/v2.1/install-gde/bk-install-guide.html

**Comment by sgnsajgon** [comment]
@dshevtsov , There are still contradictions. Please read again issue description. I have cited the caption from http://devdocs.magento.com/guides/v2.1/install-gde/install-flow-diagram.html there:

> To be able to use the Web Setup Wizard to install or upgrade the Magento software, or to manage extensions you get from Magento Marketplace, you must either get a compressed archive or a Composer metapackage.
> 
> If you clone the GitHub repository, you cannot use the Web Setup Wizard to install or upgrade either the Magento software or extensions.

The second paragraph is in conflict with http://devdocs.magento.com/guides/v2.1/install-gde/bk-install-guide.html. The first page states that you cannot install using Web Setup wizard in case of Github cloning, but the second states you can.

**Comment by jeff-matthews** [comment]
Thanks @sgnsajgon. You can install Magento and extensions from a cloned repo using the Web Setup Wizard, but you can't use it to upgrade. Updating the docs to eliminate the contradiction.

**Comment by jeff-matthews** [comment]
@sgnsajgon: See PR #1247.
