### ISSUE TITLE
Applying child sub theme

### ISSUE THREAD

**Issue by robgt** [magento/devdocs#1156]
Feedback on page: /guides/v2.1/frontend-dev-guide/themes/theme-inherit.html

Hi,
This section of the page says:
"Once the Orange Winter theme is applied..."

Could a reference on how to "apply" the Orange Winter theme be added to this page please?
Cheers!!

**Comment by almarchenko** [comment]
@robgt Sure, our bad. 
I will add the link shortly, it will reference this topic:
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html

**Comment by almarchenko** [comment]
I've merged a PR adding a link, thank you for your feedback!!
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-inherit.html
