### ISSUE TITLE
Wrong references in v2.1/frontend-dev-guide/translations/xlate.md

### ISSUE THREAD

**Issue by lorenaramonda** [magento/devdocs#1157]
At the https://github.com/magento/devdocs/blob/develop/guides/v2.1/frontend-dev-guide/translations/xlate.md#translation-dictionaries paragraph there is written:

> The Magento application automatically assembles translation dictionaries located in modules’ i18n directory into a dictionary per language. For example, Brazilian Portuguese (pt_BR) translation dictionaries might be located in module and theme directories similar to the following:
```
 app/code/Magento/Checkout/i18n/pt_BR.csv
 app/design/frontend/<Vendor>/<theme>/i18n/pt_BR.csv
```

but these two folders are not there anymore. They sound more like Magento1 version 🤔

I'd like to fix it but I'm not sure of what should be written in there.

**Comment by almarchenko** [comment]
Hi @lorenaramonda!
What exactly folders do you mean?
I didn't contact devs yet, but I did a quick check on github, and looks like the directories structure is the same, for example:
https://github.com/magento/magento2/tree/2.1/app/code/Magento/Checkout/i18n
https://github.com/magento/magento2/tree/2.1/app/design/frontend/Magento/blank/i18n

**Comment by lorenaramonda** [comment]
Ok, well I discussed this with my colleague and it seems that yes, that folders exist if you run magento without composer, but with composer, as I am working, the folders aren't there or, if there are, they're empty.
So maybe it should be specified that this is true when magento is installed without composer. Instead, in composer way, those folders can be found respectively in:

vendor/<vendor-name>/<module-name>/i18n/pt_BR.csv
vendor/<vendor-name>/<theme-name>/i18n/pt_BR.csv

Could this be more accurate/correct?

**Comment by almarchenko** [comment]
@lorenaramonda  You are right, it should be noted that path may differ depending on the way Magento was installed. I've created an internal issue 69647 for this. 

Thank you.

**Comment by almarchenko** [comment]
I've corrected the path, the changes will take effect in about an hour.
Thank you!
