### ISSUE TITLE
Broken navigation on iPad 

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#1164]
In chrome on iPad we have broken navigation
![img_0274](https://cloud.githubusercontent.com/assets/1873745/26145921/0620bdce-3af7-11e7-86dc-2682a2fae564.PNG)
![img_0275](https://cloud.githubusercontent.com/assets/1873745/26145922/066086f2-3af7-11e7-8a02-3bb2ea646b05.PNG)

**Comment by dshevtsov** [comment]
@ihor-sviziev thanks for your feedback! We'll check that.

**Comment by dshevtsov** [comment]
@ihor-sviziev a bugfix has been merged. Please check and close the issue if navigation works well now, or give us your feedback if it is still broken.

**Comment by ihor-sviziev** [comment]
Checked, it works good right now. Thank you!
