### ISSUE TITLE
"Install the Magento software using the Setup Wizard" link leads to 404 page

### ISSUE THREAD

**Issue by sdzhepa** [magento/devdocs#1165]
Feedback on page: /guides/v2.1/install-gde/install/cli/install-cli-uninstall.html

**Steps to reproduce:**

1. go to http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-uninstall.html#instgde-install-magento-reinstall in Your browser
2. Find and click link with text "Install the Magento software using the Setup Wizard"

(x) **Actual result:** 404 page

(/) **Expected Result:**
- Not sure but seems page  http://devdocs.magento.com/guides/v2.1/install-gde/install/web/install-web.html  should be opened instead of 404

**Comment by dshevtsov** [comment]
Fixed. Thanks @sdzhepa !
