### ISSUE TITLE
MySQL Connection information is out of date

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1176]
Feedback on page: /guides/v2.1/cloud/project/project-conf-files_services-mysql.html

This documentation appears to be out of date.  From Maddy:

As a developer one should not need to read these values directly. They should be read via Magento’s library: Magento\Framework\App\DeploymentConfig 
For example to get the db connection $config = $this->deploymentConfig->get(ConfigOptionsListConstants::CONFIG_PATH_DB_CONNECTION_DEFAULT);

**Comment by jcalcaben** [comment]
Thanks for pointing that out @dougkm ! 

Maddy has updated the docs in this PR: https://github.com/magento/devdocs/pull/1177

I will keep this issue open until we add replacement content for reading the values.

**Comment by jcalcaben** [comment]
Closing this issue since the PR has been merged.
