### ISSUE TITLE
Ambiguous test command

### ISSUE THREAD

**Issue by QwertyZW** [magento/devdocs#1178]
Feedback on page: /guides/v2.0/test/integration/integration_test_setup.html

The page concludes with 

>Such a test suite configuration can then be executed using the --testsuite command option, for example --testsuite "Third Party Integration Tests"

What command is it talking about?

It doesn't seem to be

```
php bin/magento dev:tests:run
```

nor

```
php bin/magento dev:tests:run integration
```

It's probably 

```
php ../../../vendor/bin/phpunit --testsuite <name>
```
from within `dev/tests/integration`

**Comment by dshevtsov** [comment]
@QwertyZW thank you for your detailed feedback!
Please check how it looks with changes - http://devdocs.magento.com/guides/v2.1/test/integration/integration_test_setup.html

**Comment by QwertyZW** [comment]
Well done!
