### ISSUE TITLE
Message Queue: process management with MySQL

### ISSUE THREAD

**Issue by ocornu-mediastay** [magento/devdocs#1179]
Feedback on page: /guides/v2.1/config-guide/mq/manage-mysql.html

I successfully set up a message queue and manage it by MySQL. However I'm wondering if adding a cron that runs every night to launch a new consumer is a good idea.

I mean: if the consumers has no queue to process for several days, a new consumer is launched each day and will stay in memory.

Maybe the doc should not advice to run cron to launch consumers.

**Comment by jcalcaben** [comment]
@keharper can you follow up on this issue and see what the next steps are?

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
