### ISSUE TITLE
Provide a 'supported version overview'

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1180]
Hi guys

Just something that popped into my head.
I seem to recall I read somewhere that Magento will support each major version (2.0, 2.1, 2.2, 2.3, ...) for up to 2 years.
It would be nice if we could see this in the official documentation, with the exact dates on which a version was released and when the support will stop.
Also: will there be a difference in the timeline on support for bug fixes and security fixes, where the timeline for security fixes will be extended over the normal bug fixes?

If this hasn't been decided yet internally, then it is probably not necessary to document this until it has been decided.

Examples:
- PHP: http://php.net/supported-versions.php
- Symfony2: http://symfony.com/doc/current/contributing/community/releases.html#version-history
- Laravel: https://laravel-news.com/laravel-release-process

**Comment by hostep** [comment]
So @okorshenko has pointed out that version 2.0 is [now considered EOL](https://github.com/magento/magento2/issues/7279#issuecomment-310175923), I assume this means there was an internal decision made around the how long each version will be supported.
It would be great if these timelines could be published in the official documentation so everyone is aware of this, I believe this would be very useful.

Thanks again!

**Comment by mzeis** [comment]
With the EOL for 2.0 approaching in less than three months it would be great to get this page added. Is there already a plan for this @dshevtsov?

**Comment by dshevtsov** [comment]
@mzeis, @hostep 
Currently, End of Support Dates are published for Magento Commerce (previously EE) in [Enterprise Edition Subscription Agreement](https://magento.com/legal/terms/enterprise-agreement).
End Dates for Magento Open Source (previously CE) are still discussed.

**Comment by jfrontain** [comment]
Hi Pieter, I'm not commenting directly on this issue but am using it to contact you.  this is Jeanne, the Magento devdoc writer that you’ve been indirectly working with on the recent release notes and  I’d like to approach you about several potential collaborations.

First of all, thanks for your astute comments on published release notes. I welcome any suggestions that improve the accuracy and readability of these documents. Please feel free to send comments on any sets of published release notes, and I’ll update them. 

Second, in the interest of improving accuracy before we publish a set of release notes, I’d like to send you drafts of the release note text for issues that you’ve worked on before we publish. I hope to approach frequent contributors and encourage their involvement before we actually publish. I’m currently working on the notes for 2.1.14 and 2.2.5, and I’ve seen your name on several issues. May I send you those issue descriptions, and you can add information or correct as needed?

(This second request is part of a larger effort to encourage community contributions in our devdocs repo. There is an enormous range and depth of skills in the Magento community, and we can’t properly document the code without the community’s help. With that goal in mind, we’ve created a community maintainers program for devdocs, similar to the maintainers program associated with the Community Engineering team. We’d love to have you as an official maintainer. Here’s a link to the page that describes this new program: 

https://devdocs.magento.com/guides/v2.2/contributor-guide/devdocs-maintainers.html

Whether you join the maintainers team or not, we always welcome your comments and contributions. You can reach me on GitHub as usual or directly at my magento.com address. Thanks — Jeanne

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
Please feel free to create a new issue if necessary. Thank you for continued collaboration and assistance!

**Comment by hostep** [comment]
@dshevtsov: can we assume that Magento Open Source is supported for the same amount of time as Magento Commerce? Since the [last release of 2.0 for Open Source](https://github.com/magento/magento2/releases/tag/2.0.18) was on 27 February 2018 and that seems to match the date (March 2018) mentioned in [the document you referred to](https://magento.com/legal/terms/enterprise-agreement).

It also looks like from Magento 2.2 onwards, the support duration will only be 2 years, in contrast to 3 years for 2.0 and 2.1 according to that same document :(

**Comment by mzeis** [comment]
@hostep To my knowledge, EOL for Open Source is 2 years after launch. The only official source I can refer to is this [Tweet](https://twitter.com/ProductPaul/status/748302089554583553) by Paul who was Director of Product Management at Magento.

I will try to get some feedback on this.

**Comment by mzeis** [comment]
@hostep This isn't the official word by Magento (it will be clarified soon, hopefully), but based on responses I got from core members this is my new personal working hypothesis: https://www.magento.com/legal/terms refers to https://www.magento.com/sites/default/files/magento-software-lifecycle-policy.pdf and Open Source follows the same time deadlines as mentioned for Commerce.

This would mean that support for 2.1 OS didn't end June 2018 as could be assumed by my previous comment (2.1 was released June 2016) but will end June 2019 as listed in the document. Another indication for this is that PRs can still be backported to the `2.1-develop` which wouldn't make sense if 2.1.14 was the last OS release in this series.

Please take this interpretation with a grain of salt until there is an official announcement.

**Comment by hostep** [comment]
Thanks for pursuing this @mzeis. Your interpretation is the same as mine and makes the most sense. Since Magento Commerce relies on Magento OS code, so it makes sense that OS is supported as long as Commerce itself.
