### ISSUE TITLE
Misleading link Form Component page for Magento 2.1

### ISSUE THREAD

**Issue by Nikolay-Baychenko** [magento/devdocs#1188]
When switching versions from Magento 2.0 to 2.1 from this page:
http://devdocs.magento.com/guides/v2.0/ui-components/ui-form.html
Throws page not found by requesting Form Component page for Magento 2.1:
http://devdocs.magento.com/guides/v2.1/ui-components/ui-form.html

What possibly should be there is:
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-form.html

**Comment by almarchenko** [comment]
@Nikolay-Baychenko 
Thanks for your feedback. You are right, it should be http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-form.html.
I've added the redirect, the edit will take effect in an hour I think.

**Comment by almarchenko** [comment]
It was published, and redirect works ok! 
Thank you for raising this!

**Comment by Nikolay-Baychenko** [comment]
@almarchenko I'm afraid now there is the same problem when switching from 2.1 to 2.0.
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-form.html
Directs to this URL and gives page not found:
http://devdocs.magento.com/guides/v2.0/ui_comp_guide/components/ui-form.html
Should be this one:
http://devdocs.magento.com/guides/v2.0/ui-components/ui-form.html
