### ISSUE TITLE
errors in recommended actions for the 1.x versions for Mastercard issue

### ISSUE THREAD

**Issue by kennylawrence** [magento/devdocs#1191]
Feedback on page: /guides/v2.1/release-notes/tech_bull_21x_MasterCard.html

> 1.9.0.0 	Install patch PATCH_SUPEE-2725_EE_1.9.0.0_v1.sh before installing PATCH_SUPEE-8967_EE_1.13.1.0_v1.sh.

It says to use Enterprise patches for community version?

> 1.9.1.0 – 1.11.2.0 	Install PATCH_SUPEE-2725_EE_1.9.1.1-EE_1.11.2.0_v2.sh before installing PATCH_SUPEE-8967_EE_1.13.1.0_v1.sh

Look at the filenames again. EE_1.9.1.1... don't you mean CE? Are you mixing CE and EE version numbers? If so, that is extremely confusing. I am not sure what to do. I have CE 1.9.2.2

**Comment by kennylawrence** [comment]
Also, why is SUPEE-2725 mentioned at all for 1.9.1.0-1.11.2.0? SUPEE-2725 was released in Feb 2014. Shouldn't it already be integrated in CE 1.9.1.0?

**Comment by jfrontain** [comment]
@kennylawrence, I'm working on getting clarification of these issues, and will update the MasterCard Technical Bulletin as soon as I can. Thanks for your questions --we want these Bulletins (well, all our docs) to be as accurate as possible.

**Comment by jcalcaben** [comment]
@jfrontain what is the status of this issue?

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
Please feel free to create a new issue if necessary. Thank you for continued collaboration and assistance!
