### ISSUE TITLE
Release notes: Correct the instructions for older version regarding upgrade to 2.1.7

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1192]
Feedback on page: http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.7CE.html

The guidelines table is a bit misleading in contrast with the accompanying text.
At the first glance one might think 2.1.5 cannot benefit from this update and shouldn't bother doing anything at all: http://take.ms/7O4I3
I assume that's not true? If that's the case, I'd suggest correcting the name of the last column to "Additional Actions" instead.

I would also imagine the version range in the first row could be broader (as in: 2.1.0-2.1.5 )

**Comment by jfrontain** [comment]
good suggestions, @korostii  -- will update now. Thanks!

**Comment by jfrontain** [comment]
Hi @korostii, I've updated the 2.1.7 release notes to include your suggested changes plus a few others. I'm closing this issue now; feel free to open an other if you catch anything else. Thanks again for your great comments!

**Comment by hostep** [comment]
@jfrontain: tnx! But you made a small typo though: `Additinal` ;)

**Comment by jfrontain** [comment]
Yikes! Fixing it now. Thanks!
