### ISSUE TITLE
Not able to get customer collection with SOAP API

### ISSUE THREAD

**Issue by allamsettiramesh** [magento/devdocs#1194]
Team, i am trying to get customer collection with below script but am able to get single record instead of 5 records.

 $searchCriteria = [ 
                            'searchCriteria' => [
                                                  'filterGroups' =>  [ 
                                                                         [ 
                                                                           'filters' =>  [ 
                                                                                            [ 
                                                                                               'field' => 'entity_id',
                                                                                               'value' => '1',
                                                                                               'condition_type' => 'gteq',
                                                                                             ],
                                                                                         ],
                                                                          ],
                                                                     ],
                                                 'currentPage' => 1,
                                                 'pageSize' => 10,                                          
                                               ],
                          ];

` $wsdlUrl = 'http://127.0.0.1/magento/soap/default?wsdl&services=customerCustomerRepositoryV1';`
`$soapResponse = $soapClient->customerCustomerRepositoryV1GetList($searchCriteria);`

Actually i want to get customer collection.

**Comment by keharper** [comment]
@allamsettiramesh, it will take me a while to set up everything in SOAP, but I can answer quickly in REST. This call works in REST. I don't have a `slide_id` so I sorted by last name. 

`http://m2-3.vg/rest/default/V1/customers/search?
searchCriteria[filter_groups][0][filters][0][field]=entity_id&
searchCriteria[filter_groups][0][filters][0][value]=1&
searchCriteria[filter_groups][0][filters][0][condition_type]=gteq&
searchCriteria[sortOrders][0][field]=lastname&
searchCriteria[sortOrders][0][direction]=ASC`

**Comment by allamsettiramesh** [comment]
@keharper, Actually my query look likes your query but i am't able to get all the customers. slide_id is commented in my query.

**Comment by keharper** [comment]
@allamsettiramesh Would you post the full definition of a customer with `slide_id` included?

**Comment by allamsettiramesh** [comment]
@keharper , I updated my query.

**Comment by keharper** [comment]
@allamsettiramesh could you provide the output from a GET /V1/customers/:customerId call for a customer that has an assigned `slack_id`?

**Comment by allamsettiramesh** [comment]
@keharper, Am sharing customer data


 `{
    "id": 86,
    "group_id": 1,
    "default_billing": "193",
    "default_shipping": "193",
    "created_at": "2017-07-13 05:30:44",
    "updated_at": "2017-07-13 05:30:44",
    "created_in": "Default Store View",
    "email": "test01@test.com",
    "firstname": "test01",
    "lastname": "test01",
    "store_id": 1,
    "website_id": 1,
    "addresses": [
        {
            "id": 193,
            "customer_id": 86,
            "region": {
                "region_code": "Hyd",
                "region": "Hyd",
                "region_id": 0
            },
            "region_id": 0,
            "country_id": "IN",
            "street": [
                "Test"
            ],
            "telephone": "1234567891",
            "postcode": "500045",
            "city": "test",
            "firstname": "test01",
            "lastname": "test01",
            "default_shipping": true,
            "default_billing": true,
            "custom_attributes": [
                {
                    "attribute_code": "addressupdatedinsap",
                    "value": "0"
                },
                {
                    "attribute_code": "adressfrommagento",
                    "value": "0"
                }
            ]
        }
    ],
    "disable_auto_group_change": 0,
    "custom_attributes": [
        {
            "attribute_code": "updatedinsap",
            "value": "0"
        },
        {
            "attribute_code": "magentocustomer",
            "value": "0"
        },
        {
            "attribute_code": "isactivated",
            "value": "0"
        }
    ]
}`
