### ISSUE TITLE
Did not work, error message

### ISSUE THREAD

**Issue by rimkutea** [magento/devdocs#1195]
Feedback on page: /guides/v2.0/config-guide/secy/secy-cron.html

Good day
I tried to Run cron from a web browser in order to reindex (My files are stored on external third party server). Unfortunately it did not work and brought an error message, any idea how to fix it?

http://beuty.ausra.ch/pub/cron.php?group=index

Fatal error: Class 'Magento\Framework\Console\CLI' not found in /home/httpd/vhosts/comunara.com/beuty.ausra.ch/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php on line 173

**Comment by jeff-matthews** [comment]
@rimkutea, configuring and storing a password file on a third-party server is outside the scope of this topic, but if you figured out a way to do it, please consider submitting a pull request to update the docs.
