### ISSUE TITLE
Put the Magento file system owner in the web server’s group

### ISSUE THREAD

**Issue by sgnsajgon** [magento/devdocs#1196]
I think in the section "_Put the Magento file system owner in the web server’s group_", for example on page http://devdocs.magento.com/guides/v2.1/install-gde/prereq/file-system-perms.html, it is reasonable to change command from:

> usermod -g \<www-server-group\> \<username\>

to:

> usermod -a -G \<www-server-group\> \<username\>

The first command **changes the user's primary group**, but the second command **adds user to secondary group**. Reasons:

1. If we creates a new user dedicated to Magento installation filesystem, we want new files created by this user under Magento installation filesystem to be owned by www server group. On the other hand, if we use this user to create new files outside Magento installation filesystem, such files presumably related to Magento (i.e. private content, documentation, reports, notes), but with intention to be not accessible to www server user due to security concerns, we do not want these files to be owned by www server group. If our user has www server group as primary group, all files created created by this user are owned by www server group. However if this group is assigned to our user as secondary group, only files created by user under Magento installation filesystem are owned by www server group (because of _setguid_ bit sets on all directories under Magento Installation filesystem, sets by _find_ command as described in section "_Set ownership and permissions for the shared group_"). Files in other locations would belong to default user's group, which has typically the same name as user's name.
2. On development environment (but also in production environments) it is likely that developer do not want to create new user strictly dedicated to Magento installation filesystem. She/he would like to use any other account. In development environment it would be probable that developer uses her/his main account to operate on Magento installation filesystem. In such case, it is not desirable to change main account primary group to www server group, but rather add that group as secondary group of the account.

**Comment by jeff-matthews** [comment]
Thanks for the feedback @sgnsajgon. You bring up several good points. I think it'd also be helpful to point out that using the `usermod -g <www-server-group> <username>` command removes the user from all other groups; making the `-a -G` options even more important if you're configuring an existing user account.

I'll start working on these revisions.

**Comment by jeff-matthews** [comment]
See PR #1236
