### ISSUE TITLE
Link to magento2-samples example

### ISSUE THREAD

**Issue by WileESpaghetti** [magento/devdocs#1197]
Feedback on page: /guides/v2.1/extension-dev-guide/bk-extension-dev-guide.html

I discovered the awesome (magento2-samples)[https://github.com/magento/magento2-samples] repo. It would be nice if each of the topics linked to the corresponding example module. These examples give a bit more context to the code on the devdoc pages and typically better answer the question "How do I use X".

**Comment by jcalcaben** [comment]
Thanks for the suggestion @WileESpaghetti, but the linked `magento2-samples` is not an actively maintained repository.

If you feel strongly that this should be included, please create a PR that adds this information to the page.
