### ISSUE TITLE
Example for around-listener broken

### ISSUE THREAD

**Issue by mzeis** [magento/devdocs#120]
On http://devdocs.magento.com/guides/v1.0/config-guide/config/plugins.html, the example for the around-listener shows the code for the before-listener. I didn't find a fitting example in the gists listed at https://gist.github.com/xcomSteveJohnson.

**Comment by xcomSteveJohnson** [comment]
Fixed. Please close this issue if you're happy with the resolution.

http://devdocs.magento.com/guides/v1.0/config-guide/config/plugins.html

**Comment by mzeis** [comment]
Thank you, Steve! I'll close the issue.

It's not part of this issue but if I understood correctly that calling `$proceed();`also executes the original product save method you could add this information to the explanation of the `$proceed` parameter. I'm pretty sure it works this way but not 100% and this may be the case for others too.

**Comment by xcomSteveJohnson** [comment]
Response from Anton Makarenko. Please let me know what you think:

Yes, he is correct, although I’d describe it in slightly different way. Here is what you have now:
“The $proceed parameter calls the next plug-in or method.”

I’d recommend something like this:
The $proceed() invokes the original method and/or other nested plug-ins (if any).

**Comment by mzeis** [comment]
Yes, that's better, thanks!
