### ISSUE TITLE
Magento 2.1.7 release notes: mention something about the update of the pdepend/pdepend library

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1200]
Hi!

I'm not sure if this is really important, but the dependency in the `composer.json` file on the `pdepend/pdepend` library has [changed](https://github.com/magento/magento2/compare/2.1.6...2.1.7#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) from version 2.2.2 to 2.4.0.

If we just simply follow the [command line upgrade instructions](http://devdocs.magento.com/guides/v2.1/comp-mgr/cli/cli-upgrade.html), this dependency will still be at version 2.2.2, because it is defined like that in the `composer.json` file of your project.

The reason why I mention this, is because if we manually change it to version 2.4.0 in our project's `composer.json` file, a couple of symfony modules get updated to a much more modern version. 
And I'm not sure if this is part of the security update or not (probably not), but since Magento now uses these more modern versions of the symfony modules in testing, it makes sense if all projects also use these newer versions.
The symfony modules I'm talking about:

| Symfony module | version installed using `pdepend/pdepend` 2.2.2 | version installed using `pdepend/pdepend` 2.4.0 |
| ---------------|----------------- | ------------------- |
| `symfony/filesystem` | v2.8.21 | v3.3.0 |
| `symfony/dependency-injection` | v2.8.21 | v3.1.10 |
| `symfony/config` | v2.8.21 | v3.2.9 |

Can you please check this with the developers, if it is recommended to everyone to update their `pdepend/pdepend` dependency to version 2.4.0 ?

(this does not apply for Magento 2.0.14 I think, since it still uses `pdepend/pdepend` version 2.2.2)

Also, but less important, the page http://devdocs.magento.com/guides/v2.1/release-notes/thirdparty_ce.html should also be updated with the new version of `pdepend/pdepend`, it is still at 2.2.2 currently (I haven't checked the other dependencies mentioned on that page, maybe some of them are outdated as well?), or maybe just remove all versions from those pages, otherwise you'll have to update them all the time ...

Thanks!

**Comment by jfrontain** [comment]
Thanks, @hostep. We're following up now.

**Comment by buskamuza** [comment]
@hostep , it's not required to update `pdepend` for your project. The reason why it was updated is a fix in `pdepend` that made dependencies calculated correctly - https://github.com/pdepend/pdepend/issues/210
It's unrelated to security, so it's up to you whether update it or not.
As I can see, update to the newer version didn't require any fixes in the tests from our side, so the old `pdepend` version should be compatible with new version of Magento.

**Comment by hostep** [comment]
@buskamuza: I'm talking about the symfony dependencies of `pdepend`, they have been upped to a much more recent version.
But I dug in a little further and the three symfony dependencies mentioned above aren't being used by Magento's code, so my remark is irrelevant.

Sorry about this, I should have researched this a little bit better.
Thanks for the fast response though!
