### ISSUE TITLE
Missing adjustment to `http_resp_size` that is required for large headers

### ISSUE THREAD

**Issue by ivan-section-io** [magento/devdocs#1202]
Feedback on page: /guides/v2.0/config-guide/varnish/tshoot-varnish-503.html and /guides/v2.2/config-guide/varnish/tshoot-varnish-503.html

`http_resp_hdr_len` is the  allowable header length within the total allowable (non-body) response size (32K default).
Once `http_resp_hdr_len` is increased to exceed this 32K default, (which it would be for the example 64000 value), `http_resp_size` must also be increased to accommodate the total non-body response size.

Failing to adjust this results in Varnish producing 503s and "FetchError     http read error: overflow"

See:
* http://www.varnish-cache.org/docs/4.0/reference/varnishd.html#http-resp-size
* http://www.varnish-cache.org/docs/4.0/reference/varnishd.html#http-resp-hdr-len

**Comment by jeff-matthews** [comment]
@ivan-section-io Thanks for the feedback! What would be a reasonable example value for the `http_resp_size` parameter?

**Comment by ivan-section-io** [comment]
@jeff-matthews For the current example using 64000 for a header - I'd probably use a nice round 64k value - 65536.

**Comment by jeff-matthews** [comment]
Thanks @ivan-section-io. I revised the documentation and opened a pull request.

**Comment by jeff-matthews** [comment]
PR #1225 merged

**Comment by jeff-matthews** [comment]
Per recommendation from internal Magento developer, update the `http_resp_size` example value to 96k.

Calculation:
`http_resp_size` (32k) + `http_resp_hdr_len` (64k) = 96k

**Comment by jeff-matthews** [comment]
See PR #1227
