### ISSUE TITLE
No mention of where adding a theme should happen

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1205]
Feedback on page: /guides/v2.0/cloud/howtos/custom-theme.html

There is no mention of where adding a theme should be done.  This needs to be done in a local development environment setup by the customer.

**Comment by jeff-matthews** [comment]
@dougkm: I believe the [Get started with a branch](http://devdocs.magento.com/guides/v2.0/cloud/howtos/custom-theme.html#branch) section addresses this. This section may not have existed when you originally reported this issue, so please confirm.

**Comment by jeff-matthews** [comment]
The branching section in the theme topic addresses this.
