### ISSUE TITLE
Missleading link Form Component Magento 2.1 

### ISSUE THREAD

**Issue by addxorsw** [magento/devdocs#1206]
Previously reported an [issue](https://github.com/magento/devdocs/issues/1188) which was solved but caused another problem.

When switching from 2.1 to 2.0.
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-form.html
Directs to this URL and gives page not found:
http://devdocs.magento.com/guides/v2.0/ui_comp_guide/components/ui-form.html
Should be this one:
http://devdocs.magento.com/guides/v2.0/ui-components/ui-form.html

**Comment by almarchenko** [comment]
@addxorsw Sorry I missed your last comment in the closed issue.
I've fixed hopefully the new problem as well!

**Comment by addxorsw** [comment]
@almarchenko Works perfectly as I see it. Thank you.
