### ISSUE TITLE
This page doesn't describe how to pull in the region_id

### ISSUE THREAD

**Issue by noctufaber** [magento/devdocs#1215]
I'm guessing that another api call needs to be made to get more region details?

Feedback on page: /guides/v2.1/get-started/order-tutorial/order-prepare-checkout.html

**Comment by keharper** [comment]
What type of region details do you mean?

**Comment by noctufaber** [comment]
In the code sample to request the shipping estimate it asks for the region_id.  I don't know where that's coming from.

**Comment by keharper** [comment]
I can give you this workaround today that I know works for US addresses. It'll take longer to get a definitive answer.

Go to app/code/Magento/Directory/Setup/InstallData.php and copy these lines into a text editor with line numbers turned on

            ['US', 'AL', 'Alabama'],
            ['US', 'AK', 'Alaska'],
            ['US', 'AS', 'American Samoa'],
            ....
            ['US', 'AL', 'Alabama'],
            ['US', 'AK', 'Alaska'],
            ['US', 'AS', 'American Samoa']

The line number will be the region ID

**Comment by noctufaber** [comment]
K.  Thanks for the help.
