### ISSUE TITLE
Difference between EAV attributes and Extension Attributes

### ISSUE THREAD

**Issue by WileESpaghetti** [magento/devdocs#1217]
Feedback on page: /guides/v2.0/extension-dev-guide/attributes.html

When should I use an Extension attribute in my module instead of an EAV attribute? It's not immediately clear what the difference between them are and why I should prefer one over the other.

**Comment by maghamed** [comment]
Hey @WileESpaghetti 
There is an official documentation regarding this one - http://devdocs.magento.com/guides/v2.0/extension-dev-guide/attributes.html

the long story short:
For now EAV attributes available just for 2 entities Catalog Product and Customer. You can't add EAV for other entities, like Stock, Wishlist etc.
Also, EAV attributes represent just simple attribute types, compared to Extension ones, which could represent some custom object type with an own interface.

**Comment by jcalcaben** [comment]
Closing this issue. If you have further comments and feedback, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!
