### ISSUE TITLE
Not all data providers provide the possibility of passing php modifiers pool as argument

### ISSUE THREAD

**Issue by medmek** [magento/devdocs#1220]
Feedback on page: /guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.html
from the General implementation overview 

> section DataProvider() is a PHP part of a UI component, a class responsible for the component’s data and metadata preparation. The pool of modifiers (virtual type) is injected to this data provider using the __construct() method. The pool’s preference is defined in di.xml.

One could understand that every DataProvider can receive this pool.
for example `\Magento\Customer\Model\Customer\DataProvider` have a `filterPool `not `pool` : 

    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        EavValidationRules $eavValidationRules,
        CustomerCollectionFactory $customerCollectionFactory,
        Config $eavConfig,
        FilterPool $filterPool,
        array $meta = [],
        array $data = []
    ) {...}

 If it is expected from everyone to start overriding dataProviders in order to meet that requirement, I think it should be mentioned here somewhere.

**Comment by bdenham** [comment]
Sorry this issue has sat dormant for so long. Thanks, for bringing this to our attention. I'm not sure I fully understand what the issue is. Can you explain further, so we can address it? Thanks.

**Comment by shrielenee** [comment]
Hey @medmek - We haven't heard from you regarding this issue in a while. Due to inactivity, we are closing this issue. If you have further comments and feedback, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!
