### ISSUE TITLE
Insufficient description how to configure AllowOverride directive for Apache configuration

### ISSUE THREAD

**Issue by sgnsajgon** [magento/devdocs#1224]
Feedback on page: /guides/v2.1/install-gde/prereq/apache.html

Aforementioned page is aimed to explain how to enable Apache 2.2 and 2.4 Rewrites module and specify a setting for the distributed configuration file, ._htaccess_. In fact, presented explanation is insufficient and superficial, because does not concern the heart of the matter, namely how to setup _AllowOverride_ directive of site configuration. It merely forces reader to see the guidelines in the Apache documentation. In my opinion, this page should precisely show how Apache configuration for Magento has to be setup. It is likely that user would have to spend some time to find proper configuration using "trials and errors" approach, or would be discouraged to find a solution on her/his own and would configure it as "_AllowOverride All_", what is probably not a good idea due to security concerns.

I have done some recognitions and I have concluded that the minimal configuration for working site on Apache 2.4 should be as shown below, assuming that document root is  "_/var/www/html/magento_":

```
<Directory /var/www/html/magento>
    AllowOverride FileInfo Indexes Limit Options=FollowSymLinks,Indexes,MultiViews
    Require all granted
</Directory>

<Directory /var/www/html/magento/pub/media>
    AllowOverride FileInfo Limit Options=All
</Directory>
```
Rationale:
- _FileInfo_: to enable Rewrites module.
- _Indexes_: to enable directory index (i.e. _DirectoryIndex_ directive).
- _Limit_: to enable directives controlling host access (_Allow_, _Deny_ and _Order_).
- _Options=FollowSymLinks_: to enable _Options +FollowSymLinks_ directive i.e. in main directory _.htaccess_ file.
- _Options=Indexes_: to enable _Options +Indexes_ directive i.e. in main directory _.htaccess_ file.
- _Options=MultiViews_: to enable _Options -MultiViews_ directive i.e. in _pub/static/.htaccess_ file.
- _Options=All_ in case of _pub/media_ and directories: to enable _Options=All_ directive in _.htaccess_ files within these directories.

To test above configuration, we can run Magento virtual host site (without installation steps performed), and try to access (simulating web browser) each Magento filesystem directory which contains _.htaccess_ file using the following command (assuming that virtual host in configured for _magento.sgnsajgon.pl_ domain):

`find -name .htaccess -printf 'http://magento.sgnsajgon.pl%h/\n' | sed -e 's|\./|/|' | xargs curl -vIL --stderr - | grep "500\|403" -B 10`

We can see that there is no page causing 403 (Forbidden) error, and only 2 pages cause 500 (Internal Error) error, but due to PHP exceptions, not Apache configuration issues.

It is minimal configuration for Apache 2.4. Configuration for Apache 2.2 is likely the same or very similar, but I have no tested it with version 2.2.

I have several additional proposals of improvements for this page:
- In section "_Enable rewrites and .htaccess for Apache 2.4_" there is an advise: 
    > In some cases, additional parameters might be required. For more information, see the Apache 2.4      documentation.

    For clarify it should be explained what cases are meant here.
- In section "_Enable rewrites and .htaccess for Apache 2.2_" there is an advise:
    > The preceding values for Order might not work in all cases. For more information, see the Apache   documentation (2.2, 2.4).

    For clarify it should be explained what cases are meant here.
- in sections "_Solving 403 Forbidden errors for Apache 2.4_" and "_Solving 403 Forbidden errors for Apache 2.2_" there are advices:
    > The preceding values for Order might not work in all cases. For more information, see the Apache documentation.

    For clarify it should be explained what cases are meant here.
- In configuration examples on page there is presented _Options_ directive:
`Options Indexes FollowSymLinks MultiViews`

    Is it necessary? I have found that several _.htaccess_ configurations enable or disable these options explicitly for directory if needed ( thus "_AllowOverride Options=FollowSymLinks,Indexes,MultiViews_" directive is required, as I describe above), so I guess that it is not required to enable them for entire site. In fact, it may cause security issues, i.e. if _Indexes_ option in set for entire site and we forget to apply _DiretoryIndex_ directive in any _.htaccess_ file - it would cause directory content leak.

**Comment by jbliesener** [comment]
I have found this AllowOverride directive for `/var/www/html/magento/pub/media` to be insufficient. The problem is that `/var/www/html/magento/pub/media` inherits from `/var/www/html/magento` and therefore can NOT have more permissions on Options than `/var/www/html/magento`. 

I got an error 500 due to `Options -ExecCGI` in `/var/www/html/magento/pub/media/.htaccess`. Adding `,ExecCGI` to `AllowOverride` in the `<Directory /var/www/html/magento/pub/media/>` block didn't resolve the issue. I had to include it in the `<Directory /var/www/html/magento>` block.

**Comment by jcalcaben** [comment]
Hi @sgnsajgon, would you be willing to create a PR with this information for the page?

**Comment by jeff-matthews** [comment]
@osrecio, is this something you could help us with?

**Comment by osrecio** [comment]
For sure. Now I'm at MM18DE. I will check on Thursday.

**Comment by jeff-matthews** [comment]
Hi @osrecio, can you take a look at this this week?

**Comment by osrecio** [comment]
I tested the config from @sgnsajgon and seems to be ok. I compared with other projects in production with Apache and is so similar.

I will create a PR to add the advices I think is a good idea to have a guideline if is your first time with Magento and Apache configuration. 

IMHO the Apache configuration depends at all of your environment although it is true that we can have a "standard".

**Comment by jeff-matthews** [comment]
Thanks @osrecio!

**Comment by shrielenee** [comment]
Hey @osrecio @jeff-matthews - Was there a PR created for this work? I don't notice one referenced here. Let us know so we can update this to be accurate!

**Comment by hguthrie** [comment]
@osrecio Is this still **In Progress**?

**Comment by shrielenee** [comment]
We haven't heard from you regarding this issue in two weeks or more. Due to inactivity, we are closing this issue. If you have further comments and feedback, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by MantisMan13** [comment]
Your documentation is still horribly lacking. I hope the guidance I found here helps me. This should not have been a closed thread without having acted on the suggestion and updated the documentation as suggested or explained why that is not a good thing to be done. JMO
