### ISSUE TITLE
Incorrect information on SSL certs

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1229]
Feedback on page: /guides/v2.1/cloud/live/live.html

"Purchase an SSL certificate and provide it to Support when requested."

ECE customer do not provide SSL certs by default.  It is an addon.

**Comment by lorikrell** [comment]
Thank you for the feedback. Investigating and updating docs. I'll reach out with questions as I have them.

**Comment by lorikrell** [comment]
Updates are posted and available at: http://devdocs.magento.com/guides/v2.1/cloud/live/live.html

**Comment by lorikrell** [comment]
Closing issue as completed. If you have further needs, please provide new feedback. Thanks!
