### ISSUE TITLE
This page doesn't describe how to configure the system if you're running Magento behind a load balancer.

### ISSUE THREAD

**Issue by noctufaber** [magento/devdocs#1231]
Feedback on page: /guides/v2.1/install-gde/install/web/install-web_3-web-conf.html

This page doesn't describe how to configure the system if you're running Magento behind a load balancer.

**Comment by jeff-matthews** [comment]
@noctufaber, did you ever figure out how to do this? If so, please consider creating a PR to update the docs. You can also just leave comments about how you did it and I'll update the docs.

**Comment by lorikrell** [comment]
Need to check with architects for additional information. @buskamuza do you happen to know who may have this info?

**Comment by hguthrie** [comment]
There has been no response for some time. We are closing this issue.
