### ISSUE TITLE
I can't create shipment through REST API 

### ISSUE THREAD

**Issue by allamsettiramesh** [magento/devdocs#1233]
I am't able to create shipment properly through REST API with following Parameters,
{
    "entity": {
        "billing_address_id": 32,
	    "customer_id": 64,
	    "order_id": 18,
	    "packages": [],
	    "shipping_address_id": 31,
	    "store_id": 1,
	    "total_qty": 1,
	    "items": [
	        {
	            "name": "T Shirt",
	            "price": 100,
	            "product_id": 2,
	            "sku": "tshirt",
	            "weight": 12,
	            "qty": 1
	        }
	    ],
	   "tracks": [
        {
            "order_id": 18,
            "weight": null,
            "qty": null,
            "parent_id": 39,
            "description": null,
            "track_number": "1234567890",
            "title": "Federal Express",
            "carrier_code": "fedex"
        }
    ],
	    "comments": []
    }
}

Here without parent_id i can't create shipment if i sent parent_id then am getting below error 
"
( ! ) Fatal error: Call to a member function getIsVirtual() on a non-object in /var/www/html/magento2/vendor/magento/module-shipping/view/adminhtml/templates/view/items.phtml on line 19"

**Comment by allamsettiramesh** [comment]
@keharper, can you please provide the solution for this.

**Comment by allamsettiramesh** [comment]
Actually i am facing this issue in 2.0.10 But it's working in 2.1.6. Could you please provide any solution for 2.0.10

**Comment by keharper** [comment]
I can't tell for sure which endpoint you're using, but I think it's `POST /V1/shipment/`.

Try `POST /V1/order/:orderId/ship`

**Comment by keharper** [comment]
@allamsettiramesh Any luck?

**Comment by allamsettiramesh** [comment]
@keharper, It's working when am i upgraded to 2.1.6
