### ISSUE TITLE
Outdated images of GitHub repository cloning web interface

### ISSUE THREAD

**Issue by sgnsajgon** [magento/devdocs#1238]
Feedback on page: /guides/v2.1/install-gde/prereq/dev_install.html

Two images in section "_How to clone the Magento 2 GitHub repository_" (within sub-sections "_Clone with SSH_" and "_Clone with HTTPS_") are outdated. These pictures show old GitHub web interface. The new interface is slightly different.

Descriptions just above images should also be slightly modified to reflect new interface.

**Comment by jeff-matthews** [comment]
Thanks @sgnsajgon. I may simplify the "Clone with..." sections in this topic and link to [Github's documentation](https://help.github.com/articles/cloning-a-repository-from-github/) for more detailed instructions. Either way, I'll get this updated.

**Comment by jcalcaben** [comment]
@jeff-matthews has this page been updated?

**Comment by jeff-matthews** [comment]
No, but I'd rather remove this info altogether and just link to GH's docs. This type of content doesn't belong in our docs.
