### ISSUE TITLE
[2.2.0 RC] Install link is dead

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1240]
Feedback on page: [/guides/v2.2/release-notes/release-candidate/quick-start.html](http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/quick-start.html)

The link at the bottom of the page is dead:
> Ready to [install](http://devdocs.magento.com/guides/v2.2/release-candidate/install.html) Magento 2.2.0 Release Candidate?

Upd.: It seems that the link should lead to http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html instead.

**Comment by jfrontain** [comment]
Thanks, @korostii! Fixing now.

**Comment by korostii** [comment]
Upd.: It seems that the link should lead to http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html instead.

**Comment by jfrontain** [comment]
We really appreciate how closely you read our work, @korostii! Keep those comments coming!

**Comment by korostii** [comment]
NP, glad to be able to help =)

**Comment by jcalcaben** [comment]
Link is fixed! The change should take effect in the next publishing cycle. Thanks again @korostii !
