### ISSUE TITLE
[2.2.0 RC] Release notes: incomplete list of known issues

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1241]
Feedback on page: [/guides/v2.2/release-notes/release-notes-2-2-prerelease1-CE.html#breaking-issues](http://devdocs.magento.com/guides/v2.2/release-notes/release-notes-2-2-prerelease1-CE.html#breaking-issues)

There is this [short list of "breaking issues"](http://devdocs.magento.com/guides/v2.2/release-notes/release-notes-2-2-prerelease1-CE.html#breaking-issues). Not sure how the issues are picked for it (assuming: acknowledged, unresolved on develop), but, in any case, the list seems to be incomplete and will probably need to be updated rather frequently. 

Maybe a "View All" link underneath would be a good idea? Leading to a filtered GitHub Issues' view, similar to the following:
https://github.com/magento/magento2/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Adevelop%20label%3Aacknowledged

**Comment by jfrontain** [comment]
@korostii, great observations. Here's our current thinking: This short list includes only the highest level unresolved issues -- the show-stoppers -- that we are currently working on for this particular RC. We plan on releasing fresh RC code weekly, and will update this list to reflect the changes that occur between code drops. 

We can't list to a longer list right now for various reasons, one of which is the questionable utility of the list, which by nature of our rapid bug-fixing, changes frquently. But we will update it each Friday for the next 5 - 6 weeks. 

Once our 2.2.0 Release Candidate matures (and certainly for GA), we will publish a much more comprehensive accounting of both Fixed and Known (unresolved)  issues. 

Does that clarify our perspective a bit better?

**Comment by korostii** [comment]
Alright, that helps somewhat, but now I am not sure whether this list is relevant to the release notes, at all. I mean, these are the issues which are to be fixed in the _next_ version, not in the one just released... right? 

Maybe it should mention "this week" explicitly? Personally, I'd rather see the list separately, similarly to the "Component Status" page. Anyway, you seem to have it sorted out.


A bit off-topic, I looked through the 2.1.x release notes and they don't contain much known issues neither. Which is a bit strange, if you consider that all three "show-stoppers" mentioned for 2.2.0 RC are present in 2.1.7, as well.

Similarly, [release notes for 2.1.2](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.2CE.html) contain [GITHUB-6275](https://github.com/magento/magento2/issues/6275) as known issue, but isn't mentioned in [2.1.5](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.5CE.html) despite the fact that it's still an issue in 2.1.7. The fix was [merged](https://github.com/magento/magento2/pull/9590) into `2.1-develop` in May and isn't released to date. It's a bit disappointing to see this bug reported again and again (presumably because people expect it to be fixed in the next release|). @hostep counted 12 separate issue report [on his PR](https://github.com/magento/magento2/pull/9590)!

Not sure if it goes against some of your internal policies, but IMHO an honest, full list of known issues (or, at least, a small-font "view all minor known issues" link) would benefit everyone.

**Comment by jcalcaben** [comment]
Thanks for the input @korostii ! We will take this into account when we are developing our release notes.
