### ISSUE TITLE
Need to change Default PHP upload_max_filesize from 2Mb

### ISSUE THREAD

**Issue by cannycookie** [magento/devdocs#1244]
Feedback on page: /guides/v2.1/install-gde/docker/docker-over.html

**Comment by cannycookie** [comment]
Can anyone suggest how to change php.ini?

**Comment by cannycookie** [comment]
In docker-compose.yml add the following line under web volumes:-

`- "./shared/custom.ini:/usr/local/etc/php/conf.d/custom.ini"`

add required PHP.ini customisations into a new file shared/custom.ini :-

`upload_max_filesize = 64M`
`post_max_size = 64M`

Restart docker container:-

'docker-compose restart`

New PHP ini settings should be applied.

**Comment by jcalcaben** [comment]
Thanks for the feedback @cannycookie ! At the moment the DevBox project is on hold and there are no planned doc updates until it resumes.
