### ISSUE TITLE
2.2.0-release-candidate branch and magento2ce.git repo don't exist

### ISSUE THREAD

**Issue by WaPoNe** [magento/devdocs#1248]
Feedback on page: /guides/v2.2/release-notes/release-candidate/install.html

There are errors in this piece of documentation:

1. Clone the `magento2ce/` repository to your server’s docroot:

```
cd /var/www/html
git clone -b 2.2.0-release-candidate git@github.com:magento/magento2ce.git
```

It has to change into:

1. Clone the `magento2/` repository to your server’s docroot:

```
cd /var/www/html
git clone -b develop git@github.com:magento/magento2.git
```

**Comment by korostii** [comment]
Actually, as far as I know, magento2ce does exist, but isn't public.
Your argument still stands, of course: the instructions don't match the [repositories' list](http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html#release-candidate-1-code-repositories) above them.

**Comment by WaPoNe** [comment]
@korostii Exactly!
In any case, if **magento2ce** repository does exist, it will be private so don't accessible to everyone.

**Comment by jfrontain** [comment]
@korostii and @WaPoNe -- we'll follow up on these instructions today. Thanks!

**Comment by jeff-matthews** [comment]
Thanks @WaPoNe! I just updated the topic: http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html

**Comment by WaPoNe** [comment]
@jeff-matthews branch `2.2.0-release-candidate` doesn't exist in `magento2` repository so you have to change it with develop

Definitively it should be: `git clone -b develop git@github.com:magento/magento2.git`

**Comment by jeff-matthews** [comment]
@WaPoNe: Sorry, you're right. I'll push that update now.

**Comment by jeff-matthews** [comment]
See PR #1251

**Comment by WaPoNe** [comment]
I'm sorry @jeff-matthews but I continue to see `git clone -b 2.2.0-release-candidate git@github.com:magento/magento2.git` in the page..

**Comment by jeff-matthews** [comment]
@WaPoNe: I probably closed this issue prematurely. I'll wait until after the next CI/CD cycle before closing.

**Comment by jeff-matthews** [comment]
@WaPoNe: The changes are now live. 

http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html

**Comment by WaPoNe** [comment]
@jeff-matthews Great!
