### ISSUE TITLE
Data Migration Tool Preconditions don't mention SUPER privilege

### ISSUE THREAD

**Issue by bryanjswift** [magento/devdocs#1250]
Feedback on [devdocs/guides/v2.0/migration/migration-tool-preconditions.md](https://github.com/magento/devdocs/blob/develop/guides/v2.0/migration/migration-tool-preconditions.md)

Executing the Data Migration Tool requires the user connecting to the Magento 1 database has SUPER privileges. This should be mentioned in the preconditions documentation. Running the tool without the SUPER privilege causes errors during execution:

    [Zend_Db_Statement_Exception]                                                                                           
    SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable), query was:
    CREATE TRIGGER trg_catalog_compare_item_after_insert AFTER INSERT ON catalog_compare_item FOR EACH ROW                                                          
    BEGIN                                                                                                                   
    INSERT INTO m2_cl_catalog_compare_item (`catalog_compare_item_id`, `operation`) VALUES (NEW.catalog_compare_item_id, 'INSERT')ON DUPLICATE KEY UPDATE operation = 'INSERT';
    END

    [PDOException]                                                                                                          
    SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)

Yes the error tells you the exact problem but I'd prefer to have known about the requirement ahead of attempting the migration.

**Comment by victor-v-rad** [comment]
You wont have this issue if 
1. your Binary Logging is disabled in MySQL configuration
2. your Binary Logging is enabled and log_bin_trust_function_creators = 1 in MySQL configuration
3. your Binary Logging is enabled in MySQL configuration and SUPER privilege is set for your account

**Comment by dmrachkovskyi** [comment]
@bryanjswift, we've updated the Data Migration Tool's [Preconditions page](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-preconditions.html).
See the [Database section](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-preconditions.html#database) for detailed info.

If you find the doc update useful, please kindly close the issue. Thanks again for letting us know; we'll be looking forward to more feedback from you!

**Comment by bryanjswift** [comment]
Looks good to me. Thanks!
