### ISSUE TITLE
Explain the fallback mechanism in production mode

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#1253]
Feedback on page: /guides/v2.0/config-guide/bootstrap/magento-modes.html

The "Production mode" section mentions a "fallback mechanism" twice, but doesn't explain what it is. Please provide more context.

**Comment by antonkril** [comment]
The page states that the fallback is not used in production mode.

Static files (CSS, js, theme images, etc.) are served by the web server from 'pub/static' directory. In Magento those files are shipped in module and theme directories, that are not in 'pub/static'. So to make the static files available for the web server, they have to be 'materialized' - copied to pub/static.

In the default mode materialization happens "on demand" if a request comes to webserver for a file, but that file is not present in the pub/static, Magento will try to find it in module/theme/lib folders. If it finds it - the file is materialized and served. If not - 404 is returned.

In production mode, this "on demand" materialization or 'static file fallback' is switched off. The system admin is supposed to run `magento setup:static-content:deploy` to manually materialize all static during deployment.
