### ISSUE TITLE
Suggestion about unit test execution cli documentation

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#1257]
Feedback on page: /guides/v2.0/test/unit/unit_test_execution_cli.html

> To run all tests, navigate to the Magento base directory and execute the following command:
> $ ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist

Just a notice. 

Why not add to "To run all tests, navigate to the Magento base directory" a line "you can also use full path" or similar to indicate that the command can be run anywhere when used full bath to these files? That is of course is crystal clear, but to me it seemed that the sentence to be as command. Debatable ?

**Comment by dshevtsov** [comment]
@user3748173 thanks for your point!
But, in this case, given alternative will add some ambiguousness for novices in CLI.
