### ISSUE TITLE
Error in the code example of app/code/Learning/ClothingMaterial/Setup/InstallData.php

### ISSUE THREAD

**Issue by Eyal-Shalev** [magento/devdocs#1261]
Feedback on page: /videos/fundamentals/add-new-product-attribute/

The code example is missing a closing tag for the doc-block above the InstallData class

This is the code on the page
```
/**
* @codeCoverageIgnore
class InstallData implements InstallDataInterface
{
...
}
```

This is the fixed code
```
/**
* @codeCoverageIgnore
*/
class InstallData implements InstallDataInterface
{
...
}
```

**Comment by dmrachkovskyi** [comment]
@Eyal-Shalev , thanks for catching this! 

I've updated the [How to Add a New Product Attribute](http://devdocs.magento.com/videos/fundamentals/add-new-product-attribute/) page. Could you please take a look and close the issue?

Thanks again!
