### ISSUE TITLE
Please Correct This part

### ISSUE THREAD

**Issue by abelyanvahe** [magento/devdocs#1266]
Feedback on page: /guides/v2.2/migration/migration-overview-how.html

```
The data migration tool recognizes the differences in database structure between Magento 1.x versions. Most of these database structural differences are declared in map files. Each step in the process uses map files to transform data for use in your Magento 2 store.

For example, when you transform data from a Magento CE 1.8.0.0 database to Magento 2.x.x, the map file accounts 
```
Here you first mention that it sees the differences between Magento 1.x versions and then you give an example of Magento 1.x->Magento 2 differences.

**Comment by shrielenee** [comment]
Hey @abelyanvahe - thanks for pointing out this slight discrepancy. I'm creating a PR for this fix - [#1960](https://github.com/magento/devdocs/pull/1960). Check there for more information and let me know if you have any further questions.
