### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by abelyanvahe** [magento/devdocs#1267]
Feedback on page: /guides/v2.0/migration/migration-plan.html

You Say "horoughly test your Magento 2.x site.

Note that after such testing the next step (Incremental data update) might not work properly."

I don't understand why you say do testing and then you say after testing the next step will not work.

Thanks

**Comment by shrielenee** [comment]
Hey there @abelyanvahe - thanks for bringing this to our attention. I'm looking over the 2.0 doc page you mention and find no instance of this kind of phrasing. Just to be sure, I also checked v2.1, v2.2, and v2.3: it looks like that content doesn't appear in this doc.

I will be closing this issue, as it looks like what you're communicated has already been remedied. Thanks for taking the time to create a GitHub issue!

**Comment by keharper** [comment]
It was updated as a result of [PR 1611](https://github.com/magento/devdocs/pull/1611)
