### ISSUE TITLE
Please reflect that the background property of view.xml currently isn't working as expected

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1268]
Feedback on page: /guides/v2.1/frontend-dev-guide/themes/theme-images.html
As of 2.1.3, the `background` property is known not to work as described in the devdocs: [magento2/#8799](https://github.com/magento/magento2/issues/8799). Since this issue is acknowledged, it is safe to assume that 2.1.7 (and maybe even 2.2.0 RC) still has it.

Please update the [corresponding doc](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-images.html) in order to mention this known issue and possible workarounds (if any).

**Comment by korostii** [comment]
Hello there.
The [bug referenced](https://github.com/magento/magento2/issues/8799) is still an issue.

Are there any specific regulations regarding documenting \ not documenting known issues? 
I understand that fixing, and testing ,and releasing bugfixes goes slowly at Magento, but keeping documentation filled with corresponding warnings in the mid-time seems only humane, at the very least.

I would appreciate some kind of response, if possible. 
Thanks in advance & have a nice day.

**Comment by jfrontain** [comment]
Hi @korosti, and sorry for the delay in responding. I appreciate both your questions and frustration.

Quite honestly, it’s not just community members who are frustrated by how we handle known issues in the codebase; Magento employees would like to  better resolve and document these issues, too; we use this code. For us, it is a bandwidth issue — there are literally hundreds of 2.x issues opened on GitHub, and we simply don’t have the resources to resolve each reproducible issue as quickly as we’d like.

For the 2.x release notes, our policy is to document only known issues that first appear during testing for the current release. And that applies for major releases only. Obviously, that excludes dozens of issues logged on GitHub that are still part of the code base. I am not sure when that policy will become more inclusive, or when we might offer some other way to expedite the resolution of particular issues. I know the many of us are working both to more quickly resolve issues and document their fixes, where necessary.

For this specific issue, I can do my best to track down its probable fix, if one is scheduled. But I suspect that you, as an active community member, might know as much or more than I do.

And that brings me to one last thought: Have you thought about bringing this issue to the attention of the Community engineering team and perhaps seeing if you can get it in their sights?

I genuinely appreciate your feedback and wish I could offer you a more satisfying answer.

**Comment by korostii** [comment]
Hello & thank you so much for the answer. I really appreciate the effort.

Let my try to address your points the best I can.

> For us, it is a bandwidth issue — there are literally hundreds of 2.x issues opened on GitHub, and we simply don’t have the resources to resolve each reproducible issue as quickly as we’d like

Yes I understand that the (human) resources currently assigned to resolving issues are limited and can only cover some part of the issues (let's say "major" bugs). It's okay and it makes sense since Magento, Inc. is commercial company with limited resources and priorities with somewhat differ from the priorities of the developer community. It might lead to a reputation hit in the long run (i.e. developers recommending merchants not to use Magento 2.2 because it's too buggy or), but it's still up to the company.

> For the 2.x release notes, our policy is to document only known issues that first appear during testing for the current release.

Wow, just.. wow.
To be clear, I don't insist on any particular solution, but it's really sad to see the same issue reported multiple times on GitHub over a large period of time (just because it was never fixed nor publicly acknowledged).

Now that I think about it, maybe this could be something less official like a "User Contributed Notes" comment section similar to [what PHP's docs provide](http://php.net/manual/en/function.json-encode.php#106641) (voteable and\or pre-moderated) so that Magento, Inc. wouldn't have to take any responsibility for it or whatever's reason stopping you from including into the docs themselves. 

> For this specific issue
> Have you thought about bringing this issue to the attention of the Community engineering team

To make things clear: No, it's not like this one specific issue is show-stopper for me. I don't think this exact bug should have the top priority. However, there's a lot of times where something doesn't work and you're not sure whether your code is lacking something, or the core doesn't behave the way docs say it should. 
Since it's not likely that this bug will get any more attention under a reasonable timeframe (just like many others, let's say "minor" bugs), there should be a way to warn the developer community.

IMHO, something like "we know this feature isn't currently working as documented, click _here_ if you want to contribute to fixing it" would be plenty enough in this particular case. Otherwise it's actively misleading and potentially harmful to whoever happens to read it.


Anyway, if there doesn't seem to be any reasonable way to improve this situation under current policies, you may consider this a rant.
I'll close this issue, feel free to ignore it. Have a nice day!

**Comment by jfrontain** [comment]
hey @korostii, just wanted to add that I did not consider your comments here a rant -- I genuinely appreciate the conversation we were having. I am going to look at the PHP docs you recommend and see what I can learn from how they handle those types of issues. I can tell you that we in DevDocs are actively working on ways we can better engage the community to understand their needs and help hone our priorities. So please keep offering suggestions! I am all ears (and keyboard).

**Comment by korostii** [comment]
> I am going to look at the PHP docs you recommend and see what I can learn from how they handle those types of issues

They don't specifically do anything, but the user comments' section allows the community to add a kind of footnote warning about the quirks or potential side-effects which documentation fails to mention explicitly, write some best practices, post workarounds etc. 
It's not a perfect solution, of course, but it's still better than nothing. 

I guess some people might be already using [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) for this kind of content. Not sure if any kind of integration with it would be feasible, but I'd suggest looking into that as well (as an alternative). 

At the very least, a couple of simple boilerplate links to those in somewhere in the footer wouldn't hurt =)
