### ISSUE TITLE
Community contribution: Menu widgets

### ISSUE THREAD

**Issue by awilsonCurt** [magento/devdocs#1276]
Feedback on page: /guides/v2.0/javascript-dev-guide/widgets/widget_menu.html

This page contains almost no information on how to use this widget. There are no code samples, and only minimal information on the variables that should be included in options. There's essentially the generic widget documentation template with a link to the source code in it. It is extremely unhelpful.

**Comment by jeff-matthews** [comment]
Help us improve the [Menu widget](http://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_menu.html) topic by contributing working code samples and better descriptions of menu options. Refer to our [Contribution guidelines](http://devdocs.magento.com/guides/v2.2/contributor-guide/contributing_docs.html) for more information.

**Acceptance criteria:**
Your content must meet the following criteria:
- Sample code showing the use of the menu widget.
- Sample code showing the use of other widgets that are not documented, including [`dropdowndialog`](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_dialog.html) and [`list`](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_list.html)

**Comment by jfrontain** [comment]
We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the Frontend project.

**Comment by jeff-matthews** [comment]
Thank you @eduard13 for contributing the code sample!

Thank you @vasilii-b for contributing supplemental documentation about widget options!
