### ISSUE TITLE
Percona version support missing

### ISSUE THREAD

**Issue by mbrinton01** [magento/devdocs#1277]
Feedback on page: /guides/v2.2/install-gde/system-requirements-tech.html

This page needs to cover what versions of Percona are supported in version M2.2

The correct version should be 5.7 (which is used in Magento internal testing environments)

**Comment by jeff-matthews** [comment]
Thanks @mbrinton01. I'm using internal issue MAGETWO-70544 to track updates for 2.2 system requirements.

**Comment by jeff-matthews** [comment]
See [PR](https://github.com/magento/devdocs_internal/pull/992) in devdocs_internal/

**Comment by jeff-matthews** [comment]
Docs updated. See [Database](http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#database) section.
