### ISSUE TITLE
Misc modules belong in B2B section of this page

### ISSUE THREAD

**Issue by mbrinton01** [magento/devdocs#1283]
Feedback on page: /guides/v2.2/release-notes/release-candidate/component-status.html

Company Credit and Requisition lists should be moved to B2B Modules section of this page.  Please move them to this part.

**Comment by keharper** [comment]
@mbrinton01 After these changes, the "Misc Modules" section still lists two items. A question about each:

**Module/ Catalog/ Pricing** Do you think this is referring to the special/tier/base/cost enhancements? If so, should this be placed with the CE modules?

**Module/ RapidOrd** Is this a synonym for QuickOrder?

**Comment by mbrinton01** [comment]
Pricing – yes, place with CE
RapidOrd – check with Andrey Konosov. This may be the EE implementation of “quick order.” There is a separate one for B2B (already in the correct section) that is named “quick order”

Thank you,
Mark

**Comment by jcalcaben** [comment]
I will make these changes in tomorrow's scheduled update. Thanks @mbrinton01 !
