### ISSUE TITLE
what do you mean by "Your host’s IP address is 192.0.2.5"

### ISSUE THREAD

**Issue by victorw999** [magento/devdocs#1285]
Feedback on page: /guides/v2.0/install-gde/install-quick-ref.html

what do you mean by "Your host’s IP address is 192.0.2.5".
Is 192.0.2.5 simply a example IP? 
I don't have that IP on my VPS server. I only have a external IP.

https://magento.stackexchange.com/questions/183425/confusion-of-host-ip-address

**Comment by jeff-matthews** [comment]
@victorw999: That's just an example (private) IP address. You can configure whatever IP address (private/external) you want. I don't think including this particular example in the docs is helpful, so I'll remove it.

**Comment by jeff-matthews** [comment]
Docs updated: http://devdocs.magento.com/guides/v2.0/install-gde/install-quick-ref.html
