### ISSUE TITLE
Readiness check but making the prerequisites

### ISSUE THREAD

**Issue by mousebat** [magento/devdocs#1289]
Feedback on page: /guides/v2.0/install-gde/prereq/php-ubuntu.html

I'm running PHP Version 7.0.18-0ubuntu0.16.04.1

Getting the lack of php version in readiness check

Also have openssl module installed and enabled

**Comment by jeff-matthews** [comment]
@mousebat:  Magento v2.0 is compatible with PHP v7.0.x, so I'm not sure what's causing your readiness check failure. Have you tried searching the [Magento Stack Exchange](https://magento.stackexchange.com/) forum for a resolution to your issue?

**Comment by mousebat** [comment]
I have - could it be something to do with not having Cron Jobs set yet?

Many thanks

Elliot

**Comment by jeff-matthews** [comment]
It's possible. Are you using the Web Setup Wizard?

**Comment by mousebat** [comment]
Yes, I just unpacked magento in root, chown’d the directories and pointed the browser.  I guess I’ve missed a step or something! 

As an aside - I use ISPConfig 3.1 to manage my sites on this server - but even when I su into the website user, my command line php -v shows the same as the phpinfo page one.

Is there anything I can provide you with that would help?

**Comment by jeff-matthews** [comment]
I encourage you to follow the instructions in the docs first. It sounds like you're using a compressed Magento software archive. Have you followed the installation guide for that method?

http://devdocs.magento.com/guides/v2.0/install-gde/prereq/zip_install.html

**Comment by mousebat** [comment]
Hi Jeff

Thanks for your help, I’ve followed the guide to the letter and I’m still really having problems with the web setup wizard.  The below screenshot is as far as I can get:



Is there anything I can send you to help debug this?

Kind Regards

Elliot Cater

**Comment by mousebat** [comment]
Managed to get it installed by command line, it was not easy.  Composer needed updating as it was still using alpha version.

Install could really do with streamlining.  I’m no stranger to Unix, I live and breathe it, it puts food on my plate but it should not have taken me over 3 hours to work out how to get the base system of a web app installed!

Thanks for your direction…

Elliot

**Comment by jeff-matthews** [comment]
I'm glad you managed to get it installed! Sorry you had a bad experience with the install docs. We're actively working on improvements and always appreciate community feedback. Thanks for being patient with us.
