### ISSUE TITLE
Issue in admin Upgrading 2.1.1 to 2.1.7 

### ISSUE THREAD

**Issue by gab0019** [magento/devdocs#1291]
Fatal error: Uncaught Error: Call to a member function getId() on null in C:\web\magento\vendor\magento\framework\View\Model\Layout\Merge.php:751 Stack trace: #0 C:\web\magento\vendor\magento\framework\View\Model\Layout\Merge.php(684): Magento\Framework\View\Model\Layout\Merge->_getPhysicalTheme(Object(Magento\Theme\Model\Theme)) #1 C:\web\magento\vendor\magento\framework\View\Model\Layout\Merge.php(633): Magento\Framework\View\Model\Layout\Merge->_loadFileLayoutUpdatesXml() #2 C:\web\magento\var\generation\Magento\Framework\View\Model\Layout\Merge\Interceptor.php(232): Magento\Framework\View\Model\Layout\Merge->getFileLayoutUpdatesXml() #3 C:\web\magento\vendor\magento\framework\View\Model\Layout\Merge.php(527): Magento\Framework\View\Model\Layout\Merge\Interceptor->getFileLayoutUpdatesXml() #4 C:\web\magento\vendor\magento\framework\View\Model\Layout\Merge.php(506): Magento\Framework\View\Model\Layout\Merge->_fetchPackageLayoutUpdates('default') #5 C:\web\magento\vendor\magento\framework\View\Model\Layout\ in C:\web\magento\vendor\magento\framework\View\Model\Layout\Merge.php on line 751

please help me to fix this issue in admin.

**Comment by jcalcaben** [comment]
Please post this issue in the Magento2 repository:
https://github.com/magento/magento2

The devdocs repository is reserved for documentation issues.
