### ISSUE TITLE
no normal information

### ISSUE THREAD

**Issue by yehor-chernyshov** [magento/devdocs#1292]
Feedback on page: /guides/v2.0/config-guide/log/log-intro.html
FE i want to implement logstash and no exaples in Docs. very small docs

**Comment by yehor-chernyshov** [comment]
https://magento.stackexchange.com/questions/184050/how-use-logstash-in-magento2-in-docker

**Comment by akhan522** [comment]
Does anyone know how to fix this error: 

Class Magento\Framework\Serialize\Serializer\Json does not exist

I get this error clicking the save button on adding a new attribute

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
