### ISSUE TITLE
There is no code visible for me to copy to install Devbox from the command line.

### ISSUE THREAD

**Issue by NeuralNeurosis** [magento/devdocs#1297]
![invisible](https://user-images.githubusercontent.com/15053187/28373412-461cfffa-6c70-11e7-82bf-582d4ae5ab73.JPG)
Feedback on page: /guides/v2.1/install-gde/docker/docker-trouble.html

WHAT IS THE INSTALL COMMAND!! This is super frustrating. I can't find the install command anywhere else and it is not visible on the https://magento.com/tech-resources/downloads/magento/configure/  page. Please help.

**Comment by jeff-matthews** [comment]
@NeuralNeurosis, try `./m2devbox-init.sh` (Mac/Linnux) or `m2devbox-init.bat` (Windows). 

<img width="1274" alt="screen_shot_2017-07-19_at_11_16_05_am" src="https://user-images.githubusercontent.com/13662379/28378053-73e20256-6c74-11e7-81f6-d2de1f65efa3.png">

**Comment by NeuralNeurosis** [comment]
@jeff-matthews Thanks, I didn't think to use dev tools to look at the html, now I know to always check that first.

**Comment by jeff-matthews** [comment]
You shouldn't have to, but it's a good habit to get into. There's an open internal issue tracking that bug, so it should be fixed soon.
