### ISSUE TITLE
Magento 2 Impossible to install

### ISSUE THREAD

**Issue by JohnABCD** [magento/devdocs#1306]
Previously I owned magenta 1.x but started to get get massage to upgrade to magenta 2 and issues with PayPal. After 8 hours of trying to update Magento 1, I gave up. ( waste of time) I made a back up & completely delated my store. 

Bought a new shop theme $89 UAS and downloaded Magento 2. 
Paid my web host to upagede my private server to Easy Apache 4 & PHP7 cost me $75 USA. 
Went to read documentation how to install Magenta 2 
OMG!!!! 6 hours of reading without any one making sense. They say we need composer installed. Installed where and how to connect it to my website??? NO INFO!!!

I've used my domain name/setup went through the server check successfully, database... when it came to installing it hangs for hours... 

Looked all over you tube, everyone on of them, the guinness they are, using code that normal people would not know where to start. other have no sound, or using windows only.

I JUST NEED TO INSTALL THE FREAKING THING ON MY SEREVR THROUGH FTP!!
If it was Wordpress it would took my 10 min and done.

This cost me 3 days of my life, my store is down and i am out $150 USA.

Does any one know where to start without going through 10000 of pages to find small answer??

Thanks,

John

**Comment by paales** [comment]
Hi Joh, Great that you are setting up your Magento 2 store. It can be a little bit overwhelming at first, with all the new technologies required etc. Magento 2 hasn't got the ease-of-install that wordpress offers and requires a bit more knowledge about the environment, etc.

Have you read the following documentation page? http://devdocs.magento.com/guides/v2.1/install-gde/prereq/zip_install.html

As for further questions, this GitHub is about improvements to the documentation, not about questions about the software. To get help, you can try to ask your question here: https://magento.stackexchange.com/
