### ISSUE TITLE
Missing article about Integration test annotations (@magentoConfigFixture, @magentoAppArea)

### ISSUE THREAD

**Issue by paales** [magento/devdocs#1308]
I've found this article which explains a lot, but I'm unsure where to find references to this in code? http://dusanlukic.com/annotations-in-magento-2-integration-tests and thus if this article is complete.

**Comment by dshevtsov** [comment]
@paales 
Please check [a new topic](http://devdocs.magento.com/guides/v2.2/test/integration/annotations.html) with short overview of custom annotations that are available in integration tests.

**Comment by paales** [comment]
Ohw yeah! Nice

**Comment by dshevtsov** [comment]
Adding the annotations topics in #2665
