### ISSUE TITLE
Struggling to contribute to the contribution guide.

### ISSUE THREAD

**Issue by JamesAnelay** [magento/devdocs#132]
The link to github ("Edit this page on GitHub") on  http://devdocs.magento.com/guides/v1.0/contributor-guide/CONTRIBUTING.html / https://github.com/magento/devdocs/blob/master/guides/v1.0/contributor-guide/CONTRIBUTING.md is incorrect.

Rather than just fix it in a pull request I figured it's best to just raise an issue as the best fix may be to rename the file as it looks inconstant with a fully uppercase name.

**Comment by xcomSteveJohnson** [comment]
Fixed now. Leaving open for the time being. We regret the oversight.

http://devdocs.magento.com/guides/v1.0/contributor-guide/CONTRIBUTING.html

**Comment by xcomSteveJohnson** [comment]
Closing after no comment.
