### ISSUE TITLE
Trouble with Easy Install

### ISSUE THREAD

**Issue by rsiemens77** [magento/devdocs#1325]
Feedback on page: guides/v2.1/install-gde/prereq/zip_install.html

I followed the easy install procedure and used this software version:

Magento-CE-2.1.7-2017-05-30-01-54-40.tar.gz

Everything set up successfully, but when I click "Launch Magento Admin" on the success page, I get 404 not found.  If I browse to the magento dir I do get a home page, but it is just plain HTML (no styles), and all links also result in 404: login, create account,  my cart, etc. 

Something seems to be missing.

**Comment by jeff-matthews** [comment]
@rsiemens77: I'm assuming you're using an Apache web server. What you're reporting is usually an indication that your server rewrites aren't properly configured.

- http://devdocs.magento.com/guides/v2.1/install-gde/prereq/apache.html
- http://devdocs.magento.com/guides/v2.1/install-gde/trouble/tshoot_no-styles.html

Perhaps a short note in the topic explaining that would be helpful?

**Comment by rsiemens77** [comment]
OK, that sounds likely, thanks for the tip and references.

Perhaps it would be a nice test in the setup wizard to validate this has been set up.

A reference in the prerequisite check may also be helpful:

http://devdocs.magento.com/guides/v2.1/install-gde/prereq/prereq-overview.html

There's lots of pages with varying instructions, it's a little tricky to pull it all together, thanks again for the tip.

**Comment by jeff-matthews** [comment]
Yeah, you're right about there being lots of pages with varying instructions. I think having so many individual topics makes the task feel more complex than it is. For example, from the "Easy install" page, it takes **_8_** clicks/topics (if you go the Web Setup Wizard route) before you get to the "Verify installation" topic where we include a troubleshooting note about exactly what you experienced. That seems a little too buried to me.

I've been considering simplifying and consolidating all the steps necessary for installing Magento into a single topic or maybe two topics depending on technology stack (LAMP vs LEMP) and OS (Ubuntu vs Centos). I think that would help streamline the installation instructions.

**Comment by rsiemens77** [comment]
It looks like I already had the rewrite module:

# apachectl -M | sort | grep rewrite
 rewrite_module (shared)

Do you have any other advice to further debug this?  If the rewrite config is working?

**Comment by jeff-matthews** [comment]
Make sure *<Directory>* in
/etc/apache2/sites-available/000-default.conf is pointing
to your Magento installation directory. It should look something like this:

<Directory "/var/www/html/magento2">
    AllowOverride All
</Directory>

Note that the *AllowOverride All* setting my be insecure. Check out issue
#1224 <https://github.com/magento/devdocs/issues/1224> for more info.

**Comment by rsiemens77** [comment]
Thanks, I did get it working now.  I'm on RHEL7 so it was a little bit different.

**Comment by jeff-matthews** [comment]
Excellent!
