### ISSUE TITLE
Title is duplicated & unable to edit page

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#1327]
Page URL: http://devdocs.magento.com/guides/v2.2/mrg/ce/Analytics/description.html
Feedback on page: /guides/v2.2/mrg/ce/Analytics/description.html

There are two issues:
1. Page title is duplicated
2. "Edit this page on GitHub" returns 404 page.

**Comment by dshevtsov** [comment]
@ihor-sviziev thanks for the feedback!
This page doesn't exist anymore. The correct URL is http://devdocs.magento.com/guides/v2.2/mrg/ce/Analytics.html
I'll add a corresponding redirect to the page a bit later.

**Comment by dshevtsov** [comment]
Done.
Please check and close the ticket if the issue is resolved.

**Comment by ihor-sviziev** [comment]
Now it fixed. Thank you!
