### ISSUE TITLE
composer.json example for Module dependencies question

### ISSUE THREAD

**Issue by tonegolf71** [magento/devdocs#133]
Firstly in: `/guides/v1.0/architecture/modules/mod_depend.html` there is a problem on line 48 where &lt;Vendor> is not being displayed due to not being escaped.

Although this calls into question whether &lt;Vendor> should just be "Magento" anyway? Based on the content of the example? (name being magento/module-catalog)

**Comment by xcomSteveJohnson** [comment]
Fixed. Please close this issue if you're happy with the resolution.

http://devdocs.magento.com/guides/v1.0/architecture/modules/mod_depend.html
