### ISSUE TITLE
Wrong file name

### ISSUE THREAD

**Issue by sourabhmodi60** [magento/devdocs#1330]
Feedback on page: /videos/fundamentals/create-a-new-module/

**In last paragraph of this page, you have mentioned**

So far, we haven’t added any useful code to our module – it is still empty (and therefore invisible). In order to verify that it has been recognized, check the file **app/etc/env.php.** It has a list of auto-generated modules that are active.

**It is not app/etc/env.php. it should be app/etc/config.php.**

**Comment by lorikrell** [comment]
Updating this information today. Thank you!

**Comment by lorikrell** [comment]
Thanks for the heads up and feedback @sourabhmodi60 ! The content pushes live this morning.

Lori

**Comment by lorikrell** [comment]
Content live. Thanks!
