### ISSUE TITLE
Upgrade pelago/emogrifier to the latest version

### ISSUE THREAD

**Issue by franckgarnier21** [magento/devdocs#1337]
Feedback on page: /guides/v2.2/release-notes/thirdparty_ee.html

Hello,

Do you plan to upgrade the pelago/emogrifier dependency to the latest version ?

Which is a known issue with mail styling in production mode with Magento 2.1.7 : https://magento.stackexchange.com/questions/179203/magento-2-override-extend-the-email-css-that-is-being-used-in-the-transactional/179460#179460

Thanks,

**Comment by jcalcaben** [comment]
@jfrontain can you follow up with this issue?

**Comment by jfrontain** [comment]
@franckgarnier21, we've just updated the third-party license information for 2.2. Thanks for your help and your patience!
