### ISSUE TITLE
URL is case sensitive

### ISSUE THREAD

**Issue by AlexVandenKerkhof** [magento/devdocs#1340]
Feedback on page: /guides/v2.0/install-gde/trouble/tshoot_admin.html

Another cause of not being able to access the admin URL it is case sensitive, even on Windows platform. During the installation I used all lower case characters but the directory name on disk was in capital. You have to check the record web/unsecure/base_url in the table core_config_data. The URL you are using must match this value.

**Comment by jeff-matthews** [comment]
Thanks @AlexVandenKerkhof! The updated docs will be published when I merge the `imagine-2018` branch with the `develop` branch, which I plan on doing tomorrow. See linked PR.
