### ISSUE TITLE
Dear Devs I am struggling with creating attribute in Magento 2

### ISSUE THREAD

**Issue by akhan522** [magento/devdocs#1344]
Error: Class Magento\Framework\Serialize\Serializer\Json does not exist

I really need help with creating an attribute. When I hit save button I get a redirection to error: Class Magento\Framework\Serialize\Serializer\Json does not existand 

Can anyone please help me. I posted this issue for help but I am not getting any answers.

**Comment by jcalcaben** [comment]
Hi @akhan522 ,
Have you reviewed the docs for the Serializer?
http://devdocs.magento.com/guides/v2.2/extension-dev-guide/framework/serializer.html

**Comment by keharper** [comment]
Closing due to lack of response.
