### ISSUE TITLE
Typo in Issue reference

### ISSUE THREAD

**Issue by Drakhunter** [magento/devdocs#1346]
Feedback on page: /guides/v2.1/release-notes/ReleaseNotes2.1.8CE.html

On Chapter "Import/Export" the following Point:

> Magento now imports customer data as expected after the data passes the pre-import validation step. Previously, although data passed this validation step, an error would occur during import, and Magento displayed this message: Invalid data for insert. GitHub-**4921**, GitHub-9469

This Issue seems to be wrong. The Correct one is [https://github.com/magento/magento2/issues/4291](4291)

Just to prevent any more people beeing confused like me ;)

**Comment by jfrontain** [comment]
Thank you, @Drakhunter! Will fix that right away. I don't want to add confusion to the matter.

**Comment by jfrontain** [comment]
Thanks for closing, @Drakhunter; I've merged the change, but it might be a few minutes before the change shows up on our public website.
