### ISSUE TITLE
Where's the MAGE_RUN_CODE

### ISSUE THREAD

**Issue by WileESpaghetti** [magento/devdocs#1347]
Feedback on page: /guides/v2.1/config-guide/multi-site/ms_nginx.html

Please include instructions on how to find the MAGE_RUN_CODE that we need to put in the nginx config

**Comment by jeff-matthews** [comment]
@WileESpaghetti: I'll update the topic with instructions on where to find the code. In the meantime, just in case you're stuck, you can find the code field by logging in to Admin, clicking **Stores** > **Settings** > **All Stores** > **<you store>**. The value in the Code field is the value you need to include in the  config.

http://devdocs.magento.com/guides/v2.0/config-guide/multi-site/ms_websites.html#step-2-create-websites

![code](https://user-images.githubusercontent.com/13662379/29288251-af647988-80fd-11e7-8efc-b86bae2ba0bd.png)

**Comment by WileESpaghetti** [comment]
Perfect, thanks!
