### ISSUE TITLE
How to list catalogProduct with pagenation?

### ISSUE THREAD

**Issue by st2forget** [magento/devdocs#1348]
I'm calling SOAP service from C# application, I need to list all products that are enabled (status = 2) with pagination (pageSize = 500). the filter object only let me filter the status. How could I add pagination to the query?

```
            var filters = new filters
            {
                filter = new List<associativeEntity>
                {
                    new associativeEntity
                    {
                        key = "status",
                        value = "2"
                    }
                }.ToArray()
            };
            var client = (PortTypeClient) IndexItem.Indexer.Connection.ApiConnector.Client;
            var entities = client
                .catalogProductList(
                    ((ISoapApiConnector)IndexItem.Indexer.Connection.ApiConnector).SessionId,
                    filters,
                    IndexItem.Indexer.Connection.ResourceConnection.StoreId
                );
```

**Comment by keharper** [comment]
@st2forget I can't really help with the C# programming. See these article about performing searches and limiting the results. They're REST-centric, but they should contain the type of information you're looking for. 

http://devdocs.magento.com/guides/v2.1/howdoi/webapi/search-criteria.html

http://devdocs.magento.com/guides/v2.1/howdoi/webapi/filter-response.html

Let me know if this helps.

**Comment by shrielenee** [comment]
Hey @st2forget - Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/).

Thanks for taking the time to create a GitHub issue for docs improvement!
