### ISSUE TITLE
Cloud: Galara database cluster => Galera database cluster

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1352]
Feedback on page: /guides/v2.2/cloud/reference/discover-arch.html

`Galara` should be named `Galera` ;)

**Comment by hostep** [comment]
Same problem on: http://devdocs.magento.com/guides/v2.2/cloud/access-acct/first-time-setup.html

**Comment by convenient** [comment]
https://github.com/magento/devdocs/edit/develop/guides/v2.0/cloud/reference/discover-arch.md

Should be able to fix it straight from the github UI :)

**Comment by hostep** [comment]
@convenient: ok cool, didn't knew this. But I prefer to clone the devdocs source so I can more easily search for other occurrences for example.

(I realize that creating all these individual tickets is maybe a bit much, but I'm currently doing some research on the Cloud environment for a client of ours, so I'm just reporting issues I'm running into, will try to fix them using PR's (later on if I have the time/energy for it :)))
