### ISSUE TITLE
Cloud: Link to more info about disabled composer marshaling is a bit confusing

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1353]
Feedback on page: /guides/v2.2/cloud/reference/cloud-composer.html

At the bottom of the page, we see this line: 'For more information, see Test a Magento patch.'

This links to http://devdocs.magento.com/guides/v2.2/cloud/project/project-upgrade.html, which I *think* is correct, but then I would change the link text from 'Test a Magento patch' to 'Upgrade and test Magento Commerce' or something like that.

If the link text is currently correct though, then the link is incorrect and it should probably go to http://devdocs.magento.com/guides/v2.2/cloud/howtos/patch-magento.html

It's a bit hard to say which one is correct, both pages talk about the disabled marshaling of composer in the cloud.

Also, the very last line on the page contains a typo I think:
'If you notice any problems after **a** deploying an updated version of Magento, ...' should be
'If you notice any problems after deploying an updated version of Magento, ...'

**Comment by lorikrell** [comment]
Thanks, I accepted the PR and checking into content further for additional updates.

**Comment by lorikrell** [comment]
Getting final updates and making sure your PR is in the latest code @hostep ! Pushing updates this morning.
:)
Lori

**Comment by lorikrell** [comment]
Content live. Thanks!
