### ISSUE TITLE
Cloud: mysql - grant all priviledges => grant all privileges

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1355]
Feedback on page: /guides/v2.2/cloud/before/before-workspace-magento-prereqs.html

In the database part of the page, it says:
'grant all privile**d**ges on `<database>` to ...', this should be: 'grant all privileges on `<database>` to ...'

----

On the same page:
'for consist**a**nt data', should be 'for consistent data'

----

On the same page, the formatting of the following seems incorrect (the `<pre>` tag shouldn't be visible I think?)
```
<pre class="no-copy">source /home/magento_user/.bashrc</pre>
```

----

On the same page, the link to '.bash_profile vs .bashrc': http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html isn't working currently (this might be a temporary glitch).
I can still view the content of the page using googles cache though: http://webcache.googleusercontent.com/search?q=cache%3Awww.joshstaiger.org%2Farchives%2F2005%2F07%2Fbash_profile_vs.html&oq=cache%3Awww.joshstaiger.org%2Farchives%2F2005%2F07%2Fbash_profile_vs.html

**Comment by lorikrell** [comment]
Thanks! I accepted the PR and will verify any further edits and content.

**Comment by lorikrell** [comment]
Verified any remaining issues, made fixes, and pushing live this morning. I really appreciate all of your feedback @hostep! For all of your PRs and open issues. :) Pushing updates and tweaks to make sure your work is captured in the latest.

Lori

**Comment by lorikrell** [comment]
Content live. Thanks!
