### ISSUE TITLE
Missing Page: Set up logging

### ISSUE THREAD

**Issue by matthew0918** [magento/devdocs#1361]
http://devdocs.magento.com/guides/v2.2/config-guide/log/log-intro.html

**Comment by matthew0918** [comment]
Linked to from the page below "Set up logging"
http://devdocs.magento.com/guides/v2.2/howdoi/config/configure.html

**Comment by matthew0918** [comment]
I believe this is the page it previously linked to and it didn't get copied over for v2.2
http://devdocs.magento.com/guides/v2.1/config-guide/log/log-intro.html

**Comment by jeff-matthews** [comment]
Thanks @matthew0918. I fixed it.
