### ISSUE TITLE
Homepage - Tooltip adds scroll on mobile

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#1370]
Try to see release candidate popup on homepage. On click on the link - we have scroll. See screenshots below:
![screenshot_20170819-162645](https://user-images.githubusercontent.com/1873745/29487021-7f47956c-84fb-11e7-9cdc-8e2bd5f1bc96.png)
![screenshot_20170819-162702](https://user-images.githubusercontent.com/1873745/29487023-869ebe08-84fb-11e7-8185-74648fc59572.png)

**Comment by shrielenee** [comment]
Hey there - thanks for bringing this to our attention. This issue is no longer relevant, as this release candidate messaging is no longer visible on our site and we have no moved on to v2.3 (pre-release) docs. I will close this issue at this time.

Thanks for taking the time! Keep 'em coming.
