### ISSUE TITLE
A typo in "Galara db cluster"

### ISSUE THREAD

**Issue by Oxidant** [magento/devdocs#1371]
Feedback on page: /guides/v2.1/cloud/reference/discover-arch.html

you posted the following:
"Galara database cluster with a MariaDB MySQL database per node with an auto-increment setting of 3 for unique IDs across every database"
but the real name of the cluster is "Galera".

**Comment by hostep** [comment]
Will be fixed by https://github.com/magento/devdocs/pull/1358 ;)

**Comment by lorikrell** [comment]
Thanks and already accepted the previous PR, verifying content. :)

**Comment by lorikrell** [comment]
Already live and fixed, verified. Thanks again @hostep !
