### ISSUE TITLE
Cron Readiness bug?

### ISSUE THREAD

**Issue by drillsar** [magento/devdocs#1379]
Keep getting permission errors and I think permissions correct? I can't reindex using cron.

**Comment by jeff-matthews** [comment]
Hi @drillsar, 

This repo is for issues related to [Magento developer documentation](http://devdocs.magento.com/). This sounds like a code or environment issue. 

If our [Troubleshoot cron](http://devdocs.magento.com/guides/v2.1/comp-mgr/trouble/cman/cron.html) topic doesn't help you, please check the [magento/magento2](https://github.com/magento/magento2) repo for bugs or try [Magento Stack Exchange](https://magento.stackexchange.com/).
