### ISSUE TITLE
"is_subscribed" extension attribute not populating in customer GET /V1/customers/:customerId  API

### ISSUE THREAD

**Issue by allamsettiramesh** [magento/devdocs#1384]
Team, I trying to get the customer details with "is_subscribed" extension attribute but this vale not populating in API result
It returns like:
`{
    "id": 55,
    "group_id": 1,
    "default_billing": "35",
    "default_shipping": "35",
    "created_at": "2017-08-22 13:50:38",
    "updated_at": "2017-08-22 15:30:15",
    "created_in": "Default Store View",
    "dob": "2017-08-20",
    "email": "test1@gmail.com",
    "firstname": "Test",
    "lastname": "test",
    "gender": 1,
    "store_id": 1,
    "website_id": 1,
    "addresses": [
        {
            "id": 35,
            "customer_id": 55,
            "region": {
                "region_code": "test",
                "region": "test",
                "region_id": 0
            },
            "region_id": 0,
            "country_id": "IN",
            "street": [
                "test",
                "test",
                "test"
            ],
            "telephone": "1234567890",
            "postcode": "12345",
            "city": "test",
            "firstname": "Test",
            "lastname": "test",
            "default_shipping": true,
            "default_billing": true
        }
    ],
    "disable_auto_group_change": 0,
    "custom_attributes": [
        {
            "attribute_code": "nationality",
            "value": "test"
        },
        {
            "attribute_code": "nric_no",
            "value": "1234567890"
        },
        {
            "attribute_code": "occupation",
            "value": "test"
        },
        {
            "attribute_code": "grade",
            "value": "2"
        },
        {
            "attribute_code": "homenumber",
            "value": "1234567890"
        },
        {
            "attribute_code": "mobilenumber",
            "value": "1234567890"
        },
        {
            "attribute_code": "instrument_choice",
            "value": "2,3,4,5,6,7,8"
        },
        {
            "attribute_code": "referral",
            "value": "1,2,3"
        },
        {
            "attribute_code": "title",
            "value": "1"
        }
    ]
}`

**Comment by keharper** [comment]
@allamsettiramesh I think you've found a bug. I created a customer that included

```
		"extension_attributes": {
			"is_subscribed": true
		}
```
Then I went to the customer's page in Admin and verified that the "Subscribe to Newsletter" checkbox is checked.

Then I ran `GET /V1/customers/:customerid`, and I see that `is_subscribed` is not included in the response. It is also omitted from a PUT response.

I'll try to get confirmation on this. It might take hours, it might take weeks.

**Comment by allamsettiramesh** [comment]
Thanks @keharper

**Comment by arielmorry** [comment]
Hi, any updates on this?
GET /V1/customers/{id} still not returning is_subscribed
Magento 2.2

**Comment by keharper** [comment]
I opened internal issue MAGETWO-71829 in September, and it hasn't been prioritzed, so this problem will be present in 2.2.2 as well.

I'm closing this PR, because it's really addressing a code bug.

**Comment by lenlorijn** [comment]
Sorry for reopening the issue here, but I can't find any other public place to reopen it.
It seems like the issue in  MAGETWO-71829 is fixed in 2.3 as it now returns 'is_subscribed' in the API. However, it does not return `is_subscribed` for `rest/V1/customers/search?searchCriteria` only for `rest/V1/customers/id`. 
Is this a separate bug/issue?

**Comment by keharper** [comment]
Hi @lenlorijn. It looks like the original issue was resolved in 2.2.4. The internal ticket I opened addressed `GET /V1/customers/:customerId` only, and so it seems that `GET V1/customers/search?searchCriteria` would be a separate bug.

Please report the bug at https://github.com/magento/magento2/issues
