### ISSUE TITLE
Missing contents

### ISSUE THREAD

**Issue by divivu** [magento/devdocs#1385]
Feedback on page: /guides/v2.1/frontend-dev-guide/layouts/layout-extend.html

Seem to be missing more contents on this page

**Comment by bdenham** [comment]
Hi @divivu, it's been a while, but what content would you like to see added to this page? Thanks.

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
