### ISSUE TITLE
How to use third-party-libs without Compose 

### ISSUE THREAD

**Issue by hiteshvaghasiya83** [magento/devdocs#1386]
Hello Magento,

You have very new doc for magento 2.x . Really Thanks for this doc.

but in :  [http://devdocs.magento.com/guides/v2.1/architecture/archi_perspectives/third-party-libs.html](http://devdocs.magento.com/guides/v2.1/architecture/archi_perspectives/third-party-libs.html)

Can you please explain in depth, How to used Third Party PHP libs in magento 2 and how to call in to Extension and in magento.  

Thanks  a Ton,
Hitesh Vaghasiya

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
