### ISSUE TITLE
SOAP API dev docs shoppingCartCreate doc incorrect

### ISSUE THREAD

**Issue by Orstio** [magento/devdocs#1393]
http://devdocs.magento.com/guides/m1x/api/soap/checkout/cart/cart.create.html

In the WS-I compliance mode code example, the variable "storeId" is given, but in the actual code, only "store" works.

Incorrect code:
`$result = $proxy->shoppingCartCreate((object)array('sessionId' => $sessionId->result, 'storeId' => '3'));`

Should be:
`$result = $proxy->shoppingCartCreate((object)array('sessionId' => $sessionId->result, 'store' => '3'));`

**Comment by Orstio** [comment]
Relevant code is wsi.xml in Magento code:
`            <xsd:element name="shoppingCartCreateRequestParam">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="1" maxOccurs="1" name="sessionId" type="xsd:string" />
                        <xsd:element minOccurs="0" maxOccurs="1" name="store" type="xsd:string" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>`

**Comment by keharper** [comment]
Thanks @Orstio  I especially appreciate that you provided the supporting code.
