### ISSUE TITLE
"Magento\Framework\Object" - no such dir

### ISSUE THREAD

**Issue by divivu** [magento/devdocs#1397]
Feedback on page: /guides/v2.1/architecture/archi_perspectives/framework.html

Can not locate this path on magento2 source tree, no such directory on the source code: 
"Magento\Framework\Object"

**Comment by jfrontain** [comment]
Thanks @divivu! That directory has changed to Magento\Framework\DataObject. I will update this topic shortly.

**Comment by jcalcaben** [comment]
Hi @divivu 

This has been fixed. Thanks for reporting this!

https://devdocs.magento.com/guides/v2.1/architecture/archi_perspectives/framework.html
