### ISSUE TITLE
Cloud, default git remote is called 'magento', not 'origin'

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1400]
Feedback on page: [/guides/v2.2/cloud/before/before-setup-env-2_clone.html](http://devdocs.magento.com/guides/v2.2/cloud/before/before-setup-env-2_clone.html)

Hi, I just got access to our first Magento Cloud project, and noticed while going through the steps in the page linked above, that in step 8 and 9, the git remote name is incorrect, it should be `magento` instead of `origin`.
Not sure if this is incorrect on other pages as well, maybe best to search through the cloud documentation to find other occurrences of this.

(I might create a PR for this later when I find some time)

**Comment by lorikrell** [comment]
Not to worry, I will get this corrected asap!

**Comment by lorikrell** [comment]
Content live. Thanks!
