### ISSUE TITLE
Cloud: variables don't have checkboxes for visibility

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1402]
Feedback on page: [/guides/v2.2/cloud/before/before-setup-env-keys.html](http://devdocs.magento.com/guides/v2.2/cloud/before/before-setup-env-keys.html)

In step 9 it says:

> Select the Visible during build check box. Clear the other check boxes.

If I test this, I only see one checkbox and not 3 checkboxes. The only one available is: `JSON value`.

So the other two should be removed from the screenshot and the text should be modified to:
`Don't check the 'JSON value' checkbox` or something like that.

I tested it and it looks like it works.

**Comment by lorikrell** [comment]
I'll check into this and get it updated.

**Comment by lorikrell** [comment]
I just verified and do see up to three checkbox options. It may be due to role and permissions for the user account. I'll revise and add a note just in case. Thank you!

**Comment by hostep** [comment]
Ok, good to know, thanks!

**Comment by lorikrell** [comment]
Added a revision, thanks for the heads up @hostep! :) Pushing updates and tweaks to make sure your work is captured in the latest.

Lori

**Comment by lorikrell** [comment]
All updates are live. Closing issue. 
Thanks!

**Comment by hostep** [comment]
Great!

2 remarks though:
- little typo: `Visible agt runtime`
- I didn't see any of the two `Visible` checkboxes, only only saw the `JSON value` one

**Comment by lorikrell** [comment]
Hmm, ok checking with engineering right quick and pushing more notes!

**Comment by hostep** [comment]
Ok, so I was wrong in my statement above that it works, because the composer cache was being used during my test deploy, it didn't need the access keys. I now updated some dependencies and now the deploy no longer works because the authentication key couldn't be found anymore.

But apparently I don't have the necessary access rights and was adding this variable to the **environment** configuration, while the variable should be added the the **project** configuration.
I asked the product owner to do this, because I don't have access to the project configuration, and now it seems to work.

Also maybe good to know, the checkbox `JSON value` is the only one available in the **environment** configuration, also for the Project Owner. The 3 checkboxes are only available in the **project** configuration as far as I understand it correctly.

Sorry, I didn't read the documentation properly, my mistake!

**Comment by lorikrell** [comment]
Totally fine @hostep, still some good notes and tweaks can come out of this. There are so many keys, authentication bits, credentials and environment vs project vs local it can be crazy. Having a list of all creds/keys, where they go, what they affect is on my list. :)
