### ISSUE TITLE
Typo in REST endpoint URL

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1404]
Feedback on page: /guides/v2.0/rest/generate-local.html

In the section http://devdocs.magento.com/guides/v2.0/rest/generate-local.html#return-the-json-schema-for-one-or-more-services, it talks about the URL http://<magento_host>/rest/<store_code>/schema&services=<serviceName1,serviceName2,..>.

I believe that the "&" should be a "?" as shown in the example in the same section "http://<magento_host>/rest/default/schema?services=catalogProductRepositoryV1"

**Comment by keharper** [comment]
@dougkm You're correct. Thanks for pointing this out.
