### ISSUE TITLE
Cloud: magento-cloud command to create database dump is incorrect

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1405]
Feedback on page: [/guides/v2.1/cloud/howtos/patch-magento.html](http://devdocs.magento.com/guides/v2.1/cloud/howtos/patch-magento.html)

In Step 1 of 'Back up the database', it says:
> magento-cloud environment:mysql-dump

But this command doesn't exist (any more?), it should be replace with this I think:
> magento-cloud db:dump

Also on: http://devdocs.magento.com/guides/v2.1/cloud/howtos/upgrade-magento.html
The command is listed as:
> magento-cloud environment:sql-dump

Which does exist, but is not documented when running: `magento-cloud list`, it looks like it is an alias of `db:dump`, so maybe best to replace that one as well.

**Comment by lorikrell** [comment]
Thanks @hostep  checking the commands out! I'll search, check, and update across all cloud content.

**Comment by lorikrell** [comment]
Verified against the latest CLI commands. Updated these items and verified others around DB commands. Thanks @hostep ! Should see this information posted live shortly.
