### ISSUE TITLE
magento 2.1 with sampledata not mobile friendly

### ISSUE THREAD

**Issue by tgoeminne** [magento/devdocs#1407]
Hi,

I just wanted to point out that the sampledata is not mobile friendly. The pages showing the promo blocks are not rendering nicely on mobile devices. Is this normal? Maybe this could be fixed in future version to adjust the sampledata so it can be mobile friendly?

Greets,
Thomas

**Comment by keharper** [comment]
@tgoeminne You would be better off creating an issue in the main Magento repository at https://github.com/magento/magento2 because this is a code problem. I suggest providing some screenshots to help show what's not working correctly.
