### ISSUE TITLE
Code snippet duplication; missing WebAPI/UI handler file

### ISSUE THREAD

**Issue by danmooney2** [magento/devdocs#1409]
[Link](http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_handler.html)

The Curl handler snippet (long one with detailed comments for better understanding) is duplicated below twice in lieu of actual WebAPI/UI handler examples.

**Comment by jcalcaben** [comment]
@dshevtsov what is the status of this issue?

**Comment by shrielenee** [comment]
Hi @dshevtsov - Can you take a look at this? Thanks! 💯

**Comment by shrielenee** [comment]
Thanks for bringing this to our attention! This definitely needs to be fixed and we are creating an internal ticket to track it and begin work. If you have any further questions feel free to comment here or reopen the issue. 👍

**Comment by hguthrie** [comment]
MAGEDOC-3125
