### ISSUE TITLE
Message Queues

### ISSUE THREAD

**Issue by slackerzz** [magento/devdocs#1410]
Feedback on page: /guides/v2.1/extension-dev-guide/message-queues.html
namespace ```\Magento\Framework\Amqp``` doesn't exist (at least in magento 2.1)

**Comment by keharper** [comment]
You're correct. It looks like it should have been `MessageQueue` instead of `Amqp`. I'll confirm and correct the info soon.

**Comment by keharper** [comment]
I've posted the corrections. Thanks for pointing this out.
