### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by roseofgold** [magento/devdocs#1430]
Feedback on page: /guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html

The link  Upgrade to Magento version 2.1 (June 22, 2016) returns a 404 page.

**Comment by Aekal** [comment]
These links don't work too:
- http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/admin_theme_create.html
- http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/admin_theme_apply.html

**Comment by jcalcaben** [comment]
Thanks @Aekal ! I have fixed the broken links and the changes should be live soon.
