### ISSUE TITLE
Cloud: elasticsearch configuration documentation can be improved a little bit.

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1431]
Feedback on page: /guides/v2.1/cloud/project/project-conf-files_services-elastic.html

I just tried setting up ElasticSearch on a cloud project, and had a hard time figuring out why the 'test connection' button didn't work in the Catalog Search configuration settings in the backend of Magento.

In the end, it turned out it was because of the field 'Elasticsearch Server Hostname', which was set to `localhost`. We had to change it to `elasticsearch.internal` which we found by executing the command:
`php -r 'print_r(json_decode(base64_decode($_ENV["MAGENTO_CLOUD_RELATIONSHIPS"])));'`

The docs can probably be improved a little bit by explicitly mentioning this?

----

Also, the section 'Add Elasticsearch to your site' isn't really useful and is a bit confusing, since we don't need it to configure Magento specifically, it is only necessary for custom non-Magento code/scripts I believe? From the looks of it, it looks like it's just been copy/pasted from https://docs.platform.sh/configuration/services/elasticsearch.html
It's probably not bad to mention this code for people still wanting to connect to ElasticSearch but not using Magento itself in their scripts. But it should be mentioned that this code isn't necessary to configure Magento itself with ElasticSearch which confused me a little bit.

**Comment by lorikrell** [comment]
Thanks for the feedback. Checking into this and will get updates soon as I can.

**Comment by lorikrell** [comment]
Thanks for the great feedback and heads up, @hostep. I reviewed the content with dev. I have updated all code, info, links, and removed any unnecessary content that carried over from Platform.sh. You should see the Elasticsearch, services.yaml, and all other services topics for Cloud updated today. :)

**Comment by hostep** [comment]
Thanks Lori, great job!

**Comment by lorikrell** [comment]
:D Thanks! Team effort with your feedback and my typing!
