### ISSUE TITLE
2.2.0 release notes remarks, a lot of mistakes in there

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1432]
Feedback on page: /guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html

> You can now run magento setup:upgrade --keep-generated in production mode. Previously, Magento would throw an error when you ran setup:upgrade after compiling dependency injection. (This significantly curtailed your ability to deploy continuous integration.) GitHub-4795

This was fixed in Magento 2.1.1, so it makes no sense to have this on the Magento 2.2.0 release notes.
Be aware, this is also mentioned twice in the release notes, so you have to remove it twice. (first and thirteenth bullet point under the 'Installation, upgrade, deployment')

> Magento now correctly applies website configuration parameters to the corresponding store view. GitHub-7943

Same problem, this was already fixed in Magento 2.1.4, shouldn't be mentioned in the 2.2.0 release notes.

> Magento no longer throws an exception when the configuration checksum is absent on a new installation.

This has been reported twice in the release notes (eight and fourteenth bullet point)

> Magento no longer throws an exception when the configuration checksum is absent on a new installation.

> We fixed an issue that blocked using the web installer to successfully set up Magento. Previously, if you tried to install Magento with the web installer, Magento would indicate that the readiness check failed, and installation would not complete.

> You can now deploy build processes on a different staging machine than the one you’re running your production environment on.

> Magento now implements the minicart maximum display recently added item setting to your shopping cart. Previously, Magento displayed all the items in the shopping cart, even when the number of items exceeded this limit. GitHub-4750

> Magento no longer locks the category_product_entity table. Unlocking this table reduces the potential of lock-related timeouts that can occur when indexing and checkout operations run in parallel. Previously, Magento locked the category_product_entity table.

> You can now save a product with images multiple times.

> The category page now shows the current price after Magento runs a scheduled update. Previously, the category page would not update the price after running a scheduled update.	GitHub-4945

> ... (I have given up, their are too many duplicated fixes being mentioned)

Same thing, they are all mentioned twice, please clean those up :)

> JavaScript translations of warning messages no longer appear in the language of the primary locale only. Previously, optimizations that we made to static content deployment inadvertently generated the content only in the language of the primary locale, and then copied that directory to the other requested locales. GitHub-7862

This is **not** fixed, it broke again in Magento 2.2.0 after fixing it in a related issue.
See https://github.com/magento/magento2/issues/7862#issuecomment-331247899 for more details

> Magento now successfully loads the New Order Email templates. GitHub-5101

This was fixed in Magento 2.1.3, so it makes no sense to have this on the Magento 2.2.0 release notes.

> We’ve resolved issues with selecting widgets in TinyMCE. GitHub-9655, GitHub-9518

> Static content deployment now generates secure content, whether content included secure or non-secure URLs.

> Widgets now accept UTF-8 special characters type as input parameters. Previously, you could successfully create a widget, but UTF-8 special characters were broken.

These were all fixed in Magento 2.1.8, so it makes no sense to have this on the Magento 2.2.0 release notes.

> Magento now caches image metadata, which avoids the time-consuming need to read images for metadata loading.

> Magento now caches attribute options for the layered navigation feature. This reduces the number of queries to the database, and consequently improves performance.

> Magento no longer performs unnecessary file check operations (for example, file_exists, is_file), which improves the performance of the category and product pages.

These were all fixed in Magento 2.1.6, so it makes no sense to have this on the Magento 2.2.0 release notes.

> The sitemap is no longer generated in the wrong folder when vhost is connected to /pub. Fix submitted by community member Joseph Maxwell in pull request 9094.

> We’ve corrected the location of sitemap generation when vhost is connected to /pub. GitHub-2802

These are duplicates, I think it's best to remove the last one.

> We’ve corrected a problem with _requirejs asset retrieval via static.php in static content versioning.

> Versioning of static files (including CSS, JS, font, and image files) is now enabled by default.

> We’ve improved the speed of static asset deployment. See Deploy static view files for more information about available options.

These were all fixed in Magento 2.1.3, so it makes no sense to have this on the Magento 2.2.0 release notes.

> The setup:static-content:deploy command now provides flags that you can use to exclude or include individual themes, areas, and locales. For more information, see GitHub-4294.

Was fixed in Magento 2.1.1, so it makes no sense to have this on the Magento 2.2.0 release notes.

> Translations now work for layered navigation attribute options.

Was fixed in Magento 2.1.8, so it makes no sense to have this on the Magento 2.2.0 release notes.

----

These are only a couple ones I encountered when going through the release notes, since I somehow was involved in most of the above or because I have a good memory I guess. But I'm pretty sure there will be other mistakes in there, so please review the release notes very carefully.

Thanks! :)

**Comment by jfrontain** [comment]
Hi @hostep, our policy for 2.2.0 release notes is to include all the issues we've fixed since 2.1.0. So yes: You've seen many, but not all, of these notes before. 

You do have a good memory!

I'll remove the duplicates -- it's been hard to catch all the duplicates because issues that have been included in an earlier 2.1.x and then are ported to 2.2 are identified in our internal JIRA database by different issue numbers. 

Thanks again.

**Comment by hostep** [comment]
Ok, that's unfortunate, I would have expected to only see the changes between the last released 2.1.x version before 2.2.0 was released (2.1.9 in this case). That's much more easy to understand to see what actually changed when you want to upgrade from the latest 2.1.x to 2.2.0 to see what was actually changed.

> I'll remove the duplicates -- it's been hard to catch all the duplicates because issues that have been included in an earlier 2.1.x and then are ported to 2.2 are identified in our internal JIRA database by different issue numbers.

This would not have occured if you didn't include the fixes from 2.1.x in here ;)

----

So next to the duplicate and already released fixes remarks, there is one other which you might have missed:

> JavaScript translations of warning messages no longer appear in the language of the primary locale only. Previously, optimizations that we made to static content deployment inadvertently generated the content only in the language of the primary locale, and then copied that directory to the other requested locales. GitHub-7862

This is **not** fixed, it broke again in Magento 2.2.0 after fixing it in a related issue.
See https://github.com/magento/magento2/issues/7862#issuecomment-331070332 for more details

**Comment by jfrontain** [comment]
Hi @hostep, I made another round of edits to remove the duplicates you pointed out plus a few I caught on my own and published those changes last night (Austin time). Thanks again for your careful reading; I genuinely appreciate it. 

The JavaScript issue you mentioned is marked as fixed in our internal JIRA project -- let me follow up on that. Before I remove the issue from the release notes I need to be able to annotate the JIRA issue so that the history of the issue and fix (or un-fix here) is captured. The Austin office is awake now, and I'm sure I'll be able to follow up in the next few hours. 

You are totally right about how our current strategy really invites unintentional replication of issues. I am planning on following up on that in the next few weeks. My focus has been on getting highlights, community contributions,  and known issues into the notes, and frankly haven't thought much about redesigning the fixed-issues section. But it's on my radar now. 

I will follow up on the JavaScript issue this morning and will republish the notes later today. I will close this issue then, if you don't mind. 

Thanks again!

**Comment by jfrontain** [comment]
@hostep, I followed up on the JavaScript issue -- I've removed the issue description from the Fixed Issues section of the release notes, and we've re-opened the JIRA issue. I'll close this issue in 24 hours unless I hear otherwise from you. Thanks again.

**Comment by hostep** [comment]
Thanks @jfrontain, good work! :)
