### ISSUE TITLE
no-cache headers ignored by Varnish

### ISSUE THREAD

**Issue by maderlock** [magento/devdocs#1434]
Feedback on page: /guides/v2.1/extension-dev-guide/cache/page-caching/public-content.html

I'm finding this very confusing; some pages like this one suggest that if a page's contents should not be cachable then a cache-control header of no-store, no-cache, must-revalidate, max-age=0 should be used. This certainly works for browsers, but is ignored by varnish, which will still cache it. If it's not clear that this is happening, look in magento/framework/App/FrontController.php at the dispatch function. This is always called, and in turn calls $this->response->setNoCacheHeaders(). And this... sets the above no-cache header. In other words, this is always output.

That makes sense as Magento never wants browsers to cache pages (whether this is right or wrong, it is the case). However, varnish ignores this, so there must be another mechanism which can be used to let varnish know not to cache a page. After all, something gets passed for checkout pages.

**Comment by meker12** [comment]
**To do:**  Add information about what mechanism to use to make a page non-cacheable when using Varnish.

**Comment by shrielenee** [comment]
@meker12 Any updates on this? Thanks!

**Comment by dobooth** [comment]
Closing as outdated.
