### ISSUE TITLE
Search is no longer working on Google Chrome

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1439]
Hi guys

I've been noticing this for multiple weeks now, sorry for not reporting this.
When searching for something using the search bar, the resulting page is empty (except for the header).
At first I thought it was because of my ad blocker in Chrome, but that doesn't seem to be the case, because it still doesn't work after disabling it.

Anyways, I tested it on Chrome 61.0, Safari 11.0 and Firefox 56.0
It doesn't work in Chrome, but does work in the other ones. Not sure what can cause this. I see no warnings in my javascript console...

I think it's a javascript issue, in Firefox I can see an ajax request going to algolia.net, but in Chrome, there isn't an outgoing ajax request, which is really strange.

Below is how the url http://devdocs.magento.com/guides/v2.2/search.html?q=test looks in these three browsers:
<img width="1920" alt="screen shot 2017-10-04 at 20 26 51" src="https://user-images.githubusercontent.com/85479/31192926-d984d358-a942-11e7-81a8-6136f9a29c94.png">

Is it just me or are others seeing this as well?

**Comment by hostep** [comment]
Ugh, great, 5 minutes after posting this, I find the issue. I have an extension which allows me to toggle javascript on or off on a page. And that toggle was switched to off on the devdocs site for some reason (accidentally clicked it perhaps). Sorry for opening this issue, completely my fault. Closing.

**Comment by jfrontain** [comment]
No problem, @hostep - we love how carefully you read our docs!
