### ISSUE TITLE
Version ranges on the backwards incompatible changes pages seem reversed?

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1440]
Feedback on page: /guides/v2.1/release-notes/changes/ce_changes.html

Hi

I think it makes more sense if the version ranges on the 'backwards incompatible changes' pages are reversed.

Right now they are:
```
2.1.9 - 2.1.8
2.1.8 - 2.1.7
...
```

But doesn't it make more sense to put them like this?
```
2.1.8 - 2.1.9
2.1.7 - 2.1.8
...
```

So it means 'This is what has changed from version 2.1.8 to version 2.1.9'.

**Comment by jfrontain** [comment]
@hostep, your suggestion makes sense to me -- let me follow up on it and make the change. Thanks again!

**Comment by dshevtsov** [comment]
@hostep 
Initially, the order was as you've just suggested `<previous version> - <next version>`
But later, I received a feedback, that it makes more sense to reverse the order, because we compare in this order: new version with previous version or mathematically `new version minus previous version`.

**Comment by hostep** [comment]
Hi @dshevtsov 

I understand the reasoning, it sounds like it comes from a developer (I'm a developer myself, so I can relate :)).

But the devdocs are more meant for explaining things, not to be strictly mathematically correct (sorry, can't find a better expression at the moment).

I think currently it's too confusing. When I see this, my brain thinks: "Do I have to downgrade from 2.1.9 to 2.1.8, or what do they mean with this?"
The information is supposed to help for people upgrading from a lower version to a higher version, not the other way around, so it doesn't make much sense to me, sorry, maybe it's just me?

Maybe the better solution, is to add some extra words to the titles:
"Backward incompatible changes between versions 2.1.8 and 2.1.9", something like this?

----

And just one other slightly related remark, I just noticed the [Magento Commerce BIC page](http://devdocs.magento.com/guides/v2.1/release-notes/changes/ee_changes.html) doesn't list all the changes of Magento Open Source. Are users of Commerce supposed to first check the Open Source page and then additionally the Commerce changes? This seems kind of strange to me.

**Comment by dshevtsov** [comment]
@hostep I agree that documentation here have to be more intuitive than mathematical. I'll change ordering.

Regarding the Open Source and Commerce issue. Very good point, I have to discuss it with my team. Could you open another issue for it, please?

**Comment by dshevtsov** [comment]
@hostep 
Done, please check.

**Comment by hostep** [comment]
Thanks! Looks a lot better.
