### ISSUE TITLE
BIC documentation for Magento Commerce doesn't have the same info as Magento Open Source

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1445]
Moving this request from https://github.com/magento/devdocs/issues/1440#issuecomment-335252556 to a new issue as requested by @dshevtsov:

>  I just noticed the [Magento Commerce BIC page](http://devdocs.magento.com/guides/v2.1/release-notes/changes/ee_changes.html) doesn't list all the changes of [Magento Open Source](http://devdocs.magento.com/guides/v2.1/release-notes/changes/ce_changes.html). Are users of Commerce supposed to first check the Open Source page and then additionally the Commerce changes? This seems kind of strange to me.

**Comment by dshevtsov** [comment]
@hostep thank you
Created internal issue: MAGEDOC-2632

**Comment by dshevtsov** [comment]
Added temporary notes with explanation.
Later we will publish tables with all changes per edition (OpenSource/Commerce/B2B).

**Comment by shrielenee** [comment]
Hello all - It seems there is a working Jira issue to solve for this, but no work has been done yet. We are awaiting info on the open issue before closing this. 👍
