### ISSUE TITLE
404 link on "Get your authentication keys" page

### ISSUE THREAD

**Issue by Igloczek** [magento/devdocs#1446]
[Update components, upgrade the Magento software](http://devdocs.magento.com/guides/v2.2/comp-mgr/prereq/prereq_auth-token.html) link on http://devdocs.magento.com/guides/v2.2/install-gde/prereq/connect-auth.html page leads to 404

**Comment by jeff-matthews** [comment]
Thanks @Igloczek. The updates should be live within the hour.

**Comment by jeff-matthews** [comment]
I verified that the links are working now.
