### ISSUE TITLE
Wrong 'Edit this page on GitHub' link

### ISSUE THREAD

**Issue by WaPoNe** [magento/devdocs#1447]
Feedback on page: /guides/v2.1/release-notes/ReleaseNotes2.1.8CE.html

The 'Edit this page on GitHub' link points to https://github.com/magento/devdocs/tree/develop/guides/v/release-notes/ReleaseNotes2.1.8CE.md

The right URL should be https://github.com/magento/devdocs/blob/develop/guides/v2.1/release-notes/ReleaseNotes2.1.8CE.md

Indeed I've noticed this issue is linked to every _Magento 2.1 Release Notes_ pages.

**Comment by yogeshsyscraft** [comment]
its not a serious issue brother

**Comment by rickkuilman** [comment]
Good catch! I'll fix it right away 👍
