### ISSUE TITLE
File Uploader Component Not found for MAGENTO 2.2

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/devdocs#1448]
Hello Guys,

I was working on development of form in admin UI but when i tried File Uploader Component its not working On 2.2 , and there is not documentation for 2.2 
below is for 2.0 
> http://devdocs.magento.com/guides/v2.0/ui-components/ui-secondary-uploader.html

Please help

**Comment by keharper** [comment]
@yogeshsyscraft It appears that the file was moved here:

http://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-fileuploader.html

During the 2.1 release, there was a major effort to enhance and reorganize the UI Components information. Unfortunately, a side effect of this reorg is that the directory structure changed, making it impossible to switch between 2.0 and any subsequent release.

**Comment by keharper** [comment]
Let me know whether the 2.2 article helps resolve your issue.

**Comment by jcalcaben** [comment]
This issue has been addressed. Please create a new issue if this is still a problem.
