### ISSUE TITLE
New Dev Box ?

### ISSUE THREAD

**Issue by drdreamm** [magento/devdocs#1452]
Feedback on page: /guides/v2.1/install-gde/docker/docker-over.html

Hi Guys Can you give us an idea when the new Dev Box is going to be ready please ?  Many thanks

**Comment by joshuaswarren** [comment]
Also, would it be possible in the interim to link out to a couple of the Docker or Vagrant images that different community members have built as possible alternatives? I see people doing some crazy things to try to work around the lack of a solid, easy to use development box.

**Comment by jfrontain** [comment]
Hi @joshuaswarren. At present, we have no plans to revive our DevBox. We suggest you consider this alternative: https://github.com/paliarush/magento2-vagrant-for-developers.
