### ISSUE TITLE
[cookie] Document default/core cookies

### ISSUE THREAD

**Issue by kevingimbel** [magento/devdocs#1455]
I tried to search the devdocs for information about Cookies set by Magento 2 but could not find any information. 

One of our clients needs a list with all cookies used by Magento 2 because their internal policies request a visible list inside their webshop where each cookie is explained to the users. 

I can make sense of `form_key` or `persistent_shopping_cart`, they are sort-of self explaining, but I cannot say with confidence what `recently_compared_product_previous` is used for - probably to store the last value from `recently_compared_product` before changing it?

It would be nice to have a table inside the devdocs where each cookie set by the Magento 2 core application is documented with a short description, for example:

| ID | Description |
|---|-------------|
| form_key | The `form_key` cookie is used in forms such as the checkout or "add to cart" to verify the request on the server side | 

(👆 I'm not sure if the description is 100% true)

I could find the following cookies on our Magento store: 

- `PHPSESSID`
- `X-Magento-Vary`
- `form_key`
- `mage-cache-sessid`
- `mage-cache-storage`
- `mage-cache-storage-section-invalidation`
- `mage-messages`
- `mage-translation-file-version`
- `mage-translation-storage`
- `persistent_shopping_cart`
- `private_content_version`
- `product_data_storage`
- `recently_compared_product`
- `recently_compared_product_previous`
- `recently_viewed_product`
- `recently_viewed_product_previous`
- `section_data_ids`
- `store`

**Comment by jasonevans1** [comment]
I will work on this. #SQUASHTOBERFEST

**Comment by jeff-matthews** [comment]
@kevingimbel & @jasonevans1: have you seen this page?

https://docs.magento.com/m2/ce/user_guide/stores/cookie-reference.html

**Comment by kevingimbel** [comment]
I haven't. When I opened this issue a year ago I was only looking at https://devdocs.magento.com

**Comment by shrielenee** [comment]
Hey there - It looks like this info may be covered in our merch docs, as mentioned above. I'm going to go ahead and close this issue. If you have further comments and feedback, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!
