### ISSUE TITLE
Cloud: provide a changelog of the magento-cloud.phar tool

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1458]
Hi

I noticed the magento-cloud.phar tool got a new version today, from version `1.11.0` to version `1.11.1`. But I can't seem to find a changelog of what changed in this version.

It looks like this is "probably" the same update of the platformsh-cli tool, which went from version `3.20.4` to `3.20.5`: https://github.com/platformsh/platformsh-cli/releases/tag/v3.20.5, because version `1.11.1` of the magento-cloud.phar tool now also has the `--no-clone-parent` flag on the `branch` command, which didn't exist in version `1.11.0`

Would there be an interest in maintaining a public changelog of this tool? Maybe just referring to the changelog of the platformsh-cli tool if no specific changes from Magento were added to a certain version?

Thanks!

**Comment by lorikrell** [comment]
@hostep  Hmm, good point. I'll check into this one and see what I can get pulled together.

**Comment by lorikrell** [comment]
@hostep This is definitely for the magento-cloud CLI tool. I noticed the update as well. I'll see if Platform tracks a changelog. If not, I'll see if I can get one started on my side for changes. Thanks! I'll keep this open a bit longer as I investigate and get something in place. It may take a little time.

**Comment by lorikrell** [comment]
@hostep Doing what I can to get a changelog. Alas, it's taking more time than I thought. It's a tool provided by Platform.sh. I will capture what I can and add it to the [end of this topic](http://devdocs.magento.com/guides/v2.2/cloud/reference/cli-ref-topic.html) for now while I continue to try and get that info. My notes may not be perfect, but will keep trying! :) 

Closing this ticket for now. But it's on my radar!

**Comment by hostep** [comment]
Alrighty no problem, this is already a good start!

I'd link to the Platform.sh tool and/or [changelog](https://github.com/platformsh/platformsh-cli/releases) as well, since the magento-cloud tool seems to be based on their tool.

**Comment by lorikrell** [comment]
Gotcha! I've been looking through that changelog too. I am meeting with them soon to get the specifics of what changes complete in their tool that make it over into ours. For now, that changelog can be helpful. I'll add a link and continue my investigating. Hoping to get them to add a changelog for us too! As always, thanks!
