### ISSUE TITLE
Adding Guide | How to Deploy Magento 2 to AWS via terraform

### ISSUE THREAD

**Issue by DavidLambauer** [magento/devdocs#1467]
Hi there,

I am currently working on an AWS Magento 2 Setup, that is provisioned with terraform. I am documenting my work anyway, so I thought this topic might be interesting for more developer. 

I saw this mention in the devdocs, so this is why I ask first before I might contribute :D

> 5. For large contributions or changes that include multiple files, please <a href="https://github.com/magento/devdocs/issues" target="_blank">open an issue</a> and discuss first. This may prevent duplicate or unnecessary effort, and the DevDocs team can help find the best home for your new topics. 

The Guide I would like to write covers the following topics:

* General Information about Cloud Concepts (scalable, immutable, ...)
* General Overview of AWS
* A disclaimer to mention the scope (e.g., no docker)
* High-Level Overview of the Architecture (There is already an AWS Magento 1 CE Reference Architecture, that is quite good. I will add a new one for M2)
* General Information about Terraform and Infrastructure as Code
* Getting Started
  * Setup AWS Account
  * Setup Terraform
* Load Balancer
* Autoscaling Group
* RDS Cluster
* Elasticcache Cluster
* Cloudfront
* S3/EFS Storage
* Security Groups
* ...

In the end, it should be possible to enter ```terraform apply``` and after a couple of minutes, you have an up and running Magento 2 Shop running in the cloud. 

The guide should be seen as a reference architecture. The manual won't mention any individual configurations and follows the best practices that are documented in the Magento 2 DevDocs. For Example, there won't be a provisioner for apache AND nginx. 

Nevertheless, I think it would be helpful to have such a guide in the DevDocs.

The whole guide might be a bigger contribution, so I would prefer to send pull requests step by step instead of a single one that contains the entire topic. 

Let me know your feedback about it. As I said earlier, I would write that guide anyway, but I would prefer to publish the guide in the DevDocs. 

Cheers David

**Comment by jeff-matthews** [comment]
This sounds great, @DavidLambauer! The docs would definitely benefit from this type of content and we'd love to work with you on it. 

Nothing like this has been proposed or is currently in progress, so please feel free to proceed. I'll talk to the Magento devdocs team about how to integrate it with our current doc set and whether there are any other content opportunities we can address as part of the same effort. For example, would it make sense to use Ansible to install/configure Magento and Terraform to provision the AWS infrastructure on which it runs?

**Comment by DavidLambauer** [comment]
Hi Jeff,

thank you for your feedback, I will start to write down the first version and let you know about it. Regarding Ansible. Magento has to be provisioned anyway, so Ansible makes total sense. At the moment, I work with a plain simple bash script which works fine and is documented pretty well. This is the most basic version of provisioning and I think bash is a tool that everyone should understand right out of the box. I would prefer to start with the bash provisioning to have the first shot. 

The guide could be extended for other provisioners like Ansible, Salt, Chef, .... Converting bash into a tool might be easier than converting a tool to another tool.

What do you think about that? 

Because the topic might be a bigger one, how should I tell you about the current status? Shall I open a new branch, a fork, PR?

Please feel free to have a chat within slack if there is anything we have to discuss in detail.

**Comment by jeff-matthews** [comment]
You're right. If you already have a bash script that provisions Magento, you should just use that for your example. I like the idea of extending the guide later to include other tooling, like Ansible, Chef, etc. It gives other community members an opportunity to contribute or the devdocs team can add it to our backlog. I know our devops team has some Ansible projects that we could leverage.

I think the best way to handle the workflow for now is for you to fork and branch the devdocs repo and open a PR. Let's try that first and see how it works. We can make adjustments later if necessary. The devdocs team is meeting this afternoon to discuss this, so I'll post an update later.

Thanks again for taking this on!

**Comment by jeff-matthews** [comment]
@DavidLambauer: Actually, we're going to create a new branch off of `develop` called `aws-terraform` that we'd like you to use. Just checkout that branch and open PRs against that. I'm also going to create a Github Project in this repo to track this effort and create issues/tasks so the team can collaborate with you on this.

**Comment by DavidLambauer** [comment]
Sounds great! Thank you! I will start to add the first resources this week.

**Comment by DavidLambauer** [comment]
Hi,

just a little Update for you. 

I started to create a structure for the guide and added some content. The content is in a very early stage. I haven't done and I won't do any quality improvements until the guide covers the necessary topic. My plan is to fill the specific sections with the first version of content. I iterate over the sections often, so it should be updated a lot. 

I try to publish twice a week, but no guarantee.

I was wondering where I should publish the Code itself. Each section of the guide will have code examples, but there should be a repository to manage the terraform code and the bash provisioning itself.

**Comment by jeff-matthews** [comment]
Thanks for the update. You raise a good question about where to publish code. We'll need to discuss that with internal leadership before giving you an answer, so in the meantime, please create your own repos.

**Comment by jeff-matthews** [comment]
Hi @DavidLambauer, 

I wanted to let you know that this issue has garnered a lot of interest within Magento, which is great!  

I merged your initial pull request, but I may be slower to merge future PRs until I've had a chance to discuss the content strategy with internal stakeholders. I want to be sure that the content you're proposing with regards to cloud infrastructure aligns with, and complements, Magento's strategic cloud goals and initiatives.

I'll post an update in about a week.

Thanks!

**Comment by DavidLambauer** [comment]
Hi @jeff-matthews,

that's fine. I will come back to you if I have a version that is reviewable. At the moment, I am just writing down my thoughts in a very bad English xD.

Don't feel like you have to merge the PR's fast. The guide will be a bigger project, so we might need some time anyway.

I am excited to hear more about your content strategy :). 

Thanks!

**Comment by DavidLambauer** [comment]
Hi,

I added some terraform stuff to a personal repo:

https://github.com/DavidLambauer/magento2-aws-terraform

**Comment by jeff-matthews** [comment]
Hi @DavidLambauer,

After discussing this with internal stakeholders, we've determined that the Magento devdocs site isn't the best place for this type of content. We all agree that's it's interesting and that the community would benefit from your experience, but we want to avoid making official recommendations for specific AWS + Magento 2 configurations using Terraform, especially with sample code. Dynamic technologies such as AWS and Terraform change frequently, and the effort required to sustain a current and technically accurate configuration scenario requires more resources than we can provide. 

The good news is that Magento plans to publish a white paper soon that explains how we recently helped a partner use Terraform to provision AWS resources and deploy a Magento 2 store. This white paper will provide a more appropriate context for this type of content.

That being said, we’d like to recognize and highlight the work you’re doing somewhere on our devdocs site to show our appreciation and help others find your Terraform project on Github.

You've helped us identify a significant gap in our devdocs content related to planning Magento 2 deployments in general; not just cloud-based. We'll be gathering best practice information and planning where to put it on the devdocs site soon. We'd be grateful for your participation when that effort gets underway.

**Comment by DavidLambauer** [comment]
HI @jeff-matthews,

thank you for the update! I understand that this technology might be a little bit too critical to add it to the devdocs. I will continue publishing updates within the module and as soon it is finished, I'll also add a blog post to it. 

If you find a section in the devdocs where the project fits into, I would appreciate a link/mention.
