### ISSUE TITLE
Magento2 Webservices on ISO Standards

### ISSUE THREAD

**Issue by allamsettiramesh** [magento/devdocs#1470]
Hi,

Any thoughts on how to implement Magento2 Webservices using ISO Standards, Currently on ISO Standards 15142 has 23 XSD's how can we generate web services based on its standards.

http://standards.iso.org/iso/15143/-3/

**Comment by buskamuza** [comment]
@allamsettiramesh , could you be more specific about what you want to implement and what is your use case?

**Comment by jfrontain** [comment]
Closing this issue per @buskamuza's suggestion.
