### ISSUE TITLE
Fetch salesOrderAddressEntity from sales_order.info

### ISSUE THREAD

**Issue by mehdiagharlou** [magento/devdocs#1475]
Hello,

How can I fetch data from salesOrderAddressEntity table which seperated from other data tables in sales_order.info? 

http://devdocs.magento.com/guides/m1x/api/soap/sales/salesOrder/sales_order.info.html

$action = "sales_order.info";
$salesOrders= $client->call($sess_id, $action);

This action will return data from sales_order.info but in document of SOAP there are 5 tables named like below:

salesOrderEntity 
salesOrderAddressEntity 
salesOrderItemEntity 
salesOrderPaymentEntity 
salesOrderStatusHistoryEntity 

How can I seperate requests to fetch data from any tables collected?

Thanks

**Comment by mrkhoa99** [comment]
@mehdiagharlou the guide which you gave is for Magento 1 version. What is your Magento version?

**Comment by mehdiagharlou** [comment]
@mrkhoa99 My magento version is 1 too

**Comment by keharper** [comment]
@mehdiagharlou this repo is for documentation-specific issues only. Try asking your question on [Magento Stack Exchange](https://magento.stackexchange.com/) or in the [Magento forums](https://community.magento.com/).
