### ISSUE TITLE
DevDocs | Building DevDocs in Windows

### ISSUE THREAD

**Issue by csned** [magento/devdocs#1479]
Magento Dev Docs Readme.md claims: “Windows users must build the site in a Vagrant container running on Virtual Box as discussed in more detail in the Vagrant Readme”

I could detail three, possibly four methods for building the devdocs within Windows.  Is this something that would be desired?

They are:

1.	MSYS2
2.	Windows 10 Symlinks (https://blogs.windows.com/buildingapps/tag/symlinks/#cu3d6CrQs6YovCLz.97)
3.	Windows Subsystem Linux (WSL) (https://blogs.windows.com/buildingapps/2017/08/08/windows-subsystem-linux-windows-server/#jgGFGS50iSEiP1Qe.97)
“This is where running Linux on WSL provides value: WSL runs unmodified Linux (ELF64) binaries natively. It can install and run almost any Linux command-line tool integrated in Windows.”

Please feel free to let me know if this would help.

**Comment by jcalcaben** [comment]
Hi @csned ! We would love to hear about your methods for building the devdocs pages in a Windows environment. I'm sure our contributors who use Windows would also appreciate this information.

**Comment by jcalcaben** [comment]
@csned do you have any updates for this issue?

**Comment by hguthrie** [comment]
So, I have tested a successful, local deploy of DevDocs on Windows using a combination of Git Bash and the Chocolatey package manager. Chocolatey allows extensions for Ruby version management, much like Hombrew. You can isolate the local DevDocs repository management and builds through Git Bash without affecting your normal Windows systems settings. I am sure there is a lot of customization available with this setup, but I'm not a regular Windows user. I can prepare detailed instructions, if this seems like an interesting option to people.
@lorikrell  @jeff-matthews  Let me know whether to continue.

**Comment by lorikrell** [comment]
This sounds great to me!
