### ISSUE TITLE
Broken links on UI Components Guide under the Concepts section for v2.2

### ISSUE THREAD

**Issue by vmistrybas** [magento/devdocs#1483]
When trying to access the following links, I get a page not found error.

http://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_data_source.html
http://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_template_literals.html

I have already checked in the repo [here](https://github.com/magento/devdocs/tree/develop/guides/v2.2/ui_comp_guide/concepts) to see if the files were incorrect but it looks like they might be missing?

Thanks!

**Comment by jcalcaben** [comment]
Thanks @vmistrybas ! I have fixed the missing content. The change should be live within an hour.
