### ISSUE TITLE
DevDoc description has an attribute not necessary in POST endpoints

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/devdocs#1484]
In POST calls there are some endpoints which have id as an attribute in the 'request'

for example

{
"taxClass": {
"class_id": 0,
"class_name": "string",
"class_type": "string",
"extension_attributes": {}
}
}

In the above example, class_id should not be part of the 'request' (json/xml) as it is autogenerated during insertion. If we send a request with class_id, we get an error response with status code 404 saying "Request does not match any route" (which implies the request is trying to update an existing class_id).

So, in order to create a new taxClass we should not provide class_id as a parameter as it will be generated automatically.

**_This issue has moved from the section "magento2"_**
[https://github.com/magento/magento2/issues/6269](https://github.com/magento/magento2/issues/6269)

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this, and the solution is not in our purview currently. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
