### ISSUE TITLE
Broken Link found in Magento UI documentation under concepts for v2.2

### ISSUE THREAD

**Issue by vmistrybas** [magento/devdocs#1486]
Another broken link found. 
http://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_requirejs_concept.html

This page is link form these pages below. Search RequireJS ID. 
http://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_uiregistry.html
http://devdocs.magento.com/guides/v2.2/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_js.html

Thanks!

**Comment by bdenham** [comment]
Thanks, @vmistrybas. Sorry to be getting back to you on this months later, but it looks like the links you referred to have since been fixed. Let me know if I'm missing something.
