### ISSUE TITLE
Callout "magentomodule" VCL snippet prefix is reserved for the Fastly extension

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1487]
All of the out-of-the box VCL snippets provided by the Fastly extension are prefixed with "magnetomodule".

We should call out that custom VCL snippets should not use this prefix so to avoid any conflicts with changes to the Fastly extension.

Feedback on page: /guides/v2.2/cloud/configure/cloud-vcl-custom-snippets.html

**Comment by lorikrell** [comment]
Thanks for the feedback! I'll get this updated with other Fastly content changes.

**Comment by lorikrell** [comment]
Live content is updated for this information: http://devdocs.magento.com/guides/v2.2/cloud/configure/cloud-vcl-custom-snippets.html

Thanks!
