### ISSUE TITLE
PHP install command line Incomplete

### ISSUE THREAD

**Issue by hjsprite** [magento/devdocs#1488]
Feedback on page: /guides/v2.0/install-gde/prereq/php-centos.html

Page:
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-centos.html 
PHP 7 on CentOS--->3.Enter the following command
--> yum -y install php70u php70u-pdo php70u-mysqlnd php70u-opcache php70u-xml php70u-mcrypt php70u-gd php70u-devel php70u-mysql php70u-intl php70u-mbstring php70u-bcmath php70u-json php70u-iconv
this command line lack of " php70u-soap",  in the installtion of magento will  error.

**Comment by jeff-matthews** [comment]
Thanks @hjsprite! Updates are live.
