### ISSUE TITLE
Add quick start for module development to Extension Developers section

### ISSUE THREAD

**Issue by mzeis** [magento/devdocs#150]
I'm sure you have this on your backlog, but adding a quick tutorial like the [guest post](https://alankent.wordpress.com/2015/01/10/a-minimal-magento-2-extension-guest-post/) on Alan Kents blog soon would be very important now that all developers are to play around with Magento 2 in the Dev Beta.

Allow me to quote myself:

> Excellent post, Dale! Please add an introduction like this to the Extension Developers section of http://devdocs.magento.com/.
> The documentation team pretty much could copy and paste the text as it covers the most important bits to get going. There’s always time to refine and expand on it later but most developers are checking the dev docs now and may be missing such a tutorial.

**Comment by mzeis** [comment]
I saw that the Architecture section was updated and includes much more information on modules than it did before (e.g. http://devdocs.magento.com/guides/v1.0/architecture/modules/mod_intro.html). Linking from the Extension Developers section to Magento Architecture > Modules section may suffice.

**Comment by xcomSteveJohnson** [comment]
Thanks! We'll take a look and get back to you.

**Comment by xcomSteveJohnson** [comment]
We're still working on this, just didn't want you to think we had forgotten.

**Comment by xcomSteveJohnson** [comment]
@mzeis We finally did this and I forgot to update you. The first two headings in the [PHP Dev Guide|http://devdocs.magento.com/guides/v2.0/extension-dev-guide/bk-extension-dev-guide.html], Introduction and Prepare, are intended to be a quick start. 

Let us know what you think.

**Comment by mzeis** [comment]
@xcomSteveJohnson I like it very much, great work! Thank you.
