### ISSUE TITLE
Ghosts-pages

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1513]
Pages not have related files in repository and I don't understand why its available on site. And it seems like damaged.

 -  http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/components/modules/mod_anatomy.html
 - http://devdocs.magento.com/guides/v2.1/architecture/archi_perspectives/components/modules/mod_anatomy.html

![screenshot_8](https://user-images.githubusercontent.com/603401/32199864-9cb594f6-bddf-11e7-9904-4395dbdbee03.png)

**Comment by likemusic** [comment]
http://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_intro.html and the same for v2.1 and v2.0 has anchor ("Module anatomy") to that pages.

**Comment by jfrontain** [comment]
@likemusic, thanks for bringing this to our attention. We thought we had eliminated those ghost files, but clearly we didn't. We'll follow up as soon as we can, and comment here when we've pushed our fix. Thanks again.

**Comment by jeff-matthews** [comment]
PR https://github.com/magento/devdocs/pull/1578 fixed this.
