### ISSUE TITLE
Broken link in "Start the Module Manager"

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1514]
Feedback on page: /guides/v2.2/comp-mgr/module-man/compman-start.html

"Manage your modules." link point to http://devdocs.magento.com/guides/v2.2/comp-mgr/module-man/compman-main-pg.html that not exists.

Also possible that this part of guide has damaged toc.
For v2.1 toc seems good:
![screenshot_9](https://user-images.githubusercontent.com/603401/32210852-e9899cbe-be20-11e7-9d6a-4028cb77882d.png)

But for v2.2 seems worse:
![screenshot_10](https://user-images.githubusercontent.com/603401/32210882-0a70725e-be21-11e7-834e-b5a38b4ff45a.png)

**Comment by jeff-matthews** [comment]
Thanks @likemusic. I removed the link since that topic no longer exists in v2.2. The TOCs are functioning as expected. "Step 3" was moved to the **Run the Extension Manager** section just below that.
