### ISSUE TITLE
Not clear some concepts in "Module dependency types"

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1516]
Feedback on page: /guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend_types.html

1) "different product layers" - what is it? If it's about framework layers (Presentation, Service, Domain, Persistence), why used "product" word. If its true it would be great ad link pointing to [Architectural layers overview](http://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/ALayers_intro.html). If not It would be good to explain what "modules belonging to different [product] layers" means.

2)
- Dependencies in the Framework layer
- Dependencies in the Application layer

Not defined anywhere what is Framework and Application layer and how to determine to which of them module belongs.

**Comment by bdenham** [comment]
Hey @likemusic. Sorry for the late response, but thanks for indicating these holes in the docs. I will investigate and add to the documentation in the days ahead. I think your original comment still applies, but feel free to update it as necessary. Thanks!

**Comment by bdenham** [comment]
Hey @likemusic, I just created a Jira issue for this issue to clarify these concepts in the docs. Thanks for alerting us to this.

**Comment by dobooth** [comment]
The arch guide has been updated more than once since this issue was filed. The topic noted no longer exists in the repo. I am closing this as out-of-date. Happy to update any language that is currently vague.
