### ISSUE TITLE
Formatting of "Introduction to page types" broken

### ISSUE THREAD

**Issue by mzeis** [magento/devdocs#152]
It seems there is a formatting problem at http://devdocs.magento.com/guides/v1.0/architecture/view/page-type.html. After looking at https://github.com/magento/devdocs/blob/develop/guides/v1.0/architecture/view/page-type.md I assume the problem is the non-escaped `<ModuleName>` tag.

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing this out. It'll be fixed early next week, will update you then.

**Comment by xcomSteveJohnson** [comment]
Thank you very much for bringing this to our attention. Replaced many <pre>-formatted code blocks with indents, eliminating the need to escape <.

Please verify and close if you're satisfied:

http://devdocs.magento.com/guides/v1.0/architecture/view/page-type.html

**Comment by mzeis** [comment]
Thanks!
