### ISSUE TITLE
Migrate links format from html a-tag to markdown

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1526]
Currently docs have links at html and markdown formats.

What about converting all link in docs to markdown format for v2.* guides?

I think using markdown is better because it not create links to not existed pages when browse files via github interface in case then url contains placeholders like `{{ page.baseurl }}`.

If I done it and make PR it would be merged? There is no some pitfalls with it?

**Comment by keharper** [comment]
You won't be able to do it globally with a search/replace type function. If the converted markdown link is within an HTML element, the link will be treated as standard HTML text, and therefore won't render.

**Comment by jeff-matthews** [comment]
I prefer the markdown syntax as well, but @keharper makes a good point. There's not a simple way to automate this and even if there was, I wouldn't want to merge it until we've implemented some basic link checking during compile time to make sure we didn't introduce new broken links.

**Comment by likemusic** [comment]
Seems that its not difficult to write tool to change link format and skip/notice about links with html inside.

We can compare sorted list of broken links before and after links converting to be sure that we didn't introduce new broken links.

Please, keep this issue opened. I will try to do it in my spare time.

**Comment by likemusic** [comment]
https://github.com/magento/devdocs/issues/1531 - add separate issue to discuss referential integrity of documentation.

**Comment by jcalcaben** [comment]
@likemusic We are currently migrating all HTML content to markdown. Closing this issue since HTML link conversion is part of this effort.
