### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by bgronek** [magento/devdocs#1528]
Feedback on page: /guides/v2.0/architecture/bk-architecture.html

I am searching for documentation for creating custom widgets specifically custom widget parameters as there are outside articles covering some of this.  So I suppose the real question is whether you have documented your configuration xml for the custom modules and specifically widgets.  I can't find it.

**Comment by bdenham** [comment]
Hey @bgronek, I'm going to close this. If you want me to reopen, just let me know. Thanks.
