### ISSUE TITLE
Architecture > Theme Overview incorrect statement

### ISSUE THREAD

**Issue by tonegolf71** [magento/devdocs#153]
Currently `/guides/v1.0/architecture/arch_themes.md` states:

> Each theme contains a theme.xml file, which defines the name and version of that theme, as well as the name of the parent theme, if any.

It is my understanding that this is incorrect and that the composer.json file in the theme is responsible for the version and parent information. According to https://github.com/magento/magento2/issues/840 this may be changing but the docs as they stand are incorrect.

**Comment by almarchenko** [comment]
The changes were implemented already and currently theme name, version and parent are declared in theme.xml
Docs are being updated accordingly

**Comment by xcomSteveJohnson** [comment]
Sasha, this affects all of us in some way but I'm assigning it to you for the time being.

@tonegolf71 please give us some time to investigate and make the changes.

**Comment by tanberry** [comment]
I corrected the information in `/guides/v1.0/architecture/arch_themes.md` about the version being declared in the theme.xml file, and also updated the directory paths for the two default theme.xml files that are included with DevBeta relaease.

The updates will be published in the next day or two; please review and close if you are satisfied with the fix. Thanks!

**Comment by xcomSteveJohnson** [comment]
@tonegolf71 Please check it now and close this if you're happy: http://devdocs.magento.com/guides/v1.0/architecture/arch_themes.html

**Comment by tonegolf71** [comment]
Great thanks.
