### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1531]
At the moment, the documentation contains a lot of broken links in anchor and link tags.

I was validate current develop branch by [Xenu2](http://home.snafu.de/tilman/xenulink.html):

Total (without 200 status-code): 10 900
- internal: 1280
- external: external: 9620
  - github new issue - 3848
  - other - 5772

Xenu results:
 - [develop-server-2017-11-05-16-45.XEN.zip](https://github.com/magento/devdocs/files/1444100/develop-server-2017-11-05-16-45.XEN.zip) - in XEN format
- [develop-server-2017-11-05-16-45.txt.zip](https://github.com/magento/devdocs/files/1444099/develop-server-2017-11-05-16-45.txt.zip) - extorted to tab-separated text

List of broken links:
 - [develop-server-not200-external-2017-11-05-16-45.txt](https://github.com/magento/devdocs/files/1444133/develop-server-not200-external-2017-11-05-16-45.txt) - ordered list of external broken links (excluded create issue links)
 - [develop-server-not200-internal-2017-11-05-16-45.txt](https://github.com/magento/devdocs/files/1444134/develop-server-not200-internal-2017-11-05-16-45.txt) - ordered list of internal broken links

Diff of tab-separated text file can be used to validate that another pull-request not add new broken links or fix some of exists.

**Comment by likemusic** [comment]
It would be great to have some tools for easy and quick comparison (by bash/php script or any) with report about new/fixed internal/external links.

**Comment by likemusic** [comment]
https://github.com/magento/devdocs/pull/1532 - fix broken links by letters case

**Comment by likemusic** [comment]
I made excel tables linked to TSV-files exported by Xenu, therefore can view what links fixed/broken/removed/added. Unfortunately seems that excel use absolute paths in connection strings, but I was create it not in root of drive, therefore I don't share them yet.

**Comment by jeff-matthews** [comment]
@likemusic: Thank you for your diligent attention to detail. We're aware of the issue with broken links and are working on a solution internally. I would encourage you to focus your efforts else where, however, since the solution we're implementing uses a different tool.

**Comment by likemusic** [comment]
There is still 1121 broken internal links in devdocs site.
List of broken links: https://docs.google.com/spreadsheets/d/1wpCPj8sQQIKimBhHMLCuu17xN-it2vHnKGZqVJFlT1o/edit?usp=sharing

I think this issue should be kept opened until all broken links will not be fixed.

**Comment by likemusic** [comment]
Report generated by Xenu: https://drive.google.com/open?id=1BpivM44dlRPXZ8b46_-eL6iZK1e0QrxL

It can be helpful if someone will want to fix some broken links because report contains urls where broken link is referenced.

**Comment by jeff-matthews** [comment]
@likemusic, if you'd like to help fix broken links, please run our link check tool `rake link_report`.

**Comment by likemusic** [comment]
@jeff-matthews, thanx! I didn't know about it. I'll try to use it.

**Comment by hguthrie** [comment]
Because this repository is very active, there is a potential for broken links to emerge at any time. Thank you for helping us keep the links up to date. We are closing this issue because many links have been fixed. If you encounter any new broken links, feel free to create a new GitHub issue, or submit a pull request with a fix.
