### ISSUE TITLE
Vault documentation not available anymore

### ISSUE THREAD

**Issue by joni-jones** [magento/devdocs#1535]
The Vault documentation is missed in payment integration menu for Magento 2.2
![screenshot from 2017-11-06 22-27-09](https://user-images.githubusercontent.com/2736528/32462323-a94ec342-c341-11e7-8c3c-7d6af4e925ba.png)

Also, link to Vault integration from Payments Integrations page returns 404.

**UPD**: PR with the fix https://github.com/magento/devdocs/pull/1546.

**Comment by keharper** [comment]
It looks like @dshevtsov fixed this.
