### ISSUE TITLE
Grunt configuration remarks for Magento 2.2

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1537]
Feedback on page: [/guides/v2.2/frontend-dev-guide/tools/using_grunt.html](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/tools/using_grunt.html)

Hi guys

It would be great if someone can review the page mentioned above, because it contains some incorrect advise. And I think it's a bit confusing right now.

So to use the new custom Grunt configuration in Magento 2.2, we had to do this:
- Execute points 1, 2 and 3
- Skip point 4, just leave the configuration as is (`"themes": "dev/tools/grunt/configs/local-themes"`)
- Create a new file: `dev/tools/grunt/configs/local-themes.js` which is a copy of `dev/tools/grunt/configs/themes.js` and add our customisations to the `local-themes.js` file
- Continue with the rest.

I was confused because:
1) You shouldn't copy `grunt-config.json.sample` to `grunt-config.json` if you want to use the default configuration
2) In the 'custom configuration option 1' section, you speak of a directory: `<magento_root>/dev/tools/grunt/configs/local-themes/`, but that's incorrect, it is supposed to be a file `<magento_root>/dev/tools/grunt/configs/local-themes.js`

Please review, because I didn't actually test this myself, this was while talking to a remote frontend colleague where we tried to get this setup properly.

**Comment by hubertus2017** [comment]
..and the *.sample files shall not be deleted or you get cron error messages, duplicate and rename them

**Comment by MikeSheward** [comment]
I agree, this stuff should just work out the box.

**Comment by jfrontain** [comment]
We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the Installation and Configuration project.

**Comment by lorikrell** [comment]
Content was resolved with PR https://github.com/magento/devdocs/pull/4231
Closing issue
