### ISSUE TITLE
Incorrect gist in indexing guide

### ISSUE THREAD

**Issue by tonegolf71** [magento/devdocs#154]
A gist intended to show an example of `Merchandising/etc/indexer.xml` is embedded on line 267 in `/guides/v1.0/architecture/index-cache/indexing.md`.

This is incorrectly displaying a duplicate example of the `Merchandising/etc/mview.xml`.

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing this out. I updated the indexer and mview gists; please take a look and let me know if it makes more sense now.

**Comment by tonegolf71** [comment]
Hi, sorry to be a pain, I can see you've updated both gists, but you have replaced them with an example of catalog_product_flat. The section they are in is intended as an example for a merchandising module. Previously the mview was correct, but the indexer.xml example was merely a copy of this. What was needed was a correct example of an indexer.xml for a merchandising module.

**Comment by xcomSteveJohnson** [comment]
My mistake. I went back to some internal source material that clearly didn't match the documentation. I'll try again and get back to you. Thanks for looking at it.

**Comment by xcomSteveJohnson** [comment]
@tonegolf71 I think I really fixed it this time <g>. Please check. Thanks

**Comment by tonegolf71** [comment]
Great, that's pretty much it. The only other thing I noticed is that it now jumps between UK english "merchandising" and US english "merchandizing" between the examples which might cause some confusion?

**Comment by xcomSteveJohnson** [comment]
Whew! <g> I just copied from the wrong part of the document.

OK, I can fix that; it'll most likely be updated early next week. I'll get back to you.

**Comment by xcomSteveJohnson** [comment]
Thank you and we apologize for the delay. Fixed "merchandising".

http://devdocs.magento.com/guides/v1.0/architecture/index-cache/indexing.html
