### ISSUE TITLE
Migrating queue.xml to seperate queue_consumer.xml, queue_publisher.xml and queue_topology.xml not working

### ISSUE THREAD

**Issue by koenner01** [magento/devdocs#1547]
Feedback on page: /guides/v2.2/extension-dev-guide/message-queues/queue-migration.html

I followed the steps described in the guide and when running a setup:upgrade the queue is not being added to the queue table (no errors found in any log). If I revert back to using a queue.xml, the setup:upgrade adds the queue correctly to the database.

## Files used

queue.xml:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/queue.xsd">
    <broker topic="bl.customer.saved" exchange="magento" type="db">
        <queue name="bl_customer_data_changed_queue"
            consumer="blCustomerSavedConsumer"
            consumerInstance="Magento\Framework\MessageQueue\BatchConsumer"
            handler="Bl\ExtendedCustomer\Model\ResourceModel\Customer\Consumer::processMessage"
        />
    </broker>
</config>
```

queue_consumer.xml:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/consumer.xsd">
    <consumer name="blCustomerSavedConsumer"
        queue="bl_customer_data_changed_queue"
        connection="db"
        consumerInstance="Magento\Framework\MessageQueue\BatchConsumer"
        handler="Bl\ExtendedCustomer\Model\ResourceModel\Customer\Consumer::processMessage"
    />
</config>
```

queue_publisher.xml:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/publisher.xsd">
    <publisher topic="bl.customer.saved">
        <connection name="db" exchange="magento" />
    </publisher>
</config>
```

queue_topology.xml

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/topology.xsd">
    <exchange name="magento" type="topic" connection="db">
        <binding id="blCustomerSavedBinding"
            topic="bl.customer.saved"
            destinationType="queue"
            destination="bl_customer_data_changed_queue"
        />
    </exchange>
</config>
```

**Comment by shrielenee** [comment]
Thanks @koenner01 - This is definitely something that needs to be addressed and we are creating an internal ticket to track and resolve it. 🏆

**Comment by hguthrie** [comment]
MAGEDOC-3127

**Comment by shrielenee** [comment]
Hey all - We are checking on availability of internal resources to work this ticket as mentioned above. Stand by for updates!

**Comment by hguthrie** [comment]
I confirmed that we are still tracking this issue internally.

**Comment by hostep** [comment]
Recently somebody mentioned on Slack that the documentation might be correct after all (well at least with a more recent version of Magento). So if someone could double check and confirm, then that would be great. :)

**Comment by keharper** [comment]
@nuzil Can you comment on this?

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
