### ISSUE TITLE
Caching corrections

### ISSUE THREAD

**Issue by xcomSteveJohnson** [magento/devdocs#155]
Entered on behalf if @mzeis per tweet to Alan Kent.

"Is there an up-to-date documentation on configuring cache backends in #magento2? http://devdocs.magento.com/guides/v1.0/config-guide/config/caching.html uses local.xml instead of config.php"

**Comment by xcomSteveJohnson** [comment]
@mzeis Thank you for pointing this out. We'll try to have a solution by early next week, keep you posted.

**Comment by mzeis** [comment]
Great, thank you! I won't be able to make a pull request in time as I didn't have a deeper look at the M2 cache configuration yet.

**Comment by xcomSteveJohnson** [comment]
No problem. I know part of the answer and will get a further update this week. I'll update you. If it's not what you expected please let us know and we'll fix it.

**Comment by xcomSteveJohnson** [comment]
@mzeis Unfortunately I'm sure you'll find the update unsatisfactory: http://devdocs.magento.com/guides/v1.0/config-guide/config/caching.html

There's a lot of detail I don't understand. I removed all of the incorrect information but I do not have sufficient information to replace it with. Please open a pull request if you know some of the missing detail. Meanwhile, I will try to improve it.

**Comment by mzeis** [comment]
Hi @xcomSteveJohnson, thanks for updating the documentation! I can't promise you an update soon but if I find time I'll put something together!

**Comment by xcomSteveJohnson** [comment]
Closing because we're planning to update this topic at the appropriate time.
