### ISSUE TITLE
remove autoplay from video. add all attributes values explanation. for e.g. "visible"

### ISSUE THREAD

**Issue by danistor** [magento/devdocs#1551]
Feedback on page: /videos/fundamentals/add-new-product-attribute/

**Comment by lorikrell** [comment]
@danistor thank you for your feedback on the video autoplay. We are working to disable autoplay for all videos on DevDocs. This ticket will be updated when the change is complete. Thank you!

**Comment by lorikrell** [comment]
@danistor - We have removed the autoplay feature from all videos on DevDocs. When the page loads with a video, it will require clicking play to start.

Thank you for your request and feedback!
