### ISSUE TITLE
major css issue at the page http://devdocs.magento.com/guides/v2.0/architecture/behavior/price-calc.html

### ISSUE THREAD

**Issue by aryaashwani** [magento/devdocs#1557]
Please fix the css issue at this page

http://devdocs.magento.com/guides/v2.0/architecture/behavior/price-calc.html
<img width="932" alt="capture" src="https://user-images.githubusercontent.com/25876982/32877445-8fc21680-cac7-11e7-94c2-bc97af87d060.PNG">

**Comment by jeff-matthews** [comment]
Thanks for bringing this to our attention @aryaashwani. This issue is related to how we deploy the devdocs site. If we delete a source file without creating a redirect, it leaves behind an orphaned HTML file in the `gh-pages` branch, which is responsible for the bad formatting. 

Usually, we just need to create a redirect to regenerate the HTML, but in this case I need to first research why the directory containing this original source file was deleted and whether we need to restore it.

**Comment by jeff-matthews** [comment]
Tracking with [MAGEDOC-2687](https://jira.corp.magento.com/browse/MAGEDOC-2687)

**Comment by aryaashwani** [comment]
Thanks for reply.


Regards
Ashwani Kumar Arya

On Nov 17, 2017 12:09 AM, "Jeff Matthews" <notifications@github.com> wrote:

Thanks for bringing this to our attention @aryaashwani
<https://github.com/aryaashwani>. This issue is related to how we deploy
the devdocs site. If we delete a source file without creating a redirect,
it leaves behind an orphaned HTML file in the gh-pages branch, which is
responsible for the bad formatting.

Usually, we just need to create a redirect to regenerate the HTML, but in
this case I need to first research why the directory containing this
original source file was deleted and whether we need to restore it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/magento/devdocs/issues/1557#issuecomment-345017605>,
or mute
the thread

**Comment by jeff-matthews** [comment]
I've confirmed that the content in this file isn't valid for Magento 2.0 and should be deleted.

**Comment by esseremmerik** [comment]
@jeff-matthews So every documentation about pricing is not valid for Magento 2.2 anymore? See also http://devdocs.magento.com/guides/v2.2/architecture/behavior/pricing.html#m2devgde-pricelib-def and http://devdocs.magento.com/guides/v2.2/architecture/behavior/price-render.html which give 404's now and where there before (see google cache)

Looks strange to me, as Magento 2 had specific pricing libraries to create custom price types.

**Comment by jeff-matthews** [comment]
@esseremmerik: Based on this feedback, we're re-evaluating why these files were deleted and will likely restore them. @keharper, can you confirm?

**Comment by aryaashwani** [comment]
Hi All,
          Got the similar issue at the page
http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/components/modules/mod_anatomy.html

Please review.

**Comment by ProjectEight** [comment]
This is also happening on this page as well: http://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/arch_libraries.html

**Comment by jeff-matthews** [comment]
We purged all orphaned HTML pages from the `gh-pages` branch to eliminate the reported CSS issues site-wide. Pricing documentation is unrelated to the reported issue.
