### ISSUE TITLE
Missing area from "Modules and Areas"

### ISSUE THREAD

**Issue by tonegolf71** [magento/devdocs#156]
In `/guides/v1.0/architecture/modules/mod_and_areas.md`, it mentions that "In Magento there are six Areas". However it only lists 5 areas? I presume the missing one is "crontab"?

Although this is at odds as to what is stated about areas on `/develop/guides/v1.0/architecture/areas/areas.md`, this mentions "install" as an area, but mod_and_areas.md has "doc"?!

**Comment by xcomSteveJohnson** [comment]
@tanberry , please fix. Thanks

**Comment by tanberry** [comment]
Thanks for that catch! I've edited both pages (`mod_and_areas.md` and `areas.md`) to fix the inconsistencies and the inaccurate counting (1...2...3...4...5...). 

As you have noticed, there were changes to the Magento areas with the M2 Dev Beta release.

Fix will go live at the end of our sprint, early next week. Take a look then and please close this issue if you are satisfied with the fix. Thanks again for pointing this out.

**Comment by xcomSteveJohnson** [comment]
@tonegolf71 Please check anytime: http://devdocs.magento.com/guides/v1.0/architecture/modules/mod_and_areas.html

Close this issue if you're happy with the resolution.

**Comment by tonegolf71** [comment]
Thanks, all looks good.
