### ISSUE TITLE
The left navigation menu is broken and overlaying the content

### ISSUE THREAD

**Issue by documarezc** [magento/devdocs#1562]
Feedback on page: /guides/v2.1/architecture/archi_perspectives/components/modules/mod_anatomy.html

**Comment by keharper** [comment]
We're seeing a lot of similar issues. How did you get to this page? Google?

**Comment by documarezc** [comment]
Hey. Yes through Google. When I go the the Console in Chrome I can see a JavaScript error.

**Comment by documarezc** [comment]
I am sorry was not through Google, was from a link on this page: http://devdocs.magento.com/guides/v2.1/architecture/archi_perspectives/components/modules/mod_intro.html

**Comment by keharper** [comment]
Thanks for the info. For articles that have been removed or relocated, the devdocs website is displaying mangled files like the one you reported, instead of 404 messages. We'll get this cleaned up soon.

**Comment by jeff-matthews** [comment]
PR https://github.com/magento/devdocs/pull/1578 fixed this.
