### ISSUE TITLE
Can RabbitMQ be used with Magento Open Source installations?

### ISSUE THREAD

**Issue by SunshineTech** [magento/devdocs#1563]
In Installation Guide > Getting Started > Prerequisites > RabbitMQ (Magento Commerce only), it says "You must install and configure RabbitMQ after installing Magento Open Source or before installing Magento Commerce.".

**Comment by keharper** [comment]
You cannot use RabbitMQ with Open Source. 

The note at the top of the page is obsolete and will be removed. Thanks for bringing it to our attention.

**Comment by keharper** [comment]
Thanks for letting us know about this issue. I fixed it last week, but forgot to close this out.

**Comment by DougPlumley** [comment]
Hi @keharper - different location but same issue, the language about using RabbitMQ with Magento Open Source also appears in the devdocs - https://devdocs.magento.com/guides/v2.x/install-gde/prereq/install-rabbitmq.html

https://devdocs.magento.com/guides/v2.2/install-gde/prereq/install-rabbitmq.html
https://devdocs.magento.com/guides/v2.3/install-gde/prereq/install-rabbitmq.html
