### ISSUE TITLE
Navigation menu is on top of site, making it difficult to read.

### ISSUE THREAD

**Issue by zaibi099** [magento/devdocs#1567]
Feedback on page: /guides/v2.1/contributor-guide/contributing_docs.html
![screenshot_2](https://user-images.githubusercontent.com/5962509/33017751-56cdbffe-ce15-11e7-86ff-1e708b398296.png)

**Comment by zaibi099** [comment]
Console Error in **app.min.js** is `ReferenceError: algoliasearch is not defined`

**Comment by jeff-matthews** [comment]
Please see #1557

**Comment by jeff-matthews** [comment]
Sorry, I closed this too soon. It's related to #1557, but requires a separate fix.

**Comment by jeff-matthews** [comment]
@zaibi099: Are you sure that's the URL? When I visit that page, I don't see the misaligned text.

**Comment by jeff-matthews** [comment]
PR /guides/v2.1/contributor-guide/contributing_docs.html fixed all issues like this.
