### ISSUE TITLE
Feedback Using Fonts

### ISSUE THREAD

**Issue by iunia27** [magento/devdocs#1569]
Feedback on page: /guides/v2.0/frontend-dev-guide/css-topics/using-fonts.html

Hello,

Could you please put some examples with the whole path, I'm struggling to show my fonts in the admin panel and I find this could use more explanations and examples.
For example for a custom module, MyModule_Example, what would the full paths be and also what is <theme_dir>?

Thank you,
Iunia.

**Comment by jeff-matthews** [comment]
Thanks for the feedback @iunia27! I think you're right. We can add more information about where the theme directory is located. It's located here: `app/design/frontend/<your_vendor_name>/<your_theme_name>`. 

I also think it would be helpful to include a link to the topic that explains [how to create a theme](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-create.html#theme-gen-walkthrough).

**Comment by jeff-matthews** [comment]
Doc updates will be published when I merge the `imagine-2018` branch with `develop` later today.
