### ISSUE TITLE
Information on performance toolkit not linked

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1570]
This page references the performance toolkit but does not give any links to find more information  such as https://github.com/magento/magento2/tree/2.0/setup/performance-toolkit.  

Feedback on page: /guides/v2.1/config-guide/cli/config-cli-subcommands-perf-data.html

**Comment by jeff-matthews** [comment]
Thanks for bringing this to our attention @dougkm! Revised docs are live.
