### ISSUE TITLE
link to peformance tool kit is not updated with Magent Version

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1571]
The link to the performance toolkit does not link to the version of the toolkit associated with the documentation.

This page is the 2.1 doc but links to the 2.0 version of the toolkit - https://github.com/magento/magento2/tree/2.0/setup/performance-toolkit

Feedback on page: /guides/v2.1/cloud/live/go-live-checklist.html

**Comment by jeff-matthews** [comment]
Thanks @dougkm! I've updated the docs with version-specific links.
