### ISSUE TITLE
Check out new field - save data to db - need info

### ISSUE THREAD

**Issue by kunal1234gh** [magento/devdocs#1572]
## File to update
Feedback on page: /guides/v2.1/howdoi/checkout/checkout_new_field.html
Checkout Tutorial - [source](https://github.com/magento/devdocs/blob/master/guides/v2.1/howdoi/checkout/checkout_new_field.md) | [output](https://devdocs.magento.com/guides/v2.1/howdoi/checkout/checkout_new_field.html)

## Content to add

Hi There ,

How can we save the data to the database after creating the custom field . Can you provide some information regarding this 

Extensive information in this stack exchange may help! https://magento.stackexchange.com/questions/132114/how-to-save-custom-field-in-custom-database-table-while-editing-product-from-bac

**Comment by lorikrell** [comment]
We need to locate an SME who may have this info. Possible information for this very question: https://magento.stackexchange.com/questions/132114/how-to-save-custom-field-in-custom-database-table-while-editing-product-from-bac

**Comment by jeff-matthews** [comment]
@rogyar, can you help with this re: DB operations?

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
