### ISSUE TITLE
Devdocs suggests to drop security

### ISSUE THREAD

**Issue by vrann** [magento/devdocs#1573]
In the section Firewall and SeLinux of Elastic Search overview, DevDocs suggests to disable SeLinux, which can be dangerous on the production environment. Even though the documentation is specifically mention that this is for development environment only, it is not safe recommendation anyway.

Affected pages:
- http://devdocs.magento.com/guides/v2.1/config-guide/elasticsearch/es-overview.html
- http://devdocs.magento.com/guides/v2.2/config-guide/elasticsearch/es-overview.html

Please fix the documentation:
1. Replace the intro to the section with this note:
```
Please take into account that security-related software (iptables, SELinux, AppArmor etc.) may be configured by default to block communication between subsystems. It may be a good idea to check them in case of problems.
```
2. Remove **Disable iptables and SELinux** paragraph
3. Keep **Set up rules for iptables and SELinux** paragraph

**Comment by jeff-matthews** [comment]
Thanks @vrann! I'll get this updated.

**Comment by jeff-matthews** [comment]
These are now live.
