### ISSUE TITLE
Facing  challenge to display Component  in frontend   checkout 

### ISSUE THREAD

**Issue by kunal1234gh** [magento/devdocs#1579]
Feedback on page: /guides/v2.0/howdoi/checkout/checkout_customize.html

Facing a challenge to display Component  in frontend  . Below is my code . 

Step 1) Created view/frontend/layout
[checkout_index_index.xml.txt](https://github.com/magento/devdocs/files/1516741/checkout_index_index.xml.txt)

Step 2)
Created Mixin  in the followng path 
view/base/requirejs-config.js

`var config = {
'config': {
    'mixins': {
        'Magento_Checkout/js/view/shipping': {
            'Em_Welcome/js/view/shipping-payment-mixin': true
        },
        'Magento_Checkout/js/view/payment': {
            'Em_Welcome/js/view/shipping-payment-mixin': true
        },
        
        'Magento_Checkout/js/view/shipping': {
            'Em_Welcome/js/view/shipping-policy-mixin': true
        },
    }

}
}`

Step 3
created view/base/web/js/view/shipping-policy-mixin.js
[shipping-policy-mixin.js.txt](https://github.com/magento/devdocs/files/1516729/shipping-policy-mixin.js.txt)

Step 4

view/frontend/web/js/view/checkout/shipping
[shipping-policy.js.txt](https://github.com/magento/devdocs/files/1516737/shipping-policy.js.txt)

Step 5

view/frontend/web/template

[shipping-policy.html.txt](https://github.com/magento/devdocs/files/1516739/shipping-policy.html.txt)

**Comment by shrielenee** [comment]
Hey @kunal1234gh - It looks like you already have the steps defined! Would you mind creating a PR for this? Or another fresh issue if this is still relevant? See how to do so here: https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md.

I'm going to close this issue. Please resubmit if needed. Thanks!
