### ISSUE TITLE
Incorrect Gist examples for "RSS feed assets" on "Introduction to page assets" page

### ISSUE THREAD

**Issue by tonegolf71** [magento/devdocs#158]
The Gist examples on `/guides/v1.0/architecture/view/page-assets.md` for "RSS feed assets" are wrong, it is incorrectly repeating the "CSS assets" example.

**Comment by xcomSteveJohnson** [comment]
Thank you for bringing this to our attention. We apologize that some time elapsed before it was fixed. Please verify and close if you're satisfied:

http://devdocs.magento.com/guides/v1.0/architecture/view/page-assets.html
