### ISSUE TITLE
Fix wrong path to preprocessed files in var

### ISSUE THREAD

**Issue by 36serg6** [magento/devdocs#1580]
Topic: Simple style changes with client-side LESS compilation vs. server-side.
Link: http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.html

Need to change
![screenshot from 2017-12-01 14 55 26](https://user-images.githubusercontent.com/13270360/33483745-f8f11a98-d6a7-11e7-9fc5-f9565c2d4f17.png)
from:
var/view_preprocessed/less
to:
var/view_preprocessed/pub/static/frontend/<Your_Vendor>/<your_theme>

**Comment by jeff-matthews** [comment]
Thanks @36serg6! I'll make this update to the 2.2 version of the topic.

Since there is no `var/view_preprocessed/pub` directory in version 2.1, I'll need to update the 2.1 version of the topic accordingly:

-  `var/view_preprocessed/css`
- `var/view_preprocessed/source`

**Comment by jeff-matthews** [comment]
The updates will be live when I merge the `imagine-2018` branch with `develop`.
