### ISSUE TITLE
add versions to supported software list

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1581]
Feedback on page: /guides/v2.2/cloud/requirements/cloud-requirements.html

Can the version of the software be listed on this page?  For example, what version(s) of Redis are supported?

Currently, you have to go to the linked pages to find the supported versions rather than having them all in a single list.

**Comment by jeff-matthews** [comment]
@dougkm: Yes, we can list the version as well. I'll update this as soon as I finish doc updates for the 2.2.2 release. Thanks for the feedback!

**Comment by jeff-matthews** [comment]
@dougkm, these updates are live.

http://devdocs.magento.com/guides/v2.2/cloud/requirements/cloud-requirements.html#cloud-arch-software
