### ISSUE TITLE
Imagery

### ISSUE THREAD

**Issue by rossmc** [magento/devdocs#1588]
Feedback on page: /guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.html

Would it be possible to add imagery to this part of the docs to show how each widget looks? And if they're used on the frontend or just the backend?

Also would be nice to have a code sample on each.
`<div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>`

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
