### ISSUE TITLE
Layout broken on /guides/v1.0/architecture/view/page-type.html

### ISSUE THREAD

**Issue by tonegolf71** [magento/devdocs#159]
This page looks ok in Github, but at http://devdocs.magento.com/guides/v1.0/architecture/view/page-type.html the page layout is broken. It looks like this is due to line 25 where "&lt;ModuleName&gt;" is not escaped.

I didn't want to do a pull request as I cannot definitively test the change and see if it fixes the problem, reason being that http://devdocs.magento.com is converting the markdown and I cannot replicate that. Unless there is some way?

**Comment by mzeis** [comment]
Hi Tony, this will be fixed, see #152.

**Comment by tonegolf71** [comment]
Durrr, I remember reading that a couple of days ago too. I think my brain can't take any more docs at the mo!! I'll close now. Thanks for the headsup!
