### ISSUE TITLE
GRANT ALL MYSQL 5.7 error in your SQL syntax

### ISSUE THREAD

**Issue by erichagz** [magento/devdocs#1592]
GRANT ALL ON magento.* TO magento@localhost IDENTIFIED BY 'magento';
Query OK, 0 rows affected, 1 warning (0.00 sec)

Worked:
CREATE USER 'magento'@'localhost' IDENTIFIED BY 'password';
GRANT ALL ON magento.* TO 'magento'@'localhost';

Feedback on page: /guides/v2.2/install-gde/prereq/mysql.html

**Comment by jeff-matthews** [comment]
#1600 fixes this issue
