### ISSUE TITLE
More detailed explanation on how to create custom indexer

### ISSUE THREAD

**Issue by McFizh** [magento/devdocs#1596]
## Need Docs for Indexers

I stumbled to the same problem as did the creator of this ticket:

https://github.com/magento/magento2/issues/8866

The problem is basically that the documentation (2.0/2.1/2.2) doesn't explain that the example indexer only works when called from cli, or when the indexer mode is set to scheduled. There's no info on how to implement "on save" indexer.

Ps. I tried to see if the original author has created ticket to devdocs, but didn't find any. So I assume that nothing was ever created.

## Doc files to update

Content could be added to these pages:
- Adding a custom indexer [source](https://github.com/magento/devdocs/blob/master/guides/v2.1/extension-dev-guide/indexing-custom.md) | [output](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexing-custom.html)
- Manage the indexers [source 2.2](https://github.com/magento/devdocs/blob/master/guides/v2.2/config-guide/cli/config-cli-subcommands-index.md), [source 2.3](https://github.com/magento/devdocs/blob/master/guides/v2.3/config-guide/cli/config-cli-subcommands-index.md) | [output](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-index.html)

**Comment by andrewbess** [comment]
Hello guys. I am looking into this. Could you please assign this issue to me?

**Comment by dobooth** [comment]
Happy to see some action on this, @andrewbess!

**Comment by andrewbess** [comment]
Hello @dobooth 
I am finishing it.
I'll create PR tomorrow or the day after tomorrow.
Sorry for my late.

**Comment by PivitParkour94** [comment]
@andrewbess did you end up getting this finished? I've got a custom index running on schedule, but triggering it "on save" seems to require a lot more code digging. It would be awesome if there is a guide to point us in the right direction

**Comment by dobooth** [comment]
Thanks for the update (via Slack) Andrew. We are ready when you are.

**Comment by BarnyShergold** [comment]
@andrewbess - We've not seen an update from you for months on this topic. Please can we have a status report?

**Comment by dobooth** [comment]
@andrewbess one more nag...

**Comment by dobooth** [comment]
Closing as ancient and abandoned. Please open a new issue if the trouble is still relevant.
