### ISSUE TITLE
Magento 1.x REST/SOAP API  jquery not found

### ISSUE THREAD

**Issue by fdrechsler** [magento/devdocs#1601]
Example: http://devdocs.magento.com/guides/m1x/api/rest/http_methods.html

Is trying to get JQuery from http://devdocs.magento.com/common/js/jquery.js 
Resulting in: Failed to load resource: the server responded with a status of 404 (Not Found) 

This makes the Document unusable.

**Comment by jeff-matthews** [comment]
This is fixed now.
