### ISSUE TITLE
This page was deprecated from 2.2.0

### ISSUE THREAD

**Issue by osrecio** [magento/devdocs#1602]
Feedback on page: /guides/v2.2/config-guide/config/disable-module-output.html

Deprecated tag from Magento 2.2: [system.xml](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Backend/etc/adminhtml/system.xml#L20)

**Comment by shrielenee** [comment]
Hey @dshevtsov - Have you had a chance to review this? It looks like the deprecated tag can be removed.

**Comment by dshevtsov** [comment]
@shrielenee  do you mean the deprecated topic? We cannot remove the tag because it is a part of the codebase.
I've asked architects for confirmation of the deprecation and the topic relevance.

**Comment by dshevtsov** [comment]
@melnikovi please help to clarify the issue

**Comment by shrielenee** [comment]
Hey @melnikovi @osrecio - What's the status on this? Was it deleted?

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
