### ISSUE TITLE
Link to Advanced Reporting does not work

### ISSUE THREAD

**Issue by roman204** [magento/devdocs#1604]
![auswahl_502](https://user-images.githubusercontent.com/584168/33939165-61706680-e00a-11e7-905c-c776875b5c88.jpg)

That link refers to http://docs.magento.com.guides/v2.2/advanced-reporting/overview.html
From my thought it should be http://devdocs.magento.com/guides/v2.2/advanced-reporting/overview.html but that URL is also not found.

**Comment by roman204** [comment]
so the correct link is: http://docs.magento.com/m2/ee/user_guide/reports/advanced-reporting.html
will make a pull request

**Comment by dshevtsov** [comment]
@roman204 
Sorry for this inconvenience. 
The Advanced Reporting docs will be published in next one or two hours. The link will be fixed in my commit.

**Comment by roman204** [comment]
Ok thanks for notice
