### ISSUE TITLE
Google Fonts on Magento 2.2

### ISSUE THREAD

**Issue by embed0** [magento/devdocs#1618]
Feedback on page: /guides/v2.2/frontend-dev-guide/layouts/xml-manage.html

In devdoc for Magento 2.2 there is wrong code for external google fonts. Should be the same as Magento 2.0 .

DevDocs 2.2 
`<link src="http://fonts.googleapis.com/css?family=Montserrat" src_type="url" /> 
`
Should be :
` <link rel="stylesheet" type="text/css" src="http://fonts.googleapis.com/css?family=Montserrat" src_type="url" /> `

Spend few hours wondering why it does not work on Magento 2.2

**Comment by jeff-matthews** [comment]
Sorry about that @embed0! Updates will be published when I merge the `imagine-2018` branch with `develop`.
