### ISSUE TITLE
Orders Not Found in Order List API (MagentoRest)

### ISSUE THREAD

**Issue by Prutha29** [magento/devdocs#1624]
Following was the API Call for getting Order List : 
Request Method = GET
Request.params.filter[0][attribute] = created_at
Request.params.filter[0][from] = December 26th 2017, 22:42:18.000
Request.params.filter[0][to] = December 27th 2017, 02:52:46.000
Request.params.limit = 50
Request.params.page = 1
Request Body : Necessary OAuth Parameters
Request URI : https://www.apexmagnets.com/api/rest/orderlist?filter%5B0%5D%5Battribute%5D=created_at&filter%5B0%5D%5Bfrom%5D=2017-12-26T22%3A42%3A18&filter%5B0%5D%5Bto%5D=2017-12-27T02%3A52%3A46&limit=50&page=1

According to this API Call , the response must be having orders with entity_id **102944** , **102945** , **102946** , **102947** , **102948** as these orders were created before December 27th 2017, 02:52:46.000

But i didn't get these 5 orders in the response.
So why these orders were not there in response?

**Comment by keharper** [comment]
@Prutha29 since you seem to be implementing a custom endpoint (`orderlist`), I'm not sure if I can help. If you are imitating `GET /V1/orders`, this should accomplish what you're after. 

```
Request.params.filter[0][attribute] = created_at
Request.params.filter[0][from] = December 26th 2017, 22:42:18.000
Request.params.filter[0][condition_type] = gteq
Request.params.filter[1][attribute] = created_at
Request.params.filter[1][to] = December 27th 2017, 02:52:46.000
Request.params.filter[1][condition_type] = lteq
```
See http://devdocs.magento.com/guides/v2.2/rest/performing-searches.html for more information.

**Comment by keharper** [comment]
@Prutha29 did my previous comment help?

**Comment by Prutha29** [comment]
Thank you for your reply.
But according to our system requirement we can not implement /V1/orders endpoint.

**Comment by keharper** [comment]
The underlying SearchCriteriaInterface works the same. You need to specify separate filters ([0] and [1] for the "from" and "to" operators. 

I'll have to close this issue. Your request is beyond the scope of the devdocs team.
