### ISSUE TITLE
Magento 2 installation failed

### ISSUE THREAD

**Issue by Wen2012** [magento/devdocs#1626]
Fatal error: Declaration of Zend\Mvc\Controller\PluginManager::get($name, ?array $options = NULL) must be compatible with Zend\ServiceManager\AbstractPluginManager::get($name, $options = Array, $usePeeringServiceManagers = true) in C:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\Controller\PluginManager.php on line 211

**Comment by jeff-matthews** [comment]
Hi @Wen2012, please try searching for this error on another forum, like [Magento Stack Exchange](https://magento.stackexchange.com/). The devdocs repo is for Magento documentation issues only.
