### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by rossmitchell** [magento/devdocs#1631]
Feedback on page: /guides/v2.2/config-guide/bootstrap/mage-dirs.html

In the custom entry point code example the second `$params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS]` section clobbers the first and prevents the paths getting set.

The same thing is done in the [pub/index.php](https://github.com/magento/magento2/blob/2.2-develop/pub/index.php#L28) file in the code base, which means that it is not possible to set these values using bootstrap parameters. I'm not sure if this is a bug with the documentation or the code.

If this behavior is supposed to be supported then I'll raise a bug in the magento2 repo. If it is not then the first bullet point should be removed from this page as well

**Comment by camdixon** [comment]
While @rossmitchell is correct the code in 2nd bullet point overrides the first I am unsure of desired functionality.

It does look like they would conflict, and therefore I think the intention is to override the first example with the 2nd example.  Both have `media` examples, and the first one shows a mounted NFS example for the media.  @jeff-matthews it should be shown more clearly if the code is providing 2 different examples of use.  See line 4 compared to line 10 of the code.

```
$params = $_SERVER;
	$params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS] = [
       DirectoryList::CACHE => [DirectoryList::PATH => '/mnt/nfs/cache'],
       DirectoryList::MEDIA => [DirectoryList::PATH => '/mnt/nfs/media', DirectoryList::URL_PATH => ''],
	];

	$params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS] = [
	DirectoryList::PUB => [DirectoryList::URL_PATH => ''],	
	DirectoryList::MEDIA => [DirectoryList::URL_PATH => 'media'],
	DirectoryList::STATIC_VIEW => [DirectoryList::URL_PATH => 'static'],
	DirectoryList::UPLOAD => [DirectoryList::URL_PATH => 'media/upload'],
	];
```

**Comment by rossmitchell** [comment]
Hi,

Thanks for having a look at this. Please allow me to explain what I think on going on.

The docs say that the the media and cache directory will be set to use the NFS directories, but the code example will result in the normal media directory being used, and the cache directory falling back to the default directory as it will not be set in the params variable that is used. This is a bug in the code example and should be corrected.

The more important point is that the Magento code base does the same thing in the `pub/index.php` file, which makes it impossible to override the variables using the instructions [here](https://devdocs.magento.com/guides/v2.2/config-guide/bootstrap/magento-how-to-set.html). 

I think this is a bug in the magneto code base, but I need confirmation that this behavior is supposed to be supported before I raise a ticket. @lorikrell can you please confirm or deny that this is supposed to be possible, and if so I'll create a ticket and pull request to fix it?

Thanks

**Comment by shrielenee** [comment]
Yo @lorikrell - any news on this? 👋 Thanks!

**Comment by shrielenee** [comment]
Hello @buskamuza --- Can you clarify this? Please see above comments.

**Comment by buskamuza** [comment]
Agree, this is incorrect behavior. The specified paths should be default values, in case nothing is provided in `$_SERVER`.

**Comment by dobooth** [comment]
It seems that the bad dupe code has been removed from https://devdocs.magento.com/guides/v2.2/config-guide/bootstrap/mage-dirs.html
@lorikrell @shrielenee Is this still a valid issue?

**Comment by shrielenee** [comment]
It does look like the errant code has been removed. I would confirm with @rossmitchell that this looks correct --- Ross, https://devdocs.magento.com/guides/v2.2/config-guide/bootstrap/mage-dirs.html ???

**Comment by rossmitchell** [comment]
Hi @shrielenee, thanks the docs now look to be accurate. I'll test the instructions in the docs against the latest version of Magento over the weekend and if I hit any issues will raise a ticket there.
