### ISSUE TITLE
Can you remove the comment in module.xml

### ISSUE THREAD

**Issue by shyang292** [magento/devdocs#1634]
Feedback on page: /videos/fundamentals/create-a-new-page/

Hi, I created a new page according the tutorial. After I run "php bin/magento setup:upgrade", it gave me an error "[Symfony\Component\Console\Exception\CommandNotFoundException] There are no commands defined in the "setup" namespace."  

I use "php bin/magento list" to check the error message and found that the comment part in module.xml contains non UTF-8 chars. After I deleted the comment in the module.xml, it work well.

**Comment by jeff-matthews** [comment]
@belbiy, when you get a chance, let's talk about the videos we currently publish.

**Comment by dobooth** [comment]
I couldn't find a bad character. UTF-8 seems to validate on the whole page.

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this, and we could not reproduce this issue. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
