### ISSUE TITLE
Add references to existing files

### ISSUE THREAD

**Issue by ArvidBaa** [magento/devdocs#1636]
Feedback on page: /guides/v2.2/javascript-dev-guide/javascript/js_practice.html

As far as I can see, the files referenced in this article (gallery.js) doesn't include the functions _create and _addOption, as referenced by the file orange-gallery.js. Why is that, and how do the two functions work?

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
