### ISSUE TITLE
 Unable to unserialize value

### ISSUE THREAD

**Issue by surajtupe** [magento/devdocs#1638]
Unable to unserialize the value for only on the latest version, I am trying with a different solution, but I am unable to resolve it.

Below line I am facing the issue.

CRITICAL: Unable to unserialize value. {"exception":"[object] (InvalidArgumentException(code: 0): Unable to unserialize value. at /vendor/magento/framework/Serialize/Serializer/Json.php:39

**Comment by jeff-matthews** [comment]
@surajtupe, please reopen if you have a specific question about documentation.
