### ISSUE TITLE
custom tab implementation in admin product page not working on magento 2.2

### ISSUE THREAD

**Issue by istitutoculturaitaliana** [magento/devdocs#1640]
Hello, a simple implementation to add add a custom tab like the following in the edit product admin page

https://webkul.com/blog/add-tab-product-page-magento-admin/

is not working on magento 2.2 (while it works on magento 2.1.9)
On debug, the execution of the xml layout stops after the constructor of Block file
thank you

**Comment by jeff-matthews** [comment]
@istitutoculturaitaliana: This sounds like an issue that is more appropriate for the [magento/magento2](https://github.com/magento/magento2 ) repo. This repo is for issues related to devdocs content only.
