### ISSUE TITLE
Extra </span> </div> on Create, edit, or unlock a Magento administrator account in Prerequisites section

### ISSUE THREAD

**Issue by neeta-wagento** [magento/devdocs#1641]
There shows n extra </span> </div> tag on http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-admin.html

As i generate HTML from markdown it shows expected result so may be need to generate markdown for the file "guides/v2.1/install-gde/install/cli/install-cli-subcommands-admin.md"

Please refer below screenshots:
![dovdocs](https://user-images.githubusercontent.com/33098216/34648043-f98654d2-f3b7-11e7-99ee-a43129d14a78.png)

**Comment by jeff-matthews** [comment]
Thanks for bringing this to our attention @neeta-wagento!
