### ISSUE TITLE
Need to update this documentation for 2.2 to use bin/magento `dev:query-log:enable`

### ISSUE THREAD

**Issue by rnicklin** [magento/devdocs#1645]
Feedback on page: /guides/v2.2/config-guide/log/log-db.html

The info provided on this page is no longer applicable in M2.2.

You can now enable/disable query logging from the command line using:

./bin/magento dev:query-log:enable

./bin/magento dev:query-log:disable

**Comment by jeff-matthews** [comment]
An internal developer identified this gap a while ago. See [MAGEDOC-2791](https://jira.corp.magento.com/browse/MAGEDOC-2751) for more info.

**Comment by jeff-matthews** [comment]
@rnicklin, please see PR #2046 and let me know what you think.
