### ISSUE TITLE
Missed section in Magento 2.2

### ISSUE THREAD

**Issue by Sharkozp** [magento/devdocs#1652]
http://devdocs.magento.com/guides/v2.2/cloud/trouble/robots-sitemap.html

> 4. Navigate to Stores > Configuration > Design

in Magento 2.2.x Design section not present

**Comment by hostep** [comment]
It's a bit more complicated then that, it was also moved in version 2.1.11. Not sure how the documentation should deal with these config sections if they are moved in between patch versions, it becomes a bit hard to write correct instructions I think.

@Sharkozp: you probably already found it, but in case you hadn't: it has been moved to Content > Design > Configuration

**Comment by hguthrie** [comment]
Thanks for pointing out the outdated information. We updated the UI navigational references for the robots.txt configuration. I also took the opportunity to address other problems related to sitemap/robots troubleshooting, such as including the rewrite solution using a VCL snippet.

**Comment by hostep** [comment]
@hguthrie: thanks!

Be aware that for Magento 2.1.0 until 2.1.10 the configuration for the robots is still located in Stores > Configuration > Design
And the same is probably true for all Magento 2.0.x releases, there isn't even a Content > Design > Configuration section in those versions as far as I'm aware of (but we no longer have shops running on 2.0.x, so I can't verify at the moment)
