### ISSUE TITLE
setup:di:compile help and documentation options mismatch

### ISSUE THREAD

**Issue by AndyHodgesStemcell** [magento/devdocs#1653]
Feedback on page: /guides/v2.2/config-guide/cli/config-cli-subcommands-compiler.html

The options listed on this page don't seem to match those that are actually supported by the application in this version..

Specifically I was looking for the --exclude-pattern option, which isn't available. This is what is available in the app:

"
bin/magento help setup:di:compile
Usage:
  setup:di:compile

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Generates DI configuration and all missing classes that can be auto-generated
"

**Comment by hguthrie** [comment]
Thanks for the update. I will check this topic again to make sure it is clear and accurate.
