### ISSUE TITLE
Cloud: Please add some more information about the CRON_CONSUMERS_RUNNER variable

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1662]
We were having an issue that after deploying to an integration environment, the running message queues were getting killed and not restarted after the deploy had finished.
After a lengthy discussion with the support, they finally gave us a solution. The solution is to add a variable `CRON_CONSUMERS_RUNNER` with the contents `{"cron_run":"true"}` as a JSON value to every environment.

After setting this variable, the deploy process on the cloud will update the `app/etc/env.php` file (section `cron_consumers_runner`) and make sure the cronjobs trigger the spawning of message queue consumers.

I think it would make sense to also add this to the documentation, otherwise it's very unclear as to why message queues aren't working properly.

(This might also apply to staging & production environment, but I haven't really tested those with message queues very thoroughly yet)

Thanks!

(Magento cloud support tickets 10938 & 12268)

**Comment by jeff-matthews** [comment]
Thanks @hostep. This is the next task on my list after I finish updating some release documentation.  I should be able t publish something by this Friday. Tracking internally with MAGECLOUD-1417.

**Comment by jeff-matthews** [comment]
@hostep, I updated the docs with info about the variable. Let us know if you have any suggestions.

http://devdocs.magento.com/guides/v2.2/cloud/env/working-with-variables.html#manage-message-queues

**Comment by hostep** [comment]
Thanks @jeff-matthews, looks good at first sight 👍

Although, I would put it somewhere else, under the 'Working with variables' is not really the right place for it I believe.
Maybe create a new section around Message Queues in the Cloud TOC somewhere, it might make it easier to find if you are researching the message queues topic I think. Or maybe as a topic in Troubleshooting: 'Why aren't the Message Queues being picked up by the cron system?' or something like that.

I myself wouldn't start looking in the 'Working with variables' section to be honest...

**Comment by jeff-matthews** [comment]
That's great feedback @hostep, thanks! I think adding it as a troubleshooting topic makes sense.

We're in the process of redesigning the cloud guide information architecture, so we'll keep this in mind. I'm curious, though, do you primarily use the navigation when looking for specific information like this or do you use search?

**Comment by hostep** [comment]
Mostly the search, sometimes the navigation.
I would use the navigation more often if all topics were expanded, because then I could use cmd/ctrl+f in my browser to see if a topic I'm interested in is listed in the navigation. The fact that all those topics are collapsed by default annoys me a little bit to be honest :)

And if all else fails, I'm going to google and search for something like this:
`site:devdocs.magento.com myquery`

**Comment by jeff-matthews** [comment]
I've heard similar feedback about the collapsed structure and we plan to address that soon with a simple style update. As always, thank you for the thoughtful feedback! It's extremely helpful.

**Comment by jeff-matthews** [comment]
@dmrachkovskyi, I think this would be a good candidate for the KB.

**Comment by jeff-matthews** [comment]
@hostep, what are some of the symptoms you notice when consumers aren't retrieving messages from the queue?

**Comment by jeff-matthews** [comment]
https://github.com/magento/devdocs_internal/pull/1697

**Comment by jeff-matthews** [comment]
Added a [Message queues](http://devdocs.magento.com/guides/v2.2/cloud/trouble/message-queues.html) topic to the Troubleshooting section.

**Comment by hostep** [comment]
Excellent, thanks @jeff-matthews!
