### ISSUE TITLE
When will the magento 2 DevBox available again?

### ISSUE THREAD

**Issue by jrapm** [magento/devdocs#1664]
Hi guys!
I would really like to develop for magento 2, but unfortunately i couldn't find any working solution for setting up a magento 2 box on MacOS High Sierra. I tried the "old" vagrant solution and the "new" Docker solution, but the file syncing between docker/vm and the local file system did never work properly.

Therefore it would be great to have a up2date magento 2 devbox. Is there any plan when this will happen? The information page for the devbox ( http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-over.html ) still says "DevBox is currently undergoing an update and is not available for download. A new version will be available in the near future. Please check back for updates."

Best

**Comment by jeff-matthews** [comment]
That's a great question, @jrapm! @piotrekkaminski, perhaps you could weigh in on this for us?
