### ISSUE TITLE
Path of requirejs-config.js is ambiguous

### ISSUE THREAD

**Issue by patchee500** [magento/devdocs#1670]
Feedback on page: /guides/v2.2/javascript-dev-guide/javascript/js_mixins.html

In Step 2 of "Add a JS mixin" the docs state the following:

> In the requirejs-config.js configuration file in your module, declare the AMD module you created as a mixin to the target module. The file must be located in the <your_module_dir>/view/%area% directory.

From what I've tested this statement is correct.  
However the docs also describe a **Sample RequireJS configuration file** which lies in:
`<Orange_Sample_module_dir>/view/base/web/js/requirejs-config.js`  

I think this should be:
`<Orange_Sample_module_dir>/view/base/requirejs-config.js`

**Comment by jcalcaben** [comment]
Thanks for raising this issue @patchee500 !

I have reviewed and revised the topic to make it less ambiguous.

http://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js_mixins.html
