### ISSUE TITLE
Magento Eway Inbuilt Component

### ISSUE THREAD

**Issue by geetikatina** [magento/devdocs#1680]
Hi , I am going to configure Eway with Magento2.2.2 for Magento_Eway.
But showing us a error Transaction has been decline , please try again. 
Log file showing this error - **getAccountInfo ["GET ACCOUNT INFO for api user :
Authorization has been denied for this request."]**

Need you help.

**Comment by jeff-matthews** [comment]
HI @geetikatina, the devdocs repo is for reporting documentation-specific issues only. It sounds like you need help troubleshooting a very specific problem. Try searching [Magento Stackexchange](https://magento.stackexchange.com/).
