### ISSUE TITLE
Stores -> Configuration -> Advanced -> Developer no longer available

### ISSUE THREAD

**Issue by sadon** [magento/devdocs#1688]
Feedback on page: /guides/v2.2/config-guide/prod/prod_perf-optimize.html
Stores -> Configuration -> Advanced -> Developer
is no longer available in M2.2
So, it need to remove the tab

**Comment by keharper** [comment]
The Developer configuration pages are still there. Are you looking at Admin using a role that has diminished capabilities?

**Comment by sadon** [comment]
I'm looking with:
- Administrator role (default)
- custom role with full access:   Roles Resources- > Resource Access -> All
Looking in "production" mode

**Comment by jeff-matthews** [comment]
I don't think the Developer page is available in production mode.

**Comment by sadon** [comment]
Why not?
when I try to change production-depended settings

**Comment by jeff-matthews** [comment]
@sadon, please see the following issue for more information: https://github.com/magento/magento2/issues/11191 

We'll add a note to the documentation to prevent future confusion. Thanks.

**Comment by shrielenee** [comment]
A Jira issue has been created to track this - [MAGEDOC-3018](hhttps://jira.corp.magento.com/browse/MAGEDOC-3018).

**Comment by lorikrell** [comment]
For 2.2, this content moved to the file https://devdocs.magento.com/guides/v2.2/performance-best-practices/configuration.html.  Adding a notation to the page. Will link to a PR.

**Comment by lorikrell** [comment]
Content available in page https://devdocs.magento.com/guides/v2.2/performance-best-practices/configuration.html shortly. The merged PR will generate final docs within an hour of ticket closure. Thank you!
