### ISSUE TITLE
Invalid package name in file package.xml when download Magento 1.0 extensions for Magento marketplace.

### ISSUE THREAD

**Issue by Avinashsain** [magento/devdocs#1689]
Issue with package name - <name>yappn+Windrose_Global_Ecommerce</name>
Real Package Name - Windrose_Global_Ecommerce
With issue - yappn+Windrose_Global_Ecommerce
![package-name-error](https://user-images.githubusercontent.com/5372860/35800424-f0b0daec-0a8e-11e8-8c04-01e7fed71f27.png)

**Comment by jeff-matthews** [comment]
Hi @Avinashsain, 

The devdocs repo is for documentation-specific issues only. It looks like you're trying to report an issue with a third-party Magento developer's extension.  

The best place to start if you need help with a specific extension is to contact the developer. The developer's contact information is available on the Magento Marketplace: https://marketplace.magento.com/yappn-windrose-global-ecommerce.html#product.info.details.support
