### ISSUE TITLE
Cloud: notification log levels make no sense

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1690]
Feedback on page: [/guides/v2.2/cloud/env/setup-notifications.html](http://devdocs.magento.com/guides/v2.2/cloud/env/setup-notifications.html)

Hi guys

I've just tested these Slack notifications during a deploy.
But I'm trying to understand the log levels at the bottom of the page, they don't make much sense.
It feels like these descriptions are just (incorrectly) copy/pasted from someplace else because they don't seem to describe anything from the deploy process.

I just tried both 'debug' and 'info' (there is zero difference in using those log levels btw), I see a million different messages posted on Slack (feels really spammy), of which none have the type 'debug', most have 'info', and only a few 'notice' and 'warning'.
It's currently not really useful these messages, it would be much more useful if we see:
- deploy has started
- maintenance mode is enabled, shop is down
- maintenance mode is disabled, shop is back up
- deploy has finished
- and various errors which could occur during a deploy

That's much more useful in my opinion :)
Anyway, that last bit is just a complaint for the Cloud team, I'll create a new ticket on the Cloud support to ask for these improvements.

For the documentation team, it would be better if the docs could get updated with what we can expect from these log levels and remove the current descriptions which seem to make no sense.

Thanks!

**Comment by jeff-matthews** [comment]
HI @hostep,

Thanks for the feedback! To provide a bit more context, I believe we're using [Monolog log levels](https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#log-levels) for this functionality. I'll investigate adding more info about what to expect on cloud for each level.

**Comment by hostep** [comment]
Ah ok, the monolog log levels. These don't really make sense over here indeed :)

----

Just another quick notice, I've had a hard time figuring out how to create a Slack user token and after reading up on Slack documentation for more then an hour, finally found the one I needed, which was to create a custom Bot user which then has a token after it was created: https://api.slack.com/bot-users#custom_bot_users
But since there are [multiple types of tokens](https://api.slack.com/docs/token-types), I'm not sure if you should recommend the Bot user one, although it might be helpful for other people which don't have a lot of experience with setting up Slack integrations so they don't have to search around for which one they need.

----

Ah, and one last thing, around the example Slack configuration:
```yaml
log:
  slack:
      token: "<your-slack-token>"
      channel: "<your-slack-channel>"
      ...
```

Those `<your-slack-token>` and `<your-slack-channel>` aren't really examples (it's an exact copy/paste of a bit higher on the page, same thing with the email examples btw).

It's useful to have an actual example, because for example we use other Slack integrations in our non-Cloud projects, and over there we have to enter the `channel` and it has to start with a `#` sign. But over here this is is not necessary, so it would be nice to see this in the example configuration with a true example to avoid having to guess this.

So I would suggest to replace the above with something like this:
```yaml
log:
  slack:
      token: "abcd-0123456789-a0b2c3d4e5f6g7h8"
      channel: "my-slack-channel"
      ...
```

This is just something minor though.

**Comment by jeff-matthews** [comment]
Thanks @hostep. I'll update the examples and link out to Slack's docs about creating tokens.

**Comment by ralbin** [comment]
If I may also chime in, I would really love for there to be some screenshots/examples of each log level type.  This would allow me to rule out some of them without having to try each one to see what the output would look like.

**Comment by ralbin** [comment]
![notice](https://user-images.githubusercontent.com/11746350/36152467-c90ef49e-1090-11e8-8f23-308977c68977.png)
![info](https://user-images.githubusercontent.com/11746350/36152461-c59ddb90-1090-11e8-8e8b-e0d2165e0479.png)

**Comment by hguthrie** [comment]
It appears that the _Log levels_ descriptions were updated and the example for configuring Slack updated to include reference to the user token information. I'm looking at the idea of the screenshot/examples.

**Comment by hguthrie** [comment]
There are still some internal issues open to clean up the logging output. When development is complete, I will update the docs accordingly.

**Comment by hguthrie** [comment]
There have been many improvements from development on log levels and log message formatting in the last couple of releases. I am closing this issue.
