### ISSUE TITLE
JS bundling references the now removed "Developer" configuration section in production

### ISSUE THREAD

**Issue by xfrenette** [magento/devdocs#1691]
Feedback on page: /guides/v2.2/frontend-dev-guide/themes/js-bundling.html

The documentation explains how to bundle JS in *production* mode by going to "Configuration > Advanced > Developer" but [this section was removed in 2.2 in production mode](http://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/technical-details.html#config-deploy-admin).

If bundling is still possible, the documentation should be updated.

**Comment by dobooth** [comment]
Closing this. Looks like the topics have been updated to show the CLI instructions only.
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/js-bundling.html
