### ISSUE TITLE
Coding Style Guide - Doesn't contain explanation on PHP short echo tags for PHTML

### ISSUE THREAD

**Issue by careys7** [magento/devdocs#1697]
I couldn't find any guidelines regarding the use of the following syntax in PHTML files:

```php
<?= $block->getAdjustmentsHtml() ?>
```

It's used in most of the core templates, should this be included in the style guide?

**Comment by jeff-matthews** [comment]
Yes, we should document this in the [Frontend Developer Guide](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/templates/template-overview.html). The [Templates basic concepts](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/templates/template-override.html) topic might be the best place.

>Use short tags `<?=` when outputting data in templates.

According to internal devs, this guidance is for 2.2 and greater.

**Comment by camdixon** [comment]
@jeff-matthews I noticed "help wanted label", and decided to update.  What changes should be made here or do you have other ideas to add?

**Comment by jeff-matthews** [comment]
Thanks @camdixon! 

@jcalcaben, please review and edit PR https://github.com/magento/devdocs/pull/1857
