### ISSUE TITLE
Magento Commerce Cloud Starter backups

### ISSUE THREAD

**Issue by jaustinlam** [magento/devdocs#1704]
On the starter architecture http://devdocs.magento.com/guides/v2.2/cloud/basic-information/starter-architecture.html.

> <b>Backup and disaster recovery</b>
We automatically back up your Production environment every six hours. This snapshot and backup includes your deployed code, installed software and services, and data. You can also perform snapshots and database dumps with CLI commands.

It was my belief that the Production environment is not automatically backed up on Magento Cloud Starter.

**Comment by jeff-matthews** [comment]
@hguthrie, it might be worthwhile to address this and [MAGECLOUD-1725](https://magento2.atlassian.net/browse/MAGECLOUD-1725) together.

**Comment by hguthrie** [comment]
Thanks for pointing this out. I updated the section on Starter backup. I am also working on the snapshot topic to improve clarity.
