### ISSUE TITLE
Admin Token returned by Magento doesn´t work

### ISSUE THREAD

**Issue by dgoldfeder** [magento/devdocs#1708]
I tried to explain what is going on,

I am sending my user and password to get an admin token authorization and I got one to create and/or upgrade products and it is workin just fine, BUT when I do the same to create the images for those products I always received the error message:

`**"(string) {"message":"Consumer is not authorized to access %resources","parameters":{"resources":"Magento_Catalog::catalog"}}"**`

Why this is working to create products but not images?

I tried sending the same authorization token for create products to create images and I also tried to get a new authorization token for the images and the result is the same.
Both calls use the same user that has administrator permission

**Comment by keharper** [comment]
@dgoldfeder This is a technical question, and possibly a bug. To me, your call should work, assuming your administrator has full permissions to access the Catalog. Please go to https://github.com/magento/magento2/issues and see if the issue has been reported, and open the issue if it hasn't.
