### ISSUE TITLE
Broken link on config-php

### ISSUE THREAD

**Issue by mbrinton01** [magento/devdocs#1709]
Open page: http://devdocs.magento.com/guides/v2.0/config-guide/config/config-php.html

* Go to *Environmental configuration* section
* Under *Cache Storage* in *Structure* column, there is a link to _frontend options_

Link is invalid.

**Comment by keharper** [comment]
Thanks @mbrinton01  

I fixed the link in the 2.0 and 2.1 versions of the file. The directory structure diagrams were previously removed in the 2.2 version, so no action required there.
