### ISSUE TITLE
Duplicate page/Missing rsync doc

### ISSUE THREAD

**Issue by xpoback** [magento/devdocs#1710]
Feedback on page: /guides/v2.2/config-guide/deployment/pipeline/example/rsync.html

The page is just a copy of [Using environment variables ](/guides/v2.2/config-guide/deployment/pipeline/example/environment-variables.html)

I suppose it isn't done yet, but please mark it as stub then, so people don't lose their time looking for `rsync `in the whole article.

**Comment by jcalcaben** [comment]
Thanks for bringing this to our attention @xpoback ! 
I've created an internal issue for this task to track this effort.

**Comment by keharper** [comment]
@jcalcaben You removed the rsync document in [PR-2694](https://github.com/magento/devdocs/pull/2694). Was that work attached to this issue?

**Comment by jcalcaben** [comment]
It was attached to #2677 but it probably fixes this too. Closing issue.
