### ISSUE TITLE
Typo in lib reference

### ISSUE THREAD

**Issue by vil11** [magento/devdocs#1715]
Feedback on page: /guides/v2.2/install-gde/prereq/install-rabbitmq.html

## Steps to reproduce
1. Navigate to **Install RabbitMQ** section inside http://devdocs.magento.com/guides/v2.2/install-gde/prereq/install-rabbitmq.html article.
2. Try to execute command located in step 2.

## Actual result
It looks like the command is broken. Please fix so that users could easily install Rabbit MQ using devdocs.

Thanks in advance!

**Comment by dshevtsov** [comment]
Fixed.
Thank you, @vil11 !
