### ISSUE TITLE
Add option 'opened'

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/devdocs#1717]
Feedback on page: /guides/v2.1/ui_comp_guide/components/ui-fieldset.html

Add option 'opened' so we know how a fieldset can be expanded by default.

**Comment by jcalcaben** [comment]
Thanks for bringing this issue up @PascalBrouwers !

The documentation for Fieldset has been updated: 
http://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-fieldset.html
