### ISSUE TITLE
File system ownership for shared hosting (production mode) - Make code files and directories read-only

### ISSUE THREAD

**Issue by sfritzsche** [magento/devdocs#1719]
Feedback on page: https://devdocs.magento.com/guides/v2.3/config-guide/prod/prod_file-sys-perms.html
In your section "Make code files and directories read-only" (in 4.) you suggest to run the following command: "chmod u+x bin/magento". Wouldn't be better, to do nothing else than "chmod o-" and "chmod u-" things in this general case ?

**Comment by mrs45p** [comment]
- name: Setup JFrog CLI
  uses: jfrog/setup-jfrog-cli@v1.0.5

**Comment by BarnyShergold** [comment]
@sfritzsche @dobooth 
This simple issue has been open for 2.5 years and the page is not updated.
@sfritzsche  can you explain why the chmod u+x bin/magento should be removed? After this time it doesn't seem to be a problem.

This issue will be closed in 14 days if there is no response.

**Comment by sfritzsche** [comment]
@BarnyShergold
I think my original idea was not to remove the command "chmod u+x bin/magento", but to remove it from point 4 "Remove write permissions to the following directories" and to transfer it to a new point 5 "Make Magento commandline tool executable".

For a better understanding.

I have to admit that it was not very clever of me to open an issue for this topic. A direct "Pull Request" would have been much more effective.
