### ISSUE TITLE
REST usage notes need to be re-validated

### ISSUE THREAD

**Issue by ilima-ebay** [magento/devdocs#1721]
The REST usage notes in  http://devdocs.magento.com/guides/v2.2/rest/notes.html states

> a user could potentially specify one ID in the URL and another in the request body. Whenever this type of conflict occurs, **Magento uses the value specified in the URL**.
For example:

> The REST URL to update a customer is <route url="/V1/customers/:id" method="PUT">. If you specify an ID value of 1 in the URL (http://magento.loc/customer/1), and a body of { "id": 2, "attr": "value" }, the customer with ID of 1 will be modified.

> This applies to all REST APIs where a parameter is passed in the URL. **Anything specified in the request body with the same parameter name as the URL will be ignored**.

However, I have tested in 2.0.x, 2.1.x and 2.2.2 and it looks like it is the other way around. **Magento is actually ignoring the parameter in the URL and using the value specified in the payload.**

Using the same example of modifying a customer.
These are some of my current users:
<img width="1281" alt="customers_backend" src="https://user-images.githubusercontent.com/13220467/36489771-69f45578-16ec-11e8-8dc1-3d2f8ce8e218.png">

If I wanted to add middle name to customer with Id =4 but by accident in my request I type customer Id =5. Per documentation, customer id =5 should be modified, however, it is the customer with id =4 (specified in the payload) the one that gets modified.

<img width="602" alt="request_and_response" src="https://user-images.githubusercontent.com/13220467/36490114-29595f30-16ed-11e8-8e16-5d01f6b1e514.png">

<img width="1276" alt="updated_customers_backend" src="https://user-images.githubusercontent.com/13220467/36489778-6dc56ce6-16ec-11e8-8597-d70c56de0c62.png">

Please note that in order to update a customer, email, firstname, lastname and website id is required.
I cannot modify a customer with just a payload like the one mentioned in the documentation
`{ "id": 2, "attr": "value" }`

I also tested updating a product using /V1/products/{sku} and got the same results.

**Comment by keharper** [comment]
I can confirm that the URL parameter is being ignored. I spoke with @paliarush, and he said that the documented behavior is the intended behavior, so you've find a bug. I'll check back in a few days after development determines how to proceed.

**Comment by jcalcaben** [comment]
@keharper what's the status of this issue?

**Comment by dobooth** [comment]
We should document how it is currently working. The URL params are ignored and overwritten by the POST data.
