### ISSUE TITLE
Disable Module Output in 2.2

### ISSUE THREAD

**Issue by walrus28** [magento/devdocs#1724]
Magento 2.2.2 Single Deployment
Disabling the Output of the Review Module by editing <Magento_install_dir>/app/etc/config.php

Following the instructions on the [DevDocs page](http://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html) did not disable the output of the module.
Below is the code from the DevDocs page:
`'advanced' =>
array (
  'modules_disable_output' =>
  array (
    'Magento_Review' => '1',
  ),
)`

Instead, I added the code shown below to disable the output of the module.
`  'system' => 
  array (
    'websites' => 
    array (
      'base' => 
      array (
        'advanced' => 
        array (
          'modules_disable_output' => 
          array (
            'Magento_Review' => '1',
          ),
        ),
      ),
    ),
  ),`

**Comment by shrielenee** [comment]
Hey @walrus28 - thanks for bringing this to our attention! This snippet is more descriptive and elaborative. We've made the changes: http://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html.
