### ISSUE TITLE
Clarify use of require and suggest in composer.json

### ISSUE THREAD

**Issue by lfolco** [magento/devdocs#1727]
Feedback on page: /guides/v2.2/coding-standards/technical-guidelines.html

The docs state this:

> 8.3. If component A uses behavior of Component B, such Component B MUST be declared in the require section of Component A’s composer.json file, except for cases where Component B is used in the code that customizes the behavior of Component B.

Can you clarify what "except for cases where Component B is used in the code that customizes the behavior of Component B" means?

> 8.4. If component A extends/customizes the behavior of component B through its customization points (layout handles, plugins, events, etc.), such Component B MUST be declared in the suggest section of Component A.

It mentions customization points, but gives an incomplete list ("layout handles, plugins, events, etc."). Can you give a complete list, or a link to a complete list, of customization points?

Finally, the rules around _suggest_ bring up an interesting question. For example:  You have a module that exists solely to write to a log upon every customer login, observing the `customer_login` event. Does this module _require_ or only _suggest_ the customer module? According to the guidelines, it should be _suggest_, but the module wouldn't do anything at all without the customer module.

**Comment by Vinai** [comment]
> Finally, the rules around suggest bring up an interesting question. For example: You have a module that exists solely to write to a log upon every customer login, observing the customer_login event. Does this module require or only suggest the customer module? According to the guidelines, it should be suggest, but the module wouldn't do anything at all without the customer module.

This one I can reply to, since I asked the exact same question in the past. It confused me at first, too.

You are correct. A module should only require another module if the absence would cause errors or exceptions. A module not doing anything does not break Magento, so in your example `suggests` is correct.

This is counter-intuitive and seems to go against common sense in many cases.
In fact, for integration testing purposes of such a module it would make more sense to use `require`, so that `Magento_Customer` would be installed, too, on CI, so the module tests can run.

For now I have decided for myself that the rules make sense for the core team, but not necessarily for third party code.

**Comment by meker12** [comment]
We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the   Installation and Configuration Documentation project.

**Comment by dobooth** [comment]
@Vinai If you can make a PR with a suggested improvement to the Technical Guidelines, we can get the architects to start arguing over it and get some clarification. It is def a confusing statement.

**Comment by Vinai** [comment]
@dobooth Magento is built around composer and these usage guidelines, and changing them would probably have far reaching effects. I don't think that's a fight I want to pick.
Instead, I'll just continue to educate external companies to not follow the Magento guidelines, and use more practical approach for their own code instead.
Core contributions of course would still need to follow the official guidelines.

**Comment by dshevtsov** [comment]
@buskamuza @paliarush could you please help to clarify technical guidelines?

**Comment by shrielenee** [comment]
@paliarush @buskamuza Can we please get some assistance here? 🙏

**Comment by buskamuza** [comment]
Yes, the guidelines are meant to use "require" in case absence of the dependency will break the application (errors), and "suggest" for soft dependencies, the ones which absence will not lead to errors.

Yes, the use case discussed in this thread leads to questions, as having logging module which is doing nothing in case Customer module is absent doesn't make much sense. In the same time, what if the logging module would be logging any entity "save"? Should it require all modules that call entities save? Now the rules become more complicated up to the point "it's up to the developer", which may be convenient for the developer (though it may be even more cunfusing). But may be less convenient for the end user. Yes, having a module that is doing nothing is not great, but it might be also not the critical issue. So the rules were written following the simple rule (though I agree the representation is far from good): "require" if it leads to errors, "suggest" if it does not.

IMO, if guidelines don't make sense, suggestions are welcome. This is the point of having it open, including open for contributions. So if there is better definition of "require" and "suggest" it would be good to review those. This would be question to our Dev Guild, I think. cc @okorshenko .

**Comment by dobooth** [comment]
Closing this. It seems that between Olga and Vinai, it's accurate but doesn't cover every scenario. And the proper use of 'suggest' and 'require' is a fine topic for the Dev Guild. Updating that doc usually takes a lot of discussion so we will let that happen in its own time.
