### ISSUE TITLE
No before/after attributes for referenceBlock and referenceContainer in Magento 2.2

### ISSUE THREAD

**Issue by zennco** [magento/devdocs#1729]
Feedback on page: /guides/v2.2/frontend-dev-guide/theme-best-practice.html

The page contains the following sentence:
"reorder blocks and container using the before/after attributes of the `<referenceBlock>/<referenceContainer>` instruction

In fact, according to XSD, these elements do not allow before/after attributes.

**Comment by bdenham** [comment]
Hey @zennco , good catch. Would you be willing to submit a pull request with the update you're recommending? If so, here are some basic instructions on how to contribute to devdocs on our DevDocs Contributions page.

**Comment by clivewalkden** [comment]
I'll check this out and submit a PR if it's still needed.

**Comment by bdenham** [comment]
That would be great, Clive. Thanks.

**Comment by bdenham** [comment]
Fixed in https://github.com/magento/devdocs/pull/2854
