### ISSUE TITLE
Change project's URL to devdocs.magento.com

### ISSUE THREAD

**Issue by bluk** [magento/devdocs#173]
On https://github.com/magento/devdocs, there is a link to "Magento developer resources 
http://www.magento.com". Perhaps that should be changed to http://devdocs.magento.com/ to show the published website instead.

**Comment by xcomSteveJohnson** [comment]
That link is intentional. We discussed it internally. The Magento 2 GitHub has the same link.

**Comment by Narno** [comment]
In this case, could you put the link in the readme?

Is it a good compromise?

**Comment by xcomSteveJohnson** [comment]
Updated the REAME.md with more contact information, including a link to devdocs.magento.com

**Comment by Narno** [comment]
Nice, thank you Steve!

**Comment by xcomSteveJohnson** [comment]
We're happy to help. Let us know what else we can do.
