### ISSUE TITLE
the instructions for 2.1 command line upgrade with sample data will not work for 2.2

### ISSUE THREAD

**Issue by Dx3webs** [magento/devdocs#1736]
Feedback on page: /guides/v2.2/comp-mgr/cli/cli-rc1-samp.html

**Comment by shrielenee** [comment]
Hey there @Dx3webs  - thanks for hitting us up about this. Can you provide further information about where the process fails, what part of it runs successfully for you, or what you're setting when its failing?

I see that this topic does need to be updated, as it's referencing an update process from 2.0 to 2.1.

If we can get more info that will make it easier to pinpoint the issue and update the docs! Thanks.
