### ISSUE TITLE
Add Mod_version to system requirements

### ISSUE THREAD

**Issue by amenk** [magento/devdocs#1737]
http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

should state the requirement for "mod_version"

See also

https://github.com/magento/magento2/issues/12777
https://github.com/magento/magento2/issues/13850

**Comment by shrielenee** [comment]
Thanks @amenk for bringing this to our attention! Check it: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html.
