### ISSUE TITLE
Missing image in "Apply and configure a storefront theme" article

### ISSUE THREAD

**Issue by zanilee** [magento/devdocs#1738]
There is a missing image in "[Apply and configure a storefront theme](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-apply.html)": 
> 2. In the configuration record corresponding to your store view, click Edit. The page with design configuration for the selected scope opens. For example: 

`<img src="/common/images/fdg/apply_theme.png" alt="Design Configuration page for a particular scope">`

Applicable for 2.1, 2.2 and 2.3 documentation versions

**Comment by keharper** [comment]
Thanks for spotting this, @zanilee . It turns out the graphic file was saved with the `.PNG` extension, while the link pointed to `.png`. That was enough to cause problems.
