### ISSUE TITLE
Cant switch mode. 

### ISSUE THREAD

**Issue by ravnarayan** [magento/devdocs#1742]
Feedback on page: /guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html

Hello Team, Have been hitting my head on this and can't seem to figure out how to change the mode to developer. 

I'm am using Magento 2 via AWS Lightsail and builtin SSH via lightsail instance. THat said i am also using AWS Cloud 9 for file path/tree. 

what i am trying to do is add styles and scripts to my my page via magento online dashboad Path: content/configuration/edit(storeview)/HTML Head.

but in order for me to do this i have to load my .css, .js files on my file tree via aws cloud 9, i have done that but it wont launch as i am not on developer mode. 

can you please advise how i can change my magento 2 to developer mode? as the doc i am use mentioned above the instructions are not working 
when i type in "magento deploy:mode:show" cames back as magento: command not found

I have also tried going in do sudo su/cd, and typing in magento deploy:mode:set developer still nothing it says magento command not found. 

please advise, looking forward to your reply team. and thank you very much in advance for all your help.

Regards, 

Rav.

**Comment by jeff-matthews** [comment]
Hi @ravnarayan,

The topic you cite assumes you've read this topic first: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli.html

If you haven't added `<magento-install-directory>bin` to your system `PATH` as described [here](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli.html#config-install-cli-first), then you can expect an error when running the `magento` command by itself.

The sample we provide in the topic you cite doesn't make that clear and that's something we can fix. I think it's better to use a sample that doesn't require confniguring your system path. 

In the meantime, try running alternate forms of the `magento` command described in the note at the end of this topic: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli.html. For example, `cd` to your Magento installation directory and enter `bin/magento deploy:mode:show`.

**Comment by camdixon** [comment]
Shouldn't the docs say bin/magento command_here, because a more advanced user (not all users are advanced or assume this) can add the bin to their system ```path```? Then all of the docs would be more simple to follow.  

I noticed differences where some of the docs here do show bin/magento in front of it and some only show magento.

**Comment by jeff-matthews** [comment]
Yes @camdixon, I agree. It's on our to do list, but we won't be able to get to it right away. However, if you submit a pull request to update the docs I can process it quickly.

**Comment by camdixon** [comment]
Sure, I will work on this.

**Comment by camdixon** [comment]
@jeff-matthews I have created an initial pull request to dev docs (first one).  If all is ok I will adjust other CLI devdocs pages to reflect this as well, and mention this issue.

**Comment by jeff-matthews** [comment]
Thanks so much for helping with this @camdixon!
