### ISSUE TITLE
Security scan instructions incorrect

### ISSUE THREAD

**Issue by terolahtinen** [magento/devdocs#1751]
Thank you for the great security scan tool. 

Unfortunately, the instructions provided do not take into account that Magento 2 is a very buggy software. 

> Click Content > Design > Configuration. In the Action column, click Edit next to the website.
> To add the code to the HTML head, expand HTML Head. Enter the code in the Scripts and Style Sheets field.
> When you're finished, click Save Configuration.

This does not save the configuration, see Magento 2 issues 5288 and 5666. 
https://github.com/magento/magento2/issues/5288
https://github.com/magento/magento2/issues/5666

The instructions should be updated with something that actually works with Magento 2.

**Comment by jfrontain** [comment]
Hi @terolahtinen, just acknowledging that we've received your issue and hope to resolve it in the next week or two. Thanks for your patience.

**Comment by jfrontain** [comment]
@terolahtinen, thanks for logging this issue, and we’re glad to hear that you find the Security Scanner tool helpful.  Our Security scanner team has confirmed that the instructions for the following supported versions of Magento 2 (2.0.18, 2.1.12, 2.2.3. 2.3.0) are accurate, and they will not update the instructions for earlier versions. We’re closing this issue, but we encourage you to log issues as needed for the Magento versions listed above.
