### ISSUE TITLE
DIsabled and Excluded From menu categories are still coming in frontend

### ISSUE THREAD

**Issue by BabliDey** [magento/devdocs#1753]
I am Using magento 2.1.8. php 7.

Steps to Reproduce:
After login go to Product> categories. Click one of the sub categories of default category. 
Set:
1.  Enable Category to no
2.  Include in Menu to no
3. Displaysetting > Anchor to no.

run
1.  php bin/magento indexer:reindex
2.  php bin/magento catche:clean 
3.  php bin/magento catche:flush

Result Should be:  the disable menu should not appear in frontend.

Result I am getting: the disabled excluded from menu still appearing in frontend.

Need to fix this.

**Comment by jeff-matthews** [comment]
@BabliDey, it looks like you may have found a bug. Please report issues like this in the repo for the Magento code base: https://github.com/magento/magento2/issues

This repo is for documentation-specific issues only.

**Comment by BabliDey** [comment]
Thank you @jeff-matthews . I have posted this in magento 2 issue section . https://github.com/magento/magento2/issues/14084
