### ISSUE TITLE
Typo in _includes/install/cli_help-commands.html

### ISSUE THREAD

**Issue by SvanteAvenla** [magento/devdocs#1757]
According to the informastion in _includes/install/cli_help-commands.html the command for listing all available commands is _magento --list_. This command doesn't work, the command should instead be _magento list_, without the dashes.

**Comment by jeff-matthews** [comment]
Thanks for bringing this to our attention @SvanteAvenla. You're right. The correct command is `bin/magento list`. 

Interestingly, Magento v2.0 and 2.1 accepts both commands (e.g., `list` and `--list`), but v2.2 throws an error. We'll get this updated.

**Comment by bdenham** [comment]
Thanks @SvanteAvenla. I also removed the hyphens from the help command as it operates without them as well.
