### ISSUE TITLE
No clear definition of public content as in private content.

### ISSUE THREAD

**Issue by kshaa** [magento/devdocs#1761]
Feedback on page: /guides/v2.2/extension-dev-guide/cache/page-caching/public-content.html

I'm not sure what you mean by public content as opposed to private content which is clearly defined as "specific to individual users".
Does public content mean it's like content that is ok if it was leaked (e.g. whether user is logged in) or is it content that is always the same for everyone.

**Comment by jeff-matthews** [comment]
@kshaa, we actually describe  public content in more detail in the parent topic here: http://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching.html#public-and-private-content.
