### ISSUE TITLE
The app:config:dump command does not exists in 2.2.2

### ISSUE THREAD

**Issue by kirkmadera** [magento/devdocs#1762]
Feedback on page: /guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-export.html

I want to be able to compile static content without the db as part of a build process, but am blocked by this. 

The app:config:dump command does not exists in EE 2.2.2. I just ran a composer update to make sure. I managed to get it to work by copying the content of the example app/etc/config.php for the "scopes" key.

**Comment by hostep** [comment]
Over here the `app:config:dump` command exists both in CE & EE 2.2.2, so I think something is wrong with your installation ;)

My guess is that you haven't installed Magento yet (haven't run the `setup:install` command), in that case there are a lot fewer command available, including the `app:config:dump` command.

Btw: if you have support questions around your installation, it might be best to ask them over at https://magento.stackexchange.com/

**Comment by kirkmadera** [comment]
Yes, thank you. I figured it out. This command only exists from a working environment with an app/etc/env.php and app/etc/config.php and valid db. I see it now and was able to get static compilation without a db working correctly.
