### ISSUE TITLE
Wrong indexer interface

### ISSUE THREAD

**Issue by vinkiel** [magento/devdocs#1782]
Feedback on page: /guides/v2.1/extension-dev-guide/indexing-custom.html

> Custom indexer logic
Your custom indexer class should implement \Magento\Framework\Indexer\ActionInterface, and the indexer should be able to perform three types of operations:

> class Popular implements \Magento\Indexer\Model\ActionInterface, \Magento\Framework\Mview\ActionInterface

~~\Magento\Indexer\Model\ActionInterface~~ instead **\Magento\Framework\Indexer\ActionInterface** used.
\Magento\Indexer\Model\ActionInterface is not exist in repository at all https://github.com/magento/magento2/tree/2.1/app/code/Magento/Indexer/Model

**Comment by jcalcaben** [comment]
Fixed in #1783 and #2018
