### ISSUE TITLE
Cloud: not clear if routes.yaml works on staging & production as well

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1785]
Feedback on page: [/guides/v2.2/cloud/project/project-conf-files_routes.html](http://devdocs.magento.com/guides/v2.2/cloud/project/project-conf-files_routes.html)

First it is stated that the `routes.yaml` file also works on staging and production:
> Magento Commerce processes an incoming URL using a route. The routes.yaml file—located at .magento/routes.yaml in your project—**defines routes for Integration, Staging, and Production environments**.

But then just after, it is being denied again:
> Changes you make using YAML files affect **your Integration environment only**. For technical reasons, **neither Staging nor Production environments use YAML files**. To make these changes in a Staging or Production environment, you must create a Support ticket.

Can this be cleaned up, so we know what is actually true?

Thanks! :)

**Comment by jeff-matthews** [comment]
Thanks @hostep! We'll add this to our queue.

**Comment by hguthrie** [comment]
Granting and denying in the same introduction is not very polite. I updated the note to be more specific when this restriction applies. This note is used in other places, so this fix helps other YAML topics, too. Good catch!

**Comment by hostep** [comment]
Thanks @hguthrie, but unfortunately it is still incorrect.
Based on the feedback which I got in the Magento Community Engineering Slack workspace (by @ypyltiai I think?), we can't change the routes using the `routes.yaml` file, even for projects created after 23 October. They said "it is coming", but isn't here yet. For other yaml files it is correct, but not for the `routes.yaml` and cronjobs cant' be changed as well.

This is the file which they send me:
![arch](https://user-images.githubusercontent.com/85479/38272275-0e8921ec-3789-11e8-9f8e-383cd8363ccc.png)

**Comment by hguthrie** [comment]
Okay, I see what you are saying. I will review it again.
