### ISSUE TITLE
Cloud: some documentation to explain we can modify php.ini file would be helpful

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1786]
Hi guys

This was discovered by talking to the Magento Cloud support, but apparently there is a file [`php.ini`](https://github.com/magento/magento-cloud/blob/master/php.ini) included in the Magento Cloud files, and this file allows us to change certain php values on the server (also on staging & production).
I can't seem to find anything about this in the documentation for the Cloud, so this would make a nice addition I think for other people looking for that info?
I think it makes sense to add it underneath the ['Configure environments'](http://devdocs.magento.com/guides/v2.2/cloud/env/environments.html) section?

Thanks!

Pieter

**Comment by jeff-matthews** [comment]
Thanks @hostep! We'll add it to our queue.

**Comment by hguthrie** [comment]
There is a section in the Cloud guide that mentions customizing `php.ini` settings. Ideally, we could extract that section to a new topic and expand on it. The section is in:
[Configure environments > Application > Configure PHP options](https://devdocs.magento.com/guides/v2.2/cloud/project/project-conf-files_magento-app.html#customize-phpini-settings)

**Comment by hguthrie** [comment]
Adding the corresponding internal tracking: MCLOUD-1620

**Comment by BarnyShergold** [comment]
@hguthrie @jeff-matthews I've just taken another look at this page : https://devdocs.magento.com/cloud/project/project-conf-files_magento-app.html 

It is much too long and contains information about a wide variety of topics. I would recommend this page be broken up in small pages and made sub-pages of Configure Environment > Application. To join "Set Cache For Static Files"

I would be happy to do this task if we can agree it should be done- this would make PHP.INI it's own page and menu point

**Comment by hguthrie** [comment]
@BarnyShergold I completely agree with you. All the configuration information in that topic is applicable to the application configuration and breaking out the subjects makes sense. The internal tracking seems to have become technical debt, but the original intent was to do as you describe. Properties and Variables is enough for the one topic, but customizing PHP settings and understanding Workers should be separate topics under Application.

If you would like to take that on, it would help out immensely. 😄

**Comment by BarnyShergold** [comment]
@hguthrie - I'll take this one
