### ISSUE TITLE
Is $_isScopePrivate really deprecated?

### ISSUE THREAD

**Issue by suhasdhoke** [magento/devdocs#1788]
http://devdocs.magento.com/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.html

In the above page, it is mentioned that the block property $_isScopePrivate is obsolete and won't work properly; however I didn't found any related documentation or any @deprecated word against this property.

This has already being highlighted in issue #776 but it does not have any related clarification.

Can we have some more clarity on this?

**Comment by kokoc** [comment]
Hi @suhasdhoke,
Yes, $_isScopePrivate property is obsolete. The proper replacement for private blocks is sections described in the same article. The new approach allows to deliver and invalidate the private content more precisely.

Internally, we have a task (MAGETWO-56701) to mark $_isScopePrivate property of lib/internal/Magento/Framework/View/Element/AbstractBlock.php as deprecated. It's not closed yet.
