### ISSUE TITLE
The "crontab" area (still) missing from "Modules and Areas" page

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1791]
Feedback on page: /guides/v2.0/architecture/archi_perspectives/components/modules/mod_and_areas.html

I believe there was a question about this already, and I'm surprised that the resolution was [not to](https://github.com/magento/devdocs/issues/156#issuecomment-70166442) add the missing area to the list.

As of `2.3-develop` , the "crontab" area still seems to be used by the Magento Open Source:
https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/App/Cron.php#L78

Further on, `\Magento\Framework\App\Area` contains two additional area names as constants: `AREA_GLOBAL` and `AREA_DOC` (note: `AREA_DOC` doesn't seem to be used anywhere throughout the code, whereas the "base" area is being used despite not having a matching constant at `Area`)
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/App/Area.php#L18-L24

For something as essential as the areas (which in Magento are entities with scope that is larger than of a website, for example), one would expect a more thorough and up-to-date documentation.
Could you please re-investigate this topic and update the page correspondingly? Thanks in advance.

**Comment by jfrontain** [comment]
@korostii, I've added this to our to-do list and will work on it after Imagine later this month. Thanks, as always, for your insight.

**Comment by shrielenee** [comment]
This issue is fixed per PR #2361
