### ISSUE TITLE
Regarding Issue found on  Tax Zones and Rates Grid

### ISSUE THREAD

**Issue by ankit1388** [magento/devdocs#1792]
Feedback on page: /guides/v2.2/extension-dev-guide/bk-extension-dev-guide.html
Hello Team,
I have found an error  when i search region in Tax Zones and rates grid in magento2 admin.
I checked this same issue in default magento2 setup also.

**Comment by jeff-matthews** [comment]
Hi @ankit1388, this repo is for reporting issues about [Magento developer documentation](http://devdocs.magento.com/) only. 

It sounds like you may have found an issue with the Magento code. Please report issues with the code in the code repo: https://github.com/magento/magento2/issues.

**Comment by ankit1388** [comment]
ok Jeff ,
I will add this to magento2 code issues repo
Thanks
