### ISSUE TITLE
small typo in "Step 6: Create the UpgradeData script" section

### ISSUE THREAD

**Issue by Shreyas-Echidna** [magento/devdocs#1794]
Feedback on page: /videos/fundamentals/add-a-new-table-to-database/

Missing ending quotes in upgrade function, solution is below

$setup->getConnection()
                ->insertForce($table, ['message' => 'Happy Thanksgiving', 'season' => 'fall']);

**Comment by shrielenee** [comment]
Hi @Shreyas-Echidna - thanks for pointing this out. The page in question is: http://devdocs.magento.com/videos/fundamentals/add-a-new-table-to-database/. We'll get working on this fix and let you know when it's 👍.

**Comment by shrielenee** [comment]
Thanks @Shreyas-Echidna - this fix has been completed and is live! 

http://devdocs.magento.com/videos/fundamentals/add-a-new-table-to-database/
