### ISSUE TITLE
Clarity Regarding Varnish Version Support

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#1800]
Regarding: [Varnish Version](http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#magento-can-use-the-following-technologies)

### Description
- The version specified for Varnish 4 is **4.x** which signals to me that any current release of Varnish 4 is supported
- The version specified for Varnish 5 is **5.0** which is confusing to me. Is this meant to be **5.0.0** or **5.x**?

### Logic
- According to the official Varnish [release notes](https://varnish-cache.org/releases/index.html), 5.0.0/5.1.3 are already **Retired** ... whereas 5.2.1 is **Fresh**.

It would be instructive to have further clarity here so that upon reading the devdocs page linked above, I know what I can and cannot install and work with, without any guessing or trial and error.

Thank you

**Comment by shrielenee** [comment]
Hey @ryantfowler - Thanks for bringing this up. Your interpretation is correct: v2.2 supports Varnish 5.0 (5.0.0). Typically when communicating that a version supports all minor releases of a technology we utilize the "x", as in 4.x. In this case, for v2.2, we do indeed support 4.x and 5.0.0, but not 5.x.

I'm going to review how we communicate supported versions, as I can see how this may be confusing. Let us know if you have any more questions regarding this.
