### ISSUE TITLE
Page Broken?

### ISSUE THREAD

**Issue by jee1mr** [magento/devdocs#1801]
Is this page broken?
[Magento Blocks and Controllers](https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/controllers_intro.html)

The sidebar contents section is broken and the sentence is cut off midway 
**"Blocks and controllers are discussed extensively in the"**

**Comment by jeff-matthews** [comment]
@jee1mr, I don't think it's broken, but it may need to be added to the main, left navigation. How did you get to this page? Was it through Google search or did you follow a link from another devdocs topic? 

Sometimes, we remove topics from the main, left navigation while we determine what to do with the content. Google indexes these pages however, so they're still accessible.

**Comment by jeff-matthews** [comment]
Thanks for letting us know @jee1mr. This is a draft topic that shouldn't have been published. We'll remove it.

**Comment by jeff-matthews** [comment]
@keharper, please remove this topic.

**Comment by keharper** [comment]
I found 8 files each in the `v2.0` and `v2.1` directories that were drafts or remnants of obsolete topics. I deleted them.

Thanks @jee1mr for letting us know about the first one.
