### ISSUE TITLE
Checkout flow for guests

### ISSUE THREAD

**Issue by karthickannan** [magento/devdocs#1804]
Feedback on page: /guides/v2.2/get-started/order-tutorial/order-add-items.html

Please add another tutorial to cover the list of steps for a guest user to place an order.

**Comment by keharper** [comment]
@karthickannan 
The process for adding items to a guest cart and checking out is almost identical to that for a logged in user.

Step 4: Create a cart
`POST /V1/guest-carts`
The response will be a cartId like 87e0de18c623533692e44be275481889

Step 5. Add items to the cart
`POST /V1/guest-carts/87e0de18c623533692e44be275481889/items`
Make sure the `quote_id` in the body contains the same ID specified in the POST route

Step 6. Prepare for checkout

A. Estimate shipping costs
`POST /V1/guest-carts/87e0de18c623533692e44be275481889/estimate-shipping-methods`

B. Set shipping and billing information
`POST /V1/guest-carts/87e0de18c623533692e44be275481889/shipping-information`

Step 7. Create an order

`POST /V1/guest-carts/87e0de18c623533692e44be275481889/payment-information`

The payload of this call varies slightly from `/V1/carts/mine/payment-information`. You must specify the email address as a top-level attribute.

``` json
{
	"email": "jdoe@example.com",
	"paymentMethod": {
    	    	"method": "banktransfer"
	 },
	"billing_address": {
  	      	"region": "New York",
          	"region_id": 43,
          	"region_code": "NY",
    	    "country_id": "US",
    	    "street": ["123 Oak Ave"],
    	    "postcode": "10577",
    	    "city": "Purchase",
    	    "email": "jdoe@example.com",
    	    "telephone": "512-555-1111",
    	    "firstname": "Jane",
    	    "lastname": "Doe"
	 }
}
```
From there, Magento treats this as any other order.

I will eventually add this info to the existing tutorial. There's not enough unique information to warrant its own tutorial. 

Thanks for asking!

**Comment by karthickannan** [comment]
Thank you for the explanation. However, while adding the list of items to cart in step 5, we don't have information about the `option_id` and `option_value` for adding a configurable product.

In the tutorial, it is mentioned that these information can be fetched from an API call to the route `/V1/configurable-products/:sku/options/all` but this route is not allowed for anonymous access. To access this route, token is needed since it needs authorisation.

As a result, a guest user is not able to add configurable product to cart using REST API. Could you please let me know if I mis-understood anything or if the documentation needs an update?

**Comment by karthickannan** [comment]
I assume that you are mixing the website workflow and the REST workflow. If we are developing an Android application using the REST API, then there should be a way to get these option details.

**Comment by keharper** [comment]
@karthickannan 

Your options are discussed here: 

http://devdocs.magento.com/guides/v2.2/rest/anonymous-api-security.html

**Comment by karthickannan** [comment]
Thank you for sharing that documentation. As stated in that page, it'll give access to unwanted details like the promotional rules, disabled CMS pages, CMS blocks, disabled products etc.

But, getting the options of a product is not something that should be protected. It should be accessible by everyone without any authorisation.
