### ISSUE TITLE
Simple deployment method does not work in 2.2.3 and there's a typo in the code

### ISSUE THREAD

**Issue by nedge2k** [magento/devdocs#1812]
Feedback on page: /guides/v2.2/config-guide/config/disable-module-output.html

**Comment by camdixon** [comment]
Tried exact code provided in the config.php file.  It is working for me, but an additional step was needed `setup:upgrade`

**Comment by jeff-matthews** [comment]
@dshevtsov, please try to reproduce and update the docs as needed.

**Comment by dobooth** [comment]
@xmav In a comment above, they mentioned that they need to run`bin/magento setup:upgrade` to make these config changes stick. Is that correct? 
https://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html
