### ISSUE TITLE
assignment in return statement necessary?

### ISSUE THREAD

**Issue by kmddevdani** [magento/devdocs#1814]
Feedback on page: /guides/v2.2/ext-best-practices/extension-coding/example-module-adminpage.html

We wondered, if this code really needs the assignment in the return statement. 

```/**
         * Load the page defined in view/adminhtml/layout/exampleadminnewpage_helloworld_index.xml
         *
         * @return \Magento\Framework\View\Result\Page
         */
        public function execute()
        {
             return  $resultPage = $this->resultPageFactory->create();
        }
```

Wouldn't a simple `return $this->resultPageFactory->create();` have the same result? I personally was a bit confused, copied that example into our codebase, and was then criticized by the other devs. ;)

**Comment by matiasnombarasco** [comment]
Hey Dan, not sure why that assignation fo the `resultPageFactory` to the `$resultPage` variable has to be mandatory. I'll say that checking Magento code, even when the variable is not used, a dock block always goes along with the assignation 

```
/** @var \Magento\Framework\View\Result\Layout $resultPage */
```

which is handy to let devs know the layout can be manipulated and the Idea will pickup the methods, for example here:
![image](https://user-images.githubusercontent.com/6799792/38966680-9eef93ce-43d7-11e8-8923-7bf0dd72500e.png)

As part of the class: `Magento\ConfigurableProduct\Controller\Adminhtml\Product\Associated\Grid` 
that being said, I'll say the formatting should change in your code to suit the standard M2 code style being something more like:

```
 public function execute()
        {
             /** @var \Magento\Framework\View\Result\Layout $resultPage */
            $resultPage = $this->resultPageFactory->create();
             return $resultPage;
        }
```
That being said, I'll say lets keep the code consistent with M2 implementation, hope this helps.

**Comment by shrielenee** [comment]
Hello! The documented solution is technically correct, so we are archiving this ticket as we do not currently have the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
