### ISSUE TITLE
NO VIDEO with CHROME

### ISSUE THREAD

**Issue by mariocanta** [magento/devdocs#1817]
Feedback on page: /videos/fundamentals/add-new-product-attribute/

NO VIDEO only blanc page

**Comment by jeff-matthews** [comment]
@mariocanta, this page works for me. What browser are you using?

**Comment by mariocanta** [comment]
Chrome 

Inviato da Mario Cantalupo

**Comment by jeff-matthews** [comment]
I can't reproduce your issue, which makes me think it's a local browser setting that's preventing you from seeing this page. CAn you provide any more information?
