### ISSUE TITLE
Incorrect information on integration environments

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1842]
Feedback on page: /guides/v2.2/cloud/architecture/pro-architecture.html

"Integration—Provides a single environment branch, and you can create up to four additional, environment branches. This allows for a maximum of five active branches deployed to Platform-as-a-Service (PaaS) containers."

This statement is incorrect.  The Pro plan can have 8 active Integration branches with running full stack instances.  

I am not sure what an environment branch is.  Customers can have unlimited branches but only 8 can be associated with an active integration environment.

**Comment by jeff-matthews** [comment]
@dougkm, when @hguthrie and I were was researching this we were told that Pro customers have access to a total of **8** environments across PaaS and IaaS containers and only 5 of those are on the Integration environment:
- **Integration** (5)
- **Staging** (1)
- **Production** (1)
- **Global master** (1)

Are you saying this is incorrect?

**Comment by dougkm** [comment]
My understanding is there are 8 Integration environments (including the Master), Staging, and Production for a total of 10 environments.

**Comment by jeff-matthews** [comment]
We're meeting with @ngeron tomorrow to discuss. Stand by for more info.

**Comment by jeff-matthews** [comment]
I confirmed with internal sources that the docs accurately reflect the number of environments that the current Pro provisioning process produces. I've asked Product Management to notify me if/when that changes so we can update the docs accordingly.
