### ISSUE TITLE
Incorrect information on number of environments

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1843]
Feedback on page: /guides/v2.2/cloud/architecture/pro-architecture.html

"Your Magento Commerce (Cloud) Pro architecture supports a maximum of eight environments"

This statement is incorrect as there are 8 integration environments plus staging and production but default.  Customers can purchase additional environments as well.

**Comment by jeff-matthews** [comment]
I confirmed with internal sources that the docs accurately reflect the number of environments that the current Pro provisioning process produces. I've asked Product Management to notify me if/when that changes so we can update the docs accordingly.
