### ISSUE TITLE
Incorrect information on number of environments

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1844]
Feedback on page:http://devdocs.magento.com/guides/v2.2/cloud/architecture/pro-develop-deploy-workflow.html#develop

This section is incorrect. Customers can use 8 active integration environments plus staging and production.  

Customers can have unlimited branches but only 8 can be associated with active integration environments.

**Comment by jeff-matthews** [comment]
I confirmed with internal sources that the docs accurately reflect the number of environments that the current Pro provisioning process produces. I've asked Product Management to notify me if/when that changes so we can update the docs accordingly.
