### ISSUE TITLE
SELinux and IPTables page should also include generated directory

### ISSUE THREAD

**Issue by rip057** [magento/devdocs#1845]
and possibly the vendor directory, I havent crossed that bridge, but if the program is supposed to be able to read and write to vendor, then the suggestion about selinux should be updated to include the generated directory and the vendor directory.

http://devdocs.magento.com/guides/v2.2/install-gde/prereq/security.html
is the page i am speaking of.

without making the generated directory type httpd_sys_rw_content_t i was unable to go the home page after fresh installation in fedora 27 with selinux enabled.  no one should ever disable selinux.

**Comment by rip057** [comment]
Im kind of lost on how to do that.  Kind of ashamed to admit i have never
done a git pull.

Guess that means i need to clone the repository make some change to the
html and then submit correct?

I will look into that later today or tomorrow.  Please leave this open
until it happens because my adhd can get the better of me, and this whole
thing could disappear into the sea of work i have.

**Comment by shrielenee** [comment]
Hey there @rip057 - there are some basic instructions on how to contribute to devdocs on our [Code Contributions page](http://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html). Let us know if you have issues with that!

**Comment by shrielenee** [comment]
Hey @rip057 - it doesn't look like you've had a chance to work on this issue. Please see the above comment for information on how to create a PR for this work (and please do -- we'd love the contribution!)

I will be closing this issue now. Please reopen as a PR as needed.
