### ISSUE TITLE
Overly Generous Use of Symlinks in DevDocs

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#1848]
### Description
- I went to Edit [this](https://github.com/magento/devdocs/blob/develop/guides/v2.2/ui_comp_guide/concepts/ui_comp_uiclass_concept.md) page and found that it's merely a symlink to a page in the v2.1 guide. Ok. Makes sense to not want to duplicate similar content.... but wait, now the example documentation for the v2.2 guide is referencing v2.1 guide examples. Could this be confusing to some? I think so. Furthermore, this could also lead to a situation where something in v2.2 receives changes/back-ports/etc and v2.1 does not, but the documentation itself is referencing an incorrect version (v2.1 in this case), and now I am mislead by the "official" documentation due to a symlink.

- I can't Edit or update sections of the v2.2 guide that follow this pattern due to symlinks. So if I find something inconsistent/wrong/old/etc in the v2.2 guide, if that page is a symlink, I can't update it without updating the v2.1 guide, and that's just not correct.

- [This](https://github.com/magento/devdocs/commit/be13465626e1d0a0e3745793dd02a1b6b86fc4e0) appears to be where a handful of symlinks were committed, specifically the symlink related to the above mentioned page that I attempted to edit.

**Comment by jeff-matthews** [comment]
@ryantfowler, if you need to update a 2.2 file that's symlinked to 2.1, you must delete the symlink and create a new file for the 2.2 version; assuming the change doesn't also apply to 2.1.

**Comment by ryantfowler** [comment]
@jeff-matthews thanks for the direction here. I'll close this Issue.
