### ISSUE TITLE
Gaps around Xdebug documenation

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#1855]
Feedback on page: /guides/v2.2/cloud/howtos/debug.html

Xdebug is not really an issue for local development.  It is provided to facilitate debugging in the Cloud environments where the code is deployed into a read-only file system image.

This documentation appears to apply to the integration environments but I cannot find where the process for working with Xdebug in the staging and integration environments is described.

**Comment by hguthrie** [comment]
There is a section further down the page: http://127.0.0.1:4000/guides/v2.2/cloud/howtos/debug.html#pro-debug

Is this what you are looking for?

**Comment by dougkm** [comment]
Thanks.  I had missed that.

Perhaps this section should move from the local dev setup to Trouble shooting as "How to debug application issues"
