### ISSUE TITLE
Extension Dev Guide Module File Structure Missing Directory

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#1858]
### Description
- [This](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/module-file-structure.html#module-file-structure) link's "Module File Structure" image doesn't include the `Console` directory. It might be helpful to include that directory as well, as creating CLI commands can be a common task.

**Comment by jeff-matthews** [comment]
Thanks for the feedback @ryantfowler! We're actually in the process of updating these docs as part of an internal project, which may address the issue you've reported.

@bdenham, internal issue [MAGEDOC-2850](https://jira.corp.magento.com/browse/MAGEDOC-2850) likely covers this.

**Comment by ryantfowler** [comment]
@jeff-matthews you're welcome. Please advise on appropriate action for this issue (if I should close this or not). Thank you

**Comment by jeff-matthews** [comment]
@ryantfowler, please leave this issue open for now. 

@bdenham, please close this issue after you publish updated docs for the extension directory structure. Don't forget to add a link to that PR here as well.

**Comment by bdenham** [comment]
Hey @ryantfowler, I am currently working on this issue and will update you when it is complete. Thanks.

**Comment by bdenham** [comment]
Hey @ryantfowler, PR https://github.com/magento/devdocs/pull/2086 addresses this issue. Thanks for reporting on it and let me know if you want to add additional material to the PR.

**Comment by ryantfowler** [comment]
@bdenham sounds good, thanks.
