### ISSUE TITLE
Main downloads page link 2.1.13 Release Notes is broken

### ISSUE THREAD

**Issue by bobemoe** [magento/devdocs#1859]
https://magento.com/tech-resources/download
links to 
http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.13CE.html
but it 404's

**Comment by jeff-matthews** [comment]
It looks like this is fixed now. @jfrontain, can we close this issue?

**Comment by jfrontain** [comment]
Closing now. Thanks, @bobemoe.
