### ISSUE TITLE
ext-bcmath is required since Magento 2.2.4

### ISSUE THREAD

**Issue by thomas-blackbird** [magento/devdocs#1866]
Feedback on page: /guides/v2.2/release-notes/ReleaseNotes2.2.4CE.html

You missed to warn that the php extension ext-bcmath is now required since Magento 2.2.4

**Comment by keharper** [comment]
@jfrontain please update the following release note item:

Composer now checks the availability of the bcmath PHP module. Fix submitted by Mobecls in pull request 12768.

It should say something like 

The `ext-bcmath` PHP extension is now required in Open Source. Previously, it was required for Commerce only. Fix submitted by Mobecls in pull request 12768.

**Comment by jfrontain** [comment]
Thanks for calling our attention to this ambiguous note, @thomas-blackbird , and thanks for your help with proper wording, @keharper. This change is now public. Closing issue.
