### ISSUE TITLE
Code example for custom entity management would be great.

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1868]
Feedback on page: /guides/v2.1/extension-dev-guide/persistent-entities.html

At the moment there are many terms and approaches possible in Magento 2 to manage entities. At the same time magento core modules manage entities in different ways. In addition to this googling gives also different implementation for entity managing.  Therefor its not clean to understand what is the really right way.

Given as an example Customer and Catalog modules is bad, because entity management in this modules implemented quite different, and its even more confusing.

Therefore would be great to have a complete example in documentation link to it.
To have uml diagram would be great too.

Also would be great to have some notice about EntityManager introduced in v2.1.

**Comment by piotrekkaminski** [comment]
@likemusic thanks for the feedback. Note: there is some more information about usage in the source code here: https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/EntityManager/EntityManager.php#L15-L24

**Comment by likemusic** [comment]
@piotrekkaminski, thanx. I saw it. I think that this class should be mentioned in docs in some sentences, because this class currently used for many entities and the absence of even mentioning it in the documentation is confusing.

From stackoverflow:
> now product,category,block,page,rule entities using entity manager

**Comment by pefferen** [comment]
In addition this page is not part of the menu, it would fit under the 'Component development' section.

**Comment by dshevtsov** [comment]
We no longer support 2.1 documentation. This page does not exist in 2.2 and 2.3 versions.
@jcalcaben please add a link to the page in case it was moved.

NOTE: This issue/pull request applies to 2.1 only. We are no longer accepting pull requests for 2.1 DevDoc updates, because this version reached end of life (EOL) on June 2019. Magento no longer applies security patches, quality fixes, or documentation updates to 2.1.
