### ISSUE TITLE
Register a theme 

### ISSUE THREAD

**Issue by hweb87** [magento/devdocs#1873]
Feedback on page: /guides/v2.3/frontend-dev-guide/themes/theme-install.html

To make sure the theme is registered, in the Magento Admin navigate to **Content > Design > Configuration**. If a theme is registered, it is displayed in the list of available themes.

Need to change : **Content > Design > Themes** to **Content > Design > Configuration**

**Comment by shrielenee** [comment]
Thanks for suggesting this change @hweb87!
