### ISSUE TITLE
Wrong parameters in $this->_forward() on extensions-dev-guide/routing.html

### ISSUE THREAD

**Issue by SvanteAvenla** [magento/devdocs#1876]
The page [https://devdocs.magento.com/guides/v2.2/extension-dev-guide/routing.html](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/routing.html) (corresponding github page [here](https://github.com/magento/devdocs/blob/develop/guides/v2.1/extension-dev-guide/routing.md)) is wrong about the $this->_forward() function.

According to the page the function have one parameter containing the route, when the function really looks like this: _forward($action, $controller = null, $module = null, array $params = null). Source code [here](https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/App/Action/Action.php).

The page also seems to have other inaccurate statements, but I'm not familiar enough with Magento to know how they are wrong.

**Comment by jcalcaben** [comment]
This issue has been addressed in #2238. Thanks for reporting it @SvanteAvenla !
