### ISSUE TITLE
proposal: remove jekyll and use the site builder of GitHub or use a Git hook

### ISSUE THREAD

**Issue by DanielRuf** [magento/devdocs#1884]
Currently the repository is about 506MB big and contains many files which are probably not needed.

We could probably improve its size and its deployment.

![bildschirmfoto 2018-05-07 um 15 55 06](https://user-images.githubusercontent.com/827205/39705550-0f0feac4-520f-11e8-88a2-910cc9993a7a.png)

**Comment by jeff-matthews** [comment]
@DanielRuf, you're probably right about there being several files that are not needed. Image are usually the first file types that accumulate and can be removed. We just need to scan the site to determine which files are in use and which are not. Removing unused images would probably reduce the size of the repo significantly.

We're currently using custom internal scripting to deploy the site. However, we're in the process of optimizing our CICD flow using an internal Jenkins instance. To maintain consistency with other projects, we're not likely to use any external tooling to build and deploy the site.
