### ISSUE TITLE
config provider registration in specific area scope

### ISSUE THREAD

**Issue by thomas-blackbird** [magento/devdocs#1888]
Feedback on page: /guides/v2.2/howdoi/checkout/checkout_payment.html
Section: #access-the-system-config-data

The following is explained:

> A sample DI configuration file of a custom module <your_module_dir>/etc/di.xml:

However it seems that you must register your configProvider in the frontend area, not in global, otherwise it wont works.
Can you confirm that?

**Comment by keharper** [comment]
@thomas-blackbird you are correct. I've confirmed that the path should be `<your_module_dir>/etc/frontend/di.xml`. The corrected documentation should be published within an hour. Thank!
