### ISSUE TITLE
Code sample missing where comment can be specified

### ISSUE THREAD

**Issue by camerondw** [magento/devdocs#1896]
Feedback on page: /guides/v2.1/get-started/order-tutorial/order-create-shipment.html

This page is extremely helpful, however the code sample is missing the comment. Swagger on my server has this:

`{
  "items": [
    {
      "extension_attributes": {},
      "order_item_id": 0,
      "qty": 0
    }
  ],
  "notify": true,
  "appendComment": true,
  "comment": {
    "extension_attributes": {},
    "comment": "string",
    "is_visible_on_front": 0
  },
  "tracks": [
    {
      "extension_attributes": {},
      "track_number": "string",
      "title": "string",
      "carrier_code": "string"
    }
  ],
  "packages": [
    {
      "extension_attributes": {}
    }
  ],
  "arguments": {
    "extension_attributes": {}
  }
}`

In it is a section I can specify the comment. I'm running 2.1.10 Community.

**Comment by camerondw** [comment]
Thanks for explaining that @keharper . My confusion was from seeing appendComment set to true, but no section relating to that comment was present. May I suggest the example has appendComment set to false? Or if it stays set to true, then include the comment section?

**Comment by keharper** [comment]
I wound up deleting the `notify` and `appendComment` parameters from the request code sample since they were neither required nor relevant to the example. Thanks for helping to clarify the docs!

**Comment by camerondw** [comment]
Cheers @keharper :)
