### ISSUE TITLE
Commit #cb93abc introduce mass of broken links

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1904]
## This issue is a:
[ ] Bug on the website
[ ] New topic request
[ ] Topic clarification request
[ ] New DevDocs feature request
[x] Other
 

## Description:
```
root@magentodevdocs:~/devdocs# bundle exec jekyll serve --incremental
Configuration file: /root/devdocs/_config.yml
            Source: /root/devdocs
       Destination: /root/devdocs/_site
 Incremental build: enabled
      Generating...
jekyll 3.7.3 | Error:  No such file or directory @ rb_sysopen - /root/devdocs/guides/v2.2/architecture/arch-basics.md
``` 

### Steps to reproduce
 
1. Run `bundle exec jekyll serve --incremental` on current develop branch (last commit #9af288e)

## Expected result:
Success build and no broken links at generated site.

Checkout to previous commit (#38b62fa663b546c3a070873b3f3a9924c0e49a2b) fix this issue.

**Comment by likemusic** [comment]
@keharper I tested it on latest develop branch.

```
root@magentodevdocs:~/devdocs# git log -1
commit 9af288e4f3999312ec80b37a48636cb3bca468da
Merge: 38b62fa cb93abc
Author: Kevin Harper <keharper@users.noreply.github.com>
Date:   Fri May 11 16:49:40 2018 -0500

    Merge pull request #1997 from magento/kh_pr1801

    delete unused files
```

As I can see at the moment `guides/v2.2/architecture/arch-basics.md` is symlink to `guides/v2.1/architecture/arch-basics.md` that not exists.
- https://github.com/magento/devdocs/blob/develop/guides/v2.2/architecture/arch-basics.md
- https://github.com/magento/devdocs/blob/develop/guides/v2.1/architecture/arch-basics.md

**Comment by keharper** [comment]
I didn't realize the symlinks needed to be manually deleted. I've done so. Please let me know whether I got all of them.

**Comment by likemusic** [comment]
Seems that all is ok after latest commit. Devdocs created without any errors.

But I checked broken links. There are still a lot of broken links on the site.  Seems that its not related to this issue, therefore I close it and reopen #1531.
