### ISSUE TITLE
Magento 1 API SOAP V2 created configurable product with associated simples

### ISSUE THREAD

**Issue by albertopallotto** [magento/devdocs#1908]
## This issue is a:
[ ] Bug on the website
[ ] New topic request
[ ] Topic clarification request
[ ] New DevDocs feature request
[x] Other
 

## Description:
 I need help with the creation of a configurable products with Magento SOAP API V2.

My problem is:

I managed to create the configurable product, but there aren't any simple associated and when I open the configurable I see a windows that tell me "Select Configurable Attributes".

I thought there is a mistake in the configurable attributes.
  
## Additional information:
This is my configurable probuct data array:

$data = array(
"categories" => array("0" => 19),
"websites" => array("0" => 3),
"name" => "Sport",
"description" => "a classic-looking wimbledon-style tennis shoe re-imagined in aged blue leather and featuring a chic band-covering around the box sole",
"short_description" =>"",
"weight" => 0.9600,
"status" => 1,
"url_key" => "sport-pr53801aq000",
"url_path" => "sport-pr53801aq000.html",
"visibility" => 4,
"price" => 395.0000,
"tax_class_id" => 2,
"meta_title" => "Sport - low top - calfskin - PR53801AQ000",
"meta_keyword" =>"",
"meta_description" => "A classic-looking wimbledon-style tennis shoe re-imagined in aged blue leather and featuring a chic band-covering around the box sole",
"stock_data" => array(
"manage_stock" => 1,
"is_in_stock" => 1,
"qty" => 0.0000,
"is_qty_decimal" => "",
"use_config_manage_stock" => 1,
),
"additional_attributes" => array(
"single_data" => array(),
"multi_data" => array(),
),
"has_options" => 1,
"required_options" => 1,
"configurable_attributes" => array("0" => 167), // this correspond to the id of configurable attribute
"associated_ids" => array("82229" => 5661),
)

**Comment by jeff-matthews** [comment]
@albertopallotto, this repo is for documentation-specific issues only. Try asking your question on [Magento Stack Exchange](https://magento.stackexchange.com/) or in the [Magento forums](https://community.magento.com/).
