### ISSUE TITLE
Add example for the layout_markup_replace_elements contents

### ISSUE THREAD

**Issue by drew7721** [magento/devdocs#1910]
## This issue is a:
[ ] Bug on the website
[ ] New topic request
[x ] Topic clarification request
[ ] New DevDocs feature request
[ ] Other
 

## Description:
The **Replace elements** section lacks information. An example would be appreciated.

 

## Expected result:
 Add an example of replacing an element. How to remove it and add a new one to replace the old one.
see : https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/xml-manage.html#layout_markup_replace_elements

## Possible solutions:
 Inform of possible options to change the class of an existing block. Reference the parent block or container and then remove the old block and add a new one with the same name...

## Additional information:
I ask this because before 2.2 we could change the class from the layout xml for a given block with the `referenceBlock` tag, but now it does not work anymore. Hence, we need to use di.xml for preference definitions, but this complicates readability because we now need to check the `layout` and the `di` file to know what class the block has. And the size of the `di.xml` file just increases for no apparent good reason.

So I would like to know, how to remove and add a new block **with the same name** as the one removed so that other blocks referencing the block for positioning still display properly.

**Comment by michizhou** [comment]
I would like to take this issue. I would appreciate it if you could provide more info and docs that may help guide me. Thanks!

**Comment by jeff-matthews** [comment]
Thanks for volunteering @michizhou! If you need help understanding how to contribute to devdocs, check out our [CONTRIBUTING.md](https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md) file. If you still have questions, don't hesitate to ask.

**Comment by shrielenee** [comment]
Hey @michizhou --- It looks like the PR that fixes this is still open: https://github.com/magento/devdocs/pull/3054.

Can you take a look at feedback and resubmit? Thanks!

**Comment by michizhou** [comment]
@shrielenee My apologies for the lackluster response on my end. I have been busy with other things for the past month, but I'll be sure to revise and resubmit by the end of this week.
