### ISSUE TITLE
At some places still used Magento Community and Magento Enterprise naming

### ISSUE THREAD

**Issue by vijay-wagento** [magento/devdocs#1927]
## This issue is a:
[ ] Bug on the website
 

## Description:
 In few pages, still devdocs showing Magento Community and Magento Enterprise naming.

### Steps to reproduce
 
At below three URLs, it shows Magento Community and Magento Enterprise naming
1. https://devdocs.magento.com/guides/v2.2/cloud/access-acct/trouble.html
2. https://devdocs.magento.com/guides/v2.2/architecture/tech-stack.html
3. https://devdocs.magento.com/guides/v2.2/comp-mgr/marketplace/marketplace.html
 

## Expected result:
It should display Magento Open Source and Magento Commerce naming
 

## Possible solutions:
Instead of hard-coded, use variables {{site.data.var.ee}} and {{site.data.var.ce}} so

**Comment by jeff-matthews** [comment]
Thanks @vijay-wagento! Although we're using the old naming convention in addition to the new naming convention, I think it's time to remove the old naming convention. I don't think it's useful anymore.
 
@dshevtsov, please remove references to Enterprise and Community editions.

**Comment by vijay-wagento** [comment]
@jeff-matthews @dshevtsov Let me know if you want me to do it. I can see that Magento Commerce and Magento Open Source text rendering through variable but Enterprise and Community render hardcoded. So it is better we should get rid of old naming convention.

**Comment by jeff-matthews** [comment]
@vijay-wagento, yes please! We would appreciate it if you created a PR to fix this.

**Comment by vijay-wagento** [comment]
@jeff-matthews sure, I can do. Do you completely get rid of name or you still want to go with CE and EE?

**Comment by jeff-matthews** [comment]
Let's completely remove references to the old names and use variables for the new names. The variables for new names happen to use abbreviations from the old naming convention, but that's ok.

For example:

- Magento Open Source = `{{site.data.var.ce}}
- Magento Commerce = `{{site.data.var.ee}}

**Comment by meker12** [comment]
This issue was fixed by [PR 1928](https://github.com/magento/devdocs/pull/1928).
