### ISSUE TITLE
Provide a list of Core Bundled Extensions with details about how to contact them

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#1961]
## This issue is a:
[ ] Bug on the website
[x] New topic request
[ ] Topic clarification request
[ ] New DevDocs feature request
[ ] Other
 

Hi guys

It would be tremendously useful to have a listing in the documentation of all the Core Bundled Extensions (CBE's) included in Magento, I'm talking about those new modules which came with Magento 2.2.2 and 2.2.4, for example (I'm using the names used in their composer.json files):
- amzn/amazon-pay-and-login-magento-2-module
- dotmailer/dotmailer-magento2-extension
- shopialfb/facebook-module
- klarna/module-core
- vertex/module-tax
- ... and various others

The reason is, that we need to have some kind of feedback loop with those vendors or at least the developers of those modules. Since bugs pop up in those modules all the time and we need to know how to report them or even contribute bugfixes back to them.

So a listing with detailed information about those modules would be very useful.

Wat needs to be included in this listing:
- name of the module
- from which version of Magento this module got included by default
- a link to their public code repository (if available)
- some kind of contact information if there is no public code repository
- ... 

Currently, Magento takes no responsability in fixing bugs in those modules, so currently if an issue is being reported on Magento's Github repo for such a module, they can only pass that issue on to the third party because Magento doesn't own the code and can't fix those reported issues themselves.
That's why it would be very useful if the community knows how to communicate with those third parties, for reporting bugs, requesting features or sending in pull requests.

Thanks!
  

## Expected result:
To have a listing of CBE's with contact information on the devdocs.

**Comment by jeff-matthews** [comment]
Hi @hostep, I'll talk to the product manager who's responsible for coordinating core bundled extensions and get back to you.

**Comment by jeff-matthews** [comment]
@hostep, @jfrontain and I discussed this with Product Management and we all agreed that we need to start publishing more organized release info about bundled extensions. @jfrontain will be adding a  page for bundled extensions in the release info section of devdocs, which will include links to support and/or code repos (when available).

**Comment by shrielenee** [comment]
Hey @jfrontain - Was there a bundled extensions page added? If there is an outstanding Jira ticket we can add the Tracking tag to this. Let us know so we may close or update this issue! 🙇‍♀️

**Comment by jfrontain** [comment]
@hostep, we're in the process of adding it right now. Will be up within the next day. Thanks for your patience!

**Comment by hostep** [comment]
Thanks Jeanne (and all others involved)!
