### ISSUE TITLE
Feedback on page: /guides/v2.2/payments-integrations/payment-gateway/gateway-command.html

### ISSUE THREAD

**Issue by greatdevaks** [magento/devdocs#1973]
What is the nature of this issue?
## This issue is a:
Topic clarification request
 
What is the issue/current behavior? 
## Description:
The Magento Framework's documentation is so poor that I am unable to understand how it works. You should provide step by step guides and sample examples.
 
When this issue is resolved, what is the expected result/behavior?
## Expected result:
Expected result is that developers will be able to build the product's using Magento in a better way.
 
What would a solution for this issue look like?
## Possible solutions:
A step-by-step guide and documentation.

**Comment by jeff-matthews** [comment]
@greatdevaks, are you expressing an opinion about devdocs in general or about the [Gateway Command](https://devdocs.magento.com/guides/v2.2/payments-integrations/payment-gateway/gateway-command.html) topic specifically (as implied by the title of your issue)?

We _do_ provide step-by-step instructions and examples for several popular development tasks, including, but not limited to:

- [Order Processing with REST API](https://devdocs.magento.com/guides/v2.2/get-started/order-tutorial/order-intro.html)
- [Customizing checkout](https://devdocs.magento.com/guides/v2.2/howdoi/checkout/checkout_overview.html)
- [Adding a custom breakpoint for frontend development](https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.html)

Can you be more specific about what you're looking for? Maybe we can help point you in the right direction or create a task to address the gap.

**Comment by greatdevaks** [comment]
Hi @jeff-matthews, thanks for the prompt reply. My opinion stands for the whole devdocs.
Currently, I am trying to do the following stuff and have no clue on how to proceed:
- I have created a payment module. I want to add a feature in which when the user clicks on Place Order, the data from the form fields is collected and sent with external REST API request. Then, I need to fetch the response data and on basis of that redirect the user to Success/Fail page.

I am very confused about how actually everything in the framework is working and couldn't find and step-by-step guides or good docs online. I will be very grateful to you if you could help me out in this issue.

Thanks.

**Comment by jeff-matthews** [comment]
Did you see this page?

https://devdocs.magento.com/guides/v2.2/payments-integrations/base-integration/get-payment-info.html

**Comment by jeff-matthews** [comment]
Sorry you can't find what you're looking for on devdocs @greatdevaks. I recommend searching the [Magento Forum](https://community.magento.com/) and [Magento Stack Exchange](https://magento.stackexchange.com/) for an answer. Feel free to come back and create a PR to share what you've learned with the community.
