### ISSUE TITLE
UI Component DynamicRows documentation

### ISSUE THREAD

**Issue by Bossman1337** [magento/devdocs#1982]
## This issue is a:
[ ] Bug on the website
[ ] New topic request
[X] Topic clarification request
[X] New DevDocs feature request
[ ] Other
 

## Description:
https://github.com/magento/devdocs/commit/814e6c9b5babbe6866d4e5b1283824403bf69425
This documentation needs clarification. There are unknowns in the documentation. Looks like the original topic was closed over a year ago with no further action.
 

### Steps to reproduce
 
Create a working example of a table with dragable rows that update the position in the database.
 

## Expected result:
 Better documentation with working full XML examples using columns or fields.

## Additional information:
I have created a table that almost shows but just has the spinner spinning. I can see the JSON data being pulled from the database through Chrome dev tools but it's not applying to the dynamicRows component. I assume it has something to do with mapping the data but the docs don't clarify this.

**Comment by bdenham** [comment]
Hey @Bossman1337, thanks for submitting this issue. I will be updating the UI components guide over the next several months, so it's nice to get feedback on specific areas in the documentation that lack clear content. Can you provide a sample project that contains the table you are describing? I think getting more insight into what you are doing will help me create the documentation needed for this and many other topics in the UI Components guide.

**Comment by dobooth** [comment]
Hey @serhiyzhovnir  There is a good chance you have handled this one already. Any more updates need on this issue?

**Comment by dobooth** [comment]
Serhiy has done extensive rework on all/most of the UI Components. He provides a working sample for each. Please file a new issue if there is a gap in documentation.
