### ISSUE TITLE
Feedback on page: /guides/v2.2/magento-functional-testing-framework/release-2/page.html

### ISSUE THREAD

**Issue by Jakhotiya** [magento/devdocs#1987]
## This issue is a:
[x ] Bug on the website
[ ] New topic request
[ ] Topic clarification request
[ ] New DevDocs feature request
[ ] Other
 

## Description:
Doc says : 
"*Page.xml is stored in the Section directory of a module." under Priciples section but Pages are stored in Page directory not Section.
 

 

## Expected result:
The doc should say "*Page.xml is stored in the Page directory of a module."

**Comment by dshevtsov** [comment]
Fixed in 1964e42a1e2aaf64c023b2ab7e0b990d952889ed
