### ISSUE TITLE
Feedback on page: /guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html

### ISSUE THREAD

**Issue by J-Fricke** [magento/devdocs#1999]
## This issue is a:
- [x ] New DevDocs feature request

**Comment by jeff-matthews** [comment]
Hi @J-Fricke and thanks for contributing to devdocs! I think what you're proposing is a Magento app feature request; not a devdocs feature request. To change the Magento CLI commands, open an issue in the [magento/magento2](https://github.com/magento/magento2/issues) repo.
