### ISSUE TITLE
Feedback on page: /guides/v2.1/javascript-dev-guide/widgets/widget_modal.html

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#2014]
## This issue is a:
- [x] Topic clarification request
- [x] New DevDocs feature request
 

## Description:
The [documentation page](https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_modal.html) corresponding to the `modal` widget seems to omit the fact that the [`clickableOverlay`](https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_modal.html#modal_clickableOverlay) parameter [isn't working as expected](https://github.com/magento/magento2/issues/7399) in any of the released versions and [will only be fixed in the future 2.2.5 version](https://github.com/magento/magento2/issues/7399#issuecomment-389556338).
 

### Steps to reproduce
 
1. Observe https://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_modal.html
2. Observe https://github.com/magento/magento2/issues/7399
3. Note that the devdocs page has no reference to that issue nor any mention of anything of the sort.
 

## Expected result:
I would expect the page to contain a mention of that issue, or a reference to it, or a comment section where a community developer could post such a notice for other fellow developers to see.
 

## Possible solutions:
a) add a short mention of that issue to the corresponding documentation issue
b) add a reference to the GitHub issue https://github.com/magento/magento2/issues/7399 
c) create a comment section where a community developer could post such a notice for other fellow developers to see.

**Comment by bdenham** [comment]
Hey @korostii, good catch on this. Would you be willing to submit a pull request with the updates you're recommending? 

If so, here are some basic instructions on how to contribute to devdocs on our [Code Contributions page](http://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html). 

If not, let me know and I'll submit a PR for you.

**Comment by korostii** [comment]
Hi @bdenham, thanks for the timely response.r

Well, I am pretty sure there could be some Magento's internal policies or legalese restrictions for acknowledging issues that I don't know of. For example, there was a lengthy discussion on that topic in #1268 (long story short, was requesting a similar edit on a different page and got turned down).

That's one of the reasons why I am a little hesitant to submit any significant changes or even investing time and effort into them, at all.
Don't get me wrong, I would be very glad if you could do such an edit, feel free to the edit as you like. By all means, go for it!

Just please make sure it's okay to do so, I wouldn't want to get you in trouble =)
Keep up the good work & have a nice day!

**Comment by bdenham** [comment]
@korostii, thanks for the additional info! Interesting. I'll research this issue more to get a better understanding. Thanks, again.

**Comment by dshevtsov** [comment]
@korostii, according to magento/magento2#7399 the issue has been fixed. If you still observe any documentation issues in 2.2 or 2.3, please let us know.

Note: This issue/pull request applies to 2.1 only. We are no longer accepting pull requests for 2.1 DevDoc updates, because this version reached end of life (EOL) on June 2019. Magento no longer applies security patches, quality fixes, or documentation updates to 2.1.
