### ISSUE TITLE
Magento 2 Request Processing inaccurately explained 

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#2065]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [x] Other
 

## Description:
Magento 2 Request Processing inaccurately explained 
 

### Steps to reproduce
Observe Section **Note about Magento request processing**
https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_and_areas.html 

### Actual result
After the area name, the URI segment specifies the full front name. When an HTTP request arrives, the handle is extracted from the URL. **Magento uses the handle to identify which controller (a PHP class) and action (a PHP method in the class) to execute. A common action to display a HTML page is index, which returns an HTML page.**

### Expected result

As of Magento 2 the highlited section is wrong, the handle interpretation is as folows 
[frontname]/[controller folder]/[controller class]  e.g catalog/product/view.
Only **one** method of a given controller is executed, and that is the **execute()** method

**Comment by jfrontain** [comment]
@victortodoran, thanks so much for your comment. I'm updating that section of the discussion with the following text, approved by one of our architects. Thanks again for your help and please send more suggestions our way. 



Note about Magento request processing
Magento processes a URL request by first stripping off the base URL. The first path segment of the remaining URL identifies the request area.

After the area name, the URI segment specifies the frontname. When an HTTP request arrives, Magento extracts the handle from the URL and interprets it as follows: [frontName]/[controller folder]/[controller class] where frontName is a value defined in the module. For example, in catalog/product/view, catalog is the name of the module used, product is the controller folder, and view is the controller class. For deeper directory structures, the controller folders are separated with _ (for example, catalog/product_compare/add for Magento/Catalog/Controller/Product/Compare/Add.php).

Note that only the execute() method of any given controller is executed.
