### ISSUE TITLE
Feedback on page: /guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.html

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#2078]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other
 

## Description:
There is not clear to understand what is the difference between `imports` and `listens` properties.

Seems that there is the same functionality but with flipped key/value:

|  | key  | value |
| -------------| ------------- | ------------- |
| imports | name of the internal property or method that receives the value.  | name of the observable property or method which is tracked for changes. Can use string templates. |
| listens | name of the property or method that is tracked for changes. Can use string templates. | name of the internal method or property which listens to the changes.  |

Page: https://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.html

**Comment by lorikrell** [comment]
This issue may be linked to https://github.com/magento/devdocs/issues/1451

**Comment by dobooth** [comment]
I think it is clear on a close reading.
Imports: X has a property 'visible' that it imports from Y. When Y.visible('show') changes to 'hidden', X will import that new value and will be hidden.
Listens: When the 'visible' value for X is changed at all, it kicks off a method that does something.
