### ISSUE TITLE
Feedback on page: /guides/v2.2/frontend-dev-guide/themes/js-bundling.html

### ISSUE THREAD

**Issue by stevekarwacki** [magento/devdocs#2084]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other
 

## Description:
Documentation is incorrect. Documentation states the following:
"To optimize bundling, set the following settings to Yes:
Javascript Settings -> Merge JavaScript Files"
This is untrue and will not optimize bundling. In fact, merging javascript files seems to override bundling. When js files are merged, no bundles are generated.
 

### Steps to reproduce
 
1. Turn on JS Bundling
2. Turn on JS Merging, JS Minification, and Sign Static Files per documentation
3. Put site into production
4. Deploy static content
5. Observe merged JS file and no JS bundles
 

## Expected result:
 Remove the line "Javascript Settings -> Merge JavaScript Files" from the documentation

## Possible solutions:
"To optimize bundling, set the following settings to Yes:

Javascript Settings -> Minify Javascript Files
Static Files Settings -> Sign Static Files"

**Comment by bhargavmehta** [comment]
I am on it @shrielenee
