### ISSUE TITLE
Document app:config:dump config-types argument

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#2103]
## This issue is a:
- [ x ] Other (documentation update)
 

In [EngComm PR-12410](https://github.com/magento/magento2/pull/12410), contributor @jalogut added the ability to limit the scope of the `magento app:config:dump` command. 
 
The syntax is now

`app:config:dump [<config-types>]`
where <config-types> is a space-separated list of config types [scopes, system, themes, i18n]. If no values are specified, the command dumps all information

The contribution was ported to 2.3

## Expected result:
The new argument is documented.

**Comment by lorikrell** [comment]
Revisiting and pulling together all issues for Pipeline deployment for devdoc updates.

**Comment by lorikrell** [comment]
Content updated and merged!
