### ISSUE TITLE
Document dev:profiler:enable/disable commands

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#2104]
## This issue is a:
- [ x ] Other (documentation update)
 

## Description:
 
In [EngComm PR-11407](https://github.com/magento/magento2/pull/11407), contributor @peterjaap  added the `dev:profiler:enable <profiler_type>` and `dev:profiler:disable` commands. The profiler types are `html` (default) and `csvfile`. 

As part of the documentation effort, investigate whether the command supersedes the info presented here:

https://devdocs.magento.com/guides/v2.2/config-guide/bootstrap/mage-profiler.html

The contribution was ported to 2.3

## Expected result:
 These commands are documented

**Comment by lorikrell** [comment]
Revisiting and pulling together all issues for Pipeline deployment for devdoc updates.

**Comment by lorikrell** [comment]
Content added and merged to devdocs for 2.2 and 2.3.
