### ISSUE TITLE
variable-pool link leads to 404 page

### ISSUE THREAD

**Issue by jonashrem** [magento/devdocs#2107]
## This issue is a:
- [x] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other
 

Link to https://devdocs.magento.com/guides/v2.2extension-dev-guide/variable-pool/ leads to 404 page
 

### Steps to reproduce
1. Open module development page https://devdocs.magento.com/guides/v2.2/extension-dev-guide/module-development.html
2. click on "Variable Pool"
 

## Expected result:
Seeing a page about the "Variable Pool"

 

## Possible solutions:
In the development branch of this docs there is a page about "Variable Pool" in 2.3 ( https://github.com/magento/devdocs/blob/develop/guides/v2.3/extension-dev-guide/variable-pool/index.md )
 When this is a 2.3 feature the link in 2.2 and earlier should be removed. If this feature is present in 2.2 the page should be ported to 2.2 as well

**Comment by jcalcaben** [comment]
Thanks for reporting this @jonashrem !

This topic is a 2.3-only topic. I have fixed the table of contents so it only appears in 2.3.
