### ISSUE TITLE
add placeholders for new Topics

### ISSUE THREAD

**Issue by Flyingmana** [magento/devdocs#211]
While the current documentation looks very clean and well structured, it is still missing a lot of parts.
That is not a problem, but it makes contribution of complete new parts harder, as there are not enough patterns to follow currently.

Examples:  
* Where would I add a tutorial about replacing the default Search engine.
* What would be a good place to describe the *Interval* pattern, how to extend it and what problems it should resolve

**Comment by xcomSteveJohnson** [comment]
What do you think about us creating a new directory called 'ideas' and have a topic there that enables you to add whatever content you'd like? 

This would be in addition to us creating shell/placeholder topics for things we anticipate adding in the future.

If you create the topics we can place them in a temporary or proper home until we build similar topics around them.

**Comment by Flyingmana** [comment]
sounds like something I can work with :)

**Comment by TexanHogman** [comment]
as far as the tutorial for replacing the search engine, I believe this is a great candidate for submissions into our sample set.  https://github.com/magento/magento2-samples.  As you can see the set is basically empty now; we are working internally to build out a set of samples to demonstrate best practices using M2..  I hope over the next few weeks some of these are delivered and you can follow our lead and submit a PR

**Comment by TexanHogman** [comment]
BTW these samples will also be published to packages.magento.com

**Comment by xcomSteveJohnson** [comment]
@Flyingmana Update: I'll do an internal mock-up and will update you in a couple of days.

**Comment by xcomSteveJohnson** [comment]
This is done.
