### ISSUE TITLE
Add cache type

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#2190]
Type of Doc:
- [ ] New topic
- [x] Topic Update, Devdoc link:
- [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/11295

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/11296

Magento 2 version:
- [ ] 2.1.X
- [ ] 2.2.X
- [x] 2.3.X
- [ ] back port
- [ ] forward port

## Content:

Add the following row beneath the "DDL" row on https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.html

Cache type "friendly" name | Cache type code name | Description
-- | -- | --
Compiled Config | `compiled_config` | Compilation configuration

(The description needs to be better, but that's all the code says.)

This is the sample output of the `magento cache:status` command

```
                        config: 1
                        layout: 1
                    block_html: 1
                   collections: 1
                    reflection: 1
                        db_ddl: 1
               compiled_config: 1
                           eav: 1
         customer_notification: 1
            config_integration: 1
        config_integration_api: 1
                     full_page: 1
             config_webservice: 1
                     translate: 1
```

Look for other discussions of the `magento cache` command and update as appropriate.

## Additional information:
Related: MAGEDOC-3030.

**Comment by osrecio** [comment]
@lorikrell I can update this page. Is ok for you?

**Comment by lorikrell** [comment]
@osrecio Of course! :) Feel free to take this one.

**Comment by osrecio** [comment]
Thanks @lorikrell , I overrided a `config-cli-subcommands-cache.md` with new cache type `compiled_config`.

**Comment by lorikrell** [comment]
Reviewing the PR and working to merge. Looks great@

**Comment by lorikrell** [comment]
Accepted PR. @osrecio thank you for the contribution!
