### ISSUE TITLE
Feedback on page: /guides/v2.2/config-guide/cli/config-cli-subcommands-urn.html

### ISSUE THREAD

**Issue by elibyy** [magento/devdocs#2202]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
If you run the URN generator command on a computer without database connection it will refuse to generate and will generate MySQL error

### Steps to reproduce

1. Run `bin/magento dev:urn-catalog:generate <path>`.
You Will get `SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.`

## Expected result:
Output of the URN XML file in the <path> specified

## Possible solutions:
Please clarify the reason for database connection requirement, it would be pretty useful if the developer could generate the urn without needing the database.

**Comment by mhauri** [comment]
Hi @elibyy which magento version did you used and have you any modules/extensions installed?
Tried it on a vanilla Magento 2.2 and vanilla Magento 2.3 version, wasn't able to reproduce.

**Comment by elibyy** [comment]
@mhauri magento 2.2.4 with env.php file but with no access to the database

**Comment by mhauri** [comment]
Thank you for your reply @elibyy I tried it on a 2.2.4 with env.php and no running database. 
Sadly I still can't reproduce the issue.

**Comment by mhauri** [comment]
Hi @elibyy the message "There are no commands defined in the "xxxx:yyyy" namespace." normally appears when Magento isn't installed properly. Try to reinstall Magento again or have a look into the log files.

**Comment by mhauri** [comment]
Hi @elibyy just wanted to ask if the problem still exists? Otherwise, I would be glad if you could close the issue.

**Comment by elibyy** [comment]
Hey, 
sorry about the delay, currently I'll be closing this issue as I cannot reproduce it either, if I'll be able to reproduce will reopen this issue.

Thanks for the support 👍
