### ISSUE TITLE
Community input: Caching

### ISSUE THREAD

**Issue by xcomSteveJohnson** [magento/devdocs#222]
http://devdocs.magento.com/guides/v1.0/config-guide/config/caching.html

If you'd know something about Magento 2 caching, please click **Edit this page in GitHub** and provide some details.

**Comment by halk** [comment]
Thanks Steve. I wonder if it is really recommended to change `config.php` in order to change cache configuration?

I assume it'd be useful to work on the documentation of alternative backends. 

I'm new to Magento2 thus don't know them yet. If that changes I'd be happy to contribute.

**Comment by xcomSteveJohnson** [comment]
There is a risk to editing anything written by the installer that the next time you update Magento, your edits could get blown away. This includes config.php and composer.json at least.

However, if someone provides the content I would find a way to document it in a way that would be supportable.

I believe that work is being done on both the CLI installer and Setup Wizard to enable caching configuration during the install (or maybe afterward). Either way, caching will be documented.

**Comment by xcomSteveJohnson** [comment]
@halk We now have some information on page caching: http://bit.ly/2aBf6t5. Tell us what you think and close this issue if you're happy with it.

**Comment by xcomSteveJohnson** [comment]
Closing due to lack of response. Feel free to reopen.
