### ISSUE TITLE
Magento 2.2.4 :menu is not showing

### ISSUE THREAD

**Issue by Patelcc** [magento/devdocs#2226]
I was found that issue related to **Varnish Cache** 

If we select **Store -> Configuration -> Advanced -> System -> Full page cache -> Caching Application** Set to **Varnish Cache** then menu are not appear in home page other then appear on all pages . 

see below attached screen-shoot

![megamenu](https://user-images.githubusercontent.com/40203855/41290357-44d3291a-6e6a-11e8-8531-163244829e77.png)

If we disable full page cache from admin then menu is displaying perfectly, this problem is occurred because code(Layout) are not **Cacheable**  due to some inappropriate reason.

Don't say that it is occurred because **Varnish Cache** is not integrated in  local environment , if it is valid reason then all other pages also don't appear menu.

**Comment by keharper** [comment]
@Patelcc I'm not certain whether you are asking for a documentation fix or reporting a bug.

**Comment by Patelcc** [comment]
@keharper i am not talking about to modifying  documentation, it's a default magento bug related to varnish cache.
If you want to reproduce this issue in your system then follow step as i mentioned in my question.

**Comment by keharper** [comment]
@Patelcc I need you to report this as an issue on the magento2 code repository. 

https://github.com/magento/magento2/issues

Feel free to reopen this bug if the Community Engineering team says there's a gap or inaccuracy in the docs.
