### ISSUE TITLE
Update page layout documentation 

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#2227]
Type of Doc:
- [ ] New topic
- [x] Topic Update, Devdoc link: https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/layout-types.html
- [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/4454

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/14205

Magento 2 version:
- [ ] 2.1.X
- [x] 2.2.X
- [x] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface?
- [ ] New software requirements?
- [ ] New REST endpoints or updated GraphQL query syntax?
- [ ] New command line option?

## Content:

The `page_layout.xsd` file was updated to allow head and body page layout types. At minimum, update [Layout file types](https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/layout-types.html), but you might also need to create new examples that show how to update the head and/or body of a page.

**Comment by shrielenee** [comment]
Reference the GH issue and PR linked in the description for information on what to add or revise in the noted page.

**Comment by jeff-matthews** [comment]
@bdenham, can you handle this this week? If not, let's talk about reassigning it. Apparently, there are some support tickets that would benefit from this info.

**Comment by bdenham** [comment]
@jeff-matthews, sure, I'll make sure it gets done this week.

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this
