### ISSUE TITLE
Community input: Most-needed tutorial

### ISSUE THREAD

**Issue by xcomSteveJohnson** [magento/devdocs#223]
What one step-by-step tutorial would you benefit from the most right now?

Vote on it by replying to this issue.

**Comment by Retterketet** [comment]
I would love a simple step by step how to get something out of the magento DB into your theme.

For example, Ive added a label on the product DB, and i want the data from that  label to be shown before the "price" globally.

The data is text.

That would give me some good info how to change the html files for my own theme directory.

It would help me and many others very much , I've seen this kind of questions going on the eb for months . Off course there are answers for Mage <2.0 however...Magento 2.0 is very different.

**Comment by xcomSteveJohnson** [comment]
Thanks for your suggestion! We'll look into it and get back to you soon.

**Comment by ryantfowler** [comment]
An officially Magento sanctioned example of creating Sass-based themes. This might include replacing the Magento/Blank theme as a parent theme with something like this: https://github.com/SnowdogApps/magento2-theme-blank-sass . Which would allow all child themes to be based on Sass. If possible, include suggestions on using Compass (http://compass-style.org/) for transpilling Sass/Scss to the correct pub/static location(s) within the Magento 2 installation directory (to avoid the need of using a Php-based transpiler. Why? Needing to wait on Magento to transpile Less slows down development time. This is especially true if an individual's instance isn't tuned for performance...and most front-end developers aren't going to mess with Php opCache/Varnish/etc). If it's not possible to use external file watching tools, then it might be nice to include a reference to this module: https://github.com/magento/magento2-samples/tree/master/module-sample-scss (or an official Sass/Scss Module).
Thanks!

**Comment by ryantfowler** [comment]
Providing more information here: http://devdocs.magento.com/guides/v2.0/ext-best-practices/bk-ext-best-practices.html . At the moment, it really only provides surface level information. It would be nice to include information from ECG based on the Merchant Beta installations which have been/are in production; as well as ECG experience auditing Magento 2 code in production from partners and clients. Furthermore, code examples should not include any legacy Magento 1 code which will later be refactored to take advantage of modern Php features, architecture updates in M2, as well as new vendor libraries currently included in M2. Code examples should be based on taking advantage of the new platform.
Thanks!

**Comment by ryantfowler** [comment]
An example of integrating Magento 2 with a third party CMS, such as WordPress (or something more modern). This would be something like this: https://www.magentocommerce.com/media/webinars/best-practices-integrating-magento-3rd-party-cms/ or this: https://www.youtube.com/watch?v=2gAFClIcADg but for Magento 2. It would be nice to give a concrete example showing how this can be achieved using the Integration API. This would relate to: https://github.com/magento/devdocs/issues/591#issuecomment-207030880 .
Thanks!

**Comment by xcomSteveJohnson** [comment]
Thank you @ryantfowler ! I'm sorry I have not noticed these additions until now. @tanberry would you mind creating issues for these and getting them assigned?

**Comment by ryantfowler** [comment]
@xcomSteveJohnson no problem. Thanks @tanberry, these are important areas of knowledge that will help to improve the adoption rate of M2.

**Comment by ryantfowler** [comment]
Another useful tutorial would be expand upon this white paper: https://magento.com/resources/white-paper-magento-2-site-performance-and-scalability-optimizations . This paper is great, but for instance there is a section which reads

> Magento provides a wide range of deployment and configuration options to support different use cases. 
To optimize performance, many of the settings within Magento must be correctly configured in order to take advantage of the performance and scalability enhancements that are included in Magento 2.0. There are also specific recommended environment configurations that are beyond the scope of this white paper.

It would be fantastic to know **what** the specific recommended environment configurations were. Even if it was a matter of showing examples for CentOS or Ubuntu (or some other server environment), so that there was at least one example to base decisions for adoption in other operating systems.

**Comment by ryantfowler** [comment]
An additionally valuable tutorial might be repository strategies. @alankent has provided an initial offering here: http://alankent.me/2016/03/31/m2-project-source-code-management-recommendation/ (and does a great job trying to help out the community), but it would be helpful to again call upon ECG's experience to get information about how current partners/clients are going about this.

**Comment by ryantfowler** [comment]
@xcomSteveJohnson @tanberry Any feedback as to whether or not any of the above suggested article topics will used? If so, any idea of when these articles will be produced?
Thanks

**Comment by xcomSteveJohnson** [comment]
Internal issues created.

MAGETWO-52900 for SAAS based theme
MAGETWO-52901 for best practices
MAGETWO-52902 for integration for third-party CMS
MAGETWO-52903 for source control in development

These are all new issues so I can't give you an ETA but we'll let you know. The last one is the most speculative. I've heard talk of it but nothing definite.

**Comment by ryantfowler** [comment]
@xcomSteveJohnson Thank you for the feedback.

Not to nit-pick, but it's "Sass" vs "Saas" (just for clarity, so other don't think of a Software As A Service Theme).

That's great that there are issues created! I can appreciate that there are more important issues ahead of these.

Regarding MAGETWO-52903: This is something which is certainly subjective, but having a few suggestions would be great, as it's not entirely clear what a good path forward is, other than trail and error.

Thank you!

**Comment by xcomSteveJohnson** [comment]
Not enough caffeine...

**Comment by ryantfowler** [comment]
Looks like there won't really be a need for an official tutorial on using Sass soon: https://alankent.me/2016/05/21/magento-2-community-project-moving-from-less-to-sass/ .

**Comment by almarchenko** [comment]
Hmm, at least it means that the docs on Sass will be created for sure:) The discussion on their creation is in progress.

**Comment by tkacheva** [comment]
Closing the ticket as the documentation will be part of community project driven by  [SnowDog](https://github.com/SnowdogApps/magento2-theme-blank-sass)
