### ISSUE TITLE
Feedback on page: /guides/v2.2/migration/migration-migrate-settings.html

### ISSUE THREAD

**Issue by weblaunch** [magento/devdocs#2248]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
Run the settings migration command
`{<path to config.xml>}` is the absolute file system path to config.xml; this argument is required.

### Steps to reproduce
n/a

## Expected result:
n/a

## Possible solutions:
It is not explicit _which_ config.xml is being referred to: migration tool? magento1? magento2?

**Comment by jeff-matthews** [comment]
@victor-v-rad, can you help clarify this?

**Comment by victor-v-rad** [comment]
The config.xml which is described previous section of the guide
https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html#migration-configure
