### ISSUE TITLE
Left navigation menu not appearing on contribute to Magento DevDocs page

### ISSUE THREAD

**Issue by leviv** [magento/devdocs#2259]
## This issue is a:
- [x] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
Left navigation menu not appearing on contribute to Magento DevDocs page

### Steps to reproduce

1. First Step
Go to [contribution page](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/Contribute_edg.html)

## Expected result:
Left navigation menu will show as expected

**Comment by lorikrell** [comment]
Thank you for your feedback, @leviv! This issue will be resolved in PR https://github.com/magento/devdocs/pull/2256. We are redirecting that page to the Contributor Guide here: https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html

This should be updated shortly.

**Comment by lorikrell** [comment]
Updates have been merged.
