### ISSUE TITLE
Broken link in performance best practices TOC

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#2290]
## This issue is a:
- [X] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:

The **Advanced JavaScript Bundling**  link in the left nav/TOC of the [Performance Best Practices guide](https://devdocs.magento.com/guides/v2.2/performance-best-practices/index.html) is broken because the `guides/v2.2/performance-best-practices/advanced-js-bundling.md` file doesn't exist.

### Steps to reproduce

1. Go to https://devdocs.magento.com/guides/v2.2/performance-best-practices/index.html
2. Click Advanced JavaScript Bundling in the left nav/TOC.
3. See 404

## Expected result:

1. Go to https://devdocs.magento.com/guides/v2.2/performance-best-practices/index.html
2. Click Advanced JavaScript Bundling in the left nav/TOC.
3. See a topic about JS bundling.

## Possible solutions:

Delete the reference to the missing file from the `_data/toc/performance-best-practices.yml` file. I would've done this, but I'm not sure if this should actually be linking somewhere.

**Comment by lorikrell** [comment]
Verified with Bruce - this is strictly a 2.3 topic. Updating the TOC in PR https://github.com/magento/devdocs/pull/2320
