### ISSUE TITLE
Resurrect updater topic

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#2297]
## This issue is a:
- [ ] Bug on the website
- [x] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
The [Set up the updater (obsolete)](https://devdocs.magento.com/guides/v2.1/install-gde/prereq/prereq_updater.html) topic claims to be obsolete. @buskamuza stated that the updater is still present in the 2.3 code base. 

This topic should be revived and updated to meet current style guidelines. The following commit contains the last known edit in the topic's original state:

https://github.com/magento/devdocs/commit/c42a335b7bd706a3ea4cec460251b5e868c37ed5#diff-ecc87d6f00035a6d2db691f3d5345438

The left nav might need to be updated beyond removing "Obsolete"

## Expected result:

The updater tool is documented fully for all versions.

**Comment by dshevtsov** [comment]
The correct diff is: 821c880d460013e7accdabcd4605c1db78ecfab6#diff-59d53e8ee269bae443eecf2019e17359

**Comment by dshevtsov** [comment]
Fixed in #2660
