### ISSUE TITLE
Magento ^2.2.3 is not compatible with PHP 7.0

### ISSUE THREAD

**Issue by rafaelstz** [magento/devdocs#2312]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [x] Other

## Description:
Magento 2.2.3 and 2.2.4 is not compatible with PHP 7.0

### Steps to reproduce

1. Upgrade Magento 2.2.2
2. Run `composer install`
3. You can see that some core components need PHP 7.1

## Expected result:
Run `composer install`

## Possible solutions:
Describe on DevDocs the compatibility.

How do you think that is a better approach to show it on DevDocs?

**Comment by mhauri** [comment]
Hello @rafaelstz which PHP 7.0 version did you use exactly?

As you can see in the [system requirements](https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html) some PHP 7.0 Versions aren't supported.

I tested a fresh install with PHP 7.0.27, and it worked.
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition test-php-7.0`

**Comment by mhauri** [comment]
@rafaelstz thank you for the print screen, as far as I can see is that you use `composer install` this means it reads the versions from the composer.lock file. Maybe the lock file was generated on a system with PHP 7.1, so what you can try is to use `composer update`.

**Comment by rafaelstz** [comment]
Thanks @mhauri
