### ISSUE TITLE
Feedback on page: /guides/v2.2/install-gde/trouble/tshoot_wrong-mysql.html

### ISSUE THREAD

**Issue by techspotbr** [magento/devdocs#2337]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
I executed the article steps, but the bug was still. So I cleared the redis cache and it worked.
I suggest adding in the article this information for users who are using redis

### Steps to reproduce

1. First Step
2. Second Step
3. Etc.

## Expected result:
Correct execute bin/magento setup:upgrade

## Possible solutions:
clean redis cache with command: redis-cli FLUSHALL

**Comment by mhauri** [comment]
Hi @techspotbr thank you for your feedback, I created a [Pull Request](https://github.com/magento/devdocs/pull/2345) to add this information to the section.
