### ISSUE TITLE
Add custom atttibute like autofill in already existing field in checkout form

### ISSUE THREAD

**Issue by BabliDey** [magento/devdocs#2368]
## This issue is a:
- [ ] New topic request

## Description:
In my custom module checkou layout processor.php page added 
$jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
                    ['shippingAddress']['children']['shipping-address-fieldset']['children']['telephone']['autocomplete'] = 'section-blue shipping telephone';

### Steps to reproduce

1. First Step
2. Second Step
3. Etc.

in telephone field of checkout form there shoud be autofill attribute. But not.

As in chrome 67 autocomplete="off" in chckout form not preventing telephone or other field form auto complete. Thats why need to set autocomplete attribute for every field of that of form or in some particular form. 
Need solution.

**Comment by mhauri** [comment]
Hi @BabliDey 
GitHub is intended for bug reports only, please use [Magento Stack Exchange](https://magento.stackexchange.com/) for questions on how particular customisation can be implemented.
