### ISSUE TITLE
Feedback on page: /guides/v2.2/cloud/project/project-conf-files_services-rabbit.html

### ISSUE THREAD

**Issue by amvapor** [magento/devdocs#2369]
## This issue is a:
Topic clarification request

## Description:
The Magento documentation states simply:
> We support RabbitMQ version 3.5

However when looking at RabbitMQ's documentation, we find:

https://www.rabbitmq.com/which-erlang.html
>RabbitMQ 3.5 was released 2015-03-11, and reached end of life 2017-09-11, we strongly discourage its use

Please Clarify if additional versions of RabbitMq are supported
Alternatively, and likely better, please provide a protocol to which compliance is required.

## Possible solutions:

Updates to the documentation for all versions of Magento2 (2.0, 2.1, 2.2, 2.3)

## Additional information:
Some Clients are unwilling to use software that is past EOL.
Those same clients are also opposed to using software not supported by the software author.

This situation leaves hosting services at a catch22

**Comment by hguthrie** [comment]
The information for RabbitMQ is still correct. The Protocol is mentioned in the sentence just above. We understand it is EOL, but at this moment, the docs are truthful in defining the Cloud implementation. You can use the new Docker development environment, which supports RabbitMQ 3.7.
https://devdocs.magedevteam.com/hg-scdstrategies/guides/v2.2/cloud/docker/docker-config.html
