### ISSUE TITLE
RabbitMQ version recommended by M2.2 is EOF for more than 1 year

### ISSUE THREAD

**Issue by valugi** [magento/devdocs#2370]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [x ] Other

## Description:
M2.2 [recommends](https://devdocs.magento.com/guides/v2.2/install-gde/prereq/install-rabbitmq.html) installing RabbitMQ 3.5.x, which [has finished](https://www.rabbitmq.com/which-erlang.html) his life in 2017-09-11 and its use is not recommended. Apart of this, recommended installation does not work and there are lots of problems with installing such old dependecies of erlang. 

### Steps to reproduce
Follow the installation steps on magento [rabbitmq page](https://devdocs.magento.com/guides/v2.2/install-gde/prereq/install-rabbitmq.html).

## Expected result:
A fully working RabbitMQ.

## Possible solutions:
Upgrade M2 to use more recent RabbitMq and Erlang.

**Comment by jeff-matthews** [comment]
Related to #2369

**Comment by lorikrell** [comment]
Not related to Cloud specifically. More system requirements for install.

**Comment by shrielenee** [comment]
Hey @valugi - Are you installing on CentOS or Ubuntu?

**Comment by valugi** [comment]
correct. Centos 7

**Comment by dobooth** [comment]
From Misha via Slack " since we still will be releasing security patches for 2.2.x next year, I believe it makes sense to do the RabbitMQ upgrade for it too, so I will create a ticket for this"
