### ISSUE TITLE
Add recommendation for database backup scheduling

### ISSUE THREAD

**Issue by skotasthane** [magento/devdocs#2371]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
Admins may define maintenance schedule that takes a backup of both the production and staging databases at the same time. This will actually run more slowly than running them one after the other, due to contention for the available resources

### Steps to reproduce

1. First Step
2. Second Step
3. Etc.

## Expected result:
Users follow a best practice that we should document: "We recommend taking periodic backups of your databases. However, note that due to the I/O intensive nature of backup operation we recommend running only one backup job at a time – for e.g. backup of Production database followed by backup of Staging database. This would avoid I/O contention, especially on smaller instances"

## Additional information:
Add best practice recommendation to this page: https://devdocs.magento.com/guides/v2.2/performance-best-practices/configuration.html

**Comment by lorikrell** [comment]
@skotasthane - I have generated a PR if you want to look over the information. Thanks!

**Comment by lorikrell** [comment]
Content approved and PR merged. Closing issue. Thank you!
