### ISSUE TITLE
Document support for mutations in GraphQL

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#2404]
Type of Doc:
- [x] New topic
- [ ] Topic Update, Devdoc link:
- [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/graphql-ce/issues/74

Magento 2 GitHub PR: https://github.com/magento/graphql-ce/pull/114

Magento 2 version:
- [ ] 2.1.X
- [ ] 2.2.X
- [x] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface?
- [ ] New software requirements?
- [x] New REST endpoints or updated GraphQL query syntax?
- [ ] New command line option?

## Content:

Create a new topic about mutations

**Comment by shrielenee** [comment]
@keharper Is this valid for Squashtoberfest? If so, let's add that Project tag!

**Comment by keharper** [comment]
Completed with #3825
