### ISSUE TITLE
Feedback on page: /guides/v2.2/frontend-dev-guide/themes/js-bundling.html

### ISSUE THREAD

**Issue by kanduvisla** [magento/devdocs#2417]
## This issue is a:

- [ ] Wrong information in the documentation

## Description:

The documentation status that to enable JavaScript bundling, you need to have your site set in production mode and then navigate to "Stores > Configuration > Advanced > Developer". However, since Magento 2.2, the "Developer"-tab is no longer visible in the configuration.

### Steps to reproduce

Read the docs

## Expected result:

The documentation should be updated. Perhaps a note that JS bundling can only be enabled in the CLI in production mode:

    php -f bin/magento config:set dev/js/enable_js_bundling 1

**Comment by bdenham** [comment]
Good catch, @kanduvisla. I will update this soon.

**Comment by bhargavmehta** [comment]
@meker12  I want to take this on. 

A possible solution is to add one line in the doc representing the code for production mode or having one section for enabling in production mode.
Kindly suggest I will create a PR in a couple of hours after that.

Thank you

**Comment by meker12** [comment]
@bhargavmehta We already have PR #2519 for this issue from @gelanivishal if you'd like to review and comment on those changes.

**Comment by bdenham** [comment]
@kanduvisla and @bhargavmehta, I will make sure that the info from this issue gets merged with the changes in PR #2519 and will close it when that PR is merged. Thanks to both of you!

**Comment by bdenham** [comment]
Fixed in PR #2519. Closing.
