### ISSUE TITLE
Page in 2.2.x not reflected and is missing on 2.1.x - Not sure if intentional

### ISSUE THREAD

**Issue by GuitarKat** [magento/devdocs#2441]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [x] New DevDocs feature request
- [x] Other

## Description:

https://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions.html is not existing in https://devdocs.magento.com/guides/v2.1/comp-mgr/install-extensions.html - is this intentional?

### Steps to reproduce

1. Go to https://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions.html
2. Change by the logo Magento 2.2 to Magneto 2.1
3. See page not found page

## Expected result:

Page saying that this particular feature does not exist in 2.1  (instead of saying documentation doesn't exist - I feel it's unclear), but having the sidebar still existing (if possible?)
or
Page for 2.1

## Possible solutions:

1. Page saying this particular feature does not exist in 2.1 (instead of saying documentation doesn't exist - I feel it's unclear), but having the sidebar still existing (if possible?)
2. Page existing if it should be there for 2.1.

**Comment by jeff-matthews** [comment]
Hi @GuitarKat! Thanks for contributing to devdocs. I don't think the 2.1 version was intentionally omitted. We just need to create a 2.1 version of the file and symlink it to the 2.2 and 2.3 directories.
