### ISSUE TITLE
Feedback on page: /guides/v2.2/migration/migration-migrate-delta.html

### ISSUE THREAD

**Issue by Orstio** [magento/devdocs#2456]
# General issue
It should be noted here somewhere that you need the tables the migration initially created in the Magento 1 database in order to perform the delta.  If you wipe the Magento 1 database and try to do the delta, it will fail with the error:

 Deltalog for customer_entity is not installed

## Description:

It is not at all mentioned that the tables created during the initial migration are necessary to retain for the delta migration.

## Possible solutions:

Add a note that these tables are important for the delta migration.  So, if you have Magento 1 on one server, and Magento 2 on another that can't access the live Magento 1 database, you may need to copy the Magento 1 database over, and if you drop and overwrite the database, you will lose those special tables.

**Comment by keharper** [comment]
@dmrachkovskyi Can you help on this one?

**Comment by michizhou** [comment]
If it's alright, I would like to take this issue. #SQUASHTOBERFEST

**Comment by michizhou** [comment]
Hi @Orstio so I had worked on a separate issue (#1136) and planned to make a separate pull request for my commit to this issue, but I made the mistake of making my separate pull request before my old pull request was merged. If there is any chance you could help me split off or recommit my commit for this issue into a separate pull request, I would appreciate it.

**Comment by michizhou** [comment]
Hi @Orstio so I had worked on a separate issue (#1136) and I made the mistake of pushing my commit and then making my pull request for this issue on the same branch as my commit for that branch. Please ignore my pull request for that one (#3017) and only consider my more recent one (#3023).
