### ISSUE TITLE
Magento facebook store extension installation

### ISSUE THREAD

**Issue by Arthi22** [magento/devdocs#2503]
# New feature request

## Description

http://absolutebedding.com.sg/test/admin/
username admin
password joom123!@#sphere
[Facebook_store_application-0.1.7.zip](https://github.com/magento/devdocs/files/2191563/Facebook_store_application-0.1.7.zip)

## Expected result

We need to upload this extension. The plugin developer informed to contact the magento support.

**Comment by mhauri** [comment]
Hi @Arthi22 
The Devdoc Github is only intended for issues/feature request with the Devdocs. 
Actually you should first check with your integrator, as Magento only offers Support for Commerce (Enterprise) Clients.

Also you shouldn't never reveal your password in any form.
I will close this issue. I also suggest to change your password immediately as it is public to anyone.
