### ISSUE TITLE
Topic Correction: Magento Framework correction about the class paths mentioned in the DataObject namespace

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/devdocs#2552]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/framework.html

## Description

Under the "Highlights of Magento Framework", the following entries need to be reviewed
Magento\Framework\DataObject\Model
Magento\Framework\DataObject\AbstractModel  
Magento\Framework\DataObject\AbstractResource 
Magento\Framework\DataObject\Controller
Magento\Framework\DataObject\View
Magento\Framework\DataObject\Data
Magento\Framework\DataObject\URL

The above classes are not part of the DataObject Namespace.

## Possible solutions
Replace the original classes with the ones given against it.

Magento\Framework\DataObject\Model =>  Magento\Framework\Model
Magento\Framework\DataObject\AbstractModel   => Magento\Framework\Model\AbstractModel
Magento\Framework\DataObject\AbstractResource  => Magento\Framework\Model\ResourceModel\AbstractResource
 
Magento\Framework\DataObject\Controller => Magento\Framework\Controller 
Magento\Framework\DataObject\View => Magento\Framework\View
Magento\Framework\DataObject\Data => Magento\Framework\Data
Magento\Framework\DataObject\URL => Magento\Framework\URL

**Comment by dobooth** [comment]
Looks like these changes were made with PR #2571 noted above. Closing.
