### ISSUE TITLE
Feedback on page: /guides/v2.2/cloud/onboarding/onboarding-tasks.html

### ISSUE THREAD

**Issue by amoin-magento** [magento/devdocs#2575]
# General issue

The starter and pro architecture links are broken.

**Comment by jeff-matthews** [comment]
@hguthrie, the broken links are in this section: https://devdocs.magento.com//guides/v2.2/cloud/onboarding/onboarding-tasks.html#project-setup.

Those links use the `{{site.baseurl}}` variable, but they should probably use the `{{page.baseurl}}` variable instead. Also, the Pro Architecture link contains the wrong path to the file.

**Comment by hguthrie** [comment]
I am adding Margaret. She worked on this topic recently and wants to address it.

**Comment by meker12** [comment]
@mage2pratik Thanks for fixing the broken links.
