### ISSUE TITLE
Add info how to declare custom less mixins

### ISSUE THREAD

**Issue by denistrator** [magento/devdocs#2578]
There is info in M2 docs how to declare custom variables or how to override existing less variables.
For example: custom less variables can be define in theme in `web/css/source/_variables.less`
But where custom less mixing must be declared?

**Comment by jcalcaben** [comment]
Hi @denistrator ! Please format the content of this issue to match one of the pre-set issue templates:
https://github.com/magento/devdocs/issues/new/choose

Thanks!

**Comment by keharper** [comment]
@bdenham Can you follow up with this?

**Comment by bdenham** [comment]
Hi @denistrator!, Is this what you are looking for? https://devdocs.magento.com/guides/v2.2/coding-standards/code-standard-less.html#mixins

**Comment by denistrator** [comment]
@bdenham hi. No this is not. I need to know where I should put my custom less mixins. I think it's possible that there's no place for it yet. Need to check it

**Comment by bdenham** [comment]
@denistrator, I just talked to @bassplayer7 and in his own words:
> My suggestion is to use the `source/_extend.less` file, provided you don't have a ton [of mixins to add]. But in that case, you could import a different file. `source/_extend.less` is a `@magento_import` so it can be included individually in various modules. Also note, it's not `_extends` (with an `s`). That `_extends` file is a massive collection of mixins.

I the coming days, I will include a new devdocs topic to address this gap. In the meantime, I hope the above info helps.

**Comment by jfrontain** [comment]
We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the Frontend project.

**Comment by Santoshziffity** [comment]
@magento I am working on this
