### ISSUE TITLE
Link "Installing required PHP extensions on Ubuntu" is broken

### ISSUE THREAD

**Issue by TapaniAla** [magento/devdocs#258]
Clicking link "Installing required PHP extensions on Ubuntu"  doesn't lead anywhere.

**Comment by xcomSteveJohnson** [comment]
Thank you for pointing that out. It's an unfortunate oversight; however, each section has the extension installation instructions in it. The link isn't necessary anymore. I will notify you when the link is gone.

**Comment by TapaniAla** [comment]
I agree it is obsolete so I found it confusing. Thanks.

**Comment by xcomSteveJohnson** [comment]
Please verify and close if it's fixed:

http://devdocs.magento.com/guides/v1.0/install-gde/prereq/php-ubuntu.html
http://devdocs.magento.com/guides/v1.0/install-gde/prereq/php-centos.html
http://devdocs.magento.com/guides/v1.0/install-gde/trouble/tshoot_pdo.html
