### ISSUE TITLE
Path needs adjustment in Running Composer ...

### ISSUE THREAD

**Issue by TapaniAla** [magento/devdocs#259]
In "Running Composer to update dependencies"
"Change to the Magento installation directory and run composer install. For example,
cd /var/www/html/magento2 && composer install"

/var/www/html/magento2 will apply for Centos but Ubuntu has /var/www/magento2

**Comment by xcomSteveJohnson** [comment]
Please verify and close: http://devdocs.magento.com/guides/v1.0/install-gde/install/prepare-install.html
