### ISSUE TITLE
Prerequisites / MySQL / Installing and configuring. Add reminder to start mysql service

### ISSUE THREAD

**Issue by denistrator** [magento/devdocs#2634]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.2/install-gde/prereq/mysql.html#instgde-prereq-mysql57-ub16

## Description
In `Installing and configuring MySQL 5.7 on Ubuntu 16` section, under `To install MySQL 5.7 on Ubuntu 16:` steps it would be nice to add step after first step to remind user to start Mysql.

## Possible solutions
Add step after current 1st step ("Enter the following command:") which says:

Start Mysql service
`sudo service mysql start`

**Comment by mhauri** [comment]
Hi @denistrator thanks for pointing out, it's now added to the devdocs.
