### ISSUE TITLE
ServiceContracts DesignPatterns: Data now Mutable

### ISSUE THREAD

**Issue by otoolec** [magento/devdocs#267]
In the Service Contracts sub page about Design Patterns there are references to Data Interfaces/Objects being immutable but the codebase and strategy has changed to allow for mutable Data.  References to immutability and to builders need to be removed.

**Comment by xcomSteveJohnson** [comment]
@keharper, please take a look.

**Comment by keharper** [comment]
Will do.

**Comment by tanberry** [comment]
@keharper the "Info" section at the top of design-patterns.html is not resolving properly; the html code is displayed.

**Comment by keharper** [comment]
Fixed.

**Comment by keharper** [comment]
It appears that I forgot to close this a year ago. Closing.
