### ISSUE TITLE
 misleading documentation

### ISSUE THREAD

**Issue by LouNik1984** [magento/devdocs#2676]
# Topic clarification/correction request
Official documentation leads people to install a version of php which is not compatible with magento. Documentation should be changed to avoid this.

## Topic Link
https://devdocs.magento.com/guides/v2.2/install-gde/prereq/nginx.html

## Description
- Go to magento official guide at page https://devdocs.magento.com/guides/v2.2/install-gde/prereq/nginx.html to install magento 2.2 with nginx and php-fpm
- follow instructions, so install nginx with apt-get -y install nginx and then php-fpm with apt-get -y install php7.0-fpm php7.0-cli
- Run php -v in command line
- I expect to see the latest stable version of php7.0 or at least one of the php 7.0 version compatible with magento
- What I actually see is php 7.0.3 which, according to official documentation (https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html) is not compatible with magento.

## Possible solutions
Documentation should have instructions that would lead to have a compatible version of php-fpm.

**Comment by jeff-matthews** [comment]
Great catch @LouNik1984. I think we should also update the method of downloading the Magento software from an archive to Composer.

**Comment by LouNik1984** [comment]
I agree about composer, to this day I still haven't figure out what's the reccomended way to install magento. Some pages of the documentation goes towards composer, but then they say that you shouldn't use composer on a shared host but then again composer is mandatory for upgrades but then you shouldn't use it on production environment... But again, I don't find any other people who mention this though, so maybe it's only me that's confused

**Comment by jeff-matthews** [comment]
I don't think it's just you. Historically, we haven't made a solid recommendation. We're currently working on some update however that will make it more clear. 

Also, we recently rewrote the [Composer install topic](https://devdocs.magento.com/guides/v2.2/install-gde/composer.html) to be more clear and concise. In general, Composer is the best way to install Magento.

**Comment by lorikrell** [comment]
Updating content - notes for changes TBD:

* v2.2 - Adding note and link to PHP versions topic. When using the command, the latest 7.0.X version is installed. Can view the topic for supported versions for details.
* v2.3 - The PHP version in the command needs to be updated with link to PHP versions topic for 2.3 Verify the PHP versions topic for 2.3 is also accurate.

**Comment by lorikrell** [comment]
Content updated, revising PHP version across all Magento versions. Added Composer instructions to replace archive install. Please check [nginx](https://devdocs.magento.com/guides/v2.2/install-gde/prereq/nginx.html) for updates.
