### ISSUE TITLE
Feedback on page: /guides/v2.2/b2b/credit-manage.html

### ISSUE THREAD

**Issue by rubenexp** [magento/devdocs#2685]
# General issue

## Description:
The documentation in section https://devdocs.magento.com/guides/v2.2/b2b/credit-manage.html#update-a-company-credit-limit says the creditLimit can be updated based on companyID, but the PUT endpoint does not exist in 2.2.5.

## Possible solutions:

Remove the section, or make this endpoint available for the API.

**Comment by keharper** [comment]
@rubenexp Thanks for making us aware of this. The endpoint route was listed correctly at the top of the topic. I've corrected the route to `PUT /V1/companyCredits/:id`.

Fixed in[ PR-2689](https://github.com/magento/devdocs/pull/2689)
