### ISSUE TITLE
Add favicon to the http://devdocs.magento.com/

### ISSUE THREAD

**Issue by erikhansen** [magento/devdocs#269]
It would be nice if http://devdocs.magento.com/ had a favicon specified. The default Magento icon is an obvious choice, but something more specific might be nice. 16x16 isn't much space to work with, but it would be cool if a document icon could somehow be merged with a Magento icon. Maybe the Magento logo inside of a document. Not sure if the Magento logo guidelines would allow for this usage, but if you think it might be a good idea, let me know and I'll mockup a concept in Photoshop.

**Comment by tanberry** [comment]
Hi Erik, that icon of the Magento logo within a doc icon sounds great, and thanks for the generous offer to do a mockup! Just to be sure we understand, you mean an icon that readers would see on any pages that they have "favorited?"  We'd need to decide 1) where that icon would appear, and 2) the mechanism by which they favorite a page.
Or maybe you aren't even referring to favoriting pages, but to the whole site? Tell us more! ;-)

**Comment by erikhansen** [comment]
@tanberry Favicons are actually the icons that are associated with websites that show in a user's browser or when they bookmark that site (http://en.wikipedia.org/wiki/Favicon). Example favicons:

![favicon_-_google_search](https://cloud.githubusercontent.com/assets/129031/7522674/657b3d0e-f4bc-11e4-9636-8ec3c7d4b449.png)

**Comment by tanberry** [comment]
Ah, now I am even more interested. ;-) That would be very useful, especially for people like me that always have a gazillion tabs open. Thanks, and we will start looking into it on this end to see what guidelines we might have, etc.

**Comment by xcomSteveJohnson** [comment]
@erikhansen We have one, it was in the wrong location. I don't think we need to jump through hoops to change it but anything you do to that end is strictly up to you. We'll be glad to give you a Twitter shout out but please don't let it take away from your other work.

**Comment by erikhansen** [comment]
@xcomSteveJohnson If you have already one, then great. I have plenty of other things to work on. :)

**Comment by xcomSteveJohnson** [comment]
I figured. I put it in the correct location, it'll show up later today.
