### ISSUE TITLE
Shipping carrier validation missing important name convention

### ISSUE THREAD

**Issue by domeglic** [magento/devdocs#2700]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.2/howdoi/checkout/checkout_carrier.html

## Description

In step 4 adding validation using layout does not mention the naming convention. If the name is not correct it will get removed and will not work.

## Possible solutions

It should be mentioned that the name needs to be `carrier-rates-validation` instead of
`<item name="<your-validation-name>" xsi:type="array">` where carrier has to match the actual carrier code.

## Additional information

[This](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Checkout/Block/Checkout/LayoutProcessor.php#L193) code will remove all validation files that do not match active carriers.

**Comment by shrielenee** [comment]
Hey @lorikrell - Are you working on this? If not, is it a good candidate for community work?
