### ISSUE TITLE
URL Differences

### ISSUE THREAD

**Issue by GuitarKat** [magento/devdocs#2743]
# New topic request

## Description

Store URL and other URL differences - how they really function in templates for the Front End Dev guide.

i.e: {{base_unsecure_url}} v. {{base_secure_url}} and {{store url=""}} in how they work for different situations, like multi-store and single store and production and testing environments where SSL certs may not exist.

I couldn't find any resources specifically direct to this topic and would like to know more.

I would also want to write about URL Pathing and how it works for Front End Devs for other aspects like media, base, etc.

## Content checklist

- [x] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [x] The topic contains code samples that shows ____.
- [ ] Other (please specify)

## Additional information/resources

I asked on Stackoverflow for the answer regarding the differences, but I believe it should have a home in devdocs as testing environments v. production environments can differ.

**Comment by XxXgeoXxX** [comment]
Hi. Looks like some guide has already existed 
https://docs.magento.com/m2/ce/user_guide/stores/store-urls.html
I could help you  if you have some another questions.

**Comment by pareshpansuriya** [comment]
#mm20in

**Comment by ccondra** [comment]
This issue has been addressed.
