### ISSUE TITLE
Feedback on page: /guides/v2.2/config-guide/prod/prod_file-sys-perms.html

### ISSUE THREAD

**Issue by RedAtRareCandy** [magento/devdocs#2756]
# General issue

"Production file system ownership for shared hosting (one user)" permissions recommendation causes 500 server error with PHP-FPM & SuPHP (which run as user).

## Description:

This page suggests that User write permissions should be removed in Production for a number of directories and files. Unfortunately, with SuPHP and PHP-FPM, they run as the user so removing write permissions causes Apache to throw a 500 server error when loading storefront.

[17-Aug-2018 00:10:29 UTC] PHP Fatal error:  Uncaught Zend_Cache_Exception: cache_dir "/home/user/public_html/var/page_cache" is not writable in /home/user/public_html/vendor/magento/zendframework1/library/Zend/Cache.php:209

## Possible solutions:

This section doesn't account for hosting, in the One User sections, where the PHP handler runs as the hosting account?

**Comment by shrielenee** [comment]
Hey @antonkril - Do you have an architect willing to help with this issue? We need some expert guidance on how to approach it. Thanks!

**Comment by antonkril** [comment]
cc @buskamuza
