### ISSUE TITLE
auto flag missing in Data Migration devdocs

### ISSUE THREAD

**Issue by peterjaap** [magento/devdocs#2763]
# Topic clarification/correction request

## Topic Link

https://github.com/magento/devdocs/blob/master/guides/v2.3/migration/migration-migrate-settings.md
(symlinks to https://github.com/magento/devdocs/blob/master/guides/v2.1/migration/migration-migrate-settings.md)

## Description

The command signature shows the reset option and the config argument, but the auto option (`-a`) is missing. This was introduced in the 2.2.5 release (see https://github.com/magento/data-migration-tool/commit/92edc9e3916c0913d089679edccc9b73cde0abcc).

## Possible solutions

Add the `-a` (auto) option to the signature in the documentation so the signature becomes;

`migrate:settings [-r|--reset] [-a|--auto] [--] <config>`

**Comment by osrecio** [comment]
Hi @peterjaap . You're right, I can create a PR with the change or I can invite you to create it.
