### ISSUE TITLE
Postal Code Scope. Misleading information presented in documentation.

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#2769]
# Bug report

## Description
Misleading information shown in documentation.
Says that postal code scope is global. When In fact postal code scope is website.

## Expected result
Correct information to be presented in the documentation

## Possible solutions
Change the information presented in the documentation to be accurate.

## Additional information
https://docs.magento.com/m2/ce/user_guide/configuration/scope.html

![postal-code](https://user-images.githubusercontent.com/25669334/44307202-c9c79900-a3a6-11e8-93a6-aca248fbeb51.png)

Go to Admin > Store > Configuration > General > Store Options > Postal Code Input
![postal-code-actual](https://user-images.githubusercontent.com/25669334/44307205-d21fd400-a3a6-11e8-9dbb-424e93791cc1.png)

**Comment by jeff-matthews** [comment]
Thanks for reporting this issue @victortodoran. This repo doesn't contain the source for the _Admin User Guide_ (https://docs.magento.com). Please use the feedback mechanism at the bottom of the [affected page](https://docs.magento.com/m2/ce/user_guide/configuration/scope.html). Click **Rate This Page** > **Problem** to describe the issue.

<img width="710" alt="rate-this-page" src="https://user-images.githubusercontent.com/13662379/44340492-a35b3980-a44a-11e8-9ef5-0a068a6944e6.png">
