### ISSUE TITLE
Incorrect information about Price Scope.

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#2770]
# Bug report

## Description
Documentation states that Product Price can be set at Store Level.
This is not true. Product Price can be set only at Global or Website Level.

## Expected result
Correct and accurate information to be presented in the documentation

## Additional information
https://docs.magento.com/m2/ce/user_guide/catalog/catalog-price-scope.html
![price-docs](https://user-images.githubusercontent.com/25669334/44307267-f92ad580-a3a7-11e8-83cc-de61b81b8a7f.png)

**Comment by jeff-matthews** [comment]
Thanks for reporting this issue @victortodoran. This repo doesn't contain the source for the _Admin User Guide_ (https://docs.magento.com). Please use the feedback mechanism at the bottom of the [affected page](https://docs.magento.com/m2/ce/user_guide/catalog/catalog-price-scope.html). Click **Rate This Page** > **Problem** to describe the issue.

<img width="710" alt="rate-this-page" src="https://user-images.githubusercontent.com/13662379/44340492-a35b3980-a44a-11e8-9ef5-0a068a6944e6.png">
