### ISSUE TITLE
Feedback on page: /guides/v2.2/extension-dev-guide/plugins.html

### ISSUE THREAD

**Issue by gpnalin** [magento/devdocs#2784]
# General issue

## Description:
After the plugin execution order seems to be invalid. On devdocs page, it stated that after plugin will run on order as below.

1. PluginC::afterDispatch()
2. PluginB::afterDispatch()
3. PluginA::afterDispatch()

But with the investigations, it turns out order is as below.

1. PluginA::afterDispatch()
2. PluginB::afterDispatch()
3. PluginC::afterDispatch()

## Possible solutions:

Above should be verified and corrected immediately as it will misleading for the developers.

**Comment by osrecio** [comment]
Hi @gpnalin , You use the sortOrder for the plugin A, B, C like a documentation?
Following that they have beforeDispatch and Around Dispatch?
A->10
B->20
C->30

If you only have afterDispatch you're are right but following the guide I think is OK in the guide.

**Comment by gpnalin** [comment]
I've used the sortOrder like in the guide. Yes my concern is about the
afterDispatch. Isn't that order is incorrect? Higher sirtOrder value runs
after lower sortOrder plugins. But according to guide lower one runs after
higher ones.

**Comment by hguthrie** [comment]
@osrecio Are you still waiting for a response? Do we need a little more research into sortOrder and afterDispatch?

**Comment by osrecio** [comment]
I didn't have time to do a little reseach about it.

**Comment by hguthrie** [comment]
Okay, no problem. Thanks for your input; I removed you from the assignee.

**Comment by dobooth** [comment]
Hi @gpnalin I am following up on this issue you submitted. 
I wanted to first confirm they issue and your thoughts on it. 
In the docs, it says:
`Before the execution of the observed method, Magento will execute plugins from lowest to greatest sortOrder.`
and then:
`Following the execution of the observed method, Magento will execute plugins from greatest to lowest sortOrder.`
Note that in afterDispatch, it says the order is reversed: Greatest to lowest.
Is this inconsistent from what you are seeing?

**Comment by dobooth** [comment]
Closing as stale. The feedback I got from arch and community didn't find any errors in the docs. We can reopen if need be.
