### ISSUE TITLE
Theme inheritance - layout files order

### ISSUE THREAD

**Issue by Januszpl** [magento/devdocs#2796]
# Topic clarification/correction request
Theme inheritance - Extends layout - Layout files collecting order

## Topic Link
https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-inherit.html#theme-inherit-layout

## Description

Not sure but I think the order is opposite unless the author meant here something else and collecting != merging. But following guide from SwiftOtter probably better would be use something explanation like - see possible solutions below. This order is also used in some other places in documentation.

## Possible solutions

> Layout XML instructions are first merged in the base area and then by the area that applies to the current request (frontend or adminhtml).
> Here is the order in which layout XML is merged:
> 
> - Module base files loaded
> - Module area files loaded
> - Sorted according to their module priority (array index of module’s position in app/etc/config.php)
> - If their priorities are equal, they are sorted according to their alphabetical priority.
> - Theme files (from furthest ancestor to current theme)
> - Layout files loaded
> - Override files replaced

solution copied from pdf study guide - source: @JosephMaxwell - https://swiftotter.com/technical/certifications/magento-2-frontend-developer-study-guide

**Comment by bdenham** [comment]
Thanks, @Januszpl. Sorry for the delay on this. I will investigate and open a PR when I can. Or if you're willing to open a PR yourself on this, I'll be happy to facilitate a quicker path to production. In either case, I'll investigate and get this pushed through as soon as I'm able.

**Comment by jfrontain** [comment]
We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the Frontend project.

**Comment by Santoshziffity** [comment]
@magento I am working on this

**Comment by erikmarr** [comment]
@Santoshziffity Are you still working on this?

**Comment by BarnyShergold** [comment]
This was fixed by PR4499
