### ISSUE TITLE
Amend technology stack

### ISSUE THREAD

**Issue by mzeis** [magento/devdocs#284]
On [Technology Stack](http://devdocs.magento.com/guides/v1.0/architecture/arch-basics.html), you could add these things mentioned by Max in [presentations](http://de.slideshare.net/MeetMagentoIt/max-yekaterynenko-magento-2-overview):

* Apache 2.2, 2.4
* Nginx 1.7
* PSR-3
* PSR-4
* Optional stack component: Varnish (Caching)

**Comment by xcomSteveJohnson** [comment]
@jfrontain , please add these in a future revision. Thanks.

**Comment by xcomSteveJohnson** [comment]
@jfrontain any update?

**Comment by xcomSteveJohnson** [comment]
@mzeis Please check out the update and close this issue if you're satisfied: http://devdocs.magento.com/guides/v1.0/architecture/arch-basics.html

**Comment by mzeis** [comment]
Thank you!
