### ISSUE TITLE
Correct information

### ISSUE THREAD

**Issue by rafaelstz** [magento/devdocs#287]
Change short description and link repository for similar in `README.md` file:

**Magento developer resources** http://www.magento.com

To:

**Magento Developer Documentation** http://devdocs.magento.com

**Comment by xcomSteveJohnson** [comment]
We don't own our repository. I'll make a request to have it changed and update you with the results. I believe at one time our text matched the Magento 2 GitHub but that's no longer the case.

**Comment by xcomSteveJohnson** [comment]
This has been done. Thanks!
