### ISSUE TITLE
Table output not transformed correctly

### ISSUE THREAD

**Issue by clivewalkden** [magento/devdocs#2873]
# Bug report

## Description

Table isn't transformed into html correctly.

### Steps to reproduce

Visit the following pages:
https://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web_3-web-conf.html
https://devdocs.magento.com/guides/v2.1/install-gde/install/web/install-web_3-web-conf.html
https://devdocs.magento.com/guides/v2.2/install-gde/install/web/install-web_3-web-conf.html
https://devdocs.magento.com/guides/v2.3/install-gde/install/web/install-web_3-web-conf.html

View Step 3 bullet 1 and you'll see the broken table.

## Expected result

Data should be output in a table as Step 3 point 2

## Possible solutions

Check file _includes/install/web/install-web_3-web-conf.md for issues.

## Additional information

I'll fix the issue and create a PR shortly.

**Comment by shrielenee** [comment]
Hey @clivewalkden - I see you created a PR to address this raised issue. I'm going to go ahead and close this and work your PR instead! Thanks! 💯
