### ISSUE TITLE
Documentation about running Web API integration tests no longer correct

### ISSUE THREAD

**Issue by dverkade** [magento/devdocs#2876]
# Topic clarification/correction request

https://devdocs.magento.com/guides/v2.3/get-started/web-api-functional-testing.html

## Description

Under "running the tests" is suggests copying the file "/dev/tests/api-functional/phpunit.xml.dist". This file does not exist anymore in Magento 2.3 alpha and the files have been split up into: 

- /dev/tests/api-functional/phpunit_graphql.xml.dist
- /dev/tests/api-functional/phpunit_rest.xml.dist
- /dev/tests/api-functional/phpunit_soap.xml.dist

## Possible solutions

Change documentation to suggest copying one of these files over to start with the Web API integration tests.

**Comment by keharper** [comment]
Thanks @dverkade for letting us know about the change.

Closed via #2882 . I only mentioned the REST and SOAP files. GraphQL is documented separately. I did note the new file for GraphQL in graphql-ce [Issue 77](https://github.com/magento/graphql-ce/issues/77)
