### ISSUE TITLE
Feedback on page: /guides/v2.2/ext-best-practices/tutorials/copy-fieldsets.html

### ISSUE THREAD

**Issue by WebKenth** [magento/devdocs#2910]
# General issue

## Description:

It is not declared where the copy class should be placed.

A slimmed down version of a class without any hint of where to put it is really bad documentation.

## Possible solutions:

Rather than using the magic 3 dots to hide important information, show us the entire class. 
The namespace alone would reveal key information on where to place it.

This hardly qualifies as an example of how to copy fieldsets.

Be explicit, tell us where to place the extension_attributes.xml, don't assume we know that it should be placed in the `etc` folder.

**Comment by michizhou** [comment]
I can take this issue. If you could provide more supporting docs that would be much appreciated! #SQUASHTOBERFEST

**Comment by WebKenth** [comment]
@michizhou couldn't get it to work at all ended up using a plugin listening on `beforePlace` on the `\Magento\Sales\Api\OrderManagementInterface` and added my data from the `Quote`

All i needed was to copy a field when converting from Quote to Order and this doc seems like the right way to do it, but alas i couldn't get it to work using fieldsets.

**Comment by michizhou** [comment]
@WebKenth In that case, are there other related tasks to which I could contribute? I would appreciate being able to help resolve this issue in any way I can!

**Comment by lorikrell** [comment]
THis was completed per PR https://github.com/magento/devdocs/pull/3992. Closing issue.
