### ISSUE TITLE
Provide more info about file/classes in code snippets to adding-attributes.html

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#2916]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.html

## Description

In the [Extension Attributes Configuration section](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.html#extension-attributes-configuration) of [Adding extension attributes to entity page](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.html), add more information about files and classes relevant to the provided code snippets so that it's clearer and more descriptive.

## Additional information

This is an issue/question related to customer feedback on the DevDocs site.

**Comment by nathancasebolt** [comment]
If I may chime in, I agree with @shrielenee that this page needs attention. In my opinion, it needs to be thoroughly reworked. The only way to come close to understanding the example is to reference the sample module at the bottom of the page and try to match its files to the example text.

Even then, it's difficult to tell what's happening for a number of reasons. First, actual code is mixed with XML-style examples of response object structures _and_ with XML configuration files. This makes it harder to see when we're looking at code we need to implement and when we're looking at a conceptualized object.

Second, the language needs to be smoothed out. As a monolinguist, I have nothing but admiration and respect for people who can work in more than one language. Still, this page is pretty clearly written by someone who is still perfecting their English, and the use of non-standard grammar and syntax layers on some extra difficulty in following the example.

Third, I would _highly_ recommend giving an example of passing user input from the frontend into an extension attribute. This is the chasm I'm trying to bridge, and I'm finding clear examples quite difficult to find. It would be helpful if Magento's own docs provided a clear and understandable example of how to take custom user-input data and turn it into an extension attribute.

There are probably other ways to make this page more valuable to the developer, but those are some of my ideas. I hope they help.

**Comment by shrielenee** [comment]
That's great feedback @nathancasebolt.  💯 

@michizhou Can you run with that to start creating a PR? I'm more than happy to edit it for language and copy stuff when done. 

Let us know!!!

**Comment by shrielenee** [comment]
Hey @michizhou - Can you please update us on your progress? Thanks!

**Comment by dineshvb** [comment]
@magento I am working on this
