### ISSUE TITLE
Serving with jekyll

### ISSUE THREAD

**Issue by CoreyCole** [magento/devdocs#295]
I'm trying to build the site with jekyll like it says in the readme. I'm running on windows 7 64 bit. I renamed _config.devdocs.yml to _config.yml. When I run "jekyll serve" I get the following output:

C:\Users\CNCOLE\Documents\GitHub\devdocs>jekyll serve
Configuration file: C:/Users/CNCOLE/Documents/GitHub/devdocs/_config.yml
Source: C:/Users/CNCOLE/Documents/GitHub/devdocs
Destination: C:/Users/CNCOLE/Documents/GitHub/devdocs/_site
Generating...
Liquid Exception: Failed to get header. in guides/v1.0/architecture/backward-compatibility.md
jekyll 2.5.3 | Error:  Failed to get header.

**Comment by xcomSteveJohnson** [comment]
We're sorry you're having this issue. I also use Jekyll (v 2.4.0) on Windows 7 64-bit and do not see this issue. Googling it indicates it might be a Python issue. References at the end.

FWIW, I installed Portable Jekyll which has everything in a command environment; IOW, I don't have to install Ruby or Python or anything else. If all else fails, you can consider that: https://github.com/madhur/PortableJekyll (clone the repo and call setpath.cmd)

References:

http://ajoz.github.io/2014/06/28/jekyll-on-windows/
http://akenn.org/blog/Liquid-Exception-Jekyll/
https://talk.jekyllrb.com/t/liquid-exception-failed-to-get-header/752
http://stackoverflow.com/questions/17816499/jekyll-on-windows-liquid-exception-failed-to-get-header (from 2013)

**Comment by CoreyCole** [comment]
Thanks!

**Comment by xcomSteveJohnson** [comment]
I hope it helps.

**Comment by xcomSteveJohnson** [comment]
@CoreyCole Any change?

**Comment by CoreyCole** [comment]
I'm going to be setting it up on Linux instead because I'm not used to
Windows.

**Comment by xcomSteveJohnson** [comment]
Sounds good. Let us know if we can help. I've also run Jekyll on Linux.

**Comment by xcomSteveJohnson** [comment]
How's it going?

**Comment by CoreyCole** [comment]
I've got it working on Linux, thanks for your help.

**Comment by xcomSteveJohnson** [comment]
Issue is resolved, closing.
