### ISSUE TITLE
Feedback on page Translate theme strings

### ISSUE THREAD

**Issue by debuysserk** [magento/devdocs#2953]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/translate_theory.html

## Description

using sprintf in combination with __( to add variables in translate strings results in a too few arguments exception. 

## Possible solutions

Sprintf is not needed anymore, you can just use __('variable %1 variable %2',$yourvariable) instead. %1 = first variable of course. Don't use the same sprintf %s syntax!

## Additional information

No additional information.

**Comment by bdenham** [comment]
This issue was resolved with the merge of #3075.
