### ISSUE TITLE
Feedback on page: /guides/v2.2/release-notes/ReleaseNotes2.2.6CE.html - Use default value randomly unticked store level issue

### ISSUE THREAD

**Issue by SAPontwerp** [magento/devdocs#2954]
# General issue

## Description:

When updating attribute values on store level for other attributes default values are un ticked. 
For example when I update the product name the default value tickbox is ticked off for the images and some of the search engine optimazation fields
## Possible solutions:

Only update the attribute value that has been changed for the selected store view.

## Additional information:

Release notes 2.2.6

The Use default value option is no longer unchecked unless the user overrides the value of the attribute in the store view scope. Previously, after creating an item, if the user changed to store view scope and did not make any modifications to the item’s attributes and only clicked Save, most of the attributes that were set as Use default value became unchecked

**Comment by jcalcaben** [comment]
@jfrontain is there an update on this issue?
