### ISSUE TITLE
XML сonfiguration of UI сomponents: Example appears to offer conflicting information

### ISSUE THREAD

**Issue by nathancasebolt** [magento/devdocs#2957]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.html

## Description

If I understand this article correctly, a UI component's `component` node within a module's component configuration file (if said node exists) will merge with the UI component's `component` node within `definition.xml`. The article notes (correctly) that the `component` node is omitted from the example configuration file, but later appears to assert that it is merged with the `definition.xml` node.

## Possible solutions

Add a `component` node to the example configuration file and normalize the text to match, or normalize the text to match the existing example. Alternatively, fix my faulty understanding of what's being explained here.

## Additional information

![screen shot 2018-09-20 at 11 39 51 am](https://user-images.githubusercontent.com/37882858/45834155-1961f300-bccc-11e8-9acf-87a9c8cf6eea.png)

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
