### ISSUE TITLE
Feedback on page: /guides/v2.2/config-guide/config/disable-module-output.html

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#2959]
# General issue
No references to DB tables where module could be also disabled.

## Description:
It would be great to add info that event if there is no any disabled modules in mentioned in article files (`config.xml` in Backend module and `<Magento_install_dir>/app/etc/config.php`) it's still possible that module is disabled by value in database in table `core_config_data` and it can be found byvalue like `advanced/modules_disable_output/VendoeName_ModuelName` in `path` column.

**Comment by jeff-matthews** [comment]
Thanks for volunteering @michizhou! If you need help understanding how to contribute to devdocs, check out our [CONTRIBUTING.md](https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md) file. If you still have questions, don't hesitate to ask.

**Comment by jeff-matthews** [comment]
It would be best to work directly with @likemusic for clarification, but I think the request is to add information about disabling modules using database values instead of the `config.xml` file.

**Comment by michizhou** [comment]
Hi @jeff-matthews I just wanted you to know that I submitted a PR with a commit addressing this issue a few days ago. Let me know if other changes need to be made. Thanks!

**Comment by jeff-matthews** [comment]
Hi @michizhou, thanks. I commented on your PR.

**Comment by jfrontain** [comment]
hi @michizhou, let us know where you are in this task. We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the Installation and Configuration project.

**Comment by keharper** [comment]
This topic as been updated recently, thanks to the efforts of @dobooth I don't think we want to encourage poking around in the DB to determine whether module output is disabled. Sounds more like a potential knowledge base article.

**Comment by keharper** [comment]
Closing, per https://github.com/magento/devdocs/pull/3030

**Comment by michizhou** [comment]
@jfrontain As mentioned by @keharper, this particular issue seems no longer relevant as the focus has shifted away from its original scope of looking in the DB to see if module output is disabled for the fear that such probing could lead to unfavorable changes that could affect the DB. As such, I am no longer involved with this issue and have left @keharper and company to take over.
