### ISSUE TITLE
404 Links in /guides/v2.2/contributor-guide/contributing.html

### ISSUE THREAD

**Issue by manishmittalm** [magento/devdocs#2990]
# Bug report
404 Links in /guides/v2.2/contributor-guide/contributing.html

## Description

Many 404 Links I found in this document /guides/v2.2/contributor-guide/contributing.html, they should redirect to proper URL instead 404.

### Steps to reproduce

1. Open in browser https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html
2. Search "Community Maintainers", "Magento EngCom Team" link
3. Click on these link they will redirect to 404 page

## Expected result
They should redirect to proper url instead 404

![code contributions magento 2 developer documentation](https://user-images.githubusercontent.com/37134503/46129975-c51fbb80-c255-11e8-9c21-81122545f004.png)

**Comment by shrielenee** [comment]
Hi @manishmittalm - I checked those links on my browser and an Incognito window and received no 404s. What browser are you using?

**Comment by manishmittalm** [comment]
Hello @shrielenee 

I am using Ubuntu > Google Chrome. 

Trying to access these pages directly:

https://github.com/orgs/magento/teams/core-maintainers/members
https://github.com/orgs/magento/teams/open-source-maintainers/members

![404 png 1366x768](https://user-images.githubusercontent.com/37134503/46194160-34f97900-c31e-11e8-8866-1147c3c3b84c.png)

**Comment by jeff-matthews** [comment]
I believe that you must have access to a GitHub org to see the teams associated with that org. GitHub doesn't do a good job indicating you don't have access on their error page.

**Comment by manishmittalm** [comment]
Thanks, Jeff, can you please guide how can I access now.

**Comment by jeff-matthews** [comment]
If you create a pull request for this repo, you'll automatically receive an invitation to join the maintainers team, which is part of the Magento org. After accepting the invitation, you should be able to see these links.

**Comment by shrielenee** [comment]
Did that work for you @manishmittalm? If so, I'll close this issue! Thanks for taking the time to submit it. 🏆

**Comment by bhargavmehta** [comment]
Hello @shrielenee can we replace the maintainers link with https://magento.com/magento-contributors#/community-maintainers which is a better option and maintained on Magento Website?
If so I'll create a PR for the same.

Thank you

**Comment by manishmittalm** [comment]
Hello @jeff-matthews Can you please share a link of the repo to create a pull request. Thanks for the help and one more suggestion if we have to make a pull request for this repo then that should be mention therein guidance so that will be helpful to other users.

**Comment by manishmittalm** [comment]
> Did that work for you @manishmittalm? If so, I'll close this issue! Thanks for taking the time to submit it.

Thanks @shrielenee but still facing issue.

**Comment by jeff-matthews** [comment]
@manishmittalm, it's _this_ repo: https://github.com/magento/devdocs

**Comment by shrielenee** [comment]
@bhargavmehta You want to change the Maintainers link in the left sidebar on this page https://devdocs.magento.com/guides/v2.2/contributor-guide/maintainers.html to https://magento.com/magento-contributors#/community-maintainers ?

The way it's currently linked is appropriate, as the page we send users to includes the link to the Contributors page you mentioned, along with a wealth of other relevant info. I'd like to leave it as-is for now. Thanks!

**Comment by bhargavmehta** [comment]
Hello @shrielenee ,

I was talking of the line "To deploy, Community Maintainers, a Magento EngCom Team member, or contributor under the existing Pull Request enters the following command as a comment to the pull request:" in the attached screenshot. But I guess its correct right now and dont need any change. As that page will appear after someone does a PR.
Thank you
![image](https://user-images.githubusercontent.com/7995219/46622201-50972780-cb47-11e8-9f07-5b92811180b3.png)

**Comment by shrielenee** [comment]
Hey @manishmittalm - I'm going to go ahead and close this issue, as it seems you now have a better idea where to create a PR for this! Thanks so much for taking the time to report an issue!
