### ISSUE TITLE
Feedback on page: /guides/v2.2/frontend-dev-guide/templates/template-email.html

### ISSUE THREAD

**Issue by camplusplus** [magento/devdocs#3018]
# General issue
No List of Vars
## Description:
There are no full list of possible vars like {{var store_hours}} ...

**Comment by michizhou** [comment]
Hi @camplusplus just wanted you to know that I can take this issue. #SQUASHTOBERFEST

**Comment by michizhou** [comment]
@camplusplus Just wanted to let you know that I created a PR that will address this issue. Let me know if you need me to make any more changes to the documentation. Thanks!
