### ISSUE TITLE
Add a note about order of properties in theme-images.md file

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#3072]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-images.html (all versions)

## Description

Create a note on the theme-images.md file that all image properties, including width, height, constraint, aspect_ratio, frame, etc., used in etc/view.xml should be used in listed order to prevent a frontend error ("This element is not expected.")

## Possible solutions

Add note similar to... "All image properties used in `etc/view.xml` should be listed in the order shown here to prevent a "This element is not expected." frontend error."

## Additional information

Reported via Hotjar on DevDocs site

**Comment by bhargavmehta** [comment]
Hello @shrielenee ,

Was thinking to add just before the For example line in the attached screenshot. Do let me know your thoughts if agreed will create a PR for the same.

![image](https://user-images.githubusercontent.com/7995219/46782912-b6510280-cd45-11e8-878b-d5019636e6ba.png)


Thank you
