### ISSUE TITLE
Missing page for Form Component in Magento 2.2 when switching from Magento 2.0

### ISSUE THREAD

**Issue by diazwatson** [magento/devdocs#3080]
# Bug report

## Description

Wrong redirection in Component Form page from 2.0 to 2.2

### Steps to reproduce

1. Go to https://devdocs.magento.com/guides/v2.0/ui-components/ui-form.html
2. In the Magento version dropdown at the top of the page, select Magento 2.2

## Expected result

You should be redirected to 
https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-form.html

Instead, the dropdown redirects you to 
https://devdocs.magento.com/guides/v2.2/ui-components/ui-form.html and this page does not exists.

## Possible solutions

- Fix the link in the dropdown to redirect to
https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-form.html
- Create a redirect 
from 
https://devdocs.magento.com/guides/v2.2/ui-components/ui-form.html  
to
https://devdocs.magento.com/guides/v2.2/ui_comp_guide/components/ui-form.html

Like it seems to be done when you try to switch from Magento 2.1 to Magento 2,2 
## Additional information
No additional information.

**Comment by diazwatson** [comment]
I just cloned the repo and after install the project using `bundle exec jekyll serve --incremental` I can see the following:
```
[2018-10-11 14:39:19] ERROR `/guides/v2.2/ui-components/ui-form.html' not found.
```
I would be more than happy to fix it if somebody point me in the right direction.

**Comment by jeff-matthews** [comment]
This also affects the 2.3 topic. Try switching from 2.0 to 2.3; you get the same 404.

Yes, I think we need to create redirects in the 2.2 and 2.3 files. For example:

In **guides/v2.2/ui_comp_guide/components/ui-form.md**, add the following parameter to the YAML metadata at the top of the file:
>redirect_from: /guides/v2.2/ui-components/ui-form.html

In **guides/v2.3/ui_comp_guide/components/ui-form.md**, add the following parameter to the YAML metadata at the top of the file:
>redirect_from: /guides/v2.3/ui-components/ui-form.html

**Comment by diazwatson** [comment]
is it not better to update the links in 
```
_site/guides/v2.0/ui-components/ui-form.html
```
?
That way we could remove the following errors:
```
[2018-10-12 09:53:33] ERROR `/guides/v2.2/ui-components/ui-form.html' not found.
```

**Comment by jeff-matthews** [comment]
It's not quite that simple. There are no links in the topic itself. The version switcher automatically generates links at build time.

**Comment by diazwatson** [comment]
Ok,
One more thing, is it normal that any change in 
```
guides/v2.2/ui_comp_guide/components/ui-form.md
```
gets automatically replicated in 
```
guides/v2.3/ui_comp_guide/components/ui-form.md
```
and viceversa

**Comment by jeff-matthews** [comment]
Yes, that's normal because (in this case) 2.2 is symlinked to 2.3. 

We use symlinking to simplify versioning. If there is no difference between versions of a file, we'll create a symlink from the earlier version to the later version (e.g., 2.1 --> 2.2) instead of duplicating the file. That means we only have to update a single file instead of two.

Now, when a file is unique between versions, we break the symlink and create a new file for that version. In that case, we must manually update both files if a change applies to both.

**Comment by diazwatson** [comment]
Thanks @jeff-matthews
