### ISSUE TITLE
add file attributes to product

### ISSUE THREAD

**Issue by myselfgaurav** [magento/devdocs#3082]
i want to create file type attributes, where i can add pds,doc to product

**Comment by bhargavmehta** [comment]
Hello @myselfgaurav ,

There is no possible way to create file type attributes right now by using default Magento. You will need to do customizations or use an extension.

For your reference please go through
https://magento.stackexchange.com/questions/140347/show-value-of-product-attribute-of-type-file-in-magento2-backend

Thank you
