### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by itsazzad** [magento/devdocs#3086]
# Bug report

## Description

Page Not Found

### Steps to reproduce

https://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-over.html

## Expected result

DevBox documentation

**Comment by jeff-matthews** [comment]
@itsazzad, where did you find that link?

**Comment by itsazzad** [comment]
https://github.com/magento/magento2devbox-web
Magento DevBox Beta – Update in Progress, Check Back Soon: https://magento.com/tech-resources/download

**Comment by jeff-matthews** [comment]
Thanks for letting us know. This isn't actually a devdocs issue since development of devbox has been suspended. We removed all devbox topics from devdocs as a result. The devbox README should be updated.

**Comment by itsazzad** [comment]
Should we use devbox or not?

**Comment by jeff-matthews** [comment]
No, I don't recommend using devbox.
