### ISSUE TITLE
MSI inventory API and tech overview

### ISSUE THREAD

**Issue by lorikrell** [magento/devdocs#3112]
# Community engineering issue

Content for MSI

Type of Doc:
- [X] New topic
- [ ] Topic Update, Devdoc link:
- [ ] Other

Magento 2 GitHub Issue: No GH issue associated

Magento 2 GitHub PR: https://github.com/magento/magento2ce/pull/3263

Magento 2 version:
- [ ] 2.1.X
- [ ] 2.2.X
- [X] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface?
- [ ] New software requirements?
- [ ] New REST endpoints or updated GraphQL query syntax?
- [ ] New command line option?

## Content

Need a new page located here: https://devdocs.magento.com/guides/v2.3/rest/modules/inventory/inventory.html

- The page does not exist yet. It should give a general (or deep) introduction to Inventory Management API changes. 
- Content should specify with MSI  `CatalogInventory` module and all associated APIs are deprecated. 
- Information can be leveraged from https://github.com/magento-engcom/msi/wiki/Technical-Vision.-Catalog-Inventory
- Lori can provide updated graphics as needed. 

## Additional information

We need to keep the link exact. It is used/linked in API docblocks and deprecation messages. The deprecated APIs will point to replacement APIs when possible. If a single API is not possible to reference, the deprecation message will point to this page.

Another conversation to check on this: https://magento.slack.com/archives/C9XSHSBHU/p1539691832000100

Ask Lori for more info.

**Comment by keharper** [comment]
Closed via #3139
