### ISSUE TITLE
Add best practices to Community Resources

### ISSUE THREAD

**Issue by lorikrell** [magento/devdocs#3117]
# New topic request

## Description

Add best/leading practices or common solutions section to DevDocs from Community. 

## Content checklist

Add content into multiple pages to https://devdocs.magento.com/community/resources/index.html
Add navigation for new pages
Add links and info for existing best practices to the pages
Possible rename discussions may affect multiple sections: best practices vs leading practices vs common solutions

[ ] The topic provides an explanation of how ____ works.
[ ] The topic provides steps for ____.
[ ] The topic contains code samples that shows ____.
[X] Other (please specify): Add best practices section

## Additional information/resources

Open to info/advice/and additions.

**Comment by brentwpeterson** [comment]
@lorikrell am I able to add navigation?

**Comment by lorikrell** [comment]
Hey there! I added a parent page with linked info, side navigation, etc in this PR: https://github.com/magento/devdocs/pull/3121

When this PR is merged, it will add navigation with commented out example of how to add new pages (_data/toc/community.yml file). We can also handle all the navigation if confusing to submitted PRs.
Anyone can add new contribution pages to /community/resources. Just submit PRs! The parent page is just an intro with links to current best practices, leading practices, common solutions, etc found when searching current DevDocs. 

If anyone wants to start PRs before this is merged, feel free! I am very happy to help out on this project!

**Comment by lorikrell** [comment]
Added a section for community contributed best practices: https://devdocs.magento.com/community/resources/best-practices.html

Anyone that wants to add content, look over the contributing section. Content will be added to this page, and to the navigation through PRs. If you would like help, feel free to contact me and the DevDocs Slack in EngCom!
