### ISSUE TITLE
Ensure noted file paths are correct per applicable repo in Javascript resources for Magento page

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#3118]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js-resources.html

## Description

Ensure that the paths in the Accessing JS resources section are correct.

Per Hotjar customer feedback:  

> I think this page has errors in the example paths; e.g. app/code/deisgn shouldn't this be app/design or app/code? also <locale>/Magento_Configurable/ should be <locale>/Magento_ConfigurableProduct/ ... 

## Possible solutions

1. Check the applicable repo and ensure noted paths are correct (potentially also check all paths on page).
2. Update page to include correct paths (check all versions to ensure correctness).
3. Notify me (@shrielenee) so I may contact the customer and let them know this has been remedied.

## Additional information

Hotjar ID 16637016, response #3827

**Comment by bhargavmehta** [comment]
Hello @shrielenee ,
I checked the page found few things. 
https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js-resources.html
1) Structure of the document is broken at some places.
2) app/code/design is nowhere on the page.
3) Magento_Configurable path needs to be changed.

If assigned would like to take up the issue and fix it up.

Thank you

**Comment by shrielenee** [comment]
No problem @bhargavmehta - You are free to work on it! Please create a PR for this work. Mention that it "Fixes #3118" and when your PR is merged this issue will be closed. Let me know if you need anything else!

**Comment by shrielenee** [comment]
Hey @bhargavmehta - Are you planning to work on this? Please let us know! Thanks.

**Comment by bhargavmehta** [comment]
Hey @shrielenee ,

Sorry for late reply. Yes, I will be working on the ticket this weekend. 

Thank you
