### ISSUE TITLE
setup_version is optional starting from Magento 2.3

### ISSUE THREAD

**Issue by buskamuza** [magento/devdocs#3126]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/create_component.html#module-xml

## Description

> Here name is the name of your component, and setup_version is your module’s database schema version. Both of these attributes are required.

"Both of these attributes are required." is incorrect for Magento 2.3+. While "name" is still required, "setup_version" is optional, and should be omitted if declarative schema approach is used.

## Additional information

Background: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/

**Comment by keharper** [comment]
Thanks for your offer @arshadkazmi42, but this is more complicated than it looks. I've got it.

**Comment by keharper** [comment]
Closed via #3153
