### ISSUE TITLE
Old Dev Docs URLs in Search Engine

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#315]
Today I was searching for some Magento 2 information -- and Google returned a result with the following URL

http://devdocs.magento.com/guides/v1.0/config-guide/config/plugins.html

However, this URL returned a 404.  If the old versions of docs aren't going to stick around, there old URLs should redirect (`301`, permanent) to the current equivalent document, or an appropriate page if the old URLs are going away.

**Comment by xcomSteveJohnson** [comment]
Suggestion for how to do it?

**Comment by steverobbins** [comment]
You need to create the page at that location but specify the redirect: https://help.github.com/articles/redirects-on-github-pages/

**Comment by xcomSteveJohnson** [comment]
Is there a simpler way, that would redirect everything from guides/v1.0 to guides/v2.0?

And how long before search engines change those URLs on their own?

**Comment by steverobbins** [comment]
GitHub pages doesn't allow `.htaccess` files so you can't perform blanket redirects using that method.  I'm not sure if there's another option.

Aren't there still [valid pages](https://github.com/magento/devdocs/tree/develop/guides/v1.0) in `v1.0`?

**Comment by xcomSteveJohnson** [comment]
Ironically the only pages left in 1.0 are some temporary Meta tag redirects to cover URLs referenced by code. Those will go away in the next few weeks.

We're investigating. Thanks for bringing it up.

**Comment by astorm** [comment]
It sounds like you're willing let Google realize the pages are 404ing, and to automatically slurp up the new pages.  This might just be frozen caveman web developer talking -- but with that as standard policy aren't you sacrificing any SEO reputation the older URLs had built up?  Every time you do a release of the docs you'll end up needing to build the search engine rep of that page back up.

**Comment by xcomSteveJohnson** [comment]
Sometimes a question is just a question <g>. We're not SEO experts or web designers. We'll find a solution.

**Comment by alankent** [comment]
I think this is partly a symptom of trying to get docs published quickly. We know the infrastructure needs more work. Release early, release often - and get bitten occasionally as well sorry.

**Comment by xcomSteveJohnson** [comment]
@astorm http://devdocs.magento.com/guides/v1.0/config-guide/config/plugins.html

That has not been a valid URL in a very long time, that might go back to Dev Beta in December 2014. However, everything we renamed on 7/21 is now being redirected.

**Comment by xcomSteveJohnson** [comment]
Thanks to assistance from our excellent CICD team, all guides/v1.0 links now are being redirected to guides/v2.0.

Please check and report any issues.

**Comment by jfrontain** [comment]
Great!

**Comment by xcomSteveJohnson** [comment]
@astorm We'll fix this one today: http://devdocs.magento.com/guides/v1.0/config-guide/config/plugins.html

Amazing it's still around in searchengineland.

**Comment by xcomSteveJohnson** [comment]
Everything I know of is fixed now. Closing. Please reopen if you find other 404s.
