### ISSUE TITLE
Add information to "Add a new input form to checkout" topic

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#3152]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.2/howdoi/checkout/checkout_form.html

## Description

We received feedback about page via the Hotjar widget on DevDocs. Upon following up via email I got the following information and a request for topic clarity.

> Step 1:
The guide gives an example JS file to start with, but doesn't name this example file, which makes it difficult to follow along later in the guide.

> Step 2:
Same problem, a file example is given, down to what directory it should go in, but a file name isn't given, making it difficult to follow.

> Suddenly the guide suggests clearing static files, but at this stage nothing would show up on the front-end anyway. It could make someone who doesn't know better think that somehow these files are automatically found (as Magento magically finds files in other scenarios).

> Step 3:
Describes sort of how to figure out where to put your new form field, then gives an XML example, but then leaves out a pretty critical part! It just glosses over what kind of data should go in <-- your form declaration here -->. If the javascript file in step 1 was given a name, it could have been used as an example here.

> And then we get the option of creating an XML layout or PHP layout, depending on whether or not you're creating a static form or a dynamic form. And my understanding is that XML only works for static forms, but you can use PHP for static or dynamic forms. Not clear in this documentation. So the first example is XML for a static form. The XML code does reference the JS and HTML examples from steps 1 and 2, but thats hardly clear. Blink and you miss it. Then there are some notes sprinkled into the XML comments of the code example, which gives an explanation for 2 or 3 of the attributes we're setting.

> Then it jumps to the PHP example, giving no explanations at all, and doesn't even reference the JS or HTML written earlier. So that PHP code at the end is just kind of sitting there not providing much value. And we're still left with so many questions. "customScope" is described in an XML comment as being used to group elements; but what is dataScope? Whats the relationship between "component", "template" and "elementTmpl"? I have figured out some of this on my own, but it would be pretty valuable information here.

**Comment by lorikrell** [comment]
Lucas added content for all steps and info, except for "Create a more clear section for the "dynamic" and "static" ways" which can be completed in another PR.
