### ISSUE TITLE
Feedback on page: /guides/v2.2/install-gde/prereq/prereq_updater.html

### ISSUE THREAD

**Issue by ricalonso58** [magento/devdocs#3178]
# General issue
When disabling a module the Readiness Check fails on several levels.  One of which is that the updater is missing. I clicked the link provided which took me to this page.

The link to the github repository gives a 404 page.

I searched on git-hub but there is no available repository for the updater.

## Description:

When I try to clone from github....

git clone git@github.com:magento/magento2-updater.git update
Cloning into 'update'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

## Possible solutions:

Per response from Architects:
Need to update this page to recommend install updater from composer `composer create-project magento/updater update --repository https://repo.magento.com` and make the repo public, so community can contribute.
Currently it is private.

**Comment by shrielenee** [comment]
The linked repo is private. @buskamuza Was this repo always private?

**Comment by dshevtsov** [comment]
@buskamuza, see the related issues for more context: #2962, #2660

**Comment by shrielenee** [comment]
Hey @buskamuza @ricalonso58 @dshevtsov --- It looks like we need to delete this page. Please confirm ASAP. Thanks!

**Comment by ricalonso58** [comment]
OK to delete.

**Comment by dshevtsov** [comment]
@melnikovi @buskamuza what is the appropriate scenario for the described issue?

**Comment by melnikovi** [comment]
Need to update this page to recommend install updater from composer `composer create-project magento/updater update --repository https://repo.magento.com` and make the repo public, so community can contribute.

**Comment by buskamuza** [comment]
@dshevtsov , Updater can be installed via Composer. But for contributions, the repo should be made public.

**Comment by dshevtsov** [comment]
Links to https://devdocs.magento.com/guides/v2.3/install-gde/prereq/prereq_updater.html will be replaced with links to https://devdocs.magento.com/guides/v2.3/comp-mgr/updater/update-updater.html (same for 2.2).
The topic itself will be removed.
