### ISSUE TITLE
Update REST bulk API examples

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#3187]
# Community engineering issue

Type of Doc:
- [ ] New topic
- [x] Topic Update, Devdoc link:
- [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/async-import/issues/23

Magento 2 GitHub PR: 

Magento 2 version:
- [ ] 2.1.X
- [ ] 2.2.X
- [x] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface?
- [ ] New software requirements?
- [x] New REST endpoints or updated GraphQL query syntax?
- [ ] New command line option?

## Content

Per [async-import issue 23](https://github.com/magento/async-import/issues/23)m the `data_hash` parameter will be removed from bulk responses. At minimum, update https://devdocs.magento.com/guides/v2.3/rest/bulk-endpoints.html

Also check whether this topic is affected:
https://devdocs.magento.com/guides/v2.3/rest/asynchronous-web-endpoints.html

**Comment by dobooth** [comment]
Hey @nuzil, is this just a matter of removing the data-hash from the code example?
