### ISSUE TITLE
Install documentation is a broken link

### ISSUE THREAD

**Issue by nickolasnikolic** [magento/devdocs#3190]
https://devdocs.magento.com/guides/v2.2/howdoi/install/install-topics.html?_ga=2.29235647.2030894075.1540600117-914559671.1540600117

is a broken link

**Comment by shrielenee** [comment]
@nickolasnikolic - From where did you click or find this link? Also, it's a requirement when creating an issue to completed fill out the provided form with as much information as possible. This allows us to quickly assess and take care of the issue.

**Comment by lorikrell** [comment]
The link may be from Merchant docs. If found a link in these two versions https://docs.magento.com/m2/2.2/ce/user_guide/magento/installation.html and https://docs.magento.com/m2/2.2/ee/user_guide/magento/installation.html and https://docs.magento.com/m2/2.2/b2b/user_guide/magento/installation.html with different Google Analytics tag that come up with a 404 on devdocs. I'll get a ticket in for fixing them internal Merchant guides. 

Would be good to know where @nickolasnikolic clicked from too. Thanks!

**Comment by shrielenee** [comment]
Hey @lorikrell - did you create a ticket for this? If so, I'll add the tracking label. Thanks!

**Comment by lorikrell** [comment]
Yes I have an internal ticket - MAGEDOC-3225

**Comment by lorikrell** [comment]
This is a Merchant Docs issue. I am tracking and completing the work using an internal ticket. Updates will be pushed November 6, 2018 to production for the User Guides. Thank you for reporting!
