### ISSUE TITLE
Prioritizing Plugins section of Plugins (Interceptors) is not clear

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#3200]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html

## Description

Section "Prioritizing plugins" is not clear enough:
* I have read "During each plugin execution, Magento executes the current plugin’s before method." But what if there is no before handlers? What will happen? Running observed method? -- I hope NO! Running `around` handler of current plugin? -- Probably yes, but it is not clear. ”
* What will happen if the plugin with low sortOrder has no `before` handler? Will it be ignored? ”
* It seems that the phrase "Following the execution of the observed method, Magento will execute plugins from greatest to lowest sortOrder." should sounds as "Following the execution of the observed method, Magento will execute `after` plugins from greatest to lowest sortOrder." I think this formulation is more accurate. Isn't it ? ”

## Additional information

This is feedback received from [Hotjar ID 17209224](https://insights.hotjar.com/sites/806243/feedback/responses/38638?frid=17209224).

**Comment by dobooth** [comment]
https://github.com/magento/devdocs/issues/2784

**Comment by atwixfirster** [comment]
> I have read "During each plugin execution, Magento executes the current plugin’s before method." But what if there is no before handlers? What will happen? Running observed method? -- I hope NO! Running around handler of current plugin? -- Probably yes, but it is not clear. ”

> But what if there is no before handlers?

Nothing. 

> What will happen? 

Magento will check if plugin has the `around` method. If `around` does not exist in the plugin then Magento execute a parent(native) method.


CC: @shrielenee

**Comment by atwixfirster** [comment]
> What will happen if the plugin with low sortOrder has no `before` handler? Will it be ignored?

Will be skipped. Magento verifies each plugin for the `before`, `around` and `after` methods availability.

**Comment by atwixfirster** [comment]
> It seems that the phrase "Following the execution of the observed method, Magento will execute plugins from greatest to lowest sortOrder." should sounds as "Following the execution of the observed method, Magento will execute after plugins from greatest to lowest sortOrder." I think this formulation is more accurate. Isn't it ? ”

@shrielenee , let me please clarify how does it work.

For example, we have some class with `execute` method.

For this method we have 2 plugins:
- `Plugin A` (sortOrder = 10)
  - `aroundExecute` method
  - `afterExecute` method
- `Plugin B` (sortOrder = 20)
  - `beforeExecute` method
  - `aroundExecute` method
  - `afterExecute` method

**Execution queue:**
1. `Plugin A`::`aroundExecute` (sortOrder=10)
2. `Plugin B`::`beforeExecute` (sortOrder=20)
3. `Plugin B`::`aroundExecute` (sortOrder=20)
4. `execute` method of native class
5. `Plugin B`::`afterExecute` (sortOrder=20)
6. `Plugin A`::`afterExecute` (sortOrder=10)

**Comment by atwixfirster** [comment]
Added some editorial fixes that will help to understand the explanations.

https://github.com/magento/devdocs/pull/5205
