### ISSUE TITLE
Feedback on page: /guides/v2.3/config-guide/multi-site/ms_nginx.html

### ISSUE THREAD

**Issue by dpatil-magento** [magento/devdocs#3203]
I recently setup Multiple website on enterprise env. Some observations below -
1. Under /etc/nginx/ there is no directory called "sites-available" but we have "conf.d"
2. Also there is no "Sites-enabled" directory, we need to use conf.d only. so the command links needs to be updated.

**Comment by jeff-matthews** [comment]
Thanks for reporting these issues @dpatil-magento. 

The `sites-available` and `sites-enabled` directories are considered a best practice, especially for hosting multiple sites on a single server. These directories are created by default when you install nginx or apache. If you don't have them, it probably means that you or your server admin decided to manage your virtual host configuration using `conf.d` instead, which is a valid alternative, but not a best practice.
