### ISSUE TITLE
Page missing Next Link - https://devdocs.magento.com/guides/v2.1/config-guide/varnish/config-varnish.html

### ISSUE THREAD

**Issue by caseybecking** [magento/devdocs#3213]
# Bug report

### Steps to reproduce

1. Goto - https://devdocs.magento.com/guides/v2.1/config-guide/varnish/config-varnish.html 
2. scroll all the way down to Install Varnish

## Expected result

Expecting to be directed to https://devdocs.magento.com/guides/v2.1/config-guide/varnish/config-varnish-install.html

## Possible solutions

Fix the link issue in the markdown page, I will submit a PR for it.
## Additional information

None

**Comment by jeff-matthews** [comment]
Fixed via #3214
