### ISSUE TITLE
Javascript dev guide link doesn't work

### ISSUE THREAD

**Issue by danslo** [magento/devdocs#322]
- Go to http://devdocs.magento.com/
- Click on *JAVASCRIPT DEVELOPER GUIDE*
- It goes to this page which gives a 404: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/bk-javascript-dev-guide.html

Seems to exist just fine as markdown:  https://github.com/magento/devdocs/blob/develop/guides/v2.0/javascript-dev-guide/bk-javascript-dev-guide.md

**Comment by almarchenko** [comment]
Thanks! Will fix in a couple of hours!

**Comment by xcomSteveJohnson** [comment]
<egg on face> @danslo Fixed now.

**Comment by danslo** [comment]
Thanks! :+1:
