### ISSUE TITLE
Distinction Between Code Generation and Compiled Mode

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#325]
Hey all -- just a few suggestions here based on some limited real world explorations.  I'm not sure what "the right" answer is, but the current documentation about these subjects is/are a little confusing to an outsider.

This is regarding the documentation on "single-tenant" and "multi-tenant" compilation
    http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler-single.html
    http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler-multi.html
    
Each of these pages indicate (or imply heavily) that Magento 2 compilation is the the same thing as code generation     

> This section discusses the basics of code compilation (which is also referred to as code generation).

However, I'm not sure that's 100% true -- compilation seems to be something more.

While running either of the compiler commands **will** generate class files in `var/generation`, compiling also creates a number of `.ser` files in `var/di/` (in this context `.ser` appears to be PHP's internal `serialization` format).  

The purpose of these files isn't clear.

Also, if these `.ser` files are present, the framework seems to run in some sort of "Compiled" mode 

    #File: /lib/internal/Magento/Framework/App/EnvironmentFactory.php
    private function getMode()
    {
        if (file_exists(ConfigLoader\Compiled::getFilePath(Area::AREA_GLOBAL))) {
            return Compiled::MODE;
        }

        return Developer::MODE;
    }
    
I found this out because removing the files in `var/generation/` while in compiled mode appears to break the system.  I needed to remove the `.ser` files as well to restore normal functionality.  

If possible, it'd be great if the docs could explain how "compiled" code goes above and beyond simply pre-generating all generated code.  This information is going to be of particular importance as developers start rolling out Magento 2 systems into production.

**Comment by tanberry** [comment]
Thanks so much Alan! Code generation is one of the topics that we identified to explain [better] in our PHP Developers Guide (currently titled Extension Developers Guide). Both conceptually and details such as you point out above; files created, what they do, how to treat them, etc. @xcomSteveJohnson can handle the CLI docs, and @tdobbs, can you capture this info in your draft topic on code generation? 
Thanks again, Alan, we will get back with something for you to review.

**Comment by dkvashninbay** [comment]
Hi Alan,

I'm sure that the documentation will be updated soon.

Currently SE compilation process consists of several steps (not ordered):
* Application code generation (Factories, Proxies, etc.)
* Area configuration aggregation (I.e. *.ser files are optimized DI
configurations per area, are needed for DI container to construct objects)
* Interceptors generation (optimized code generation of interceptors)
* Interception cache generation (Aggregates plugin/interception
configuration in optimized way and puts it into Magento cache)
* Repositories code generation (same sense as p.1 - it generates code for
API)
* Service data attributes generation (Generates extension classes for data
objects)

You can find all major operations in
\Magento\Setup\Module\Di\App\Task\Operation namespace

**Comment by tdobbs** [comment]
@astorm, we've added some information on code generation at http://devdocs.magento.com/guides/v2.0/extension-dev-guide/code-generation.html. Let us know if this addresses your issues with this topic--and especially let us know where it doesn't.

**Comment by astorm** [comment]
Solid start -- I like it!  The only thing i'd suggest is a better introduction or easing into "compiling" code.  The anyone with a background in programming, the work "compile" usually means converting something like C code into executable machine code, or transforming a program written in one language into another.   In Magento's unique world, "compiling" really means 

- Generating any class files
- Performing optimization and creating serialized cache files to improve performance, etc. (those .ser) files.

Folks already in the Magento eco-system should be able to suss that difference out after reading through this page -- but folks new to Magento may be left scratching their heads.  Submitted a pull request with some initial thoughts, (not heavily invested in the specifics -- feel free to run with it)

https://github.com/magento/devdocs/pull/384

**Comment by xcomSteveJohnson** [comment]
I think we made the updates you suggest. Please reopen if that's not the case.
