### ISSUE TITLE
Small Padding to .page-intro

### ISSUE THREAD

**Issue by tegansnyder** [magento/devdocs#326]
I suggest adding a small amount of padding (think a 14px padding-left) on the `.page-intro` class would make the headings look better.

Before:
![image](https://cloud.githubusercontent.com/assets/1200195/9183524/3a69be70-3f75-11e5-99eb-e6c649722335.png)

After:
<img width="1258" alt="installation_overview" src="https://cloud.githubusercontent.com/assets/1200195/9183541/529e46b4-3f75-11e5-8e88-650ce78482e7.png">

Thoughts?

**Comment by tanberry** [comment]
We agree! What browser and version are you viewing the docs in, please? We have identified several "site improvements" that we need to make, and padding is one... but it seems only certain browsers have the crowded left shown in your first screenshot above.
Thanks for bringing it up, let us know your browser and version please, and we hope to get it resolved soon! Please keep sending any and all feedback; we want to hear from our community about ways to improve our docs.

**Comment by tegansnyder** [comment]
Thanks @tanberry:

Chrome - Version 43.0.2357.134 (64-bit) - OSX

**Comment by tanberry** [comment]
Great, thanks for that info. @tdobbs can you make sure that this version is on your test list?

**Comment by tdobbs** [comment]
I'm testing Chrome OS X Version 44.0.2403.125 (64-bit) or greater. Will that fit the bill?

**Comment by tdobbs** [comment]
@tegansnyder, we've updated the styling a little on devdocs.magento.com, including adding a little padding to the title when the browser window collapses. Thanks for your help!
