### ISSUE TITLE
Architecture layers names are switched the whole time

### ISSUE THREAD

**Issue by CompactCodeEU** [magento/devdocs#3295]
# Topic clarification/correction request

Consistent naming of the layers is something that will help understanding this topic

## Topic Link

https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/present_layer.html
https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/service_layer.html

## Description

Initially you have 4 layers : 
- Presentation layer
- Service layer
- Domain layer
- Persistence layer

So far so good!

But in Present layer it seems that there is a 5th layer Product layers and Domain layer is now also Business logic layer. This term is used before it is explained that it is the same thing later on.

In the Service layer you suddenly have the model layer which i think is also the domain layer since it has domain logic. So now we have 3 names used for the same layer. 

What the product layer is is still to be guessed.
Since it is talking about underlying product layers we can guess that this is the Service layer even though it does not make any sense to call it a product layer

## Possible solutions

Keep the same terminology that you are explaining.

## Additional information

Do not get me wrong here please. I love the devdocs but i feel this should be improved on

**Comment by lorikrell** [comment]
Thank you for your feedback on the Architecture Guide, @CompactCodeEU . The entire guide could use review, revision, etc. As we investigate writer support, we are also open to any contributor that would like to help with this issue!

**Comment by CompactCodeEU** [comment]
When we use and see errors in the documentation as a company we would love to help out and improve it based on our experience even though we can not be responsible for grammar errors and such.

**Comment by dobooth** [comment]
Thanks CCEU. We are working on a redo of the Architecture Guide at the moment and will bring in the clarifications you are asking for here.

**Comment by dobooth** [comment]
Fixed.
