### ISSUE TITLE
Required , cannot , should not , may not ,...

### ISSUE THREAD

**Issue by CompactCodeEU** [magento/devdocs#3298]
# Topic clarification/correction request

As the usage of words are important within PSR PHP guidelines they are also important in documentation.
I will give some examples

## Topic Link

https://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/modules/mod_relationships.html
https://devdocs.magento.com/guides/v2.2/extension-dev-guide/intro/developers_roadmap.html

## Description

The usage of words does not meet the actual situation.

## Possible solutions

In the mod relationships under "A uses B, C customizes B" the text says : 

> In a scenario where module A uses module B and module C customizes module B, the customizations in module C cannot break the API of module B so that module A still functions properly in the face of these customizations.

This should be

> In a scenario where module A uses module B and module C customizes module B, the customizations in module C **must not** break the API of module B so that module A still functions properly in the face of these customizations.

It can break the API of module B if coded wrong but it must not do that.

In the developer roadmap page it says 

> Minimum required elements:

But those are not all minimum required elements. If you do not have language packages you do not use the **language.xml** and same is for **composer.json**

**Comment by CompactCodeEU** [comment]
composer.json is not a required file. It is a recommended file.  It even says so on https://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/composer-integration.html

**Comment by CompactCodeEU** [comment]
https://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/required-configuration-files.html

Again composer.json is NOT required. It is recommended but not required. Lacking that fille makes it that composer can not manage that module and it needs to be done manually

**Comment by shrielenee** [comment]
So, @CompactCodeEU, are you suggesting that declaring component dependencies in composer.json is optional?

**Comment by CompactCodeEU** [comment]
@shrielenee It is best practice and everybody should do it. But it is not required at all. I would even go as far that if the module does not have any dependencies the file is redundant when not installed provided via composer.

The thing here is clarity between terms. Required means that it will not work without it. Think about the exams how confusing it is.

If you want to have automatic dependency management and/or provide the module over composer that file is required to add that functionality but we can say the same about other functionalities. 

Required : 'officially compulsory, or otherwise considered essential; indispensable.'

So in our opinion this file does not belong between the required files but under 'recommended files'.

**Comment by dobooth** [comment]
Closing as fixed.
