### ISSUE TITLE
PDF Versions of the Devdocs should be made available

### ISSUE THREAD

**Issue by joshuaswarren** [magento/devdocs#330]
Creating from a discussion that started on Twitter: https://twitter.com/JoshuaSWarren/status/634727275452239872

Basically - a PDF version (either an on-the-fly PDF generation, or more likely, a pre-generated PDF that's refreshed periodically) of the devdocs would be great. It would allow the docs to be loaded onto ereaders, tablets, etc., and used in offline situations, or downloaded as a complete set before boarding a flight without wifi, etc. 

There was a suggestion on Twitter at https://twitter.com/knowj/status/634729093016199168 - "You could clone the repo and build using jekyll as a stop gap. PDF's would be nice as well."

This got me to thinking that maybe there's a way to use Jekyll + https://github.com/pdfkit/PDFKit to automatically generate these PDFs. It wouldn't be the prettiest layout, but it'd be a start.

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by tanberry** [comment]
Thanks, @ihor-sviziev and @joshuaswarren; we have long had an internal ticket to work on this, but we hear you and we're trying to move it up the queue. Thanks, keep the feedback coming!

**Comment by prahladyeri** [comment]
Its been almost an year, but no PDF version yet :cry:

**Comment by jcalcaben** [comment]
@prahladyeri we apologize for the delay. This issue is still on our radar, and we are still in the process of looking into and developing an appropriate automated solution for generating PDF versions of each documentation sections. Thank you for your patience!

**Comment by prahladyeri** [comment]
@jcalcaben No probs! You guys are doing a great job with creating Magento docs :+1:. Please let me know is there any way to contribute to your project.

**Comment by jcalcaben** [comment]
@prahladyeri we absolutely welcome any contributions you can provide! Small contributions such as simple content additions, editing, and correcting typos would be appreciated very much. 

Do you have a particular area of expertise in Magento? If so, consider writing a full topic and we will credit you on the page as a contributor!

To get started, take a look at our [Doc Contribution Guide](http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing_docs.html) and this [template page](https://github.com/magento/devdocs/blob/2.0/guides/v2.0/howdoi/howdoi_template.md) to help you get started.

**Comment by prahladyeri** [comment]
@jcalcaben I don't have any expertise yet! I'm still learning the basics of modules and theme development in M2. But once I'm finished, I'd like to contribute to documentation since its a great way to keep brushing up the knowledge in all areas of M2.

Thanks for the links.

**Comment by jeff-matthews** [comment]
There are no plans to make PDFs available.
