### ISSUE TITLE
Missing directories

### ISSUE THREAD

**Issue by CompactCodeEU** [magento/devdocs#3306]
# Topic clarification/correction request

This is missing addtional directories.

## Topic Link

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/module-file-structure.html

## Description

It states that additional directories are
Api: contains any PHP classes exposed to the API .
Console: contains CLI commands. For more info, see Add CLI commands.
i18n: contains localization files.
Plugin: contains any needed plug-ins.
view: contains view files, including static view files, design templates, email templates, and layout files.

But this are not all of them.
Observer , UI,Helper and CustomerData are important directories but not listed

**Comment by jcalcaben** [comment]
@CompactCodeEU can you provide descriptions for each of the additional directories you listed?
