### ISSUE TITLE
Feedback on page: /guides/v2.2/config-guide/config/config-create.html

### ISSUE THREAD

**Issue by benjamin2708** [magento/devdocs#3318]
# General issue

## Description:

The page says: 

> To extend an existing configuration type, you need only create a configuration file in your module .For example, to add an event observer, you create **app/etc/events.xml** and declare a new observer.

is that the correct place for a module event observer?

## Possible solutions:
change to module-dir/etc/events.xml ?

**Comment by shrielenee** [comment]
This issue fixed by #3348
