### ISSUE TITLE
Feedback on page: guides/v2.3/graphql/search-pagination.html

### ISSUE THREAD

**Issue by dani97** [magento/devdocs#3328]
Docs  for pagination functions before,after,first, last etc.

**Comment by keharper** [comment]
Hi, @dani97. we need a little more context about what kind of information you're looking for. We address pagination in the context of query results at https://devdocs.magento.com/guides/v2.3/graphql/search-pagination.html

**Comment by dani97** [comment]
Hi @keharper  I meant is there any implementations like first, last, before, after etc pagination functions  as there in https://graphql.org/learn/pagination/#pagination-and-edges

**Comment by keharper** [comment]
@dani97  I asked the GraphQL product manager if this type of pagination is on our roadmap, and unfortunately, it's not. All we've got for now are pagination attributes described on the page I linked to earlier. 

Thanks for asking.

**Comment by dani97** [comment]
Thanks @keharper . I have made a feature request for it :+1:
