### ISSUE TITLE
GraphQL: Add wishlist endpoint for 2.3.1 

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#3341]
# Community engineering issue

Type of Doc:
- [x] New topic
- [ ] Topic Update, Devdoc link:
- [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/graphql-ce/issues/43

Magento 2 GitHub PR: https://github.com/magento/graphql-ce/pull/223

Magento 2 version:
- [ ] 2.1.X
- [ ] 2.2.X
- [x] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface?
- [ ] New software requirements?
- [x] New REST endpoints or updated GraphQL query syntax?
- [ ] New command line option?

## Content

The `WishlistGraphQl` module currently defines one query, which returns the contents of a customer's wishlist. There are no mutations at this time,

**Comment by erikmarr** [comment]
test is located here:
https://github.com/magento/graphql-ce/blob/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Wishlist/WishlistTest.php
