### ISSUE TITLE
Feedback on page: /guides/v2.1/install-gde/install/sample-data.html

### ISSUE THREAD

**Issue by belbiy** [magento/devdocs#3357]
# General issue

## Description:

Sample data installation guides missing left navigation.

## Possible solutions:

Page `group` is set to `SampleData`, but no matching TOC exists in _data/toc/. Either create a new TOC, or change the group to `installation-guide`

## Additional information:

Search for group `SampleData` to find similar pages with the same issue.

**Comment by jeff-matthews** [comment]
Thanks for reporting @belbiy. The right solution in this case is to use the existing `installation-guide` TOC.
