### ISSUE TITLE
Configuration object topic

### ISSUE THREAD

**Issue by jcalcaben** [magento/devdocs#3361]
# New topic request

## Description

As a developer, I want to understand how to "use the classes described in Overview of Module Configuration to create a configuration object for a new system wide foo.xml. In addition to solving a specific problem (how do I add new global/frontend/adminhtml configuration file to the system) the existence of this article would also allow developers to infer how they could read from the other configuration files."

## Content checklist

- [ ] How to use the classes described in [Overview of Module Configuration](http://devdocs.magento.com/guides/v2.0/config-guide/config/config-files.html) to create a configuration object for a new system wide foo.xml
- [ ] How to read from the merged configuration tree
- [ ] How to use classes from the existing configuration class hierarchy to read custom configuration files

## Additional information/resources

StackExchange: http://magento.stackexchange.com/questions/82022/magento-2-how-to-read-from-configuration-tree

Related JIRA ticket: MAGEDOC-2582

Related GitHub issues: 
* #470
* #453

**Comment by diazwatson** [comment]
Hey guys I am looking into this issue could you please assign this to me?

**Comment by keharper** [comment]
@diazwatson It's yours.

**Comment by diazwatson** [comment]
Thanks @keharper  👍

**Comment by meker12** [comment]
@diazwatson  Are you still interested in working on this new topic?

**Comment by diazwatson** [comment]
Hi @meker12 apologies for the delay. I will submit a PR in the next few hours

**Comment by diazwatson** [comment]
I finally started working in this (apologies for the delay) and I have some doubts you guys maybe could give me a hand with?

1. do you guys think is better to use generic names like Vendor\ModuleName in the examples or refer to the core files?
Putting myself in the shoes of a developer that lands to this topic looking for answers that help his/her develops a module I can see benefits in both approaches.

2. [Module configuration files](https://devdocs.magento.com/guides/v2.3/config-guide/config/config-files.html) is a big section and therefore I think it would make more sense to create a separated topic for this. But at the same time I have not seen any other HowTo topic under [Configuration Guide](https://devdocs.magento.com/guides/v2.3/config-guide/bk-config-guide.html) so I am not sure what would be the best place to put this topic

Thanks in advance

**Comment by jcalcaben** [comment]
>do you guys think is better to use generic names like Vendor\ModuleName in the examples or refer to the core files?
Putting myself in the shoes of a developer that lands to this topic looking for answers that help his/her develops a module I can see benefits in both approaches.

I would go with the generic name as the primary example and then link/refer to core files for any additional information needed.

>Module configuration files is a big section and therefore I think it would make more sense to create a separated topic for this. But at the same time I have not seen any other HowTo topic under Configuration Guide so I am not sure what would be the best place to put this topic

I agree with creating a separate topic for this issue. My recommendation would be to put it under the *Module configuration files* topic.

**Comment by diazwatson** [comment]
Thanks @jcalcaben

**Comment by shrielenee** [comment]
Contributors! See the above closed PR for the work. Clean it up, submit, call it good!

**Comment by atwixfirster** [comment]
Let's try with this one - https://github.com/magento/devdocs/pull/6514. It's based on @diazwatson PR.
