### ISSUE TITLE
Feedback on page: /guides/v2.3/cloud/live/go-live-checklist.html

### ISSUE THREAD

**Issue by cgarrigues** [magento/devdocs#3388]
# General issue

This page seems to be a clone of the v2.1 documentation rather than the 2.2 documentation
## Description:

The information is out of date and incorrect

## Possible solutions:

Copy the documentation from the 2.2 version into place

**Comment by meker12** [comment]
Updated the v2.3 [Go Live Checklist](https://devdocs.magento.com/guides/v2.3/cloud/live/go-live-checklist.html)
