### ISSUE TITLE
Varnish documentation missing some points

### ISSUE THREAD

**Issue by aoldoni** [magento/devdocs#339]
Hi All,

Most of the doubts regarding FPC in general (and also Varnish now) are related to its usage and a page life-cycle in cache. I believe the current documentation is missing:
- How to purge data in Varnish from Magento admin.
- Which actions in the backend are likely to generate a purge, and to which URL.
- Static assets cached by Varnish: how to replace them?

Please let me know what are your thoughts on the above.

Thanks!

**Comment by xcomSteveJohnson** [comment]
I know we plan to add some info about purging in the next two weeks so watch for that.

I'll find out about your second point.

Not sure what you mean by "replace" in your third point; clarify?

**Comment by netstartergit** [comment]
Sure @xcomSteveJohnson , the final point is more around the supposition that if Varnish also cache CSS/JS, how one would purge those from Varnish once a deploy with new code happens.

Thanks!

**Comment by aoldoni** [comment]
Sure @xcomSteveJohnson , the final point is more around the supposition that if Varnish also cache CSS/JS, how one would purge those from Varnish once a deploy with new code happens.

Thanks!

**Comment by xcomSteveJohnson** [comment]
@aoldoni I added a new topic to start answering your questions: http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-use-varnish.html

Still need detail internally about static assets and I'm not sure about "to which URL" but will try to find out.

Please let us know what you think and leave this issue open.

**Comment by aoldoni** [comment]
The "to which URL" part attempts to clarify the following common questions:
- Once you save a product which URLs in the frontend get their FPC/Varnish cleared? Likely: All catalogue URLs this product belongs + the product page URL (this in all websites this product belongs to). Of course, this needs to be extrapolated to other actions in backend that triggers FPC cleaning.
- If someone is constantly saving products in series in the backend, it could be the case it is constantly refreshing pages it's not aware of, thus causing performance issues. This is a known misunderstanding in M1 thus why modules such as https://github.com/fbrnc/Aoe_AsyncCache gets build.

I might be mixing Varnish / FPC documentations here please let me know.

**Comment by xcomSteveJohnson** [comment]
@aoldoni Update. I think I now have all of this covered except for your last point about "constantly saving products". I'll bounce that off of an architect and see if it's something that should be documented. (And is it an edge case?)

I'll need to get the new topic reviewed then I think this issue can be closed. Keep you informed.

**Comment by xcomSteveJohnson** [comment]
@aoldoni I think the new topics should answer your questions:

http://devdocs.magento.com/guides/v2.0/config-guide/varnish/use-varnish-cache.html
http://devdocs.magento.com/guides/v2.0/config-guide/varnish/use-varnish-cache-how.html

If you agree, please close the issue. If not, please let us know what else you need.

**Comment by aoldoni** [comment]
Hi @xcomSteveJohnson,

Thanks, I hope you agree that now the documentation is more comprehensive. Very good.

I would still elaborate on the following:
- In this section http://devdocs.magento.com/guides/v2.0/config-guide/varnish/use-varnish-cache.html#use-varnish-magento-purge --> elaborate on this item as to be a comprehensive list instead of only a few examples.
- Elaborate a little bit more on the specifics of catalogue update: which URLs in the frontend get their FPC/Varnish cleared; what happen if someone is constantly saving products in series in the backend.

This is because my understanding is that the devdocs purpose is to document how Magento actually uses the technologies (e.g.: how it interacts with Varnish and when).

I understand that there's a lot of things to document and the above might not be priority, but this more detailed behaviour is something that developers would benefit from knowing.

Again, thanks!

**Comment by xcomSteveJohnson** [comment]
@aoldoni I got an answer from our architect which I'll summarize. This should result in another minor update in the next few days.

Magento doesn't use URLs to invalidate cache content; instead, we use tags. Varnish listens on / basically so to list URLs that are updated for any particular change doesn't make sense.

His reason: "any entity has many representations on the storefront (e.g. Product per website, product price per customer group/customer segment/ currency, etc). Such custom representation of the entity are defined on the view level, whichh is highly customizable. That is why it¹s hard to detect the URLs for some changed entity."

I'll make an update to this effect and let you know when it's ready.

**Comment by aoldoni** [comment]
OK, that's good. Thanks.

**Comment by xcomSteveJohnson** [comment]
Didn't want you to think we'd forgotten. I understand we're getting some detailed feedback from a partner we will be able to share at some point (not sure when). Will keep you updated.

**Comment by xcomSteveJohnson** [comment]
Created internal issue MAGEDOC-2502 to track.

**Comment by xcomSteveJohnson** [comment]
Unfortunately we're stuck on improving Varnish documentation. We need some help to discuss how to use Varnish with HTTPS and it isn't happening. I can't give you an ETA right now.

**Comment by sylink** [comment]
SSL with Varnish is more than possible, we do it with Apache/Nginx.

**Comment by jeff-matthews** [comment]
@aoldoni: I believe the updated [Varnish documentation](http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish.html) covers the missing points you originally reported. Let me know if we're still missing anything and I'll reopen.
