### ISSUE TITLE
Feedback on page: /guides/v2.2/ui_comp_guide/components/ui-insertlisting.html

### ISSUE THREAD

**Issue by shawnabramson** [magento/devdocs#3396]
# General issue

## Description:
I am using an insertListing component to insert a grid into a form. I want to pre-filter the grid by a value from the parent form. I've spent quite a bit of time studying insert-listing.js as well as core examples of using externalFilterMode, externalProvider, and some other options that go along with it. There is very little, if anything, online that describes the "Magento way" of doing this. I've gotten close but no cigar.

**Comment by dobooth** [comment]
Any action needed here as well, @serhiyzhovnir?

**Comment by dobooth** [comment]
There have been a lot of updates to the UI Component docs since this issue was filed. Please open a new issue if there are still gaps in the docs.
