### ISSUE TITLE
Feedback on page: /guides/v2.3/comp-mgr/cli/cli-rc1-samp.html

### ISSUE THREAD

**Issue by jacekl** [magento/devdocs#3399]
# General issue
There is a typo on the page, Magento Open Source mentioned twice by mistake.

## Description:

There is a typo on the page, Magento Open Source mentioned twice:
`These instructions apply to Magento Open Source (formerly Community Edition (CE) and Magento Open Source (formerly Enterprise Edition (EE) users only if all of the following are true`

## Possible solutions:

Change to: 
`These instructions apply to Magento Open Source (formerly Community Edition (CE) and Magento Commerce (formerly Enterprise Edition (EE) users only if all of the following are true`

**Comment by gelanivishal** [comment]
@jacekl Give me page URL.

**Comment by keharper** [comment]
Hi @gelanivishal . The file to be updated is at _includes/install/sampledata/sample-data-rc1-cli.md

I think it's OK to remove `(formerly Community Edition (CE)` and `(formerly Enterprise Edition (EE)`. It's been well over a year since we renamed the products.

**Comment by keharper** [comment]
@gelanivishal Please make the same change as suggested in #3409.
