### ISSUE TITLE
Suggestions to improve the Frontend Developer Guide content concerning blocks

### ISSUE THREAD

**Issue by joshuaswarren** [magento/devdocs#340]
I've been spending a lot of time this weekend with the Frontend Developer Guide - http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/bk-frontend-dev-guide.html - and I've noticed two areas that it could potentially be improved in that I wanted to suggest:

1. More content about Blocks - specifically, create a section about Blocks on the same level (and with the same details) as Layout and Templates. Right now there's content on Blocks scattered throughout the guide as it comes up. I think it would be helpful (especially for developers new to any version of Magento) to have Blocks called out in their own section before the Layout section.  

2. I couldn't find any mention of CMS/static blocks and how to add those to themes and the fact that users can edit them from the admin panel.

**Comment by xcomSteveJohnson** [comment]
@almarchenko Please take a look.

**Comment by almarchenko** [comment]
Hi! Thank you for spending time on our docs! We are researching your request and will get back soon as possible.

**Comment by joshuaswarren** [comment]
You're welcome! I've been spending a lot of time with the documentation lately, so I've been trying to either submit pull requests when I have time, or at least post issues when I see something that could be improved but don't have time to submit myself. Let me know if you have any questions about this issue.

**Comment by almarchenko** [comment]
Hi @joshuaswarren, unfortunately CMS blocks are not covered yet, because we 
were trying to keep pace with new things developers added each sprint. 
But the time for comprehensive CMS docs is coming, because a lot of improvements are planned in this area by the product team in the one of upcoming releases. We will save 
you comment to consider when creating CMS docs, and close this issue if you don't mind.

**Comment by joshuaswarren** [comment]
@almarchenko - that makes sense. I'll go ahead and close this issue. When the new CMS improvements start rolling out, I'd love to discuss this area with you more and help build out these docs!

**Comment by almarchenko** [comment]
@joshuaswarren 
Great, thank you! Actually I wanted to add a note asking you for feedback in future :)
