### ISSUE TITLE
Magento 2.3 Optimization Guide Page 

### ISSUE THREAD

**Issue by syedqurat** [magento/devdocs#3404]
# General issue
optimization guide page not found
## Description:

Here is link when i go to optimize guide and select documentation version 2.3 i got page not found error.
https://devdocs.magento.com/guides/v2.3/config-guide/prod/prod_perf-optimize.html  

page not found

**Comment by keharper** [comment]
@syedqurat I'll fix that shortly. In the meantime, that URL should redirect to here:

https://devdocs.magento.com/guides/v2.3/performance-best-practices/introduction.html

**Comment by keharper** [comment]
Fixed via #3405
