### ISSUE TITLE
Development Best Practices - Database Architecture

### ISSUE THREAD

**Issue by df2k2** [magento/devdocs#3412]
# New topic request

## Description

I've not found any development documentation, best practices, or even guidelines when working with database architecture.  There are some fairly important points surrounding database architecture that should be noted for developers.

## Content checklist

Topics should cover various areas surrounding database table design and maintenance, best practices, etc..  Example topics:

**Database design guidelines**

  * Table and field naming
  * Field datatypes
  * Indexes

**Database design best practices**

* Consistency for common fields
  * Examples:  **created** and **updated** time-stamping
* Datatype specifications
  * Understanding the difference between the `timestamp` and `datetime` fields, such as which is best for performance, timestamp limitations and dependency on the OS or configured timezone settings.
  * Datatype suggestions for integers - knowing when to use bit, tinyint, smallint, mediumint, int, bigint, and the typical minimum and maxmimum of each, as well as when unsigned specified.
  * Understanding datatype **display width** and how it affects anything or nothing.  The display width is the _m_ in `int(m)` or `varchar(m)`
* Design using Indexes, Unique Indexes
* Design for best performance
  * IPv4 Addresses - Unsigned integers instead of string, functions to convert between.
  * Text and Blob datatypes and their impact on performance and memory during various query operations such as sorting and joining.
  * Mismatched types - For example, query filtering a field with an integer for a varchar-based increment_id
  * Database maintenance - Log and temporary table cleansing, table optimization - fragmented data, etc..
  * Database configuration

## Additional information/resources

* [MariaDB Documentation - MariaDB Knowledge Base](https://mariadb.com/kb/en/library/documentation/)
* [Percona Server 5.7 - Documentation](https://www.percona.com/doc/percona-server/LATEST/index.html)
* [MySQL :: MySQL Documentation](https://dev.mysql.com/doc/)

**Comment by Vinai** [comment]
Much of this isn't Magento specific, but rather depends on the underlying RDBMS. I don't think Magento should document those things.
From what you listed, I think only table and field naming are Magento specific.
In addition to that it would make sense to write something about avoiding foreign key constraints across DB sections.

**Comment by shrielenee** [comment]
@Vinai is correct here, these are not Magento-specific. Please feel free to submit a PR with the external resources you mentioned @df2k2 to the Community resources section Lori mentions above.

We are closing this issue, as we will not document these in Magento documentation.
