### ISSUE TITLE
Testing Resources For Magento 2 Are Referencing Magento 1 Resources

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#3422]
# Correction request

## Topic Links
- https://devdocs.magento.com/guides/v2.2/extension-dev-guide/validate/test-module.html#more-information
  - The "Validating Magento Extensions" link
- https://devdocs.magento.com/community/resources/resources.html#automated-testing
  - "Book Test Driven Magento Extension Development by Allan MacGregor"

## Description
There are references to unit testing for Magento 1 in the DevDocs. This can lead to confusion for developers, as well call into question the process used by the Documentation team to validate content prior to publishing it.

## Possible solutions
Either add a demarcation stating that the above resources are for Magento 1, or even better, remove them. I would take this a step further and ask that relevant content is provided for Magento 2. If there was the ability to do a "Documentation Sprint" on Unit Testing for Magento 2, that would be great. Otherwise, please replace the above links with something like http://mage2katas.com which is Magento 2-specific.

## Additional information
If there's a lack of official material for unit testing for Magento 2, then I would argue that putting Magento 1 material as a stop-gap isn't sufficient. The state of PHP, PHPUnit, and the target framework have changed quite a bit, so it's not really the same thing. The DevDocs are a resource that has evolved into something quite good, but this is an instance of questionable decision making.

**Comment by lorikrell** [comment]
@ryantfowler  thanks for the feedback! I've investigated a number of resources, including the one you provided. I also accept any additions and favorites for the Community Resources page through issues, PRs, or twitter messages. PR incoming with changes.

**Comment by ryantfowler** [comment]
@lorikrell Thank you
