### ISSUE TITLE
Slider for Magento 2

### ISSUE THREAD

**Issue by mrkhoa99** [magento/devdocs#344]
Hi,

I don't see ideas about Slider for Magento 2. For example, Javascript lib should be used and how to create an example slider. Any idea about my point? If I can, I will contribute to this point.

Thanks!

**Comment by guz-anton** [comment]
Hi Mr Khoa,
What do mean under _slider_? Is it [Slider-Images-carousel](https://www.google.co.uk/search?q=carousel+jquery&biw=1920&bih=1019&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMI1N7ukK3qxwIVxxTbCh0RhA0Y&gws_rd=cr&ei=uFvwVdeOG5GU7QbM-5Uw) of [Slider-as-Form-control](https://www.google.co.uk/search?q=carousel+jquery&biw=1920&bih=1019&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMI1N7ukK3qxwIVxxTbCh0RhA0Y&gws_rd=cr&ei=uFvwVdeOG5GU7QbM-5Uw#tbm=isch&q=slider+input+jquery) ?

**Comment by mrkhoa99** [comment]
Hi,
I mean that it is Slider images carousel. For example, banner slider in homepage. In 1.9.x version, Magento recommended that we should use [Owl Carousel] (http://owlgraphic.com/owlcarousel/) for banners slider.

**Comment by guz-anton** [comment]
We have plans to integrate some Carousel in Magento box. Currently I can't promise what exact widget it would be and when it comes in Release.

If you also planning to contribute in this direction, look on new [Magento Gallery widget](https://github.com/magento/magento2/blob/develop/lib/web/mage/gallery/gallery.js). Maybe you can find some interesting patterns.

P.S.: As for me as developer: Owl Carousel is flexible enough to use it own projects.

**Comment by mrkhoa99** [comment]
Ok, I will take a look on new Magento Gallery widget. And, I will try to understand it.

Thanks!
