### ISSUE TITLE
Value clarification in install/allowoverrides24.md

### ISSUE THREAD

**Issue by dobooth** [magento/devdocs#3441]
# Topic clarification/correction request

## Topic Link

https://github.com/magento/devdocs/blob/master/_includes/install/allowoverrides24.md

## Description

In step 2, it is not clear what value needs to go in the <Value from apache site> area. We should be clear about expected values.

**Comment by jeff-matthews** [comment]
Thanks @dobooth. I think this may duplicate #1224. Please confirm. If so, please close this issue.

**Comment by dobooth** [comment]
Duped!
