### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/prereq/dev_install.html

### ISSUE THREAD

**Issue by igrybkov** [magento/devdocs#3482]
# General issue

## Description:

In the section "[Creating an authorization file](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/dev_install.html#instgde-prereq-compose-clone-auth)" documentation describes how to set a GitHub token to `auth.json` file to avoid GitHub's throttling by requests.
In the public slack channel appeared, that some developers does not familiar with the concept of GitHub personal access token. This and the fact that googling the term "GitHub OAuth ID" used in the documentation shows information regarding Github OAuth Apps leads to the misunderstanding of which token we want to set here and developers trying to create OAuth app instead.

## Possible solutions:

Add a link to GitHub documentation to Personal Access Token creation:
- https://blog.github.com/2013-05-16-personal-api-tokens/
- https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

And/or link composer's troubleshooting documentation:
- https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

Optionally describe which scopes and why should be selected:
- https://gist.github.com/jeffersonmartin/d0d4a8dfec90d224d14f250b36c74d2f

**Comment by dobooth** [comment]
This will be fixed when https://github.com/magento/devdocs/pull/3491 is pushed.
