### ISSUE TITLE
deploy:mode changed to setup:mode 

### ISSUE THREAD

**Issue by biotech** [magento/devdocs#349]
Should be changed according to https://github.com/magento/magento2/blob/6ba36cff388d71e8031a144d45158ce896dd44cb/app/code/Magento/Deploy/README.md 

Discovered by http://magento.stackexchange.com/questions/82166/clear-theme-css-cache-in-magento-2/82168#82168

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing that out. I'll suggest a change to the README because the command should be under deploy. I'm not sure when the changes were made but as of 1.0.0-beta3 anyway, the documentation should be correct.
