### ISSUE TITLE
Feedback on page: /guides/v2.3/rest/bulk-endpoints.html

### ISSUE THREAD

**Issue by rddwh** [magento/devdocs#3508]
# General issue
More examples required around product creation via bulk API

## Description:
There is little or no information available on how to create configurable products, options and linked child SKUs using the bulk API.  Is this possible out of the box?  The page states:

_Endpoint routes that contain input parameters require additional changes. For example, PUT /V1/product/:sku/options/:optionId contains the :sku and :optionId input parameters. The route of a bulk request cannot contain input parameters, so you must change the route so that it does not contain any. To do this, replace the colon (:) with by and change the first letter of the parameter to uppercase._

Some of the payloads for the endpoints used when creating a configurable product (such as **V1/configurable-products/:sku/options** and **V1/configurable-products/:sku/child**) do not have the SKU as a field in the payload.

## Possible solutions:
A tutorial on the best approach to create products via the bulk API would very helpful (in the same way as https://devdocs.magento.com/guides/v2.3/rest/tutorials/configurable-product/config-product-intro.html)

**Comment by nuzil** [comment]
Hi @rddwh I will try to create documentation in next days

**Comment by nuzil** [comment]
Here is a PR with tutorial for Bulk API
https://github.com/magento/devdocs/pull/3580

**Comment by camdixon** [comment]
Finally some documentation about this item for bulk cataloging.  :)

**Comment by nuzil** [comment]
Tutorial is available online. So I'm closing issue

**Comment by rddwh** [comment]
@nuzil Thanks for adding the tutorial however this only covers using the async endpoints.  I was hoping for the example to cover the Bulk endpoints e.g. /async/bulk/V1/products

The only documentation on using the Bulk endpoints is here:

https://devdocs.magento.com/guides/v2.3/rest/bulk-endpoints.html

It would be good to cover the configurable product creation, options and child linking using Bulk as the payloads and endpoints are different.
