### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/prereq/dev_install.md

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/devdocs#3511]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/install-gde/prereq/dev_install.html

## Description

The required information for Composer authentication glazes over how to generate a GitHub token. The Composer object naming implies that an OAuth token is needed, but this requires detailed information about the application be provided.

Currently, Magento provides no guidance on the GitHub auth process and for a developer that doesn't touch infrastructure like this often there's no obvious path. 

## Possible solutions

I'll submit a pull request to this issue shortly, which improves the documentation with a list of the requirements to set up Composer's auth file and how to generate those keys.

## Additional information

Currently, the DevDocs repo uses an `include` which is not versioned for each Magento release. My PR changes the docs for Magento 2.0 + 2.1 (2.2 + 2.3 use a symlink).

I tried to normalize this section of the docs in a couple ways and consolidate the information to be more readable. I'm not sure if these are all practices the DevDocs team will agree with.

- Outline the `auth.json` requirements before describing how to achieve each requirement.
- Describe the process to achieve each requirement in enough detail to remove ambiguity.
- Use proper heading hierarchy (major sections are typically H2 not H3).
- Final "next steps" is an H2 (not a sub-section of the former section).

Lastly, I'm not at all sure if the approach I prescribed is correct for providing GitHub authentication (use personal access tokens, not OAuth App). It does work and this was a recommendation I received on the Magento Community Engineering Slack. I didn't receive any other feedback that there were working alternatives, so I think it makes sense to document a verifiable working approach.

## Annotations

![notes](https://user-images.githubusercontent.com/214924/50618369-1e2b6b00-0ea7-11e9-95e4-ad70815ecfe8.png)

**Comment by jeff-matthews** [comment]
@brendanfalkowski,

I see that you've already created a PR and I'll add comments there re: versioning. For future reference, we no longer update version 2.0 of the docs, as indicated in the banner message at the top of all 2.0 devdocs pages. In most cases, the 2.1 version of a file is symlinked to 2.2 and 2.2 symlinked to 2.3. Always check for symlinks before updating a file. Sometimes, you need to make the update to more than one file if there's no symlink.
