### ISSUE TITLE
Memory size limitted

### ISSUE THREAD

**Issue by hbweb** [magento/devdocs#352]
I'm getting this error message when install sample data as below. Just wonder how much memory does it need to allocate? 

Also, any way we can re-install data?

CLI >> bin/magento sampledata:install admin
Installing theme:
.
Installing customers:
.
Installing CMS pages:
....
Installing catalog attributes:
...........................
Installing categories:
.........................................
Installing simple products:
............................................
Installing bundle products:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/shop.getbraise.com/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 221

**Comment by xcomSteveJohnson** [comment]
This could be a number of things. I don't have the Magento 2 GitHub issue numbers handy but you can disable xdebug if it's enabled. You can also use a command-line argument to set the PHP memory_size on the CLI. (Check PHP documentation.)

Finally, you can set the memory_limit in php.ini to the recommended value of 768M: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone

**Comment by xcomSteveJohnson** [comment]
Closing. Please reopen if this didn't work for you.
