### ISSUE TITLE
URLs have several sources (duplicates in redirects)

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#3521]
# Bug report

## Description

The `jekyll doctor` tool reports about [429 conflicts](https://gist.github.com/dshevtsov/9f9a6eaef2cf454b5989ef8f3dcfee66) where a URL is destination for several sources. In most cases the conflicts are caused by duplicated redirects when the same URL is declared as a redirect in several topics. Some of them are introduced manually and can be fixed manually. Many of the conflicts can be caused by symlinks that requires a more complex system solution, then manual editing.

Primary goal: Find all files that do not have sym link AND have multiple redirects and ensure that they only have a single redirect.

- need to have 1 md file as the redirect per old file link
- for symlinks, add redirect for all versions of file being redirected
- may require multiple PRs to handle sections of links, see REPORT link below
- if you enter PR for section of links, make sure to note which ones you fix in the PR/Ticket

### Steps to reproduce

Run `bundle exec jekyll doctor`

## Expected result

Good: A search for conflicted URL returns only one source for the URL.
Perfect: No URLs with conflicts.

## Possible solutions

Search for a URL with conflicts and remove extra declarations so that the URL had one source only.

## Additional information

[Report with conflicts](https://gist.github.com/dshevtsov/9f9a6eaef2cf454b5989ef8f3dcfee66).

**Comment by dobooth** [comment]
When files have multiple redirects:
`- /guides/v2.1/cloud/before/before-project-owner.html 
- /guides/v2.2/cloud/before/before-project-owner.html
- /guides/v2.3/cloud/before/before-project-owner.html `
The last one listed is the resultant redirect. 
I suspect the first two are written and then immediately overwritten.
When files are symlinked between versions, all these multiple redirects are copied over as well.
That means in the above scenario (assuming the original is 2.1), 2.1, 2.2 and 2.3 files will all redirect to 2.3.
This is the version hopping we are trying to avoid. 
Therefor any file should only have a single redirect. 

Files with multiple symlinks as above will need to have the symlink broken and keep the redirect within the same version.

**Comment by dobooth** [comment]
https://github.com/magento/devdocs/pull/3812

**Comment by hguthrie** [comment]
Regarding the cloud example with `/before/before-project-owner.html`. The original file does not exist. There is only one file that exists and it is an Onboarding topic in version 2.1. Are you talking about Redirect To? Or Redirect From?

I'm all for cleaning these things up. Over time, they get messy.

**Comment by dshevtsov** [comment]
The current number of conflicts is [120](https://gist.github.com/dshevtsov/9f9a6eaef2cf454b5989ef8f3dcfee66).

**Comment by dshevtsov** [comment]
#5037 reduces the number of conflicts to [108](https://gist.github.com/dshevtsov/9f9a6eaef2cf454b5989ef8f3dcfee66)

**Comment by dshevtsov** [comment]
There are still [4 conflicts](https://gist.github.com/dshevtsov/9f9a6eaef2cf454b5989ef8f3dcfee66).
