### ISSUE TITLE
MSI - Add information for new SSA Distance Priority 

### ISSUE THREAD

**Issue by lorikrell** [magento/devdocs#3548]
# Community engineering issue

Type of Doc:
- [ ] New topic
- [X] Topic Update, Devdoc link:
- [ ] Other

Magento 2 GitHub PR: https://github.com/magento-engcom/msi/pull/1866
Draft User Content: https://github.com/magento-engcom/msi/wiki/Configure-MSI-SSA 

Magento 2 version:
- [ ] 2.1.X
- [ ] 2.2.X
- [X] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface?
- [ ] New software requirements?
- [ ] New REST endpoints or updated GraphQL query syntax?
- [X] New command line option?

## Release 
Releasing with MSI 1.1.0, January 2019 - TBD final date
Affects 2.3.0

## Content

DevDocs affected: https://devdocs.magento.com/guides/v2.3/rest/modules/inventory/manage-source-selection.html

Need to add info on another SSA available out of the box: Distance Priority Algorithm. For details, see the draft user content: https://github.com/magento-engcom/msi/wiki/Configure-MSI-SSA 

There is a new CLI command for Distance Priority Algorithm: `php bin/magento inventory-geonames:import <countries>...`
Space separated command required as part of the Distance Priority Algorithm set up. 

For example, if you want to import geocodes for the United States, United Kingdom, Italy, and France, you would use the command:

`php bin/magento inventory-geonames:import us uk fr it`

See the draft user content for some background/merchant steps. 
Short term, may want to just update the content.

**Comment by keharper** [comment]
Devdocs PR: #3668

**Comment by lorikrell** [comment]
Closing due to work completed.
