### ISSUE TITLE
Feedback on page: /guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.html

### ISSUE THREAD

**Issue by mohammadttc** [magento/devdocs#3554]
# General issue
Broken link.
## Description:

There is a broken link at the following page.
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.html
"UI components configuration" link is pointing to a 404 page.

**Comment by jeff-matthews** [comment]
Thanks for reporting @mohammadttc. The issue is a double slash in the URL.

**Comment by dobooth** [comment]
Fixed with https://github.com/magento/devdocs/pull/3567
