### ISSUE TITLE
Missing _config.yml breaks some links and images

### ISSUE THREAD

**Issue by t-richards** [magento/devdocs#357]
After a fresh clone on my local machine (specifically, commit 814d69e2bfd65a33600565ac8bf0147a37718577 at this time of writing), running `$ bin/jekyll serve` results in a semi-working docs site. 

The Magento logo on the homepage is missing:

![logo-missing](https://cloud.githubusercontent.com/assets/3905798/10006632/cb57ff22-608c-11e5-8bbb-dc72fd2e7d3d.png)

At least some of the links on the site are broken (notice the duplicated `api` in the URL):

![broken-url](https://cloud.githubusercontent.com/assets/3905798/10006647/e3835114-608c-11e5-8889-e1384c8b40a9.png)

The broken images and links in question require values from the [recently deleted `_config.yml` file](https://github.com/magento/devdocs/commit/f3572f3d7f7b4d5e1493f17463f8e50b2bfaa032). Either the content should be updated to not require those configuration values anymore, or the `_config.yml` should be restored.

**Comment by t-richards** [comment]
A follow-up question: why was `_config.yml` deleted in the first place? It's rather odd for a Jekyll site to be without one, in my opinion.

**Comment by tanberry** [comment]
Hi, @t-richards, sorry about that, and thanks for alerting us to this! We are looking into it now...

**Comment by tdobbs** [comment]
@t-richards, we've restored the _config.yml file.

**Comment by t-richards** [comment]
@tdobbs Thanks!

Fixed in: c75117d6be34e9a3abf52ddd80d8414c2257d124
