### ISSUE TITLE
Missing Page: https://devdocs.magento.com/guides/v2.3/cloud/project/project-domains.html

### ISSUE THREAD

**Issue by gregdolder** [magento/devdocs#3582]
# Bug report

## Description

Dev Doc Missing Page: https://devdocs.magento.com/guides/v2.3/cloud/project/project-domains.html

### Steps to reproduce

1. Login to Cloud site
2. From the Domains view click the help ?

## Expected result

Page to display

## Possible solutions

Create page or name the link appropriately.

**Comment by hguthrie** [comment]
There are two problems here. 

1.   I will review the missing content and see if it is missing or needs a redirect.
2.  Any links from the Cloud site is out of the control of DevDocs, but I will pass along the notice to whomever controls it.

Thanks for alerting us about this!

**Comment by hguthrie** [comment]
Created MAGECLOUD-3120 to address the outdated links in the Cloud project web UI. The PO will assign this to the appropriate group.
