### ISSUE TITLE
Mobile view of devdocs.magento.com

### ISSUE THREAD

**Issue by biotech** [magento/devdocs#360]
Broken responsive design , hard to read and navigate. Screenshoots from Chrome on iphone 6. 

![img_8361](https://cloud.githubusercontent.com/assets/2007450/10125506/8cd133e6-6577-11e5-85ff-cba66ed7a91a.jpg)

![img_8360](https://cloud.githubusercontent.com/assets/2007450/10125507/8e676f9a-6577-11e5-9f84-76db09eb257e.jpg)

**Comment by tanberry** [comment]
Thanks, @biotech. Yep, we already have an internal ticket to work this (we agree, it doesn't look so great). I'll add your request to the queue and work for some traction, but in the meantime, if anyone in the community wants to help out with this, it would be great!

**Comment by xcomSteveJohnson** [comment]
@biotech We have a solution in the works! We're really close to rolling it out. We'll let you know.

**Comment by xcomSteveJohnson** [comment]
Closing because we are close to a solution. Watch for an announcement on Twitter.
