### ISSUE TITLE
SSL Certificate issue on devdocs.magento.com 

### ISSUE THREAD

**Issue by biotech** [magento/devdocs#364]
https://devdocs.magento.com/guides/v2.0/howdoi/php/php_clear-dirs.html trying to use SSL certificate of GitHub which cause error and un-secure connection

<img width="1199" alt="screenshot 2015-10-05 07 15 10" src="https://cloud.githubusercontent.com/assets/2007450/10273473/521bcb98-6b31-11e5-91af-1ce6c1d06913.png">

**Comment by xcomSteveJohnson** [comment]
Why is this our certificate issue if we have no certificate? Wouldn't it be a GitHub certificate issue?

**Comment by biotech** [comment]
On some pages you have link to HTTPS pages - this is how it get there - was security error on Chrome - i will continue and get errors as above. Need to check if somehow https links can be created and maybe make global 301 redirect for all https to http URLs for avoid issues.

**Comment by xcomSteveJohnson** [comment]
I don't see how that's possible. Can you elaborate? 

You're describing a known issue with GitHub. Suggest you inform them or vote for a solution: https://github.com/isaacs/github/issues/156

**Comment by biotech** [comment]
Trying different cases but not able to reproduce behaviour , i only know that i just navigate a lot inside documentation and get this https page somehow. Will let you know if i find something. Thanks @xcomSteveJohnson for all hard work here

**Comment by xcomSteveJohnson** [comment]
We'll leave this open in case you find the source of the https:// link. I would be very surprised to find it in the devdocs site. Please let us know.

**Comment by xcomSteveJohnson** [comment]
This is resolved now. Please reopen if you don't agree.
