### ISSUE TITLE
The example in module load order is not correct

### ISSUE THREAD

**Issue by bnymn** [magento/devdocs#3649]
# Bug report

The first example given to explain module load order is not correct. I think component A and component B should be switched in the example.

The current documentation is as follows:

> Component A introduces gadgetlayout.xml, which updates block gadgetBlock from component B. In this case, layout files from component A should be loaded before component B, so you should specify that in component B’s <sequence> entry in module .xml. In other words, component B is dependent on component A. That is to say:

### Steps to reproduce

Please visit the following link to see the erroneous example, https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-load-order.html

## Expected result

I think that the correct paragraph should be as follows:
Component A introduces gadgetlayout.xml, which updates block gadgetBlock from component B. In this case, layout files from component B should be loaded before component A, so you should specify that in component A’s <sequence> entry in module .xml. In other words, component A is dependent on component B. That is to say:

## Possible solutions

I have just put the solution above.

## Additional information

I might misunderstood the example. What I understand is the following:
There are two components called **Component A** and **Component B**. **Component B** has a block defined in it. That block is called **gadgetBlock**. **Component B** has no idea about **Component A**. But, **Component A** would like to update the block **gadgetBlock**, which is defined in **Component B** in the first place. So, **Component A** should depend on **Component B**. Because, if there were not any **Component B**, then there would not be any block for **Component A** to update.

**Comment by irajneeshgupta** [comment]
@bnymn

Thank you for the report.
