### ISSUE TITLE
Adjust GraphQL queries indentation & text markdown

### ISSUE THREAD

**Issue by williankeller** [magento/devdocs#3687]
# Topic clarification/correction request

## Topic Link
- https://devdocs.magento.com/guides/v2.3/graphql/reference/categories.html
- https://devdocs.magento.com/guides/v2.3/graphql/reference/customer.html
- https://devdocs.magento.com/guides/v2.3/graphql/reference/products.html
- https://devdocs.magento.com/guides/v2.3/graphql/reference/quote.html
- https://devdocs.magento.com/guides/v2.3/graphql/reference/store-config.html
- https://devdocs.magento.com/guides/v2.3/graphql/search-pagination.html

## Description

Some of the GraphQL are out of indentation making it difficult to understand the attribute rules and when they start and close.
Another thing is that these queries are under the `json` markdown and since it's not a JSON format and it's causing error lines at the GitHub readme pages.

![image](https://user-images.githubusercontent.com/2963928/52218637-36b1eb00-2882-11e9-92c6-e8d50a7f735c.png) 
-----------
![image](https://user-images.githubusercontent.com/2963928/52218676-46c9ca80-2882-11e9-9ad7-b7e9ef6920f2.png)
------------
![image](https://user-images.githubusercontent.com/2963928/52218724-63660280-2882-11e9-859c-58ce7f199b9c.png)

## Possible solutions

As aligned in this [Pull Request (3670)](https://github.com/magento/devdocs/pull/3670), it will be a good idea to change the queries markdown to the `text` one and also adjust the queries indentation.

**Comment by keharper** [comment]
This work has been completed in the course of completing other tasks.
