### ISSUE TITLE
[Architecture] Add documentation about Magento's approach to testing

### ISSUE THREAD

**Issue by jcalcaben** [magento/devdocs#3690]
# New topic request

## Description

Publish topic from architects regarding Magento's approach to testing.
 
## Content checklist

- [x] Topic contains information about Magento's approach to testing
- [ ] Find an appropriate place for this topic in the docs

## Additional information/resources

Content for the topic can be found here: https://github.com/magento/architecture/pull/65

**Comment by dobooth** [comment]
Since this was mostly expository text, it seemed better to flesh out the existing testing intro rather than create a new file.
