### ISSUE TITLE
Registration.php is not mentioned in theme documentation

### ISSUE THREAD

**Issue by gglerum** [magento/devdocs#370]
I am working on my first magento 2 theme. I created all the required files defined by the documentation, but my theme did not show up under "Content => Design => Themes".

Using the luma theme as an example I created a registration.php file in the root of my theme. Now it shows up in the config.

Is this a temporary solution or is it just missing in the documentation?

**Comment by tdobbs** [comment]
Yes, the code is out in front of the documentation: https://github.com/magento/magento2/issues/2046

**Comment by xcomSteveJohnson** [comment]
@almarchenko Did you fix this?

**Comment by almarchenko** [comment]
It's fixed now http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-create.html#fedg_create_theme_reg
