### ISSUE TITLE
Add note about `InstallData` - per HotJar feedback

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#3700]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/attributes.html

[Extension attribute authentication](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/attributes.html#ext-aut) section

## Description

Mention that `InstallData` will be executed only if the module in question was just inserted in Magento system. Otherwise, you must remove it's the corresponding entry from `setup_module` table, or use `UpdateData` class. 

## Additional information

Kevin comment: This topic might require some additional changes for 2.3.x. MSI is making CatalogInventory obsolete, while Declarative Schema might change how the attributes are saved.

Per HotJar feedback - @jcalcaben owns Extension Dev Guide

**Comment by keharper** [comment]
This topic might require some additional changes for 2.3.x. MSI is making CatalogInventory obsolete, while Declarative Schema might change how the attributes are saved.

**Comment by lorikrell** [comment]
Closing this ticket as content was provided in a merged PR. If additional work is needed, a new issue can be opened.
