### ISSUE TITLE
Search on Magento 2 documentation 

### ISSUE THREAD

**Issue by biotech** [magento/devdocs#375]
I have ask some time ago and seems like you are guys already working with that , but would be good to have some status when we can have search here, this really annoying use "site:devdocs.magento.com" in Google :) 

Here is current possibilities for search on Jekyll
- https://github.com/christian-fei/Simple-Jekyll-Search 
- https://github.com/slashdotdash/jekyll-lunr-js-search 
- https://github.com/cobbler/jekyll-dynamic-search

**Comment by tanberry** [comment]
;-) Good news, @biotech; we have implemented a search tool internally and have been testing, and should be ready to publish our new Search option within the next week or two!

**Comment by xcomSteveJohnson** [comment]
Search is working. Please close this if you find it useful.

**Comment by xcomSteveJohnson** [comment]
Closing.
