### ISSUE TITLE
Deprecation Notice! Magento backup features are deprecated as of v2.3.0

### ISSUE THREAD

**Issue by travis5491811** [magento/devdocs#3766]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ce/user_guide/system/backups.html

## Description

The linked page says the following:

> Deprecation Notice! Magento backup features are deprecated as of v2.3.0. We recommend that all merchants investigate additional backup technologies and binary backup tools (such as Percona XtraBackup).

If it's deprecated as of v2.3.0, why is it in the UI for v2.3.0? Does it in-fact not work properly? For now we are using a cron job to backup the site by copying the database and the installation directory. However, this doesn't handle the case of a store admin wanting to snapshot the store before making a specific change.

Am I miss-understanding what deprecated means here? I expected if it was deprecated as of v2.3.0, the feature would not be in v2.3.0 and the last place it would have been active in the UI is v2.2.7.

## Additional information

I posted question related to this [here](https://magento.stackexchange.com/questions/260040/backups-in-magento-2-3-0-you-need-more-permissions-to-perform-a-rollback) but got no answer

**Comment by jeff-matthews** [comment]
@travis5491811, this repo is for questions/feedback about _devdocs_ content only. You're referring to _merchant_ documentation, which at present is not publicly available on GitHub the same way that the devdocs source is.

But to answer your question: yes, you are misunderstanding the definition of "deprecated". From [Wikipedia](https://en.wikipedia.org/wiki/Deprecation):

> In several fields, deprecation is the discouragement of use of some terminology, feature, design, or practice, typically because it has been superseded or is no longer considered efficient or safe, without completely removing it or prohibiting its use. It can also imply that a feature, design, or practice will be removed or discontinued entirely in the future
