### ISSUE TITLE
Defining new theme variables

### ISSUE THREAD

**Issue by danielgoodwin97** [magento/devdocs#3807]
# Defining new theme variables

## Topic Link

https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-less.html#location

## Description

When defining new variables for a theme that are used globally, it says in the devdocs that they must be defined in the _theme.less file.

But in Magento blank's [_theme.less file](https://github.com/magento/magento2/blob/2.3/app/design/frontend/Magento/blank/web/css/source/_theme.less), it says:

> Theme file should contain declarations (overrides) ONLY OF EXISTING variables

This seems to contradict the devdocs, which says that new variables (not existing) should be created there?

## Possible solutions

Find out if either the devdocs, or the _theme.less file need changing?

## Additional Information

I'd like to note that [Luma has created variables inside of the _theme.less](https://github.com/magento/magento2/blob/f4c1d7526f05bdfb1327b0701cc345f94aadcaed/app/design/frontend/Magento/luma/web/css/source/_theme.less#L302) even with the message about using the file to override existing variables.

@copyright__background-color is only used in Luma as far as I can tell.

**Comment by hitesh-wagento** [comment]
Hi @danielgoodwin97 

If you use parent theme **blank** instead of **luma** you should add new global variables in [_theme.less](https://github.com/magento/magento2/blob/2.3/app/design/frontend/Magento/blank/web/css/source/_theme.less)

**Comment by chiranjeevi-cj** [comment]
@magento i am working on this

**Comment by mrtuvn** [comment]
I think nothing wrong with that but we should following best practices here
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/theme-best-practice.html

**Comment by mrtuvn** [comment]
The note meaning when you add variables in blank _theme.less it will possible overwrite variables magento defined in
https://github.com/magento/magento2/tree/2.4-develop/lib/web/css/source/lib/variables

**Comment by BarnyShergold** [comment]
@danielgoodwin97 - There has been quite a few changes on this page since you raised this issue, plus it doesn't mention new variables in _theme.less but that if variables are COMMON.

Please respond in the next few days so the issues can be closed if not needed.

**Comment by schizek** [comment]
I believe this still needs clarification.  As of today the codebase `_theme.less` file in the blank theme still says...

```
//  Theme file should contain declarations (overrides) ONLY OF EXISTING variables
//  Otherwise this theme won't be available for parent nesting
//  All new variables should be placed in local theme lib or local theme files
```

While the [Magento Theme Best Practice doc](https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-less.html#variables) now says...

> # Variables
> ## Location
> ### Local variables
> If variables are local and used only in a module scope, they should be located in the module file, in the beginning of the general comment.
> 
> Example: _module.less:
> ```
> ...
> 
> //
> //  Variables
> //  _____________________________________________
> 
>     //  Colors
> @btn__color: @color-brownie;
> @btn-primary__color: @color-white;
> @btn-secondary__color: @color-white;
> ...
> ```
> 
> ### Theme variables
> If variables are common for several modules they should be specified in the _theme.less file.

This is still inconsistent.  Additionally, it makes no mention of the `_variables.less` file which in the blank theme contains variables such as `@tab-content__border-top-status: true;` which is initially defined in the `lib/web/css/source/lib/variables/_sections.less` and I assume would therefore be considered an "existing variable".

Further clarification is needed here on when you actually need to use `_theme.less` vs `_variables.less` and what the definition of an "existing variable" is.  Additionally, an example of **why** would be helpful in understanding the difference as it relates to...

> Otherwise this theme won't be available for parent nesting

**Comment by mrtuvn** [comment]
_variables for define variable from beginning, reused later in many places
_theme.less intend for override existing variable from parent if theme have inheritance. It's not only for override purposes it's can be use for define new variable too but i think better put new variables in _variables file for consistency

**Comment by dshevtsov** [comment]
The topic was moved to https://developer.adobe.com/commerce/php/coding-standards/less/.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-php/issues.
