### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by fbrnc** [magento/devdocs#385]
The instructions on http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data.html don't really work. (Also see: http://magento.stackexchange.com/questions/85753/magento-2-uninstallable-set-of-packages-when-deploying-magento-sample-data/86828#86828)

Not sure if this a documentation issue or an issue with the actual sample data. However, I couldn't find the `sampledata:install` command and the composer commands result in errors...

**Comment by xcomSteveJohnson** [comment]
Currently, there appears to be only one way to install sample data: to clone the Magento 2 master branch and then use the instructions on devdocs. packages.magento.com doesn't have the new packages and when I tried 'composer create-project' the other day, the sampledata command is absent.

As soon as I know something different, I'll update this issue.

**Comment by xcomSteveJohnson** [comment]
Try this and let me know: http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data.html

**Comment by xcomSteveJohnson** [comment]
Closing.

**Comment by matjack1** [comment]
Hello @xcomSteveJohnson, I still have the problem that was raised before.
I can fix it by doing this:
`composer config repositories.magento composer http://packages.magento.com`
as reported in the link above. Do you think it would be good to add that to the documentation?

**Comment by xcomSteveJohnson** [comment]
No. packages.magento.com has old code and should not be used with current releases.

**Comment by matjack1** [comment]
I see, thanks for clarifying
