### ISSUE TITLE
Navigation titles don't match the actual section titles

### ISSUE THREAD

**Issue by paales** [magento/devdocs#3886]
# Bug report

### Steps to reproduce

1. Go to a deeplink: https://devdocs.magento.com/guides/v2.3/comp-mgr/marketplace/marketplace.html
2. Guess on which section I actually am on the website..
3. Be confused because there doesn't exist a menu navigation item called 'Software Update Guide'.

## Expected result

The section name should be in the menu, no differences.

## Possible solutions

Make index pages for each section and place those in the navigation.

## Additional information

There is a _lot_ of valuable information in the devdocs but it is very unclear where I am, how I can find stuff, etc.

**Comment by dobooth** [comment]
Top-level nav in Devdocs:
Setup > Extension Update and System Upgrade Guide takes you to the Software Update Guide.
Looks like a bit of a title mis-match.

**Comment by paales** [comment]
@dobooth This is happening on multiple pages on the website, don't know if you've checked for every page, wasn't just talking about this page. :)
