### ISSUE TITLE
Search 'update msi' doesn't yield any result

### ISSUE THREAD

**Issue by paales** [magento/devdocs#3887]
# Bug report

## Description

The search looks broken, returns insensible results. 

### Steps to reproduce

Fill in 'update msi' in the search, you dont find anything useful.

## Expected result

Find the actual page: https://devdocs.magento.com/guides/v2.3/comp-mgr/install-extensions/inventory-management-installation.html

I had to search for a few minutes to find this page via the navigation because it is below some random menu 'Install extension from the commandline'..

## Possible solutions

1. Log in to algolia and fix the first 1000 searches so that they actually return some non-garbage.
2. Log in to and create a synonym list based on the results from the previous step.

## Additional information

Documentation is truely amazing and truely great! Now we need to be able to find the information ;)

**Comment by lorikrell** [comment]
Hello @paales, we are working to increase Algolia search performance and parameters. We also have a DevBlog on searches for DevDocs/MerchDocs coming out soon!

I'm updating some Inventory Management/MSI content. I'll see if I can help out a bit for searches.

**Comment by belbiy** [comment]
This bug should be fixed by now. Search index now understands `msi = multi-source inventory = inventory management`.

**Comment by paales** [comment]
🎉
