### ISSUE TITLE
Feedback on page: /guides/v2.3/migration/migration-tool.html

### ISSUE THREAD

**Issue by dharake** [magento/devdocs#3906]
# General issue

## Description:

Need a toold to transfer data between M2 instances (i.e. M2.1 -> 2.3)

## Possible solutions:

Updated migration tool?

**Comment by lorikrell** [comment]
Hello @dharake, great feature request! We do have a data migration tool available for M1 to M2 instances. For M2 version migration, you may want to feature request using the [Magento 2 Feature and Requests forum](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Everyone can review and vote for new features.

**Comment by dharake** [comment]
Thanks @lorikrell, will do
