### ISSUE TITLE
Feedback on page: /guides/v2.2/comp-mgr/trouble/cman/maint-mode.html

### ISSUE THREAD

**Issue by diazwatson** [magento/devdocs#3913]
# General issue

## Description:

Why is it recommended to create a [custom maintenance page](https://devdocs.magento.com/guides/v2.2/comp-mgr/trouble/cman/maint-mode.html) outside Magento if there is already a [maintenance page mechanism](https://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-subcommands-maint.html) in place?

**Comment by dobooth** [comment]
Hi @diazwatson 
Thanks for the issue. 
Not sure what to do with this. Both links go to the same page.
Did you want clarification somewhere?
Flesh this out a bit and we can work on it.
Thanks!

**Comment by diazwatson** [comment]
Hi @dobooth, sorry for the delay. I have updated the links in my comments to reflect the two options.
Basically one of them explains how to create a custom maintenance.html and use the web server (Nginx, Apache) to redirects to it in the event of a 503 header.

The other option uses the cli command `magento maintenance:enable`

Thanks

**Comment by dobooth** [comment]
Thanks for the update.

**Comment by dobooth** [comment]
One page describes how to setup a custom maintenance page. The other describes how to go into maintenance mode. I'm not sure what kid of clarification you are looking for. There is a bit of overlap on content on the pages but that's not egregious. 
I am going to close this issue for now. If you can point out changes you would like made or any clarification in the text, please let us know.
