### ISSUE TITLE
Feedback on page: /guides/v2.2/config-guide/elasticsearch/es-overview.html - Elastic Search Version

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#3923]
This page suggests that Magento support Elastic Search Version 5.x.  The supported version is 5.2.  5.3 and later is not supported currently (2.3.0) to the best of my knowledge

**Comment by dobooth** [comment]
Hi Doug. 
Good eye. 
We are getting ready for an ES update:
https://github.com/magento/devdocs/pull/3890
