### ISSUE TITLE
phpunit.de moved to readthedocs.io update needed

### ISSUE THREAD

**Issue by YaroslavHolovanych** [magento/devdocs#3956]
# Bug report

### Steps to reproduce

1. Navigate to page https://devdocs.magento.com/guides/v2.3/test/integration/integration_test_execution.html#adjust-the-phpunit-configuration-file
2. Click the link "PHPUnit documentation"

## Expected result

https://phpunit.readthedocs.io/en/8.0/configuration.html instead of https://phpunit.de/manual/4.1/en/appendixes.configuration.html

**Comment by dobooth** [comment]
Fixed.
