### ISSUE TITLE
Update the Magento third party licenses topic

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#3958]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/magento-third-party.html

## Description

1. The topic doesn't cover Magento 2.2 and 2.3.
2. First heading is the same as title.

## Possible solutions

1. Add sections for Magento 2.2 and Magento 2.3
2. Remove the heading that is the same as title of the topic

**Comment by erikmarr** [comment]
After talking with @keharper we should delete this topic because we now have a release_notes directory.

**Comment by dshevtsov** [comment]
The removal requires changes in the footnote layout and may require additional internal approvals.
The corresponding changes should be processed in a separate issue/PR.
