### ISSUE TITLE
Installing from `master` vs. Installing from `develop`

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#396]
Responding to an email that somehow got attached to a ticket from another GitHub repository, and I don't have Steve's email.

> http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data.html
> Please look at the latest iteration and let us know what you think. We've installed Magento with sample data several times and have not needed to do anything special for that directory.

Here's the problem with recommending that users checkout and install from the develop branch.  Take a look at [this page](https://github.com/magento/magento2/commits/develop)

Here you see every commit made by a member of a Magento team, or a member of the general public, to the develop repository.  The `develop` branch is where developers check in whatever they're working on, and then hash out problems.  Just today I see over 10 changes made.

Each and everyone of these change **might** break something.  The test frameworks you have help prevent this somewhat, but it's natural in the software developer lifecycle that someone might check something into the development branch that will break something.  This includes the sample data.

I totally believe you when you say you've tested the installation procedure on `develop` and it works.  However, with a team the size of Magento 2's checking in code every day, the installation procedure may break on any given day.  

Dealing with this breakage is a natural part of being a developer working for eBay/Magento -- but when your public facing developer documents for third party developers recommend a procedure that **might** not work on any given day?  You're going to turn people off the product and platform, guaranteed.  

**This** is why any installation instructions on the devdocs site needs to recommend or strongly prefer checking out the master branch.  My approach here would be articles and tutorials that instruct users **only** is how to checkout and install from a stable branch (i.e. master), and then at the end mention that the `develop` branch is where active Magento development happens, and that if developers are interested in working on the Magento core they should issue pull requests against `develop`. 

Does that make sense?  Let me know if you have  any questions or additional feedback -- and if you need to email me make sure you're not responding to a GitHub ticket so I can see the email to respond to :)

**Comment by xcomSteveJohnson** [comment]
Thanks for your contribution. It's a choice users of the code can make.

**Comment by xcomSteveJohnson** [comment]
Reopen so others can comment. Let us know what you think.

**Comment by xcomSteveJohnson** [comment]
Closing because of elapsed time. Sample data installation has changed a bit and is now somewhat simpler. Please reopen if issues continue.
