### ISSUE TITLE
"Your Install or Upgrade Path" is ambiguous

### ISSUE THREAD

**Issue by benmarks** [magento/devdocs#397]
[This title](https://github.com/magento/devdocs/blob/develop/guides/v2.0/install-gde/install/pre-install.md) is ambiguous given that "path" can refer to either a mapping on storage medium or the mechanism if effecting an upgrade... suggest to change to "Types of installations or upgrades" (or something like this).

**Comment by xcomSteveJohnson** [comment]
This will change in an upcoming revision. Thanks for pointing it out.
