### ISSUE TITLE
Feedback on page: /guides/v2.3/cloud/docker/docker-config.html

### ISSUE THREAD

**Issue by keithbentrup** [magento/devdocs#3975]
# General issue

## Description:

The branch to checkout for the magento-cloud repo is not specified. i think only 2.3.0 is currently deploying properly. master is not last time i checked.

Step 1 of the  *To launch docker* procedure in the [Launch docker](https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-config.html) topic doesn't specify that you have to download the magento-cloud template from a version branch.

`Download a template from the Magento Cloud repository
for the version of the magento-cloud template.`

## Possible solutions:
Add info about downloading the Cloud template from the correct version branch.

**Comment by dobooth** [comment]
@keithbentrup Could you flesh out the issue a bit more?
Where exactly is the problem on the page?

**Comment by dobooth** [comment]
Thanks for the update.

**Comment by meker12** [comment]
@keithbentrup  and I discusssed this issue, so I filled in the details in the issue above.  Thanks for submitting the issue, Keith.

**Comment by hguthrie** [comment]
I addressed this for the next Cloud release.  See #4068
