### ISSUE TITLE
Broken links on devdocs/guides/m1x/api/rest/introduction.html

### ISSUE THREAD

**Issue by goosehub** [magento/devdocs#407]
on `devdocs/guides/m1x/api/rest/introduction.html`, starting at line `122`, are a list of resources. All these links are broken. Below is an example

    <ul>
	<li>Retrieve the list of products, create, update, and delete a product.<br/>
        <b>Resource Structure</b>: <a href="http://magentohost/api/rest/products">http://magentohost/api/rest/products</a></li>
    </ul>

This

    http://magentohost/api/rest/products

should be 

    http://devdocs.magento.com/guides/m1x/api/rest/Resources/Products/products.html

**Comment by goosehub** [comment]
Ah, I see it was intended as an example. I will close this issue, but still suggest that these urls are no longer links to prevent confusion.

**Comment by tanberry** [comment]
You make a good point, @goosehub. Agreed that the examples shouldn't be links. We will look into whether our automation is creating links, or what is happening. Thanks!
