### ISSUE TITLE
Link to internal repository in documentation

### ISSUE THREAD

**Issue by danslo** [magento/devdocs#409]
http://devdocs.magento.com/guides/v2.0/extension-dev-guide/component-registration.html

Refers to
https://github.corp.ebay.com/magento2/magento2ce/blob/develop/app/code/Magento/AdminNotification/registration.php

When it should point to
https://github.com/magento/magento2/blob/develop/app/code/Magento/AdminNotification/registration.php

**Comment by tanberry** [comment]
AWESOME critter on your head, @danslo. Thanks for catching that link error! 
@tdobbs can you please take a look?

**Comment by tdobbs** [comment]
Thanks for the catch, @danslo. The correction should be up this week.

**Comment by xcomSteveJohnson** [comment]
Fixed now, thanks!
