### ISSUE TITLE
Document directories/document_root_is_pub option in env.php

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#4093]
It would be great to find documentation about that in the dev docs. I only found that:

- https://devdocs.magento.com/guides/v2.2/cloud/trouble/robots-sitemap.html

Is the `'document_root_is_pub' => true` needed for something else too?

_Originally posted by @jalogut in https://github.com/magento/magento2/pull/9094#issuecomment-420965212_

**Comment by meker12** [comment]
Documentation the doc_root_is_pub option added in PR #7038. Closing this issue.
