### ISSUE TITLE
Issue with Magento access to API error code 2

### ISSUE THREAD

**Issue by noam1610** [magento/devdocs#410]
I don't find any solution on the web.
This is the error I get :

```
{ [Magento Error: An error occurred at login]
  code: 2,
  faultCode: 2,
  faultString: 'Access denied.',
  original: { message: 'XML-RPC fault: Access denied.', name: 'Error' },
  name: 'Magento Error',
  message: 'An error occurred at login' }
```

Please Help.

**Comment by tanberry** [comment]
Hi there, @noam1610. DevDocs is glad to try to help, but you will probably get a better response if you post your question on the Magneto forum, at https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2, under the "Installing Magento 2" section. You can also take a look at Magento StackExchange, at http://magento.stackexchange.com/questions/tagged/magento2. Let us know if you find any areas in our documentation that can be improved to help with your specific issue.

**Comment by xcomSteveJohnson** [comment]
Closing because of elapsed time. Please reopen if we can help you with this.
