### ISSUE TITLE
CDN and Advanced JS Bundling do not work together: /guides/v2.3/performance-best-practices/advanced-js-bundling.html

### ISSUE THREAD

**Issue by michaelscheel** [magento/devdocs#4109]
# General issue

## Description:
requirejs/text.js is used as a plugin loader for require.js, therefore usage in combination with a CDN for static assets (or another domain) does not work – require.js tries to load a .js version of .html/.json to prevent problems with CORS.

That's why https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/requirejs/text.js exists(see history). Using mage/requirejs/text in build.js isn't working either.

**Comment by shrielenee** [comment]
@DrewML we may need some assistance with this one! @bdenham is going to get this going with ya. 🏆

**Comment by michaelscheel** [comment]
Next issue: mixins (e.g. as defined in module-checkout-agreements) do not work when the module that is „mixed“ (e.g. Magento_Checkout/js/action/place-order) is included in one of the generated bundles (e.g. bundles/checkout.js). You have to exclude all js-files that have mixins defined in build.js.

**Comment by pramodraam** [comment]
Hi, Is there a workaround to make CDN and Advanced JS bundling work together? The issue I am facing is that enabling CDN adds an .js extension to those dependencies ending in .html extension. Please advise me as to what the solution is.

https://magento.stackexchange.com/questions/316025/magento-2-3-4-enabling-cdn-for-static-subdomain-results-in-some-knockout-js-dep

**Comment by meker12** [comment]
> Hi, Is there a workaround to make CDN and Advanced JS bundling work together? The issue I am facing is that enabling CDN adds an .js extension to those dependencies ending in .html extension. Please advise me as to what the solution is.
> 
> https://magento.stackexchange.com/questions/316025/magento-2-3-4-enabling-cdn-for-static-subdomain-results-in-some-knockout-js-dep

@pramodraam Thank you for your feedback! It doesn’t seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, contact [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets)—They should be able to help you with this! Let us know if you have anymore questions.

**Comment by BarnyShergold** [comment]
@meker12 - May we close this issue as you have referred the OP to support?
