### ISSUE TITLE
Broken 404 pages on search result when search MFTF on google

### ISSUE THREAD

**Issue by krishprakash** [magento/devdocs#4113]
# Bug report

## Description

Search MFTF on google and open links it 404 pages.
https://www.google.com/search?rlz=1C1GCEU_enIN830IN830&ei=15ahXJyyL9DVz7sPxu-EiAY&q=mftf&oq=mftf&gs_l=psy-ab.3..0i71l4.0.0..289712...0.0..0.0.0.......0......gws-wiz.7v9DGEs9oqI

https://devdocs.magento.com/mftf/2.2/introduction.html
https://devdocs.magento.com/mftf/2.3/introduction.html

Review the screenshot: https://www.screencast.com/t/raHURCpYBlmV

### Steps to reproduce

1. Search MFTF on google 
https://www.google.com/search?rlz=1C1GCEU_enIN830IN830&ei=15ahXJyyL9DVz7sPxu-EiAY&q=mftf&oq=mftf&gs_l=psy-ab.3..0i71l4.0.0..289712...0.0..0.0.0.......0......gws-wiz.7v9DGEs9oqI

2. Open the first two devdoc links
https://devdocs.magento.com/mftf/2.2/introduction.html
https://devdocs.magento.com/mftf/2.3/introduction.html

## Expected result

All links should working properly.

## Possible solutions

Need to set appropriate links.

**Comment by dobooth** [comment]
Hi Prakash,
 A few days ago, we moved the MFTF docs to https://devdocs.magento.com/mftf/docs/introduction.html.
This was part of our change to a multi-repo setup. 
It will take some time for Google to update its' index to find the new URL.
Thanks for taking the time.
