### ISSUE TITLE
Magento 2.2.x does not support PHP 7.2

### ISSUE THREAD

**Issue by ashsmith** [magento/devdocs#4118]
# Bug report

## Description

DevDocs states that Magento 2.2.x supports PHP 7.2, which is not true.

Commit that made the change: https://github.com/magento/devdocs/commit/9c03365ae06e06eb23c4344b24f1018ff6952c3d#diff-2c0a624a75cf786e8905587c1042634d

Link to page in DevDocs: https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

## Expected result

DevDocs should state that php 7.2 is not supported.

## Actual result

Upon running composer update (whilst running php 7.2) I receive:

```
$ bin/magento composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/product-community-edition 2.2.8 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - magento/product-community-edition 2.2.8 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - Installation request for magento/product-community-edition 2.2.8 -> satisfiable by magento/product-community-edition[2.2.8].
```

**Comment by dobooth** [comment]
Fixed.
