### ISSUE TITLE
The value isn't correct in the example.

### ISSUE THREAD

**Issue by YaroslavHolovanych** [magento/devdocs#4169]
# Bug report

## Description
The value isn't correct in the example.

### Steps to reproduce

1. Go to [Usage examples](https://devdocs.magento.com/mftf/docs/commands/codeception.html#usage-examples)

## Expected result

`<group value="skip"/>` **instead** `<group value="skpip"/>`

**Comment by dobooth** [comment]
Fixing with https://github.com/magento/magento2-functional-testing-framework/pull/328
