### ISSUE TITLE
The page link is absent in the "Sensitive data" section.

### ISSUE THREAD

**Issue by YaroslavHolovanych** [magento/devdocs#4171]
# Bug report

## Description
The page link is absent in the "Sensitive data" section.

### Steps to reproduce

1. Go to [Sensitive data](https://devdocs.magento.com/mftf/docs/data.html#sensitive-data)

## Expected result
The text contains the link to Credentials page **instead** [Credentials][].

**Comment by dobooth** [comment]
Fixed with above merge.
