### ISSUE TITLE
Convert docx document to PDF or other free viewable format

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#4182]
# Document conversion

## Topic Link

https://github.com/magento/devdocs/blob/master/common/pdf/Pre-Launch.Checklist_4_23_2018.docx

## Description

The document is in the `docx` format that requires to use proprietary software from a user.

## Possible solutions

Convert the document to PDF or other format freely available for the open-source community to work with. (Ideally, to a devdocs topic.)

**Comment by dshevtsov** [comment]
@meker12 any progress with this issue?

**Comment by meker12** [comment]
No.  We don't own this document, but I will follow up with the owner.  We also have a MAGEDOC issue that was recently entered.

**Comment by meker12** [comment]
Fixed in #6083.
