### ISSUE TITLE
Page not found when open "Magento product availability"

### ISSUE THREAD

**Issue by williankeller** [magento/devdocs#4201]
# Bug report
When trying to open the following URL, seems it's redirected to a new one, which doesn't exist. Even searching at Google, etc. We got the 404 page.
Page: https://devdocs.magento.com/availability.html

### Steps to reproduce
1. Open https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.html
2. Search for _Magento 2.3 product availability_
3. Click on it.

----

1. Search for _Magento 2.3 product availability_ at Google
2. Click on it.

## Expected result

Open the "Magento product availability" page.

**Comment by jeff-matthews** [comment]
Thanks for reporting this @williankeller. There seems to be an issue with the redirect. I'm workiong on a fix, but in the meantime, just remove the `.html` from the URL and the page will resolve.

**Comment by jeff-matthews** [comment]
I created a temporary fix to prevent a 404 from that particular link, but the real fix is to update the link.
