### ISSUE TITLE
There are missing feature on queue:consumes:list command

### ISSUE THREAD

**Issue by sanganinamrata** [magento/devdocs#4233]
# New topic request
There are some missing feature for **queue:consumes:list** command https://devdocs.magento.com/guides/v2.3/comp-mgr/install-extensions/b2b-installation.html

## Content checklist

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains code samples that shows ____.
- [ ] Other (please specify)

**Comment by dobooth** [comment]
We haved moved the file that is referenced here but we are working to update the content with another PR.

**Comment by keharper** [comment]
Copying this comment from #4234

I don't want to list every consumer that is added to the system, so if you choose to open a new PR to address the issue, either rewrite the procedure to avoid giving the impression that only 2 consumers exist, or state that the two consumers are among those listed in the output. Thanks!

**Comment by gelanivishal** [comment]
@keharper I'm not getting you, Do you want to update it or not? If yes then I'll create a new PR for https://devdocs.magento.com/extensions/b2b/ document. Let me know.
