### ISSUE TITLE
There is path issue on document

### ISSUE THREAD

**Issue by gelanivishal** [magento/devdocs#4239]
# Bug report
There is file path issue.

### Steps to reproduce

1. Go to this link https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html
2. <Magento_root_directory/setup/src/Magento/Setup/Model/Declaration/Schema/ - I didn't get on file system

## Expected result
N/A

## Possible solutions
- Update as per file system

**Comment by dobooth** [comment]
Assigning to you for completeness with the PR.

**Comment by triabhishek95** [comment]
This is resolved here with the commit [cc7734b](https://github.com/magento/devdocs/pull/4240/commits/cc7734b47942622aad849a3a0dcaacef56331381) but it is yet to be merged.

**Comment by atwixfirster** [comment]
https://github.com/magento/devdocs/pull/4240 has been merged. 

@jeff-matthews , could you please resolve this issue?

Thank you!
