### ISSUE TITLE
Parameter issue on company account

### ISSUE THREAD

**Issue by sanganinamrata** [magento/devdocs#4244]
# Bug report

## Description
There are some parameter issue on companyCompanyRepositoryV1 API, Please check attached screenshot
![2019-04-15_18-02-50](https://user-images.githubusercontent.com/37930646/56132930-e73a1a80-5fa8-11e9-8eef-3bb4679e81ba.jpg)

### Steps to reproduce

1. https://devdocs.magento.com/guides/v2.3/b2b/company-object.html
2. Check attached screenshot

## Expected result
You have to add missing parameters on docs.

**Comment by keharper** [comment]
Closing because the company admin is defined in a different call in REST.  See [Manage company users](https://devdocs.magento.com/guides/v2.3/b2b/company-users.html) for more info,
