### ISSUE TITLE
Feedback on page: /guides/v2.3/extension-dev-guide/prepare/lifecycle.html

### ISSUE THREAD

**Issue by harrykumar123** [magento/devdocs#4259]
# General issue
Example: Customer module’s InstallData.php 
The example url not working InstallData.php
Its showing 404

**Comment by jcalcaben** [comment]
File removed in:
https://github.com/magento/magento2/commit/4236163c7115ee06fd85863a1d9fcdbfda46d152#diff-986f265e758f4cfe394a816b9e9c9727

Related to: MAGETWO-87551

**Comment by keharper** [comment]
@harrykumar123 Thanks for identifying this issue. This topic is out of date for 2.3, except for these sections:

* Recurring schema event
* Recurring data event

See [Declarative schema overview](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/) for information about the new standards.

**Comment by keharper** [comment]
The work for this issue now entails:

* Determining whether new information needs to be added for the lifecycle in 2.3+, or whether to delete the topic
* Possibly finding a new home for the two sections that aren't outdated (see above)
* Possibly updating links

**Comment by harrykumar123** [comment]
Ok Thanks
