### ISSUE TITLE
Feedback on page: /guides/v2.3/extension-dev-guide/versioning/dependencies.html

### ISSUE THREAD

**Issue by robsch** [magento/devdocs#4278]
Isn't this contradictory on the page:

> 2. Do not specify a dependency on meta packages (e.g. product-community-edition).

But on [Check the Magento version](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/check-version.html) one way is to look into the composer.lock file and look at `magento/product-community-edition` to find out the version.

So why not specify a dependy to product-community-edition?

**Comment by keharper** [comment]
@robsch The "Module version dependencies" topic discusses versioning considerations when developing a new module. The "Check the Magento version' topic just lists the least-preferred way to determine what version you're currently running. There's no contradiction here.
