### ISSUE TITLE
Tables overflow the content area if cell contains unbreakable text

### ISSUE THREAD

**Issue by belbiy** [magento/devdocs#4294]
# Bug report

## Description

See https://devdocs.magento.com/guides/v2.3/extension-dev-guide/webapi/request-processor-
pool.html

This bug was introduced with https://github.com/magento/devdocs/pull/4105.
Since all our tables have `table-layout: auto` issues like this sometimes can happen.

### Steps to reproduce

Open the page with the table that has long lines:
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/webapi/request-processor-
pool.html

## Expected result

Table should not overflow the page content.

## Possible solutions

Make table scrollable?
Add `table-layout:fixed` by applying a `{: .fixed}` class to it.

**Comment by hitesh-wagento** [comment]
I am working on this issue
