### ISSUE TITLE
Feedback on page: /guides/v2.3/ui_comp_guide/components/wysiwyg/configure-tinymce-editor.html

### ISSUE THREAD

**Issue by svossen** [magento/devdocs#4315]
# General issue
The documentation page didn‘t mention anything about adding two modules to the load order. Without adding the modules `Magento_Cms` and `Magento_PageBuilder`, it’s not possible to override the Pagebuilder default TinyMCE configuration.

## Description:

Documention lacks sufficient information to properly override the PageBuilder TinyMCE configuration.

## Possible solutions:

Please mention to add these two modules to the load order of the custom module.
```
<sequence>
    <Magento_Cms />
    <Magento_PageBuilder />
</sequence>
```

**Comment by dobooth** [comment]
@bdenham what's the holdup here?
