### ISSUE TITLE
docs about creating LESS symlinks are wrong (outdated?)

### ISSUE THREAD

**Issue by pantaoran** [magento/devdocs#433]
I'm debugging a problem where /media/styles.css is not found (404), and I tried following the instructions of the official documentation here: https://github.com/magento/devdocs/blob/develop/guides/v2.0/config-guide/cli/config-cli-subcommands-less-sass.md

but that does not work in the official 2.0.0 release. typing `bin/magento dev:css:deploy` results in `[InvalidArgumentException] There are no commands defined in the "dev:css" namespace.`

So the docs are wrong for the official release, now what should I do instead? This must have changed somehow? I've seen people advising to type `bin/magento setup:static-content:deploy`, is this related? The docs somewhere mentioned that this was for production mode, but I'm currently trying developer mode, should I still do this? I tried it but nothing changed.

**Comment by xcomSteveJohnson** [comment]
Is Magento installed? If not it's one possible cause of the "There are no commands defined in the.." error.

**Comment by pantaoran** [comment]
Yes it's freshly installed and working. The `bin/magento --list` listing also does not show any commands starting with `dev:css`.

**Comment by xcomSteveJohnson** [comment]
Have you tried [magento setup:static-content:deploy](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html#config-cli-subcommands-xlate-dict)?

**Comment by pantaoran** [comment]
I have already done 3 installations under different circumstances, on my host directly as well as in docker containers, with and without sample data, etc. I didn't see any warning/error messages and everything works perfectly (the problem I mentioned in the first post was resolved by re-installing Magento).
Also yes, I have deployed the static content.

I have never seen that command listed. Are you sure it wasn't removed recently or something like that?

**Comment by xcomSteveJohnson** [comment]
Thanks for bringing this up. I also don't see this command in CE or EE. Created internal issue MAGETWO-46415 to investigate.

**Comment by xcomSteveJohnson** [comment]
Try `magento dev:source-theme:deploy`

**Comment by pantaoran** [comment]
great, thanks.
