### ISSUE TITLE
How do I: Read from a Merged Configuration Tree?

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#435]
Suggestion for

http://devdocs.magento.com/guides/v2.0/howdoi/bk-how-do-i.html

How do I, as a module developer, read data from a merged configuration tree? (the merged `events.xml`, `module.xml`, `di.xml`, etc)

How do I, as a module developer, create my own configuration file that other modules can merge in `app/etc/`?

**Comment by xcomSteveJohnson** [comment]
After discussing internally, we decided this is not a good how-to topic. We have an internal issue on something similar, MAGETWO-38492.

We expect to have some kind of UI that shows this in a future release.

**Comment by antonkril** [comment]
@astorm every configuration type is represented by separate object (example: `Magento\Framework\Event\Config` for `events.xml`). You can get merged configuration from those objects. Do you want to have the full list of such objects documented?

Does [this presentation](https://www.youtube.com/watch?v=lhnRrwJq8ok&feature=youtu.be&t=870) cover the topics you want to be described?
