### ISSUE TITLE
Page "Set the mode (MAGE_MODE)" does not tell me how to set the mode

### ISSUE THREAD

**Issue by pantaoran** [magento/devdocs#437]
The page here:
https://github.com/magento/devdocs/blob/develop/guides/v2.0/config-guide/bootstrap/magento-modes.md

It explains all about what the 3 modes are intended for and what they do, but it does not tell me how to set the mode, even though the page title is "set the mode". I think that can be improved.

Please include a section which mentions the CLI command: `magento deploy:mode:set <mode>`

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing out that regrettable oversight. Fixed now; if you're happy with it, please close this issue.

**Comment by pantaoran** [comment]
Thanks, now it makes more sense.
