### ISSUE TITLE
Clarify full page cache recommendations

### ISSUE THREAD

**Issue by mttjohnson** [magento/devdocs#438]
There is a warning listed on the Varnish Configuration page http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish.html

> We strongly recommend you use Varnish in production instead of the default full-page caching. Full-page caching (to either the file system or database) is much slower than Varnish, which is designed to accelerate HTTP traffic.
> 
> Full-page caching is acceptable in a development environment.

There was a bit of discussion surrounding some label changing inside the Magento configuration section that appears misleading. magento/magento2#2585

I would suggest updating the Varnish Configuration page to reflect the fact that the built-in cache is a valid and acceptable option for full page caching for a production implementation of Magento 2. It may not be the best, and I would retain the strong recommendation for Varnish, but a warning seems to imply there are problems with not using Varnish on this page. Instead of a warning, maybe it should be represented more like a tip to call out.

This note could also use some more clarity in differentiating between the two types of full page caching, "built-in" and the "varnish" options. The default "built-in" full-page caching is not specifically stated in reference to the `Full-page caching (to either the file system or database)`. 

The later statement about full-page caching being acceptable in a development environment doesn't clearly differentiate the two options to state the recommendation well, or explain anything about its use in a development environment. I expect you could use the built-in or varnish full-page caching acceptably in a  development environment, as well as a production environment, so this statement does not seem to have much of a point. There is likely more overhead in working with either option in a development environment (though valuable and likely necessary), and if it is planned for use in production then development and testing should incorporate the implementations also.

**Comment by xcomSteveJohnson** [comment]
Just updated [the note](http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish.html). Let us know what you think.

**Comment by mttjohnson** [comment]
Looks great, thanks!
