### ISSUE TITLE
Getting 404 Market Place link on The composer.json file Page

### ISSUE THREAD

**Issue by sagarppanchal** [magento/devdocs#4391]
# Getting 404 Market Place link on The composer.json file Page

### Steps to reproduce

1. Click on the above given 
2. Scroll upto Magento Marketplace Extensions Paragraph
3. Click on the Magento Marketplace (https://docs.magento.com/marketplace/user_guide/getting-started-seller.html)
4. You will get 404, [CLICK HERE](https://ibb.co/3pWks4n)
5. Here is the existing link [CLICK HERE](https://ibb.co/YQkPzh2)

## Expected result

This link should be open

https://marketplace.magento.com/

**Comment by lorikrell** [comment]
Investigating the Marketplace User Guide (outside of DevDocs), the content is not available in the guide in any other topic. 
Recommend this topic for more info on Vendor Name, where located in Marketplace, etc https://docs.magento.com/marketplace/user_guide/sellers/company-profile.html. Or removing the sentence.

**Comment by dobooth** [comment]
Fixed with above merge.
