### ISSUE TITLE
Fetching all products in a particular category which are in stock using SOAP API V1.1

### ISSUE THREAD

**Issue by SyedTayyab** [magento/devdocs#442]
Hi,
I am looking for an API call that would allow me to fetch all products in a particular category which are in stock (qty > 0). The problem is that apparently there is no call that can achieve this. The "catalog_product.list" doesn't filter on categories anymore since 1,4 and "catalog_category.assignedProducts" can't have filters. 

I'm stuck!!! Please help me. 

P.S.: I'm consuming magento API through a PHP client and I don't have write permissions to the magento core files.

**Comment by keharper** [comment]
Thanks for your question.  We're looking to find an answer. You are using M1, correct?

**Comment by xcomSteveJohnson** [comment]
@SyedTayyab  Any update? Is this issue about Magento 1 or Magento 2?

**Comment by keharper** [comment]
Closing. Feel free to re-open.
