### ISSUE TITLE
Inconsistent URL of file references in 2.3 Devdocs

### ISSUE THREAD

**Issue by realadityayadav** [magento/devdocs#4422]
# Bug report

## Description

Even though the guide is of Magento 2.3 but the file URL's to GitHub point to Version 2.2 like 

![image](https://user-images.githubusercontent.com/25526193/57175363-ab3bfc00-6e68-11e9-8eae-eb1e2bd4a22b.png)

Same is for 
https://devdocs.magento.com/guides/v2.3/config-guide/log/log-magento.html 
The di.xml reference takes to the 2.0 version of it.

## Expected result
The file should be pointing to its appropriate version on GitHub according to the guide being viewed.

## Possible solutions

The issue lies in file 
devdocs/guides/v2.3/ui_comp_guide/components/ui-multiselectcolumn.md
which inherits devdocs/guides/v2.2/ui_comp_guide/components/ui-multiselectcolumn.md but this file should be created itself with correct URL's to apt version files.
Or there is a better way to handle it?

**Comment by Ketika** [comment]
I am working on this at #dmcdindia19

**Comment by Ketika** [comment]
I am working on this at #dmcdindia19

**Comment by realadityayadav** [comment]
@ketika what will be the correct way since I asked about it?

**Comment by realadityayadav** [comment]
@ronak2ram can you suggest the correct way to make these changes so that I can go ahead and create the Pull Request for it?

**Comment by ronak2ram** [comment]
Hie @realadityayadav 
As per my suggestion not need to do any change.
Because if you refer di.xml example. then [di.xml](https://github.com/magento/magento2/blob/2.0/app/etc/di.xml#L9) is showing `<preference for="Psr\Log\LoggerInterface" type="Magento\Framework\Logger\Monolog" />` and same code showing in [2.1](https://github.com/magento/magento2/blob/2.1/app/etc/di.xml#L9), [2.2](https://github.com/magento/magento2/blob/2.2/app/etc/di.xml#L10) and [2.3](https://github.com/magento/magento2/blob/2.3/app/etc/di.xml#L10). so there is no change in the latest version of Magento files. if there is any change in the latest Magento version then we have to change it.

**Comment by erikmarr** [comment]
Hi @realadityayadav thank you for filing a bug report. With symlink files, we cannot have unique URLs based on the devdocs version. This is a known issue that we hope to resolve in a future release when we incorporate a more robust branching strategy.

**Comment by realadityayadav** [comment]
Ok Thanks @erikmarr & @ronak2ram for your comments. 
The base I believe why this needs correction is because Even though the general lines mentioned might be similar but the concept of viewing a 2.3 doc means to look over 2.3 Magento Code and not 2.0 code. 
This is very much inconsistent logically. So until a robust branching strategy is made should we help to find and resolve such figures as @williankeller did reference in his pull request [https://github.com/magento/devdocs/pull/4454](url) ?

**Comment by lorikrell** [comment]
The best short term solution is to remove the symlink files. Create new files using the original per version, changing the link to the code files per version. If anyone needs help, can definitely provide more info!

**Comment by realadityayadav** [comment]
I am working on this.
#ContributionDay

**Comment by realadityayadav** [comment]
#ContributionDay

**Comment by jeff-matthews** [comment]
I don't think that removing all the symlinks in our project just to replace variables with the correct version is the best short-term solution at all. We have hundreds of symlinked files and we could potentially receive hundreds of PRs about this, which is not a good use of our time.

If we were to proceed with breaking symlinks, we would do so all at once as part of an internal project.

**Comment by realadityayadav** [comment]
Great you got this resolved @dshevtsov

**Comment by erikmarr** [comment]
Thanks @realadityayadav for raising this issue! As you can see, @dshevtsov was able to implement a fix internally and his PR has been merged (https://github.com/magento/devdocs/pull/4518).
