### ISSUE TITLE
README content for modules - work in M2 Code

### ISSUE THREAD

**Issue by lorikrell** [magento/devdocs#4451]
# Topic clarification/correction request

## Topic Link

All modules documented in the Open Source and Commerce 
 of the [Module Reference Guide](https://devdocs.magento.com/guides/v2.4/mrg/intro.html) pull the content from the READMEs in Magento 2 code. To add content, create PRs to Magento 2 core!

## Solution

We need Modules documented in the Magento 2 source code. 
2.4: https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento

- We have a template for you to use: [Magento module readme template](https://github.com/magento/devdocs/wiki/Magento-module-README.md)
- As you add PRs to Magento 2 core, add a link to this issue. 
- We can review your PR in Magento 2. 
- The merged PRs will be pulled by our doc process, automatically adding content to DevDocs!

**Comment by diazwatson** [comment]
Hi guys, can I have this assigned to me please?

**Comment by jeff-matthews** [comment]
@diazwatson, assigned to you. It looks like we still need to provide you with a README template before you can start work. 

@dshevtsov, is there a template available?

**Comment by diazwatson** [comment]
Yes please.
From what I can see Readme files need to be created for all modules in m2 repo, then (once change merged) referenced in these 2 pages. Is this correct?

**Comment by jeff-matthews** [comment]
Yes, that's correct @diazwatson.

**Comment by dshevtsov** [comment]
@jeff-matthews, the template is in our internal wiki and has to be published.

**Comment by jeff-matthews** [comment]
@diazwatson, I attached the template to this comment. GitHub won't accept a Markdown (.md) file attachment, so I changed it to `.txt`. After you download it, just change the extension to `.md`.

[module-readme-template.txt](https://github.com/magento/devdocs/files/3443413/module-readme-template.txt)

**Comment by diazwatson** [comment]
Thanks for sorting that @jeff-matthews I think I have everything to start

**Comment by jeff-matthews** [comment]
No problem! Thanks for volunteering to work on this. I also created a public gist of the template: https://gist.github.com/magento-docbot/dfb8cc7db6519da14fc92b890d49b7d3

**Comment by keharper** [comment]
Make sure any links that point to devdocs contain the proper version in the URL. The template shows links with "2.1".

**Comment by jeff-matthews** [comment]
Thanks for pointing that out @keharper. I just fixed the gist, but the file attached to my previous comment still has the old 2.1 links.

**Comment by diazwatson** [comment]
A bit of update in here:
I am planning to submit more PR in the next few days and expecting to complete this task by the end of December

**Comment by shrielenee** [comment]
Hey @diazwatson --- Are you still planning to do more work on this?

**Comment by diazwatson** [comment]
Yes

**Comment by shrielenee** [comment]
Removing you as assignee @diazwatson. If you want to pick this up again in the future, please do!

**Comment by korovitskyi** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@korovitskyi I think there are more modules that need to be updated.  Can I also join the show? If you okay with that.

**Comment by korovitskyi** [comment]
Hi @chiranjeevi-cj !
Sure.
I think you should start from the button of modules list to avoid conflicts.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by vlmed** [comment]
@magento I am working on this

**Comment by ProkopovVitaliy** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
Great to see all this progress!

**Comment by dshevtsov** [comment]
Seemed like an unintentional closure via a closing keyword.

**Comment by engcom-Hotel** [comment]
Adding appropriate labels to create a JIRA ticket.
