### ISSUE TITLE
PHP syntax highlighter not indenting correctly

### ISSUE THREAD

**Issue by robbieaverill** [magento/devdocs#449]
See: http://devdocs.magento.com/guides/v2.0/coding-standards/docblock-standard-general.html

It appears that doc blocks for example with one space at the beginning of the line (e.g. ` * @var string`) have the first character trimmed.

I forked the page to fix, only to find that the source contains the correct level of formatting and that the preview functionality didn't actually render the code block.

*Input:*

```
/**
 * Some doc block
 * @return self
 */
```

*Expected:*
```
/**
 * Some doc block
 * @return self
 */
```

*Actual:*
```
/**
* Some doc block
* @return self
*/
```

**Comment by xcomSteveJohnson** [comment]
Yes, we're aware of this but do not know a solution. Any ideas?

**Comment by robbieaverill** [comment]
@xcomSteveJohnson nope. Is it a GitHub widget that parses the input? If so I'm happy to close and open this with them.

**Comment by xcomSteveJohnson** [comment]
I'm not sure. I'll update you if I find out something interesting.

**Comment by xcomSteveJohnson** [comment]
It appears the issue affects PHP code samples only. Still don't know a solution.

**Comment by dshevtsov** [comment]
Just fixed. @robbieaverill please check.

**Comment by robbieaverill** [comment]
@dshevtsov  Looks good. Thanks!
