### ISSUE TITLE
B2B company credit discussion incomplete

### ISSUE THREAD

**Issue by jfrontain** [magento/devdocs#4492]
Ticket created at Imagine 2019 Contribution Day.
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/b2b/user_guide/sales/credit-company.html

## Description
The discussion of company credit needs clarification and additional information. This observation was made by a developer translating the docs into German, where the term "credit" can be translated in my ways. 

## Additional information

Another discussion in the doc set that might be useful: https://devdocs.magento.com/guides/v2.3/b2b/credit-manage.html

**Comment by nicolashibrido** [comment]
Something like this can help?

The limit value of credit granted by the seller to the purchasing company is to enable agility in PO purchases, if necessary
The value of the credit is defined by the seller for each company, and the credit possibility for the companies to make the purchase without payment at the moment, accumulating several buy for later payment according to the negotiation that this one has with the seller.

**Comment by lorikrell** [comment]
Thanks @nicolashibrido ! Will check this out for adding to the Admin User Guide.

**Comment by lorikrell** [comment]
Removing the Contribution Day label as the repo for working this issue is not open yet for open source contribution.

**Comment by lorikrell** [comment]
Closing issue and moving to the new MerchDocs repo. The repository and contribution submissions for the Magento Merchant content (User Guide) will be available at a later date. Thank you!
