### ISSUE TITLE
Provide detailed steps of how you can execute tests on your local machine before creating a PR

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#4495]
# Community engineering issue

Type of Doc:
- [x] New topic
- [ ] Topic Update, Devdoc link: 
- [ ] Other

Magento 2 version:
- [ ] 2.1.X
- [x] 2.2.X
- [x] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface?
- [ ] New software requirements?
- [ ] New REST endpoints or updated GraphQL query syntax?
- [ ] New command line option?

## Content

Hi!

When creating a PR on the magento2 repo, there are a bunch of [automated tests](https://github.com/magento/magento2/wiki/Magento-Automated-Testing) which get executed. But there currently doesn't seem to be a clear explanation of how to execute these tests yourself.
It would be nice if we have some documentation which says how to run those tests, so we can already prepare the PR ourselves to get accepted faster and not having to go back and forth and wait until the automated tests have run after changing something.
There is already some good documentation around [how to run unit tests](https://devdocs.magento.com/guides/v2.3/test/unit/unit_test_execution_cli.html), but the other tests (static tests for example) are not documented properly I think. There is [this page](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-test.html), which says to call `bin/magento dev:tests:run static`, but that doesn't seem to give the same results as the static tests ran through automatisation.

## Additional information

For example, I created a PR https://github.com/magento/magento2/pull/22733 which apparently failed on some static tests. And then a Magento developer fixed those. Which is great btw, but I would like to be able to see those failures myself and fix them myself if possible before creating the PR.
When [asking](https://github.com/magento/magento2/pull/22733#issuecomment-491242429) how to execute these static test, I didn't get a very clear answer, so I went looking in the documentation where to find information regarding that and I couldn't find anything around it (unless I missed it somehow).

Thanks!

**Comment by lorikrell** [comment]
@hostep, great request! I'm working with @dmanners on a set of [Beginner Guides](https://github.com/magento/magento2/wiki/Getting-Started) and the [wiki](https://github.com/magento/magento2/wiki) for Magento2 repo to document some of this information. I've assigned myself to the ticket, and will work towards that content. 

We've covered the Issue process. Next is PR! More info soon for this one.

**Comment by DanielRuf** [comment]
Exactly the issue that I face at the moment.
It is not clear how and what is running behind the curtains on the new private CI setup (no logs?).

**Comment by erfanimani** [comment]
I can second this request. The instructions on running tests are quite confusing at the moment.

Is it for core code? Is it for custom code in app/code? Are you supposed to use the phpcs/phpunit commands or dev:tests:run? What's up with Magento ignoring `Magento2.Files.LineLength.MaxExceeded` when the Magento2 standard actually throws `Generic.Files.LineLength.TooLong`? Why is the Magento2 coding standard failing on core code?

**Comment by dobooth** [comment]
Hi @hostep. Do you think that #7951 takes care of this issue?

**Comment by hostep** [comment]
Maybe, I'll try to check it out later when I find some more time, sorry 🙂

**Comment by BarnyShergold** [comment]
@hostep @dobooth - it was suggested 6 months ago that #7951 took care of this issue - can this be confirmed? Can we close this issue?

**Comment by hostep** [comment]
@BarnyShergold: feel free to close it, I never found the time to properly test this again. I'll open a new issue next time I encounter this problem again.

**Comment by BarnyShergold** [comment]
Closed in agreement
