### ISSUE TITLE
Table content containing glossary tags incorrectly forces a new table row

### ISSUE THREAD

**Issue by ProcessEight** [magento/devdocs#4505]
# Bug report

## Description

On this page: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html
In the 'Declare Extension Attributes' section, there is a table.
The second row of the table begins with 'that processes the extensions. '. However, that line of text should in fact be part of the second cell of the first row (the cell that begins with 'The fully-qualified type name with the namespace').
It appears that when the table content contains glossary tags, everything after the closing glossary tag is forced into a new table row.
See also the table rows 'ref' and 'join_on_field' in the same table.

The markdown looks syntactically correct, however:
https://github.com/magento/devdocs/blob/master/guides/v2.3/extension-dev-guide/attributes.md

### Steps to reproduce

1. Visit https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html
2. Review the 'Declare Extension Attributes' table
3. Note that the rows underneath the rows beginning with 'for', 'ref', 'join_on_field' all contain the rest of the sentence started in the second column of the previous row.

## Expected result

The text in the first row, second column should read 'The fully-qualified type name with the namespace that processes the extensions. The value must be a type that implements ExtensibleDataInterface. The interface can be in a different module.', as it is defined in the markdown file. The text in the first row, third column should read 'Magento\Quote\Api\Data\TotalsInterface', again as it is defined in the markdown file.

**Comment by jcalcaben** [comment]
A possible solution for this would be to remove the surrounding glossary tag.

**Comment by shrielenee** [comment]
This issue appears to have been resolved for v2.3 via #4584. I will make any table fixes (there are some link issues for 2.1 and 2.2 versions).

**Comment by shrielenee** [comment]
This has been fixed in #4834 - closing.
