### ISSUE TITLE
Feedback on page: /guides/v2.3/cloud/project/sendgrid.html

### ISSUE THREAD

**Issue by kurund** [magento/devdocs#4525]
# General issue
This page should be removed as SendGrid does not support v2.3

**Comment by hguthrie** [comment]
This is typically Magento version agnostic. @kurund  Could you provide more information why you think it should be removed?

**Comment by hguthrie** [comment]
@kurund if you are referring to the module : https://marketplace.magento.com/sendgrid-email-delivery-simplified.html
Cloud does **not** use the module, but rather the SMTP proxy service.
