### ISSUE TITLE
How To: What Replaces Mage::getConfig() in Magento 2?

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#453]
Essentially [reopening this](https://github.com/magento/devdocs/issues/435#issuecomment-164853626) -- I can't see the internal ticket so I'm not sure of the rational, **but** maybe if the same questions were cast differently the real need for a "how to" might be clearer.

Magento 1 has/had a global configuration tree, built from merging the XML configuration of all modules.  This is a common pattern in module oriented systems.  

The configuration tree was accessible via code that looked something like this.

    Mage::getConfig()->getNode('path/to/value');
    
i.e. Module developers could examine the merged tree and take programatic action based on the merged values.  This was/is a very common module development task.

Without clear guidance from the core Magento team, developers are in the dark on how to access configuration values from Magento 2's merged configuration trees.  This leaves developers migrating a Magento 1 module to Magento 2 without a clear path forward.  Without that clear, official, "`@api` blessed" path forward, each individual developer/team will come up with their own inconsistent, fragile way of reading the merged configuration trees. This will either tie the hands of the core development team going forward, or break merchant systems that use these modules. 

If third party developers are expected to work with the system they need this guidance.

**Comment by tanberry** [comment]
Thanks for this good question, @astorm. We're getting with one of the core dev team architects, will then get back to you with more info. Question for my sake: are you looking for the process by which one would even create/generate this merged config tree in order to see all values in one place, or are you/developers looking for low-level guidance on how to "use" these values once they are all readily visible in the merged tree?

**Comment by astorm** [comment]
@tanberry More the former than the later.  Basically, the information in this article

http://devdocs.magento.com/guides/v2.0/config-guide/config/config-files.html

With a "how to" that outlines how to use all the various classes/interfaces etc to read from the a merged configuration file.  This seems like the sort of basic "computer plumbing" style task that should have a simple, clear way to approach for the basic case.

**Comment by xcomSteveJohnson** [comment]
@astorm After internal discussion, we decided this should not be documented. We have internal issue MAGETWO-38492 to track a module reference, which is expected to be dynamically generated like Swagger for APIs. This should help.

I also created internal issue MAGEDOC-2497 to improve the current documentation.

Closing; please reopen if you disagree.

**Comment by xcomSteveJohnson** [comment]
Internal issue MAGETWO-47808

**Comment by xcomSteveJohnson** [comment]
Oops, opened a duplicate. Closing again.
