### ISSUE TITLE
Installing Data Migration Tool for Enterprise Edition

### ISSUE THREAD

**Issue by Caprico85** [magento/devdocs#454]
You might want to add instructions on how to install the Data Migration Tool for Enterprise Edition. The instructions on http://devdocs.magento.com/guides/v2.0/migration/migration-tool-install.html only installs the Migration Tool for CE.

It took me some hours of googling, trying and asking the support until I discovered that the correct command to install from repo.magento.com is `composer require magento/data-migration-tool-ee:<version>` (note the `-ee`). I don't know how to install the EE tool from Github, but that is not important for me anyways.

**Comment by xcomSteveJohnson** [comment]
Refer to internal issue MDVA-55

**Comment by xcomSteveJohnson** [comment]
@Caprico85 I understand that Support is working on this. You have probably already contacted them but if not, please do.

**Comment by xcomSteveJohnson** [comment]
@Caprico85 Documentation has been updated. Have you tried it for EE lately?

**Comment by Caprico85** [comment]
I updated my installation today. Data migration tool 2.0.2 now includes all configuration files for Magento EE (in migration tool 2.0.0 they were missing). So the instructions on the page are entirely correct.

Thank you!
