### ISSUE TITLE
Inadequate solution in trobleshoot: After installing, images and stylesheets do not load; only text displays, no graphics 

### ISSUE THREAD

**Issue by kiatng** [magento/devdocs#459]
I spent many hours trying to figure out: [After installing, images and stylesheets do not load; only text displays, no graphics] (http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_no-styles.html). The reason I have this issue is because I am on a shared hosting with cPanel, which has restriction on permissions: the directories must be 755 and files must be 644. It also has restriction on changing *Owner/Group*.  The solution to my issue is not **server rewrites** as suggested in the doc. Unfortunately, I am a noob and still quite stuck with this issue. Ref [Magento 2 issue 2412] (https://github.com/magento/magento2/issues/2412).

Also, I may be wrong, but the appearance of directories in `pub/static`:

> Magento static assets should be located under <your Magento install dir>/pub/static/ (there should be frontend and adminhtml directories).

may depends on the [mode] (http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html?cx=018116925022773002786%3Aklu67apuihk&ie=UTF-8&q=pub%2Fstatic#searchResultsBox). If so, then it will help a lot to list the expected directories for each mode.

**Comment by xcomSteveJohnson** [comment]
We're sorry for the troubles you had. Shared hosting is obviously an issue that the Magento code needs to better account for. I could not even set up Magento 2 on shared hosting because the provider doesn't support MySQL 5.6. 

Close this issue and will track 2412.
