### ISSUE TITLE
Setup Nginx server and Php Fpm

### ISSUE THREAD

**Issue by mrkhoa99** [magento/devdocs#460]
Hello,

I don't see the guide for installing Nginx server and Php Fpm? I think we should have this guide.

**Comment by xcomSteveJohnson** [comment]
This is on the radar but with no ETA. We have not had time to do it so far and not sure it will get done anytime soon. Suggest you raise the issue on the [Magento 2 GitHub](https://github.com/magento/magento2/issues) so it gets the attention of Products.

Closing.

**Comment by jeff-matthews** [comment]
This issue should be linked to [PR 798](https://github.com/magento/devdocs_internal/pull/798) in the devdocs_internal/ repo. That PR is currently under review and could potentially resolve this issue.

**Comment by jeff-matthews** [comment]
[PR 798](https://github.com/magento/devdocs_internal/pull/798) addresses a separate issue, so I'm going to open a new PR for this issue.

**Comment by jeff-matthews** [comment]
See [PR 1047](https://github.com/magento/devdocs_internal/pull/1047) in devdocs_internal/ repo

**Comment by jeff-matthews** [comment]
The new topic is now live:

http://devdocs.magento.com/guides/v2.1/install-gde/prereq/nginx.html
