### ISSUE TITLE
Link missing on page: /guides/v2.3/frontend-dev-guide/translations/xlate.html

### ISSUE THREAD

**Issue by bassplayer7** [magento/devdocs#4601]
# General issue

There is a placeholder / missing link on the Translation page.

## Description:

Under [the heading](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/translations/xlate.html#m2devgde-xlate-generatortool) this link does not exist:
> For more information, see [dictionary generator tool].

## Possible solutions:

If there is currently a page on this it should be included. If not, perhaps change the sentence to: "We intend to publish more information on this technique at a later time."

**Comment by hguthrie** [comment]
Looks like there is an attempt to fix this broken link in #4998
