### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/prereq/prereq_updater.html

### ISSUE THREAD

**Issue by cihatzafer** [magento/devdocs#4614]
# General issue

## Description:

https://github.com/magento/magento2-updater is not available.

## Possible solutions:

Information about its history and if exist, its replacement.

**Comment by shrielenee** [comment]
@dshevtsov This repo hasn't been updated in some time. Do you have information on the updater?

**Comment by dshevtsov** [comment]
There is a similar issue #3178

**Comment by lorikrell** [comment]
@cihatzafer thank you for your feedback! We have an older open ticket for this issue here https://github.com/magento/devdocs/issues/3178. We will work to get this resolved/updated.
