### ISSUE TITLE
magento 2 theme problem.

### ISSUE THREAD

**Issue by ea430** [magento/devdocs#463]
http://eyyupacar.com/magento2/

**Comment by xcomSteveJohnson** [comment]
Please state the problem. Your link does not work.

**Comment by ea430** [comment]
After the installation theme error

http://i.hizliresim.com/ornoyR.png

**Comment by xcomSteveJohnson** [comment]
The link results in "Access restricted"

**Comment by xcomSteveJohnson** [comment]
Please provide a link or a description so we can understand the issue.

**Comment by almarchenko** [comment]
@ea430 is the issue still actual?
Do I understand correctly that the styles are not applied on the storefront right after installation?

**Comment by xcomSteveJohnson** [comment]
Can we close this?

**Comment by xcomSteveJohnson** [comment]
Closing because of no response. You can reopen if you'd like to provide more detail.
