### ISSUE TITLE
Declarative schema. Confusing (possibly incorrect) revertable data patch docs.

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#4649]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/data-patches.html

## Description
The docs say 

> Revertable data patch - A patch that can be reverted as a module or patch is uninstalled or deleted.
 
This leads to believe that patches can be uninstalled individually and revert logic is executed when a patch is uninstalled or deleted. This is not true. 

## Possible solutions
A possible solution would be to clarify that revert logic is executed only at module uninstall or document how a single patch can be uninstalled.

## Additional information
On another page the docs clearly state

> Magento does not allow you to revert a particular module data patch..

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/data-patches.html#reverting-data-patches

**Comment by atwixfirster** [comment]
Hi, @victortodoran! 

Thank you for the reporting. You can check a proposed solution in https://github.com/magento/devdocs/pull/5202.

Please let us know if it ok for you?

Thank you!
