### ISSUE TITLE
/guides/v2.3/config-guide/cron/custom-cron-tut.html

### ISSUE THREAD

**Issue by jasonhildebrand** [magento/devdocs#4651]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/config-guide/cron/custom-cron-tut.html

## Description

After creating crontab.xml and then proceeding with the following section (Verify the cron job), no entries showed up in the cron_schedule table.  Even after running magento cron:run more than 3 times.

## Possible solutions

I found that running `magento setup:di:compile` was necessary.  I believe that running this command causes Magento to notice the new crontab.xml file.  `magento cron:run` should then be run 2 or 3 times after this.

**Comment by lorikrell** [comment]
**Consideration of content location:**
For location of this content, we may want to consider adding cron specifics to [pipeline deployment docs](https://devdocs.magento.com/guides/v2.3/config-guide/deployment/) where the `magento setup:di:compile` comes into play. Then add a link in https://devdocs.magento.com/guides/v2.3/config-guide/cron/custom-cron-tut.html to that info added to pipeline deployment?

**Comment by atwixfirster** [comment]
Yep, we missed `bin/magento cache:clean` in the tutorial. But if you having disabled all caches on your develop/instance then tutorial will work ;)

The necessary information has been added.

Thank you!

**Comment by jasonhildebrand** [comment]
Thanks!
