### ISSUE TITLE
Missing redirect for URL found in Google

### ISSUE THREAD

**Issue by DrewML** [magento/devdocs#4658]
# Bug report

## Description
https://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js-resources.html

(Looks like [this](https://github.com/magento/devdocs/blob/3a1f8d795b008a2511dba6be6f4c39b66f6c6f4e/guides/v2.1/javascript-dev-guide/javascript/requirejs_concept.md) is the document)

### Steps to reproduce

1. Go to Google
2. Search `magento "requirejs-config.js" devdocs`
3. Click the first result

## Expected result

I arrive on the devdocs page

## Actual Result
404

## Possible solutions

Set up redirects from anything under `2.0/*` to `2.3/*`

## Additional information
Screenshot since Google results are tailored to individuals and you may get different results
![image](https://user-images.githubusercontent.com/5233399/58746639-ad41ac80-8460-11e9-8568-cc8ac995e3f0.png)

**Comment by keharper** [comment]
This file existed in 2.0 and 2.1, but not 2.2 and 2.3.

**Comment by jeff-matthews** [comment]
Thanks for the report. There's definitely a bug with the redirect config that I'll have to investigate. It's adding an extra slash to the end of the URL which is causing a 404. When there is no 2.3 equivalent for a 2.0 file, it should redirect to the 2.3 home page.

**Comment by dshevtsov** [comment]
When I follow the scenario, I see the 2.3 topic as a first result.
<img width="883" alt="Screen Shot 2019-06-03 at 09 30 42" src="https://user-images.githubusercontent.com/12731225/58809897-6ed3fb00-85e2-11e9-9fe2-a720acd7bdc7.png">

**Comment by jeff-matthews** [comment]
I think your search results depend on your search and browsing history. So, if you've predominantly visited 2.0 pages, your search is more likely to include 2.0 results.

**Comment by jeff-matthews** [comment]
I fixed the issue that was adding an extra slash to the URL, which was causing 404. This is working as designed now.

**Comment by DrewML** [comment]
Thanks @jeff-matthews!
