### ISSUE TITLE
Code generation. Misleading information about factories. 

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#4661]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/code-generation.html#codegen-over-why
## Description
Excerpt from the docs

> Suppose a Factory or Proxy class for a Customer class is generated and the Customer class has new methods added to it. Because a Factory or Proxy exists on the file system, it is not regenerated. However, the Factory or Proxy implementation is now incomplete because it does not have the new methods. In this case, you must regenerate the Factory or Proxy class.

The issue is that factories have only one method, that is **create** they are not affected (as far as I can tell) by the adding or subtraction of class methods. Class constructors modifications might have impact on factories (I'm not sure)

## Possible solutions
Remove the Factory entity from above quote, possibly specify separately how are factories affected and when should they be regenerated

**Comment by jeff-matthews** [comment]
@buskamuza, can you provide any insight on this?

**Comment by buskamuza** [comment]
That's correct. Please remove "factory" from the statement.

**Comment by konarshankar07** [comment]
Hello guys,
Please assign to me as I'm working on this task
Thanks
