### ISSUE TITLE
Payment method integration - with redirect to external system

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/devdocs#4662]
Currently devdocs - https://devdocs.magento.com/guides/v2.3/payments-integrations/bk-payments-integrations.html for payment integration don't mention how to correctly handle payments with redirect to external system. It would be extremely useful to know how to do it according to Magento guidelines.

**Comment by dshevtsov** [comment]
The topic was moved to https://developer.adobe.com/commerce/php/development/payments-integrations/.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-php/issues.
