### ISSUE TITLE
Feedback on page: /guides/v2.3/cloud/configure/setup-cron-jobs.html

### ISSUE THREAD

**Issue by balex13** [magento/devdocs#4681]
# General issue

## Description:

Please remove `indexer:reindex` from the samples

## Possible solutions:

Use something like `import:start` or any other sample command name.

## Additional information:

The `indexer:reindex` command performs reindexation of indexers. And this lead to clean caches and site slowness. And it looks like Magento recommend doing this.

**Comment by hguthrie** [comment]
Thanks for bringing this to our attention. I will review.

**Comment by hguthrie** [comment]
Assigned to @meker12 , writer working on cron updates.
