### ISSUE TITLE
Magento 2: Custom payment module on checkout page

### ISSUE THREAD

**Issue by mohinik-chetu** [magento/devdocs#469]
Hi,

I am not able to register my custom module template to checkout page after following all the steps mentioned in documentation.
I have created checkout_index_index.xml, view/payment/component's js file, method renderer's js file, config.xml in etc.
What step am I missing?
Also I am seeing method renderer of all modules in pub/static/frontend/....../module/js/view/payment/. But for my module I can see single js file only on the place.
Please help me out.

**Comment by xcomSteveJohnson** [comment]
@mohinik-chetu Would you mind providing a link to the page you're referring to? Thanks!

**Comment by mohinik-chetu** [comment]
Although very few documentation is available for magento2, but I referred http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_payment.html#create
for rendering payment module on checkout page.

Now, I am able to add my custom payment module to checkout page. As the issue was due to system.xml file. I was trying to create nested groups.

I am newbie to magento and learning it as well. ;)

**Comment by xcomSteveJohnson** [comment]
Can this issue be closed?

**Comment by mohinik-chetu** [comment]
Yeah. Sure!! :)

**Comment by magewn** [comment]
Hey I am still facing the same issue, can you please tell me how you resolved this.  I am taking this following example, but still I am facing the same issue. I can see the module in backend part but not on checkout page. Can you please help me on this? 
Using below example, 
http://cedcommerce.com/blog/magento2/code-fragments/payment-module-in-magento-2/#comment-2722968555
Do we need to have di.xml and config.php. 

Please help me.

Thanks
