### ISSUE TITLE
How To: What Replaces Mage::getConfig() in Magento 2?

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#470]
Continuing discussion from: https://github.com/magento/devdocs/issues/453 since I lack reopen powers.

> @astorm After internal discussion, we decided this should not be documented. We have internal issue MAGETWO-38492 to track a module reference, which is expected to be dynamically generated like Swagger for APIs. This should help.
> 
> I also created internal issue MAGEDOC-2497 to improve the current documentation.
> 
> Closing; please reopen if you disagree.

It's hard to know whether to agree or disagree without being able to see what the proposed solution to this issue is. The _dynamically generated like Swagger for APIs_ could mean a lot of things.  Some of those would be great, others of those would be great but solving a different, unrelated, problem.  Is there a public GitHub engineering issue that's tracking this?

Being uncertain am reopening.

Thanks!

**Comment by xcomSteveJohnson** [comment]
MAGETWO-38492 is the issue I'm told where this will be addressed. Here is part of the description:

"As a Magento Developer, as a Industrial Partner, as a System Integrator, as a Business Analyst, as a devdocs.magento.com Reader I want to have a tool to collect module information from code and create document that Tech Writer could convert to Module Reference Guide.

The community and potential investors have asked specifically for better documentation around our modules. The business value is high, as any developer working with our code base needs easy access to details about each module."

I don't know if there's a public GitHub issue but you can create one if you'd like.

**Comment by astorm** [comment]
Not sure what to say to that @xcomSteveJohnson.  It sounds like a generic "modules should self document" feature request.  There's nothing about the specific problem of how to read from the merged configuration tree in that ticket. 

If this is the polite corporate way of saying you're not going to allocate resources for this because it's not something Magento Inc. itself needs, fair enough. However, the world wide community of Magento developers **would** benefit from this information, and I'd still vote that it's worth documenting. 

Thanks!

**Comment by xcomSteveJohnson** [comment]
You should raise this on the Magento 2 GitHub because then Products will see it and might bump up the priority. If you know any Magento architects, you can reach out to them as well. 

I pointed two architects to your issue and both of them agreed it's not something we should document. There's plenty of room for improving the documentation about configuration, so I opened an issue for that. 

We realize it's disappointing but this is an argument that you and the community can still make. I can't make the case as persuasively as you can.

**Comment by astorm** [comment]
@xcomSteveJohnson Fair enough Steve. The architects are a valuable part of the development process, but they're the least well situated to know what folks on the ground actually using the system need to get their jobs done.  I'm not sure what more compelling case there is than the prevalence of calls to `Mage::getConfig` through the free/open-source Magento 1 extension base.  Not having a clear path forward on how to convert this code is a problem, and I don't see why a document explaining how it's done in the existing core modules is a problem.  If the architects are pushing back on it it means they're just pushing back on everything as a mater of course/policy, or they have an architectural agenda that works counter to the sort of information outside programmers need to get their job done.

At a certain point it becomes tilting at windmills. Bureaucracy politics wins this one -- closing the ticket

**Comment by antonkril** [comment]
Looks like a miscommunication. Configuration topic is important and should be well documented. Some content is already available (we did few presentations), but it's not enough. Commented on original ticket.

**Comment by astorm** [comment]
Per previous comments on this, what's needed/wanted is a clear set of instructions one how an end-programmer-user (i.e. module developer) *should* use classes from the existing configuration class hierarchy to read their own configuration files.  

Put another way, how would a developer use the classes described in [Overview of Module Configuration](http://devdocs.magento.com/guides/v2.0/config-guide/config/config-files.html) to create a configuration object for a new system wide `foo.xml`.  In addition to solving a specific problem (how do I add new global/frontend/adminhtml configuration file to the system) the existence of this article would also allow developers to infer how they could read from the other configuration files.

**Comment by xcomSteveJohnson** [comment]
Internal issue MAGETWO-47808

**Comment by astorm** [comment]
The answer on this StackExchange question *starts* to get at the sort of documentation that's needed.  Apparently the fundamentals course covers this, so whomever ends up writing the article should have a good head start. 

http://magento.stackexchange.com/questions/82022/magento-2-how-to-read-from-configuration-tree

**Comment by astorm** [comment]
Any update on this, or is this not going to happen?

**Comment by xcomSteveJohnson** [comment]
I supposedly have the information I need to write this but haven't started yet. With holidays on us, I'll take a look and get back to you here with a yes/no soon, and then an ETA after that.

**Comment by jcalcaben** [comment]
This request has been recreated in #3361 using the new issue template to better outline the type of content that needs to be written.
