### ISSUE TITLE
Feedback on page: /guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.html

### ISSUE THREAD

**Issue by webosteve** [magento/devdocs#4716]
The entire documentation should be removed, it is incorrect and causes developers to waste large amounts of time reading and following along with instructions that are in NO WAY HELPFUL!

I believe it was the goal of Magento to create Magento 2 in the most complicated, unconventional and laborious of ways in order to try and get as much of the existing community to PAY for training. Only thing is that once ANYONE has had training the first thing they tell others is DON'T USE MAGENTO 2...

I am dumbfounded that Adobe made such a bad purchase, but my assumption is that they will be doing away with the platform completely as it is a disaster and only offer a scaled down version as a hosted solution, like WIX.

**Comment by shrielenee** [comment]
Hello @webosteve --- Can you elaborate on what is incorrect about [this page|https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.html]? 

What exactly was the issue you were trying to solve with our documentation? It would be helpful for us if you provided information on the specific issue(s) in your feedback.

Barring documentation changes, to get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests).
