### ISSUE TITLE
Missing information about ui component php modifiers.

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#4719]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_config_flow_concept.html
## Description
First, thank you for this page.
Under this section 

> When the request for my_page comes, the server does the following:

there is no information about when and how php modifiers kick in even though they are mentioned in the beginning of the explication

## Possible solutions

Insert information about how and when php modifiers intervene.

**Comment by jcalcaben** [comment]
Does the following page contain the information you need?

https://devdocs.magento.com/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.html

**Comment by victortodoran** [comment]
Yes
