### ISSUE TITLE
Cannot reach the link on dependency injection page

### ISSUE THREAD

**Issue by mrkhoa99** [magento/devdocs#472]
Hi,

When reading about *Dependency Injection*: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html. We cannot reach the link: www.objectmentor.com/resources/articles/dip.pdf. This link may refer to this post: https://sites.google.com/site/unclebobconsultingllc/blogs-by-robert-martin/dependency-injection-inversion?

**Comment by xcomSteveJohnson** [comment]
Sorry about the old link, which still appears on Google. Replaced it with yours.

Please close this issue if you feel this is a satisfactory result.

**Comment by mrkhoa99** [comment]
Fixed!
