### ISSUE TITLE
Add article for event/observer pattern in Magento 2

### ISSUE THREAD

**Issue by erikhansen** [magento/devdocs#473]
The devdocs doesn't have a page covering the event/observer pattern in Magento 2. This is a very important concept to cover. There are 430 usages of `implements ObserverInterface`, so it's clear that observers are still very much used in Magento 2 and ought to be documented.

This page could look something like this: http://code.tutsplus.com/tutorials/custom-events-in-magento-with-the-observer-pattern--cms-22120

**Comment by xcomSteveJohnson** [comment]
Thank you. Created internal issue MAGEDOC-2498 to track.

**Comment by jcalcaben** [comment]
Documentation for the event/observer pattern has been created and can be found here: http://devdocs.magento.com/guides/v2.1/extension-dev-guide/events-and-observers.html

**Comment by erikhansen** [comment]
Great!
