### ISSUE TITLE
Feedback on page: /guides/v2.3/config-guide/cli/config-cli-subcommands-mode.html (update git rm instruction)

### ISSUE THREAD

**Issue by SD-dthompson** [magento/devdocs#4748]
# General issue
rm -rf command described in the "Change to developer mode" section shows absolute paths

## Description:

it seems highly unlikely (if even possible) that someone's magento root would be the same as their actual system root directory, which is where the current recommended rm -rf command (for use before switching to developer mode from production mode) suggests the files to be deleted live.

## Possible solutions:

change 
rm -rf /generated/metadata/* /generated/code/*

to 
rm -rf generated/metadata/* generated/code/*

or as a variable example, rather than a command someone might copy-paste: 
rm -rf <magento_root>/generated/metadata/* <magento_root>/generated/code/*

## Additional information:

 might be worth looking back to earlier versions (same issue exists on the 2.2 version instructions as well, the 2.1 version instructions were for different directories, but did at least specify the <magento_root>)

**Comment by keharper** [comment]
Fixed by #4779
