### ISSUE TITLE
Update documentation for Composer repo.magento.com keys

### ISSUE THREAD

**Issue by erikhansen** [magento/devdocs#475]
The http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html page has outdated instructions for retrieving your authentication keys. The "Secure Keys" page has now been moved into this tab:

![bn6yv](https://cloud.githubusercontent.com/assets/129031/12246792/13624192-b876-11e5-9cb6-1e2b0bea94ac.png)

**Comment by xcomSteveJohnson** [comment]
Please check because I believe I changed that already.

**Comment by xcomSteveJohnson** [comment]
I did make a change to this, let me figure out why it's not showing up.

**Comment by xcomSteveJohnson** [comment]
Gee whiz, I don't know what happened the first time I fixed this but I just fixed it again.

Please close this issue if you agree. Thanks for pointing it out.

**Comment by erikhansen** [comment]
@xcomSteveJohnson It looks better, but on step 2 you say "In the left pane, click **Connect.**". At least on desktop screens, the "Connect" link is a tab on top, not a link in the left pane. Although on small screens, it may be positioned differently. I would recommend updating this with wording that is accurate regardless of the screen size.

**Comment by xcomSteveJohnson** [comment]
Thanks. I was in a hurry last night and missed that. Please check it now.

**Comment by erikhansen** [comment]
Looks great! I love how you continue to stay on top of devdocs! Keep up the good work. Closing issue.
