### ISSUE TITLE
Feedback on page: /guides/v2.3/frontend-dev-guide/theme-best-practice.html

### ISSUE THREAD

**Issue by Carradee** [magento/devdocs#4757]
# General issue

Objective grammar errors.

## Description:

The punctuation and grammar are poor.

Poor grammar.

For example:

"Keep in mind, that after Magento instances, updates or upgrades something can change in default templates, layouts, and styles. So it is recommended to check if the changes effected the files overridden in your theme and copy changes if any, to your templates, layouts, and styles."

This contains a comma splice, a possibly misplaced word, an outright incorrect word, and a poorly designed sentence fragment.

## Possible solutions:

For example:
"Keep in mind that Magento instances, updates, or upgrades can change default templates, layouts, and styles, so it is recommended to check if such changes affect the files overridden in your theme and to copy any changes into your overrides."

## Additional information:

I'm a line editor with over a decade of experience.

**Comment by shrielenee** [comment]
Hey @Carradee -- Thanks for raising this issue. We will address this oversight.

In other news, did you know you can contribute to our docs!? We'd love for you to provide your insight and expertise. See here to get started: https://github.com/magento/devdocs/wiki.

We have a team of technical writers that manage and facilitate GitHub issues and PRs, as well as write a slew of documentation for MANY different features, but unfortunately, sometimes mistakes are made.
