### ISSUE TITLE
Enterprise Integrator metapackage

### ISSUE THREAD

**Issue by chris-brabender** [magento/devdocs#476]
When trying to install Magento 2 Enterprise Edition via the Integrator metapackage we are getting the following error:

    Could not find package magento/project-enterprise-edition with stability stable.

We are using this command (which works fine with the community edition set)

    composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition

The secure keys used work for the community install but not the enterprise package. The account being used is a Magento partner account. Are there additional steps to enable the project-enterprise-edition repo for integrator accounts?

**Comment by davidalger** [comment]
@chris-brabender You'll need to contact Magento support and request they grant enterprise access to the account. Include the account number to ensure the request gets it added to the correct partner account. :)

**Comment by chris-brabender** [comment]
thanks @davidalger, all good now.
