### ISSUE TITLE
Inconsistent line endings in guides/v2.0/howdoi/checkout/checkout_payment.md

### ISSUE THREAD

**Issue by mageghost** [magento/devdocs#477]
The line endings in said file are inconsistent. Some lines use Windows line endings, others use Unix line endings. Given the rest of the docs appear to standardise on Unix line endings, this file should be corrected.

**Comment by tanberry** [comment]
Thanks, @mageghost, we agree. We will work on it, and also if you are willing it would be great if you wanted to do a PR to fix the places you find; we really appreciate all the help we can get, especially PRs.

**Comment by almarchenko** [comment]
@mageghost Thanks for reporting this, we will fix this!
Can I close the issue?

**Comment by xcomSteveJohnson** [comment]
@mageghost Can you elaborate on the issue? Which line endings are Windows?

Thanks

**Comment by almarchenko** [comment]
I've fixed the line endings in source files. Thank you, closing.
