### ISSUE TITLE
Duplicate blocks in documentation

### ISSUE THREAD

**Issue by vzabaznov** [magento/devdocs#478]
On page http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache.html block "Enable rewrites and .htaccess for Apache 2.4" duplicates 3 times

**Comment by tanberry** [comment]
Thanks, @zabaz. Very odd, not sure what happened there. We will fix it, thanks again. Please also feel free to create a Pull Request and go ahead and fix problems like this, if you like. We appreciate all the help we can get. Thanks again!

**Comment by xcomSteveJohnson** [comment]
Thanks, I'll fix it and update you.

**Comment by xcomSteveJohnson** [comment]
Should be fixed now. Please verify and close this issue. Thanks!

**Comment by vzabaznov** [comment]
no, ,it was 3 times on page, now its still twice on a page, text to find "Enable rewrites and .htaccess for Apache 2.4" 
http://prntscr.com/9t9sib
http://prntscr.com/9t9smc

**Comment by xcomSteveJohnson** [comment]
It's correct the way it is. The section on 2.4 is repeated intentionally in the section on setting up Apache 2.4 for Ubuntu 12. So many people reported issues with images not displaying on the storefront and Admin I decided to include the .htaccess instructions for both 2.2 and 2.4 in the sections on setting up Apache for Ubuntu 14 and Ubuntu 12.

Thanks

**Comment by vzabaznov** [comment]
Thanks a lot.
