### ISSUE TITLE
Module documentation for Security.txt EngCom submission

### ISSUE THREAD

**Issue by lorikrell** [magento/devdocs#4789]
# Community engineering issue

Dev in progress! 
Docs: DevDocs may have content...?  MerchDocs for Config updates. Issue for MerchDocs created in the new repo)
**Dev Contact**: @kalpmehta 
Community Core project

Type of Doc:
- [x] New topic
- [ ] Topic Update, Devdoc link:
- [ ] Other

Magento 2 GitHub repo: https://github.com/kalpmehta/securitytxt

Magento 2 version:
VERSION TBD! 2.3.x, tbd if 2.2.x
- [ ] 2.1.X
- [ ] 2.2.X
- [ ] 2.3.X
- [ ] back port
- [ ] forward port

Notifications of Changes:
- [ ] Changes to Admin interface? New configuration page for **Stores > Settings > Configuration > Security** - https://github.com/kalpmehta/securitytxt/blob/master/app/code/Kalpesh/Securitytxt/Model/Config/Signature.php (instructions moving from the config page to doc)
- [ ] New software requirements?
- [ ] New REST endpoints or updated GraphQL query syntax?
- [ ] New command line option?

## Content

Security.txt is a new module for Magento 2 core. Final versions affected TBD.

Documentation needed:

- Info on module: see README https://github.com/kalpmehta/securitytxt
- Instructions moving out from the config page to documentation
- https://github.com/kalpmehta/securitytxt/blob/master/app/code/Kalpesh/Securitytxt/Model/Config/Signature.php 

Install may not be needed, as it will be a new module in Core. 
More screenshots: https://github.com/kalpmehta/securitytxt/tree/master/screenshots
![image](https://user-images.githubusercontent.com/29388020/59804828-145ebe00-92b5-11e9-8eb0-26ea7a503a24.png)

## Additional information

TBD!

**Comment by lorikrell** [comment]
Created issue in the MerchDocs repo. The repository and contribution submissions for the Magento Merchant content (User Guide) will be available at a later date. This ticket may have content for DevDocs.

**Comment by keharper** [comment]
@tilling Can this issue be moved/duplicated in the Merchant Doc repo?

**Comment by keharper** [comment]
I'm closing this issue. Please open a MAGEDOC if devdocs is affected.
