### ISSUE TITLE
Clarify command-line update prereq steps

### ISSUE THREAD

**Issue by SD-dthompson** [magento/devdocs#4792]
# General issue

## Description:
/guides/v2.3/comp-mgr/cli/cli-upgrade.html

Command Line Upgrade process includes running the System Upgrade Utility as part of it's prerequisites.

## Possible solutions:

Maybe just omit this, or move it out of the prerequisites? Unless I am misunderstanding, if a user wanted to be running an update via the command line, instructions to run the update via the System Upgrade Utility (from the frontend) among the prerequisites seem like misdirection.

Note: The writing team thinks that the second prereq bullet point is overloaded and assumes a lot of knowledge. We would like to see a link to another topic that talks about the /pub root or something here to flesh out the steps required to manage /pub root or subdomains.

**Comment by jeff-matthews** [comment]
Thanks @SD-dthompson. I think you're right about the reference to the System Upgrade Utility in a CLI upgrade topic. I think we should remove it. Also, we should link the topic about modifying docroot: https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html.

**Comment by atwixfirster** [comment]
PR: https://github.com/magento/devdocs/pull/5308
