### ISSUE TITLE
Wrong limitation on plug-in page

### ISSUE THREAD

**Issue by vzabaznov** [magento/devdocs#482]
Page - http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html
Block - Limitation
Issue - There is no limitation about Inherited methods in magento plugins, they works as well

**Comment by xcomSteveJohnson** [comment]
@vzabaznov This bullet item is gone. Please close if you are happy with the resoultion.

**Comment by xcomSteveJohnson** [comment]
Closing. Please reopen if there is something wrong.

**Comment by vzabaznov** [comment]
Thank you, now everything is fine
