### ISSUE TITLE
Dependency injection article misses some examples

### ISSUE THREAD

**Issue by anatolykazantsev** [magento/devdocs#486]
Section: https://github.com/magento/devdocs/blob/develop/guides/v2.0/extension-dev-guide/depend-inj.md#configuration-overview

It seems following lines should have examples:
* For example, to set the interface preferences for the Magento Admin, use app/code/core/Magento/Backend/etc/adminhtml/di.xml as follows:
* You can also specify whether or not the object is shareable in its di.xml as follows:

**Comment by tanberry** [comment]
Ooops!! Thanks, @anatolykazantsev, you are right; we missed those two examples. If you want to contribute them, and do a Pull Request, that would be great. Otherwise, we will work on them as soon as we get a chance here. Thanks again!

**Comment by anatolykazantsev** [comment]
Sure, I will. Just need to get a better understanding of Magento 2 :-)

**Comment by xcomSteveJohnson** [comment]
@anatolykazantsev  Would you mind checking the page again? I updated the examples you mentioned. If you're happy, please close this issue.

**Comment by anatolykazantsev** [comment]
Fixed version: https://github.com/magento/devdocs/blob/2.0/guides/v2.0/extension-dev-guide/depend-inj.md

It looks OK for me.
