### ISSUE TITLE
Feedback on page: /guides/v2.3/comp-mgr/cli/cli-upgrade.html

### ISSUE THREAD

**Issue by jarkkouitti** [magento/devdocs#4877]
# General issue

## Description:

php_codesniffer version (3.2.2) is too old in command:
Specify additional packages:
"composer require --dev allure-framework/allure-phpunit:~1.2.0 friendsofphp/php-cs-fixer:~2.13.0 lusitanian/oauth:~0.8.10 magento/magento-coding-standard:~1.0.0 magento/magento2-functional-testing-framework:~2.3.14 pdepend/pdepend:2.5.2 phpunit/phpunit:~6.5.0 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:3.2.2 --sort-packages --no-update
--"

> composer update

  Problem 1
    - magento/magento-coding-standard 1.0.2 requires squizlabs/php_codesniffer ~3.3.0 -> satisfiable by squizlabs/php_codesniffer[3.3.0, 3.3.1, 3.3.2] but these conflict with your requirements or minimum-stability.
    - magento/magento-coding-standard 1.0.1 requires squizlabs/php_codesniffer ~3.3.0 -> satisfiable by squizlabs/php_codesniffer[3.3.0, 3.3.1, 3.3.2] but these conflict with your requirements or minimum-stability.

## Possible solutions:

Fix php_codesniffer version 3.3.0 or newer.

**Comment by dobooth** [comment]
Fixed in https://github.com/magento/devdocs/pull/4886
