### ISSUE TITLE
Update image in Inventory Management overview

### ISSUE THREAD

**Issue by cundd** [magento/devdocs#4879]
# General issue

## Description:

The text under in section "A simple scenario" does not match the image (https://devdocs.magento.com/guides/v2.3/inventory/index.html#a-simple-scenario)

- Text mentions a German (DE) web store which is not in the image
- Drop shipper in image never mentioned in text

## Possible solutions:

- Update text
- Update image

**Comment by keharper** [comment]
It looks like this has been taken care of.
