### ISSUE TITLE
Suggestion for build process: check for 404

### ISSUE THREAD

**Issue by gwillem** [magento/devdocs#490]
There's a 404 on http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/dev_update-magento.html pointing to http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/instgde-install-magento-update-db

In general, I'd suggest to add a 404 check to your docs build process for catch these issues.

**Comment by xcomSteveJohnson** [comment]
Should be fixed now. Please check and close this issue.

Link checking is on the radar with no ETA. If you know of a good tool, please let us know.

**Comment by gwillem** [comment]
Thanks!
