### ISSUE TITLE
Provide example for afterGetList method

### ISSUE THREAD

**Issue by jsamhall** [magento/devdocs#4903]
# General issue

## Description:

There is no example method provided for the `afterGetList` method of proposed Plugin class to handle loading extension attribute data. Instead, the documentation simply reads "AfterGetList is similar to afterGet."

This is **wildly** open to interpretation and has no place in official documentation.

Is iterating over the collection returned from `getList` and hitting the extension attribute repository implementation for every entity a good solution? Probably not, but I'm sure there are plenty of community members who wouldn't think twice about it.
 
## Possible solutions:

Provide an example for the afterGetList method that supports recommended best practices and yields good performance.

## Additional information:

Its great to see the official documentation being updated, but disappointing to see the effort stop at "acceptable".

**Comment by keharper** [comment]
Affected pages

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.html
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/devdocs/pull/5826
