### ISSUE TITLE
Overview of System Upgrade - article bottom section is not proper.

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/devdocs#493]
On following url  http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html

The bottom most section HTML is not proper.

Error

The following error can indicate one of several issues, including that you haven't entered your <a href="/guides/v2.0/comp-mgr/prereq/prereq_auth-token.html">authentication keys</a> in the Magento Admin:

<img src="/common/images/upgr-sorry.png" width="600px">

For suggested solutions to other causes indicated by this message, see <a href="/guides/v2.0/comp-mgr/trouble/cman/were-sorry.html">troubleshooting</a>.

The page displays similar to the following when we find components to upgrade.<br><br>
<img src="/common/images/upgr_stuff-2-upgrade.png" width="650px" alt="Magento finds software to upgrade"><br><br> 4. 	Continue with <a href="/guides/v2.0/comp-mgr/upgrader/upgrade-main-pg.html">Step 1. Select versions to upgrade</a>.

The hyper links should be clickable.

![screenshot-devdocs magento com 2016-01-25 15-12-38](https://cloud.githubusercontent.com/assets/5028259/12547392/1f18a070-c376-11e5-8b36-2f00505eea5e.png)

**Comment by xcomSteveJohnson** [comment]
Sorry about that, fixed it yesterday. Please check and close this.

**Comment by tiwarimukesh** [comment]
Thank you for the fix.
