### ISSUE TITLE
Feedback on page: /guides/v2.3/config-guide/redis/redis-pg-cache.html

### ISSUE THREAD

**Issue by anishcorratech** [magento/devdocs#4957]
# General issue

Regarding the Magento Object Cache "<cache>"

Can we use a similar config from this [Page](https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/master/README.md#elasticache)  in magento 2 `env.php`

```
    <!-- This is a child node of config/global/cache -->
    <backend_options>
      <server>primary-endpoint.0001.euw1.cache.amazonaws.com</server>
      <port>6379</port>
      <database>0</database>                    <!-- Make sure database is 0 -->
      <master_write_only>1</master_write_only>
      <load_from_slave>
        <node-001>
          <server>replica-endpoint-1.jwbaun.0001.euw1.cache.amazonaws.com</server>
          <port>6379</port>
        </node-001>
        <node-002>
          <server>replica-endpoint-2.jwbaun.0001.euw1.cache.amazonaws.com</server>
          <port>6379</port>
        </node-002>
      </load_from_slave>
    </backend_options>
```

## Description:

New Configuration Parameter for Magento 2 Elasticache.

## Possible solutions:

Magento 2 to use Read Replica's

## Additional information:

NA

**Comment by shrielenee** [comment]
Can we get some clarification on this issue? Are you suggesting a more optimal config? And is the config in the docs not sufficient or not working? Thanks!

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this and we haven't heard from you in two weeks.

We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
--
