### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/prereq/prereq_updater.html

### ISSUE THREAD

**Issue by farhadniaz** [magento/devdocs#4987]
# General issue

## Description:

The "Magento 2 updater" link is doesn't exist on github and it gives 404 error .
https://github.com/magento/magento2-updater
## Possible solutions:
please fix to correct link

**Comment by jcalcaben** [comment]
@dobooth to check in with architects to see why the repository is now private

**Comment by dobooth** [comment]
https://github.com/magento/devdocs/issues/3178
