### ISSUE TITLE
References to Encrypting Personally Identifiable Customer Information

### ISSUE THREAD

**Issue by gorillagroup** [magento/devdocs#499]
The docs refer to the encryption key being used to encrypt personally identifiable customer information in multiple instances:

- _includes/install/web/install-web_3-web-conf.md 
- guides/v2.0/install-gde/install/cli/install-cli-subcommands-deployment.md 
- guides/v2.0/install-gde/install/cli/install-cli-install.md 
- guides/m1x/install/installing_install.html

Is this in fact a feature Magento supports out of the box? If so, please include some links to where this is discussed, otherwise, please remove or reword.

**Comment by xcomSteveJohnson** [comment]
We're not clear on your request. Magento encryption keys are used to encrypt sensitive information in the database.

We're not sure what information you need to know about them. Would you mind updating this issue? Thanks!

**Comment by gorillagroup** [comment]
@xcomSteveJohnson ,

My point is that this documentation is stating that the encryption key is used for a few different purposes:

1. Sensitive data
2. Customer passwords
3. Personally identifiable customer information

My question is whether these statements are true, and if they are, whether you can point out where this functionality can be enabled. I am specifically looking for  personally identifiable customer information encryption. 

My opinion is that at least some of the statements are not true: 
1. **True**: Magento does use the encryption key to encrypt some System Configuration values adn stored credit cards
2. **Not true**: Magento does not encrypt customer or admin user passwords. (unless this refers to passwords in the System Configuration)
3. **Not true**: Magento does not encrypt personally identifiable customer information

Thanks for your help.

**Comment by davidalger** [comment]
@gorillagroup My guess is 2 refers to the payment / shipping / etc account details in the system config, and 3 is relating to customer card data for stored payment methods. Sounds like it could use some clarification so it's more specifc. :)

**Comment by gorillagroup** [comment]
@davidalger ,

I agree. PII means a very specific thing, and I'm pretty sure that data is not encrypted. Although, it would be nice to have this functionality out of the box.

**Comment by xcomSteveJohnson** [comment]
@gorillagroup @davidalger We're seeing some internal e-mails about this now and hope to have a resolution very soon. Thanks for bringing this up.

**Comment by xcomSteveJohnson** [comment]
@gorillagroup Thanks again for bringing this up. All of the topics you mentioned are updated *except* for Magento 1.x installation. That will take a bit longer.

Please review the information and, if you're happy with it, close this issue.

**Comment by gorillagroup** [comment]
@xcomSteveJohnson ,

Looks good, with some minor tweaks I suggest in the PR.

**Comment by xcomSteveJohnson** [comment]
Merged your PR. Close this now?

**Comment by gorillagroup** [comment]
@xcomSteveJohnson,

Thanks! Closed.
