### ISSUE TITLE
MTF Tutorial

### ISSUE THREAD

**Issue by jahved** [magento/devdocs#500]
I want a clear & Easy tutorial to create My First Magento MTF Funtional Test.. Can you please provide me since the user guide is too complex

**Comment by xcomSteveJohnson** [comment]
Adding detail from @jahved emails.

First email:

Hi Steven,
Well, I have been able to run the MTF test on Magento 1.14.2.1 but now I want to know how to create a customized Test using MTF from start.

Example:
Login as admin 
create a product
Login an Front End 
In Magento 1.14.2.1 we don't have php generatefixturexml.php. So to create and Update the fixture we need to do that manually.
Below is what I have understood of how MTF Architecture works. please update if am wrong.
I need a tutorial to create a simple functional test in Magento MTF explaining clearly the inject, prepare test e.t.c I am stuck with the _Inject _Prepare test  
![1](https://cloud.githubusercontent.com/assets/1268334/12696537/dcc2427e-c732-11e5-9a1c-5ff548c15c20.jpeg)

**Comment by xcomSteveJohnson** [comment]
Email 2:

Hi Steven ,
I have another question for your MTF Team, in the CreateAdminUserEntityTest we have 7 variations. Is there a way to run only variation number 4 without altering the dataset.
In phpunit to execute a specific test we use 

phpunit --filter CreateCreateAdminUserEntityTest --debug
What about a specific Variation in a specific test-- When a test failed during regression testing we will not run the full test again and we will not alter the dataset again and again.
Waiting for your team feedback..
Regard
Jahved

**Comment by xcomSteveJohnson** [comment]
Email 3:

Sorry I have lot of questions coming up. I am currently trying to run MTF on one of our live environment.

 All our website has an Authorization Request 

![2](https://cloud.githubusercontent.com/assets/1268334/12696549/065c2640-c733-11e5-8098-2c8849ab4359.png)

 
How do we cater for this in MTF?
Regards
Jahved

**Comment by xcomSteveJohnson** [comment]
Tracking with internal issue MAGETWO-48592

**Comment by dshevtsov** [comment]
@jahved thanks for your feedback.

> Email 1

We are working on the MTF tutorial now.

> Email 2

There is no way to run specific variation in phpunit.

>Email 3

In the [config.xml](http://devdocs.magento.com/guides/v2.0/mtf/mtf_quickstart/mtf_quickstart_config.html#mtf_quickstart_config_phpunitxml) try to set URLs for the `app_frontend_url` and `app_backend_url` in the following format: `http://username:password@site.com/page`

**Comment by dshevtsov** [comment]
@jahved please check the new topic http://devdocs.magento.com/guides/v2.0/mtf/create_test/create_new_test.html

**Comment by jahved** [comment]
Thanks Dmitry. I will check it and provide you a feedback.

**Comment by dshevtsov** [comment]
@jahved please close this issue if everything is fine. Or if you do not have enough time to estimate the content at the moment, you can close this issue and open another one later, if needed. Thanks.

**Comment by jahved** [comment]
@dshevtsov 
I have already gone through the content it's really great.
 Should I close this one and open a new ticket for Scenario Test Topic.

**Comment by dshevtsov** [comment]
Thanks, @jahved!
Please close this ticket and track the [existing Scenario Test Topic issue](https://github.com/magento/devdocs/issues/517).
