### ISSUE TITLE
Update integration page about integrating modules in 2.3

### ISSUE THREAD

**Issue by scouttyg** [magento/devdocs#5001]
# General issue
Integration guide missing critical steps for 2.3

## Description:
Following the guide for creating a basic integration for 2.3 resulted in a module that is almost exactly this:

[Vendor1.zip](https://github.com/magento/devdocs/files/3411679/Vendor1.zip)

This module does not show up in `System > Extensions > Integrations`, even though it is supposed to as per the guide's instructions.

## Possible solutions:
There are a few pieces at play here:

1. The guide suggests to put the integration at 

```bash
<magento_base_dir>/vendor/<vendor_name>/module-<module_name>
````
But putting it in the `vendor` folder resulted in nothing happening when I ran `bin/magento setup:upgrade`. 

The first solution was to put my code instead `app/code/<vendor_name>/module-<module_name>`, at which point I could see the installation finally happening. Even after the install happened though, I saw no change and no integration at `System > Extensions > Integrations`

2. After still not seeing it anywhere, I decided to look back at the [previous version's integration guide ](https://devdocs.magento.com/guides/v2.2/get-started/create-integration.html), which had differences from 2.3 in that a module needed:

-  An `etc/acl.xml` file, 
- An `etc/integration.xml` file(Which seems like it was replaced with `integration/api.xml` and `integration/config.xml` in 2.3)

3. Finally, in 2.2 the config string looked like `TestIntegration` everywhere, e.g. 

```php
$this->integrationManager->processIntegrationConfig(['TestIntegration']);
```

With only one mention of `testIntegration` (camel case), whereas in 2.3 it somewhat flips between `testIntegration` and `TestIntegration` somewhat haphazardly.

After making the changes above (putting code in `app/code`, adding an `etc/acl.xml` file and `etc/integration.xml` file, and changing all the cases of `TestIntegration` to title case, only then when I installed was I able to see my integration in `System > Extensions > Integrations`

## Additional information:

See also issues https://github.com/magento/magento2/issues/4023, https://github.com/magento/magento2/issues/4824, and https://github.com/magento/magento2/issues/6484, which were all I think slightly different issues, but I spent a lot of time Googling before figuring everything out.

**Comment by jcalcaben** [comment]
Feedback on page: /guides/v2.3/get-started/create-integration.html

**Comment by eduard13** [comment]
Hi @jcalcaben, could you please assign it to me? I'd like to check it.
Thanks.

**Comment by zellkz** [comment]
> m2-community-project bot added Progress: dev in progress
Is this actually in progress? These inaccurate/outdated docs caused me some headache.

**Comment by keharper** [comment]
@eduard13 Any update on the status of this issue?

**Comment by keharper** [comment]
I'll unassign it, @eduard13.

**Comment by jcalcaben** [comment]
If this is for development, the guide should say it needs to be added to `app/code/<vendorName>` instead of the `vendor` directory.

**Comment by dobooth** [comment]
#7707 was closed due to the submitter not returning to complete the PR. The work is still there.

**Comment by bdenham** [comment]
I reopened and will merge this #7707 because the PR changes were correct.

**Comment by chandru-199** [comment]
This issue have some labels. But PR linked with this issue doesn't have any labels. Could anybody look into it?
