### ISSUE TITLE
Update Magento setup rollback command

### ISSUE THREAD

**Issue by HeiderSati** [magento/devdocs#5005]
# General issue

/guides/v2.3/install-gde/install/cli/install-cli-backup.html

 Description:   Online Document Incorrect: The rollback procedure has "=" after the (-m -c -d) switches which causes the rollback script execution to give an error of "code/data file not found ...".

## Possible solutions: Please replace the following statement: 

 magento setup:rollback [-c|--code-file="<name>"] [-m|--media-file="<name>"] [-d|--db-file="<name>"]

into

 magento setup:rollback [-c|--code-file "<name>"] [-m|--media-file "<name>"] [-d|--db-file "<name>"]

**Comment by HeiderSati** [comment]
From execution, please see the below output:

php bin/magento setup:rollback -c=1563541635_filesystem_code.tgz -d=1563541635_db.sql
Maintenance mode already enabled
You are about to remove current code and/or database tables. Are you sure?[y/N]y
Do you want to keep the backups?[y/N]y
The rollback file doesn't exist. Verify the file and try again.
Skipped disabling maintenance mode

-----------------------

versus:
=====
php bin/magento setup:rollback -c 1563541635_filesystem_code.tgz -d 1563541635_db.sql 
Maintenance mode already enabled
You are about to remove current code and/or database tables. Are you sure?[y/N]y
Do you want to keep the backups?[y/N]y
Code rollback is starting ...
Code rollback filename: 1563541635_filesystem_code.tgz
Code rollback file path: /..../var/backups/1563541635_filesystem_code.tgz
[SUCCESS]: Code rollback completed successfully.
SQLSTATE[HY000] [2006] MySQL server has gone away

I hope this helps,

Regards
Heider

**Comment by diazwatson** [comment]
@jcalcaben I am looking into this issue could you please assign this to me?

**Comment by keharper** [comment]
It's yours @diazwatson

**Comment by diazwatson** [comment]
Cheers

**Comment by SYDevsys** [comment]
Thank you guys, looking forward to the update.

**Comment by HeiderSati** [comment]
Thank you guys

Looking forward to the update.

Thanks
