### ISSUE TITLE
'Edit this page on Github' URL is incorrect

### ISSUE THREAD

**Issue by BenSpace48** [magento/devdocs#502]
Clicking on the 'edit this page on Github' link returns 'this webpage is not available'. It occurs on every page in the docs for me.

For example on the tabs widget page it attempts to go to https://github.corp.ebay.com/Magento/devdocs_internal/tree/develop/guides/v2.0/javascript-dev-guide/widgets/widget_tabs.md

![screen shot 2016-01-28 at 14 25 03](https://cloud.githubusercontent.com/assets/8895777/12646977/f0712e84-c5ca-11e5-843f-03c6c889f2f8.png)

**Comment by xcomSteveJohnson** [comment]
Very sorry! We'll fix that today. I'll update you.

**Comment by xcomSteveJohnson** [comment]
Should be fixed now. Please let us know if you find issues or close this if not.

Thanks for pointing it out

**Comment by BenSpace48** [comment]
Thanks for the quick fix, all is well now.
