### ISSUE TITLE
Broken external links

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5022]
# Bug report

## Description

Local link checking reports about more than 400 broken external links.

### Steps to reproduce

1. In the `_config.checks.yml`, set `:disable_external: false`
2. Run `rake test`
3. See the report that appears in your default browser

## Expected result

No broken external links.

## Possible solutions

Fix the links that can be fixed.
Remove the links that cannot be fixed.
Remove the links to private repositories and other resources that have restricted access.

**Comment by twocs** [comment]
I believe that this bug relates to missing links in the wiki pages. For example, on the page https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.html, the link is `[de_de]` resolves to a page that does not exist:
https://github.com/magento/magento2/blob/2.3/app/i18n/magento/de_de/registration.php

It appears that the correct page is:
https://github.com/magento/magento2/tree/2.3/app/i18n/Magento/de_DE

Ergo, the github directory was changed from `blob` to` tree` but links did not update.

**Comment by dshevtsov** [comment]
Thank you, @twocs 
Seems like GitHub server processes [git objects](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects) differently. It is case sensitive when you open file as part of a blob, and case insensitive when you open the file as a tree.
