### ISSUE TITLE
Docs for customAttributeMetadata query are out of date

### ISSUE THREAD

**Issue by mrrobotisback** [magento/devdocs#5032]
```
query product {
 customAttributeMetadata(
   attributes: {
     attribute_code: "energy_label_water_filter"
     entity_type: "4"
   }
 ) {
   items {
     attribute_code
     attribute_type
     attribute_options {
       value
       label
     }
   } 
 }
}
```

Is there a way, for specify more than one attribute_code ?

Exemple:
I need listing of 3 attributes ( energy_label_heating, energy_label_water, energy_label_cooling ) 

I try with this syntax, but it is wrong.
```
query product {
 customAttributeMetadata(
   attributes: {
     attribute_code: "energy_label_cooling", "energy_label_water", " energy_label_heating"
     entity_type: "4"
   }
 ) {
   items {
     attribute_code
     attribute_type
     attribute_options {
       value
       label
     }
   } 
 }
}
```
Is there a way to solve this problem easly ?
Or do I need to create a module? 

Thank you in advance ;)

**Comment by keharper** [comment]
@mrrobotisback It looks like the syntax of the query changed since this topic was posted. This is the correct syntax with two items. It's easy to add a third.

```
query {
  customAttributeMetadata(
    attributes: [
      { 
        attribute_code: "energy_label_heating"
        entity_type: "<string1>" 
      }
      { 
        attribute_code: "energy_label_water"
        entity_type: "<string2>" 
      }
    ]
  ) {
    items {
      attribute_code
      attribute_type
      entity_type
    }
  }
}
```

I'm keeping this issue open because the topic needs to be updated.

**Comment by mrrobotisback** [comment]
Thank you for the response, now it work.

But i have another question, can i take a name of attribute and not only attribute code, from insomnia i see only 4 option:

``` 
    items {
      attribute_code
      attribute_type
      entity_type
      attribute_options {
       value
       label
     }
    }
```
But i need of attribute name.
is there a way ?

**Comment by keharper** [comment]
@mrrobotisback Your question is beyond what I can answer. I suggest asking on the graphql channel in the [EngComm Slack](https://tinyurl.com/engcom-slack).
