### ISSUE TITLE
Magento2 : Add dynamic labels to system XML

### ISSUE THREAD

**Issue by mohinik-chetu** [magento/devdocs#505]
Please suggest a way to add dynamic labels, comments to system XML file. Tried using [module]/field_comment method but no success.

**Comment by xcomSteveJohnson** [comment]
Have you asked this question in the [Magento 2 GitHub issues](https://github.com/magento/magento2/issues), stackexchange, or other technical forum? If so, would you mind linking this issue so we can see the answer when you find it?

Meanwhile we'll try and find an answer but don't want to duplicate effort. Thanks

**Comment by mohinik-chetu** [comment]
Here only, I asked this. But related thing was discussed in http://magento.stackexchange.com/questions/45201/magento2-dynamic-system-configuration-comments

**Comment by almarchenko** [comment]
@mohinik-chetu I followed the link to github, and it led to https://github.com/magento/magento2/pull/2626 in the end.
We'll investigate what's going on with this issue, and let you know about the docs.
Thank you.

**Comment by mohinik-chetu** [comment]
For more clarification, I am creating a custom payment module, where I want to append brand name(dynamically from db/constant file) to all text available in system configuration file.

**Comment by sunilit42** [comment]
@mohinik-chetu have you found anything for this?

**Comment by almarchenko** [comment]
Internal issue MAGETWO-60331

**Comment by sereban** [comment]
Hi @mohinik-chetu What is module in [module]/field_comment? 

I looked at Config/Reader that is responsible for system.xml file, and do not find an existing way to do this (however maybe Im wrong).

It is possible to use dynamic things in node attributes. And eah dynamic variable for attribute should look like:

<section some_attribute="section_name/group_name/field_name">
 ....
</section>

However you can add your own compiler which allows to do this:
You can configure compiler here:
\Magento\Framework\View\TemplateEngine\Xhtml\Compiler
and add item with name "comment" or with name "label". Extend this compiler from standard compiler that is used now. In this compiler you will have argument $processedObject. This argument should have information about readed section.

I hope this information will be helpfull for you.
@see
\Magento\Config\Model\Config\Structure\Reader
\Magento\Config\Model\Config\Compiler\IncludeElement
\Magento\Framework\View\TemplateEngine\Xhtml\CompilerInterface
\Magento\Framework\View\TemplateEngine\Xhtml\Compiler

Thanks,
Sergii

**Comment by markdavidsonmis** [comment]
Try following way:

Change your comment tag by


<comment><model>Vendor\Module\Model\Comment</model></comment>
And your model class should be


namespace Vendor\Module\Model;

class Comment implements \Magento\Config\Model\Config\CommentInterface
{
    /**
     * Retrieve element comment by element value
     * @param string $elementValue
     * @return string
     */
    public function getCommentText($elementValue)
    {
        //do some calculations here
        return 'Some string based on the calculations';
    }
}

Thanks,
<a href="https://magnetoitsolutions.com/services/magento-support/">Magento Support </a>

**Comment by jeff-matthews** [comment]
We welcome community contributions to update the docs for this feature.

**Comment by dshevtsov** [comment]
The solution is documented in https://github.com/magento/magento2/pull/2626#issuecomment-305904005
Must be ported to devdocs.

**Comment by shrielenee** [comment]
Hi @rafaelstz - Is this something you can help us with? It requires using the solution documented in the link above and adding it to the relevant page. Let us know! 💯

**Comment by rafaelstz** [comment]
I'm taking a look @shrielenee .

**Comment by rafaelstz** [comment]
@shrielenee I think that this page below is the more relevant page to add it, what do you think? I can create the usual way, then create an optional and dynamic way to add the label.

https://devdocs.magento.com/guides/v2.2/ext-best-practices/extension-coding/example-module-adminpage.html

**Comment by shrielenee** [comment]
Hi @rafaelstz - our very own @vrann documented the solution in the [mentioned issue](https://github.com/magento/magento2/pull/2626#issuecomment-305904005) back in 2017. However, if you know of another or more efficient way to accomplish this we absolutely welcome your work.

We would love it if you submitted a PR for this - please do! I'll check back here in a weeks time to get an update on your progress. Thanks for being willing to help out!

**Comment by shrielenee** [comment]
Hi @rafaelstz - any news on this? Thanks!

**Comment by shrielenee** [comment]
We haven't heard from you regarding this issue in two weeks. Due to inactivity, we are closing this issue.
If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!

**Comment by ikef** [comment]
Any solution for this in 2024?
