### ISSUE TITLE
Next  / Previous

### ISSUE THREAD

**Issue by pocallaghan** [magento/devdocs#506]
It would be nice to introduce some kind of next / previous mechanism to every page. The left hand column shows which page of a specific 'guide' you are on, so you can use it to move to the next or previous article. When there is either a long navigation and short article or long article and short navigation, this can become annoying. In some guides the Related Articles at the bottom are making this easier in a sort of ad-hoc manner, but it's often not clear which is actually the next document.

If we could get some Next / Previous buttons near the bottom, probably just before related articles I feel this would aid navigation through the guides substantially. Something akin to on https://read-the-docs.readthedocs.org/en/latest/getting_started.html

**Comment by pocallaghan** [comment]
Just as a quick follow up to this, I'm not remotely familiar with Jekyll let alone how you're employing it so this may not be relevant, but it seems like it does support page.next and page.previous type syntax - http://david.elbe.me/jekyll/2015/06/20/how-to-link-to-next-and-previous-post-with-jekyll.html

**Comment by xcomSteveJohnson** [comment]
I'm skeptical of that because who's to say what you want to read before and after a particular topic? Not everybody learns the same way.

I'd like to hear more detail from you and others.

**Comment by pocallaghan** [comment]
There is an implied order to the pages within a guide, the order in which they appear in the left hand navigation. If people want to learn in different ways, I don't see a single reason having two additional links on the page makes the remotest bit of difference to their workflow. I'm not saying the link text has to (or even should) say "Next" or "Previous", the title from the navigation would arguably make more sense.

If however you wish to follow the guide through in the order it was laid out, it's currently more difficult than it need be, due to the lack of consistently placed link to the 'next' page. You have to actively search for the current page in the left hand column in order to continue the topic. Does this make the documentation unusable? No, of course not. Would the addition of links make it easier to follow a guide from start to finish? Yes, I find it hard to imagine that somebody could disagree with that.

Granted, given the way the documentation is currently laid out in places, the next page might not always be entirely relevant. Navigating through the prerequisites for example, makes sense. But do you need to go from "PHP 5.5 or 5.6—CentOS", to "PHP 5.5 or 5.6—Ubuntu" though? Probably not. If however you're reading about "Installing Varnish", isn't it far more likely you'll next be looking to "Configure Varnish" rather than say "MySQL Message Queues".

This is a common navigation mechanism that is used in many major documentation platforms.

- http://uk1.php.net/manual/en/book.pcre.php - top right
- https://symfony.com/doc/current/book/from_flat_php_to_symfony2.html - bottom of the page
- https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html - top and bottom of the page
- https://read-the-docs.readthedocs.org/en/latest/badges.html#status-badges - bottom of the page
- https://www.drupal.org/getting-started/7/admin - bottom of the page

**Comment by xcomSteveJohnson** [comment]
In your example about Varnish isn't it also likely that you would look down the vertical TOC to see what the next topic is? And we do have a Next topic at the bottom of the topic you mention.

Other types of tasks, like creating modules, aren't as clear cut. We don't know in advance what order any particular person needs to know things.

Thanks for your input! I look forward to hearing from others in this issue also. What do you think?

**Comment by xcomSteveJohnson** [comment]
Tracking with internal issue MAGEDOC-2513

**Comment by jcalcaben** [comment]
Thank you for the suggestion. Please look at our new UI. We have implemented this feature in some pages, but we feel the Related Links does a good job of guiding users to the appropriate next steps.

For an example, please see: http://devdocs.magento.com/guides/v2.1/get-started/order-tutorial/order-intro.html
