### ISSUE TITLE
I want to translate this doc, what is the its licence?

### ISSUE THREAD

**Issue by LiangWei88** [magento/devdocs#507]
Hi I want to translate this document to chinese.
What is the licence?
How should I do?
Can I put the translation in my github or other site?
Thank you

**Comment by xcomSteveJohnson** [comment]
Sorry for the delay. I'm not sure, I'll try and find out soon. Thanks for asking.

**Comment by LiangWei88** [comment]
so, do you have any news?

**Comment by xcomSteveJohnson** [comment]
Not yet but we have a question.

What is your ultimate destination for translations? Your own site or devdocs.magento.com?

What languages are you considering translating into?

**Comment by LiangWei88** [comment]
I don't have plan to setup my own site to provide magento doc.
I think devdocs.magento.com is a good place for the translations.
If I can take credit for my contribution it would be better.
Or I can just forks the docs on github, and begin to translate.
I just worry about the licence.

**Comment by xcomSteveJohnson** [comment]
Thanks for the information. Have you had experience with translating GitHub pages before? Among other things we're curious if GitHub natively supports localization. It probably does but this is an area we're unfamiliar with right now.

We're circulating internal e-mails with Legal and should have an answer soon. Thanks again.

**Comment by xcomSteveJohnson** [comment]
@LiangWei88  Looks like licensing isn't an issue as long as the translations stay on devdocs. More questions for you:

*  Please tell us about your translation methodology. Do you have translators with programming and e-commerce domain experience?
*  Do you plan to translate everything or a subset of what is on devdocs?
* How do you plan to maintain the translations, considering that devdocs changes constantly and there will soon be a set of 2.1 content as well.

**Comment by xcomSteveJohnson** [comment]
@LiangWei88 Any update?

**Comment by xcomSteveJohnson** [comment]
Closing.
