### ISSUE TITLE
Not full description on --base-url-secure

### ISSUE THREAD

**Issue by Rykh** [magento/devdocs#508]
A parameter `--base-url-secure` can be an URL also. For example, `--base-url-secure='https://example.com'`

**Comment by xcomSteveJohnson** [comment]
This should be fixed now. If so, please close.

**Comment by Rykh** [comment]
Now problem with the table style 
![screen1](https://cloud.githubusercontent.com/assets/10633702/12868634/0854dfba-cd13-11e5-8533-48a2d1a267d4.PNG)

**Comment by xcomSteveJohnson** [comment]
Oops, sorry about that. Should be fixed any minute.
