### ISSUE TITLE
Magento 2 server configuration and development toolset

### ISSUE THREAD

**Issue by magenx** [magento/devdocs#509]
https://github.com/magenx/Magento-Automated-Server-Configuration-from-MagenX/tree/master/Magento-2/CentOS-7

we have created two files , one is to configure Magento 2 on CentOS 7.
complete server configuration from scratch to production.

another file was created for server templates. 
you can easily reset the server for any other user/domain, that was configured and then restored from its snapshot or image.

handy toolset for community to quickly configure own Magento 2 on CentOS 7 and continue to study magento server configuration and Magento 2 development.

probably it can be included in some third party tools/scripts or documented for CentOS 7 server setup.

cheers

**Comment by xcomSteveJohnson** [comment]
Sounds good. Closing because there's nothing for us to do.
