### ISSUE TITLE
2.3.2-validated PHP version?

### ISSUE THREAD

**Issue by not-art** [magento/devdocs#5103]
# Topic clarification/correction request
Currently, the 2.3.2 Open Source and Commerce release notes do not reference the certified, tested version of PHP. The 2.3 DevDocs Tech Requirements also only list the tested/certified PHP version for 2.3.1, not 2.3.2.

If you're using the debian stretch, you need to upgrade PHP to 7.2.20 in order to install the required libsodium 1.0.13 package update, but Magento hasn't yet announced if 7.2.20 is a stable version of PHP to use for Magento if upgrading to 2.3.2.

## Topic Link
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.html
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.html
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php

## Description
Please publish what version of PHP is certified & tested against Magento 2.3.2

## Possible solutions
If PHP 7.2.11 is still the only certified, tested PHP version, perhaps provide additional libsodium upgrade steps for Magento stores running linux packages that don't yet support libsodium 1.0.13 in older PHP 7.2.X releases? (curl, etc)

**Comment by jcalcaben** [comment]
@jfrontain Who can we contact to get this information?

**Comment by jeff-matthews** [comment]
@chernenm

**Comment by jfrontain** [comment]
@jcalcaben, it looks as though Magento support policy does not "certify" any particular version of PHP. Although we test PHP compatibility on a range of environments, we stick to only a general message that the Magento platform is compatible with PHP 7.1.x, 7.2.x and 7.3.x (and that 7.0.x is no longer supported). 

That said, Olena Marchenko would know best about our test environments and who has the most experience with  libsodium.

**Comment by hostep** [comment]
Small remark, libsodium is not strictly needed to run Magento, it is highly recommended, but not strictly needed.
If it isn't installed, Magento will not use the new argon2id password hashing algorithm introduced in Magento 2.3.2, it will fall back to the old sha256 algorithm instead and will continue working just fine (as long as you don't already have upgraded password hashes in your database).

**Comment by jeff-matthews** [comment]
The following DevBlog post provides the most up-to-date info we have about PHP support for the 2.2.x and 2.3.x release lines: https://community.magento.com/t5/Magento-DevBlog/Changes-to-supported-PHP-versions-due-to-PHP-7-1-End-of-Life/ba-p/140142.

The system requirements topic on devdocs pulls the PHP version directly from the `composer.lock` file for the most recent patch release.

Our general policy is to not provide instructions for installing third-party tools/software on devdocs and instead defer to the third-party's documentation, which is what we are currently doing in the release notes: https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=libsodium#known-issues
