### ISSUE TITLE
Provide detailed steps on how to create and use viewModels

### ISSUE THREAD

**Issue by diazwatson** [magento/devdocs#5115]
# New topic request

## Description
In many places we encourage the use of `viewModel` over other techniques to inject functionality in elements, however detailed steps on how to create and use a `viewModel` are only found in https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html#layout_markup_add_to_elements

## Questions:
- Should we redirect readers to this page?
- How about those who search specifically for viewModels?
- Should we add a separated section to explain how to create and use a `viewModel` and then create links to this page when the word `viewModel` is mentioned?

## Content checklist

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains code samples that shows ____.
- [ ] Other (please specify)

### Some examples:
- https://devdocs.magento.com/guides/v2.3/architecture/archi_perspectives/ABasics_intro.html
- https://devdocs.magento.com/guides/v2.3/search.html?query=viewModel

**Comment by diazwatson** [comment]
I am ready to create a PR with changes to fix this issue (so please assign to me if this issue is accepted), although would need DevDocs team to provide answers to these questions.

**Comment by jcalcaben** [comment]
Issue is yours @diazwatson 

Answers:
1. Yes, we should direct people to this page from the page you listed
2. If you have viewModel used in your topic, our search indexer should pick it up
3. Yes, please create this section. Creating links is optional.
