### ISSUE TITLE
composer misses repositories

### ISSUE THREAD

**Issue by atombrella** [magento/devdocs#514]
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-create.html

I got it working only after adding this section to the `composer.json` file.

    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],

**Comment by almarchenko** [comment]
Thank you for sharing! We'll check and update the doc.

**Comment by almarchenko** [comment]
Hi @atombrella,

According to our tests the theme is created correctly the way it is described, no need to add the piece of code you mention. 
Is it ok if we close the issue?

**Comment by atombrella** [comment]
No, you can leave it closed.
