### ISSUE TITLE
REST API Store Code scope documentation differs from application

### ISSUE THREAD

**Issue by rain2o** [magento/devdocs#5149]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/get-started/gs-web-api-request.html#endpoints

## Description

There seems to be a discrepancy between real-life implementation of the M2 REST API and the documentation around it. The documentation for the API structure is as follows:

>An endpoint is a combination of the server that fulfills a request, the web service, the store code, the resource against which the request is being made, and any template parameters.
For example, in the http://magento.ll/index.php/rest/default/V1/customerGroups/:id endpoint, the server is magento.ll/index.php/, the web service is rest, the resource is /V1/customerGroups, and the template parameter is id.

Based on the docs, if I had a store code of `en_us` I would call `http://{domain}/index.php/rest/en_us/V1/{endpoint}`. However, when checking how Magento's default theme Luma, and Swagger, actually used the APIs, I noticed the structure they both use is `http://{domain}/index.php/en_us/rest/en_us/V1/{endpoint}`. Notice the extra store code before `rest`.

## Possible solutions

It would be useful to have the documentation explain what the difference is between these two store code placements, if there is one at all. In testing I have found that you can put the store code before, after, or around `rest`, and most of the time it doesn't make a difference, but sometimes it seems to. Is there a reason for these two placements, and is there a difference between them?

## Additional information

Originally opened as an issue on Magento 2 repo (https://github.com/magento/magento2/issues/24071) but after testing in fresh sandbox I realized the issue I was having was unique to my setup, and it seems to be a matter of documentation missing the extra information needed for understanding the differences.

**Comment by erikmarr** [comment]
@keharper this looks like it might turn into a devdocs PR, but wanted to see if you had thoughts before proceeding.

**Comment by keharper** [comment]
@paliarush Is this issue correct?

**Comment by paliarush** [comment]
Described situation may happen when store code is [configured to be used in URLs](https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_websites.html#multi-storecode-baseurl). 

I do not think this is a bug.

**Comment by keharper** [comment]
Closing based on Alex's statement.
