### ISSUE TITLE
The official documentation should state that a «before» plugin could avoid declaration of unused last arguments

### ISSUE THREAD

**Issue by dfediuk** [magento/devdocs#516]
https://mage2.pro/t/468
https://github.com/magento/magento2/issues/3326

**Comment by xcomSteveJohnson** [comment]
Added to the [plug-in topic](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html#plugin-priority). It took some thought as to where to put the info. Please close this if you approve.

**Comment by xcomSteveJohnson** [comment]
Closing.
