### ISSUE TITLE
Clarify when to use the command for deploying a theme

### ISSUE THREAD

**Issue by nettree** [magento/devdocs#5179]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-create.html

## Description

Down to the bottom of the topic link page, in section `Troubleshooting`, it suggests we can run the static content deploy command like `magento setup:static-content:deploy en_US` if:
```
theme changes are not visible even after clearing the cache
```
Based on my understanding, if we're in developer mode, this command should not be run, right? 

## Possible solutions

Maybe it is actually trying to say use `magento dev:source-theme:deploy`? Or maybe we should add some comment like `(don't run it on developer mode)`

## Additional information

We found most of time when a theme is not visible is because it's marked as virtual in database, we have to manually change that back in `theme` table to mark the theme as not virtual, then we're able to see the theme

**Comment by drpayyne** [comment]
@jeff-matthews @shrielenee @keharper Please assign this to me, so I can start working on this. Thanks!

**Comment by keharper** [comment]
@drpayyne It's yours.
