### ISSUE TITLE
The official documentation should state that a «before» plugin could return nothing if it needs not modify any argument

### ISSUE THREAD

**Issue by dfediuk** [magento/devdocs#518]
https://mage2.pro/t/464

**Comment by xcomSteveJohnson** [comment]
Added to the [plug-in topic](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html#plugin-priority). It took some thought as to where to put the info. Please close this if you approve.

**Comment by xcomSteveJohnson** [comment]
Closing
