### ISSUE TITLE
Need more info about configuring TinyMCE

### ISSUE THREAD

**Issue by hubertinio** [magento/devdocs#5185]
# General issue

Verify that instructions on the page work. Issue submitter @hubertinio was not able to configure it correctly in di.xml.

https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/wysiwyg/configure-tinymce-editor.html

## Description:
Proposed solution don`t work.

## Possible solutions:

```
namespace Module\Namespace\Plugin\Cms\Wysiwyg;

class ConfigProvider
{
    public function afterGetConfig(
        \Magento\Cms\Model\Wysiwyg\DefaultConfigProvider $subject,
        $result
    ) {
        $result['force_p_newlines'] = false;
        $result['forced_root_block'] = '';
        return $result;
    }
}```

**Comment by erikmarr** [comment]
Hi @hubertinio thank you for taking the time to submit an issue. Can you provide more context and information about the issue and your proposed solution?

**Comment by hubertinio** [comment]
I have plan add these options from tinyMce manual to it initialize config in
lib/web/mage/adminhtml/wysiwyg/tiny_mce/setup.js::33
I have achived it by plugin
```
    <type name="Magento\Cms\Model\Wysiwyg\DefaultConfigProvider">
        <plugin name="tkaninowo-cms-wysiwyg-config"
                type="Adrem\Tkaninowo\Plugin\Cms\Wysiwyg\ConfigProvider" />
    </type>
```

**Comment by shrielenee** [comment]
Hey @hubertinio --- Are you using an external plugin to provide internal functionality? What result are you attempting to achieve by doing this? The snippet you provided is not in the documentation page you referenced in this issue.

**Comment by hubertinio** [comment]
Yes, I did external plugin and this is my solution, because that one mentioned in manual in section "Edit the module’s di.xml file" doesnt work.

**Comment by dobooth** [comment]
Fixed in https://github.com/magento/devdocs/pull/6681
