### ISSUE TITLE
Need info about structures in Adding a custom indexer

### ISSUE THREAD

**Issue by ericclaeren** [magento/devdocs#5218]
How does 'structure' work in an indexer?

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexing-custom.html

## Description:

There apparently is a ```<structure>``` element within an indexer.xml, but this is not described on the documentation page. 

## Possible solutions:

Explain what structure does optionally with a code example.  A use case when to use db_schema.xml for an index or when to use structure would be helpful.

**Comment by dobooth** [comment]
@ericclaeren I am not seeing a reference to 'structure'. Can you provide a link to the code?

**Comment by ericclaeren** [comment]
Hi, It is used here:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogSearch/etc/indexer.xml

Maybe in some other indexer files as well.

**Comment by ericclaeren** [comment]
@dobooth Was the information I provided useful?

**Comment by atwixfirster** [comment]
PR: https://github.com/magento/devdocs/pull/6042
