### ISSUE TITLE
Update Magento binding syntax for template binding

### ISSUE THREAD

**Issue by rani-webkul** [magento/devdocs#5233]
# Topic clarification/correction request

## Description
Issue Reference : https://github.com/magento/magento2/issues/24087
Here Knockout Syntax and Magento Syntax for  template binding is wrong. It's not working.

## Possible solutions
It should be
**Knockout Syntax**
&lt;div data-bind="template:{name:'templateUrl',data:{}}"&gt;&lt;/div&gt;
**Magento Syntax**
&lt;div template="{name:'templateUrl',data:{}}" &gt;&lt;/div&gt;

**Comment by keharper** [comment]
PR: https://github.com/magento/devdocs/pull/5234

**Comment by keharper** [comment]
Closed per #5262
