### ISSUE TITLE
Invalid example in CSS in responsive design topic

### ISSUE THREAD

**Issue by magudelo62** [magento/devdocs#5235]
# Bug report

## Description

Why does Magento documentation show a media breakpoint that doesn't work? (Tablet breakpoint)

![63506700-52a37400-c4d6-11e9-88b1-bfe252f1b8a3](https://user-images.githubusercontent.com/5323922/63508725-c6e01680-c4da-11e9-81b8-cb5a087f0332.png)

> https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.html#lib_rwd
> https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_css.html#lib_rwd

### Steps to reproduce

1. When you try to use the .media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__l) into less files, this breakpoint does not work. You have to create the media breakpoint by added a new one for tablets

## Expected result

The media query should works as documentations says

## Possible solutions

Introduce this breakpoint into magento's lib core or delete the tablets media breakpoint comment from documentation.

## Additional information

See more about the breakpoint issue discussion here https://github.com/magento/magento2/issues/21005

**Comment by atwixfirster** [comment]
Hi!

There are two different tablet declarations:
- [Tablets](https://github.com/magento/magento2/blob/2.3/app/design/adminhtml/Magento/backend/Magento_Backend/web/css/source/module/_menu.less#L532) for back-end styles
- [Tablet](https://github.com/magento/magento2/blob/2.3/app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/checkout/_order-summary.less#L236) for front-end

I've fixed an example code in https://github.com/magento/devdocs/pull/5306

Thanks!
