### ISSUE TITLE
Markdown linting: Header levels should only increment by one level at a time (MD001)

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5240]
# Bug report

## Description

The Markdown linter reports about 276 issues when the [rule 'MD001'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md001---header-levels-should-only-increment-by-one-level-at-a-time) is enabled.

### Steps to reproduce

1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD001'` to `rule 'MD001'`.
2. In your terminal, run `rake test:md`.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

## Additional information

- Create working branches from the [`MD001-integration`](https://github.com/magento/devdocs/tree/MD001-integration) branch
- Use the [`MD001-integration`](https://github.com/magento/devdocs/tree/MD001-integration) branch as the base branch whenc reating PRs

**Comment by dshevtsov** [comment]
@hguthrie, it is not clear why the _Waiting for response_ label was added here. Could you please add the request for response in comments here?

**Comment by jeff-matthews** [comment]
Before this issue can be worked, we need to create a new CSS class in the [devdocs theme](https://github.com/magento-devdocs/devdocs-theme) that we can use to replace some occurrences of H4s (e.g., Related topics, cloud topics, API topics). This issue is not ready for dev.

**Comment by hguthrie** [comment]
The new procedure class is live. The Cloud guide has been scrubbed.

**Comment by jeff-matthews** [comment]
Thank you for scrubbing the cloud topics @hguthrie.

We likely need a similar solution for instances of **Related topics** and **Next steps**. 

I'm also concerned about headings that are too long. For example: https://github.com/magento/devdocs/pull/5310/files#diff-107c3817ff51b41f675673f8ac907514R24. That won't look good in the **On this page** table of contents. I suspect the original author used an H3 to circumvent that issue. There are likely cases where we need to either shorten headings or apply different formatting.

I'll start working on that.

**Comment by hguthrie** [comment]
@jeff-matthews In Cloud guide, I reduced the Next steps and Previous steps to be BOLD and have no header value. There were not part of a tutorial, and we may eliminate them soon anyway. But I preferred a closer review of the other guides before using the same solution.

**Comment by jeff-matthews** [comment]
I created a new class called `pseudo-header` for the **Related topics** and **Next step** sections:

<img width="801" alt="Screen Shot 2019-10-03 at 8 22 30 AM" src="https://user-images.githubusercontent.com/13662379/66130492-6652f780-e5b7-11e9-86d0-9a05656cb2a6.png">

@keharper, do you think you could use these for other scenarios in API docs for examples and what not?

**Comment by jeff-matthews** [comment]
I got some feedback on this.

Class should use H4 font size with default text color (black). Change the class name to `ref-header`. We can create another class later to address scenarios where we use plain bolded text as a header (API docs).
