### ISSUE TITLE
Markdown linting: Inconsistent unordered list style (MD004 )

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5241]
# Bug report

## Description

The Markdown linter reports about 5224 issues when [rule 'MD004'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md004---unordered-list-style) is enabled.

### Instructions

1. Checkout the `MD004-integration` branch.
1. In the `_checks/styles/style-rules-prod` file, change `exclude_rule 'MD004'` to `rule 'MD004'`.
1. In your terminal, run `rake test:md`.
1. Review the list of errors.
1. Add a comment to this issue claiming a single directory that you want to work on (should include both v2.2 and v2.3 directories when applicable).
1. Fix errors.

### Test your updates

1. Follow "Instructions" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message.

### Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

## Additional information

- **Scope:** It makes sense to fix the following issues at the same time as MD004:
   - MD005: List indentation
   - MD006: Start bulleted lists at the beginning of a line
   - MD007: List indentation
   - MD030: Spaces after list markers

- See the [Markdown linting issues](https://github.com/magento/devdocs/wiki/Markdown-linting-issues) wiki page for detailed guidelines.

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/ui_comp_guide/`
- `guides/v2.3/ui_comp_guide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/config-guide/`
- `guides/v2.3/config-guide/`

**Comment by jeff-matthews** [comment]
I'm working in the following directories:

- `guides/v2.2/release-notes/`
- `guides/v2.3/release-notes/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/frontend-dev-guide/`
- `guides/v2.3/frontend-dev-guide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/migration/`
- `guides/v2.3/migration/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/design-styleguide/`
- `guides/v2.3/design-styleguide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.3/graphql/`
- `guides/v2.3/inventory/`
- `guides/v2.2/mtf/`
- `guides/v2.3/mtf/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/cloud/`
- `guides/v2.3/cloud/`
- `community/`
