### ISSUE TITLE
Markdown linting: Inconsistent indentation for list items at the same level (MD005 )

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5242]
# Bug report

## Description

The Markdown linter reports about 622 issues when the [rule 'MD005'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md005---inconsistent-indentation-for-list-items-at-the-same-level) is enabled.

### Instructions

1. Add a comment to this issue requesting the `devdocs-admins` to assign the issue to you.
1. Checkout the `MD005-integration` branch.
1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD005'` to `rule 'MD005'`.
1. In your terminal, run `rake test:md`.
1. Review the list of errors.
1. Add a comment to this issue claiming a directory that you want to work on (should include both v2.2 and v2.3 directories when applicable).
1. Fix errors.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message or PR comments.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

## Additional information

- **Scope:** It makes sense to fix the following issues at the same time as MD005:
   - MD006: Start bulleted lists at the beginning of a line
   - MD007: List indentation
   - MD030: Spaces after list markers

- See the [Markdown linting issues](https://github.com/magento/devdocs/wiki/Markdown-linting-issues) wiki page for detailed guidelines.

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.3/javascript-dev-guide/`
- `guides/v2.3/marketplace/`
- `guides/v2.3/mtf/`
- `guides/v2.3/payments-integrations/`
- `guides/v2.3/release-notes/`
- `guides/v2.3/rest/tutorials/`
- `guides/v2.3/ui_comp_guide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.3/coding-standards/`
- `guides/v2.3/config-guide/`
- `guides/v2.3/frontend-dev-guide/`
- `guides/v2.3/graphql/`
- `guides/v2.3/howdoi/`
- `guides/v2.3/install-gde/`
