### ISSUE TITLE
Markdown linting: Unordered list indentation (MD007)

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5244]
# Bug report

## Description

The Markdown linter reports about 436 issues when the [rule 'MD007'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md007---unordered-list-indentation) is enabled with 3 spaces for each nesting level.

### Instructions

1. Add a comment to this issue requesting the `devdocs-admins` to assign the issue to you.
1. Checkout the `MD007-integration` branch.
1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD007'` to `rule 'MD007', :indent => 3`.
1. In your terminal, run `rake test:md`.
1. Review the list of errors.
1. Add a comment to this issue claiming a directory that you want to work on (should include both v2.2 and v2.3 directories when applicable).
1. Fix errors.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message or PR comments.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

## Additional information

- **Scope:** It makes sense to fix the following issues at the same time as MD007:
   - MD030: Spaces after list markers

- See the [Markdown linting issues](https://github.com/magento/devdocs/wiki/Markdown-linting-issues) wiki page for detailed guidelines.

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `_includes/`
- `_videos/`
- `community/`
- `extensions/`
- `guides/v2.2/architecture/`
- `guides/v2.2/cloud/`
- `guides/v2.2/coding-standards/`
- `guides/v2.2/comp-mgr/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/config-guide/`
- `guides/v2.2/design-styleguide/`
- `guides/v2.2/ext-best-practices/`
- `guides/v2.2/frontend-dev-guide/`
- `guides/v2.2/get-started/`
- `guides/v2.2/install-gde/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/javascript-dev-guide/`
- `guides/v2.2/migration/`
- `guides/v2.2/mrg/`
- `guides/v2.2/mtf/`
- `guides/v2.2/release-notes/`
- `guides/v2.2/test/`
- `guides/v2.2/ui_comp_guide/`
- `guides/v2.3/architecture/`

**Comment by jeff-matthews** [comment]
@dshevtsov, almost all errors have been fixed. 

I'm still getting errors on the following files and I'm not sure why:

```
guides/v2.2/comp-mgr/cli/cli-upgrade.md:140: MD007 Unordered list indentation
guides/v2.2/config-guide/bootstrap/magento-bootstrap.md:82: MD007 Unordered list indentation
guides/v2.3/config-guide/bootstrap/magento-bootstrap.md:82: MD007 Unordered list indentation
```

I think it has something to do with nested lists. Here's an example of an error.

```
1. Error handling (in the following priority order):

   1. If you're using [developer mode]({{ page.baseurl }}/config-guide/bootstrap/magento-modes.html#developer-mode):
      *  If the Magento application is not installed, redirect to Setup Wizard.
      *  If the Magento application is installed, display an error and HTTP status code 500 (Internal Server Error).
   1. If the Magento application is in maintenance mode, display a
``` 

I've checked for errors in other lists in file, but there are none. It's isolated to these deeply nested lists. This is blocking this rule.

**Comment by dshevtsov** [comment]
Try this please:
```
1. Error handling (in the following priority order):

   1. If you're using [developer mode]({{ page.baseurl }}/config-guide/bootstrap/magento-modes.html#developer-mode):
   *  If the Magento application is not installed, redirect to Setup Wizard.
   *  If the Magento application is installed, display an error and HTTP status code 500 (Internal Server Error).
   1. If the Magento application is in maintenance mode, display 
```

**Comment by jeff-matthews** [comment]
Still shows as an error:

```
guides/v2.2/config-guide/bootstrap/magento-bootstrap.md:82: MD007 Unordered list indentation
guides/v2.3/config-guide/bootstrap/magento-bootstrap.md:82: MD007 Unordered list indentation
```

I'm going to see if we have other examples of nesting this deeply. If not, we may need to add a convention to our style guide that prohibits nesting past 2 levels in lists.

**Comment by dshevtsov** [comment]
It worked for me on those files.

**Comment by jeff-matthews** [comment]
Indenting 2 spaces works (tests pass and renders HTML correctly.

```
1. Error handling (in the following priority order):

   1. If you're using [developer mode]({{ page.baseurl }}/config-guide/bootstrap/magento-modes.html#developer-mode):
     *  If the Magento application is not installed, redirect to Setup Wizard.
     *  If the Magento application is installed, display an error and HTTP status code 500 (Internal Server Error).
```
```
