### ISSUE TITLE
Markdown linting: Hard tabs (MD010)

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5245]
# Bug report

## Description

The Markdown linter reports about 11725 issues when the [rule 'MD010'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md010---hard-tabs) is enabled.

### Steps to reproduce

1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD010'` to `rule 'MD010'`.
2. In your terminal, run `rake test:md`.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

**Comment by shrielenee** [comment]
@danidelcar This will also have an impact on our repo.

**Comment by atwixfirster** [comment]
@dshevtsov ,
> @danidelcar This will also have an impact on our repo.

Can we break this ISSUE into pieces? 

For example, remove HARD TABS in B2B, Cloud, Coding Standards, etc...

Thank you!

**Comment by dshevtsov** [comment]
@atwixfirster feel free to create several PRs for different scopes like in #5252.

**Comment by jeff-matthews** [comment]
@atwixfirster, I'm fixing errors in the `_include/install/` directory right now, so you should focus on other areas.

**Comment by jeff-matthews** [comment]
@atwixfirster, now I'm working on errors in the `_include/config/` directory.

**Comment by atwixfirster** [comment]
> @atwixfirster, now I'm working on errors in the `_include/config/` directory.

sure 

Thank you, @jeff-matthews

**Comment by jeff-matthews** [comment]
Working on errors in the following directories:

- `guides/v2.2/pattern-library/`
- `guides/v2.3/pattern-library/`

**Comment by jeff-matthews** [comment]
Working on errors in the following directories:

- `guides/v2.2/migration`
- `guides/v2.3/migration`

**Comment by jeff-matthews** [comment]
Working on errors in the following directories:

- `guides/v2.2/release-notes/`
- `guides/v2.3/release-notes/`

**Comment by jeff-matthews** [comment]
Working on errors in the following directories:

- `guides/v2.2/rest/`
- `guides/v2.3/rest/`

**Comment by jeff-matthews** [comment]
I'm working on errors in the following directories:

- `guides/v2.2/test/`
- `guides/v2.3/test/`

**Comment by jeff-matthews** [comment]
I'm working on errors in the following directories:

- `guides/v2.2/ui_comp_guide/`
- `guides/v2.3/ui_comp_guide/`
- `guides/v2.2/javascript-dev-guide/`
- `guides/v2.3/javascript-dev-guide/`

**Comment by jeff-matthews** [comment]
I'm working on errors in the following directories:

- `guides/v2.2/graphql/`
- `guides/v2.3/graphql/`

**Comment by jeff-matthews** [comment]
I'm working on all files in the `_include/` directory except cloud.

**Comment by jeff-matthews** [comment]
I'm working on the remaining errors to complete this issue, which are all located in the following directories:

- `_include/cloud/`
- `guides/v2.2/cloud/`
- `guides/v2.3/cloud/`

**Comment by atwixfirster** [comment]
Working on `guides/pattern-library/` (v2.2, v2.3)

**Comment by atwixfirster** [comment]
Working on `guides/payments-integrations/` (v2.2, v2.3) -

**Comment by atwixfirster** [comment]
Working on `guides/performance-best-practices/` (v2.2, v2.3)

**Comment by atwixfirster** [comment]
Working on `_layouts` files.

**Comment by jeff-matthews** [comment]
A majority of MD010 errors have been resolved in the `db_hardtab_integration` branch. The remaining errors are related to cloud files.

I'm reviewing #5471 to see if we can merge it and resolve the remaining issues.

Please do not submit any more PRs until further notice.
