### ISSUE TITLE
Markdown linting: Headers must start at the beginning of the line (MD023)

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5247]
# Bug report

## Description

The Markdown linter reports about 8 issues when the [rule 'MD023'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md023---headers-must-start-at-the-beginning-of-the-line) is enabled.

### Steps to reproduce

1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD023'` to `rule 'MD023'`.
2. In your terminal, run `rake test:md`.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

**Comment by jeff-matthews** [comment]
There's an error in the MRG topic that must be fixed in the magento2 codebase:

```
devdocs/guides/v2.3/mrg/ce/ReleaseNotification.md
```

I'll open a PR shortly.

**Comment by jeff-matthews** [comment]
PR to fix README: magento/magento2#24489
