### ISSUE TITLE
Markdown linting: Ordered list item prefix (MD029)

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5248]
# Bug report

## Description

The Markdown linter reports about 3867 issues when the [rule 'MD029'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md029---ordered-list-item-prefix) is enabled.

### Instructions

1. Add a comment to this issue requesting the `devdocs-admins` to assign the issue to you.
1. Checkout the `MD029-integration` branch.
1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD029'` to `rule 'MD029'`.
1. In your terminal, run `rake test:md`.
1. Review the list of errors.
1. Add a comment to this issue claiming a directory that you want to work on (should include both v2.2 and v2.3 directories when applicable).
1. Fix errors.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message or PR comments.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

## Additional information

- **Scope:** It makes sense to fix the following issues at the same time as MD029:
   - MD030: Spaces after list markers

- See the [Markdown linting issues](https://github.com/magento/devdocs/wiki/Markdown-linting-issues) wiki page for detailed guidelines.

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `guides/v2.2/rest/`
- `guides/v2.2/test/`
- `guides/v2.2/ui_comp_guide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `release-notes/`
- `performance-best-practices/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `pattern-library/`
- `payments-integrations/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `marketplace/`
- `migration/`
- `mtf/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `inventory/`
- `javascript-dev-guide`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `howdoi/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `graphql/`
- `get-started/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `frontend-dev-guide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `ext-best-practices/`
-`extension-dev-guide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `config-guide/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `design-styleguide/`
- `contributor-guide/`
- `comp-mgr/`
- `coding-standards/`

**Comment by jeff-matthews** [comment]
I'm working on the following directories:

- `advanced-reporting/`
- `architecture/`
- `_vidoes/`

**Comment by jeff-matthews** [comment]
I'm working on all `_include/` files except cloud.

**Comment by jeff-matthews** [comment]
All remaining MD029 errors are in cloud files. I'm working on that next.
