### ISSUE TITLE
Markdown linting: Spaces after list markers (MD030)

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5249]
# Bug report

**We're no longer accepting PRS for this issue.**

## Description

The Markdown linter reports about 11851 issues when the [rule 'MD030'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md030---spaces-after-list-markers) is enabled.

### Instructions

1. Add a comment to this issue requesting the `devdocs-admins` to assign the issue to you.
1. Checkout the `MD030-integration` branch.
1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD030'` to `rule 'MD030', :ul_single => 2, :ol_single => 1, :ul_multi => 2, :ol_multi => 1`.
1. In your terminal, run `rake test:md`.
1. Review the list of errors.
1. Add a comment to this issue claiming a directory that you want to work on (should include both v2.2 and v2.3 directories when applicable).
1. Fix errors.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message or PR comments.

## Expected result

All the reported issues are fixed.
The `rake test:md` command returns `No issues found`.

## Additional information

- **Scope:** Limit your changes to resolving only MD030 errors.
- See the [Markdown linting issues](https://github.com/magento/devdocs/wiki/Markdown-linting-issues) wiki page for detailed guidelines.

**Comment by atwixfirster** [comment]
Working on files in `_includes` directory.

**Comment by jeff-matthews** [comment]
Welcome to the party @drpayyne!

**Comment by eduard13** [comment]
Hi @jeff-matthews, I'd also love to join the party 👯‍♂. Could you please assign me to the ticket?
I'l be working on `extensions/` folder if you don't mind.

**Comment by atwixfirster** [comment]
Working on files in `guides/v2.2/b2b` and `guides/v2.3/b2b` directories:

**Comment by jeff-matthews** [comment]
Welcome aboard @eduard13 !

**Comment by atwixfirster** [comment]
Working on files in the next directories:
- `guides/v2.2/cloud`
- `guides/v2.3/cloud`

**Comment by atwixfirster** [comment]
Working on files in the next directories:
- `guides/v2.2/coding-standards`
- `guides/v2.3/coding-standards`

**Comment by atwixfirster** [comment]
Working on files in the next directories:
- `guides/v2.2/comp-mgr`
- `guides/v2.3/comp-mgr`

PR:

**Comment by eduard13** [comment]
Working on the following directories:
- `guides/v2.2/javascript-dev-guide`
- `guides/v2.3/javascript-dev-guide`

**Comment by atwixfirster** [comment]
Working on files in the next directories:
- `guides/v2.2/config-guide`
- `guides/v2.3/config-guide`

PR:

**Comment by atwixfirster** [comment]
Working on files in the next directories:
- `guides/v2.2/contributor-guide`
- `guides/v2.3/contributor-guide`
- `guides/v2.2/design-styleguide`
- `guides/v2.3/design-styleguide`

PR:

**Comment by atwixfirster** [comment]
Working on files in the next directories:
- `guides/v2.2/ext-best-practices`
- `guides/v2.3/extension-dev-guide`
- `guides/v2.2/ext-best-practices`
- `guides/v2.3/extension-dev-guide`

PR:

**Comment by drpayyne** [comment]
WIP in directory/file:
- `guides/v2.3/ui_comp_guide`

PRs created:
- #5743

**Comment by drpayyne** [comment]
@jeff-matthews Have refactored all code, in the above PRs **_except_** the following directories which have been chosen by developers already to avoid conflicts
- `guides/v2.2/javascript-dev-guide`
- `guides/v2.3/javascript-dev-guide`
- `guides/v2.2/extension-dev-guide`
- `guides/v2.3/extension-dev-guide`
- `_includes`

**I believe there are no remaining issues to take up, regarding MD030.**
Thank you.

**Comment by jeff-matthews** [comment]
Thanks for all your help @drpayyne, @atwixfirster, and @eduard13! I'm going to run some checks on the integration branch and make any final changes necessary before creating a PR to master.

Please do not submit any new PRs.

**Comment by atwixfirster** [comment]
@jeff-matthews , for your notice: `extension-dev-guide` is not fixed. I am working on files from that folder but I did not create a PRs yet.

Thanks

**Comment by jeff-matthews** [comment]
Oh ok. Thanks @atwixfirster. In that case, submit your PRs when you're ready. I think I got ahead of myself and assumed all work was complete.

**Comment by eduard13** [comment]
@jeff-matthews, the same here, planning to finish with `javascript-dev-guide` folder soon.
Thanks.

**Comment by jeff-matthews** [comment]
No problem @eduard13!

**Comment by atwixfirster** [comment]
@jeff-matthews , I've finished all my pending files. All PRs from my side were created. 

Thank you and have fun in review ;)
