### ISSUE TITLE
Missing function escapeCss

### ISSUE THREAD

**Issue by Sharkozp** [magento/devdocs#5273]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-security.html

## Description

Here is missing documentation about function:

> escapeCss

## Possible solutions

Description from code is **Escape string for the CSS context**

**Comment by jeff-matthews** [comment]
Thanks @Sharkozp. Can you please provide an example of using the function?

**Case:** Escape string for the CSS context
**Function:** escapeCss
> [add code snippet]

**Comment by Sharkozp** [comment]
Case: Escape string for the CSS context
Function: escapeCss
```
<?php header('Content-Type: application/xhtml+xml; charset=UTF-8');?>
<?php $css = "background: #000\"><script>alert(1)</script>"; ?>
<div style="<?= $block->escapeCss($css) ?>"></div>
```

Here example from [Zend Framework 2](https://framework.zend.com/manual/2.1/en/modules/zend.escaper.escaping-css.html)

**Comment by jeff-matthews** [comment]
Thanks @Sharkozp! I'll open a PR shortly.
