### ISSUE TITLE
Directory name to be corrected

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/devdocs#528]
Hi,

On http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-apply.html page under
**Troubleshooting (if the changes do not get applied) section.** 

The directory name var/view_preprocessing should be view_preprocessed

**Comment by almarchenko** [comment]
Thanks!

**Comment by almarchenko** [comment]
I've corrected, will be published once PR is merged.
