### ISSUE TITLE
Feedback on page: /guides/v2.3/config-guide/cli/config-cli-subcommands-perf-data.html

### ISSUE THREAD

**Issue by paulgreenspan** [magento/devdocs#5288]
# General issue

## Description:

Path to profile file is wrong

## Possible solutions:

bin/magento setup:perf:generate-fixtures /var/www/html/magento2/setup/performance-toolkit/profiles/ce/small.xml

file location is actually:  /var/www/html/setup/performance-toolkit/profiles/ce/small.xml

**Comment by jeff-matthews** [comment]
Thanks @paulgreenspan. Doesn't the path depend on where you installed the app? Most of our docs recommend installing in a directory called `magento2` instead of in the `html` directory.

**Comment by paulgreenspan** [comment]
@paulgreenspan Yes, I guess that is true.

Maybe we should change the regression envs to match the docs.
