### ISSUE TITLE
Theme inheritance example not working

### ISSUE THREAD

**Issue by MattDeanCS** [magento/devdocs#530]
I was following this guide http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-inherit.html and tried to copy the example at the bottom of the page "OrangeCo decided they should remove the “Report bugs” link from the footer" using

`<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <remove name="report.bugs"/>
    </body>
</page>`

This doesn't work though.

If I swap the `<remove name="report.bugs"/>` out for `<referenceBlock name='report.bugs' remove='true'/>` this now works.

My question is should the example given work and if so why is it not working?
Alternatively is the guide wrong? 
I'm pretty new to this so took quite a while to figure out what was the issue.
Thanks
Matt

**Comment by almarchenko** [comment]
@MattDeanCS  Thank you for reporting this, and I'm very sorry that the sample was not up to date.
I'll investigate and update it.
Thank you.

**Comment by MattDeanCS** [comment]
Thanks @almarchenko 
Not ruling out that it was something I've done.

**Comment by almarchenko** [comment]
@MattDeanCS  I've updated the sample, and also the topic describing layout instructions. 
Will be published in couple of hours, when merged.
Thank you again.
Can we close this?

**Comment by MattDeanCS** [comment]
Great, thanks @almarchenko .
Yes, please close it.
