### ISSUE TITLE
broken table layout for https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html

### ISSUE THREAD

**Issue by UB3RL33T** [magento/devdocs#5316]
# Bug report

## Description

The Issue is the, what I believe is supposed to be a table inside the "Work with configuration and mapping files" section: https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html#migration-config

I believe it's supposed to be a table because of the closing </table> tag at the end of the section.

### Steps to reproduce

1. Open up https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html#migration-config
2. scroll down and see 
![bug](https://user-images.githubusercontent.com/21123031/64177413-bd05ce00-ce5f-11e9-837f-69f1e1319fce.png)

## Expected result

The information should be shown as a table with the mapping file name and the description of those files in a table layout?

**Comment by atwixfirster** [comment]
Fix for this issue has been created 5 days ago - https://github.com/magento/devdocs/pull/5302

**Comment by UB3RL33T** [comment]
I was looking for an existing issue, but didn't find one... silly me.

Thank you for sharing :)

**Comment by jeff-matthews** [comment]
I'm going to close this since the PR that fixes has been merged. The change won't be deployed to production until we merge the `small-changes` branch with `master`.
