### ISSUE TITLE
Update Component Status page

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#5321]
# General issue

## Description:
AFAIK following pages showed status of each component in 2.3.0 preview releases:
https://devdocs.magento.com/guides/v2.3/release-notes/component-status.html

On the following page I can see that not all components showed as "green" status. Is there any real reasons to keep it "yellow"?

## Possible solutions:
- Add meaningful description what this page needed for?
- Mark all components status to "green" to highlight that everything is stable in latest releases

**Comment by jeff-matthews** [comment]
Thanks for the feedback @ihor-sviziev. You're correct, this page only shows module status for the 2.3.0 preview releases and is not updated for patches.

I've raised this issue with internal stakeholders to start a conversation about the goals and purpose of this page. I'll keep this open and report back here when I have more info to share.

**Comment by dobooth** [comment]
Any updates here, @jeff-matthews ?

**Comment by jeff-matthews** [comment]
I've spoken to engineering and we're still trying to figure out what we want to publish for the next minor release (2.4.0).

**Comment by jeff-matthews** [comment]
We should definitely update this topic to clarify that it only applied to the 2.3.0 beta release onle and does not apply to 2.3.x patch releases. I don't think there's any value in changing the remaining statuses to green.

After several internal discussions, we decided to discontinue the component status page and will not publish it for 2.4.0 beta.
