### ISSUE TITLE
Feedback on page: /guides/v2.2/mtf/create_test/create_new_test.html

### ISSUE THREAD

**Issue by sakiland** [magento/devdocs#5359]
# General issue
Script generateFixtureXml.php doesn't exist from Magento 2.2

## Description:
The script generateFixtureXml.php has been removed from Magento 2.2 and above. So, instructions on this page is not relevant any more, and developer cannot create fixture on this way.

## Possible solutions:
 We need to update documentation with relevant instructions.

**Comment by dobooth** [comment]
Hi @sakiland Thanks for the feedback. We no develop for the MTF. As we note in https://devdocs.magento.com/guides/v2.2/mtf/mtf_introduction.html, we are focused on the [MFTF](https://devdocs.magento.com/mftf/docs/introduction.html) for the future of testing and we recommend that new tests be made through it.
The MTF documentation is being kept up until the porting to MFTF is complete. We don't expect to make any updates to the MTF docs.
