### ISSUE TITLE
Magento 1 path used as example in devdocs

### ISSUE THREAD

**Issue by peterjaap** [magento/devdocs#537]
See http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html

Snippet;

> For example, to set the interface preferences for the Magento Admin, use app/code/core/Magento/Backend/etc/adminhtml/di.xml as follows:

**Comment by xcomSteveJohnson** [comment]
That's certainly embarrassing. I fixed the thing you mentioned but IMHO there is an error in the example after the next line:

"You can also specify whether or not the object is shareable in its di.xml as follows:"

Can you advise on a suitable replacement? I have not been able to find one.

**Comment by xcomSteveJohnson** [comment]
Everything should be fixed now. Please close this is you feel it's sufficient.

**Comment by peterjaap** [comment]
'It' in 'its di.xml' refers to the module, not the object. Maybe clarify
that. The rest is okay!

**Comment by xcomSteveJohnson** [comment]
Done, thanks!

**Comment by xcomSteveJohnson** [comment]
Closing, reopen if there is something wrong.
