### ISSUE TITLE
A properly organized RequireJS guide

### ISSUE THREAD

**Issue by drpayyne** [magento/devdocs#5463]
# New topic request

## Description

There isn't a properly structured, and well-explained RequireJS guide present in the DevDocs. I feel RequireJS needs a separate side bar section for itself and have pages for introduction, all the properties and functionalities (Mixin, Shim, Paths, etc) of a RequireJS file with examples, and also how RequireJS is loaded and used in Magento.

Also, I feel the [Javscript Developer Guide](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/bk-javascript-dev-guide.html) itself is very sparse, and the little content in it, is scattered (RequireJS, for example) ? 

## Content checklist

What I propose for the structure of a new RequireJS section to be, open to suggestions, of course.

- A well structure RequireJS Guide `Section`.
  - Introduction to RequireJS `Page`
  - Properties used in RequireJS with examples `Page`
    - `paths`
    - `shim`
    - `deps`
    - `map`
    - `mixins`
    - Anything more?
  - RequireJS in Magento `Page`

## Additional information

```
This would be both restructuring and addition of necessary content for RequireJS.
```

Edit: ~~_I can start working on this once I get some feedback on this, thanks!_~~ PR Created.

**Comment by shrielenee** [comment]
@bdenham @jcalcaben --- @drpayyne Wants to start on this! How does his proposed structure look? Please provide a bit of guidance so he can run with it.

**Comment by jcalcaben** [comment]
I think the best solution for this issue is to create the page "RequireJS in Magento Page" you suggested. Since RequireJS documentation already exists, we want to avoid duplicating these docs and just link to them in the appropriate places on the "RequireJS in Magento Page" topic.

**Comment by drpayyne** [comment]
I agree, @jcalcaben. But I thought _examples and usage_  of RequireJS **in** Magento would be needed in DevDocs since RequireJS isn't as popular and standard as jQuery for example, for which we definitely don't need docs in DevDocs.

Thank you.

**Comment by drpayyne** [comment]
I can start working on this for a preliminary PR, please assign me to avoid duplicate work. Thanks!

**Comment by jcalcaben** [comment]
@drpayyne If necessary, you can maybe create an additional topic "RequireJS examples and usage"

**Comment by drpayyne** [comment]
Will do, thanks
