### ISSUE TITLE
Prerequisite task in "Create a configurable product using bulk APIs" tutorial doesn't work

### ISSUE THREAD

**Issue by webmaster-sfs** [magento/devdocs#5468]
When I get to the last step (Use the bin/magento queue:consumers:start async.operations.all command to enable bulk endpoint processing.), I get an error:

$ bin/magento queue:consumers:start async.operations.all
In ConnectionTypeResolver.php line 43:

I'm on Magento CE 2.3.1 

Affected topic: /guides/v2.3/rest/tutorials/bulk-configurable-product/config-product-intro.html

#5867  fixes this issue

**Comment by keharper** [comment]
@nuzil Is there any system configuration that needs to occur befoe you run `bin/magento queue:consumers:start async.operations.all`?

**Comment by brunoroeder** [comment]
@keharper and @webmaster-sfs You should configure the cron_consumers_runner before: https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html

**Comment by meker12** [comment]
This was fixed in #5867 fixes this issue.  Must ensure that RabbitMQ is configured before running the command provided.
