### ISSUE TITLE
Frontend Guide, layout XML, action tag - confusing

### ISSUE THREAD

**Issue by vduglued** [magento/devdocs#549]
On the layout instructions in the frontend guide, [the `<action>` example](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_act) seems not to correspond to the following text.

> In the previous example, the value of <arg1> is passed as the first argument and <arg2> values are passed...

The code block doesn't contain any `arg1` or `arg2`.

**Comment by almarchenko** [comment]
@vduglued Thank you for reaching us! I fixed it!
Please close the issue if it's ok.
