### ISSUE TITLE
Clarify/add indexer class locations

### ISSUE THREAD

**Issue by heider-hulft** [magento/devdocs#5502]
# General issue

## Description: 
You are showing classes (thanks) but where "exactly" are these files located?!

## Possible solutions: 
Please provide the full path to each file you are referring to (di.xml for example exists everywhere, and the CatalogInventory directories that I found using the linux "find" tool only reports ones that has no "etc" directories, therefore, the article isn't working. 

Additional information: 
Thank you !

**Comment by keharper** [comment]
@heider-hulft Does this section provide the info you're looking for?

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/indexing.html#m2devgde-indexing-outofbox

**Comment by keharper** [comment]
Closing this PR due to the lack of response.

**Comment by HeiderSati** [comment]
Hi Shrielenee

Apologies for taking time to get back to you, I was off on a holiday.

I looked at the page you sent, unfortunately, it does not resolve the problem. I believe my initial query was about the files on the original page I was referring to, mainly asking "which di.xml file was the page referring to?" the page you sent has nothing to do with this file.

I hope this makes sense.

Kind Regards
Heider
