### ISSUE TITLE
This Security scheme doesn't work AT ALL!

### ISSUE THREAD

**Issue by sholdowa** [magento/devdocs#553]
https://github.com/magento/devdocs/blob/2.0/guides/m1x/install/installer-privileges_after.html

In the example, potentially malicious code will be running through the web server, so will be the same user as the owner of the files in the docroot. If you own files, then you can override the current permissions to re-write them / add extra files, making this semblance of security worse than useless, as it engenders a completely false sense of security.

If you want to provide a decent level of security, then look at the ownership by the nobody user ( for example ), providing read / greater permissions where necessary, and the use of immutability using the chattr +i command. 

Better still, look at the use of the php_include search directive and move relevant files outside the docroot completely, leaving just those necessary to access the site, and leave them locked down tight.

**Comment by xcomSteveJohnson** [comment]
Created internal issue MSI-9 to investigate.

**Comment by gamort** [comment]
In practice, moving files outside the webroot is well established as the correct security scheme and at the same time not feasible.   PHP web applications need to be installable by uploading into a single directory - and the only reliable directory one can count on is the webroot.

Moreover, Magento provides the ability to dynamically adjust properties of static resources.  For example, you can change the product image size for all products via configuration settings.   To do this, requests for non-existant static files[images in the pub directory] will result be routed to an image processing script which generates the image on the fly.   As such, the PHP process executed by the web server to generate responses must be allowed to save files somewhere.

Nevertheless, there is much room for improvement.   Linux has supported more fine grained ACL permissions for over a decade.  These features were introduced in Linux 2.5 and are widely implemented in not only all modern linux distributions - but in almost every linux distribution one is likely to find today.  Even CentOS 6 - for example - while lagging abysmally behind modern improvements - uses a 2.6 kernel and enables ACL support by default.

Feedback would be welcome to issue 609.   I'll document it as I can.
See  https://github.com/magento/devdocs/issues/609

File permissions are boring, tedious, and never work for every installation.  My experience is that open source projects tend to limit themselves to promoting the most secure/restrictive set of permissions that might work - while at the same time development is done using 777 so none of the little hiccups are documented.

**Comment by xcomSteveJohnson** [comment]
We don't expect any updates to this topic. As the topic says these are suggestions, not requirements. Closing.
