### ISSUE TITLE
Dead link to Magento MVC Pattern

### ISSUE THREAD

**Issue by DmitryRublev** [magento/devdocs#554]
Page at devdocs/guides/v2.0/architecture/archi_perspectives/components/modules/mod_anatomy.md
points to 
[http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/components/Magento_MVC.html](http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/components/Magento_MVC.html) 
and 
[http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/Magento_MVC.html](http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/Magento_MVC.html) which both are 404 currently.

**Comment by jfrontain** [comment]
Thanks for noticing this issue, Dmitry — will fix soon. Thanks again.

**Comment by xcomSteveJohnson** [comment]
@DmitryRublev Please check now and close if it's fixed.

**Comment by DmitryRublev** [comment]
No dead links anymore, thank you!
