### ISSUE TITLE
error in documentation - migrate settings

### ISSUE THREAD

**Issue by dev4q1** [magento/devdocs#559]
Hi,

I am currently going through the documentation to migrate magento 1 to magento 2 and I am currently stuck on this part of the documentation devdocs/guides/v2.0/migration/migration-migrate-settings.md -> "Migrating settings" -> "2. Change to the following directory:" and "3. Enter the following command to create settings.xml from the provided sample:"

The instruction 3. says that I should copy the file "settings.xml.dist" but in the folder "`<your Magento 2 install dir>/vendor/magento/data-migration-tool/etc" there's only the "settings.xsd" file.

Is it the same file?

**Comment by dshevtsov** [comment]
@dev4q1 sorry, instruction was wrong. Now fixed, please check.

**Comment by dev4q1** [comment]
It seems there's still an error.

In my folder `.../magento2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.3`

I only have those files:
```
config.xml
config.xml.dist
map.xml.dist*
```

Is it meant to be the `settings.xml.dist` in `.../magento2/vendor/magento/data-migration-tool/etc/ce-to-ce`?

**Comment by xcomSteveJohnson** [comment]
@dev4q1 Looks like the correct path is `vendor/magento/data-migration-tool/etc/<edition-to-edition>`

Updated two topics:

*  [Data migration tool specification](http://devdocs.magento.com/guides/v2.0/migration/migration-tool-internal-spec.html)
*  [Migration settings](http://devdocs.magento.com/guides/v2.0/migration/migration-migrate-settings.html)

Please close this issue if it resolves your concerns.
