### ISSUE TITLE
Layout override doesn't seem to work

### ISSUE THREAD

**Issue by samleeiii** [magento/devdocs#560]
I'm trying to override the catalog_category_view.xml file in /vendor/magento/module-catalog/view/frontend/layout/ by putting it into app/design/frontend/<vendor>/<theme>/Magento-Catalog/layout/ but it doesn't seem to be aware of my override. The only way I can make the changes I need is to edit the original.

**Comment by almarchenko** [comment]
HI @samleeiii 

In our docs we state that to override a module layout, you need to put in a certain location in the theme, see
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/layout-override.html#fedg_layout_override_howto

In your case, plz put your custom catalog_category_view.xml  in the <your_theme_dir>/Magento_Catalog/layout/override/base/ directory.

Please let me know if it works.

**Comment by samleeiii** [comment]
Ok so I tried putting an override for module-newsletter/view/frontend/layout/default.xml into "my_theme_dir/Magento_Newsletter/layout/override/base/ but nothing happens. Is that location correct?

**Comment by mrkhoa99** [comment]
@samleeiii Seem your location of file isn't correct. It should be `my_theme_dir/Magento_Newsletter/layout/default.xml`

**Comment by samleeiii** [comment]
I actually tried that first but wasn't able to get any change either. I refreshed the cache. Is there anything else I need to do? 

Unrelated I seem able to override template and less files fine.

**Comment by samleeiii** [comment]
Ok so I figured it out, it's kind of weird. I had to put it into:

my_theme_dir/Magento_Newsletter/layout/override/theme/Magento/luma/

Even though the luma theme doesn't have a default.xml file for the newsletter. I probably should've mentioned that I declare luma as my parent in my theme.xml file, but anyway still very confusing.

**Comment by samleeiii** [comment]
Actually nevermind it didn't work that way either, I didn't realize I had modified it in the original module. So yeah still not sure how this is supposed to work.

**Comment by almarchenko** [comment]
@samleeiii  Can we close this issue?
