### ISSUE TITLE
Add instructions on how to install php 7

### ISSUE THREAD

**Issue by erickmarsh** [magento/devdocs#561]
There are instructions on how to install PHP 5.5 and 5.6 as part of the Prerequisits, but no instructions on how to install PHP 7. There may be some hesitation with regard to installing PHP 7 because Ubuntu users need to add a 3rd party repository, which apparently, can freak out some sys-admins.

**Pages in question to be updated:**
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-centos.html
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html

**Comment by xcomSteveJohnson** [comment]
Thanks, it's in the plan but I cannot provide an ETA at this time.

**Comment by xcomSteveJohnson** [comment]
I got some time today to do it:

[CentOS](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-centos.html)
[Ubuntu](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html)

Please close this issue if this is helpful.

**Comment by xcomSteveJohnson** [comment]
Closing
