### ISSUE TITLE
Need clarifications for creating an integration

### ISSUE THREAD

**Issue by sparrowek** [magento/devdocs#5611]
# General issue

## Description:
Missing example for "testIntegration must refer to your etc/integrations/config.xml file, and the integration name value must be the same."
There is no example of how this file should look like.
The path should also be etc/integration/config.xml ie. without the "s"
Probably this refers to the file mentioned below "Your module can optionally provide a configuration file config.xml". Is so this is incorrect the file is not optional but mandatory.

## Possible solutions:
Provide example of such a file.

Affected page: /guides/v2.3/get-started/create-integration.html

**Comment by sparrowek** [comment]
It seems that <email> is also required although when defining integration through admin it is not.

**Comment by keharper** [comment]
It would also be helpful to update the code samples. For example, the `composer.json` file lists versions of PHP that are no longer supported.
