### ISSUE TITLE
Incorrect link to JSCS site.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/devdocs#5632]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-javascript.html#eslint-and-jscs-tools

## Description

Link to JSCS site is incorrect. Looks like this project no longer has a separate site.
https://github.com/jscs-dev/node-jscs/blob/master/README.md

**Comment by brunoroeder** [comment]
I'm working on it.

**Comment by shrielenee** [comment]
Yo @brunoroeder --- We closed the applicable PR for this because it exceeded our two week timeframe for response.

If you, or someone else, wants to work this feel free to open a new PR or reopen the closed one.

🙅

**Comment by atwixfirster** [comment]
Let's try with this one - https://github.com/magento/devdocs/pull/6040

Thank you!
