### ISSUE TITLE
Devdocs Build throws warnings on new build

### ISSUE THREAD

**Issue by aepod** [magento/devdocs#5715]
# Bug report

## Description

During a build of the devdocs warnings are thrown as follows:
>[webuser@localhost magento-devdocs]$ bundle exec jekyll serve --incremental
>Configuration file: /home/webuser/magento-devdocs/_config.yml
>            Source: /home/webuser/magento-devdocs
>       Destination: /home/webuser/magento-devdocs/_site
> Incremental build: enabled
>      Generating...
>    Liquid Warning: Liquid syntax error (line 123): [:dot, "."] is not a valid expression in "{{ .bs-callout-warning }}" in guides/v2.2/cloud/env/variables-deploy.md
>    Liquid Warning: Liquid syntax error (line 123): [:dot, "."] is not a valid expression in "{{ .bs-callout-warning }}" in guides/v2.3/cloud/env/variables-deploy.md
>                    done in 252.115 seconds.
> Auto-regeneration: enabled for '/home/webuser/magento-devdocs'
>    Server address: http://127.0.0.1:4000/
>  Server running... press ctrl-c to stop.`

### Steps to reproduce
1. checkout source clean 
2. run a devdocs build 
`bundle exec jekyll serve --incremental`

Note this is on a freshly checked out and not modified version of the devdocs.

## Expected result
There should be no warnings.

## Additional information
This is just a warning, and oddly the syntax looks right in the stanza it is complaining about. There are several other chunks that look just like this and do not throw the warning. This also does not happen on subsequent builds.

**Comment by jeff-matthews** [comment]
Thanks for reporting @aepod.

You've discovered a syntax error in the note class.

Line 132 in https://github.com/magento/devdocs/blob/master/guides/v2.2/cloud/env/variables-deploy.md should be `{:.bs-callout-warning}`; NOT `{{ .bs-callout-warning }}`.
