### ISSUE TITLE
Layout Customization Example Not Working

### ISSUE THREAD

**Issue by tcmax76** [magento/devdocs#574]
I'm trying to follow the example layout customization for moving customer account links in my theme (located here: devdocs/guides/v2.0/frontend-dev-guide/layouts/layout-practice.md), and it doesn't appear to be working fully. Additionally, the code shown in the customer.phtml is outdated.

Here's the code that's in my app/code/Magento/Customer/view/frontend/templates/account/customer.phtml file:

`<?php if($block->customerLoggedIn()): ?>
    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <span data-bind="text: customer().fullname"></span>
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="customer-menu-toggle">
                <span><?php /* @escapeNotVerified */ echo __('Change')?></span>
            </button>
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <?php if($block->getChildHtml()):?>
        <div class="customer-menu" data-target="dropdown">
            <?php echo $block->getChildHtml();?>
        </div>
        <?php endif; ?>
    </li>
<?php endif; ?>`

When I follow the layout customization example, everything gets moved to the correct spot on the page, but the javascript that generates the customer name (text: customer().fullname) doesn't appear to be working when I'm logged into the site. So, there's just a blank space there (though I know where it is, so when I click that blank space, the drop-down does work).

I also tried using the following piece of code from the customer.phtml file in DevDocs example to try and get the customer name to display, but to no avail:

`<?php echo $this->getCustomerName(); ?>`

This could very easily be something I'm doing wrong, but I would love it if someone could check the code to make sure it's not something that should be updated in the example.

**Comment by almarchenko** [comment]
@tcmax76 thanks for the detailed description!
We'll check the code samples and respond!

**Comment by tcmax76** [comment]
Thanks @almarchenko!

**Comment by tcmax76** [comment]
I just realized the reason I can't get the customer name to appear on the front-end is likely because there appears to be an issue with the Customer Grid index on our site. So, probably not an issue with any of the code on this example, but the code still does stand to be updated since it doesn't match up with the present version of Magento.

Regardless, thank you for your assistance.

**Comment by almarchenko** [comment]
Hi @tcmax76 
Thank you for bringing this to our attention! we've updated the topic;
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/layout-practice.html
Please let me know if we can close the issue.

**Comment by tcmax76** [comment]
Looks good to me, @almarchenko! Thanks for the update!

(Unfortunately, I still can't get it to work...but I think that has more to do with something not working properly on our installation).
