### ISSUE TITLE
Detect Malware with New Discovery Rules

### ISSUE THREAD

**Issue by scholtz** [magento/devdocs#5818]
# Topic clarification/correction request

## Topic Link

https://magento.com/security/best-practices/detect-malware-new-discovery-rules

## Description

On **pure magento 2.3.3 installation** i have received this error:
Your site is compromised with injected JavaScript malware. (18)
Malicious code signature(s) have been found in these resources:
https://m2-demo-sk.aveo-trade.cz/static/version1570604447/_cache/merged/fb9f3333129aa8bba4b0c60e01089d2c.min.js	

This is my pure magento installation script: https://m2-demo-sk.aveo-trade.cz/install.sh

Therefore i tried to do what was written at "How to Detect Malware" 
https://magento.com/security/best-practices/detect-malware-new-discovery-rules

I got to step installing malware scanner:
git clone https://github.com/gwillem/magento-malware-scanner.git

little wierd to rely on third party git, but whatever..

the next step was to run python tools/runtests.py

however there is no runtests.py file in the git so no in my dir..

also i have noticed the message "The opensource malware scanner is no longer maintained as of 2018."

## Possible solutions

Something that tells me what might be wrong with security on pure magento installation.

Perhaps someone should give more info in the security scanner not to expect people use commercial software on detecting false positive security issues.

**Comment by hguthrie** [comment]
@scholtz  DevDocs does not maintain the topic you are referencing; however, we will look into the scenario to determine if there is a need to update DevDocs.

**Comment by scholtz** [comment]
@hguthrie Is there any other better place to submit this type of error?

**Comment by jeff-matthews** [comment]
We can notify the maintainers of the [Magento Security Center](https://magento.com/security) blog.

Cc: @piotrekkaminski.

We have plans to add a Security section to devdocs by the end of this year to accommodate CCPA data privacy legislation. Perhaps we could consider adding some of the requested info at that time.

**Comment by jfrontain** [comment]
hi @scholtz, I've followed up with our new Security PM, and here are her suggestions: 
* Please sign up for the Magento Security Scan tool at https://magento.com/security. If you still see that error, you can then open a support ticket on that tool. That'll be the most efficient way to bring attention to your issue.  (When you open the ticket, please include your store URL in the issue description.)
* I've alerted the security team, who own the blog that published the best practices topic, to remove the malware discovery rule section.  They will remove it as soon as they can. 
*  And finally, please feel free to keep me in the loop. I am going to open a PRODSECBUG ticket internally to make sure this stays on our radar. 
Thanks again. Closing this issue now.
