### ISSUE TITLE
Can we translate only storefront in Magento 2?

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/devdocs#583]
Hi,

This is not a bug report, Please see this url   [http://magento.stackexchange.com/questions/108252/how-to-translate-only-the-storefront-in-magento-2](url)

Is it possible with Magento 2 to implement this? though there is a dev doc link for the theme translation [http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/translate_practice.html](url)

If it is possible could you update the documentation on [http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.html](url)

**Comment by almarchenko** [comment]
Hi @tiwarimukesh 

The current implementation of the i18n tool there is no option to generate a dictionary for the storefront strings only.
Is it ok with you if I close the issue?

Thank you.

**Comment by tiwarimukesh** [comment]
Hi @almarchenko 
Should I create a feature request for this on Magento 2?
You can close the issue.
