### ISSUE TITLE
Magento doesn't create queues at RabbitMQ automatically

### ISSUE THREAD

**Issue by gorillagroup** [magento/devdocs#584]
When we enable Magento/ScalableInventory module and configure it properly at admin Magento shoul publish new message to inventory_qty_counter_queue

```
namespace Magento\ScalableInventory\Model\ResourceModel;

class QtyCounter implements QtyCounterInterface
{

    /**
     * {@inheritdoc}
     */
    public function correctItemsQty(array $items, $websiteId, $operator)
    {
        $items = $this->itemsBuilder->build($items, $websiteId, $operator);
        $this->publisher->publish('inventory.counter.updated', $items);
    }
```

But the no new queues found at RabbitMQ server and during start consumer run there are also message:
NOT_FOUND - no queue 'inventory_qty_counter_queue' in vhost '/'

**Comment by hshar7** [comment]
Hi @gorillagroup thank you for reporting this. Which branch is this happening in? We addressed many, many issues relating to Magento Message Queue Framework in past few months. On develop branch when I install Magento I can see the scalable inventory queue as you may see:
![screen shot 2016-03-31 at 6 22 51 pm](https://cloud.githubusercontent.com/assets/17727543/14193817/c8be3b46-f76d-11e5-91b1-c03f8d1bcb59.png)

**Comment by gorillagroup** [comment]
Hi

We tested this for release 2.0.2. And installed RabbitMQ server after Magento installation that may be the issue so after manual running installation for Amqp module queues and binding appeared on RabbitMQ server. But we expected that during message publishing queue will be created automatically.

Also we don't see amqp connection at RabbitMQ side. Do we need to do any additional configuration manually  to get this?

**Comment by hshar7** [comment]
We did refactor this logic, @gorillagroup, but it has not made it to 2.0.2
You will have to use latest develop branch or wait for 2.1 release coming soon.

**Comment by xcomSteveJohnson** [comment]
Can we close this?
