### ISSUE TITLE
Feedback on page: /guides/v2.3/howdoi/checkout/checkout_order.html

### ISSUE THREAD

**Issue by magedevel** [magento/devdocs#5859]
# General issue
The example do not show how to show the validation message
## Description:
The example do not show hot to show the validation message if the validation fails. 

## Possible solutions:
I suggest to add a code snippet that show how to show the validation message on top of checkout page. As an example:
````
define(
    ['mage/translate', 'Magento_Ui/js/model/messageList'],
    function ( $t, messageList) {
        'use strict';
        return {
            validate: function () {
                messageList.addErrorMessage({ message: $t('a possibile failure message ...  ') });
                return false;
            }
        }
    }
);
````

**Comment by alvsgabriel** [comment]
I'm working on it
