### ISSUE TITLE
Need chance link reference on page: /guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.html

### ISSUE THREAD

**Issue by fabriciosobral** [magento/devdocs#5887]
# Bug report

## Description
When we are reading the "listens property" Observe the following excerpt:
"For an example of listens usage in Magento code see line 92." The link is incorrect because the line has changed, now the line is 84

### Steps to reproduce
**Step 1** 
Access the link:
[https://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.html#listens-property](https://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.html#listens-property)
**Step 2**
Read the following excerpt on listens property: 
On the part XLM example after the code example the link " new_category_form.xml, line 92", observe that this line into the code needs change to line 84.

## Expected result

The text needs to be changed to line 84

**Comment by fabriciosobral** [comment]
I'm working on this

**Comment by dobooth** [comment]
Closing as merged.
