### ISSUE TITLE
Add use cases and examples to Searching with repositories topic

### ISSUE THREAD

**Issue by lfolco** [magento/devdocs#5916]
# General issue

## Description:

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/searching-with-repositories.html

Can you add more information on JoinProcessors? There is very little to go on about how to use them, when they should be used, etc. The examples are pretty light, and there is no explanation on what is going on in the examples.

**Comment by shrielenee** [comment]
Add information about use cases, how to use them, when they should be used, and more.

**Comment by DenisSaltanahmedov** [comment]
Hi, I am working on this issue.
@jeff-matthews could you please assign the issue to me? Thx.

**Comment by jeff-matthews** [comment]
It's all yours @DenisSaltanahmedov! Thanks for helping out.

**Comment by DenisSaltanahmedov** [comment]
Hi, @shrielenee the PR https://github.com/magento/devdocs/pull/6543 merged, could you please close the issue. Thx.

**Comment by jeff-matthews** [comment]
Thanks @DenisSaltanahmedov!
