### ISSUE TITLE
GraphQL product query missing filter attribute "url_key"

### ISSUE THREAD

**Issue by oneserv-heuser** [magento/devdocs#5919]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/graphql/queries/products.html#ProductFilterInput

## Description

On the GraphQL products query page in the section "filter attribute" there is a list with all attributes which can be used to create filters. This list is incomplete as there are attributes missing, for example "url_key".
I don't know if they're any other attributes missing but "url_key" is.
It's possible to use this attribute as filter attribute.

## Possible solutions

Add the entry "url_key" to the list of attributes which can be used to create filters.

Edit: Could it be that every attribute of the [ProductInterface](https://devdocs.magento.com/guides/v2.3/graphql/product/product-interface.html) is filterable except "id"?

**Comment by keharper** [comment]
Good catch @oneserv-heuser. Most filters are defined here

https://github.com/magento/magento2/blob/d5104d52fc5e07f88be373ae2bc6a61d4d98c939/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L308

However, a few filter attributes are defined in other modules, and `url_key` is one of them.
