### ISSUE TITLE
Add clarification to required files in About component file structure page

### ISSUE THREAD

**Issue by multipasko** [magento/devdocs#5924]
# General issue

## Description:

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/prepare/prepare_file-str.html

you say:

"All components require these three files:"
- etc/module.xml

This is not true. Only modules have this etc/module.xml file. Themes or language packages do not have this. I also believe that composer.json is not required but recommended to use.

**Comment by shrielenee** [comment]
Add more details to individual line items in Required files section. 

Or "Components may require these three files:"

**Comment by atwixfirster** [comment]
> Add more details to individual line items in Required files section.
> 
> Or "Components may require these three files:"

@shrielenee 

A problem is more deeper than a simple description change  :)

More details here: https://github.com/magento/devdocs/pull/6184

Thank you!
