### ISSUE TITLE
Install Guide: PHP settings topic has formatting issues

### ISSUE THREAD

**Issue by hguthrie** [magento/devdocs#5926]
The [Required PHP settings](https://devdocs.magento.com/guides/v2.2/install-gde/prereq/php-settings.html) topic of the Install guide has some formatting issues in the **Supported PHP versions** list. It looks like both versions of the topic use an include file: `install/php-versions-template.md`

Review this formatting problem and make corrections so that the list displays appropriately.

It is possible that it is caused by the include file, so may need to review all topics that use the `install/php-versions-template.md` file.

**Comment by shrielenee** [comment]
I also would like to see the expandable/collapsible sections removed so that everything is visible.

**Comment by rodrigowebjump** [comment]
I am working on this.

**Comment by atwixfirster** [comment]
Last update here was 27 days ago.

So, I've fixed this issue in https://github.com/magento/devdocs/pull/6181 due to @rodrigowebjump inactivity.

Thanks
