### ISSUE TITLE
Update env.php ref page with config options + descriptions

### ISSUE THREAD

**Issue by GreenGinkgo** [magento/devdocs#5927]
# General issue

The env.php reference page is lacking most configuration options or detailed descriptions

## Description:

The current reference page includes 11 top-level configuration sections, but little-to-no detailed information that is easily accessible. Additionally, there are dozens of env.php sub-sections which are not mentioned at all in this page, and indeed may not be detailed anywhere in any documentation. An example would be db -> indexer -> persistent.

## Possible solutions:

Provide a well organized, easy to read, and understandable reference which includes all configuration options, what version they were introduced, and links to pages on how those various options can be used effectively.

**Comment by ajithkumar-maragathavel** [comment]
@magento Pull request for this has been raised.
https://github.com/magento/devdocs/pull/6167
