### ISSUE TITLE
oAuth Docs -- no mention of where `oauth_verifier` Comes From

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#594]
Regarding [the oAuth documentation at](http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html#http-post), the docs mention using an `oauth_verifier` token when requesting an access token.

> oauth_verifier. The verification code that is tied to the consumer and request token.

However, the page makes no mention of where this `oauth_verifier` token comes from.  I would presume it's something returned when the user makes a request for the **request** token, but the docs don't reflect that, and my assumption may be wrong. 

The points to something being incorrect in the docs, but I have no docs to tell me what that incorrectness is :)

**Comment by tanberry** [comment]
Yep, we need to make that clear, from where the 'oauth_verifier' comes.  I promise that we don't try to make our docs existential ("no docs to tell me what that incorrectness is"). ;-)

**Comment by keharper** [comment]
@astorm , I've updated the following documents.

http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html
http://devdocs.magento.com/guides/v2.0/howdoi/webapi/integration.html#integrate

Let me know whether I've fully addressed the issues.

**Comment by keharper** [comment]
Closing the issue.
