### ISSUE TITLE
Add options for secure DB connection during installation

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#5951]
## Description:

PR https://github.com/magento/magento2/pull/25398 introduced the following new `bin/magento setup:install` options in Magento 2.3.4:

- `--db-ssl-key=<MYSQL_CLIENT_KEY>`
- `--db-ssl-cert=<MYSQL_CLIENT_CERT>`
- `--db-ssl-ca=<MYSQL_SERVER_CERT>`

These options have not been documented in devdocs.

## Possible solutions:

Add the options and descriptions to the **Site, database, and RabbitMQ configuration options** table in [this section](https://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-install.html#instgde-install-cli-magento).

## Additional information:

These options will be included in the [Magento CLI Tools Reference](https://devdocs.magento.com/guides/v2.2/reference/cli/magento.html) topic when we update the data files in the devdocs project immediately following the 2.3.4 release. No further action necessary.

**Comment by keharper** [comment]
Additional notes.

The  link to the "Install the Magento software" topic goes to the 2.2 version, but as far as I can tell, the new flags were added for 2.3 only. The contributor who works on this will need  to 

1. Break the symlink from the 2.3 version to the 2.2 version.
2. Copy the 2.2 version to the 2.3 directory.
3. Edit the copied 2.3 version.
