### ISSUE TITLE
Clarify Enable profiling (MAGE_PROFILER) topic

### ISSUE THREAD

**Issue by swaibar** [magento/devdocs#5954]
# General issue

## Description:

After reading this page and trying to get the profiler running I was quite frustrated.

## Possible solutions:

The solution to my problem after a while of googling was to set the correct deploy mode:

`php bin/magento deploy:mode:set developer`

obvious really, but would have been nice to see on the page.

**Comment by konarshankar07** [comment]
Hello @swaibar ,
As I have checked in the various magento version, I can't find this issue cause Profiler is running in all the modes. Can you please add more information?
Thanks

**Comment by atwixfirster** [comment]
@shrielenee , regarding to @rogyar [comment](https://github.com/magento/devdocs/pull/6012#discussion_r347417960) we can close this issue because profiler is not depend on deployment mode and works in all modes.

Thank you!

**Comment by shrielenee** [comment]
Per @rogyar explanation and @atwixfirster this is no longer an issue. Will close.
