### ISSUE TITLE
Less syntax not applied

### ISSUE THREAD

**Issue by rafaelstz** [magento/devdocs#5967]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/js-resources.html#including-third-party-javascript-libraries

## Description

There is no style applied to Less syntax.

<img width="1272" alt="Screen Shot 2019-11-11 at 12 32 03 PM" src="https://user-images.githubusercontent.com/610598/68600364-266a1480-0481-11ea-9205-9553ddabeac6.png">

## Possible solutions

Check why the compiler is not adding the additional classes to customize it or why it has not been accepted or remove the less syntax.

## Additional information

I thought that this snippet wouldn't be following using the code snippet syntax correctly but it's, we can see it with style through the Github's MD preview.

https://github.com/magento/devdocs/master/guides/v2.2/javascript-dev-guide/javascript/js-resources.md

<img width="884" alt="Screen Shot 2019-11-11 at 12 41 12 PM" src="https://user-images.githubusercontent.com/610598/68600482-5ca79400-0481-11ea-8c5d-fc94676be914.png">

**Comment by shrielenee** [comment]
`less` is not the correct syntax, use `scss` instead.

**Comment by konarshankar07** [comment]
Hello @shrielenee ,
I like to work on this ticket. But I'm not sure about the above comment so you want to change the import `less` file to `scss` file? Correct me if I'm wrong
Thanks

**Comment by shrielenee** [comment]
The syntax of `less` does not render code blocks correctly. To add the syntax to the code block use `scss` instead/

**Comment by rafaelstz** [comment]
Hi @shrielenee and @konarshankar07,

As it was an easy fix I already created the PR: https://github.com/magento/devdocs/pull/6018

Thanks
