### ISSUE TITLE
Use standard generated factory in example on Factories topic

### ISSUE THREAD

**Issue by lfolco** [magento/devdocs#6011]
# General issue
Example for passing parameters to the `ItemFactory` can cause confusion due to using a non-standard factory definition in the example. https://devdocs.magento.com/guides/v2.3/extension-dev-guide/factories.html

## Description:
The example for passing parameters to a factory points to factory that does not follow the same pattern as generated factories.

```
$resultItem = $this->itemFactory->create([
  'title' => $item->getQueryText(),
  'num_results' => $item->getNumResults(),
]);
```

The class `Magento\Search\Model\Autocomplete\ItemFactory` has this `create()` method signature:

```
public function create(array $data)
{
        return $this->objectManager->create(\Magento\Search\Model\Autocomplete\Item::class, ['data' => $data]);
}
```

Whereas a standard generated factory's `create` method signature is as follows:

```
public function create(array $data = [])
{
    return $this->_objectManager->create($this->_instanceName, $data);
}
```
## Possible solutions:

Use a standard generated factory in the example (or a non-generated that follow the same method signature as other generated factories), such as `\Magento\Framework\FlagFactory`; then change the example to this:

```
$flag = $this->flagFactory->create(
    [
        'data' =>  ['flag_code' => 'something']
    ]
);
```

Would also be useful to point out that the `Flag` class has a `$data` constructor parameter which corresponds to the `data` key in the create array above.

## Additional information:

I would submit a PR but it looks like this topic is symlinked to older dev docs and I'm not sure how to go about working on it.

**Comment by keharper** [comment]
@lfolco you can edit the `guides/v2.2` version of the file unless the Magento code has changed for 2.3. If the code has changed, break the symlink by deleting the 2.3 version with `git rm <file>` and copy the 2.2 version over to the 2.3 directory. Then edit the 2.3 version.

If you'd like to work on this issue, let us know, and someone will assign it to you.

**Comment by lfolco** [comment]
Okay that works, you can assign it to me.

**Comment by shrielenee** [comment]
@lfolco A little late to the party but we can definitely get you started on this. Assigning... let us know if you want us to UNassign you. 😄

**Comment by dineshvb** [comment]
@magento I am working on this
