### ISSUE TITLE
Server-side Less compilation for production?

### ISSUE THREAD

**Issue by MidnightDesign** [magento/devdocs#603]
[_Simple style changes with client-side LESS compilation vs. server-side_](https://github.com/magento/devdocs/blob/2.0/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_mode.md#-whats-in-this-topic-) contains the following:

> server-side compilation mode (the default one, recommended for production)

This should be changed, right? Neither server-side nor cient-side is meant for production mode.

**Comment by almarchenko** [comment]
@MidnightDesign you are right, it is not the absolutely correct statement, so we removed it.
Thank you!
Can I close the issue?

**Comment by MidnightDesign** [comment]
Yes, thanks!
