### ISSUE TITLE
Grunt 1.0.0 release breaks some peer dependencies

### ISSUE THREAD

**Issue by ntoombs19** [magento/devdocs#604]
Grunt 1.0.0 was recently released http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released

http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html

This page says to run `npm install grunt --save-dev` to install grunt but when you subsequently run `npm install` you will get several peerinvalid errors for peer dependencies that expect grunt versions closer to 0.4.5 (the latest after 1.0.1)

This page should be updated to say to run `npm install grunt@0.4.5 --save-dev`.

**Comment by tanberry** [comment]
@ntoombs19  thanks for this info! Do you think most people have tools that expect grunt versions that are more recent than .0.4.5 (which was released early May)?

Is the version usually specified in the command like that, with the version number following the word grunt?

Would it make sense in the docs to use variables, and say the command is:
'npm install grunt@x.x.x --save-dev'
where x.x.x is the installed version of grunt.

That way, we don't have to always update the numbers.

Adding @almarchenko  who is our Frontend Dev Guide writer.

**Comment by almarchenko** [comment]
Hi @ntoombs19! Thank you for your input! 
We've discussed the topic, and went through the doc with one of our developers, and as a result modified the procedure description:
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html#grunt_prereq

The `npm install grunt --save-dev` step was excessive, cause Grunt will be installed locally along with other dependencies when the following is run (next step)
```
cd <your_Magento_instance_directory>
npm install
npm update
```
The version of Grunt that will be installed is specified in the `package.json` file located in the root directory.

**Comment by almarchenko** [comment]
Plz let me know if we can close the issue or are there more questions.

**Comment by ntoombs19** [comment]
I like this solution. Thanks for taking a look at it.
