### ISSUE TITLE
More information about staging functionality

### ISSUE THREAD

**Issue by ascottfuji** [magento/devdocs#6044]
# General issue
Not enough information

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/staging.html

## Description:

This topic provide very high-level information about Staging functionality.   However it does provide any information on whether the listed modules are; and if so how.  Nor does this topic provide a link to corresponding documentation in the User Guide.  As a developer you have to understand how your users are expected or might use the components before you start trying to design or develop a solution using the components.

**Comment by alexkwellbe** [comment]
@magento I am working on it

**Comment by alexkwellbe** [comment]
@m2-community-project I am working on it

**Comment by BarnyShergold** [comment]
@shrielenee @ascottfuji 
The first request "However it does provide any information on whether the listed modules are; and if so how" doesn't make sense as "it does" implies the information is there and "whether the listed modules are", whether they are what?

@ascottfuji - we'd need clarity on what you are asking for there and please expand more on what you are after - there are details on how the modules function in the Readme for each module which is replicated on the guide.

For the second requires, we could add a link to the Staging Guide - https://docs.magento.com/user-guide/cms/content-staging.html at the top of the page to guide the developer for functionality,

I do not feel it is the guide to give the developer an indepth explanation of how each module works. If we did that, we'd have to do it for every module in the codebase.
