### ISSUE TITLE
Feedback on ece-tools package topic

### ISSUE THREAD

**Issue by meker12** [magento/devdocs#6067]
# General issue

I can’t find anywhere in devdocs that it says to do a DB query against a slave database in cloud you should hit port 3304 instead of 3306. 

What is not well documented is that the load balancer provides different ports for accessing MySQL for different purposes. The default port of 3304 gets spread across all 3 nodes of the cluster. while 3306 gets sent to just the non-master MySQL nodes. I’m further speculating that there’s also a port which gets you only the MySQL master.

https://devdocs.magento.com/cloud/reference/ece-tools-reference.html

## Description:

Provide information that describes the database ports for Cloud Staging and Production environments, and when you would use each one.

**Comment by hguthrie** [comment]
This is not a problem with ece-tools package topic, per se, since that is a brief introduction on how to use ece-tools. This topic request seems to be about understanding the load balancer with the remote database cluster. I recommend this is an opportunity for a new topic, or new section to enhance the [MySQL service](https://devdocs.magento.com/cloud/project/project-conf-files_services-mysql.html#connect-to-the-database) topic.

**Comment by BarnyShergold** [comment]
@hguthrie @meker12 - I think a small mention on the MSQL Service page is in order but perhaps there should be an additional section under "Manage Your Project" called "Remote Database Access" - eg showing how to make a connection using a mySQL tool like SequelPro to access databases - both master & slave?

@meker12 - Under what circumstances were you expecting to need to know the difference between 3306 & 3304? Ie when you need to know if you are accessing Master or Slave?

**Comment by hguthrie** [comment]
The Manage your project topic does reference where to access the remote load balancer URLs, but a more intentional section or topic "showing how" is always well received.

> @hguthrie @meker12 - I think a small mention on the MSQL Service page is in order but perhaps there should be an additional section under "Manage Your Project" called "Remote Database Access" - eg showing how to make a connection using a mySQL tool like SequelPro to access databases - both master & slave?

**Comment by BarnyShergold** [comment]
If we added a small section at the end of this : https://devdocs.magento.com/cloud/project/services-mysql.html#connect-to-the-database to describe how to remote access the databases (and choose a port) AND update the existing section to details different databases access and the ports?

 Is it necessary to say why someone would use a slave-db? The main reason I might use the slave (when needing direct access) would be to do a mysqldump as slave is read only. (Performance and avoids table locks on master) Or is that a useful bit of info?

**Comment by hguthrie** [comment]
> If we added a small section at the end of this : https://devdocs.magento.com/cloud/project/services-mysql.html#connect-to-the-database to describe how to remote access the databases (and choose a port) AND update the existing section to details different databases access and the ports?
> 
> Is it necessary to say why someone would use a slave-db? The main reason I might use the slave (when needing direct access) would be to do a mysqldump as slave is read only. (Performance and avoids table locks on master) Or is that a useful bit of info?

I think it is very useful to provide an example use case, depending on whether it is a common task. (Weird, edge-cases are not helpful and can be confusing to new users.) I ask questions like—Is it a normal or preferred action to access the remote database? What problem can it solve for me or to what purpose does it serve? What do I need to be careful about when I do? Okay, show me the happy pathway.

**Comment by hguthrie** [comment]
Or, you can point to the [KB article for best practice](https://support.magento.com/hc/en-us/articles/360049045351).

**Comment by BarnyShergold** [comment]
@hguthrie - I'm still considering how to do this - it's not forgotten
