### ISSUE TITLE
File permission rewrite

### ISSUE THREAD

**Issue by gamort** [magento/devdocs#609]
For PR 607 I limited the changes to a minimal set of changes needed to run under common multi-host PHP FPM configurations:  https://github.com/magento/devdocs/pull/607

This set of changes is incomplete by being based on integrating into the existing documentation.

File permissions really should be expanded quite a bit to accommodate different environments.  The preferred file permissions are 400 [user: read only, group and world no access] and the preferred directory permissions are 500[user: read & search/list.  Group and world no access].  This should be combined with using setgid on all directories.

Beyond those file permissions, it is preferable to use an acl and establish fine grained, user specific permission.  

I simply cannot work out how to add an entire section of documentation AND make sure it links back to the original locations.  Time permitting I'll review it next month.

**Comment by xcomSteveJohnson** [comment]
Why should Magento provide such detailed advice about multiple hosts, for example? Doesn't it depend on what the user or integrator wants?

**Comment by sholdowa** [comment]
There's not much point using the setgid bit* on a directory with 500 permissions is there! And what's wrong with 100?

I disagree with your fundamental point that everything should be placed in the docroot...
As an alternative suggestion, why not have public and private there. Website users log in to a site that is under public, whereas admins ( that's primarily sysadmins updating code or installing new stuff, but the same can be said for site admins ) use either the parent or another docroot. This one can be far more heavily protected ( limit by IP, password protected, and so on ) without affecting its day-to-day running.

That way, the risk of the public site being hacked can be reduced way down by locking all of the static code under /public, and banning running anything out of the necessarily writeable areas ( if there are any - I need to think long and hard about file/media uploads - cache and sessions are no-brainers ).

As you're providing web server config scripts, just adding an extra cname for admin.example.com won't be that much extra effort on the installer's part.

Alternatively use a pair of ( again well protected ) lock/unlock scripts. The problem with this ( even old farts like me only learned this a couple of days ago! ) is that making files/folders immutable requires root privileges, so the risk attached with implementing that is rather high unless logging on to the server, where a sudo setup would limit the enhanced privileges.

*this implements the BSD convention that a file is created with the same group ownership as the directory it's created in. I suppose you could argue that this may automatically improve access, but as any newly created file will need to be writeable it's creator, any potential gains could well already have been negated.

**Comment by xcomSteveJohnson** [comment]
If you're requesting changes be made to Magento code, please open a request on the [Magento 2 GitHub](https://github.com/magento/magento2/issues).

**Comment by gamort** [comment]
"*this implements the BSD convention that a file is created with the same group ownership as the directory it's created in."

The PHP application runs as user: magento-fpm
You ssh to the system as user: magento-cli
Your web server runs as user: magento-apache
You have product imports being uploaded via ftp from user: 3rdparty-ftp

These users are all in the group: magento-users

setgid eliminates the issues that occur when files are created by one of those 'users' and the others cannot access them.  Not my preferred solution, but I focus on dealing with things as they are.  I don't have the luxury of refusing to fix an existing website until everything is configured "as it should be".

Note: all these files do not have to be in the webroot.  In fact, there is a large number of configuration options which allow you to specify alternate directories and move them outside the webroot.  And not a lot of documentation on how to do it..assuming that it actually works.   I simply see no reason to let the perfect be the enemy of the good.   I am interested in making things better ie good.   If you have time to make them perfect go for it.  And if you have any suggestions on how I can make things better while you are working on making them perfect feel free to let me know.

Thanks!

**Comment by sholdowa** [comment]
But you've already stated your preference for directories to be 500 perms, which ( denies updates and ) disables any access via group permissions. You can't have both!

**Comment by xcomSteveJohnson** [comment]
We're discussing this. I'll provide an update when I have one.

**Comment by xcomSteveJohnson** [comment]
As we stated in #607 Magento is changing the file system permissions scheme for Magento 2. We should announce this in the next month or so.

Closing this issue. You can open a new one if you'd like after our permissions scheme has been updated.
