### ISSUE TITLE
Misleading statements about theme's view.xml file

### ISSUE THREAD

**Issue by sanganinamrata** [magento/devdocs#6091]
# Topic clarification/correction request

- Misleading statements about theme's view.xml file

## Topic Link

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-inherit.html#override-viewxml-file

## Description

> If you add the <theme_dir>/etc/view.xml file in your theme, it overrides the parent’s file.

The above statement is incorrect with respect to the actual implementation of theme's view.xml file.

## Possible solutions

N/A

## Additional information

N/A

**Comment by dobooth** [comment]
Hi @sanganinamrata Thanks for creating this issue. Could you explain how it would be better explained? What part is misleading?

**Comment by shrielenee** [comment]
Hey @sanganinamrata --- Any more info on this so we can begin work? Thanks!

P.S. Loved your Hackathon t-shirt tweet 😄

**Comment by sanganinamrata** [comment]
@shrielenee Great to hear that you recognized me😄And TYSM for the complement 😊 
- I'll revert back to you about in couple of hours.

Thanks!

**Comment by sanganinamrata** [comment]
As mentioned here: https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-inherit.html#override-viewxml-file

`If your theme does not contain a view.xml configuration file, it will be inherited from the parent theme. If you add the <theme_dir>/etc/view.xml file in your theme, it overrides the parent’s file.`

This means that the child theme's view.xml file overrides the parent theme's view.xml files. But the Child theme's `view.xml` actually extends parent themes `view.xml`, does not overrides it.

**Comment by dobooth** [comment]
That's great feedback! Thanks for the clarification.
