### ISSUE TITLE
How do I link to external js like for installing a Typekit font from Adobe?

### ISSUE THREAD

**Issue by samleeiii** [magento/devdocs#610]
I need to put the following in the <head>:

`<script src="https://blahblahblah.js"></script><script>try{Typekit.load();}catch(e){}</script>`

I tried using defaults_head_blocks.xml to do so, but when I use a `<script>` tag, it assumes I'm trying to add a relative URL instead of an absolute URL which of course results in a 404.

**Comment by samleeiii** [comment]
I found that if I go to root.phtml in module-theme/view/base/templates then I can add that snippet and it works but that's probably not considered "best practices". :)

**Comment by almarchenko** [comment]
Hi @samleeiii ! 

Try adding the `src_type="url"` attribute in your `<script> `tag, as described here: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-manage.html#layout_markup_css
(see the paragraph right after the code sample)

**Comment by samleeiii** [comment]
Ahhh thanks!

**Comment by almarchenko** [comment]
Did it work?) Can we close the issue?
