### ISSUE TITLE
Feedback on Create and manage users topic

### ISSUE THREAD

**Issue by meker12** [magento/devdocs#6101]
# General issue

Possibly inaccurate information in https://devdocs.magento.com/cloud/project/user-admin.html

## Description:

This page indicates that a redployment is required in order for newly added users to access the environment. in my experience this is not the case. can we validate/update as necessary?

**Comment by shrielenee** [comment]
Hey @meker12 --- I feel like this needs a knowledgeable developer to verify whether redeploy is required in this case. Can you tag someone who may be a good fit? 😺

**Comment by atwixfirster** [comment]
Hi, @meker12!
[Rebuild the environment](https://devdocs.magento.com/cloud/project/user-admin.html#rebuild) is true when you create admin from the Magento Cloud Account. But if you create admin from the back-end side you do not need to run redeploy.

I can add this notice if you approve.

Thank you!

**Comment by meker12** [comment]
> Hi, @meker12!
> [Rebuild the environment](https://devdocs.magento.com/cloud/project/user-admin.html#rebuild) is true when you create admin from the Magento Cloud Account. But if you create admin from the back-end side you do not need to run redeploy.
> 
> I can add this notice if you approve.
> 
> Thank you!

@atwixfirster  That sounds great.  Thanks!

**Comment by meker12** [comment]
> > Hi, @meker12!
> > [Rebuild the environment](https://devdocs.magento.com/cloud/project/user-admin.html#rebuild) is true when you create admin from the Magento Cloud Account. But if you create admin from the back-end side you do not need to run redeploy.
> > I can add this notice if you approve.
> > Thank you!
> 
> @atwixfirster That sounds great. Thanks!

So the content on the page is correct.  If you add a user to a Cloud environment using the Project Web UI or the CLI, you have to redeploy.  If you add a user to the Magento Application through the Magento Admin UI, you do not have to redeploy the environment.

![image](https://user-images.githubusercontent.com/6391769/70751283-a6d89b00-1cf5-11ea-9fd0-96f9e5e4075f.png)

I think the note just needs to clarify that adding a user through the Magento Application is different than adding a user to the Cloud environment.

**Comment by atwixfirster** [comment]
@meker12 , could you please review a proposed option:

<img width="1193" alt="6101" src="https://user-images.githubusercontent.com/13585327/70837709-8d2a7700-1e0d-11ea-8b40-4a6d196a88e9.png">

PR: https://github.com/magento/devdocs/pull/6205

Thank you!
