### ISSUE TITLE
Feedback on page: /guides/v2.3/cloud/project/manage-disk-space.html

### ISSUE THREAD

**Issue by almarchenko** [magento/devdocs#6103]
# General issue
Need to add a note that Allocating disk space as described is not applicable for Cloud Pro Staging and Production. The latter should contact support and pay for increase.
## Description:

Need to add a note that Allocating disk space as described is not applicable for Cloud Pro Staging and Production. The latter should contact support and pay for increase.
More tech details can be provided by support and sales details by CSMs.

**Comment by jeff-matthews** [comment]
@meker12, does this issue duplicate #6100?

**Comment by meker12** [comment]
@jeff-matthews  Yes. It's a related issue.  Updated note instructs customers to submit Support ticket to change disk space allocation on Pro Staging and Production environments.
