### ISSUE TITLE
catalogProductAttributeOptionManagementV1 API nto working

### ISSUE THREAD

**Issue by plumslice** [magento/devdocs#611]
@alankent @keharper 
http://magento_host/soap/default?services=catalogProductAttributeOptionManagementV1
Above service is responsible for getting option items and as well as adding new one. This do not work either.

**Comment by keharper** [comment]
Your issue appears to be the same as this.

https://github.com/magento/magento2/issues/4630

Development is working on a fix, and it should be delivered in a patch soon. 

I'm going to close this issue. Feel free to reopen.
