### ISSUE TITLE
catalogProductAttributeManagement service stop after assigning new attribute

### ISSUE THREAD

**Issue by plumslice** [magento/devdocs#612]
@alankent @keharper 
http://magento_host/soap/default?services=catalogProductAttributeManagementV1
Above service is responsible for getting attributes by attributeSetId. The service works fine if there is no select type attribute is assigned to attribute set but once it is assigned (like color, size attribute) using UI or from service call this service stop working forever.

**Comment by keharper** [comment]
It appears this issue was addressed here:

https://github.com/magento/magento2/issues/4103
