### ISSUE TITLE
Feedback on page: /guides/v2.3/frontend-dev-guide/css-topics/css-critical-path.html

### ISSUE THREAD

**Issue by david-ziffity** [magento/devdocs#6125]
# General issue
External link icon not displaying 
## Description:
External link svg icon implemented as background which is not displaying in the browser chrome Version 75.0.3770.142 (Official Build) (64-bit)  in ubuntu

External link icon not displaying in chrome Version 75.0.3770.142 (Official Build) (64-bit) ubuntu

**Comment by dobooth** [comment]
Closing as a browser-specific issue. We don't have anything we can change to fix it.
