### ISSUE TITLE
Can we have section on the dev docs which displays deprecated code?

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/devdocs#614]
This is a advice if we can have the a note for every section if something is getting deprecated in new releases.

As there are so many tutorials on the web which are using deprecated ways of creating the admin grid.
Like http://magento.stackexchange.com/a/86886/3895

Reputed users of community are mentioning that this method is deprecated. Though the dev docs are being maintained well but it is difficult to find about deprecated code.

**Comment by tanberry** [comment]
HI @tiwarimukesh thanks for that suggestion. At this point, with the limited resources we have, it would be very difficult to create/maintain such a list.

We have recently starting publishing a generated list of backwards incompatible changes [here.](http://devdocs.magento.com/guides/v2.0/release-notes/changes_2.0.html)  It is not exactly what you are looking for but it might help.

For documentation about creating grids, please refer to our [UI Components guide](http://127.0.0.1:4000/guides/v2.0/ui-components/ui-component.html)and our other developer guides on devdocs.magento.com.

**Comment by tiwarimukesh** [comment]
Hi @tanberry
I think backward incompatible section on release notes is also good enough. URl for the _UI Components guide_ in your reply is unreachable.
I think you can close the ticket.

**Comment by tanberry** [comment]
Hi @tiwarimukesh , apologies that I mistyped the syntax for the UI Components Guide in my reply above! Here is the direct URL: http://devdocs.magento.com/guides/v2.0/ui-components/ui-component.html

OK, I'll close this ticket. Please stay in touch, and Thanks!

**Comment by xcomSteveJohnson** [comment]
Closing
