### ISSUE TITLE
Feedback Import Magento Commerce code into a Cloud project

### ISSUE THREAD

**Issue by meker12** [magento/devdocs#6160]
# General issue
This is a general request to review this page and clean up a little bit here and there to make it clearer what we’re talking about when we’re talking about it, and making sure we talk about them editing files either in their existing live magento directory or in a directory of files that are a clone of the github of their magento version or so.

https://devdocs.magento.com/cloud/setup/first-time-setup-import-import.html

Specifically, clarify this sentence: 

"If you haven't done so already, log in to your Magento Commerce Cloud server as the Magento file system owner."

I think it means go to the Magento installation directory of the code that you downloaded from git as the Magento file system owner.

**Additional clarification and cleanup**

The [Prepare your existing Magento Commerce system](https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html) isn't referenced as a prerequisite for the [Import Magento Commerce code](https://devdocs.magento.com/cloud/setup/first-time-setup-import-import.html) topic.  Also the Prepare topic has some formatting issues and a missing image in the  [Prepare and add required files](https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html#required-files) topic.

Update examples to use a more recent Magento Commerce version -- 2.3.3, for example

**Comment by awktion** [comment]
There are 3 main venues covered in this page, the local development environment (what's downloaded from git for example), the existing production environment (generally referred to as Magento Commerce system), and any of the cloud environments (referred to as Magento Commerce Cloud server). 

In the cloud itself when logged into the cloud the main Magento folder is not writable, so .magento.app.yaml, .magento.env.yaml, files in .magento/ and files in that main Magento folder such as composer.lock and so forth are not able to be modified as they are in a write-only area.

I guess the overall suggestion with reference to the git files may just be to copy individual files mentioned in the guide on the page into the production Magento Commerce system such as magento-vars.php and perhaps even the composer.json that it's talking about in the initial sentence I objected to and suggested a replacement for.

**Comment by andrewbess** [comment]
Hello @meker12 
Sorry, Margaret, but are you sure that provided in description link is correct?
I think, correct link is https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html

**Comment by meker12** [comment]
@andrewbess So this issue looks like it requires clarification and cleanup for two topics:

https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html
https://devdocs.magento.com/cloud/setup/first-time-setup-import-import.html

I updated the description to indicate the additional changes.

If you would like to take this issue, I am happy to collaborate with you on the updates.

**Comment by andrewbess** [comment]
Thank you @meker12 
I am working on this issue now

**Comment by andrewbess** [comment]
I cannot assign this issue myself.
This is strange, because I have a possibility to do it on magento/magento2 repo.

**Comment by keharper** [comment]
It's yours @andrewbess

**Comment by andrewbess** [comment]
Yes, thanks.
You wrote: "...The Prepare your existing Magento Commerce system isn't referenced as a prerequisite for the Import Magento Commerce code topic..."
I think this is different topics

**Comment by meker12** [comment]
@andrewbess So this topic:  Prepare your existing Magento Commerce system  provides the steps to complete before you "Import Magento Commerce code"

The problem is that if you open the "Import Magento Commerce code" topic directly, that topic is based on having completed the preparation steps for import.   However, the "Import Magento Commerce" code topic doesn't mention that you need to complete the preparation first.

**Comment by andrewbess** [comment]
Perhaps, it should be above [this block](https://monosnap.com/file/ThwdYSW55zNgjjelDthBAHGeJPo2MZ) and should look like 
If you have the already installed Magento Commerce you can use [Prepare your existing Magento Commerce install instruction](https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html).

What do you think about this? @meker12

**Comment by andrewbess** [comment]
@meker12 Something like this
<img width="1172" alt="Import Magento Commerce code into a Cloud project  Magento 2 Developer Documentation 2019-12-19 01-51-11" src="https://user-images.githubusercontent.com/10788564/71133113-41f3d800-2202-11ea-94a1-6bfe60206dc0.png">

**Comment by meker12** [comment]
> Perhaps, it should be above [this block](https://monosnap.com/file/ThwdYSW55zNgjjelDthBAHGeJPo2MZ) and should look like
> "If you have the already installed Magento Commerce you can use [Prepare your existing Magento Commerce install instruction](https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html)."
> 
> What do you think about this? @meker12

Before you begin the import process, make sure that you have completed the steps to [Prepare your existing Magento Commerce system](https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html).

So the idea is that you already have a Magento Commerce project that is not on Cloud. You prepare that project by following the instructions in the "Prepare" topic.  Then, the next step is to import the prepared code into a Cloud project.

**Comment by meker12** [comment]
I think if the note uses the language in previous comment, update will be good:  Before you begin....

Having two notes together is not ideal.  That warning note makes more sense if you move it to the section  [Import your Magento Commerce code to your Cloud project](https://devdocs.magento.com/cloud/setup/first-time-setup-import-import.html#cloud-import-imp)

**Comment by meker12** [comment]
Thanks for your help @andrewbess 🥇
