### ISSUE TITLE
Feedback on Cloud composer topic

### ISSUE THREAD

**Issue by carlos-reynosa** [magento/devdocs#6168]
# General issue

https://devdocs.magento.com/cloud/reference/cloud-composer.html

## Description:

I feel like the description of the **magento/magento-cloud-metapackage** is kind of flat and as I was reading it I wasn't aware that the sections following the description of **magento/magento-cloud-metapackage** were describing it's included components. 

## Possible solutions:

A diagram describing the relationship between the **magento/magento-cloud-metapackage** and it's child packages **vendor/magento/ece-tools** and **vendor/magento/product-enterprise-edition** would be helpful. Or provide some type of text or visual cue that the following sections are subsections that help describe the **magento/magento-cloud-metapackage**  meta-package.

**Comment by shrielenee** [comment]
There hasn't been any work on this issue, so I'm moving it back to Ready for Dev. If someone wants to grab this to work please do!

**Comment by BarnyShergold** [comment]
@carlos-reynosa @shrielenee 
The Cloud Metapackage pulls in the 4 main components -
                fastly/magento2
                magento/ece-tools
                magento/module-paypal-on-boarding
                magento/product-enterprise-edition

Would a brief description of the purpose of each of these packages be sufficient to solve this issue?
