### ISSUE TITLE
Requirements for the StoreFront application

### ISSUE THREAD

**Issue by atwixfirster** [magento/devdocs#6194]
# New topic request

## Description

We have a new requirements for the StoreFront application:

<img width="1068" alt="6194_01" src="https://user-images.githubusercontent.com/13585327/70747330-6b0ef700-1d30-11ea-800c-ee1b21ca457f.png">

I would like to add them into existing documentation. Looking for the proper place.

**Option 1:** Add into existing [GraphQL Overview](https://devdocs.magento.com/guides/v2.3/graphql/) page

**Option 2:** Add a new topic in the Development section:

<img width="827" alt="6194_02" src="https://user-images.githubusercontent.com/13585327/70747417-a0b3e000-1d30-11ea-8f85-fd8f3ea195ed.png">

@keharper , what is your opinion?

## Content checklist

-  [ ] The topic provides an explanation of how ____ works.
-  [ ] The topic provides steps for ____.
-  [ ] The topic contains code samples that shows ____.
-  [ ] Other (please specify)

## Additional information/resources

Many thanks!

**Comment by jeff-matthews** [comment]
@keharper, can you help @atwixfirster groom this issue?
