### ISSUE TITLE
What is Transaction Details URL for Authorize.net Payments

### ISSUE THREAD

**Issue by Greenbebiz** [magento/devdocs#623]
I just called Authorize.net and they said they dont know what this form field is:
Transaction Details URL
![image](https://cloud.githubusercontent.com/assets/17227328/14751584/81c68d92-0898-11e6-857f-0cf0da01c435.png)

Im testing a sandbox account and am getting an infinite spinning css animation when I click to Submit Payment. There is a timeout issue with Authorize.net but the payment is processed.

Magento 2.0.0

**Comment by asemenenko** [comment]
Hi @Greenbebiz we utilize transaction details API provided by Auth.net, see page 10 here http://www.authorize.net/content/dam/authorize/documents/ReportingGuide_SOAP.pdf

> Im testing a sandbox account and am getting an infinite spinning css animation when I click to Submit Payment. 

Direct Post requires external web access to your machine otherwise it will not be able to return a response back.

**Comment by Greenbebiz** [comment]
which ports and what resources is required to be opened for external access?

**Comment by xcomSteveJohnson** [comment]
@asemenenko @Greenbebiz What else is needed to close this issue?

**Comment by xcomSteveJohnson** [comment]
Closing
