### ISSUE TITLE
Need more info about interpreting output of db:size command

### ISSUE THREAD

**Issue by almarchenko** [magento/devdocs#6245]
# General issue
The $magento-cloud db:size command can return very confusing information, like 1021% being used. (I tried attaching the image, do not understand if it worked out).
Talked to two support agents, and they do not recommend customers using this command. 
## Description:
The $magento-cloud db:size command can return very confusing information, like 1021% being used. (I tried attaching the image, do not understand if it worked out).
Talked to two support agents, and they do not recommend customers using this command.

## Possible solutions:
I suggest this command usage recommendations should be double-checked. Thank you.

## Additional information:

See [Manage disk space](https://devdocs.magento.com/cloud/project/manage-disk-space.html) topic. Possibly add more information and guidance about interpreting the output of `db:size` command.

**Comment by hguthrie** [comment]
Ah, yes. I think we might address this problem in the PR #7171 
We shall see...

**Comment by meker12** [comment]
So thinking that the article update which provides separate instructions for checking db-size on Integration and checking it on dedicated clusters (Pro Staging and Production_ might clarify the use of these commands.  @almarchenko Can you check the updated article:  https://devdocs.magento.com/cloud/project/manage-disk-space.html?

**Comment by meker12** [comment]
@almarchenko Closing this issue based on recent update. If needed, open a new issue for any further updates required.
