### ISSUE TITLE
Should Web User ulimit Information In More Locations?

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#628]
Should information regarding setting a ulimit for the web user ( http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_compman-ulimit.html ) be included in other pages? Possibly in the following:
- http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html
- http://devdocs.magento.com/guides/v2.0/install-gde/install/prepare-install.html
- http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_compman-checklist.html

Thanks

**Comment by xcomSteveJohnson** [comment]
I'll check with engineering to see if they are going to implement a solution. My current understanding is this affects only rollback using Component Manager or System Upgrade. If so, the information belongs only in the checklist.

Thanks for pointing it out.

**Comment by ryantfowler** [comment]
Ok, understood. Thank you @xcomSteveJohnson . I appreciate the feedback.

**Comment by xcomSteveJohnson** [comment]
I just learned that this issue affects all rollbacks. After I make the update I'll let you know so you can check it. Thanks again.

**Comment by ryantfowler** [comment]
Good to know. Thank you, Sir 😀

**Comment by xcomSteveJohnson** [comment]
The information is now in two places:

*  http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_compman-ulimit.html (where it was already)
*  http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-backup.html

I think that is appropriate because the issue affects rollback only. You don't need to set it to install Magento AFAIK.

If you agree, please close; if not, let us know what we should add.

**Comment by ryantfowler** [comment]
I haven't ran into any issues related to this during installation, so I also don't believe this is required for installation.

Thanks for the responsiveness in your communication. This is a fantastic improvement upon M1.

I don't currently see any further issues here.

**Comment by xcomSteveJohnson** [comment]
Sure, we're here to help you. It was frustrating for me also having no feedback from Magento 1 customers. This is a lot better.
