### ISSUE TITLE
Clarify steps in Migration Guide

### ISSUE THREAD

**Issue by burakswe** [magento/devdocs#6310]
Hello everyone, 

I have some struggles to follow if the document means Magento 1 or Magento 2 directory for the commands. Do you have a chance to express the difference? 

Thanks!

File: /guides/v2.3/migration/migration-migrate-settings.html

**Comment by shrielenee** [comment]
Hey there @burakswe --- Thanks for this question! We need to add info in the overview content about what versions you are migrating between. It's mentioned in the topmost topic, https://devdocs.magento.com/guides/v2.3/migration/bk-migration-guide.html, but not in the parent of this topic or within this topic.

This is Magento 2, by the way. We will clarify.

**Comment by atwixfirster** [comment]
Hi, @burakswe !

> I have some struggles to follow if the document means Magento 1 or Magento 2 directory for the commands. Do you have a chance to express the difference?

The first point `1. Log in to Magento server as the file system owner.` on the [Migrate settings](https://devdocs.magento.com/guides/v2.3/migration/migration-migrate-settings.html) means that on the Magento server you have Magento 1 and Magento 2 installations.

Also please note, Magento 1 does not have a `bin/magento` tool.

Please let us know if you have any additional questions here.

Thanks
