### ISSUE TITLE
Provide more info in Configure Apache and Elasticsearch

### ISSUE THREAD

**Issue by broros** [magento/devdocs#6316]
# General issue

## Description:

This page does not make a lot of sense, multiple parts are not very clear.

**Step 2: Secure communication with Apache

in step 2 it does not tell you how to add elasticsearh to the proxy, in only tell you how to remove the previous unsecured connection

```
<VirtualHost *:8080>
    ProxyPass http://localhost:9200/
    ProxyPassReverse http://localhost:9200/
</VirtualHost>
```

## Possible solutions:

don't have one

## Additional information:

File: https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-apache.html

**Comment by dobooth** [comment]
Adding the steps are described in step 1 and step 2 describes removing info that may or may have not been added from https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-apache.html#es-apache-proxy-24. Please provide more details about what could be clarified here. While it is a big, complicated topic, I am not sure what exactly to change with this issue.
