### ISSUE TITLE
Setup multiple domains info not correct in Set up multiple websites or stores with nginx topic

### ISSUE THREAD

**Issue by hungpvdev** [magento/devdocs#6317]
# General issue
Setup multiple domains using multiple virtual hosts is not correct
## Description:
-- In multiple virtual hosts, using Nginx "map" directive will not work correctly due to "map" directive only run once for the same variable. 

> Since variables are evaluated only when they are used, the mere declaration even of a large number of “map” variables does not add any extra costs to request processing. 

http://nginx.org/en/docs/http/ngx_http_map_module.html#map

## Possible solutions:
Instead of using map directive, we will set variable directly, map directive does not necessary due to we create Nginx file for each domain. 
set $MAGE_RUN_TYPE store;
set $MAGE_RUN_CODE fr;

## Additional information:
http://nginx.org/en/docs/http/ngx_http_map_module.html#map

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this
