### ISSUE TITLE
Clarify Magento version support for magento/url-rewrite-import-export

### ISSUE THREAD

**Issue by mpchadwick** [magento/devdocs#6322]
## Topic Link

https://github.com/magento/devdocs/blame/81586c737e31b63b12fa364b8d5edd551abde49f/src/cloud/configure/import-url-rewrites.md#L13

## Description

Is it true that this module is only available for 2.2.x or does it also support 2.3.x?

**Comment by atwixfirster** [comment]
Regarding to [module](https://marketplace.magento.com/commerceextensions-module-urlrewrites-import-export.html) compatibility it supports the next versions: 2.0, 2.1, 2.2

<img width="1286" alt="6322" src="https://user-images.githubusercontent.com/13585327/71694490-050a1280-2db8-11ea-8be2-f8fc86f9e7aa.png">

**Comment by atwixfirster** [comment]
> Is it true that this module is only available for 2.2.x or does it also support 2.3.x?

@mpchadwick , I've asked Scott (seller) directly and he answered - YES.

So, you can use it for your Magento 2.3.x.

Thank you!

**Comment by scottbolasevich** [comment]
Yes it will work on 2.3.x

**Comment by milindsingh** [comment]
Hi  @atwixfirster 
Is `magento/module-url-rewrite-import-export` and `commerceextensions/module-urlrewrites-import-export` are same ?

**Comment by atwixfirster** [comment]
Hi, @milindsingh !

> Hi @atwixfirster
> Is `magento/module-url-rewrite-import-export` and `commerceextensions/module-urlrewrites-import-export` are same ?

No. Looks like I missed up with module name 😊

**Comment by atwixfirster** [comment]
Ok. 

So, regarding to @rogyar notice `magento/module-url-rewrite-import-export` supports ~7.0.13|~7.1.0 PHP versions:

<img width="904" alt="module info" src="https://user-images.githubusercontent.com/2148959/71722378-dd9f5e00-2e28-11ea-89e0-de1d9299f125.png">

Regarding to [Magento 2.3 technology stack requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php) Magento 2.3.x supports the next PHP versions:
    ~7.1.3
    ~7.2.0
    ~7.3.0

and looks like `magento/module-url-rewrite-import-export` will not work with Magento 2.3.x.

Thank you, @rogyar for the provided info!

**Comment by scottbolasevich** [comment]
Who can i send the latest zip too?
