### ISSUE TITLE
Configuring the lock provider should be done with 'setup:config:set' instead of 'setup:store-config:set'

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#6325]
# Bug report

## Description

In the [configure the lock provider](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-lock.html#instgde-cli-lockconfig) section, it says to use `setup:store-config:set`, but that is incorrect. It should be done using `setup:config:set`.

### Steps to reproduce

1. Run `bin/magento setup:store-config:set --help`
1. Run `bin/magento setup:config:set --help`
1. Verify which one of those command have the options which start with `--lock-`

## Expected result

Seeing the command `setup:config:set` being used

## Possible solutions

Changing the command `setup:store-config:set` to `setup:config:set`

**Comment by karyna-tsymbal-atwix** [comment]
Indeed, looks like store-config:set is deprecated since 2.2.0, and config:set should be used.
I'm preparing PR with fix.

**Comment by karyna-tsymbal-atwix** [comment]
PR https://github.com/magento/devdocs/pull/6402

**Comment by hostep** [comment]
This was fixed in #6402, thanks @karyna-tsymbal-atwix!

Closing issue.
