### ISSUE TITLE
Editorial. Replace mdash HTML special char.

### ISSUE THREAD

**Issue by atwixfirster** [magento/devdocs#6337]
# Topic clarification/correction request

## Topic Link

[Translation dictionaries and language packages](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.html)

## Description

There are a lot of pages which have `&mdash;` special HTML char:

<img width="1281" alt="mdash" src="https://user-images.githubusercontent.com/13585327/71813497-68c76080-3082-11ea-8c91-bc2b08989644.png">

## Possible solutions

Replace `&mdash;` with `-`.

## Additional information

CC: @jeff-matthews

**Comment by jeff-matthews** [comment]
Thanks for reporting @atwixfirster. Your description suggests replacing the HTML entity with a hyphen/dash (`-`). The correct solution is to replace the HTML entity with the unicode [em dash](https://en.wikipedia.org/wiki/Dash#Em_dash) (`— `) character.

We use kramdown, which is supposed to convert three consecutive hyphens/dashes to a single em dash, but I haven't tested it to verify. See [kramdown docs](https://kramdown.gettalong.org/syntax.html#typographic-symbols).

> kramdown converts the following plain ASCII character into their corresponding typographic symbols:
>
>--- will become an em-dash (like this —)
> ...

**Comment by atwixfirster** [comment]
@jeff-matthews , can we discuss the award for this issue?  ;)

Many thanks!

**Comment by shrielenee** [comment]
@atwixfirster Points are awarded for completed PRs, not issues :)

Make this fix, per Jeff's info, and we can talk award points! 🏆

**Comment by atwixfirster** [comment]
> @atwixfirster Points are awarded for completed PRs, not issues :)
> 
> Make this fix, per Jeff's info, and we can talk award points! 🏆

Ok,  @shrielenee :)  

This is a PR https://github.com/magento/devdocs/pull/6351

Now your move :)

Thanks

**Comment by hguthrie** [comment]
Three dashes does convert to an em dash; however, it stores it as three separate characters.

**Comment by atwixfirster** [comment]
Hi, @hguthrie 
> Three dashes does convert to an em dash; however, it stores it as three separate characters.

sounds like an approve?

**Comment by hguthrie** [comment]
I'm not quite sure, @atwixfirster . Also, I was thinking about the Jekyll headers surrounded by three dashes. We might have to check that it doesn't interfere...

**Comment by hguthrie** [comment]
Okay, I tested a few scenarios:
First, my IDE highlights some instances as an error, which reflects a preference in my environment, so take that with a  grain of salt.
Second, when using three dashes inside of a Jekyll header will not work. For example, some of the fixes were in a title (`src/guides/v2.3/install-gde/continue-to-verify.md`).

Otherwise, it seems okay. As long as it is not used in a Jekyll title or alone on a single line, then it seems to work. Would probably be better to use the unicode —, though.

**Comment by keharper** [comment]
I didn't see the discussion happening here. Changing the mdash to 3 dashes in the frontmatter causes 3 separate dashes to be displayed in the title. I commented in #6351
