### ISSUE TITLE
GraphQL Query Wish List

### ISSUE THREAD

**Issue by zepgram** [magento/devdocs#6343]
# Topic clarification/correction request
The wishlist query is marked as available through Customer Query but it's not on latest version available (2.3.3), it will be done with 2.4 release according to this : 
- https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/WishlistGraphQl/etc/schema.graphqls

## Topic Link
https://devdocs.magento.com/guides/v2.3/graphql/queries/wishlist.html
https://devdocs.magento.com/guides/v2.3/graphql/queries/customer.html#retrieve-the-customers-wish-list

## Description
Documentation suggests it's accessible with version 2.3.x
But according to code, wish list is only accessible through her own Mutation on magento 2.3.x
https://github.com/magento/magento2/blob/2.3/app/code/Magento/WishlistGraphQl/etc/schema.graphqls

## Possible solutions

- First solution: Remove warning deprecated from graphQL wish list documentation (do it when magento 2.4 will be release) and remove wish list query from graphQL customer documentation
- Second solution: replace **"The wishlist query has been deprecated. Wish list information is now provided by the customer query."** by **"The wishlist query has been deprecated. Wish list information will be provided by the customer query with 2.4 release."**

**Comment by keharper** [comment]
@zepgram We inadvertently merged the `2.3.4-develop` branch into master prematurely and are working to revert those changes. This should be completed later today. Thanks for your diligence.
