### ISSUE TITLE
Custom elementTempl for UI forms' components.

### ISSUE THREAD

**Issue by ValeraPogrommist** [magento/devdocs#636]
Hi. Let's see an example.
`<textarea class="Magento\Ui\Component\Form\Element\Textarea">
        <argument name="data" xsi:type="array">
            <item name="js_config" xsi:type="array">
                <item name="component" xsi:type="string">Magento_Ui/js/form/element/textarea</item>
                <item name="config" xsi:type="array">
                    <item name="template" xsi:type="string">ui/form/field</item>
                    <item name="elementTmpl" xsi:type="string">ui/form/element/textarea</item>
                </item>
            </item>
        </argument>
    </textarea>`

Is it real to change that path
`<item name="elementTmpl" xsi:type="string">ui/form/element/textarea</item>`
in this way
`<item name="elementTmpl" xsi:type="string">MyModule/form/element/custom_textarea</item>`

Thx.

**Comment by almarchenko** [comment]
Hi @ValeraPogrommist, does your question refer to a specific doc?

**Comment by ValeraPogrommist** [comment]
No, its an abstract question, but i used that
http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_edit_form.html#template
And it doesnt work for me.

**Comment by almarchenko** [comment]
I've asked, cause for development questions there are more chances to get a reply from a developer on [Community Forums ](https://community.magento.com/)or [Magento Stack Exchange](http://magento.stackexchange.com/)

About the docs: could you plz give more details, what exactly does not work?

**Comment by ValeraPogrommist** [comment]
This line works fine
`<item name="elementTmpl" xsi:type="string">ui/form/element/input</item>`

But these don't
`<item name="elementTmpl" xsi:type="string">Magento_Ui/form/element/input</item>`

`<item name="elementTmpl" xsi:type="string">MyModule_Ui/form/element/input</item>`

**Comment by irenelagno** [comment]
@ValeraPogrommist, could you add instead <item name="elementTmpl" xsi:type="string">Magento_Ui/form/element/input</item> this one:
<item name="template" xsi:type="string">Magento_Ui/form/element/input</item>

<item name="template" xsi:type="string">MyModule/form/element/input</item>.
Sample:

Does it work for you?

**Comment by ValeraPogrommist** [comment]
I can't cause already use it.
`<item name="template" xsi:type="string">ui/form/field</item>`
`<item name="elementTmpl" xsi:type="string">Magento_Ui/form/element/input</item>`

**Comment by irenelagno** [comment]
@ValeraPogrommist , are you create your own definition.xml in your module to override default configuration for  "Magento\Ui\Component\Form\Element\Textarea"?

**Comment by ValeraPogrommist** [comment]
@irenelagno yes

**Comment by onakonechna** [comment]
Suppose you have MyModule module in app/code/. You should use <item name="elementTmpl" xsi:type="string">Magento_MyModule/form/element/input</item> and place your template file in MyModule/view/adminhtml/web/template/form/element/input.html. Notice that it must be placed in ../template/.., not ../templates/.. ! And because the UI module have this specific 'templates' folder naming, it can't be referred to as Magento_Ui and you better use ui/.. path for it.

**Comment by ValeraPogrommist** [comment]
U sure about that 
`Magento_MyModule`
?
Cause i have only Magento_Ui and MyModule folders in ...public/static... directory

**Comment by ValeraPogrommist** [comment]
For example, app\code\Sample\Ui.

In 

> pub\static\adminhtml\Magento\backend\en_US

I have Sample_Ui folder. And
`<item name="elementTmpl" xsi:type="string">Magento_Sample_Ui/form/element/input</item>`
`<item name="elementTmpl" xsi:type="string">Sample_Ui/form/element/input</item>`
not working. Any ideas?

**Comment by ValeraPogrommist** [comment]
It works. I've just renamed Sample_Ui in Sample_AnotherName. It seems that Magento's parser doesnt like using _Ui prefix. I had some assumptions about that.

@almarchenko So, lets close this issue, please. And it'll be better to add a bit info in devdocs.

Thank you.

**Comment by almarchenko** [comment]
@ValeraPogrommist yeah, definitely, i'll update the docs.
Thank you for your input.
