### ISSUE TITLE
Add disclaimer to Indexing overview topic about triggering reindex logic

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#6383]
# General issue

## Description:
The page does not explicitly specify that UpdateOnSave Indexers must be handled by custom code (plugins, events or any other working approach). 
The diagram is misleading and leaves you to believe that the Indexer logic is executed when the Index is configured as Update On Save when in reality this is not the case

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexing.html

## Possible solutions:
The solution is trivial. A clear disclaimer in a visibly delimited box, font or color that custom logic has to be added (e.g. plugins) to trigger re-index logic when involved entities are saved/deleted etc. and the indexer is configured as Update On Save
A core example would be very helpful as well.

**Comment by dobooth** [comment]
@jcalcaben Is this in your wheelhouse?

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this

**Comment by shrielenee** [comment]
@ajithkumar-maragathavel Hey there! When you start working an issue update the title to be more descriptive and add the link to the topic in the description. I made that change here! 🙇‍♀️

**Comment by shrielenee** [comment]
@ajithkumar-maragathavel Removing you as assignee as there has been no progress on this issue. Please re-assign if you want to work it!

**Comment by dineshvb** [comment]
@magento I am working on this
