### ISSUE TITLE
How to translate these docs?

### ISSUE THREAD

**Issue by QiuLihua83** [magento/devdocs#641]

**Comment by xcomSteveJohnson** [comment]
What language(s) are you interested in?

We haven't discussed this in any detail. We know there is a way to do it but the process will be lengthy and require constant updating.

**Comment by QiuLihua83** [comment]
I'm interested in chinese(zh_CN) language.Can you provide a way  to select different languages in the pages?

**Comment by xcomSteveJohnson** [comment]
We haven't thought about that either but I'm sure there's a way to do it.

**Comment by QiuLihua83** [comment]
Thanks very much.
