### ISSUE TITLE
Clarify what is <ClassName>

### ISSUE THREAD

**Issue by vshcheglov** [magento/devdocs#6413]
# General issue

## Description:

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html

> Use the following naming convention when you specify this element: \Vendor\Module\Plugin\<ClassName>

Not enough transparently what is ClassName here.

Is it a class name of class which I want to create?
Or a class name of class on which I'm creating a plugin?

If it is a class name of class which I want to create, do we have any naming convention after \Vendor\Module\Plugin\?

**Comment by atwixfirster** [comment]
Hi, @vshcheglov !

> Not enough transparently what is ClassName here.

 The name of a plugin’s class or its virtual type. 

For example,

```
<?php
namespace My\Module\Plugin;

class ProductAttributesUpdater
{
    public function beforeSetName(\Magento\Catalog\Model\Product $subject, $name)
    {
        return ['(' . $name . ')'];
    }
}
```

**Comment by vshcheglov** [comment]
So, considering your response, <ClassName> is just a desired plugin class name and part of class name after `My\Module\Plugin\` can be any which I want. No any naming convention from magento?

As you see here, Magento sometimes includes part in plugin class name, regarding to class name in "type" - CatalogRule\Model\Rule. 
```xml
<type name="Magento\CatalogRule\Model\Rule">
    <plugin name="addVariationsToProductRule" type="Magento\CatalogRuleConfigurable\Plugin\CatalogRule\Model\Rule\ConfigurableProductHandler"/>
    <plugin name="configurableChildValidation" type="Magento\CatalogRuleConfigurable\Plugin\CatalogRule\Model\Rule\Validation"/>
</type>
```
But somethimes not.
```xml
<type name="Magento\ProductAlert\Model\ProductSalability">
    <plugin name="product_alert_adapt_salability" type="Magento\InventoryProductAlert\Plugin\AdaptProductSalabilityPlugin"/>
</type>
```

**Comment by atwixfirster** [comment]
@vshcheglov 

> So, considering your response, is just a desired plugin class name and part of class name after My\Module\Plugin\ can be any which I want. 

yep

> No any naming convention from magento?

no :)

But, from my practice : the name of plugin class should describe a plugin purpose. This is an understandable point for another developers. 

Please let me know if have any additional question here.

**Comment by dobooth** [comment]
Thanks for the issue, and thanks Alex for your input. @vshcheglov, with this new information, please let us know where you think we can clarify here.

**Comment by atwixfirster** [comment]
@dobooth , I think we can resolve this issue because @vshcheglov did not provide any additional questions.

Thanks!
