### ISSUE TITLE
Feedback on page: /guides/v2.3/config-guide/varnish/config-varnish.html

### ISSUE THREAD

**Issue by hvanmegen** [magento/devdocs#6422]
I have no idea what 'stanza' means in this context.. the online definitions of 'stanza' also don't help.. contrary to popular opinion, the Magento 2 documentation ain't poetry as far as I know.

**Comment by jeff-matthews** [comment]
@hvanmegen, a [simple Google search](https://www.google.com/search?q=varnish+stanza&oq=varnish+stanza&aqs=chrome..69i57.1877j0j7&sourceid=chrome&ie=UTF-8) for "varnish stanza" returns several results directly from Varnish docs. Here are a few examples: 

- https://readthedocs.org/projects/varnish-cache/downloads/pdf/readthedocs/
- https://varnish-cache.org/docs/trunk/users-guide/purging.html
- http://varnish-cache.org/docs/6.3/users-guide/vcl-backends.html
