### ISSUE TITLE
Feedback on page: /cloud/architecture/scaled-architecture.html

### ISSUE THREAD

**Issue by awktion** [magento/devdocs#6436]
# General issue

## Additional information:

looks good, though i think we could improve this - the unified role of the core nodes would be more clear if updated to split or core so they are not hte same as other normal non split node roles (edited) 
meaning we’d have 3 roles:
unified (normal cluster)
core (db nodes in split)
web (web nodes in split)
Also this doesn’t seem to really say what’s special about the architecture and what makes it different. it says a few things but its not a clear accurate definition of ‘whats on core’ and ‘whats on web’ (edited) 
When the core tier approaches capacity, the only way to scale is to increase the server size, such as boosting the CPU power and memory
^- this may be a limitation we choose to have, but isn’t a technical limitation imo

**Comment by hguthrie** [comment]
I am not sure what you are trying to say about technical limitations. This topic provides a very high-level description of the scaling capabilities available to certain Cloud Pro projects. It does say that core nodes provide the various services and DB storage. But I have made an effort to clarify further for both node types and roles. If you have any further concerns, you are welcome to create a PR to make corrections or to provide more specific solutions in the issue.
