### ISSUE TITLE
Align Magento PHP prerequisites in different topics

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#6443]
# General issue

Align [Magento PHP prerequisites](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html#verify-installed-extensions) with [system requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php).

## Description:

The [System requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php) topic uses autogenerated data for supported PHP versions and required PHP extensions.

The [PHP prerequisites](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html#verify-installed-extensions) contain some information, which is partially hardcoded, that makes the prerequisites and requirements to look different at some point.

## Possible solutions:

Update the [PHP prerequisites](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html) to link to the corresponding [PHP requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php) or use the same scripting to autogenerate the data. Remove redundant hardcoded explanations such as _Magento 2.3.3 supports PHP 7.3._, since the autogenerated list already contains this information.

## Additional information:

Review other topics that contain hardcoded PHP requirements and align them to be of the same format using autogeneration unless it must not be used there.

**Comment by DenisSaltanahmedov** [comment]
Hi @shrielenee
The PR of the issue https://github.com/magento/devdocs/pull/6517 is merged
Could you close the issue?
Thx.

**Comment by shrielenee** [comment]
Yes @DenisSaltanahmedov --- The trigger "Closes #6443" wasn't used so this didn't auto close. Thanks for the reminder!
