### ISSUE TITLE
Create bundle product with price_type = 1 in REST

### ISSUE THREAD

**Issue by electrospanner** [magento/devdocs#6452]
# General issue
Cannot create bundle product with price_type = 1 (fixed) with REST API
## Description:
The customer raised a support ticket with this issue:

> We try to create bundle product with price_type = 1 (fixed) with REST API. Bundle products are created, but all have price_type = 0 (= dynamic price).
> How do we create bundle products with price_type = 0 with REST API Call?

## Possible solutions:

For bundle products, the attribute price_type must be set under custom_attributes!

```
"custom_attributes": [
      {
        "attribute_code": "price_type",
        "value": "1"
      }
    ]
 
```

> Please add that part to your documentation!

## Additional information:

The client found it here: 

https://stackoverflow.com/questions/40168472/how-to-create-bundle-product-in-magento-2-by-rest-api

**Comment by keharper** [comment]
The author referenced /guides/v2.3/graphql/queries/custom-attribute-metadata.html, but this is actually a request to add REST information. There isn't an automatic place to put this in the REST documentation.
