### ISSUE TITLE
Feedback on page: /guides/v2.3/rest/tutorials/orders/order-prepare-checkout.html

### ISSUE THREAD

**Issue by VanArmenia** [magento/devdocs#6458]
No such carriers

 "shipping_carrier_code": "tablerate",
 "shipping_method_code": "bestway"

After sending post request I have this error response.
I have tried to add this method and clear the cache, but result is the same.
I have tried also to change shipping_carrier_code and shipping_method_code, but the result is the same.

Could you please help?

 "message": "Carrier with such method not found: %1, %2",
    "parameters": [
        "bestway",
        "tablerate"
    ],

**Comment by keharper** [comment]
Hi @VanArmenia, I just ran the tutorial, and provided payload works fine for me.

The tutorial assumes you're using the Luma sample data and you've configured your installation as described in https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-config-store.html 

If your instance is configured correctly, the only question I can think to ask is which version of Magento are you running?

**Comment by keharper** [comment]
Closing due to lack of response.
