### ISSUE TITLE
Invalid link to CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by katmoon** [magento/devdocs#6467]
# Bug report

## Description

This bug report template contains a link https://github.com/magento/devdocs/blob/develop/.github/CODE_OF_CONDUCT.md which leads to a 404 page.

### Steps to reproduce

1. Open https://github.com/magento/devdocs/issues/new?template=BUG.md
2. Scroll down the issue template till Additional information section
3. Open the mentioned link https://github.com/magento/devdocs/blob/develop/.github/CODE_OF_CONDUCT.md

## Expected result

It seems the correct link is https://github.com/magento/devdocs/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by dobooth** [comment]
Yup. Need to change the link to the master branch, as nicely put in Expected Result.
