### ISSUE TITLE
Potentially misleading information

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#648]
On the following page : [Convert layout XML files](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-layout-xml.html) it reads 

>When  XML schema are updated, you should update your layout XML files to match the new Extensible Stylesheet Language Transformations (XSLT) stylesheet.

It's my understanding that XSLT are not related to XML schemas, they are simply a form of css for XML. It is my understanding that the XSD files are responsible for XML schemas.

For example, in `app/code/Magento/Cms/etc/frontend/page_types.xml` the page_types node reads:
`<page_types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_types.xsd">
`
The page_types.xsd file that is referenced, is what is responsible for defining the XML schema for page type declarations, not a XSLT file.

Either I'm misunderstanding something here or this information could be written in a way that conveys the intent with more clarity.

Thank you for your time.

**Comment by xcomSteveJohnson** [comment]
I'm sorry this took so long; I had assigned it to the wrong person.

Removed the word "schema". The internal wiki says "The command converts layout(XML) files to new format by applying XSL style sheet." which is kind of vague. If you've used this command, please let me know how and when you used it and I'll update the information.

If you're happy with the resolution, please close this issue.

**Comment by xcomSteveJohnson** [comment]
@ryantfowler  OK to close?

**Comment by xcomSteveJohnson** [comment]
Closing.

**Comment by ryantfowler** [comment]
@xcomSteveJohnson my apologies for not closing this...and yes I'm happy with the resolution. Thanks!
