### ISSUE TITLE
Clarify which logs are handled in /cloud/env/log-handlers.html

### ISSUE THREAD

**Issue by cgarrigues** [magento/devdocs#6482]
# General issue

## Description:

This page should be explicit as to what logs are being handled here.

## Possible solutions:

Explicitly state that this is for build and deploy logs, not for application or nginx logs.

More than one person has assumed that they can send nginx logs this way.

**Comment by meker12** [comment]
The log handlers topic already states that the log forwarding is for build and deploy actions:

![image](https://user-images.githubusercontent.com/6391769/78594919-bc2a8580-780e-11ea-873e-60060655538b.png)
 
However, in the log locations topic, there is a link to the logging handler topic that doesn't clarify that you  configuring slack and email is for build and deploy actions only, which might contribute to misunderstanding that you can configure logging handlers for nginx logs.  

![image](https://user-images.githubusercontent.com/6391769/78595156-217e7680-780f-11ea-9d5d-f4fa7842f006.png)

I updated the note to clarify that you can configure for build and deploy actions in PR #6999 .
