### ISSUE TITLE
Feedback on page: /guides/v2.3/rest/bk-rest.html

### ISSUE THREAD

**Issue by taf2** [magento/devdocs#6487]
# General issue
Not finding details that show how to authenticate the API

**Comment by keharper** [comment]
@taf2 Is this what you're looking for?

https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-token.html

**Comment by taf2** [comment]
Yes thank you! I found it after googling thought it should appear in the nav on that page thank you!
