### ISSUE TITLE
Feedback on page: /guides/v2.3/config-guide/elasticsearch/es-config-apache.html

### ISSUE THREAD

**Issue by broros** [magento/devdocs#6507]
do I still need to setup authentication if elasticsearch and Magento are on the same server using localhost for connection?

**Comment by dobooth** [comment]
Is there a particular section in this topic this needs clarification?

**Comment by dobooth** [comment]
We need to clarify around "Enable Elasticsearch HTTP Auth". The field is not in the screen shot. There is an option to setup auth within ES specifically.
