### ISSUE TITLE
Release Notes - Not correct the version

### ISSUE THREAD

**Issue by mrkhoa99** [magento/devdocs#652]
The version should be CE version: http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.3CE.html

![selection_205](https://cloud.githubusercontent.com/assets/6185767/15103227/04ef17f6-15d3-11e6-936b-e7457dfcdf02.png)

**Comment by jfrontain** [comment]
Thanks, Mr. Khoa! I will fix this today. I appreciate your catching this issue.

**Comment by jfrontain** [comment]
Hi Mr. Khoa, I wanted to update you on this issue. I've fixed the problem in the source but won't publish until tomorrow (5/17). Thank you for your help.

**Comment by jfrontain** [comment]
Hi Mr. Khoa, this fix has been published, so I am closing. Thanks again.
