### ISSUE TITLE
| symbol is missing on the Menu Bar

### ISSUE THREAD

**Issue by hitendra-wagento** [magento/devdocs#6528]
# Bug report
Dev Docs Home page "|" symbol is not displayed between each Menu Name.

## Description
Dev Docs Home Page.

### Steps to reproduce

1. Go to the below URL(Dev Docs Home Page).
2. https://devdocs.magento.com/
3. You will be able to see the Menu Bar.
4. Between the Testing and Functional Areas show the "|". and also the " | " vertical-align not proper.
5. While other Menu bars "|" symbol not showing.

## Expected result
" | " symbol should be displayed between.

## Possible solutions

" | " symbol should be displayed between.all the Menu Name

## Additional information

Here I have attached the screenshot for your reference.

![screenshot-devdocs magento com-2020 02](https://user-images.githubusercontent.com/34908133/73603651-b9f84080-45ab-11ea-9aee-fb8b28beec67.png)

**Comment by hitesh-wagento** [comment]
I am working on this issue.

**Comment by shrielenee** [comment]
@hitendra-wagento @hitesh-wagento This is a UX/design issue/decision. I am closing this one so we can investigate internally and fix the error. Thanks!

**Comment by jeff-matthews** [comment]
The original design calls for a single pipe character to separate the core top-level categories from the Functional Areas and Tutorials categories. This is working as designed between Docs and UX.
