### ISSUE TITLE
Extraneous " | " displays in the top navigation

### ISSUE THREAD

**Issue by hitendra-wagento** [magento/devdocs#6529]
# Bug report

Dev Docs Home page " | " symbol is not vertical-align proper.

### Steps to reproduce

1.Go to the below URL(Dev Docs Home Page).
2.https://devdocs.magento.com/
3.You will be able to see the Menu Bar.
4.Between the Testing and Functional Areas show the "|". a symbol is not vertical-align not proper.

## Expected result

" | " symbol should be vertical-align proper.

## Possible solutions

" | " symbol should be vertical-align proper.

## Additional information

Here I have attached the screenshot for your reference.

![Align ment](https://user-images.githubusercontent.com/34908133/73603870-6fc48e80-45ae-11ea-894c-6f9c61b74487.png)

**Comment by shrielenee** [comment]
This design decision was intentional, so I am going to close this for now. Please let us know if you have any questions!
