### ISSUE TITLE
About Customer New Address API

### ISSUE THREAD

**Issue by gzchauhan** [magento/devdocs#653]
Hello,
I checked magento V1 API in http://devdocs.magento.com/swagger/index.html#/ but didn't find any api for add new customer address, I want to ADD/EDIT customer addresses.

**Comment by keharper** [comment]
How about `PUT V1/customers/{id} `? The underlying method is a `save`, not a `create`, so it should be able to do what you're asking.

**Comment by keharper** [comment]
Did that work, @gzchauhan ?

**Comment by keharper** [comment]
@gzchauhan , I'll close this tomorrow (May 20) if I don't get a response.

**Comment by keharper** [comment]
Feel free to re-open.
