### ISSUE TITLE
Clarify behavior of plugins in Plugins (Interceptors) topic

### ISSUE THREAD

**Issue by gibbotronic** [magento/devdocs#6535]
# General issue
Plugins do not replace functionality. https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html

## Description:
The plugin guide states that plugins "substitute" behaviour of the original class. They do not. They merely call functions around it.
Calling functions around another function is not what the word "substitute" means, because the original function is still called.

In the given scenarios for replacing ```Action::dispatch()```, the original ```Action::dispatch()``` function always get called. Therefore it has not been substituted. It has still been called.

Another word for "substitute" is REPLACE. If the original function is still called, it has not been REPLACED.

In normal PHP inheritance, when you inherit from a base class and implement an overriding function, if you call that function on the object you get the child class' function, eg.
```
class ParentClass
{
  public function X()
  {
    echo "ParentClass::X called";
  }
}
class Child extends ParentClass
{
  public function X()
  {
    echo "Child::X called";
  }
}
$x = new Child();
$x->X();
// Will output Child::X called.
```
This is what replacing ParentClass::X() does.

This is not what plugins do. They do not replace the original at all. They merely pad it out with more calls.

## Possible solutions:
To avoid widespread confusion, change the documentation to actually state the reality, that the Plugin system does not stop the original getting called.
Plugins do not replace the original object's functions. They don't even extend them (you can't change what the original function returns directly for example).

They merely add more calls before/after the original.

Perhaps state:
_Plugins let you add extra functionality around existing functionality. They do not replace the original functionality._

## Additional information:

The existing documentation causes widespread confusion.

**Comment by milindsingh** [comment]
Thanks @gibbotronic for pointing this out. I believe the plugin just modifies the behavior of the original method. 
So, shall I replace the word `substitute` with `modifies` ? And add some extra description like:
`Plugins let you add extra functionality around existing functionality. They do not replace the original functionality.`

**Comment by gibbotronic** [comment]
Yes please, that'd be great, thank you!

**Comment by atwixfirster** [comment]
> Plugins let you add extra functionality around existing functionality. They do not replace the original functionality.

That's not correct statement. 

If you call a `callable` method in your plugin class then the original/parent method will be executed but if you do not do that then a parent method will be skipped.

Example with parent method call in the custom AROUND plugin:

```
    public function aroundDispatch(Action $subject, callable $proceed, ...$args)
    {
        $proceed(...$args);
    }
```

Example when parent method WILL BE SKIPPED in the custom AROUND plugin:
```
    public function aroundDispatch(Action $subject, callable $proceed, ...$args)
    {
        return 'my result';
    }
```

I've attached a module - 
[Vendor.zip](https://github.com/magento/devdocs/files/4173376/Vendor.zip) 

You can debug it if you want to understand how the AROUND plugin works.

Thanks!

**Comment by gibbotronic** [comment]
Perhaps after the warning "If the around method does not call the callable, it will prevent the execution of all the plugins next in the chain and the original method call." on the page, two examples could exist:
1. calling ```callable()```
2. NOT calling ```callable()```
to show the differences in outcome.

Also it isn't clear what happens if you don't call ```callable()`` - in Scenario B, if Plugin B does not call ```callable()```, what happens to PluginC? Does it still get its ```beforeDispatch``` and ```afterDispatch``` methods called? This isn't clear.

The sentence "Magento runs the code in around methods before and after their observed methods" is wrong too. The ```around``` function is only ran once. It isn't called twice.
The call stacks given in the scenarios imply that it is ran before AND after but it isn't - it is ran once, and needs to call ```callable()``` itself.

**Comment by atwixfirster** [comment]
> Also it isn't clear what happens if you don't call `callable()` - in `Scenario B`, if `Plugin B` does not call `callable()`, what happens to `PluginC`? Does it still get its `beforeDispatch` and afterDispatch` methods called? This isn't clear.

`Plugin C` will be not triggered.

See the attached example - 
[scenario_B_without_callable.zip.zip](https://github.com/magento/devdocs/files/4302666/scenario_B_without_callable.zip.zip)

**Comment by atwixfirster** [comment]
> The sentence "Magento runs the code in around methods before and after their observed methods" is wrong too. The around function is only ran once. It isn't called twice.

See the explanations in the next example - 
[scenario_B_with_callable.zip](https://github.com/magento/devdocs/files/4302667/scenario_B_with_callable.zip)
