### ISSUE TITLE
Clear Documentation on how Application Entry Points and Areas Effect di.xml Loading

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#654]
Full programmer context here -- https://github.com/magento/magento2/issues/2832

Magento's _areas_ (`frontend`, `adminhtml`) and _application entry points_ (`index.php`, `pub/static.php` ... others?) seems to impact which `di.xml` file gets loaded.  Having the official scoop on how this works from the Magento engineering team, as well as a clear explanation form the dev docs team seems important.

**Comment by antonkril** [comment]
Every entry point is supposed to use `Bootstrap` to create application object. `Bootstrap` loads all global `di.xml` files (`etc\di.xml` of modules). So all standard di.xml features work for such applications. One note: plugins are not supported in `app/etc/di.xml` as they are supposed to be used by extension developers for customizations.

In every application class (`implements \Magento\Framework\AppInterface`) you can see which areas this application loads.
For example:

- in index.php `\Magento\Framework\App\Http` loads area depending on front-name provided in url:
```php
$areaCode = $this->_areaList->getCodeByFrontName($this->_request->getFrontName());
$this->_state->setAreaCode($areaCode);
$this->_objectManager->configure($this->_configLoader->load($areaCode));
```
- in static.php `\Magento\Framework\App\StaticResource` also loads area based on request:
```php
$params = $this->parsePath($path);
$this->state->setAreaCode($params['area']);
$this->objectManager->configure($this->configLoader->load($params['area']));
``` 
- in cron.php `\Magento\Framework\App\Cron` always loads 'crontab' area:
```php
$this->_state->setAreaCode(Area::AREA_CRONTAB);
$configLoader = $this->objectManager->get('Magento\Framework\ObjectManager\ConfigLoaderInterface');
$this->objectManager->configure($configLoader->load(Area::AREA_CRONTAB));
```

**Comment by tanberry** [comment]
@jcalcaben is there an update to devdocs to reflect this info?

**Comment by jcalcaben** [comment]
Yes, I have updated the [Dependency Injection](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html#areas-and-application-entry-points) page with the answer provided by @antonkril.

@astorm can I close this issue?

**Comment by astorm** [comment]
@jcalcaben I don't know, can you? What is you're team's process for ensuring the documented information is correct? 

If you're only aping what Anton said in that ticket I'd say no, you can't close the issue.  You'd want to get a second opinion from an internal resource on whether the information, as documented, is correct and understandable.  The original information was likely incorrect because this validation didn't happen -- having someone else validate it is vital if you want the material to be correct.

**Comment by jcalcaben** [comment]
I will keep this ticket open until the content has been verified internally for correctness and clarity.

**Comment by jcalcaben** [comment]
You can now find the documentation for application entry points as it relates to the `di.xml` file at: http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/di-xml-file.html#areas-and-application-entry-points

**Comment by astorm** [comment]
> Type configurations describe an objects lifestyle and how to instantiate it.

Lifestyles of the rich and famous objects? ;)
