### ISSUE TITLE
Unable to run 'rake preview' on local

### ISSUE THREAD

**Issue by milindsingh** [magento/devdocs#6541]
# Bug report

## Description
`src/_data/codebase/v2_3/open-source/bin-magento.json): found unknown escape character while parsing a quoted scalar at line 1 column 200 (Psych::SyntaxError)`

### Steps to reproduce

1. Pull the code and run `bundle exec jekyll serve --incremental --trace` or `rake preview`

## Expected result
It should compile and run.

## Additional information
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by samshuai** [comment]
+1
`root@dev:/data/wwwroot/doc.magentochina.org# jekyll build --trace/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Configuration file: /data/wwwroot/doc.magentochina.org/_config.yml
 Theme Config file: /var/lib/gems/2.5.0/bundler/gems/devdocs-theme-e1a4ff6880d5/_config.yml
            Source: /data/wwwroot/doc.magentochina.org/src
       Destination: /data/wwwroot/doc.magentochina.org/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Traceback (most recent call last):
        36: from /usr/local/bin/jekyll:23:in `<main>'
        35: from /usr/local/bin/jekyll:23:in `load'
        34: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        33: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        32: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        31: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        30: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        29: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        28: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        27: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        26: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        25: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
        24: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
        23: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
        22: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
        21: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:74:in `process'
        20: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:174:in `read'
        19: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/reader.rb:19:in `read'
        18: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:20:in `read'
        17: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `read_data_to'
        16: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `each'
        15: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:43:in `block in read_data_to'
        14: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `read_data_to'
        13: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `each'
        12: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:43:in `block in read_data_to'
        11: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `read_data_to'
        10: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `each'
         9: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:43:in `block in read_data_to'
         8: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `read_data_to'
         7: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:38:in `each'
         6: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:46:in `block in read_data_to'
         5: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/readers/data_reader.rb:66:in `read_data_file'
         4: from /var/lib/gems/2.5.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
         3: from /var/lib/gems/2.5.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
         2: from /var/lib/gems/2.5.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
         1: from /var/lib/gems/2.5.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
/var/lib/gems/2.5.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': (/data/wwwroot/doc.magentochina.org/src/_data/codebase/v2_2/commerce/bin-magento.json): found unknown escape character while parsing a quoted scalar at line 1 column 153 (Psych::SyntaxError)`

**Comment by keharper** [comment]
@dshevtsov Can you take a look?

**Comment by dshevtsov** [comment]
Waiting for #6579 and #6546 to be merged into master to continue.
