### ISSUE TITLE
Describe how to add a custom attribute to GraphQL

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#6564]
# New feature request

## Description

Devdocs covers how to create a query or mutation from scratch, but it doesn't describe how to add a custom attribute to an existing query or mutation. The processes aren't really that different, so this information would provide clarity.

General process:

1. Add a field to the DB. This process is beyond the scope of the topic. A link to the declarative schema documentation will probably suffice.

2. Add the attribute to the schema within the graphqls file of your module

3. Write a resolver to process the attribute.

If there are more steps, add them.

## Additional information

Add links to the "Define the GraphQL schema for a module" and "Resolvers" topics.

**Comment by drpayyne** [comment]
Hey @keharper, please assign this to me. I'd like to work on this!

**Comment by keharper** [comment]
It's yours, @drpayyne
