### ISSUE TITLE
Can you provide a function to export this site as a pdf file?

### ISSUE THREAD

**Issue by andylhqiu** [magento/devdocs#661]
or do you have another way to do this?

**Comment by xcomSteveJohnson** [comment]
We currently have no way to do this. You can PDF one page at a time only.

**Comment by xcomSteveJohnson** [comment]
Tracking with MAGEDOC-2085.

**Comment by jcalcaben** [comment]
Closing issue.

This is a duplicate of: https://github.com/magento/devdocs/issues/330
