### ISSUE TITLE
Clarify explicitly why "EAV indexer" should be enabled/disabled when different search engines are used

### ISSUE THREAD

**Issue by ilnytskyi** [magento/devdocs#6659]
# Topic clarification/correction request
When trying to get information why we should use ES search or Mysql search there is no exact explanation how EAV indexer affects those scopes
## Topic Link

https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/configure-magento.html
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexer-batch.html

## Description
Not that much info is clear on this page about EAV indexer
https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/configure-magento.html

A bit more info available here
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexer-batch.html
But the pages are not linked.
Then It is not clear how EAV indexer behaves and inceracts with Mysql search and ES, it is not clear where the `catalog_product_index_eav`  table used. 

e.g. 
```
As of Magento 2.3, under certain circumstances, you can disable this indexer to improve performance. (Its indexation takes about 5 minutes on a large Magento 2 Commerce performance profile.)
```
1. `under certain circumstances` --- what exactly ?
2. ` to improve performance` --- how it works ?

there is no even single mention of **EAV** word at the page https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/configure-magento.html
## Possible solutions
Improve documentation

**Comment by LeanderFS** [comment]
Is there any update regarding this issue?

**Comment by sagar1dahiwala** [comment]
any updates yet?

**Comment by alitopaloglu** [comment]
Any updates?

**Comment by tuyennn** [comment]
+1

**Comment by dshevtsov** [comment]
The topics were moved to:
* https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/search/configure-search-engine
* https://developer.adobe.com/commerce/php/development/components/indexing/optimization/

If the issue is still relevant, please feel free to reopen it in the corresponding repositories:
* https://github.com/AdobeDocs/commerce-operations.en/issues
* https://github.com/AdobeDocs/commerce-php/issues
