### ISSUE TITLE
Ubuntu 16.04LTS Installation Instructions

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#668]
Now that Ubuntu 16 is out, will there be any plans to update the [Ubuntu](https://github.com/magento/devdocs/blob/2.0/guides/v2.0/install-gde/prereq/php-ubuntu.md) installation page?

**Comment by xcomSteveJohnson** [comment]
Not at this time. It's very time-consuming. I haven't fully documented CentOS 7 yet.

**Comment by ryantfowler** [comment]
Understood. Is this something that is open to PRs? Or is this something that is reserved for Magento employees to document?

**Comment by xcomSteveJohnson** [comment]
You're more than welcome to open a PR. I'll verify it so merging will take some time.

Thanks!

**Comment by ryantfowler** [comment]
Excellent.

Thanks for the clarification!
