### ISSUE TITLE
Space in Custom Directive code does not work on Email Templates

### ISSUE THREAD

**Issue by lenlorijn** [magento/devdocs#6683]
## Description:

The example of a new directive does not work in an upgraded 2.3.4 Magento.

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-email-migration.html

## Possible solutions:

Either a part of the description is missing or the code should be made to work. I personally have not been able to make this work.

## Additional information:

I have created a directive, a copy of the code here but in a different namespace.
When I add the directive to the template as a core change, to test if it works, the directive is not replaced.
If I place spaces between the curly braces and the name of the directive I get a notice "Undefined index: directiveName in vendor/magento/framework/Filter/DirectiveProcessor/SimpleDirective.php on line 68"

**Comment by denis-zyk** [comment]
@lenlorijn I've just had the same issue after upgrading to 2.3.4, and after some debugging it all resolved to template directives having spaces inside of curly braces, e.g.:
`<div>{{ name }}</div>`
should be replaced with:
`<div>{{name}}</div>`.

**Comment by dobooth** [comment]
@nathanjosiah

**Comment by rahulpathakweb** [comment]
error filtering template: notice: undefined index: directivename in vendor/magento/framework/filter/directiveprocessor/simpledirective.php on line 68
Hi Dear, i felt same error but i solved it 100%.  please check email template in marketing in the admin, if any commented code or unused  space please remove. you will get 100% solution.

**Comment by grafzahl-io** [comment]
> @lenlorijn I've just had the same issue after upgrading to 2.3.4, and after some debugging it all resolved to template directives having spaces inside of curly braces, e.g.: `<div>{{ name }}</div>` should be replaced with: `<div>{{name}}</div>`.

Thanks! Helped me to find my fault: I just changed the address format and accidentally moved a `{{/if}}` to the wrong place. This also caused this unrelated error message.

**Comment by akislawek** [comment]
@lenlorijn, @denis-zyk, @grafzahl-io 

Did anyone of you manage to successfully implement a custom directive in an email template and get it working correctly? I'm currently trying to achieve this, but with no success. The directive is not interpreted and still show as "{{lifetime_spend}}" in the email body.

I would be grateful if you could share your code if you got it working correctly.

Below I'm leaving a reference to a newly created github ticket for this issue: #9441, as well as a reference to [my question on stack exchange](https://magento.stackexchange.com/questions/355797/custom-email-directive-as-per-magento-2-4-docs-example-not-working) (on replies so far).
