### ISSUE TITLE
Remove 404 links to MarketPlace tools repo

### ISSUE THREAD

**Issue by benhath** [magento/devdocs#6684]
Validation tool URL dead.

**Comment by andrewbess** [comment]
Also, this link exists in [this article in the Magento blog](https://magento.com/blog/marketplace/magento-20-extension-upload-validation-tool)

**Comment by andrewbess** [comment]
I think it would be better to use here the next text: **_"Use our feature "Magento coding standard" to check your package before you distribute it"_** and add the link to [Magento coding standard Github repository](https://github.com/magento/magento-coding-standard).
How do you think @dobooth ?

**Comment by dobooth** [comment]
Let's remove the links for now. We will have updated information for them later on.
Fix the same link on this topic. https://devdocs.magento.com/guides/v2.3/extension-dev-guide/prepare/dev-summary.html
Ready when you are, @andrewbess!

**Comment by dobooth** [comment]
Search show me:
src/guides/v2.3/extension-dev-guide/intro/developers_roadmap.md
src/guides/v2.3/extension-dev-guide/package/package_module.md
src/guides/v2.3/extension-dev-guide/package/package.md
src/guides/v2.3/extension-dev-guide/prepare/dev-summary.md

**Comment by andrewbess** [comment]
Hello @dobooth 
I have fixed it.
Thank you for your effort to find dependent pages.
I also tried to find the dependent pages using some different methods. There was not exist more.
Please take a look at [my PR](https://github.com/magento/devdocs/pull/6736).
Thank you in advance.
