### ISSUE TITLE
Add information about required Apache configuration adjustment

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#6689]
# General issue

## Description:

In the documentation there is no information that apache configuration requires also following parameter to be set for apache globally or in virtualhosts:
```
AllowEncodedSlashes NoDecode
```

Context: 
https://github.com/magento/magento2/issues/21353#issuecomment-588988384

Incorrect configuration causing following issues, and maybe more:
- https://github.com/magento/magento2/issues/8615
- https://github.com/magento/magento2/issues/10434
- https://github.com/magento/magento2/issues/13343
- https://github.com/magento/magento2/issues/21179
- https://github.com/magento/magento2/issues/21353

I looked on following page https://devdocs.magento.com/guides/v2.3/install-gde/prereq/apache.html

## Possible solutions:

Adjust installation instructions to also add the following parameter to the global server configuration or to the virtualhost:
```
AllowEncodedSlashes NoDecode
```

Related docs in Apache: 
- https://httpd.apache.org/docs/2.2/mod/core.html#allowencodedslashes
- https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes

**Comment by ihor-sviziev** [comment]
In addition to that I see that also not shown that following modules need to be enabled:
- mod_expires - https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/pub/.htaccess#L172-L182
- mod_headers - https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/pub/.htaccess#L229-L233

**Comment by atwixfirster** [comment]
> In addition to that I see that also not described that following apache modules need to be enabled:
> 
>     * mod_expires - https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/pub/.htaccess#L172-L182
> 
>     * mod_headers - https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/pub/.htaccess#L229-L233

Added in the separate PR - https://github.com/magento/devdocs/pull/6755.

Thanks
