### ISSUE TITLE
Feedback on page: /cloud/project/project-conf-files_magento-app.html

### ISSUE THREAD

**Issue by abukatar** [magento/devdocs#6697]
# General issue
We have to emphasize that renaming an existing project is strictly discouraged.

## Description:
We have a client that complains that he lost project images due to the project renaming and there were no explanations of consequences in devdocs.
## Possible solutions:

Please change a notice:
"Do not change the name of an application after it has been deployed."
into a warning:
"Do not change the name of an application after it has been deployed. Doing so will result in data loss."

**Comment by dobooth** [comment]
@meker12 FYI...
