### ISSUE TITLE
Need to document the inheritance elimination for action controllers

### ISSUE THREAD

**Issue by lenaorobei** [magento/devdocs#6721]
Need to document layer super type removal and the recommendations for extension developers.

https://github.com/magento/magento2/pull/26778 PR moves the dispatching of the `controller_predispatch` events into a plugin.
It also changes the plugins for `Action::dispatch()` method to `ActionInterface::execute()`.
Finally, it preserves the behavior in regards to the `NO_DISPATCH` and `NO_POST_DISPATCH` action flags.

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: magento/community-features#9

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/26778

Magento 2 version:

-  [ ] 2.1.X
-  [ ] 2.2.X
-  [ ] 2.3.X
-  [x] 2.4.X
-  [ ] back port
-  [ ] forward port

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [ ] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

**Comment by jeff-matthews** [comment]
@lenaorobei, will this be backported to 2.3.5 or should we plan on publishing for 2.4.0 only?

**Comment by lenaorobei** [comment]
@jeff-matthews, 2.4.0 only.

**Comment by AnshuMishra17** [comment]
@lenaorobei What is the expected release date for Magento 2.4?

**Comment by jeff-matthews** [comment]
Thank you @lenaorobei! We will need a technical resource to help us with this, Do you have a recommendation?

**Comment by lenaorobei** [comment]
Sure @jeff-matthews! You can ping me or @lbajsarowicz. 
This blog post might be helpful as well https://community.magento.com/t5/Magento-DevBlog/Decomposition-of-Magento-Controllers/ba-p/430883

**Comment by lbajsarowicz** [comment]
It's been covered already.

**Comment by jeff-matthews** [comment]
Thanks @lbajsarowicz!
