### ISSUE TITLE
Link On The Bottom of install-cli-install.html Is Broken for After Install File Permissions

### ISSUE THREAD

**Issue by rip057** [magento/devdocs#680]
the full link is
http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html

there is no guidance for 2.0.6 AFTER install file permissions...

this really needs to be fixed

**Comment by xcomSteveJohnson** [comment]
Sorry about that. There is no post-install file permissions topic; there is only a topic about [umask](http://devdocs.magento.com/guides/v2.0/install-gde/install/post-install-umask.html) that doesn't apply to everybody. I will fix it today.

**Comment by rip057** [comment]
Hey thanks a lot, I just know in the legacy section there is a cut and
paste script type box that sets all permissions.  But thanks for the
attention
On May 23, 2016 3:08 PM, "Steve Johnson" <notifications@github.com> wrote:

Sorry about that. There is no post-install file permissions topic; there is
only a topic about umask
<http://devdocs.magento.com/guides/v2.0/install-gde/install/post-install-umask.html>
that doesn't apply to everybody. I will fix it today.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/magento/devdocs/issues/680#issuecomment-221080955>

**Comment by xcomSteveJohnson** [comment]
Fixed now, please verify and close this.

**Comment by rip057** [comment]
Hey thanks for all your hard work.  I hope to soon be able to contribute,
I'm just not confident enough in my work skills just yet
On May 23, 2016 3:32 PM, "Steve Johnson" <notifications@github.com> wrote:

Fixed now, please verify and close this.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/magento/devdocs/issues/680#issuecomment-221087217>

**Comment by xcomSteveJohnson** [comment]
This wasn't hard, it's kind of embarrassing although the file system permission change was a big one for me. 

Please give us feedback when you do contribute; we want to make it as easy as possible. Don't worry too much about the finer points; the submission itself is valuable. We can help with the details.

**Comment by rip057** [comment]
verified as working and that specific section of the install progress make a ton more sense now.

It just left things open ended for me, and i am uber security conscious with all the logged attacks on my webserver.  Its kind of sad to be totally honest, the amount of bans fail2ban logs and the other times i notice things
