### ISSUE TITLE
Move downloadables from the repository

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#6807]
# New feature request

## Description

The repository contains large binary files linked in topics as downloadables such as images of proprietary formats and archives, that sufficiently enlarges the repository in size. It would be great to have them as just links like https://devdocs.magento.com/downloads to avoid tracking the huge files in git and adding them to each build.

## Expected result

1. All downloadables are removed from the repository.
2. All downloadables are still available by the appropriately updates links.

## Benefits

This will help to avoid unneeded inflation of the repository.
Local development will take far less space on disk.

## Possible solutions

Move the downloadables to https://devdocs.magento.com/downloads or other Magento-supported DNS and maintain them separately.

**Comment by jeff-matthews** [comment]
@dshevtsov, I found several `.pdf`, `.psd`, and `.zip` files in the project that should be moved. Can you think of any other file types I should search for?

**Comment by dshevtsov** [comment]
`.ai`, `.sketch`
@dobooth maybe you can add more.

**Comment by jeff-matthews** [comment]
I propose moving the binaries to a new object in our S3 bucket called `downloads/`. We do something similar on the `docs.magento.com` site for storing PDFs.

I'll create the new object on S3 and update links in a new devdocs branch to show how this will work.

We would need to update the devdocs production Jenkins pipeline to exclude the new object so it doesn't get deleted on subsequent deployments.

I can also create a branch for the change in the infra repo.

The only thing left to consider is how we plan to manage and backup these binary files. 

- What if we lose data on S3 and need to redeploy the binaries for some reason?
- What if a team member needs to add a new binary file?
- Where should we store these binaries?
- Should we create a pipeline to manage these interactions?

**Comment by jeff-matthews** [comment]
See DOC-120

**Comment by dshevtsov** [comment]
The discussion about internal implementation will be discussed in internal channels.
Any important highlights about affected content or changes in contribution workflows will be shared here.
