### ISSUE TITLE
Document how to install extensions/themes/packages purchased through Marketplace

### ISSUE THREAD

**Issue by erikhansen** [magento/devdocs#682]
Provide easy-to-follow instructions for how to download the extensions/themes/packages from the Marketplace using Composer. I realize [this page](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html) gives instructions on how to generate a public/private key pair, but there needs to be a devdocs page explaining how the process works. And the Marketplace interface should also provide inline documentation on how this works.

Right now, if I purchase an extension through the marketplace, there is NO indication that it is possible to install via Composer. In fact, it seems like the only possible course of action is to download a ZIP of the extension:

![11-54-56 my purchases-w9rsk](https://cloud.githubusercontent.com/assets/129031/15512611/668a238c-21a6-11e6-80d6-edf459e95458.png)

**Comment by xcomSteveJohnson** [comment]
I don't quite understand. Granted, I'm a Magento employee so I know that the same user name and password you used to get the extension can be used by Component Manager to download it.

This seems to be a request to change the Marketplace UI and possibly Marketplace user documentation, is that correct?

I don't think it makes sense to add to devdocs when there's no link from this page to devdocs.

**Comment by erikhansen** [comment]
At the very least, the Marketplace UI should cover this. Is there a separate place for Martketplace documentation? I wasn't aware of that.

I just discovered this section in devdocs: http://devdocs.magento.com/guides/v2.0/comp-mgr/compman-start.html This covers what I was hoping to see in devdocs. So it seems like all that should be done now is that the Marketplace UI should be updated to point to that section of the devdocs so that merchants don't think they need to manually download and install extensions.

Closing this issue.

**Comment by xcomSteveJohnson** [comment]
I brought this to the attention of the product owner for this area so I'm going to reopen it for the time being.
You're right, there should be information _on the Marketplace page_ that there are 3 ways to install with some instructions on how to do it and pointers to documentation for details: download, Composer, and Component Manager.

**Comment by erikhansen** [comment]
Thanks for re-opening and taking initiative on this.

I agree that better documentation about the different approaches is needed.

Classy Llama built and maintains the AvaTax extension for Magento 2. On our [documentation page](http://www.classyllama.com/documentation/extensions/avatax-magento-2-module#installation), we've covered installing the module via Composer and via copying files, and need to add a section about how to install via the Marketplace. That is what prompted this Github issue as it wasn't apparent to me how to do that.

**Comment by xcomSteveJohnson** [comment]
Minor update. I am working on Magento Enterprise Cloud Edition, and you cannot use Component Manager or System Upgrade; they are effectively disabled. To install extensions and perform updates, you have to use the command line.

Yesterday in an internal Skype chat, I brought up what a pain that is; just finding the Composer name practically takes an act of Congress! I'm told that there are plans to provide the Composer name on-screen after you purchase an extension (not sure where). 

It would be nicer still if you could download the extension in a format that enabled you to extract it in your Magento root dir but there are no definite plans to do that.

I encourage you and others to use your influence to improve this experience; I will do what I can but you can help also. Meanwhile, I'm still set to document the above post 2.1 so stay tuned.

**Comment by xcomSteveJohnson** [comment]
@erikhansen FWIW, it's now easier to get an extension's Composer name. We cover it [here](http://devdocs.magento.com/guides/v2.1/cloud/howtos/install-components.html#cloud-howto-comp-composer).

In 2.2, there will be an Extension Manager (install, uninstall, update) and a Module Manager (enable, disable). This will make dealing with components a little easier.

Question remains as to how valuable it is to document:

*  Downloading an extension from Marketplace and installing it (unzip, etc)
*  Command-line extension installs and updates

I could probably do those before 2.2 is released; please advise as to what you think the priority is.

**Comment by erikhansen** [comment]
I'm glad to see that it's easier to get a Composer packages name!

I guess the feedback I have at this point is more of a Marketplace UI issue, not necessarily a documentation issue.

I would encourage you to go through the process of purchasing an extension (even a free one) on the Marketplace and do it in the mindset of a non tech-savvy merchant. I haven't done it recently, but I do know that when I'm looking at a list of my "purchases", there is no indication that I can install a module via Composer/Extension Manager (see the screenshot in my initial issue description). This seems like it's a big shortcoming in the UI of the Marketplace.

**Comment by xcomSteveJohnson** [comment]
Your request is forwarded to the Marketplace team.

Created issue MAGETWO-59819 to track.
