### ISSUE TITLE
commands from prod_file-sys-perms.html for post production file system permissions

### ISSUE THREAD

**Issue by rip057** [magento/devdocs#683]
on the page 

http://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_file-sys-perms.html

the commands as follows for post install or production store

find var vendor lib pub/static pub/media app/etc -type f -exec chmod g-w {} \;
find var vendor lib pub/static pub/media app/etc -type d -exec chmod g-w {} \;
chmod o-rwx app/etc/env.php

specifically renders the software broken as the home page reveals this

Fatal error: Uncaught exception 'Zend_Cache_Exception' with message 'cache_dir "/var/www/magento2/var/page_cache" is not writable' in /var/www/magento2/vendor/magento/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/var...') #1 /var/www/magento2/lib/internal/Cm/Cache/Backend/File.php(82): Zend_Cache_Backend_File->setCacheDir('/var/www/magent...') #2 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /var/www/magento2/vendor/magento/framework/App/Cache/Frontend/Factory.php(155): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true) #5 /var/www/magento2/vendor/magento/framework/App/Cache/Frontend/Pool.php(67): Magento\Framework\App\C in /var/www/magento2/vendor/magento/zendframework1/library/Zend/Cache.php on line 209

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing this out. It will take a little time to verify a fix; I'll update you on Wed.

**Comment by rip057** [comment]
well this was from a fresh composer install of 2.0.7. figures as soon as i get 2.0.6 working i need to upgrade lol

**Comment by rip057** [comment]
also my lamp versions incase you curious
PHP 5.6.21 (cli) (built: Apr 28 2016 06:53:44)

Server version: Apache/2.4.18 (Fedora)
Server built:   Jan  4 2016 13:05:47

mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for Linux (x86_64) using readline 5.1

Linux 4.4.6-201.fc22.x86_64 #1 SMP Wed Mar 30 18:30:16 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xcomSteveJohnson** [comment]
I don't doubt what you're saying. I'm starting to go through it now.

**Comment by xcomSteveJohnson** [comment]
I updated the documentation. Would you mind trying it?

http://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_file-sys-perms.html#mage-owner-two-prod

**Comment by rip057** [comment]
OK but it'll be later tonight I will.

Sorry if these issues are minor or bothersome

**Comment by rip057** [comment]
it seems fine now, I actually had just run 
magento setup:static-content:deploy
instead of 
magento deploy:mode:set production

so i am extremely grateful for making this issue

I will add this and maybe you can forward it where need be, as it can be extremely confusing.  At the end of the compile section of magento deploy:mode:set production it drops this text.

On *nix systems, verify the Magento application has permissions to modify files created by the compiler in the "var" directory. For instance, if you run the Magento application using Apache, the owner of the files in the "var" directory should be the Apache user (example command: "chown -R www-data:www-data <MAGENTO_ROOT>/var" where MAGENTO_ROOT is the Magento root directory).

we all know that magento 2.0 is promoting a two user system for security purposes and this forgets all about that

**Comment by xcomSteveJohnson** [comment]
Created internal issue MAGETWO-53473 to track the message.
