### ISSUE TITLE
Need to document dashboard charts improvement

### ISSUE THREAD

**Issue by lenaorobei** [magento/devdocs#6830]
# New topic request

## Description
Need to document dashboard charts improvement base on https://github.com/magento/magento2/pull/26923

Will be the part of 2.4.0 release.

## Content checklist

-  [ ] The topic provides an explanation of how ____ works.
-  [ ] The topic provides steps for ____.
-  [ ] The topic contains code samples that shows ____.
-  [ ] Other (please specify)

## Additional information/resources
In the scope of https://github.com/magento/magento2/pull/26923 new library was added in order to improve the UI.

**Comment by atwixfirster** [comment]
I may be wrong but this ticket is a [MerchDoc](https://github.com/magento/merchdocs/) stuff.

**Comment by lenaorobei** [comment]
You are right, we should consider transferring it.

**Comment by jeff-matthews** [comment]
Yes, this issue belongs in the magento/merchdocs repo. We don't have permissions to move issues between repos, so I just created a new issue in magento/merchdocs#403.
