### ISSUE TITLE
clarify usage of _extend.less in theme structure

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#6864]
# Topic clarification/correction request
I just faced a misconception after reading the documentation about extending less files in the child theme by using `_extend.less` file. 

By reading the documentation it is apparent to me that I can chain uses of _extend.less in child themes' children. 

So if I have a structure like 

mytheme 
mytheme/mychildtheme which extends mytheme
mytheme/mychildtheme/mysecondchildtheme   which extends mytheme/mychildtheme 

and both my child themes use _extend.less 

in reality `mysecondchildtheme`  will override the _extend.less of `mychildtheme` instead of extending it. 

Reading on the #8852 (https://github.com/magento/magento2/issues/8852) issue in magento 2 issues tracker I can see that this is expected behaviour and not a bug so I think it needs to be clarified in the docs too. 

## Topic Link

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-guide/css_quick_guide_approach.html

## Description

So if I have a structure like 

mytheme 
mytheme/mychildtheme which extends mytheme
mytheme/mychildtheme/mysecondchildtheme   which extends mytheme/mychildtheme 

and both my child themes use _extend.less 

in reality `mysecondchildtheme`  will override the _extend.less of `mychildtheme` instead of extending it. 

Reading on the #8852 issue in magento 2 issues tracker I can see that this is expected behaviour and not a bug so I think it needs to be clarified in the docs too. 

## Possible solutions

A solution would be to provide an example of what is possible and what is not possible.

**Comment by mrtuvn** [comment]
Have you re-read the docs ?
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-guide/css_quick_guide_approach.html
