### ISSUE TITLE
Typo in the description of Pagebuilder->Extend a content Type -> step 3: Extend Forms - Extension forms.

### ISSUE THREAD

**Issue by sagar1dahiwala** [magento/devdocs#6865]
# Topic clarification/correction request
I think there is a typo in the description of step 3: Extend Forms - Extension forms. The name of the form will be the same as the existing content type’s form. As per the given example in the document and codebase, that file name should be "pagebuilder_banner_form.xml" instead of "page-banner-form.xml" 

## Topic Link
https://devdocs.magento.com/page-builder/docs/extend-existing-content-type/step-3-extend-forms.html#extension-form

## Description

The name of the form will be the same as the existing content type’s form. As per the given example in the document and codebase, that file name should be "pagebuilder_banner_form.xml" instead of "page-banner-form.xml"

## Possible solutions

Update the doc for content. "In our case, we are customizing the Banner’s form, which means we must name our form: **page-banner-form.xml.**" to "In our case, we are customizing the Banner’s form, which means we must name our form: **pagebuilder_banner_form.xml.**"

**Comment by jeff-matthews** [comment]
@bdenham, can you help with this one?

**Comment by bdenham** [comment]
hey @sagar1dahiwala, you are correct. It should be `pagebuilder_banner_form.xml`. Thanks for catching that. I will fix it soon with a PR and update you when done.

**Comment by bdenham** [comment]
PR has been created for this issue. It will be fixed in the docs soon. Thanks again for catching that!

**Comment by bdenham** [comment]
@sagar1dahiwala fixed now :) https://devdocs.magento.com/page-builder/docs/extend-existing-content-type/step-3-extend-forms.html#extension-form
