### ISSUE TITLE
Feedback on page: /guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.html

### ISSUE THREAD

**Issue by hieudmg** [magento/devdocs#6896]
# The guide is not working on Magento 2.3.3

I followed the guide to add command line to my newly installed Magento 2.3.3 instance. When run `bin/magento setup:upgrade` or `bin/magento setup:di:compile` or `bin/magento cache:clean` this error will be shown: 

```
The command defined in "Vendor\Module\Console\Command\SomeCommand\Interceptor" cannot have an empty name.
```

After add `$this->setName("anything");` in `configure()` function the error is gone.

The code in the guide and sample module have too much differences, it is very confused.

**Comment by atwixfirster** [comment]
There are two ways how you can define a name of your custom command:
- via `di.xml`:

```
       <type name=" Magento\CommandExample\Console\Command\SomeCommand">
           <arguments>
               <!-- configure the command name via constructor $name argument -->
               <argument name="name" xsi:type="string">my:first:command</argument>
           </arguments>
       </type>
```

- in the `configure()` function:

```
    protected function configure()
    {
        $this->setName('example:modules:check-active')
            ->setDescription('Checks application status (installed or not)');

        parent::configure();
    }
```

I will update a tutorial.

**Comment by jeff-matthews** [comment]
Thanks @atwixfirster!

**Comment by hieudmg** [comment]
@atwixfirster thanks but the xml way is not working for me. I copy-pasted the code from the guide and the error showed up.

**Comment by atwixfirster** [comment]
> @atwixfirster thanks but the xml way is not working for me. I copy-pasted the code from the guide and the error showed up.

Does your custom Command class have a `__construct()` method? If yes then you need to put a `$name` into a parent `__construct()`. For example:

```
class UpgradeHashAlgorithmCommand extends Command
{
    /**
     * @var CollectionFactory
     */
    private $customerCollectionFactory;

    /**
     * @var Collection
     */
    private $collection;

    /**
     * @var Encryptor
     */
    private $encryptor;

    public function __construct(
        CollectionFactory $customerCollectionFactory,
        Encryptor $encryptor,
        string $name = null
    ) {
        parent::__construct($name);

        $this->customerCollectionFactory = $customerCollectionFactory;
        $this->encryptor = $encryptor;
    }

  ....
}
```

If your custom Command class does not have a `__construct()` method then it should work:
```
