### ISSUE TITLE
PHP Extension ext-sockets not in requirement list

### ISSUE THREAD

**Issue by dverkade** [magento/devdocs#6912]
# Bug report

## Description

Magento requires the following library: php-amqplib/php-amqplib this requirement is listed in the root composer.json of Magento here: https://github.com/magento/magento2/blob/2.4-develop/composer.json#L45

This library required the PHP extension "ext-sockets" since 2018. However this extension is not listed in the required PHP extension list in the documentation. 

The library requires ext-sockets since 2018 as listed here: https://github.com/php-amqplib/php-amqplib/blob/master/CHANGELOG.md#281---2018-11-13

### Steps to reproduce

Install Magento without the ext-sockets PHP extension. This will fail.

## Expected result

Have the required extension added to the documentation.

## Possible solutions

Add requirement to the list of required PHP extensions.

**Comment by atwixfirster** [comment]
Fixed in https://github.com/magento/devdocs/pull/6922.

Thank you for reporting, @dverkade
