### ISSUE TITLE
The "--all" option does not exist.  

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#694]
When following page

    http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-test.html

include a code sample that indicates a `--all` option exists for the `dev:tests:run` command

    magento dev:tests:run [--all] <test>

However, trying to use this option results in the following

    $ magento dev:tests:run --all
                     
      [RuntimeException]                  
      The "--all" option does not exist.  

      dev:tests:run [type]

**Comment by xcomSteveJohnson** [comment]
Updated the page. Please check it out and close this issue if it's fixed.

**Comment by astorm** [comment]
Can't tell you if it's "fixed" or not -- that's up to whatever internal process you're using to ensure the dev docs information is accurate, works, and reflects the goals of each individual page.
