### ISSUE TITLE
Clarify which directories are synced in staging/prod clusters

### ISSUE THREAD

**Issue by tscoffield** [magento/devdocs#6942]
# General issue
Clarification on what directories are synced on a pro environment

## Description:

https://devdocs.magento.com/cloud/architecture/pro-architecture.html#production-technology-stack
https://devdocs.magento.com/cloud/project/project-conf-files_magento-app.html#mounts
https://devdocs.magento.com/cloud/project/log-locations.html

The above links describe where to find logs and which locations are writable, however, I do not see any explanation of which directories are synced across the 3 nodes in the staging and production clusters. For example, ~/var/log is not synced and I cannot see anywhere it explicitly states this.

## Possible solutions:

Explicitly state which files and directories are synced in a cluster

**Comment by hguthrie** [comment]
We do mention this for the scaled architecture. https://devdocs.magento.com/cloud/architecture/scaled-architecture.html#log-locations

**Comment by meker12** [comment]
https://devdocs.magento.com/cloud/project/log-locations.html#viewing-logs

![image](https://user-images.githubusercontent.com/6391769/82265956-f028b880-992d-11ea-93fc-4434d8677c45.png)

**Comment by meker12** [comment]
This issue is addressed in updates from https://github.com/magento/devdocs/pull/7238
