### ISSUE TITLE
order cart with payment method by "paypal_express" 

### ISSUE THREAD

**Issue by linhtv97** [magento/devdocs#6948]
When making payment by paypal in magento pwa, when considering setPaymentMethodOnCart with the following payment_method method: "paypal_express" I proceed with the order by mutation: {placeOrder (input: PlaceOrderInput): {PlaceOrderOutput}}
but the result returns Invalid token (# 10410: Invalid token). In my opinion, especially when the user has paid, there is "payer_id" so how to order with the payment method "paypal_express" ???
Thanks and sorry My English is very bad
![image](https://user-images.githubusercontent.com/48935244/77853621-1fb12380-720f-11ea-9b97-e5f4c8fba16a.png)

**Comment by atwixfirster** [comment]
Hi, @linhtv97 !

Did you try to use [createPaypalExpressToken](https://devdocs.magento.com/guides/v2.3/graphql/mutations/create-paypal-express-token.html)?

**Comment by keharper** [comment]
@linhtv97 Your screenshot doesn't show what mutations you ran before `placeOrder`. If [PayPal Express Checkout payment method](https://devdocs.magento.com/guides/v2.3/graphql/payment-methods/paypal-express-checkout.html) doesn't answer your question, then there is a technical issue, and you should ask on the graphql channel on Engcomm Slack. https://magentocommeng.slack.com/archives/C8076E0KS

**Comment by linhtv97** [comment]
> Hi, @linhtv97 !
> 
> Did you try to use [createPaypalExpressToken](https://devdocs.magento.com/guides/v2.3/graphql/mutations/create-paypal-express-token.html)?

hi @atwixfirster  
I have followed and created the url, but when paying with that url it all fails to show the payment form and manually redirect to the magento page, maybe when creating the url token information is not enough

**Comment by linhtv97** [comment]
> @linhtv97 Your screenshot doesn't show what mutations you ran before `placeOrder`. If [PayPal Express Checkout payment method](https://devdocs.magento.com/guides/v2.3/graphql/payment-methods/paypal-express-checkout.html) doesn't answer your question, then there is a technical issue, and you should ask on the graphql channel on Engcomm Slack. https://magentocommeng.slack.com/archives/C8076E0KS

@keharper 
mutation I ran before include: 
+ create emty cart 
+ add product into cart
+ set payment method is "paypal_express"
+ set email because owner of cart is guest
+ placeOrder ( error 10410 invalid token )
![image](https://user-images.githubusercontent.com/48935244/77859548-50f01a80-7234-11ea-99df-446fbb6838c6.png)
![image](https://user-images.githubusercontent.com/48935244/77859580-70874300-7234-11ea-9e93-a9d6745a1a0f.png)

**Comment by keharper** [comment]
@linhtv97  Your `setPaymentMethodOnCart` mutation doesn't include the proper payload. Make sure that you're following the procedure described in "PayPal Express Checkout payment method", linked above. Also, make sure the `return_url` value in the `createPaypalExpressToken` is an actual page.

**Comment by linhtv97** [comment]
> @linhtv97 Your `setPaymentMethodOnCart` mutation doesn't include the proper payload. Make sure that you're following the procedure described in "PayPal Express Checkout payment method", linked above. Also, make sure the `return_url` value in the `createPaypalExpressToken` is an actual page.

@keharper  
Is there a way to return_url will return to pwa page rather than back to magento's back end url
![image](https://user-images.githubusercontent.com/48935244/77885
919-22a12800-7292-11ea-8f4a-995ef9cf93e3.png)

when payment finish t want it back page pwa studio but it back to font_end magento 
![image](https://user-images.githubusercontent.com/48935244/77886192-9e9b7000-7292-11ea-9182-815e045526b5.png)

Thanks!

**Comment by keharper** [comment]
It sounds like you're looking to combine steps 3 & 4 of the PP EC workflow, and that's beyond the scope of the documentation. Please ask your question on the #graphql or #pwa channel on the Engcomm Slack. [Sign up](https://opensource.magento.com/slack) here.
