### ISSUE TITLE
Move the Grunt documentation to its own page

### ISSUE THREAD

**Issue by erikhansen** [magento/devdocs#695]
Currently the Grunt documentation is buried in the "Styles debugging" page: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html#grunt_prereq A number of developers I've worked with have had a hard time finding this section, even after I tell them it is in DevDocs.

The "Installing and configuring Grunt" section and all content beneath it should be moved to its own page. I'd call it something like "Compile LESS with Grunt". So it would then display like this (mocked this up in Chrome DevTools):

![15-06-21 styles debugging-bu8zu](https://cloud.githubusercontent.com/assets/129031/15588414/6d16fb04-2353-11e6-8549-9125cf86270b.png)

**Comment by almarchenko** [comment]
Hi @erikhansen 
Your suggestion totally makes sense! The internal issue MAGETWO-53780 was created

**Comment by erikhansen** [comment]
@almarchenko Great, thanks!

**Comment by almarchenko** [comment]
@erikhansen We've made it a separate topic
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html

(I didn't rename the file itself this time, to avoid issues with re-addressing, but will do eventually)

**Comment by erikhansen** [comment]
@almarchenko Looks great! Thanks for being so responsive to community feedback.
