### ISSUE TITLE
Need more examples for utilizing custom cache type

### ISSUE THREAD

**Issue by dsmithhayes** [magento/devdocs#6970]
# General issue

## Description:

Lack of examples on how to utilize the custom Cache Type.

## Possible solutions:

Include an example class (Repository, Model, Block, etc) that utilizes the new Cache Type. Examples may include how to save, how to load, how cleaning works, and how to remove the data from the cache.

Also, it may be valuable to show how a cache type can save/load/clean/remove multiple pieces of uniquely identifiable data.

## Additional information:

This will be beneficial for all developing coming to the documentation to learn how to create and utilize custom Cache types for their own modules.

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
