### ISSUE TITLE
Install JDK on Ubuntu instructions do not work

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#6972]
# Bug report

## Description

In the Install and configure Elasticsearch topic, the instructions for [installing JDK on Ubuntu](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html#install-prereq-java-ubuntu) don't work.

### Steps to reproduce

1. Spin up an Ubuntu 18 VM.
1. Follow the [instructions](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html#install-prereq-java-ubuntu) in devdocs.

## Expected result

Ubuntu successfully installs JDK.

## Actual result

JDK does not install. See the following console output:

```
vagrant@ubuntu-bionic:~$ sudo apt install -y oracle-java8-installer
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate
```

## Possible solutions

This is a great example of the perils of documenting instructions for third-party packages when linking to the third party's documentation would be safer.

Remove the instructions from devdocs and update the link to Oracle's documentation to point here: https://docs.oracle.com/javase/8/docs/technotes/guides/install/linux_jdk.html#BJFJJEFG.

## Additional information

- This issue was originally reported in Hotjar (ID `#9904`). 
- The Hotjar feedback provides a link to more information here: http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

**Comment by jeff-matthews** [comment]
Using this command appears to install JDK, but I haven't tested it with the entire Elasticsearch setup instructions for Magento.

```
sudo apt install default-jdk
```

**Comment by milindsingh** [comment]
WebUpd8 team's PPA has been discontinued effective from April 16, 2019. Thus this PPA doesn't have any Java files. More information can be found on PPA's page on Launchpad. Hence this method no longer works and exists because of historical reasons.

Reference:
https://launchpad.net/~webupd8team/+archive/ubuntu/java

I can update the doc with default-sdk (open-jdk) command.

**Comment by jeff-matthews** [comment]
Sounds good. Thanks @milindsingh.
