### ISSUE TITLE
Magento 2.3 (&2.2) Set up multiple websites, stores, and store views in the Admin

### ISSUE THREAD

**Issue by Giuliano69** [magento/devdocs#7007]
# Bug report
typo from old version  in  "Step 7: Change the default store view base URL"
## Description
at point  5 ,  a  wrong domain name is given in the URL
`“Enter the **http://mysite.mg** URL in the Base URL and Base Link URL fields.”`
The given domain name mysite.mg has no relation with the current example (magento.mg)
It is perhaps a typo from a 1.x realese....

### Steps to reproduce

1. First Step
1. Second Step
1. Etc.

## Expected result
the URL should be http://www.magento.mg   (I suppose..)

## Additional information
May be the example could be given not only for stores in subdomains, but also for stores in different domain ?

**Comment by meker12** [comment]
@Giuliano69 Can you provide the link to the topic that requires update. Thanks!

**Comment by keharper** [comment]
It's https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_websites.html
