### ISSUE TITLE
Blackfire Cloud Integration page is missing

### ISSUE THREAD

**Issue by tonicc** [magento/devdocs#7032]
# Bug report

## Description

Blackfire Cloud documentation page is missing: https://devdocs.magento.com/cloud/project/project-integrate-blackfire.html

### Steps to reproduce

1. Access https://devdocs.magento.com/cloud/project/project-integrate-blackfire.html
2. You'll get HTTP 404 Page Not Found

## Expected result

1. Access https://devdocs.magento.com/cloud/project/project-integrate-blackfire.html
2. See the documentation to integrate Blackfire on a cloud project

**Comment by meker12** [comment]
Blackfire is no longer integrated with Magento Commerce Cloud. You can still use Blackfire.io with Magento projects, but you must have your own account and use the documentation provided by Blackfire. See the [Blackfire site](https://blackfire.io/magento) for information.
