### ISSUE TITLE
Feedback on page: /recommendations/install-configure.html

### ISSUE THREAD

**Issue by amarroni** [magento/devdocs#7033]
# General issue
Reviewing how to use this functionality I found link under configuration step not working. 

## Description:
Under the step **Configure Product Recommendations** the link to _specifying the API Key and selecting a SaaS Environment_ show Page not found.

## Possible solutions:
Update the link with the correct page path.

## Additional information:
Here is screenshot showing the URL path and "Page not found"

![image](https://user-images.githubusercontent.com/5198527/79244009-c53dd700-7e4c-11ea-98d1-e5cbba308a24.png)

**Comment by jeff-matthews** [comment]
Assigning to @erikmarr to investigate.

**Comment by amarroni** [comment]
Seen to be working right now the link!

Thank you! I'm closing the issue.
