### ISSUE TITLE
Magento cron documentation

### ISSUE THREAD

**Issue by dooblem** [magento/devdocs#705]
@davidalger and stevjohnson
 devdocs/_includes/config/setup-cron.md

Why are you advising to put php -c and the webserver php configuration ?

On standard Ubuntu / Debian install, the memory limit is even higher in cli configuration.

Removing -c works perfectly fine (at least on my system).

The problem with -c is that it's not including php conf.d directories (/etc/php/7.0/apache2/conf.d/).

I would advise the following:
 * make the doc simpler and remove -c in cron (in my point of view any critical config should go in Magento code)
 * or, if you really need an environment that is exactly the same as Apache, use the PHP_INI_SCAN_DIR envvar.

See bellow: as I have set the memory_limit in apache conf.d config files:
```
# test.php contains a phpinfo()

# calling as advised in the doc (wrong memory_limit)
php -c /etc/php/7.0/apache2/php.ini /tmp/test.php |grep -i -e php.ini -e scan -e memory_limit
Configuration File (php.ini) Path => /etc/php/7.0/cli
Loaded Configuration File => /etc/php/7.0/apache2/php.ini
Scan this dir for additional .ini files => /etc/php/7.0/cli/conf.d
memory_limit => 128M => 128M

# calling without -c (ok because memory_limit default for cli is higher)
php /tmp/test.php |grep -i -e php.ini -e scan -e memory_limit
Configuration File (php.ini) Path => /etc/php/7.0/cli
Loaded Configuration File => /etc/php/7.0/cli/php.ini
Scan this dir for additional .ini files => /etc/php/7.0/cli/conf.d
memory_limit => -1 => -1

# calling with PHP_INI_SCAN_DIR (environment "perfectly" identical to Apache)
PHP_INI_SCAN_DIR=/etc/php/7.0/apache2/conf.d/ php -c /etc/php/7.0/apache2/php.ini /tmp/test.php |grep -i -e php.ini -e scan -e memory_limit
Configuration File (php.ini) Path => /etc/php/7.0/cli
Loaded Configuration File => /etc/php/7.0/apache2/php.ini
Scan this dir for additional .ini files => /etc/php/7.0/apache2/conf.d/
memory_limit => 1G => 1G
PHP_INI_SCAN_DIR => /etc/php/7.0/apache2/conf.d/
$_SERVER['PHP_INI_SCAN_DIR'] => /etc/php/7.0/apache2/conf.d/
```

I may edit and submit a PR if you wish.

Thanks in advance,
Marc

**Comment by xcomSteveJohnson** [comment]
All of your examples are for PHP 7. Is it the same with earlier versions? When I installed PHP on Ubuntu and CentOS, I believe `memory_limit` was `128M` in `/etc/php.ini` (for CentOS).

I'll research why we recommend `-c` but I believe it's because the Setup Wizard needs to use the same settings as the CLI.

**Comment by dooblem** [comment]
Hello,
I think you do not have the case in CentOS because there is no conf.d directories. Am I right ?
Here is the behaviour on Debian 8 / PHP5.6.

The difference I see: In PHP7 php.ini directives seems to take priority over conf.d.

Anyway, I think this is not good to call php with -c only, because you may have half the config taken from /etc/php5/apache2/php.ini and half the config taken from /etc/php5/cli/conf.d.

```
root@magento2-demo:~# php -c /etc/php5/apache2/php.ini /tmp/test.php | grep -i -e php.ini -e scan -e memory_limit
Configuration File (php.ini) Path => /etc/php5/cli
Loaded Configuration File => /etc/php5/apache2/php.ini
Scan this dir for additional .ini files => /etc/php5/cli/conf.d
memory_limit => 1G => 1G

root@magento2-demo:~# php /tmp/test.php | grep -i -e php.ini -e scan -e memory_limit
Configuration File (php.ini) Path => /etc/php5/cli
Loaded Configuration File => /etc/php5/cli/php.ini
Scan this dir for additional .ini files => /etc/php5/cli/conf.d
memory_limit => 1G => 1G

root@magento2-demo:~# PHP_INI_SCAN_DIR=/etc/php5/apache2/conf.d/ php -c /etc/php5/apache2/php.ini /tmp/test.php | grep -i -e php.ini -e scan -e memory_limit
Configuration File (php.ini) Path => /etc/php5/cli
Loaded Configuration File => /etc/php5/apache2/php.ini
Scan this dir for additional .ini files => /etc/php5/apache2/conf.d/
memory_limit => 1G => 1G
PHP_INI_SCAN_DIR => /etc/php5/apache2/conf.d/
_SERVER["PHP_INI_SCAN_DIR"] => /etc/php5/apache2/conf.d/
```

**Comment by xcomSteveJohnson** [comment]
Update. The people who can help me with this are out of the office and we expect another Magento release soon so we'll update this issue in a week or so.

**Comment by davidalger** [comment]
@dooblem The -c was in there when I submitted a PR, so I left it in the example since that wasn't the change I was targeting. That said…I don't use the -c flag in environments I deploy. IMO the reason the -c flag was specified was because it's a "cheap" way of trying to ensure the documented practice doesn't cause problems due to differences in configuration between the CLI and php when run inside of web-services. It won't work in all cases, as you've discovered.

What I personally use on my production / stage env deployments is the following:

```
MAILTO="foo@example.com"

* * * * * cd /var/www/html/current && bin/magento cron:run | grep -v "Ran jobs by schedule" | tee -a var/log/magento.cron.log
* * * * * cd /var/www/html/current && bin/magento setup:cron:run | tee -a var/log/setup.cron.log
* * * * * cd /var/www/html/current && /usr/bin/php -f update/cron.php | tee -a var/log/update.cron.log
```

On the servers I'm deploying to, I don't usually setup a php-cli.ini file. If I do, it's usually to do something such as control stuff like memory limit on the CLI separately from the web-services, but this is one of the things that I'll eventually end up fine tuning after I've done a few more setups than I have already.

**Comment by xcomSteveJohnson** [comment]
We're still looking at this and hope to have an answer soon. Thanks.

**Comment by xcomSteveJohnson** [comment]
Thanks @dooblem for bringing this up and to @davidalger for the solution. Updated the [crontab topic](http://devdocs.magento.com/guides/v2.1/install-gde/install/post-install-config.html#post-install-cron) and the [PHP settings topics](http://devdocs.magento.com/guides/v2.1/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone) as follows:

*  Removed `-c` from crontab
*  Advised in both places to set PHP options the same in the web server and the command line configurations

If this resolution is satisfactory, please close this issue.

**Comment by xcomSteveJohnson** [comment]
@dooblem  Please let us know if you have additional feedback or concerns; otherwise, I expect to close this in the next week or so.

**Comment by dooblem** [comment]
Perfect for me. I think you can close.
