### ISSUE TITLE
Add note about recommendation to put site in main mode and disable cron

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#7051]
# General issue

It would be great to update https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-index.html with a notice saying that before switching indexer mode, it is recommended to put your website to the maintenance mode and disable cron. Doing so will ensure you don't have database locks. 

## Additional information:

Originally reported by @almarchenko. 

Please refer to @shiftedreality for tech review or more information.

**Comment by hostep** [comment]
@almarchenko: can you give a bit more information where this is coming from?

We are seeing this is becoming required after upgrading to 2.3.5 but we are not sure yet why this suddenly is changed (it wasn't needed in our case on 2.3.4 and lower)?

See https://magentocommeng.slack.com/archives/C4YS78WE6/p1587562804354300 for the full details
