### ISSUE TITLE
clarifications about filterProcessor when searching with repositories

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#7059]
# General issue
I think there needs to be a clarification about the different types of FilterProcessors in Magento 2 and their appropriate usage at: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/searching-with-repositories.html#filter-processor

## Description:

Currently there is only a generic paragraph about the FilterProcessors pointing to `Magento\Framework\Api\SearchCriteria\CollectionProcessor\FilterProcessor` but there is also the `Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor` 

Depending on your type of Entity you need to use the appropriate one or you get an error when trying to access the attribute when you use search criteria. 

The name is also misleading because in the example it's `FilterProcessor` and the one needed to make it work with EAV entities is `CollectionProcessor` 

## Possible solutions:

We could mention that if the developer is building an EAV Model and needs to implement the Repository::getList method, they should use the EAV Filter Processor instead otherwise the filters won't be added to the collection.

**Comment by dineshvb** [comment]
@magento I am working on this
