### ISSUE TITLE
Please Update PHP Ubuntu Page

### ISSUE THREAD

**Issue by deepanshu27193** [magento/devdocs#706]
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-php56-install-ubuntu

As i have old php5.5 installed from default ubuntu 14.04 archive but after following steps to upgrade php to 5.6 i came across a situation that "this ppa of php5.6 will be deprecated in end of june please change it to ppa:ondrej/php ".

and now also i have problem of clash between previously installed php5.5 and newly installed php5.6.

So, please have a look on this issue and update the instruction with up to date method and if possible help regarding this php merging issue.

**Comment by xcomSteveJohnson** [comment]
We can't help with the PHP merge issue but I have a question for you. The `mcrypt` and `mhash` extensions aren't in `ppa:ondrej/php`. `mhash` is supposedly in `php-common` and I used `php5-mcrypt`, which installs a PHP 5.4 version. Do you know if that works with Magento?

**Comment by xcomSteveJohnson** [comment]
@deepanshu27193  Updated, please check and close this if you're satisfied.

**Comment by xcomSteveJohnson** [comment]
Update?

**Comment by deepanshu27193** [comment]
First of all sorry for the late reply, as far as my concern i haven't came across with any problem, so i can say that there will be no issues regarding mcrypt and mhash, and it will work fine with magento 2.0.x.
