### ISSUE TITLE
Broken link on Installation roadmap (reference) page

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/devdocs#707]
Hi,

On following page [http://devdocs.magento.com/guides/v2.0/install-gde/install-roadmap_part1.html](url)

_Deploy Magento to production_ link redirects to a 404 page.

**Comment by xcomSteveJohnson** [comment]
Sorry about that. I believe it's fixed now; if so, please close this issue.

**Comment by tiwarimukesh** [comment]
@xcomSteveJohnson 
Still getting  404 page

**Comment by xcomSteveJohnson** [comment]
Try [this link](http://devdocs.magento.com/guides/v2.0/howdoi/deploy/deploy-to-prod.html). The link in your original comment doesn't work.

**Comment by tiwarimukesh** [comment]
Hi @xcomSteveJohnson 

The link you mentioned is working but could you fix it for http://devdocs.magento.com/guides/v2.0/install-gde/install-roadmap_part1.html url , "Deploy to production" section

Thanks

**Comment by xcomSteveJohnson** [comment]
So sorry! Fixed now (really)!

**Comment by tiwarimukesh** [comment]
Hi @xcomSteveJohnson 

It is working now.
