### ISSUE TITLE
Correction for Accessing js resources in JavaScript resources in Magento

### ISSUE THREAD

**Issue by Januszpl** [magento/devdocs#7092]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/js-resources.html#accessing-js-resources

## Description

Example nr 2 in Accessing js resources need to be corrected as it is wrong.

## Possible solutions

**Replace this:**
> File actual location: app/design/frontend/Magento/blank/Magento_Theme/web/js/theme.js
> File published to pub/static: pub/static/frontend/Magento/\<theme>/\<locale>/js/theme.js
> Called in script:

> `require(["js/theme"], function(){`
> `});`

**With:**
> File actual location: app/design/frontend/Magento/blank/Magento_Theme/web/js/theme.js
> File published to pub/static: pub/static/frontend/Magento/\<theme>/\<locale>/Magento_Theme/js/theme.js
> Called in script:

> `require(["Magento_Theme/js/theme"], function(){`
> `});`

Changed path in "File published to..." and path to file in require dependency array.

**OR:**
perhaps better provide example from "[theme]/web/js"

> File actual location: app/design/frontend/Magento/blank/web/js/navigation-menu.js
> File published to pub/static: pub/static/frontend/Magento/\<theme>/\<locale>/js/navigation-menu.js
> Called in script:

> `require(["js/navigation-menu"], function(){`
> `});`

## Additional information

Probably mistake was made because of code from adminhtml area, where I see some "define" for "theme/js" but we don't have anything like that in frontend area.

**Comment by atwixfirster** [comment]
Good catch , @Januszpl !

**fixed** in https://github.com/magento/devdocs/pull/7097

Thank you!
