### ISSUE TITLE
UI Library docs

### ISSUE THREAD

**Issue by slackerzz** [magento/devdocs#711]
In the [official documentation](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/theme-ui-lib.html#docs) there is a links to https://github.com/magento/magento2/blob/2.0/lib/web/css/docs/source/README.md as UI Library documentation but it is a code style guide rather that documenting the UI Library

**Comment by almarchenko** [comment]
Hi @slackerzz 
You are write, and our doc states the same "lib/web/css/docs/source/README.md: describes the Magento UI library structure, naming conventions, and code style."
And it is a part of UI library documentation. 
You can create a PR suggesting wording change if you think the current text is not correct.
Thank you.

**Comment by slackerzz** [comment]
It's not a problem of wording, the point is that there is no documentations for the UI Library, code style docs are not so useful. It's hard to use it without docs and with [broken](https://github.com/magento/magento2/issues/4770) examples

**Comment by almarchenko** [comment]
Did you try the documentation available in the HTML view in the following location in your Magento installation: pub/static/frontend/Magento/blank/en_US/css/docs/index.html ? 
We are sorry that there's an issue with those example.

**Comment by almarchenko** [comment]
Closing as no response for a couple of months.
