### ISSUE TITLE
add an EOL table for community versions?

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#7110]
# New feature request
Is it possible to add a section to the devdocs about support and updates and EOL for each magento 2 version? 

## Description

I would like to see a table stating the various versions from 2.0 to 2.3 and the creation date / EOL date. I wasn't able to find it by searching the devdocs. It could be a part of the update guide perhaps?

## Expected result

Developers would be easily able to see when they should schedule upgrades to major versions in a centralized place

## Benefits

Developers won't have to search the internet for information and it's easy to point the merchants to the docs and tell them here's why you should update.

**Comment by jeff-matthews** [comment]
Hi @ioweb-gr,

I recommend bookmarking this link: https://magento.com/sites/default/files/magento-software-lifecycle-policy.pdf

It describes the lifecycle for Magento release lines. There's a link to that document at the bottom of this devdocs page: https://devdocs.magento.com/release/policy/.

We also have this page on devdocs: https://devdocs.magento.com/release/.

It contains a [Patch schedule](https://devdocs.magento.com/release/#patch-schedule) that you may find useful.

**Comment by BarnyShergold** [comment]
@shrielenee - I think this issue can be closed as Jeff showed the issue raiser where to find the information - do you concur?
