### ISSUE TITLE
Document Elasticsearch 7 Suppport Feedback on page: /cloud/project/project-conf-files_services.html

### ISSUE THREAD

**Issue by mpchadwick** [magento/devdocs#7114]
# General issue

## Description:

Elasticsearch 7 support was added in Magento 2.3.5. Currently it is not documented that ES7 is supported, nor which specific 7.X version is supported.

https://github.com/magento/devdocs/blame/c816c89fd607c211e0359d901adcc82273be857f/src/cloud/project/project-conf-files_services.md#L164

## Possible solutions:

Update file to clarify.

## Additional information:

N/A

**Comment by mpchadwick** [comment]
Also here: https://devdocs.magento.com/cloud/project/project-conf-files_services-elastic.html

**Comment by jeff-matthews** [comment]
We updated the system requirements here: https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#technologies-magento-can-use.

I suppose the cloud docs need an update as well @meker12.
