### ISSUE TITLE
"Javascript Component" is Never Defined

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#712]
This page

http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js_init.html

> This topic talks about how to initialize a JavaScript component in the Magento 2 application. It covers initializing JavaScript components

never defines what, exactly, a Javascript "component" is.  

- Javascript has no native concept of "components".  

- The document appears to define a special way of including in a RequireJS module, but the use of the word component implies there are other things happening

- The document also talks about extra things that aren't supported by plain RequireJS modules (*the initializer passes the config and element values to this function. For example:*)

So, while a good first draft, the lack of a clear definition of what Magento (or a Magento core developer) considers a components makes this page more confusing than helpful.  The original, or a new, SME should be found the the page should be fleshed out, or a preliminary article describing components should be included. (to preempt the usual next question -- if I knew what should be on the page, I would be reporting it as an issue)

**Comment by almarchenko** [comment]
@astorm  thank you for the feedback!
I created the internal issue MAGETWO-54203 to elaborate the topic.

**Comment by almarchenko** [comment]
@astorm  "JS component" term in defined here http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/bk-javascript-dev-guide.html#js_terms 
I've added a link to the definitions in JS initialiation topic

**Comment by astorm** [comment]
@almarchenko  Thank you!  It seems small, but it's an important distinction that makes things clearer for folks coming cold into Magento's javascript systems!
