### ISSUE TITLE
Web Services Mapping from Magento 1 to 2

### ISSUE THREAD

**Issue by aboelmor** [magento/devdocs#714]
Dear all,

I have the following used web services in Magento 1 which I would like to define their corresponding services in Magento 2:

catalogProductInfo
catalogProductList
customerAddressCreate
customerAddressDelete
customerAddressInfo
customerAddressList
customerAddressUpdate
customerCustomerCreate
customerCustomerInfo
customerCustomerUpdate
login
shoppingCartCouponAdd
shoppingCartCouponRemove
shoppingCartCreate
shoppingCartCustomerAddresses
shoppingCartCustomerSet
shoppingCartInfo
shoppingCartPaymentMethod
shoppingCartProductAdd
shoppingCartProductList
shoppingCartProductMoveToCustomerQuote
shoppingCartProductRemove
shoppingCartProductUpdate
shoppingCartTotals
catalogProductAttributeMediaList
catalogProductLinkList
customerCustomerList
catalogCategoryInfo
catalogCategoryTree
shoppingCartSetStore
shoppingCartShippingMethod
shoppingCartPaymentList
shoppingCartOrder
salesOrderCancel
storeInfo
SalesOrderAddComment

I would appreciate if someone can help me with the mapping

Best Regards

**Comment by xcomSteveJohnson** [comment]
We suggest putting this request on [community.magento.com](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2). Our intent with Magento 2 APIs was to start fresh and not try to base them on Magento 1 APIs. We think the community should drive this mapping.

**Comment by aboelmor** [comment]
Hi Steve, You can't start fresh if you already have a platform of users using Magento 1 services !! You can't let the user take the extra mile alone without help.
Anyway, I will try the community; in addition, I already started the mapping myself and did most of the work but I needed somebody to show me interest in this matter since not all services are clear for now.

**Comment by keharper** [comment]
We've looked into the possibility of adding mappings as part of the Code Migration Tool, but that idea did not gain any support internally. As Steve (now user ghost) said, we want developers to approach developing in 2.x from a fresh perspective, so we have to politely decline the request.
