### ISSUE TITLE
Clarification on Varnish supported versions 

### ISSUE THREAD

**Issue by chris-brabender** [magento/devdocs#7142]
# General issue

Varnish support is unclear / defines an unsupported Varnish version
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

## Description:

The definition of Varnish support is not entirely clear between the technology stack requirements page, where Varnish support is listed as 4.x, 5.2 and 6.2 versus the [Varnish configuration page](https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish.html) where varnish support is listed as 4.x, 5.x and 6.x.

As Varnish 6.2 is no longer supported, can we get confirmation that the 6.x versioning is relevant and we can upgrade to Varnish version 6.4.x?

## Possible solutions:

Add Varnish 6.x compatibility to Magento for non-end of life Varnish versions.

## Additional information:

Varnish versioning information - https://varnish-cache.org/releases/index.html

**Comment by chris-brabender** [comment]
The 2.3.3 release notes dictate only 6.2.0 as supported - https://devdocs-beta.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-commerce.html#platform-upgrades

**Comment by keharper** [comment]
@chernenm What versions of Varnish are supported in 2.3.5?

**Comment by chernenm** [comment]
hi @keharper , we can say 6.x is supported and tested with 6.3.1
