### ISSUE TITLE
Markdown links in tables must be converted to HTML links

### ISSUE THREAD

**Issue by Tazaf** [magento/devdocs#7168]
# General issue

## Description:

Markdown links markup seems to not be converted correctly when in tables (see following excerpt of the page):

![image](https://user-images.githubusercontent.com/7702322/81269334-73eac700-9049-11ea-8d95-f6df991f6bc3.png)

**Comment by dobooth** [comment]
markdown links within HTML tables will not get converted. Need to make the link HTML.

**Comment by bdenham** [comment]
Hey @Tazaf, thanks for reporting this.
