### ISSUE TITLE
Release Candidate 2 Page Contains Installation Instructions for RC1?

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#717]
The following page's title indicates its for the second release canidate

http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC2CE.html

However, the composer instructions reference the `2.1.0-rc1` package

    composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.1.0-rc1 <installation directory name>

and makes reference to the Magento RC1 in several other places.

Is the `2.1.0-rc1` package the up to date one?  Or should that be `2.1.0-rc2`?  Or something else.

**Comment by jfrontain** [comment]
Hi Alan, thanks for catching these errors. I've fixed the installation instructions as needed in the RC2 CE and EE notes, and republished. As always, your eagle eyes are welcome.
