### ISSUE TITLE
Feedback on page: /guides/v2.3/javascript-dev-guide/javascript/js-resources.html

### ISSUE THREAD

**Issue by Tazaf** [magento/devdocs#7182]
# General issue

## Description:

In the **JS resources location** section, some list items have a word surrounded by brackets (see following screenshot).

![image](https://user-images.githubusercontent.com/7702322/81397526-d1eddc00-9127-11ea-81dc-553057770b4c.png)

I suppose it was intended as a link markup but someone forgot to put the actual link after?

**Comment by atwixfirster** [comment]
> I suppose it was intended as a link markup but someone forgot to put the actual link after?

Looks like yes.

Fixed in https://github.com/magento/devdocs/pull/7187

Thanks for reporting , @Tazaf
