### ISSUE TITLE
Contributions may be missing after DevDocs redesign

### ISSUE THREAD

**Issue by VenkataRamanaGandham** [magento/devdocs#7189]
# General issue

## Description:

My contribution is listed earlier on devdocs, after revamp of the design, my contribution is missing in. :
https://github.com/magento/devdocs/graphs/contributors

My Contribution PR:
https://github.com/magento/devdocs/pull/7150

Contribution link:
https://devdocs.magento.com/guides/v2.3/graphql/mutations/update-customer-address.html

**Comment by hellotaran** [comment]
@VenkataRamanaGandham What issue do you see? You contribution "," is there on the doc page. If you are looking for your name in the contributor list then it will show up if you fall under top 100. The list you are looking at is for top 100 contributors.

**Comment by BarnyShergold** [comment]
Issue raiser is looking in the wrong location for contributions. The correct location : https://opensource.magento.com/profile/VenkataRamanaGandham/contribution_statistic

Pull request 7150 can be seen on May's statistics
