### ISSUE TITLE
JavaScript testing documentation is incomplete

### ISSUE THREAD

**Issue by Vinai** [magento/devdocs#719]
The page https://github.com/magento/devdocs/blob/2.0/guides/v2.0/extension-dev-guide/test/test_js-unit.md only covers using the old qunit/JsTestDriver based tests found in the directory `dev/tests/js/JsTestDriver`.  

It does not cover the jasmine/grunt based tests found in `dev/tests/js/jasmine`, even though they are newer and easier read, write and execute.

Links to the documentation of the associated projects should be added:
- [JsTestDriver download](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/js-test-driver/JsTestDriver-1.3.5.jar)
- [JsTestDriver getting started](https://code.google.com/archive/p/js-test-driver/wikis/GettingStarted.wiki)
- [qunit](https://qunitjs.com/) (It probably should also be mentioned that the version of qunit is 1.14, not the newer 2.0)
- [jasmine](http://jasmine.github.io/2.0/introduction.html)

**Comment by xcomSteveJohnson** [comment]
@Vinai Any chance you can help with this?

**Comment by Vinai** [comment]
Currently too busy to commit, but generally I'd be happy to.

**Comment by dshevtsov** [comment]
an internal issue created: MAGETWO-60308

**Comment by dshevtsov** [comment]
Added a new topic - [JavaScript Unit Testing with Jasmin](http://devdocs.magento.com/guides/v2.0/test/js/jasmine.html)
@Vinai what do you think?

**Comment by dshevtsov** [comment]
@Vinai I'm closing the issue, but if you have any feedback, you are welcome to comment it at any time.

**Comment by Vinai** [comment]
Hey, sorry I missed your comment and the "Waiting for response" label"
Thanks for the update, it looks great! Last time I tried to use the jasmin tests, it failed because of broken tests in the core. I'll it out again soon and should there be issues you'll hear from me 👍 
Thank you very much for the documentation!
