### ISSUE TITLE
 Greek language pack for the administrator Options

### ISSUE THREAD

**Issue by vagdou** [magento/devdocs#722]
Hi,

There Greek language pack for the administrator of magento 2.0.7 Connunity?

Yours sincerely

Vag dou

**Comment by xcomSteveJohnson** [comment]
Suggest you ask in the [crowdin discussion](https://crowdin.com/project/magento-2)

**Comment by vagdou** [comment]
Ok, Thank you very much!

**Comment by xcomSteveJohnson** [comment]
Closing
