### ISSUE TITLE
Enterprise/Commerce Support Site not working

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#7251]
# Bug report

## Description

Sorry, not sure where to post this issue. 
I want to notify you, that the support site is not working.

### Steps to reproduce

1. Login to your magento account.

2. Open Support site:
https://support.magento.com/hc/en-us/requests/new

Try to submit a ticket.

## Expected result

Everything works

**Comment by meker12** [comment]
@Eddcapone can you be more specific about what's not working.  We'll tag our Magento KB team in this ticket for follow up. 

If you don't see a "Submit a ticket" link, there is an article about that in the Magento Help Center:
[Submit a ticket link not displayed](https://support.magento.com/hc/en-us/articles/360020597871)

@almarchenko

**Comment by Eddcapone** [comment]
The site was just not loading. White screen.
