### ISSUE TITLE
Technical error with code example in Widget Media Uploader

### ISSUE THREAD

**Issue by palomaEcommistry** [magento/devdocs#7260]
# General issue

https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget-media-uploader.html

## Description:

I tried to replicate this on my local environment and it gives me an error:
`A technical problem with the server created an error. Try again to continue what you were doing`

I copied the HTML and JS exactly as they are in the explanation on my phtml file.

Is there a way to fix this? 
Or how should it be implemented for a widget?
Thanks

**Comment by dobooth** [comment]
Hey @serhiyzhovnir Can you see anything amiss here?

**Comment by shrielenee** [comment]
This has seen no progress for months. @serhiyzhovnir if you wanna grab this again please do! You were removed as assignee for now.

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by sathiyaaa** [comment]
Hello @palomaEcommistry , I tried the above code and implemented the widget and it seems to be working fine for all of PNG, JPEG and JPG formats. I have attached the screenshot for your reference. 
![rsz_widget](https://user-images.githubusercontent.com/50226394/99552480-0e599900-29e3-11eb-839b-c946adf5e5ae.png)

**Comment by sathiyaaa** [comment]
The documentation covers only the JS and phtml part whereas the other files required for setting up a widget programmatically (widget.xml, block files) are missing.

**Comment by sathiyaaa** [comment]
@shrielenee Thoughts?

**Comment by shrielenee** [comment]
Yes @sathiyaaa! Please add any information about files that are not covered in the documentation currently and submit a PR. Don't forget to tag this issue in it so they are linked. 🙇‍♀️

**Comment by hguthrie** [comment]
@sathiyaaa Are you still working on this?

**Comment by dshevtsov** [comment]
The topic was migrated to <https://developer.adobe.com/commerce/frontend-core/javascript/jquery-widgets/media-uploader/>.
If the issue is still relevant, feel free to reopen it in <https://github.com/AdobeDocs/commerce-frontend-core/issues>.
