### ISSUE TITLE
Dead links on the Code Contributions page

### ISSUE THREAD

**Issue by nazaridak** [magento/devdocs#7274]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#combine-pr

## Description
When I researched the Code Contributions page I found several dead links on this page - https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#combine-pr.

For instance:
"To combine pull requests, a member of the [Community Maintainers](https://github.com/orgs/magento/teams/open-source-maintainers/members) or [Magento EngCom Team](https://github.com/orgs/magento/teams/core-maintainers/members) under the ..."

## Possible solutions
Edit the information to the correct links.

[Magento EngCom Team]
**from** https://github.com/orgs/magento/teams/core-maintainers/members
**to**
need specify

## Additional information
Also, I think this issue can be on other pages.

**Comment by nazaridak** [comment]
@magento I am working on this

**Comment by nazaridak** [comment]
Also,
if I'm not member of Magento Community Maintainers this https://github.com/orgs/magento/teams/open-source-maintainers/members link shows me 404 pages.

![image](https://user-images.githubusercontent.com/43548684/82807939-83fc0680-9e91-11ea-8747-34c357aeb567.png)

If I read this info the first time and I'm not familiar with the contribution this error confusing me.

**Comment by dobooth** [comment]
Pinged @okorshenko to get the proper EngCom link.

**Comment by manish-sp** [comment]
@magento I am working on this

**Comment by manishmittalm** [comment]
@magento I am working on this

**Comment by manishmittalm** [comment]
Fixes: #7432
