### ISSUE TITLE
Need to clarify workflow for deploying static assets to production

### ISSUE THREAD

**Issue by vlmironov** [magento/devdocs#7297]
# General issue

## Description:

https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/

The Build System description is confusing.
This sentence: **"One system on which you deploy static assets and compile code for your production system."** doesn't make whole lot of sense because once you move the built assets to production environment you will need to flip magento to Production mode, what will in its turn trigger the compilation process and static assets deployment again.
If you decide to switch the mode to Production on your build server - you will have to run magento install/upgrade CLI command (which requires Db connection), otherwise the 'deploy' tooling is not available:

![image](https://user-images.githubusercontent.com/51212485/83065212-1ab2f980-a031-11ea-917e-1cab466a6583.png)

**Comment by hostep** [comment]
@vlmironov: you can execute: `bin/magento deploy:mode:set --skip-compilation`, the `--skip-compilation` flag will skip the static assets generation and the compilation process. This is probably what you are searching for?

**Comment by BarnyShergold** [comment]
@hostep @vlmironov Hostep's comment seems to answer the issue. Is there any reason why we cant' close this issue?

**Comment by BarnyShergold** [comment]
@shrielenee - Can we close this ticket? Any reason not to?

**Comment by BarnyShergold** [comment]
@shrielenee - I would argue that the documentation is deliberately high level as the following statement is made in the assumptions - "An experienced system integrator with excellent knowledge of Magento configuration options."

If you don't know about what hostep mentioned, you probably are not experienced enough and should leave well alone. A little knowledge is a dangerous thing! I believe the page is for describing how Pipeline works not how to make it work.

Rebuttal? 😄

**Comment by shrielenee** [comment]
No rebuttal at all @BarnyShergold --- That was my general feeling about what info we should include. The scope and audience of each topic is not always designed for explicit instructions on every little thing. This can be closed in my opinion!

**Comment by BarnyShergold** [comment]
Closing issue due to discussion above
