### ISSUE TITLE
Elasticsearch link broken

### ISSUE THREAD

**Issue by avoelkl** [magento/devdocs#731]
Hi,

The "More information about Elasticsearch" link on this page is broken:
http://devdocs.magento.com/guides/v2.0/cloud/project/project-conf-files_services-elastic.html

Instead of http://devdocs.magento.com/guides/v2.1/config-guide/elasticsearch/es-overview.html it links to http://devdocs.magento.com/guides/v2.0/config-guide/elasticsearch/es-overview.html

I'm not quite sure how the link generation works `[More information about Elasticsearch]({{ site.gdeurl }}config-guide/elasticsearch/es-overview.html).` thus the issue :-)

**Comment by xcomSteveJohnson** [comment]
Sorry about that. Fixed now. Please check and close this issue if it resolves the problem.

**Comment by avoelkl** [comment]
Hi,
Thanks, works now :)
