### ISSUE TITLE
Search Criteria documentation incorrect for "And" scenario

### ISSUE THREAD

**Issue by christopherbradbury** [magento/devdocs#732]
#### Re:
http://devdocs.magento.com/guides/v2.1/howdoi/webapi/search-criteria.html

Section for "The following example searches for products whose attributes are size=Large <strong>AND</strong> color=Red." (emphasis mine)
```
GET http://<magento_host>/rest/V1/products?`
searchCriteria[filter_groups][0][filters][0][field]=size&
searchCriteria[filter_groups][0][filters][0][value]=Large&
searchCriteria[filter_groups][0][filters][0][condition_type]=eq&
searchCriteria[filter_groups][0][filters][1][field]=color&
searchCriteria[filter_groups][0][filters][1][value]=Red&
searchCriteria[filter_groups][0][filters][1][condition_type]=eq
```

#### Version
Magento 2.1.0

#### Issue/Question

We are using Magento 2.1.0, and best I can tell, the above example does not result in an AND condition, but an OR condition.  That is, it would return products that are size=Large <strong>OR</strong> color=Red.

I think for an and scenario, this is what is needed, or at least what seems to work (note the use of the first index spot, for `[filter_groups]`:
```
GET http://<magento_host>/rest/V1/products?`
searchCriteria[filter_groups][0][filters][0][field]=size&
searchCriteria[filter_groups][0][filters][0][value]=Large&
searchCriteria[filter_groups][0][filters][0][condition_type]=eq&
searchCriteria[filter_groups][1][filters][0][field]=color&
searchCriteria[filter_groups][1][filters][0][value]=Red&
searchCriteria[filter_groups][1][filters][0][condition_type]=eq
```

Am I misunderstanding or missing anything?  Could you confirm either an error in the documentation or a bug? I am finding limited help on this elsewhere. Thank you.

**Comment by keharper** [comment]
@christopherbradbury You are correct, and it's a documentation bug. The filters within a filter_groups are logically OR'd. The filter_groups logically AND'd. This is internal issue MAGETWO-50587, and I'll correct the documentation this week

**Comment by christopherbradbury** [comment]
@keharper Thank you for the reply/clarification!

**Comment by keharper** [comment]
@christopherbradbury  I've posted the updates to the searchCriteria article. Let me know what you think.

**Comment by christopherbradbury** [comment]
👍 
Thank you for updating that!

**Comment by keharper** [comment]
Glad you liked it. I'll close this issue. Feel free to reopen if you see any errors or need more clarification.
