### ISSUE TITLE
Link Snapshop article with Cloud Role article

### ISSUE THREAD

**Issue by gideon-magento** [magento/devdocs#7325]
# Topic clarification/correction request

## Description

The Snapshots documentation should be updated to include that only Admin and Super Users  have the rights to create Snapshots. The docs probably should link to each other as well.
https://devdocs.magento.com/cloud/project/project-webint-snap.html
https://devdocs.magento.com/cloud/project/user-admin.html#cloud-role-project

**Comment by dobooth** [comment]
Sound correct, @hguthrie ?

**Comment by manishmittalm** [comment]
@gideon-magento are you looking to add this note "Admin and Super Users have the rights to create Snapshots." in document is it? and where are you suggesting to add this link to https://devdocs.magento.com/cloud/project/user-admin.html#cloud-role-project

Please specify.

**Comment by gideon-magento** [comment]
The first bullet point already mentions that Super Users have the rights to create snapshots.

The Super user role grants administrator access to all environments. They can change settings and execute actions on any environment, including creating and restoring snapshots.

The word ‘snapshot’ should probably link to the Snapshots article. https://devdocs.magento.com/cloud/project/project-webint-snap.html

Gideon Amparo  | Technical Support Engineer |  Adobe  |  gamparo@adobe.com<mailto:gamparo@adobe.com>

**Comment by manishmittalm** [comment]
@magento I am working on this.

**Comment by manishmittalm** [comment]
This is pending from reviewer now, I have shared already fix for this in 2.4-manish-develop branch.

**Comment by manishmittalm** [comment]
Fixed, closing this issue.
