### ISSUE TITLE
question regarding page: guides/v2.4/release-notes/release-notes-2-4-0-open-source.html

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#7332]
## Description

https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html#frameworks
> Non-cacheable blocks are no longer added to default layout handles. Adding non-cacheable blocks to default layout handlers renders all Magento pages non-cacheable. This results from the layout generation process: During layout generation, Magento collects all available layout handles for a particular page and merges instructions from them into the page’s final layout structure. The default layout handle is used as a basic handle for every page. As a result, layout updates that are declared for the default handler appear on every Magento page. GitHub-9041

Linked issue and PR seem to be closed, is there a link to commits available for this change? It is not clear how does the behavior change, and it sounds like a backward-incompatible change.

**Comment by jfrontain** [comment]
@korostii, thanks for the feedback. I'm researching this right now.

**Comment by hostep** [comment]
@korostii, there's this hidden feature of the release notes which links the Magento internal ticket number to an entry in the release notes, if you take a look at the html source code, you'll see this. In this case the internal ticket number is `MC-31729`.

If I then search the git commits on the `2.4-develop` branch using something like `git log origin/2.4-develop --grep 'MC-31729'`, I find a bunch of commits, and the last commit seems to be the merge commit for that issue which is: https://github.com/magento/magento2/commit/dcaee490a450264078bbb7d173b8b5ddce114b88

Is this enough information for you?

**Comment by shrielenee** [comment]
Hey @korostii @jfrontain is this still in progress?

**Comment by jfrontain** [comment]
Hi @korostii, I believe that we updated the release notes a couple of months ago, and I forgot to close this issue. Closing now.
