### ISSUE TITLE
Feedback on page: /guides/v2.4/release-notes/release-notes-2-4-0-open-source.html

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/devdocs#7333]
# General issue

Duplicate sentence on release-notes-2-4-0-open-source

## Description:

Duplicate sentence

## Possible solutions:

Remove duplicate sentance:
```
We have improved the performance of indexer_update_all_views. Indexing is now faster, inactive rules are no longer processed, and caches are cleared of entries for only changed products.
```

**Comment by jfrontain** [comment]
Thanks, @PascalBrouwers. I've entered this change in both versions of the notes while making other edits.
