### ISSUE TITLE
Feedback on page: /guides/v2.4/release-notes/release-notes-2-4-0-open-source.html

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/devdocs#7334]
# General issue

Typo on release-notes-2-4-0-open-source.
"JavaScript magnification" should be: "JavaScript minification"

## Description:

Under the section Backend is a typo:
```
can now be previewed from the Admin when JavaScript magnification is enabled
```

## Possible solutions:

replace `magnification` with `minification`

**Comment by jfrontain** [comment]
Thanks, @PascalBrouwers -- really glad you caught that. I've entered the change while making other changes to these files. Thanks again.
