### ISSUE TITLE
404 for indexing link

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#734]
On the page http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-index.html, the link for "More information about Indexing" (http://devdocs.magento.com/guides/v2.1/architecture/index-cache/indexing.html) returns a 404

**Comment by xcomSteveJohnson** [comment]
Fixed now. Please verify and close this issue.

**Comment by dougkm** [comment]
verified
