### ISSUE TITLE
Magento 2.1 documentation

### ISSUE THREAD

**Issue by LittleCamel** [magento/devdocs#735]
Documentation need updates for Magento v2.1. For example: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-apply.html to apply theme and add a design exception in Admin now you have to go to Content->Configuration and then from table select where you want to apply the theme.

**Comment by almarchenko** [comment]
@LittleCamel Thanks!
The topic for v 2.0 was published for 2.1 by mistake. I'll correct asap.

**Comment by almarchenko** [comment]
@LittleCamel I've fixed the problem, 
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html 
Thank you again for reporting, can we close the issue?

**Comment by LittleCamel** [comment]
Yes, you can close this issue.
Thank you!
