### ISSUE TITLE
404 on Magento EE Backwards Comp Link

### ISSUE THREAD

**Issue by brobie** [magento/devdocs#736]
From this page: http://devdocs.magento.com/guides/v2.1/release-notes/changes_2.0.html

When clicking on the link for: Magento EE backward incompatible changes

404 happens.

**Comment by xcomSteveJohnson** [comment]
This is a strange side effect of using Jekyll. After initially publishing 2.1 documentation, I removed the `changes_2.0.html` page from the source; however, the HTML page that Jekyll created is still there.

When you go to the [2.1 Release Notes home page](http://devdocs.magento.com/guides/v2.1/release-notes/bk-release-notes.html), you don't see that same link.

There's no easy way to clean these old HTML pages so I'll leave this issue open for others to see then eventually close it.

**Comment by xcomSteveJohnson** [comment]
I was incorrect that deleting HTML files breaks the publication process. I deleted the HTML file you mentioned, so now you'll get a 404 if you try to go to that page.

Please verify and close.

**Comment by xcomSteveJohnson** [comment]
Please let us know if you still have concerns. I expect to close this in the next week or so otherwise.

**Comment by xcomSteveJohnson** [comment]
Closing.
