### ISSUE TITLE
The URL for the website uses http instead of https

### ISSUE THREAD

**Issue by ksaandev** [magento/devdocs#7361]
# Bug report

## Description

Github repository magento/devdocs provides a link to website using http

## Possible solutions

Replace link with https, it's 2020 it's better to be secure 😄 

## Additional information

HTTP redirects to HTTPS on magento/devdocs so visitors are secured, but it's even better for the image to use http instead of https

**Comment by ksaandev** [comment]
Screenshot
<img width="1040" alt="Capture d’écran 2020-06-06 à 22 53 04" src="https://user-images.githubusercontent.com/65755110/83954368-c4bc2e00-a848-11ea-89d3-b033e981a67a.png">

**Comment by dobooth** [comment]
Fixed! Thanks for the sharp eye, @ksaandev.
