### ISSUE TITLE
GraphQL: Add support for gift messages

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7363]
# Community engineering issue

Type of Doc:

-  [ ] New topic
-  [x] Topic Update, Devdoc link: multiple
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28519

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/28072

Magento 2 version:

-  [x] 2.4.1

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

This issue provides an overview of the GraphQL documentation changes required to support gift messages. Additional work might be required.

* Update the `storeConfig` query to include new fields
* Potentially update any mutation that adds items to a cart or updates a cart
* Potentially update the `cart` query

**Important**
* If any affected file in the `v2.4/graphql` directory is a symlink, the symlink must be broken with the `git rm <path to 2.4 file>` command. Then copy the v2.3 version over to v2.4.

* If any file in the `_includes/graphql` directory needs to be updated, and that file name does not end with `-24.md`, make a copy of that file and give it a name that ends with `-24.md`. All files in the `v2.4` directory that reference the original include file must be updated to reference the new `-24.md` file.

It is not necessary to update all examples to show the gift message functionality. One example somewhere should suffice.

Create your branch off of `2.4.1-develop`.

## Additional information

This issue is assigned to Atwix, because they contributed the functionality.

**Comment by atwixfirster** [comment]
@magento I am working on this

**Comment by atwixfirster** [comment]
> Update the storeConfig query to include new fields

**done**

PR: https://github.com/magento/devdocs/pull/7449
