### ISSUE TITLE
GraphQL: Document password change mutations

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7364]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [x] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28521

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/27876

Magento 2 version:

-  [x] 2.4.0

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add documentation for the following mutations:

* requestPasswordResetEmail
* resetPassword

The documentation must include examples, descriptions for input/output attributes, and a description of the error messages.

Update the src/_data/toc/graphql.yml file to include the new mutations.

Update the `storeConfig` query to include the new attributes

Create your branch off of `2.4.1-develop`.

## Additional information

This issue is assigned to Atwix, because they contributed the functionality.

**Comment by atwixfirster** [comment]
@magento I am working on this

**Comment by atwixfirster** [comment]
> Add documentation for the following mutations: requestPasswordResetEmail

**done** in https://github.com/magento/devdocs/pull/7424

> Add documentation for the following mutations: resetPassword

**in progress**

> Update the storeConfig query to include the new attributes

**in progress**

**Comment by keharper** [comment]
Reopening because #7426 is still in progress.
