### ISSUE TITLE
update Services document to reflect our packaged build and deploy scripts

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#737]
For example, the page:

https://github.com/magento/devdocs/blob/develop/guides/v2.0/cloud/project/project-conf-files_services-elastic.md

Gives the implementation example for out how extend the deploy script for elastic but this should just be handled by our out of the box script.  That script is not referenced by the documentation.

**Comment by xcomSteveJohnson** [comment]
Please provide more detail because I do not know what script you're referring to.

**Comment by xcomSteveJohnson** [comment]
@dougkm  Reminder. I am not sure what I need to do.

**Comment by xcomSteveJohnson** [comment]
@dougkm Closing because of elapsed time. Feel free to reopen with more information.
