### ISSUE TITLE
GraphQL: Add support for wish lists

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7373]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28551

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/28205

Magento 2 version:

-  [x] 2.4.1

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

This issue provides an overview of the work needed to document the wish list functionality to be added in the 2.4.1 release. This work might be done across several pull requests.

Add documentation for the following mutations and queries:

* createWishlist mutation
* addProductsToWishlist mutation
* removeProductsFromWishlist mutation
* updateProductsInWishlist mutation
* wishlist query

This new documentation must include examples, descriptions for input/output attributes, and a description of the error messages.

Add deprecation notices wherever applicable

Update the src/_data/toc/graphql.yml file to include the new mutations/query.

## Additional information

This issue is assigned to Atwix, because they contributed the functionality.

**Comment by eduard13** [comment]
This issue has to be postponed, as there will be some implementation adjustments on the current GraphQl Wishlist implementation, based on the following [discussion](https://github.com/magento/partners-magento2ee/pull/248#issuecomment-649749589).

**Comment by keharper** [comment]
I see that mutations were added in https://github.com/magento/magento2/pull/28205 for managing products within the default CE wishlist. I'll add those. All other features were deferred to 2.4.2.
