### ISSUE TITLE
GraphQL: Add support for compare lists

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7374]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28522

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/29047

Magento 2 version:

-  [x] 2.4.1

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

This issue provides an overview of the work needed to document the compare lists functionality to be added in the 2.4.1 release. This work might be done across several pull requests.

Add documentation for the following mutations and queries:

* compareList query
* createCompareList mutation
* deleteCompareList mutation
* addItemsToCompareList mutation
* removeItemsFromCompareList mutation
* assignCompareListToCustomer mutation

This new documentation must include examples, descriptions for input/output attributes, and a description of the error messages.

Update the src/_data/toc/graphql.yml file to include the new mutations/query.

## Additional information

This issue is assigned to Atwix, because they contributed the functionality.

**Comment by atwixfirster** [comment]
@magento I am working on this

**Comment by shrielenee** [comment]
Are you still on this @atwixfirster ?

**Comment by keharper** [comment]
The schema for compare lists is still under development, so the work on this issue can't move forward.

**Comment by andrewbess** [comment]
@magento I am working on this

**Comment by keharper** [comment]
@magento export issue to Jira project PWA as Issue

**Comment by keharper** [comment]
@magento export issue to Jira project PWA as Story
