### ISSUE TITLE
Clarify info about accessing diff nodes on Pro architecure and Scaled architecture topics

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#7377]
In https://devdocs.magento.com/cloud/architecture/scaled-architecture.html#ssh-access

the section on accessing the different nodes applies to both Pro Architecture and the Scaled Architecture.  The Pro architecture only has nodes 1 - 3. 

This section was the only place I could find this documented.

Also, the possible values of <environment> should be spelled out.

**Comment by BarnyShergold** [comment]
@dougkm 
I have reviewed the documentation and on the Scaled Architecture and I'm unsure as to what you need clarifying?

Scaled Architecture is available to Pro Projects with  Pro48+ - so its an optional feature.

The first part of you comment says -

> In https://devdocs.magento.com/cloud/architecture/scaled-architecture.html#ssh-access
> 
> the section on accessing the different nodes applies to both Pro Architecture and the Scaled Architecture. The Pro architecture only has nodes 1 - 3.
> 
> This section was the only place I could find this documented.

However, this is a statement not a question or a request - what do you need?

Secondly you say -

> Also, the possible values of should be spelled out.

But this is an incomplete sentence, the possible values of what? And when you say "Spelled out" - what do you mean? The SSH section is very clear on the node numbering from 1 to n. Also how to access the nodes.

We'd need more and clearer information from yourself to determine what documentation needs to be clarified and what it should say.

Thanks!

**Comment by BarnyShergold** [comment]
Closed as issue raiser did not respond within 14 days and current information seems clear enough
