### ISSUE TITLE
Installation bug on new install

### ISSUE THREAD

**Issue by sugarcubeproductions** [magento/devdocs#7379]
# Bug report

## Description

Deprecated Functionality: Function ReflectionType::__toString() is deprecat  
  ed in /var/www/puppypridestore-2.3.5/vendor/laminas/laminas-code/src/Reflec  
  tion/ParameterReflection.php on line 83    

### Steps to reproduce

Freshly installed PHP7.4, downloaded new Magento 2.3.5, try to install

## Expected result

I'd assume it would install?

## Possible solutions

Complete removal of the Lamina's code? I dunno...

**Comment by jeff-matthews** [comment]
@sugarcubeproductions, Magento 2.3.x does not support PHP 7.4: https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php

Magento 2.4.0 supports PHP 7.4: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html#php
