### ISSUE TITLE
Mistake in "Magento ownership and permissions in development and production"

### ISSUE THREAD

**Issue by RG-1** [magento/devdocs#738]
There is a small mistake in Developer Documentation.

Where to find it?
--
1. Go to http://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_file-sys-perms.html
2. Find "Tasks for one Magento file system owner" and reveal "Click to show/hide content"
3. Find "Make files and directories writable:"

> Make files and directories writable:
> 
> To make files and directories writable so you can update components and upgrade the Magento software:
> 
> Log in to your Magento server.
> Change to your Magento installation directory.
> Enter the following commands:
> chmod -R u+x .

Mistake
--
I think that `chmod -R u+x .` should be changed to `chmod -R u+w .`

File
--
https://github.com/magento/devdocs/blob/develop/guides/v2.0/config-guide/prod/prod_file-sys-perms.md

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing that out. I fixed some other mistakes at the same time. Please take a look.

**Comment by RG-1** [comment]
:thumbsup:
