### ISSUE TITLE
ESLINT and JSCS rules links do not work on 2.4

### ISSUE THREAD

**Issue by navarr** [magento/devdocs#7380]
# Bug report

## Description

The ESLINT and JSCS links on the [JavaScript coding standard page](https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-javascript.html) point to incorrect URLs.

This is due to them using {{ page.guide_version }} as part of the URL, and the page content being cloned from 2.3.

Currently, there exists a 2.3 branch and a 2.4-develop branch, and the way these URLs are built does not account for it.

### Steps to reproduce

1. Visit https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-javascript.html
1. Click "Magento ESLint Rules"

## Expected result

* Be on https://github.com/magento/magento2/blob/2.4-develop/dev/tests/static/testsuite/Magento/Test/Js/_files/eslint/.eslintrc-magento

**Comment by dobooth** [comment]
Links to the 2.4 codebase will fail in the beta docs until the actual release date. We added a note to reflect this. Thanks!
