### ISSUE TITLE
Feedback on page: /redoc/2.3/

### ISSUE THREAD

**Issue by erastl** [magento/devdocs#7386]
# General issue

## Description:

This page https://devdocs.magento.com/redoc/2.3/admin-rest-api.html is practically unusable for me. The side menu freezes when scrolling, and sometimes the entire page freezes up, and I have to stop and wait just to even copy some piece of text. 

## Additional information:

I'm using Chrome v. 81 to view the page.

**Comment by dobooth** [comment]
HI @erastl thanks for posting this. We have heard about it, from both the community and internal users as well. It has to do with the size of the admin data file. We are currently looking at solutions for this, including dedicated hosting, alternative API implementations and other speed increases we can wring out of it.
This issue, and comments in other forums let us know just how much people depend on these docs and we will try to make them as performant as possible.

**Comment by keharper** [comment]
@erastl Firefox seems to work better than Chrome. Also try waiting a couple of minutes after the page loads before trying to scroll and interact with the page.
