### ISSUE TITLE
Linux kernel info out of date on Software recommendations page

### ISSUE THREAD

**Issue by rip057** [magento/devdocs#7391]
# General issue

## Description:

Regarding https://devdocs.magento.com/guides/v2.3/performance-best-practices/software.html

Operating System section specifically

>  The Linux kernel supports a mechanism to “reuse” and “recycle” TCP connections. Be aware that more aggressive recycling than re-use may cause issues on the load balancers. To enable these kernel settings, set the following values in /etc/sysctl.conf:
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1

## Possible solutions:

Well first and foremost net.ipv4.tcp_tw_recycle doesnt exist past kernel 4.12
see [https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4396e46187ca5070219b81773c4e65088dac50cc](url)
also [https://stackoverflow.com/questions/6426253/tcp-tw-reuse-vs-tcp-tw-recycle-which-to-use-or-both](url)
not even notated anymore in sysctl documention [https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt](url)

and net.ipv4.tcp_tw_reuse is useless for incoming connections

> Enabling net.ipv4.tcp_tw_reuse is useless for incoming connections.

please see [https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux](url)

**Comment by dobooth** [comment]
@buskamuza who is the right person to get info on this issue?

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
