### ISSUE TITLE
Feedback on page: /guides/v2.3/comp-mgr/updater/update-updater.html

### ISSUE THREAD

**Issue by meaty68** [magento/devdocs#7403]
# General issue - unable to update the updater - Magento 2.3.5-p1

## Description:

The Update the Updater Application failed for me with the following error:
 [InvalidArgumentException]
  Could not find package magento/updater with stability stable in a version installable using your PHP version 7.3.16.

## Possible solutions:

Is a new version available?

**Comment by erikmarr** [comment]
@meaty68 thanks for your feedback. This looks more like a support issue. You can find more resources here: https://devdocs.magento.com/community/resources/support.html
