### ISSUE TITLE
Feedback on page: /guides/v2.4/ui_comp_guide/components/ui-wysiwyg.html

### ISSUE THREAD

**Issue by arshadpkm** [magento/devdocs#7404]
# General issue

## Description:

Under events (https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-wysiwyg.html#events) listed about TinyMCE javascript events, but given a link to Magento events and observers under (See Events and observers to learn more about events and how to use them.)

## Possible solutions:

Remove the link to Magento events and observer and give link to how to handle javascript events in Magento.

**Comment by atwixfirster** [comment]
@magento I am working on this
