### ISSUE TITLE
Magento Testing Guide missing from v2.1

### ISSUE THREAD

**Issue by navarr** [magento/devdocs#741]
The howdoi/mtf is missing in v2.1, where it exists in v2.0, and is linked from extension-dev-guide/validate/test-module

Page with link: http://devdocs.magento.com/guides/v2.1/extension-dev-guide/validate/test-module.html
Link text: "Magento Testing Overview"
Link to: http://devdocs.magento.com/guides/v2.1/howdoi/mtf/mtf.html

**Comment by dshevtsov** [comment]
Good catch!
This topic was moved to http://devdocs.magento.com/guides/v2.1/test/testing.html
Now you can open it when click "Testing" in navigation bar on top of the page (on left from "How Do I...?").
We'll fix the links.
Thanks!

**Comment by dshevtsov** [comment]
Please check the "Magento Testing Overview" link.

**Comment by navarr** [comment]
Confirmed fixed.
