### ISSUE TITLE
Search results are leading to the wrong links

### ISSUE THREAD

**Issue by eduard13** [magento/devdocs#7435]
# Bug report

## Description

When searching something using the top search bar, we're expecting to get the correct links

### Steps to reproduce

1. Open the following [page](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/conventions_js.html) or this [one](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/bk-javascript-dev-guide.html)
1. Open the search bar
1. Type into the input - "Modal"
![image](https://user-images.githubusercontent.com/15868188/85311222-c0854700-b4bd-11ea-97f2-68f16d304b25.png)

## Expected result

The result "Modal widget" link should link to widget's documentation.

## Possible solutions

Remove the errant blank topic https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/back_to_guide.html

## Additional information

There are two Modal widget topics ---- one of which is errant and has a link back to the JS guide and one which is correct: https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_modal.html.

**Comment by shrielenee** [comment]
Is this automation gone wrong?
