### ISSUE TITLE
[DOCS] The routes.yaml docs are either wrong or very confusing

### ISSUE THREAD

**Issue by damienwebdev** [magento/devdocs#7444]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/cloud/project/project-conf-files_routes.html

## Description

As a developer, I'd like to be able to configure routes for my project in a multi-store environment in both production and staging. My routes can be either http:// or https://.

## Possible solutions

In theory, this is entirely configurable from `routes.yaml`.

## Additional information

This ticket is a result of some discussion and confusion that came up on the Community Engineering Slack around `routes.yaml`.

Attached is the original discussion.

> So, I've configured a domain in fastly/cloud "mcstaging.mysecondcloudstore.com" and I keep getting a 404 on when I attempt to hit the URL.
> I noticed a routes.yaml update that I didn't have: https://github.com/magento/magento-cloud/blob/master/.magento/routes.yaml
```
"http://{all}/":
    type: upstream
    upstream: "mymagento:http"
```
> I added this and it didnt change the behavior.
> Next, I submitted a support ticket and they said that I was missing the {all} (I wasn't on this branch), and now they're saying I need to have https:// in the routes.yaml. This seems contradictory with some of what I've read in devdocs.

>> The error is that you have included http in the routes.yaml file whereas when the request is resolved it translates to https which is not defined in the routes.yaml.
>> curl -snILk http://mcstaging.mysecondcloudstore.com/
>> HTTP/1.1 301 Moved Permanently
>> Retry-After: 0
>> Location: https://mcstaging.mysecondcloudstore.comm/
>> Content-Length: 0
>> Accept-Ranges: bytes
>> Date: Tue, 23 Jun 2020 06:35:54 GMT
>> Connection: close
>> X-Served-By: cache-bom18223-BOM
>> X-Cache: HIT
>> X-Cache-Hits: 0
>> X-Timer: S1592894155.907965,VS0,VE0
>> strict-transport-security: max-age=31536000
>> Vary: 

> Specifically this contradicts: https://support.magento.com/hc/en-us/articles/360006296953-Redirect-HTTP-to-HTTPS-for-all-pages-on-Cloud-Force-TLS-
>> No changes needed in routes.yaml
>> To enable HTTP to HTTPS redirect on all pages of your store, you do not have to add the pages to the routes.yaml configuration file—enabling Force TLS globally for your entire store (using Magento Admin) is enough.
> and https://devdocs.magento.com/cloud/project/project-conf-files_routes.html
>> {all} represents all the domain names configured for the project. For example, if you have a project with example.com and example1.com domains, the route templates http://www.{all}/ and https://{all}/blog resolve to routes for all domains in the project:

@syno-bvo: 
The pro envs (staging and production) doesn't read the routes file atm (maybe soon :slightly_smiling_face: ) you'll need to create a ticket to support

@BarnyShergold: 
Erm  - it depends on the service agreed - We have PRO env where we control what goes in routes.yaml. -We don't need a ticket for it to be applied

@BarnyShergold: 
@damienwebdev - At it's simplest you should have this in routes.yaml :
```
https://{default}/:
    type: upstream
    upstream: mymagento:http
https://{all}/:
    type: upstream
    upstream: mymagento:http
```

@syno-bvo
oh really ? Is this new ?

@BarnyShergold:
{all} refers to EVERY domain on the environment - {default} is a single domain that has been deemed default.

@BarnyShergold:
@Benjamin Volle Not sure how new but I know as I made some changes a few weeks ago, applied the file but it didn;t work. So i thought I needed them to apply it and raised a ticket. T

@BarnyShergold:
They said - Nope on this one it's self-management. It didn't work as I had the wrong information.

@syno-bvo:
magento support things ... ¯\_(ツ)_/¯

@damienwebdev: 
@barnyshergold I don't quite understand, why do the docs differ from reality? Docs say:
{all} represents all the domain names configured for the project. For example, if you have a project with example.com and example1.com domains, the route templates http://www.{all}/ and https://{all}/blog resolve to routes for all domains in the project
But you say:
```
https://{all}/:
    type: upstream
    upstream: mymagento:http
```

@damienwebdev: 
I'm assuming the docs must be wrong then?

@damienwebdev:
Because, strangely, https:// works for {default} without the https:// configuration. Do I need BOTH http:// and https://? 

@barnyshergold 
IIRC http is routed to https these days. You CAN put in http:// but I don;t think it is necesasry now. And the DOCs are sometimes out of date.

@damienwebdev:
Ok, why is the file in the .magento/routes.yaml in the cloud repo http:// then? Lots of confusing shenanigans going on here.

@YPyltiai
@syno-bvo it’s just a feature that can be enabled but requires mostly some changes in files from you, that’s why it’s not auto-enabled. You can ask support.

@barnyshergold
It's equally  valid to have just https or http/https

======

This potentially warrants changes to https://github.com/magento/magento-cloud/blob/master/.magento/routes.yaml as well.

**Comment by YPyltiai** [comment]
@meker12 , @hguthrie , please review once you have a chance.
It fits into the discussion we had some time ago about "request only" feature list, which would be great to document somewhere.

**Comment by shrielenee** [comment]
This looks to not be in progress anymore (last activity June 25). Moving back to Ready for Development.

**Comment by BarnyShergold** [comment]
@meker12 @shrielenee 
I get confused over this file on occasion too - can we get an Adobe Magento Developer to take a look at this, provide the definitive definition and then we can write it up?

**Comment by meker12** [comment]
@YPyltiai can you suggest someone who can help with fixing the routes documentation in the _Cloud Guide_.

**Comment by YPyltiai** [comment]
@NadiyaS , could you please help with that ^ ?

**Comment by NadiyaS** [comment]
Sure. I will review https://devdocs.magento.com/cloud/project/routes.html and create PR.
