### ISSUE TITLE
"Customize email templates" needs update due to changes since Magento 2.1.0

### ISSUE THREAD

**Issue by RG-1** [magento/devdocs#745]
Developer Documentation needs update due to changes since Magento 2.1.0

Where to find it?
--
1. File: https://github.com/magento/devdocs/blob/develop/guides/v2.0/frontend-dev-guide/templates/template-email.md
2. Go to http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-email.html#customize-logo-admin

> Customize the email logo using the Admin
> 
> In the Magento Admin, navigate to STORES > Settings > Configuration > GENERAL > Design > Emails
> In the Scope drop-down list, select the scope for which you want to set a logo (a certain store view, the whole website, or default config).
> Upload your logo and specify the alternative text for it. 
> 

Update 
--
1. `STORES > Settings > Configuration > GENERAL > Design > Emails` is now moved to: `Content > Design: Configuration > *Edit Store View* > Transactional Emails`
2. Screenshot should be changed.

----

Where to find it?
--
1. Same file
2. Go to http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-email.html#contact-information-emails

> Use contact information in emails
> 
> Emails can output your store name, store email address, store phone number, and store hours of operation if those values are configured in the Admin.
> 
> To set those values:
> 
> To set the store name, phone number, and hours of operation:
> In the Magento Admin, navigate to STORES > Settings > Configuration > GENERAL > General > Emails
> Input values into the Store Name, Store Phone Number, and Store Hours of Operation fields.
> Note: The Store Phone Number and Store Hours of Operation fields are optional.
> Click the Save Config button.
> To set the store email:
> In the Magento Admin, navigate to STORES > Settings > Configuration > GENERAL > General > Store Email Addresses > General Contact
> Input values into the Sender Name and Sender Email fields.
> Click the Save Config button.

Update 
--
1. This part: `STORES > Settings > Configuration > GENERAL > General > Emails` should be changed to `STORES > Settings > Configuration > GENERAL > General > Store Information`

**Comment by almarchenko** [comment]
@RG-1 Thank you! Sorry it took so long! Looking at this now.

**Comment by gazzaf** [comment]
Please fix this because the live 2.1 docs are still showing incorrect information. 
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-email.html

I spent hours tearing my hair out trying to follow instructions that were completely wrong. The menus are a complete maze to anyone new to Magento so accurate documentation is essential. In the end I found this useful post from @RG-1 with the correct information.

What would be useful is if the search box in the backend can be used to find the correct admin pages. e.g. type in 'email' and it will list links going directly to pages that control email related settings.

**Comment by almarchenko** [comment]
No excuse( fixing it now!

**Comment by gazzaf** [comment]
Thank you @almarchenko :-)

**Comment by almarchenko** [comment]
@RG-1  @gazzaf  I updated the doc, sorry it took so long. Plz let me know if I can close this issue.

**Comment by gazzaf** [comment]
Ok by me, although I've uninstalled 2.1 now as it's not fit for production. _Upgraded_ to 1.9 now.

**Comment by almarchenko** [comment]
@gazzaf I hope you will get back to M2. We'll update docs quicker, I promise!))
