### ISSUE TITLE
Modules block in env

### ISSUE THREAD

**Issue by mykhailo-superiorseating** [magento/devdocs#7456]
# Bug report

## Description

Devdocs/[env.php reference](https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-envphp.html) doesn't contain 'modules' block clarification.

## Additional information

Example:
```php
'modules' => [
    'Amazon_Payment' => 0,
    'Amazon_Login' => 0
]
```

**Comment by manishmittalm** [comment]
@mykhailo-superiorseating  Module not exists in env.php file. This is part of config.php file.
Please refer this
https://devdocs.magento.com/guides/v2.4/config-guide/config/config-files.html

**Comment by mykhailo-superiorseating** [comment]
@manishmittalm Got it. But what about https://github.com/magento/community-features/issues/126 ?

    According to the comment above, this ticket is moved to feature-requests track

Is it implemented?

**Comment by manishmittalm** [comment]
Please track same ticket for that issue, when it will be implemented then only we can take any documentation ticket. Thanks

**Comment by shrielenee** [comment]
Hey there @mykhailo-superiorseating @manishmittalm I am going to close this. Based on your comments above it seems this should be tracked in the mentioned issue, and this one is no longer relevant. If you feel this was in error please open another issue!
