### ISSUE TITLE
Feedback on page: /cloud/project/privatelink-service.html

### ISSUE THREAD

**Issue by jpanke** [magento/devdocs#7459]
# General issue

## Description:

In the Limitation section, it talks about customers being able to purchase additional support to help with enablement.  There is no team that will help beyond initial enablement.

Magento support does not cover troubleshooting AWS PrivateLink issues beyond initial enablement. **Customers have the option to purchase additional support from Magento Services**

## Possible solutions:

Just remove the statement  **Customers have the option to purchase additional support from Magento Services**

## Additional information:

Thanks

**Comment by meker12** [comment]
Fixed in #7464.
