### ISSUE TITLE
Where do we get the `authorization endpoint` in v2

### ISSUE THREAD

**Issue by shraddhacloudelements** [magento/devdocs#747]
What endpoint is being used for `admin authorization`?

**Comment by keharper** [comment]
I'm not sure I understand the full context of your question. Are you looking for /V1/integration/admin/token?

**Comment by keharper** [comment]
@shraddhacloudelements , just checking to see if you're still looking for help.

**Comment by shraddhacloudelements** [comment]
Instead of oauth, I switched to Token authentication. That worked fine. Thanks for your help.
