### ISSUE TITLE
ModifierInterface example is wrong

### ISSUE THREAD

**Issue by Sartoric** [magento/devdocs#7474]
# General issue

Affected page: /guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.html

## Description:

In the document we have : 
`In your custom module, add a class that implements \Magento\Ui\DataProvider\Modifier\ModifierInterface `

But the example Class, in fact, extends the AbstractModifier (that implement the interface)

## Possible solutions:

Correct the text or the sample

**Comment by atwixfirster** [comment]
@magento I am working on this

**Comment by atwixfirster** [comment]
Fixes provided in: https://github.com/magento/devdocs/pull/7480

Thank you for reporting, @Sartoric 👍
