### ISSUE TITLE
Feedback on page: /guides/v2.4/ui_comp_guide/howto/add_category_attribute.html

### ISSUE THREAD

**Issue by sw-tt-jigneshvagh** [magento/devdocs#7475]
# General issue
After adding the custom attribute, its showing on category edit details but it is not saving the data.

## Description:
After adding the custom attribute, its showing on category edit details but it is not saving the data, I have tried different methods and also tried to clear cache, setup:upgrade, re-indexing but still facing issue.

## Additional information:
Can you please guide me what is the issue here.

**Comment by manishmittalm** [comment]
@sw-tt-jigneshvagh Please post this issue here: https://community.magento.com/

This forum to share issues with documentation only. closing this ticket here.
