### ISSUE TITLE
Catalog Category Link Widget issue

### ISSUE THREAD

**Issue by LittleCamel** [magento/devdocs#748]
When adding "Catalog Category Link" widget if you leave empty "Anchor Custom Text" it should use category name but it don't. It just display empty span inside anchor on fronted ( link to category is there but category name is not).

**Comment by almarchenko** [comment]
Hi @LittleCamel 
As far as I understand this is an issue in the product itself, not docs, so more chances it would efficiently addressed  if you put in the magento2 github repo. https://github.com/magento/magento2/issues

**Comment by LittleCamel** [comment]
Hi @almarchenko 
Yes, sorry. I open it here by mistake.
You can close this.
