### ISSUE TITLE
Link to ReDoc 2.4 doesn't work

### ISSUE THREAD

**Issue by PiotrBenedysiuk** [magento/devdocs#7491]
# General issue
Hyperlink to the REST API docs sends me to Magento 404 page.
## Description:
The content of https://devdocs.magento.com/redoc/2.4/index.html seems to be gone. 

## Possible solutions:

If docs are moved to a different location then the hyperlink referencing them should be adjusted.
If they are rightfully gone, then display information on your page regarding the end of support for Magento 1.

**Comment by jeff-matthews** [comment]
@PiotrBenedysiuk, the 2.4 docs are in beta at the moment. The 2.4 REST API docs won't be published until 2.4.0 reaches GA.

**Comment by keharper** [comment]
@PiotrBenedysiuk We have fixed the issue. The file you mentioned no longer exists, but the left navigation now takes you to the 2.4 admin schema.
