### ISSUE TITLE
Feedback on page: /guides/v2.4/extension-dev-guide/routing.html

### ISSUE THREAD

**Issue by brucemead** [magento/devdocs#7496]
# General issue

## Description:

Some links going to `https://github.com/magento/magento2/blob/2.4/...` instead of `https://github.com/magento/magento2/blob/2.4-develop/...`

## Possible solutions:

Update links to `https://github.com/magento/magento2/blob/2.4-develop/...`

**Comment by brucemead** [comment]
@magento I am working on this

**Comment by brucemead** [comment]
So reviewing the `routing.md` file its using variable `{{ page.guide_version }}` which is pulled from line 4 
```
version: 2.4
```
Which I believe is then used here in one of these https://github.com/magento/devdocs/tree/master/_plugins/page-params to set the variable `{{ page.guide_version }}`.

So in my suggested PR https://github.com/magento/devdocs/pull/7497 I've added a new variable `version_branch` and used that in these links instead.

An alternative option could be to replace `{{ page.guide_version }}` with `{{ page.guide_version }}-develop`.

**Comment by dshevtsov** [comment]
> So reviewing the `routing.md` file its using variable `{{ page.guide_version }}` which is pulled from line 4

`guide_version` version is generated by [custom plugin ](https://github.com/magento/devdocs/blob/master/_plugins/page-params/page-baseurl-generator.rb#L9-L10) for each page.

**Comment by dshevtsov** [comment]
Code in `2.4-develop` is not fully relevant to documentation in 2.4. The documentation covers 2.4.0 codebase but `2.4-develop` accepts contributions for releases AFTER 2.4.0 already. `2.4` links will be resolved right after 2.4.0 release.

**Comment by dshevtsov** [comment]
Removing the redundant `version` parameter in #7502.
For more detail on where `2.4`. comes from, refer to my comment [here](https://github.com/magento/devdocs/pull/7497#issuecomment-656166612).
