### ISSUE TITLE
Update Additional search configuration section to provide info about ELASTICSUITE_CONFIGURATION variable

### ISSUE THREAD

**Issue by meker12** [magento/devdocs#7500]
# General issue

## Description:

- In the Cloud Guide, [Additional search configuration](https://devdocs.magento.com/cloud/project/project-conf-files_services-elastic.html#additional-search-configuration) section mentions Elasticsuite and custom configuration, but it does not provide a link to the [ELASTICSUITE_CONFIGURATION](https://devdocs.magento.com/cloud/env/variables-deploy.html#elasticsuite_configuration) deploy variable for to configure and retain customized ElasticSuite service settings between deployments. 

- [SEARCH_CONFIGURATION](https://devdocs.magento.com/cloud/env/variables-deploy.html#search_configuration) variable doesn't reference the Elastic suite config variable (maybe that's OK, but it might be helpful to include a reference there.)

Slack conversation:

```
Mathew Beane  5:55 AM
use native mode, no waiting... performance is just as good now for the most part, unless you are on old hardware.

2 replies
Last reply today at 7:14 AMView thread

Mathew Beane  9:06 AM
[2020-07-09 13:13:04] ERROR: [114] Fix configuration with given suggestions:
- ElasticSuite is installed but elasticsearch6 set as search engine.  
[2020-07-09 13:13:04] INFO: Set flag: var/.deploy_is_failed  
In Processor.php line 118:
  [114] Fix configuration with given suggestions:                       
  - ElasticSuite is installed but elasticsearch6 set as search engine.  
In ValidateConfiguration.php line 58:
  Fix configuration with given suggestions:                             
  - ElasticSuite is installed but elasticsearch6 set as search engine.  
deploy
returned non-zero exit status 114
Has anyone seen this error with a deploy?

Mathew Beane  9:32 AM
It seems like ECE expects it to be configured but not clear how. https://devdocs.magento.com/cloud/env/variables-deploy.html#elasticsuite_configuration outlines it a little... I guess.... @shiftedreality ?
devdocs.magento.comdevdocs.magento.com
Deploy variables | Magento 2 Developer Documentation
Magento 2 Developer Documentation.
9:35
@Yevhenii Pyltiai this one goes to you too, since Oleg is still afk :wink:

Yevhenii Pyltiai:magento:  9:37 AM
@aepod in env.php or DB I guess you have ES configured as the main search engine

Mathew Beane  9:37 AM
it defaults to elasticsearch6

Yevhenii Pyltiai:magento:  9:37 AM
When ElasticSuite module is set up - it modifies ES logic in a way that native one becomes broken

Mathew Beane  9:37 AM
nothing is set

Yevhenii Pyltiai:magento:  9:38 AM
So if Suite is there - it needs to be enabled

Mathew Beane  9:38 AM
enabled how?

Yevhenii Pyltiai:magento:  9:38 AM
https://devdocs.magento.com/cloud/env/variables-deploy.html#search_configuration
devdocs.magento.comdevdocs.magento.com
Deploy variables | Magento 2 Developer Documentation
Magento 2 Developer Documentation.
9:38
You can set this one and set engine to Suite

Mathew Beane  9:39 AM
Ok, that makes sense. @Alain Landry Noutchomwo you got this :slightly_smiling_face:

Yevhenii Pyltiai:magento:  9:39 AM
Known limitations—
Changing the search engine to any type other than elasticsuite causes a deploy failure accompanied by an appropriate validation error
Removing the ElasticSearch service causes a deploy failure accompanied by an appropriate validation error
9:39
^ from DevDocs
9:39
So if composer package is there - it will keep failing until you actually make it enabled

Alain Landry Noutchomwo  9:43 AM
Just for make myself

Mathew Beane  9:43 AM
you have to add that configuration to the .magento.app.yaml

Yevhenii Pyltiai:magento:  9:43 AM
.magento.env.yaml

Alain Landry Noutchomwo  9:43 AM
@Yevhenii Pyltiai You say that I will put this in my env.php right
9:43
stage:
  deploy:
   SEARCH_CONFIGURATION:
     engine: elasticsearch
     elasticsearch_server_hostname: hostname
     elasticsearch_server_port: '123456'
     elasticsearch_index_prefix: magento
     elasticsearch_server_timeout: '15'

Mathew Beane  9:44 AM
no that goes in the .magento.app.yaml

Yevhenii Pyltiai:magento:  9:44 AM
.magento.env.yaml
It’s ECE-Tools variable :slightly_smiling_face:
```

## Possible solutions:

Update the [Additional search configuration](https://devdocs.magento.com/cloud/project/project-conf-files_services-elastic.html#additional-search-configuration) section to provide info about the ELASTICSUITE_CONFIGURATION variable.

## Additional information:

In the past, Elasticsearch configuration documentation for Cloud was subject of some support investigations, and the docs were updated accordingly. Checking with @NadiyaS  and @hguthrie for additional guidance on proposed updates.

Update:  Cloud Dev team in investigating the issue. Will update this issue about any required doc updates based on outcome of investigation.

**Comment by BarnyShergold** [comment]
@meker12 
I've checked this section in the Cloud docs and in the "Additional Search Configuration" there is a link to the SEARCH_CONFIGURATION section when you click "Deploy Variables" 

If the text was updated to "See Deploy variables for further information on SEARCH_CONFIGURATION" - would that address this issue?

**Comment by meker12** [comment]
@BarnyShergold I think it's as simple as adding info about the ELASTICSUITE_CONFIGURATION variable at the end of this sentence:

```If you use the ElasticSuite third-party plugin, you must update the ece-tools package to version 2002.0.19 or later.```

For example, append the following sentence:

After you set up ElasticSuite, you can add the configuration settings to the ELASTICSUITE_CONFIGURATION deploy variable to save the settings across deployments.
