### ISSUE TITLE
Explain best practices for sample files

### ISSUE THREAD

**Issue by brianpittvps** [magento/devdocs#7504]
# General issue

## Description:
The migration tool contains a bunch of sample files for the mapping, settings, etc that we can copy to our own module for configuring the migration tool.  The map.xml.dist file, for instance, contains over 2200 lines with hundreds of entries.  Is this just an example or are we supposed to keep all that stuff in there and add our own customizations as needed?  This is not explained at all.  It tells you to use the files included in the module, but not what content within the file should be kept.

https://devdocs.magento.com/guides/v2.3/migration/migration-tool-internal-spec.html

Reference similar closed issue for more context: https://github.com/magento/devdocs/issues/7503

## Possible solutions:
You need to explain better how we're supposed to use the sample files.  Should they be left as is and only added to?  Or should we wipe it all out and just put in the things we want to put in?  I don't even know what half those sample entries are, let alone if they're important or should be ignored.

**Comment by shrielenee** [comment]
This page also requires a general copyedit.

**Comment by atwixfirster** [comment]
For this issue we can write a book. DMT is a complex tool. It's impossible to write a few sentences to explain how does it work.

**Comment by BarnyShergold** [comment]
@shrielenee @atwixfirster 
Based on the fact that @atwixfirster quite rightly says you could write book on this tool, so where do you start (where do you end?) and there have been no updates or responses for 2 months, I propose we close this issue. DO you concur?

**Comment by brianpittvps** [comment]
This is just one programmers opinion, but it seems there has to be a happy medium between a comprehensive book of details and addressing a few areas of confusion.  For instance, my original report talks about sample files with thousands of lines in it and no clear understanding of what is needed.  Do we just customize what we wanna customize?  Do we copy the entire file?  I realize there are a myriad of options and you can't necessarily explain it all in detail, but you can provide a little bit more insight than what is currently documented.

That being said, I also don't think that "it's hard" is a reason not to do something.  Since version 1 Magento has been notorious for poor documentation, relying on the community to help each other.  M2 is your chance to do better.  Don't give up because it's hard, that doesn't help anyone.

**Comment by shrielenee** [comment]
@BarnyShergold Issues remain open if they can be worked, which this one _still_ I think can be worked. It's PRs that we close after a certain amount of time with no response.

@brianpittvps Thanks for your helpful feedback regarding our documentation. This issue is open and will be worked, but the team has not yet been able to prioritize it internally. I added "help wanted" and "good first issue" labels to signal that we could use some assistance on this.

@atwixfirster If you have some simple guidelines that we can start with, that would be great.

Thanks all!

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this
