### ISSUE TITLE
Version switcher looks wrong in Safari

### ISSUE THREAD

**Issue by Zifius** [magento/devdocs#7513]
# Bug report

## Description

The switcher on the new layout has too much text padding from the top in Safari. Looks good in Chrome
## Expected result

Switcher looks the same in all browsers
## Additional information

<img width="144" alt="Screenshot 2020-07-14 at 10 12 35" src="https://user-images.githubusercontent.com/696727/87402118-64dd4380-c5bb-11ea-96e2-05af699837b3.png">

**Comment by dobooth** [comment]
@belbiy Thought you might want to see this.

**Comment by Zifius** [comment]
Checked and it looks fine now. Closing and thanks for the fix!
