### ISSUE TITLE
Cloud: what to do when you update Elasticsearch

### ISSUE THREAD

**Issue by meker12** [magento/devdocs#7557]
# General issue

In the Elasticsearch set up information, no information about what to do when you update the Elasticsearch version.

Affected page: /cloud/project/project-conf-files_services-elastic.html

## Description:

In the [Services](https://devdocs.magento.com/cloud/project/project-conf-files_services.html)  and [Upgrade the Magento application](https://devdocs.magento.com/cloud/project/project-upgrade.html#upgrade-the-magento-application) section of the _Upgrade Magento version_ topic, there's a note that says that you have to submit a Support ticket to install or update services in Staging or Production.  

## Possible solutions:

Add note about service updates to the Setup Elasticsearch topic, or add a section to Setup Elasticsearch section that tells how to update the ES version and plugins for Pro Production, Staging, and Integration environments as well as Starter Production environment. 

## Additional information:

Relates to PR #7543

cc: @atwixfirster

**Comment by atwixfirster** [comment]
@magento I am working on this

**Comment by meker12** [comment]
We add instructions for upgrading and downgrading services for Magento Commerce on the Cloud platform.  See [Changing services versions](https://devdocs.magento.com/cloud/project/project-conf-files_services.html#change-service-version).
