### ISSUE TITLE
Inconsistent ElasticSearch recommendation

### ISSUE THREAD

**Issue by rafaelstz** [magento/devdocs#7562]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-nginx.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-apache.html 

## Description

There are two different recommendations/examples:

"The Magento application and Elasticsearch are installed on different hosts (Running on separate hosts is secure, enables Elasticsearch to be scaled, and is necessary for proxying to work)": 
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html

"Elasticsearch runs on the same host as a web server (The advantage of putting Elasticsearch and the web server on the same host is that it makes intercepting encrypted communication impossible)": 
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-nginx.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-apache.html 

## Possible solutions

A possible solution would be removing the not recommended one.

## Additional information

It was reported originally here: https://magento.stackexchange.com/q/317886/16416

**Comment by BarnyShergold** [comment]
@shrielenee Can we get a definitive answer on this from the Magento team? The issue is easy to fix, remove A or B - but we need to know if it's A or B 😄

**Comment by shrielenee** [comment]
Yes, we need to get an opinion from a dev/architect to ensure we're leaving the right explanation and taking out the one we do not advise. Let me ping someone.

Also @BarnyShergold the gray labels are used by GitHub automation, so do not manually add or remove those from issues or PRs.

**Comment by BarnyShergold** [comment]
@shrielenee - I didn't remove the "dev in progress"! I just marked it "Waiting for Response"! I think the system did it.

I'm most happy to be the "Assignee" for this once we have an answer

**Comment by shrielenee** [comment]
Hey @BarnyShergold I talked to @chernenm and @maghamed (our internal all-knowing resources) and we agreed we should leave the suggestion that reflects our cloud deployments config:

"Elasticsearch runs on the same host as a web server (The advantage of putting Elasticsearch and the web server on the same host is that it makes intercepting encrypted communication impossible)":
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-nginx.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-apache.html"

Let me know if you have any questions! ❓

**Comment by BarnyShergold** [comment]
@shrielenee - I would proposed then to remove the complete content of the section "Recommended configuration" on this page : https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html and replace it with the second point - https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-nginx.html#recommendations

Is that agreeable?

**Comment by shrielenee** [comment]
I believe that is accurate. Instead of duplicating content, I would simply point to the existing section with the info that's needed with a "See the Recommendations section of the Configure nginx and Elasticsearch topic for information on the recommended configuration." or similar.

**Comment by rafaelstz** [comment]
Hi @shrielenee and @BarnyShergold,

I created this PR below to fix it, I left the old content but as another section, providing explanations on how to proceed in case the ElasticSearch must be in another host. I think it's very useful for the content there, and there are many hosts that don't provide ES build-in.

https://github.com/magento/devdocs/pull/7980

Please let me what do you think!
