### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/system-requirements-tech.html

### ISSUE THREAD

**Issue by lokesh450** [magento/devdocs#7568]
# PHP Extensions Check

4 missing PHP extensions. Hide detail 

## Description:
how to extensions

**Comment by dobooth** [comment]
@lokesh450 Thanks for the issue. Can you please provide more details about the specific extensions that are missing?

**Comment by BarnyShergold** [comment]
This issue has been closed due to lack of detail and no response to request for information

**Comment by hostep** [comment]
- `ext-sockets` which became required in 2.4.0 at least is still missing on https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html

@dobooth is aware of this, but unfortunately it's still not fixed yet 🙁
