### ISSUE TITLE
Add details to Define the GraphQL schema for a module 

### ISSUE THREAD

**Issue by RimantasAdeoWeb** [magento/devdocs#7580]
# General issue

The lack of examples in some sections make this page uninformative.

Path to file: /guides/v2.4/graphql/develop/create-graphqls-file.html

## Description:

There are no examples under "Declare input attributes", "Specify output attributes", "Define the output interface", "Define enumerations"
It makes these sections nearly useless to people not already familiar with Magento's integration of GraphQl - it just says what is possible to do but doesn't show how to do it. 

## Possible solutions:

Link to a schema file in some module which has a good example of an implementation of whatever the section is about.
Add an example in the page itself, such as in the "Define queries" section

**Comment by keharper** [comment]
Thanks for taking this PR, @chandru-199

**Comment by chandru-199** [comment]
If any GraphQL expertise take this PR, it will be better I think. Thank you!.

**Comment by gelanivishal** [comment]
@magento I am working on this

**Comment by sathiyaaa** [comment]
@magento I am working on this
