### ISSUE TITLE
Duplicated entries in BiC reference list for 2.4.0

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#7592]
# Bug report

## Description

This is about the page [Backward incompatible changes reference](https://devdocs.magento.com/guides/v2.4/release-notes/backward-incompatible-changes/reference.html)

### Steps to reproduce

1. Look at the [Database changes](https://devdocs.magento.com/guides/v2.4/release-notes/backward-incompatible-changes/reference.html#ce_2.3.0-2.4.0-develop-database) list

## Expected result

Not finding duplicated entries, for example: `signifyd_case` => `Table was dropped` is mentioned 7 times.

## Possible solutions

Look at the script which generates this and try to figure out why duplicated entries get outputted and fix the script.

## Additional information

Also not sure why there are 2 different sections for certain topics like `Class changes`, `Interface changes`, `Database changes`, ... on that one page?

**Comment by dshevtsov** [comment]
Engineering is aware of this issue. Unfortunately, the Documentation team doesn't have control over the BiC reference generation tool; we can only work with its results. We've been publishing raw output for the _magento2ce_ and _magento2ee_ codebases until the 2.4.0 release. The lists will be processed to a normal view right after the release.
