### ISSUE TITLE
Bad clear pub/static command

### ISSUE THREAD

**Issue by nickmarx12345678** [magento/devdocs#760]
On the page
http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html

In the orange box towards the middle of the page, you suggest the following command to clear the static content files

`find . -depth -name .htaccess -prune -o -delete`

It isn't immediately clear this is a very destructive action if run from the wrong directory (project root for example)

You need to add a warning to this and a qualifier saying specifically what directory to run it from (`pub/static`). I realized what happened half way through and it still managed to destroy all of my git repo and code directory.

**Comment by hostep** [comment]
A way more easier command to remove all files from `pub/static` without removing hidden files (the `*` doesn't match hidden files) is:

```bash
rm -R pub/static/*
```

In my opinion, way more clearer then that complicated `find` command ;)

**Comment by xcomSteveJohnson** [comment]
@nickmarx12345678 Thank you for pointing this out. I'm sorry to hear how much trouble it caused you. I don't recall who suggested this command but it's gone now.

Thanks to @hostep for the simple solution.

Please check it and close this issue if you're happy with the resolution: http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html

**Comment by nickmarx12345678** [comment]
That should do it yeah, thanks. closing
