### ISSUE TITLE
Business Logic layer is mentioned, but no explanation of this term.

### ISSUE THREAD

**Issue by icsw** [magento/devdocs#762]
At http://devdocs.magento.com/guides/v2.1/architecture/arch_whatis.html there is Business Logic layer mentioned but no explanation of its meaning are given.

> Domain layer provides core business logic and functionality in base classes, resource models, and data access capabilities that you can extend and customize. Business logic rules, which define how data is retrieved from the database and manipulated, are stored in the Business Logic layer.

Have they equivalent meanings (synonyms)? Or, is Business Logic layer subset of Domain layer (made by developers)? Or is it something else?

**Comment by dmrachkovskyi** [comment]
Hi @icsw. Thanks for reporting this!

The guide has already been updated, Still, to fully cover the topic, the MAGETWO-60303 has been created.   Stay tuned!

**Comment by dmrachkovskyi** [comment]
The Business Logic layer is a synonym of the Domain layer, not its subset or a separate entity. Sorry for this confusion.

The [text](http://devdocs.magento.com/guides/v2.1/architecture/arch_whatis.html#domain-layer) in the Architecture Guide is now correct.

Thanks for your help!
