### ISSUE TITLE
Store scopes in config.php works only for fresh install.

### ISSUE THREAD

**Issue by milindsingh** [magento/devdocs#7625]
# General issue

## Description:
Feedback on page: /guides/v2.4/config-guide/prod/config-reference-configphp.html

- `group_id` and `store_id` is db auto increment field and cannot be taken by the provided config.php.

**Comment by BarnyShergold** [comment]
@milindsingh The scopes section (as well as the themes section) in config.php is not supposed to be added by hand but by using the app:config:dump command as detailed here : https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-config-mgmt-export.html

Magento will then add the correct values for group_ids and store_ids as they are.

If this information was added to the page you reference, would it make things clearer?

**Comment by BarnyShergold** [comment]
@milindsingh - Just a final nudge - if we don't get feedback from you in the next 3 days, then this issue will be closed for inactivity

**Comment by BarnyShergold** [comment]
@hguthrie - I've suggested a small change to the docs above for this issue but the OP hasn't responded in 3 weeks. For a second opinion - should I make the changes as suggested or should this be regarded as a non-issue?

**Comment by hguthrie** [comment]
@milindsingh  We appreciate you bringing this to our attention. This is a reference page that defines what you see in the configuration file.  @BarnyShergold provided a link to more detailed explanation above, so I am closing this request.

If you believe that this needs further review, feel free open a new issue with more detailed information and a possible solution and we can revisit. Thank you for your continued collaboration and assistance!
