### ISSUE TITLE
REST: GET /V1/products/attribute-sets/groups/list

### ISSUE THREAD

**Issue by shraddhacloudelements** [magento/devdocs#763]
I used exactly this API:
http://{site}/index.php/rest/V1/products/attribute-sets/groups/list?searchCriteria[pageSize]=100&searchCriteria[currentPage]=1

This API gives me this error:
{
  "message": "%fieldName is a required field.",
  "parameters": {
    "fieldName": "attribute_set_id"
  }
}

Just wanted to check if this is the correct way?

**Comment by keharper** [comment]
You'll have to specify a field/value/condition_type as shown here:

http://devdocs.magento.com/guides/v2.1/howdoi/webapi/search-criteria.html

Then you can add your pageSize and currentPage arguments.

**Comment by shraddhacloudelements** [comment]
That means, `attribute_set_id` is mandatory to be passed as parameters. That worked. Thanks.
