### ISSUE TITLE
Add info about creating "maintenance.enable" file in maintenance mode when CLI is used

### ISSUE THREAD

**Issue by pmonosolo** [magento/devdocs#7636]
# General issue

## Description:

Custom Maintenance page only works when you do "touch <magento_root>/maintenance.enable". When CLI is used to enable the Maintenance mode it does not create "maintenance.enable" file and therefore the custom page is not shown. 

## Possible solutions:

bin/magento maintenance:enable needs to create maintenance.enable file or a redirect for 503 should be included in the article to deal with the 503 code.

**Comment by dobooth** [comment]
Hi @pmonosolo Thanks for the issue. That command is listed in the steps on the page you provided. Is the command not working correctly for you?

**Comment by pmonosolo** [comment]
> Hi @pmonosolo Thanks for the issue. That command is listed in the steps on the page you provided. Is the command not working correctly for you?

The command works, but the article only sets up rules in NGINX to deal with "touch <magento_root>/maintenance.enable" and does not take in consideration that CLI command bin/magento maintenance:enable often is setup to run via cron and thus the maintenance.html page that you have set up will not be shown.

Here is a breakdown;

- touch <magento_root>/maintenance.enable - creates a file and nginx rules(from the article) redirect to maintenance.html

- bin/magento maintenance:enable - bypasses NGINX rules set up(from the article) and just points to /pub/errors/default/503.phtml

**Comment by dobooth** [comment]
@buskamuza We could use a consult on this. Are the docs unclear here or is the command missing something? Not sure what the expected behavior is. Thanks!

**Comment by buskamuza** [comment]
Hm. Looks like docs are not corresponding to what we have in the implementation. The command creates `var/.maintenance.flag` file. I think if docs will replace `.maintenance.enable` with `var/.maintenance.flag`, all should work as expected. Also, IP addresses can be specified with a CLI command, and will be stored in `var/.maintenance.ip`. Possibly this same file can be read to provide IP addresses in nginx config.

**Comment by BarnyShergold** [comment]
@buskamuza @dobooth @pmonosolo 
Confirmed : Magento created the maintenance.flag file in the var folder
Confirmed : Every instance of maintenance.flag in the documentation refers to it being in var

The issue the OP has raised is that if you have a CUSTOM maintenance page, you should not use the CLI method as it does not create or do what the custom steps do.

Proposal : On this page : https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-maint.html#instgde-cli-maint (and the 2.3 version) put a blue alert box that if a custom maintenance page is to be used then this page should be used https://devdocs.magento.com/guides/v2.4/comp-mgr/trouble/cman/maint-mode.html

Would this fulfill the needs of this issue?

**Comment by BarnyShergold** [comment]
@hguthrie Can you check my suggestion above and confirm if you believe it's correct? I've not had a reply back from the issue raiser
