### ISSUE TITLE
creating Coupons through magento UI

### ISSUE THREAD

**Issue by shraddhacloudelements** [magento/devdocs#765]
What is the path to `Coupons` option in Magento UI? I am sure it should be under `Sales`, but I cannot find it.

**Comment by xcomSteveJohnson** [comment]
We're not familiar with all the options in the Admin but you can start here: http://docs.magento.com/m2/2.0/ce/user_guide/marketing/price-rules-cart.html

There is also a configuration reference: http://docs.magento.com/m2/2.0/ce/user_guide/stores/configuration.html

**Comment by shraddhacloudelements** [comment]
That would be of good help. Thanks @xcomSteveJohnson.

**Comment by ccondra** [comment]
One thing I would add is that whenever you can't find something, just do a search from the user guide.  A search for "coupon" returns 27 results.  Even though I work on the user guides, I use Search all the time!

**Comment by shraddhacloudelements** [comment]
Sure. Thanks!

**Comment by tanberry** [comment]
Thanks, @ccondra . Can you throw in the URL for the User guide, for @shraddhacloudelements ?

**Comment by ccondra** [comment]
Steve included the links, but here's a link to our documentation landing page, where you can find everything that you might need:  https://magento.com/help/documentation

**Comment by shraddhacloudelements** [comment]
Thanks guys for helping me out.

**Comment by xcomSteveJohnson** [comment]
@shraddhacloudelements  Can we close this?

**Comment by shraddhacloudelements** [comment]
Thanks!
