### ISSUE TITLE
Add asynchronous variant for uiRegistry component in uiRegistry topic

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#7656]
# General issue

## Description:

This page is showing only synchronous variant of using uiRegistry component, while it's not good from performance perspective. In the JS file we have exampe how to retrieve any component using async variant: https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Ui/view/base/web/js/lib/registry/registry.js#L342-L346

## Possible solutions:

Add information about async way of retrieving ui components from registry and mark it as recommended.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
