### ISSUE TITLE
Version of symfony/console for migration tool incompatible with the rest of M2.4

### ISSUE THREAD

**Issue by ghoyle** [magento/devdocs#7676]
# M2.4 migration tool incompatible

## Description:
On trying to install the migration tool onto a clean M2.4.0 open source site I get an error saying the version of a dependent module symfony/console (v4.4.0) conflicts with other dependencies which require symfony/console (v4.1.12)

## Additional information:

`Problem 1
    - Conclusion: don't install magento/data-migration-tool 2.4.0
    - Conclusion: don't install magento/data-migration-tool 2.4.0
    - Conclusion: remove symfony/console v4.1.12
    - Installation request for magento/data-migration-tool 2.4.0 -> satisfiable by magento/data-migration-tool[2.4.0].
    - Conclusion: don't install symfony/console v4.1.12
    - magento/data-migration-tool 2.4.0 requires symfony/console ~4.4.0 -> satisfiable by symfony/console[v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - Can only install one of: symfony/console[v4.4.0, v4.1.12].
    - Can only install one of: symfony/console[v4.4.1, v4.1.12].
    - Can only install one of: symfony/console[v4.4.10, v4.1.12].
    - Can only install one of: symfony/console[v4.4.11, v4.1.12].
    - Can only install one of: symfony/console[v4.4.2, v4.1.12].
    - Can only install one of: symfony/console[v4.4.3, v4.1.12].
    - Can only install one of: symfony/console[v4.4.4, v4.1.12].
    - Can only install one of: symfony/console[v4.4.5, v4.1.12].
    - Can only install one of: symfony/console[v4.4.6, v4.1.12].
    - Can only install one of: symfony/console[v4.4.7, v4.1.12].
    - Can only install one of: symfony/console[v4.4.8, v4.1.12].
    - Can only install one of: symfony/console[v4.4.9, v4.1.12].
    - Installation request for symfony/console (locked at v4.1.12) -> satisfiable by symfony/console[v4.1.12]`

**Comment by victor-v-rad** [comment]
Hi @ghoyle 

There is a dedicated repository https://github.com/magento/data-migration-tool for Data Migration Tool related issues. Please describe details of the issue there. Like Magneto version used, how it was installed from github or composer. The same for DMT. Thank you!

**Comment by dobooth** [comment]
Closing as there is a better place for the issue.
