### ISSUE TITLE
A broken link

### ISSUE THREAD

**Issue by icsw** [magento/devdocs#769]
(I found it in page http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-install.html)

There's link http://devdocs.magento.com/guides/v2.1/install-gde/install/continue.html under text "Your install or upgrade path" that is broken.

Or, from page's source code:
`<a href="/guides/v2.1/install-gde/install/continue.html">Your install or upgrade path</a>`

**Comment by xcomSteveJohnson** [comment]
@icsw Sorry, I cannot find the link. Please confirm the page you found it on and I'll be glad to fix it ASAP.

**Comment by icsw** [comment]
It's still here.
I updated description a bit. I hope that helps.

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing it out. Fixed now. Please close this if you're happy with the resolution.

**Comment by icsw** [comment]
Thanks!
