### ISSUE TITLE
In-Store Pickup GraphQl intersection products assignments filter

### ISSUE THREAD

**Issue by swnsma** [magento/devdocs#7701]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/guides/v2.4/graphql/queries/pickup-locations.html

## Description
Update GraphQl query with newest information as soon as 
https://github.com/magento/inventory/pull/3161 - Approved 09/09/2020
https://github.com/magento/architecture/pull/419 - Merged
Will be approved and merged.

**Comment by swnsma** [comment]
@magento I am working on this

**Comment by shrielenee** [comment]
@swnsma Are you still working on the related PR #7702 ?

**Comment by swnsma** [comment]
Hi @shrielenee!
Yes, it waits for https://github.com/magento/inventory/pull/3161 to be delivered first.

**Comment by keharper** [comment]
Closed per #7702
