### ISSUE TITLE
Feedback on page: /guides/v2.4/release-notes/release-notes-2-4-0-open-source.html

### ISSUE THREAD

**Issue by chakravarthykalyan90** [magento/devdocs#7709]
# General issue

## Description:

Under "Additional security enhancements" > "Implementation of 2FA for Admin accounts, Magento.com user accounts, and Cloud SSH access" > "Securing your Magento Admin account."

It is described as 2FA is enabled by default and cannot be disabled. But actual behavior is 2FA mobule can be disabled and admin is allowed to login without it. 

![image](https://user-images.githubusercontent.com/3271931/89813613-95cf7a80-db5f-11ea-99ec-9e33967acf01.png)

## Demo Video of admin login without 2FA:

[M2.4 Admin Login WIthout 2FA](https://www.loom.com/share/fcbf999dfb67470eb1b295f0ed820590)

## Possible solutions:

Correct the description in the document from "2FA is enabled by default and cannot be disabled" to "2FA is enabled by default but can be disabled".

**Comment by chakravarthykalyan90** [comment]
@magento I am working on this

**Comment by chakravarthykalyan90** [comment]
@magento add to contributors team

**Comment by chakravarthykalyan90** [comment]
@magento I am working on this

**Comment by jeff-matthews** [comment]
See comment in #7710
