### ISSUE TITLE
REST: GET /V1/stockItems/lowStock/

### ISSUE THREAD

**Issue by shraddhacloudelements** [magento/devdocs#771]
For this API, how can I get the `scopeId` which is to be passed as one of the parameter?

**Comment by keharper** [comment]
It seems to be a bit of a mystery. Try your website ID.

**Comment by keharper** [comment]
GET /V1/store/websites

**Comment by shraddhacloudelements** [comment]
Thanks for the input, but now it gives this error:
"{\"message\":\"One or more input exceptions have occurred.\",\"errors\":[{\"message\":\"%fieldName is a required field.\",\"parameters\":{\"fieldName\":\"scopeId\"}},{\"message\":\"%fieldName is a required field.\",\"parameters\":{\"fieldName\":\"qty\"}}]}"

I gave the scopeId as website ID.

**Comment by keharper** [comment]
This is working for me. 

GET http://<server>/rest/default/V1/stockItems/lowStock/?scopeId=0&qty=10&pageSize=100

**Comment by shraddhacloudelements** [comment]
That worked for me as well. I was not passing the scopeId and qty as query. Thanks for that.

**Comment by keharper** [comment]
@shraddhacloudelements  I just want to make sure you're aware of the option to use Swagger on your own server. See http://devdocs.magento.com/guides/v2.1/rest/generate-local.html 

i got the URL above from using my local Swagger.

**Comment by shraddhacloudelements** [comment]
I am using this link: http://devdocs.magento.com/swagger/index.html#/ and postman to run the APIs and then integrating it with my App.

Well I was using the API this way:
http:///rest/default/V1/stockItems/lowStock/?searchCriteria[pageSize]=100&searchCriteria[filter_groups][0][filters][0][field]=scopeId&searchCriteria[filter_groups][0][filters][0][value]=1&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][field]=qty&searchCriteria[filter_groups][0][filters][0][value]=10&searchCriteria[filter_groups][0][filters][0][condition_type]=eq

So far all the APIs in Magento 2.0 are being used in the above format but this particular API uses the below format:
http:///rest/default/V1/stockItems/lowStock/?scopeId=0&qty=10&pageSize=100
So I had to make changes for this API in my App.
