### ISSUE TITLE
Add note about mixing cacheable and noncacheable queries in a single request

### ISSUE THREAD

**Issue by DrewML** [magento/devdocs#7718]
# General issue

## Description:
It would be great if we could list that we have a bit of a caveat with GraphQL caching.

Unlike typical REST APIs, GraphQL will let you include as many distinct queries as you'd like in a single request.

But, with Magento's Full Page GraphQL cache, a single query that is not cacheable will cause _all queries in the same request to bypass cache_.

**Example that hits cache**
```graphql
{
   urlResolver(url: "foo.html") {
      type
      relative_url
   }
}
```

**Example that completely misses the cache**
```graphql
{
   urlResolver(url: "foo.html") {
      type
      relative_url
   }
   # storeConfig is a non-cacheable query, so it invalidates
   # all caching on this request
   storeConfig {
      copyright
   }
}
```

## Possible solutions:
Developers should become familiar with the [list of cacheable queries](https://devdocs.magento.com/guides/v2.4/graphql/caching.html#cached-queries), and separate requests for cacheable data from requests for non-cacheable data

**Comment by sirugh** [comment]
> Developers should become familiar with the list of cacheable queries, and separate requests for cacheable data from requests for non-cacheable data

I wonder if it would be possible to have combined queries split into cacheable/non-cacheable combinations before sending across the network.

**Comment by DrewML** [comment]
> I wonder if it would be possible to have combined queries split into cacheable/non-cacheable combinations before sending across the network.

Sure, @fnhipster is working on something like that for his PWA.

There's a big downside though. If you're splitting the queries automagically like that, that means both requests would need to complete before your client code could "stitch" the responses back together. Means that, no matter how fast the cached query is, your component code wouldn't see it until the slow uncached query completed.
