### ISSUE TITLE
EAV Attribute Options

### ISSUE THREAD

**Issue by paul-gene** [magento/devdocs#7739]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/attributes.html

## Description

The page includes a list of options that can be set for attributes, but some are lacking a real description of what they actually do. See the screenshot for an example of 4 options with zero, useful, information.

<img width="794" alt="Screen Shot 2020-08-13 at 14 20 38" src="https://user-images.githubusercontent.com/47739147/90140729-0cdc5d00-dd72-11ea-82ab-32029a1c0f3a.png">

**Comment by BarnyShergold** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@dobooth - I'll work on this - the descriptions are rather  lacking
