### ISSUE TITLE
Feedback on page: /guides/v2.4/install-gde/system-requirements-tech.html

### ISSUE THREAD

**Issue by ivanavm** [magento/devdocs#7759]
# General issue
Elasticsearch version requerment is incorect.
## Description:
Impossible to install Magento Comunity Edition with elasticsearch 7.6.x

## Possible solutions:
Minimum required version is 7.7.x

## Additional information:
`- magento/product-community-edition 2.4.0 requires elasticsearch/elasticsearch ~7.7.0 -> satisfiable by elasticsearch/elasticsearch[7.7.x-dev, v7.7.0] but these conflict with your requirements or minimum-stability.
- magento/product-community-edition 2.4.0 requires elasticsearch/elasticsearch ~7.7.0 -> satisfiable by elasticsearch/elasticsearch[7.7.x-dev, v7.7.0] but these conflict with your requirements or minimum-stability.
- Installation request for magento/product-community-edition 2.4.0 -> satisfiable by magento/product-community-edition[2.4.0].`

**Comment by fascinosum** [comment]
hello @ivanavm, 
thank you for your contribution. From the error you provided I see that you have a conflict between the dependencies in `composer.json` of your project. The [ES Engine](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html) version does not play any role at the composer install/upgrade step.
In the above error, we see the information that your current project has a conflict with the Magento base dependency `"elasticsearch/elasticsearch:~7.7.0"`, which is not the ES Engine version, but the ES PHP library version
