### ISSUE TITLE
Questions on private page content documentation

### ISSUE THREAD

**Issue by Vinai** [magento/devdocs#776]
Hi,
reading the page http://devdocs.magento.com/guides/v2.1/config-guide/cache/cache-priv-priv.html and trying to follow along by creating my own example private content block, I don't find answers to the following questions.  
It would be great if the documentation could be improved by the original author to include more information to make it simpler to follow.

---

Why is there no example for "Replace private data in blocks with placeholders (using Knockout syntax)."? A link to some core code where that is done would be helpful.

---

Does the `data-bind="scope: 'compareProducts'"` JS identifier correspond to the item name in the `sectionSourceMap` di configuration, just in CamelCase? It seems like it does, but the documentation doesn't say so, and there is so much complex mapping going on it would be good to state such things explicitly instead of relying on the reader to make the correct assumptions.

---

Why does the private content JS have to be initialized with such boilerplate code?

```
<script type="text/x-magento-init">
    {"<css-selector>": {"Magento_Ui/js/core/app": <?php echo getJsLayout();?>}}
</script>
```

It seems the only thing that can be changed is the css selector. Can the selector be freely chosen or does it have to correspond to the section name in some way? Does it have to specify a single DOM element or can it match multiple elements?  
Is it possible to use the `data-mage-init` initialization, too? If so, an example would help to clarify.

---

In the linked UI component JS example, the selector `[data-role=compare-products-sidebar]` is also specified as part of the [JS initialization example](https://github.com/magento/magento2/blob/2.0/app/code/Magento/Catalog/view/frontend/templates/product/compare/sidebar.phtml#L46-L48), so the element should be passed to the component initialization function in JS.  
According to best practices, the view models should be decoupled from the DOM. That is is not used here is confusing and it would be good if the documentation would give a reason for it.

---

Is `$_isScopePrivate` really deprecated? It isn't marked as such in the source code:
(see https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L163 and https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L1108).

According to the documentation "This property is obsolete and won't work properly.".  
If so, why is it still present in the core code and not marked as `@deprecated`?  
A quick test shows it seems to be working correctly. Under what circumstances does it not work?

---

What if I want to render the private content server side and not in knockout?  
The obsolete `isScopePrivate()` method made that very easy and convenient.
The "new" ui component approach seems overly complicated in comparison.  
For example, if I just want to render a simple string as private content, this seems like too much work. Is there a simpler (supported) way to display private scope content?

---

On that note, is it possible to display private content without having to define a UI component?  
If so it would be great to add it to the documentation, as it would be a wonderful thing!

---

On "defining a UI component in a layout" only an example is linked, but what is that content? What is required? What can be customized? Does it have to be a `jsLayout` layout argument, or can it be anything?

**Comment by xcomSteveJohnson** [comment]
Thanks for the detailed list of questions. Created internal issue MAGETWO-56161 and contacted the source of the information. We'll try to get answers ASAP.

**Comment by antonkril** [comment]
Thanks again, Vinai. Good catch as always.

Main confustion with this page is that it describes more details about UI components than about page caching. And I see that most of your questions are about UI components, not about private content.

Specifically this question indicates the confusion most: 

> On that note, is it possible to display private content without having to define a UI component?

Yes, of course, private content can be rendered without UI components. Main point about private data is that it should not be rendered on server. You don't need a UI component for that. We provide UI components for your convenience (yes it may be convenient to use them if you have complex logic, and when we provide proper documentation). 

With any implementation of private content rendering in js, main problem that you will face, is delivering user session data to browser, and we have lightweight CustomerData JS API for that (which is only mentioned in code example). CustomerData JS API provides observable customer session data, so it's convenient to use it in KO templates - it will be re-rendered when data is updated. 

Old whole punching approach is deprecated, because it requires extra infrastructure on server, and makes private data retrieval expensive (you have to render blocks on server on ajax request).

I will create a draft of new doc for page caching.

UI component documentation is being improved by frontend team, but that is different story.

**Comment by tanberry** [comment]
Hi all... @Vinai, on the issue of UI Components... first of all thank you and @ryantfowler and community for pushing hard to get better docs around these; the comments in the Issue you opened have led to what we hope is a solid approach to vastly improving the docs, and the core action is a Doc Sprint with the frontend Devs, next week when I am in Kyiv. Details to follow... if you or Ryan have even 15 minutes to review the list of topics that we want to create during the Doc Sprint, that would be very helpful.

**Comment by Vinai** [comment]
Thank you for responding to the issue with such detail @antonkril and @tanberry. I'm looking forward to the new documentation a lot. And I would be very happy to review any documentation. What communication channel would you prefer for that? A github branch maybe?

**Comment by tanberry** [comment]
@Vinai  keep pushing, we are listening and responding as best as possible. And it's great to have the urgency around it that makes us think outside of the box. ;-)

For the new UI Components docs, here are the basics of the plan:
-- This week we are finalizing the list of topics that the community has asked for around UI Comps. I can email you that list (and I will ask Ryan and a few others as well); we would very much appreciate your feedback, both on the exact topics, and on their relative importance/prioritization. It's essential that we start off with the correct list of topics. ;-)
--Next week,in Kyiv, for our Doc Sprint we have two dedicated core developers, plus some time from an architect, scheduled for each of the five days. We will divide up the topics to be written amongst the developers, architect, our Frontend writer Sahsa and myself, and start pounding out docs... driven by the prioritized list and by lots of chocolate and coffee and whatever the team wants to keep the enthusiasm and collaboration flowing.
--The following week, we two writers will polish and edit the content produced in the Doc Sprint.. and then publish it and ask the community to review and provide both feedback and additional content. (We could do that feedback session in the form of an online, world-wide, Skypified, 24-hour Doc Sprint, but I am not sure how to ship chocolates world-wide.)

I will share the above plan with wider audience on [UI Components are painful](https://github.com/magento/magento2/issues/5906), to let the community know and start asking for community feedback.

Sound OK?

**Comment by ryantfowler** [comment]
@tanberry Glad to hear that there is action being taken at Magento, Inc in response to community feedback. Feel free to reach out to me and I'm more than willing to help in whatever way you'd like. Thanks

**Comment by Vinai** [comment]
@tanberry Wow, that sounds like a great plan! Thanks, I'm looking forward to any new content :)
Happy documentation-hacking!

**Comment by tanberry** [comment]
@Vinai and @ryantfowler , we just completed our first day of the Doc Sprint for UI components, here in the Kyiv office! Our most important step was to create the outline with the core developers, and then prioritize the topics. (We also went over our plan for how the Doc Sprint would work, agreed on demos for each new topic, process for the core developers to contribute to devdocs repo, etc). We would now like to ask for feedback on the outline: i.e. have we identified the most important topics, prioritized them correctly, etc.
Can you email me at tanberry@magento.com, please?

**Comment by Vinai** [comment]
Thanks, done

**Comment by xcomSteveJohnson** [comment]
Tracking this with MAGETWO-56161

**Comment by jeff-matthews** [comment]
@Vinai, we recently revised and reorganized the caching documentation. I haven't done an audit to see if those changes address all of the issues you reported, but I'd be grateful if you would review and let me know. Thanks!

- http://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/partial-caching.html
- http://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching.html

**Comment by Vinai** [comment]
The paragraph http://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching/private-content.html#config-cache-priv-how-block is confusing.
Especially

> The init scope on the root element is data-bind="scope: 'compareProducts'", where you define the scope name (compareProducts in this example) in your layout.

Since I originally opened the issue I've learned how the system works, but even with that understanding this sentence doesn't make any sense to me.  

I suggest not using Layout XML for the component configuration, as it is just another intermediate layer. In fact, the only relevant thing is the actual JavaScript code that uses customer-data as a dependency to pull in private content. The initialization of the UiComponent with JSON or Layout XML is not relevant in this article.
If you really want to include it, how about using plain JSON instead of layout XML - again, one less layer of indirection to keep in mind, making it easier to focus on the more relevant information.

It would be useful to add the info that unless a section is bound to an action in the section.xml, it won't be fetched by the customer-data at all. This is a common source of confusion because developers learning the system think the section.xml is only required if the private content invalidation should be bound to an action.

Instead of linking to the layout XML configuration of the compare products module, it would be more helpful to show where the `compareProducts` observable is bound in a ko template.
There it should also mention that customer-data requests the private data asynchronously. Initially it returns an empty value, but when the AJAX request for the section data is completed, the observable value is updated with the real data, and then knockout will re-render the DOM components automatically.

Probably it would be good to add "full page cache is enabled" to the "Cacheable page checklist". The reason is that many developers disable the FPC during development and might forget to turn it on when testing.

It would be helpful to explicitly state that it is not possible to show private content sections to guests who haven't yet performed a POST or PUT action. It's implicit in the current documentation, but again, I see this often as a source of confusion of developers learning the system.

**Comment by jeff-matthews** [comment]
Thanks for the detailed feedback @Vinai. We'll work on updating the docs accordingly.

**Comment by jeff-matthews** [comment]
@kokoc, it would also be helpful to get your insight on this feedback and how we can improve the documentation.

**Comment by hguthrie** [comment]
@bdenham @kokoc  What is the status on this? Is it **In Progress**?

**Comment by shrielenee** [comment]
Hey @bdenham @kokoc @osrecio - We haven't heard from you regarding this issue in two weeks or more. Due to inactivity, we are closing this issue. If you have further comments and feedback, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by shrielenee** [comment]
Hey @bdenham @kokoc @osrecio - We haven't heard from you regarding this issue in two weeks or more. Due to inactivity, we are closing this issue. If you have further comments and feedback, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!
