### ISSUE TITLE
Why use ::class only for fully qualified class names?

### ISSUE THREAD

**Issue by Vinai** [magento/devdocs#777]
The page http://devdocs.magento.com/guides/v2.0/coding-standards/code-standard-php.html states

> use PHP 5.5’s ::class keyword when referring to the fully qualified class name outside of that class

Since I'm not sure if that is on purpose or by accident, I didn't open a PR, but I think it makes no sense to only use the `::class` constant for full class names and use strings for the rest.

Since the` ::class` always is mapped to a fully qualified class name by the PHP preprocessor, there should be no need to use it only for fully qualified class names. It should be used every time a class name is referenced as a string.

### Examples:

Non imported class name:

```php
// Resolves to "\Magento\Path\To\Class"
$this->get(\Magento\Path\To\Class::class);
```

Imported class name:

```php
use Foo\Bar;

// ... other code

// Resolves to "\Foo\Bar"
$this->get(Bar::class);
```

Namespace relative class name:

```php
namespace Baz;

// ... other code

// Resolves to "\Baz\Qux"
$this->get(Qux::class);
```

Import relative class name

```php
use Magento\Framework\Data;

// ... other code

// Resolves to "\Magento\Framework\Data\Helper"
$this->get(Data\Helper::class);
```

**Comment by xcomSteveJohnson** [comment]
@antonkril Can you comment? Thanks

**Comment by xcomSteveJohnson** [comment]
@Vinai It looks like [this](https://github.com/magento/magento2/issues/4068) will be implemented soon. Does that help?

**Comment by Vinai** [comment]
Well... it's related, but I opened this issue so the wording in the documentation can be clarified. So the implementation you linked is basically the core team following the recommendation documented here.

**Comment by antonkril** [comment]
Don't see reasons to use strings for non-full names. Wording should be fixed

**Comment by jcalcaben** [comment]
I agree and see how the wording can be confusing. @Vinai may I use your examples in our docs for clarification?
