### ISSUE TITLE
consumers_wait_for_messages described in docs doesnt exist? Feedback on page: /config-guide/cli/config-cli-subcommands-queue.html

### ISSUE THREAD

**Issue by iphigenie** [magento/devdocs#7783]
# General issue

## Description:

/guides/v2.x/config-guide/cli/config-cli-subcommands-queue.html

The documentation mentions `--consumers-wait-for-messages` as a parameter that can be passed when processing message queues

Both on 2.3.4 and 2.4 this parameter results in an error  `The "--consumers-wait-for-messages" option does not exist.`

The parameter is mentioned in magento\module-message-queue\Setup\ConfigOptionsList.php where it is suggesting that it has a config path of `queue/consumers_wait_for_messages` but `bin/magento config:set` will not recognise this. 

Neither the ConsumerRunner code nor the StartConsumerCommand code have any implementation of it

## Possible solutions:

In public tickets I could not see whether this was an option removed or is a planned option in the future. I suspect someone with access to the internal backlog can figure this out

1. It's a backlog option still planned and the documentation should mention it
2. It's a gone option and it should be removed from the documentation

**Comment by meker12** [comment]
In the Magento 2.3 and 2.4 CLI reference generated from code, the `consumers-wait-for-messages` is an option for the following commands:

[`setup:config:set`](https://devdocs.magento.com/guides/v2.3/reference/cli/magento-commerce.html#setupconfigset)
[`setup:install`](https://devdocs.magento.com/guides/v2.3/reference/cli/magento-commerce.html#setupinstall)

@BaDos  Should the `--wait-for-max-messages` option be available for the `bin/magento queue:consumers:start` command?

**Comment by meker12** [comment]
@iphigenie  I submitted PR #7784 to update the _Start message queue consumers_ topic to replace the parameter descriptions with a link to the `queue:start:consumers` help, which shows the currently supported parameters for the `queue:consumers:start ` command. 

As mentioned in previous comment, it looks like the `--consumers-wait-for-messages` option is available on the following commands:

`setup:config:set`
`setup:install`

If there is a bug in the code related to the `--consumers-wait-for-messages` option, you can report an issue against the [Magento2 code repository](https://github.com/magento/magento2).

**Comment by iphigenie** [comment]
>  it looks like the --consumers-wait-for-messages option is supported by the following commands: setup:config:set

It is indeed in the documentation if you run `bin/magento help setup:config:set`

`   --consumers-wait-for-messages=CONSUMERS-WAIT-FOR-MESSAGES                                  Should consumers wait for a message from the queue? 1 - Yes, 0 - No [default: 1]`

but it seems I will have to file a bug report because try to call this and you get 

`The "--consumers_wait_for_messages" option does not exist.`
