### ISSUE TITLE
Broken DevDocs links: compman-checklist.html & extensman-checklist.html

### ISSUE THREAD

**Issue by TijnArts** [magento/devdocs#7787]
These two links seem to be broken:
https://devdocs.magento.com/guides/v2.4/comp-mgr/module-man/compman-checklist.html
https://devdocs.magento.com/guides/v2.4/comp-mgr/extens-man/extensman-checklist.html

I tried to access them from:
https://docs.magento.com/user-guide/system/tools.html

**Comment by keharper** [comment]
Closing this issue. It should have been reported in the merchdocs repo. Opened a new issue there.
