### ISSUE TITLE
What exactly POST /V1/products/attribute-sets/groups do?

### ISSUE THREAD

**Issue by shraddhacloudelements** [magento/devdocs#780]
The `POST /V1/products/attribute-sets/groups` needs an `attribute_group_id` in the POST payload. It doesn't really do a POST. Then what are the possible differences between `POST /V1/products/attribute-sets/groups` and `PUT /V1/products/attribute-sets/{attributeSetId}/groups`?

**Comment by keharper** [comment]
`attribute_group_id` isn't actually required for `POST /V1/products/attribute-sets/groups` .  If the model schema for a POST operation that creates something contains an `id`, quite often that `id` is generated. 

The minimum payload looks like this:

```
{
  "group": {
    "attribute_group_name": "My New Attribute Group",
    "attribute_set_id": 4
  }
}

```
where `attribute_set_id` identifies the attribute set to use for populating the group with default attributes. 

You would then use the PUT call to further refine the attribute sets in the group.

This is an old issue and I'm sure @shraddhacloudelements has figured this out through other means. Closing now, but feel free to re-open.
