### ISSUE TITLE
Feedback on page: /guides/v2.4/graphql/mutations/update-cart-items.html

### ISSUE THREAD

**Issue by mmborado** [magento/devdocs#7818]
# General issue

## Description:

Query does not return correct cart data after removing multiple items

## Additional information:

After setting the quantities of multiple items to 0 the cart returns, but only removes 1 item.
If I had 3 items in cart and set all 3 to be removed, then the cart would display 2 items. 

I queried for the cart after the mutation and it shows that all the items have been removed
so the cart is still removing the items, but the `uptdateCartItems` query does not return correct data.

**Comment by keharper** [comment]
Hi @mmborado. I replicated your scenario and got the same results as you. However, this is a code bug, not a documentation bug. Please open an issue on the code repo, https://github.com/magento/magento2/issues, so that this can be fixed.
