### ISSUE TITLE
2.4 index status labels are not correct in documentation

### ISSUE THREAD

**Issue by variax20** [magento/devdocs#7820]
# General issue

## Description:

The indexer status labels are different in 2.4 compared to what documentation says
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing.html

## Possible solutions:

Update the status labels from "Valid, Invalid, Working" to "Ready, Reindex Required, Processing"

## Additional information:

N/A

**Comment by shrielenee** [comment]
@BarnyShergold You working on this?
