### ISSUE TITLE
Feedback on page: /guides/v2.4/frontend-dev-guide/css-topics/css_debug.html

### ISSUE THREAD

**Issue by harakiri-cat** [magento/devdocs#7824]
# General issue

## Description:

Wrong paragraph 5 
> Add your theme to Grunt configuration. To do this, in the dev/tools/grunt/configs/themes.js file, add your theme to module.exports like following:

## Possible solutions:

You should create dev/tools/grunt/configs/local-themes/themes.js file
or edit
grunt-config.json file

## Additional information:

Gives and error:
 **$grunt clean**
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module '.../dev/tools/grunt/configs/local-themes'
Warning: Task "clean" not found. Use --force to continue.

Aborted due to warnings.

**Comment by BarnyShergold** [comment]
Hi @harakiri-cat - Can you add more information to the title of this issue so someone just reading the list of issues can have an idea what it's about? Thanks
