### ISSUE TITLE
Add more details for Elastic Search version compatibility

### ISSUE THREAD

**Issue by dooblem** [magento/devdocs#783]
Hello,

In:
http://devdocs.magento.com/guides/v2.1/config-guide/elasticsearch/es-overview.html#es-install-es

> Magento Enterprise Edition (EE) version 2.1.x supports Elasticsearch versions 1.7, 2.0, and 2.1.

However, the install commands will install the latest 2.x version (2.3 under Debian).

I did not test Magento with ES 2.3. So I don't know if it's working. Can you either:
- Launch regression testing and update the doc , if Magento is ES 2.3 compatible.
- Update the install commands in the doc, to install ES 2.1 specific version.

Thanks in advance,
Marc

**Comment by xcomSteveJohnson** [comment]
We're having an issue publishing at this time but the answer is, yes, 2.3 is supported. When I publish the update I'll put a link here.

**Comment by xcomSteveJohnson** [comment]
You can now see the changes. I put more detail [here](http://devdocs.magento.com/guides/v2.1/config-guide/elasticsearch/es-overview.html#es-spt-versions).

Please close this is you're happy with the resolution.

**Comment by dooblem** [comment]
Great! thanks.
