### ISSUE TITLE
Feedback on page: /guides/v2.4/extension-dev-guide/factories.html - Whats the benefit of using factories?

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#7836]
# General issue

## Description:

It does not explain why factories are used. What are the benefits? Why were they introduced?

## Possible solutions:

Explain benefits.

**Comment by BarnyShergold** [comment]
@Eddcapone @meker12 
I'm not sure if it's the place of technical documentation of a product to have to explain why things are the way they are. If we had to do this then where would it end? IMO a developer accepts that code works the way it does (if they want justification they can ask) and needs a technical document to explain the WHAT and the HOW. 

is there a need to explain the reasons for all the elements in Magento?

What does everyone else think?

**Comment by Eddcapone** [comment]
"IMO a developer accepts that code works the way it does "
I can only accept something that I understand. I never heard about factories before, from my understanding it is used for better performance, because objects are only loaded when needed. Is it that bad to add a simple explanation whats the idea behind factories or at least add a reference to an article which explains this? I thought it is a magento thing and used nowhere else.

**Comment by BarnyShergold** [comment]
Ah - what you need it more in depth information into what factories are and what they are for? I can understand that. 

Factories have been around for a long time : https://en.wikipedia.org/wiki/Factory_(object-oriented_programming)

So - question - if you read the Wiki article about a high-level view of factories, does that make Magento's use of them clearer? Just trying to see what sort of improvement is needed to the docs (might not be that need to make the changes as I'm not a developer anymore). Does the USE documentation need improvements?

**Comment by Eddcapone** [comment]
Yes a reference to wikipedia would make the topic clearer IMO and it would point out that this is a concept not only used in magento.

**Comment by meker12** [comment]
For high-level design questions, you can review discussions and decisions in the https://github.com/magento/architecture repository.

We are closing this issue, but we kept #7837 open with the request for improving the information provided in the example.
