### ISSUE TITLE
Describe needed parameters for a factory create

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#7837]
# General issue

## Description:

>     The example below shows the construction of a Magento\Search\Model\Autocomplete\Item object by passing in an array of parameters to a factory:
> 
>     $resultItem = $this->itemFactory->create([
>       'title' => $item->getQueryText(),
>       'num_results' => $item->getNumResults(),
>     ]);

How do we know which parameters we can pass to the Factory create method?
I looked up the class **Magento\Search\Model\Autocomplete\Item** and it only has a method "getTitle" so why did the autor added **num_results** ?

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/factories.html

**Comment by BarnyShergold** [comment]
@Eddcapone - Can you please either rename this Issue OR better, merge it with #7836 - The issue can simply be to improve this one page for multiple reasons - then we can have one PR to deal.

**Comment by Eddcapone** [comment]
@BarnyShergold Those are two unrelated feedbacks though, sure that I should merge it?

**Comment by BarnyShergold** [comment]
As I said - if you don't want to merge them - can you give them different and more meaningful titles? At the moment we have 2 issues with exactly the same name - gets confusing. People should have an idea about what an issue is by just reading the title and not having to open it - there are a lot of issues :)

**Comment by Eddcapone** [comment]
Sure, the title was auto generated.

**Comment by dineshvb** [comment]
Related Issue - #6011

**Comment by dineshvb** [comment]
It is resolved and merged
