### ISSUE TITLE
Feedback on page: /guides/v2.4/graphql/queries/pickup-locations.html

### ISSUE THREAD

**Issue by Spectre-Creative** [magento/devdocs#7847]
# General issue
Stores do not show up when searching for city/postcode. 

## Description:
Checkout Page: In-Store Pickup "Select Store" input. If I type something then delete it, all stores show. But if I type anything (city or post code) no stores found.

The response gives items: [] when a search_term is given.

## Possible solutions:
//

//

## Additional information:
//

Have tried on the /swagger page as well. Same result.

**Comment by irenelagno** [comment]
@magento give me test instance

**Comment by irenelagno** [comment]
@magento give me 2.4-develop instance

**Comment by irenelagno** [comment]
@magento give me 2.4-develop instance

**Comment by keharper** [comment]
Hi @Spectre-Creative, welcome to Magento.

It looks like you've find a code bug. and this is not the place to report that. Please go to https://github.com/magento/inventory and log an issue there.

Tagging @swnsma because he contributed the code and the devdocs page. He might know more.
