### ISSUE TITLE
More details needed about supported field types

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#7862]
# General issue

/guides/v2.4/config-guide/prod/config-reference-systemxml.html 

## Description:

There is information missing about the different supported types for fields, for example text, select, etc.
In this code you can see that the type of the field is `select`.

```
<field id="A_UNIQUE_FIELD_ID" translate="label" sortOrder="10" showInDefault="0" showInWebsite="0" showInStore="1" type="select">
    <label>Feature Flag Example</label>
    <comment>This field is an example for a basic yes or no select.</comment>
    <tooltip>Usually these kinds of fields are used to enable or disable a given feature. Other fields might be dependent to this and will only appear if this field is set to yes.</tooltip>
    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
</field>
```
There is a list missing with all the various types available

**Comment by dobooth** [comment]
Let's add a list of form field types to the `type' row in the Field attribute reference table.
