### ISSUE TITLE
GraphQL: Add schema coverage for multiple wishlists

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7866]
# Community engineering issue

Add documentation for the following mutations

createWishlist
deleteWishlist
copyProductsToWishlist
moveProductsToWishlist
updateWishlist

The `customer` query will need to be updated as well.

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28551

Magento 2 GitHub PR: https://github.com/magento/partners-magento2ee/pull/248

Internal ticket: MC-37628

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

**Comment by dobooth** [comment]
Test comment

**Comment by keharper** [comment]
Fixed #7888
