### ISSUE TITLE
Populating default values from config.xml

### ISSUE THREAD

**Issue by Stoyvo** [magento/devdocs#7877]
# Example of Default Value in config.xml

Page: /guides/v2.4/ext-best-practices/tutorials/dynamic-row-system-config.html

## Description:

An example of config.xml default nodes, to provide a value on setup:upgrade.

It will answer the question of: How does a developer populate default values from config.xml?

## Possible solutions:

Add config.xml default value to document.

**Comment by BarnyShergold** [comment]
@Stoyvo 
As someone who has written dynamic row configs I can say that I'm very sure there is no easy way to do this as ALL the data for a dynamic row config is stored in a single config in the core_config_data table with all the data in a serialised string - the backend model explodes this and populates the rows & fields.

What you could do is add the data that you want as default to a local instance and then extract the serialised and used that as the default. I'm going to look into this to see if it will work

**Comment by Stoyvo** [comment]
@BarnyShergold I always imagined something like this:
`<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <my_config_section>
            <my_field_group>
                <my_dynamic_row_elm type="dynamic_rows">
                    <item>
                        <my_row_field_1>My</my_row_field_1>
                        <my_row_field_1>Test</my_row_field_1>
                        <my_row_field_1>Row 1</my_row_field_1>
                    </item>
                    <item>
                        <my_row_field_1>My</my_row_field_1>
                        <my_row_field_1>Test</my_row_field_1>
                        <my_row_field_1>Row 2</my_row_field_1>
                    </item>
                </my_dynamic_row_elm>
            </my_field_group>
        </my_config_section>
    </default>
</config>
`
Possibly an <items> node.

**Comment by BarnyShergold** [comment]
@Stoyvo - I've found out how you can do this without any development

Will work on the documentation
