### ISSUE TITLE
Delete unnecessary topic

### ISSUE THREAD

**Issue by belbiy** [magento/devdocs#7878]
# General issue

page: /guides/v2.4/install-gde/continue-to-install.html

## Description:

Found some weird page while browsing the install guide:

1. This page is missing a title.
2. There's almost no real content on this page.

## Possible solutions:

Perhaps this page needs to be removed?

**Comment by BarnyShergold** [comment]
@meker12 This page on 2.4 has had the information about the Setup Wizard removed and is now redundant.

I suggest : 
1. Removing the page completely from 2.4 and redirecting to - https://devdocs.magento.com/guides/v2.4/install-gde/bk-install-guide.html
2. Add the title "Install Option" on 2.3

Do we concur?

**Comment by meker12** [comment]
> 1. https://devdocs.magento.com/guides/v2.4/install-gde/bk-install-guide.html

I would defer to @jeff-matthews, but here are my thoughts:

1.  Agreed: Remove the page completely from 2.4 and redirect to - https://devdocs.magento.com/guides/v2.4/install-gde/bk-install-guide.html

2.  Alternative: Remove the page completely from 2.3 and redirect to - https://devdocs.magento.com/guides/v2.3/install-

Jeff completed the updates to remove Web setup wizard, so I'm sure he has more context.

**Comment by jeff-matthews** [comment]
@BarnyShergold, I concur with your suggestions.
