### ISSUE TITLE
Version switcher should not default to the home page but should just replace 2.0 with 2.1

### ISSUE THREAD

**Issue by paales** [magento/devdocs#789]
I frequently find pages through google which refer to Magento 2.0. When I switch I expect to find the same page for Magento 2.1, but it redirects met to the home page.

**Comment by tanberry** [comment]
Yep, that's drives me nuts, too, @paales ! We are working in it, or more specifically, @jcalcaben on the DevDocs team is working on it. Thanks for your feedback, please keep it coming.

**Comment by paales** [comment]
Thanks 😄

**Comment by xcomSteveJohnson** [comment]
I think this is fixed. Please check and close if you're happy with it.

**Comment by paales** [comment]
YEAH! 👍
