### ISSUE TITLE
How to get access to the Fastly Admin UI?

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#7892]
# General issue

Page: /cloud/cdn/configure-fastly.html

## Description:

Some merchants have been asking how to get access to the Fastly Admin UI.

The article currently mentions this:
"You need the Fastly credentials to configure Fastly CDN services from the Magento Admin UI and to submit Fastly API requests."

For the sake of clarity, I think it should emphasize/add the caveat that we do not provide Fastly Admin UI access. 

## Possible solutions:

I'm not sure whether/how this information should be posed in the article, but the reason for that is the Fastly account is owned by Magento with sub-accounts created for each merchant. 

However, there's no "role management/segregation" feature available within the UI, which means that any user who has been given access to the Admin UI would have the ability to access the sub-accounts.

**Comment by BarnyShergold** [comment]
I agree - it's quite often someone will post to #cloud or #fastly asking for this.

How about adding a blue info box underneath -
With Magento Cloud, Fastly Admin UI access is not provided. Any issue that cannot be solved through the Fastly Admin in Magento should be referred to Magento Support.

**Comment by ak77-prime** [comment]
Sounds good – specific verbiage about opening a support ticket (how-to, if applicable) could probably be included.

“. Any issue that cannot be solved through the Fastly Admin in Magento should be referred to Magento Support.”

Anthony Chico
technical SUPPORT ENGINEER
Magento CUSTOMER ENGINEERING
T +1 424.258.3354  |  C +1 626.400.3699
anchico@adobe.com<mailto:anchico@adobe.com>
3640 Holdrege Ave, Los Angeles, CA, 90016, USA
[cid:image001.png@01D68D03.0A0C12B0]


[cid:image002.png@01D68D03.4FFAE7B0][cid:image004.png@01D68D03.0A0C12B0]
