### ISSUE TITLE
Information needed on authentication keys for upgrade

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/devdocs#791]
As per following link http://devdocs.magento.com/guides/v2.1/comp-mgr/upgrader/upgrade-start.html
We must use the same authentication keys which we used to install Magento.

> For upgrade or update, you must use the same authentication keys you used to install the Magento software. For example, you cannot use Magento CE authentication keys to update or upgrade Magento EE or vice versa. You also cannot use:
> 
>     Another user's authentication keys
>     Shared account authentication keys

I have a question suppose if I lost the keys which I used to install the Magento and later I recreated new keys then in this case will I be able to upgrade?

**Comment by xcomSteveJohnson** [comment]
I had been meaning to try this myself for some time so thanks for asking. I think the answer to your question, strictly speaking, is your upgrade should work unless you or someone else disabled them.

What I did:

1. Took a CE 2.0.7 system and knew what keys I had used.
2. In my magento.com account, disabled those keys.
3. Created a new pair.
4. Used the Web Setup Wizard to upgrade to 2.1.0 with no issues.

Repeated the test a little more complex:

1. Installed CE 2.0.7 fresh, saving the auth keys in `auth.json`
2. Added the keys to System Configuration.
3. Upgraded to CE 2.0.9 using the original keys.
4. Disabled the keys.
5. Created new keys, added them in System Configuration.
6. Upgraded to CE 2.1.0 without issues.

**Comment by xcomSteveJohnson** [comment]
@tiwarimukesh Can we close this?

**Comment by tiwarimukesh** [comment]
@xcomSteveJohnson You can close this ticket.
