### ISSUE TITLE
Instructions around message queues are unclear / contradictory

### ISSUE THREAD

**Issue by develpr** [magento/devdocs#792]
The docs here: https://github.com/magento/devdocs/blob/develop/guides/v2.1/config-guide/mq/config-mq.md

In general the documentation around message queues is lacking in my opinion (where is the documentation around how a person actually published a message to one of the queues that were created? How does one trigger the generation of these queues in the queue provider?), but reading through the docs that exist you will see:

>  If request is specified, **then also specify `response` if the message is asynchronous**.

However in the table below I see:

> `response` - Specifies the format of the response. This parameter is required if you are defining a synchronous topic. **Omit this parameter if you are defining an asynchronous topic.**

It's possible that I am simply not understanding / reading through enough of the code yet to "get it", and perhaps one comment is referring to an asynchronous _message_ and the other is referring to an asynchronous _topic_, but even if what is written here is technically correct it seems confusing and unclear to me.

edit: I'll add that the code out there for how to actually "use" these queue's is not very clear either. The sample xml for creating defining the consumer and queue uses examples that involved RPC classes. At least to me, a great example would be something common, for example defining a topic related to new orders being placed, and publishing a message using a sample plugin or something. Then, on the consumer side, creating the xml required to consume said new order message from a queue and so something with it.

**Comment by keharper** [comment]
I created internal issue MAGETWO-56855 to provide better examples and clarification. The message queue development team is currently working on other tasks, so it might take a few weeks to get back to you. I definitely want better examples too.

In the first line that you quoted, the last word should have been "synchronous". That correction will be pushed out immediately.

**Comment by develpr** [comment]
Awesome, thanks for following up @keharper !

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to create a new issue if necessary. Thank you for continued collaboration and assistance!
