### ISSUE TITLE
Update/cron.php has been removed. Need to update doc to reflect

### ISSUE THREAD

**Issue by ChrisOrlando** [magento/devdocs#7923]
# General issue

Affected topic: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html

## Description:

This text:
> The update/cron.php file exists in Composer- and archive-based Magento installations. It does not exist if you installed Magento by cloning the Magento 2 git repository.

Seems to say that the Magento archive should contain an update/cron.php file within it, but it does not:
```
$ md5sum magento-ce-2.4.0-2020-07-24-11-15-38.tar.gz
66d78b2b785d5689b556c420f96bf370  magento-ce-2.4.0-2020-07-24-11-15-38.tar.gz
$ tar -tf magento-ce-2.4.0-2020-07-24-11-15-38.tar.gz| grep cron.php
pub/cron.php
vendor/magento/magento2-base/pub/cron.php
```

Additionally the two "optional" cron jobs mentioned in this document don't seem to work at all in Magento 2.4.0. So they should be removed from the documentation, or it should be mentioned in the documentation that they were removed in 2.4.0 rather than say they are optional.

## Possible solutions:

Update the documentation to make it clear that this is _not_ included in the archive or include it in the archive.

If it should not be included in the archive, the documentation should be updated around creating cron jobs. If we follow the instructions laid out in the current document, the cron job that requires the updates/cron.php file will not work on Magento 2.4.0 because the file is absent.

Additionally, update the code sample to remove the obsolete commands:

```
#~ MAGENTO START c5f9e5ed71cceaabc4d4fd9b3e827a2b 
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento cron:run 2>&1 \| grep -v "Ran jobs by schedule" >> /var/www/html/magento2/var/log/magento.cron.log
* * * * * /usr/bin/php /var/www/html/magento2/update/cron.php >> /var/www/html/magento2/var/log/update.cron.log
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento setup:cron:run >> /var/www/html/magento2/var/log/setup.cron.log #~ MAGENTO END c5f9e5ed71cceaabc4d4fd9b3e827a2b
```
--

## Additional information:

A related issue on the Magento2 repo: https://github.com/magento/magento2/issues/29872

**Comment by BarnyShergold** [comment]
@ChrisOrlando 
Given that they have removed these from 2.4.0 (as per the linked issue) I would suggest that making the 2.4 version of this page differ from 2.3 and do the following -
Remove the /update/cron.php entry in the crontab example.

Change the information box that starts with "The update/cron.php" ..... to (and make it an alert box) - 

> The update/cron.php has been removed in Magento 2.4.0, if this file exists on your installation, it can be safely removed.
> 
> Also any reference to update/cron.php should be removed from the crontab

update/cron.php is removed from the "All" group definition

I'm a bit unclear what you are referring to in this statement "Additionally the two "optional" cron jobs mentioned in this document don't seem to work at all in Magento 2.4.0. So they should be removed from the documentation," can you indicate the documentation that you are referring to please?

Let me know if the above meets your expectations and I'll get on with it :) We can fine tune after the first push

**Comment by ChrisOrlando** [comment]
@BarnyShergold 
> I'm a bit unclear what you are referring to in this statement "Additionally the two "optional" cron jobs mentioned in this document don't seem to work at all in Magento 2.4.0. So they should be removed from the documentation," can you indicate the documentation that you are referring to please?

The page https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html

It mentions three cron jobs, while two of them don't work at all in 2.4.0 and are no longer needed in this Magento version. Removing these cron jobs from the example in the 2.4 version of the page and updating the info box to explain they have been removed makes sense. to me

**Comment by BarnyShergold** [comment]
@ChrisOrlando - PLease can you confirm which 2 crons don't work in 2.4?

**Comment by hostep** [comment]
@BarnyShergold, see: https://github.com/magento/magento2/issues/29872#issuecomment-686783490

Additionally, we've [added](https://github.com/magento/magento2/pull/24187) that `--non-optional` flag in Magento 2.3.4 because those two crontab entries were optionally if you weren't using the web set up wizard, but now that the web set up wizard has been removed in Magento 2.4.0 (and those two cronjobs as well), the flag `--non-optional` is currently not very useful anymore, so I don't know if we need to remove [the documentation](https://github.com/magento/devdocs/pull/6428/files) for it as well (and make it a hidden feature), or keep the documentation for this flag? (currently in 2.4.0, if you use the flag or not use it, it will result in the same behavior, at least until new crontab entries are added one day in the future ...)

Also, we should probably update the Magento 2.4.0 release notes and make a mention that if people upgrade from < 2.4.0 to >= 2.4.0, that they should amend their crontab and remove those two obsolete entries in case they had them specified.

**Comment by ChrisOrlando** [comment]
@BarnyShergold 

This cron job is required in all Magento 2 versions:
```
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /var/www/html/magento2/var/log/magento.cron.log
```

These two are optional until version 2.4.0 where they became inoperable:
```
* * * * * /usr/bin/php /var/www/html/magento2/update/cron.php >> /var/www/html/magento2/var/log/update.cron.log
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento setup:cron:run >> /var/www/html/magento2/var/log/setup.cron.log
```

**Comment by BarnyShergold** [comment]
@ChrisOrlando - Please take a look at #7944 (for some reason I can't flag you on the PR) - check my comments

**Comment by ChrisOrlando** [comment]
@BarnyShergold 
Thanks for putting that together. I added some comments on the PR https://github.com/magento/devdocs/pull/7944

**Comment by BarnyShergold** [comment]
@ChrisOrlando - Comments addressed and release notes added if you'd like to take another look

**Comment by ChrisOrlando** [comment]
@BarnyShergold lgtm -- approved. Thanks for taking care of this!
