### ISSUE TITLE
Navigation could be clearer

### ISSUE THREAD

**Issue by paales** [magento/devdocs#793]
Go to http://devdocs.magento.com/guides/v2.1/ui-components/ui-component.html

In the left navigation you see all the navigation for the UI-components, but you don't see that these pages are part of the Developers section. I'd suggest to include all other Developer topics to the left-navigation as well + a link back to 'overview'.

Documentations that get it right in my opinion:
https://stripe.com/docs/api
http://redux.js.org/

**Comment by xcomSteveJohnson** [comment]
Can you help me understand why disparate chunks of information related to development must share the same TOC? I think this would result in a huge and unusable TOC and result in complaints about "why am I seeing information about REST when I all am interested in is frontend development"?

Would breadcrumbs be equally effective?

Thanks

**Comment by hostep** [comment]
Or just add an active state to the main menu item when a subpage of that menu item is active, that will probably also resolve the issue?

**Comment by xcomSteveJohnson** [comment]
Please elaborate because I don't understand your request. Thanks. What is a "main menu"?

Do Stripe and Redux do this?


Thanks

**Comment by hostep** [comment]
Main menu:
![screen shot 2016-08-20 at 21 25 30](https://cloud.githubusercontent.com/assets/85479/17833407/b07a9b28-671c-11e6-942b-c4633042949f.png) ;)

There is currently no indication what item of the menu is active when you are on a subpage of the item (everything is in white text).

**Comment by xcomSteveJohnson** [comment]
Thanks for clarifying. Can do.

**Comment by jcalcaben** [comment]
Update: We are currently planning a site redesign where this issue will be addressed.

**Comment by xcomSteveJohnson** [comment]
@hostep Has the new design addressed this?

**Comment by hostep** [comment]
Hi Steve, I don't think so.
The main menu at the top still has no indication of what section is currently active. And also in its dropdown I think it would be handy to see which submenu item is currently active.

But these are just nice-to-haves, it doesn't really bother me.

**Comment by xcomSteveJohnson** [comment]
Created internal issue MAGETWO-62461 to track.

**Comment by xcomSteveJohnson** [comment]
I'm pretty sure we've decided not to do this because we have breadcrumbs. Feel free to reopen if you disagree or if that isn't satisfactory.

**Comment by paales** [comment]
@xcomSteveJohnson For me the breadcrumbs are fine by me. Please note that we can't reopen the issue if you have closed it, I can only reopen if I have closed it my self.

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing that out. I was copying what they say in the core Magento GitHub. Maybe they advise to create a new issue instead of reopening the same closed one. I'll say it that way in the future.
