### ISSUE TITLE
Feedback on page: /guides/v2.4/rest/bk-rest.html

### ISSUE THREAD

**Issue by kishanbharda** [magento/devdocs#7930]
# General issue

## Description:

Getting "404 Page not found" when I navigate to Admin REST endpoints by clicking one side menu Quick Reference > REST Endpoint (ReDoc) > Admin REST endpoints.

## Possible solutions:

Repairs the url

## Additional information:

I opened https://devdocs.magento.com/guides/v2.4/rest/bk-rest.html , this displays me REST API Overview section and a sidebar to navigate to different section. But, when I click on one of menu item Quick Reference > REST Endpoint (ReDoc) > Admin REST endpoints, it displays me "404 Page not found" page. 
![image](https://user-images.githubusercontent.com/39869106/94104064-bcb5e780-fe53-11ea-8cc2-c2f1ed4469d4.png)

This also happen when I navigate using any menu item of Quick Reference > REST Endpoint (ReDoc) .

**Comment by jeff-matthews** [comment]
Thanks for reporting @kishanbharda. We recently updated the URLs to include the patch level number and we forgot to update links in the docs. The new link should be magento.redoc.ly/2.4.0-admin

**Comment by BarnyShergold** [comment]
@jeff-matthews - I'm just updating that menu point

**Comment by jeff-matthews** [comment]
Perfect! Thanks @BarnyShergold!
