### ISSUE TITLE
JS error, sample code on the Collapsible widget page

### ISSUE THREAD

**Issue by nazaridak** [magento/devdocs#7935]
# Bug report

## Description
Link: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_collapsible.html

![image](https://user-images.githubusercontent.com/43548684/94237695-e89aa100-ff17-11ea-8eda-4864f4765036.png)

![image](https://user-images.githubusercontent.com/43548684/94237727-f4866300-ff17-11ea-8bc2-2274e2d9a9a8.png)

Also, the result isn't displayed correctly:
![image](https://user-images.githubusercontent.com/43548684/94237782-108a0480-ff18-11ea-88fc-e281df2d453c.png)

### Steps to reproduce

Open the page: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_collapsible.html

## Expected result

JS error isn't reproduced.
The result is displayed correctly.

**Comment by BarnyShergold** [comment]
@shrielenee - Given the nature of this issue and I can't find reference to _satellite, I would class this as either an issue because of the OPs setup or a code bug not a documentation issue?

**Comment by shrielenee** [comment]
@BarnyShergold This feels like a code issue. Traditionally we would close this issue with a message similar to:

> Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!

If we want to ensure it IS a code issue, not a docs issue, we would ping an architect/engineer. Let me know how you think is best to proceed!

CC @keharper

**Comment by BarnyShergold** [comment]
I'm very sure it's a code issue but I'd like to be certain, so would like to hear from @keharper :)

**Comment by gelanivishal** [comment]
@magento I am working on this
