### ISSUE TITLE
Add Docs For Missing Integration Test Annotations

### ISSUE THREAD

**Issue by sprankhub** [magento/devdocs#7936]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/test/integration/annotations.html

## Description

The docs do not list all possible integration test annotations. The following annotations are missing:

* `@magentoAdminConfigFixture`
* `@magentoDataFixtureBeforeTransaction`
* `@magentoIndexerDimensionMode`

## Possible solutions

The missing annotations should be listed and described.

## Additional information

n/a

**Comment by BarnyShergold** [comment]
@keharper - If you, or another, can define the three annotations above as the other have been on the page, I am happy to write them up.

**Comment by BarnyShergold** [comment]
@magento I am working on this

**Comment by keharper** [comment]
@dobooth Any insights?
