### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/composer.html

### ISSUE THREAD

**Issue by ecarlseen** [magento/devdocs#7940]
# General issue

## Description:

The example command for installing Magento2 from the command line is incorrect. There should not be equals signs (=) between the command line parameter names and the command line parameter options.

## Possible solutions:

Change text to read:

```
bin/magento setup:install \
--base-url http://localhost/magento2ee \
--db-host localhost \
--db-name magento \
--db-user magento \
--db-password magento \
--admin-firstname admin \
--admin-lastname admin \
--admin-email admin@admin.com \
--admin-user admin \
--admin-password admin123 \
--language en_US \
--currency USD \
--timezone America/Chicago \
--use-rewrites 1
```

**Comment by BarnyShergold** [comment]
@ecarlseen - Actually BOTH options are valid. For clarity and consistency the = version has always been shown in the documentation and should remain as it might cause confusion if changed. 

@shrielenee - I don't think the documentation should be changed - do you concur?

**Comment by shrielenee** [comment]
@BarnyShergold  Concur!

**Comment by BarnyShergold** [comment]
Issue is being closed to an agreement that no update is required. 

Thank you to @ecarlseen for raising the issue for discussion.
