### ISSUE TITLE
Remove reference to the sample Magento_SamplePaymentGateway module

### ISSUE THREAD

**Issue by kananinj** [magento/devdocs#7958]
# General issue

Affected topic: /guides/v2.3/payments-integrations/base-integration/module-configuration.html

## Description:

**In magento 2 sample payment gateway module link not found on github**

**Comment by gelanivishal** [comment]
Hi @keharper, Need to remove this line from docs or any other solution?

**Comment by keharper** [comment]
@gelanivishal @kananinj and anyone else watching.

We have multiple links to the magento-samples repo, which has been made private. There is no plan to make the repo pubic again. We have to research whether we can add limited code samples in topics that reference the repo, delete the references, or delete the entire topic.

**Comment by jeff-matthews** [comment]
I started a wiki page to track our decision making process: https://github.com/magento/devdocs/wiki/Archived-code-samples

**Comment by kananinj** [comment]
@gelanivishal
now it public repository.. 
https://github.com/magento/magento2-samples

i hope its good for us.

**Comment by jeff-matthews** [comment]
Thanks @kananinj! Confirmed that the repo is publicly accessible again.
