### ISSUE TITLE
Default is not allowed - Feedback on page: /guides/v2.4/extension-dev-guide/declarative-schema/db-schema.html

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#7959]
# General issue

## Description:

I tried to modify a colum and set the default value to NULL:

```
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
  <table name="catalog_product_entity_varchar" resource="default">
    <column xsi:type="text" name="value" nullable="true" comment="Value" default="0"/>
  </table>
</schema>
```

But I get default is not allowed.

```
php bin/magento setup:db-schema:upgrade
Schema creation/updates:

In Filesystem.php line 156:

  The XML in file "/home/x/y/app/code/x/Base/etc/db_schema.xml" is invalid:
  Element 'column', attribute 'default': The attribute 'default' is not allowed.
  Line: 4

  Verify the XML and try again.
```

I don't understand why I get this since default is also listed in the documentation as valid attribute:

> default | Initializes the column with the specified default value. The default value should have the same datatype defined in xsi:type.
> -- | --

I even tried to set default to a string, just like the type `default="xy"` but it still throws the same error.

**Comment by BarnyShergold** [comment]
@Eddcapone - The documentation is correct. You can have a default value on a text field in MySQL (you didn't used to be) but it is not advised as the same string as to be applied to every row in the table - which could eat up a lot of data.

For a text field the default is NULL in any case you don't need to set it. If you check all the schemas in Magento, not one has a default on a text.

Also default="0" is not NULL is it the textual value of "0" (NULL is no value not zero)- in the specific example given, the 'value' field already has a default of NULL

If you describe the table in question you get 👍-
mysql> describe catalog_product_entity_varchar;
```
+--------------+----------------------+------+-----+---------+----------------+
| Field        | Type                 | Null | Key | Default | Extra          |
+--------------+----------------------+------+-----+---------+----------------+
| value_id     | int(11)              | NO   | PRI | NULL    | auto_increment |
| attribute_id | smallint(5) unsigned | NO   | MUL | 0       |                |
| store_id     | smallint(5) unsigned | NO   | MUL | 0       |                |
| value        | varchar(255)         | YES  |     | NULL    |                |
| row_id       | int(10) unsigned     | NO   | MUL | NULL    |                |
+--------------+----------------------+------+-----+---------+----------------+
5 rows in set (0.01 sec)

```
In any case, if you were to want to set the value to something else default="??" should work. This means you may have found a bug in the Magento code, not the documentation. Therefore you need to raise this as an issue on magento/magento2 if you wish to pursue this issue further.

As this is not deemed a DEVDOCS issue, this issue will be closed.

As a side note - why are you trying to change the default text value on a Core Magento EAV table?
