### ISSUE TITLE
New Topic - How to create custom field types for system fields (admin configuration)

### ISSUE THREAD

**Issue by BarnyShergold** [magento/devdocs#7961]
# New topic request

## Description

/guides/v2.4/config-guide/prod/config-reference-systemxml.html - will soon have an updated section as to the different field types available for system fields. However, it is possible to create and use custom field types. A new topic to describe how to use this feature, with examples, would be desirable. With a link to it from the original topic.

## Content checklist

-  [ ] The topic provides an explanation of how custom field types work.
-  [ ] The topic provides steps for creating and using custom field types.
-  [ ] The topic contains code samples that shows how these are created.
-  [ ] Must have a link from the original topic

**Comment by keharper** [comment]
The topic @BarnyShergold mentioned in the description was updated in #7948.

**Comment by BarnyShergold** [comment]
@keharper - Yes but this came out of that. There is no topic on how to create CUSTOM field types. When I have time I will work on this issue - it will add to the current docs.
