### ISSUE TITLE
Beta 2.4.1 release notes contain an invalid link

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/devdocs#7967]
# General issue

Affected topic: /guides/v2.4/release-notes/open-source-2-4-1.html

## Description:

Please visit https://devdocs-beta.magento.com/guides/v2.4/release-notes/open-source-2-4-1.html 
Navigate to last paragraph in the page. There is a link given for the "The Code Migration Toolkit". On click of it redirects to a 404 page.

## Possible solutions:

I think the code migration repo has been removed from the GitHub.

## Additional information:

You may re create the repo again.

![image](https://user-images.githubusercontent.com/5028259/94767707-db276000-03ca-11eb-8492-f34d2fe1b659.png)

**Comment by jfrontain** [comment]
Thanks for catching this bad link, @tiwarimukesh. The toolkit was moved, and I just updated the release notes with a valid link. I'll merge that change today.

**Comment by tiwarimukesh** [comment]
> Thanks for catching this bad link, @tiwarimukesh. The toolkit was moved, and I just updated the release notes with a valid link. I'll merge that change today.

@jfrontain  The link is still not working.
