### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by icsw** [magento/devdocs#797]
At the page
http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html
there is a broken link:
`<a href="/guides/v2.1/install-gde/install/install-cli-subcommands-enable.html">Enable or disable modules</a>` or  <a href="http://devdocs.magento.com/guides/v2.1/install-gde/install/install-cli-subcommands-enable.html">Enable or disable modules</a>.

**Comment by xcomSteveJohnson** [comment]
Sorry about that. Fixed now. Please verify and close this issue.

**Comment by icsw** [comment]
Thank you, now it's fixed.
