### ISSUE TITLE
Unclear on how to activate the Magnifier widget

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#7976]
# General issue

## Description:

https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_gallery_mg.html
It says:

> Magnifier is a widget that allows displaying images in 100% scaled size in separate dedicated layer. In Magento it is used by the gallery widget for zooming the product images on product pages.

But if I hover over a product image in the product view in the frontend, then there is no zoom.
Do I have to enable this first or add a script to make it work?

**Comment by dobooth** [comment]
Hi @Eddcapone Thanks again for writing. Most JS widgets are implemented roughly the same way, as described in https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_init.html#init_phtml. Please let us know if these instructions need updating.

**Comment by Eddcapone** [comment]
@dobooth , no, the solution is to copy the etc/view.xml from the base theme to your theme and then setting the value for the magnifier to "true"

**Comment by dobooth** [comment]
That's good info! Thanks for the reply.

**Comment by jenlindner** [comment]
Hi, should I work off of 2.4.2-develop or 2.4-develop-s3 for this? Just wondering which branch to use (in my fork).

**Comment by jeff-matthews** [comment]
@jenlindner, you can use the `master` branch since this is not specific to a patch-level release (for example, 2.4.2). The 2.4.2-develop` branch is for updates that won't be published until 2.4.2 reaches GA.
