### ISSUE TITLE
Varnish verification is missing

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#7979]
# General issue

## Description:

Information is missing on how I can test if varnish is successfully configured and working.

https://devdocs.magento.com/guides/v2.4/config-guide/varnish/config-varnish-final.html

**Comment by dobooth** [comment]
Hi @Eddcapone Please check https://devdocs.magento.com/guides/v2.4/config-guide/varnish/config-varnish-final.html for verification instructions. If you feel this is inadequate, please let us know. Thanks for submitting.
