### ISSUE TITLE
GraphQL: Add company user mutations

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7985]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/29093

Magento 2 GitHub PR: https://github.com/magento/partners-magento2b2b/pull/203

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add documentation for the following B2B company user mutations

createCompanyUser
updateCompanyUser
deleteCompanyUser

**Comment by andrewbess** [comment]
@magento I am working on this
