### ISSUE TITLE
GraphQL: Add company role mutations

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7986]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/29094

Magento 2 GitHub PR: https://github.com/magento/partners-magento2b2b/pull/203

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add documentation for the following B2B company role mutations

createCompanyRole
updateCompanyRole
deleteCompanyRole

Also add the documentation for the checkCompanyRoleName query

**Comment by andrewbess** [comment]
@magento I am working on this
