### ISSUE TITLE
GraphQL: Add company team mutations

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7987]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/29095

Magento 2 GitHub PR: https://github.com/magento/partners-magento2b2b/pull/227

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add documentation for the following B2B company team mutations

createCompanyTeam
updateCompanyTeam
deleteCompanyTeam
updateCompanyStructure

**Comment by andrewbess** [comment]
Hello @keharper 
Thank you for assigning.
I am going to make it ASAP.
Also, I will add the link on the topic about query `company` when it becomes available to this topic.
