### ISSUE TITLE
GraphQL: Update company query to include credit history

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7989]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 https://github.com/magento/magento2/issues/28554

Magento 2 GitHub PR: https://github.com/magento/partners-magento2b2b/pull/247

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Update the company `query` to include the `credit_history` object.

Include definitions of the operation types, but don't go into great detail.

**Comment by RakeshJesadiya** [comment]
@magento I am working on this.

**Comment by keharper** [comment]
Fixed by #8303
