### ISSUE TITLE
Testing_Rest_Resources.html - header Auto Refresh - where is it?

### ISSUE THREAD

**Issue by timrsfo** [magento/devdocs#799]
[http://devdocs.magento.com/guides/m1x/api/rest/testing_rest_resources.html](url)
1) the link to [edit this page on git hub] is wrong
[https://github.com/magento/devdocs/tree/m1x/guides/m1x//guides/m1x/api/rest/testing_rest_resources.html
](url)
2) The following note appears on the page - How do you get to this pop-up? 
    "Click the Header with authorization data"  - I can't find this
<b>NOTE</b>: Click the header with authorization data and click <b>Auto refresh</b> in the opened pop-up in order to generate new values for oauth_nonce, oauth_timestamp, and oauth_signature at each request.<br/>

Ubuntu 14.04
RESTClient 2.0.5
Firefox 47.0

**Comment by xcomSteveJohnson** [comment]
@timrsfo  Thanks for pointing out the issue with **Edit this page on GitHub**. It affected _all_ API pages! That is fixed now.

I don't know the answer to your other question. Someone in engineering said that apparently the browser REST client has changed. I don't know how to generate the auth credentials to try it and I don't have Magento 1 installed right now.

There are at least two options:

*  If you can tell me how to generate the credentials, I can try it and revise the procedure.
*  If you figure it out and help me revise the procedure, I can mention you in the topic along with a link to your web site.

**Comment by keharper** [comment]
Is the Header with authorization data shown in the graphic under step 7?

**Comment by timrsfo** [comment]
for me its under step 6. I never see the popup mentiond with 
[http://devdocs.magento.com/common/images/m1x/rest_test3.png](url)

**Comment by xcomSteveJohnson** [comment]
Is this blocking you?

**Comment by timrsfo** [comment]
ok, I see the problem. Operator error on my part
Your graphic shows the [green Insert] button, but I neglected to hit it
possible update:
 step 3 In the OAuth window, on the Signature for the request tab, fill in the following fields:
last bullet:  Click Insert, to add oauth header
step 6. Click Save. You are prompted whether you want to save entered data. Click Yes.
step 6.5 Back on the main page ... Click the header with authorization data and click Auto refresh in the opened pop-up in order to generate new values for oauth_nonce, oauth_timestamp, and oauth_signature at each request.

sorry my bad

**Comment by keharper** [comment]
@timrsfo I didn't see your last post come through, so I was installing the plug-in, testing everything, and came to same conclusion as you. :)

@xcomSteveJohnson Do you want me to update the docs, since I've got the environment all set up?

**Comment by xcomSteveJohnson** [comment]
@keharper Sure, if you don't mind, thanks!

**Comment by keharper** [comment]
@timrsfo I've updated the procedure at http://devdocs.magento.com/guides/m1x/api/rest/testing_rest_resources.html . The changes weren't exactly as you suggested because whenever I tried to click on Insert as header, the window would close. 

Please close this PR if these changes are good.

**Comment by timrsfo** [comment]
looks good
