### ISSUE TITLE
GraphQL: Add gift registry mutations

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#7993]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28586
Magento 2 GitHub PR: https://github.com/magento/partners-magento2ee/pull/280/

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add documentation for the following gift registry mutations

createGiftRegistry
shareGiftRegistry

Also update the customer object to include gift registry objects and attributes

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by keharper** [comment]
Closed per #8170
