### ISSUE TITLE
Feedback on page: /guides/v2.4/coding-standards/docblock-standard-general.html

### ISSUE THREAD

**Issue by LiamTrioTech** [magento/devdocs#8012]
# General issue
How to actually generate the documentation using phpDocumentor?
Or is there an alternative Magento tool for this?

## Description:

The page clearly outlines how to document our classes, functions, files etc but does not show how to generate documentation.

## Possible solutions:

Task or better yet a Magento bin CLI?

## Additional information:

Needs to exclude many things, tests, dev folders, setup, upgrade, include app/code and app/design include phtml files and possibly js files?

Related:
https://github.com/magento/magento2/issues/1011
https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/Generating-online-HTML-from-PHP-Doc-for-Magento-2/idi-p/45829

**Comment by dobooth** [comment]
Hi @LiamTrioTech. Thanks for writing. This topic discusses the standards and formatting of writing a DocBlock. There is no need to generate docs from these blocks. It is mostly to help ensure consistency of formatting. Then if we decide to implement a feature that uses DocBlocks, they will be ready to go.
