### ISSUE TITLE
missing explanation about web > allow property on page: /cloud/project/magento-app-properties.html

### ISSUE THREAD

**Issue by medigeek** [magento/devdocs#8021]
# General issue
The "allow" property under "web" is not explained:

https://devdocs.magento.com/cloud/project/magento-app-properties.html#web

## Description:

The "allow" property under "web" is not explained.

## Possible solutions:

explain what allow does or stands for

## Additional information:

N/A

**Comment by hguthrie** [comment]
Thanks @medigeek for pointing this out! I have a PR in review with Cloud team to update that key value list.
