### ISSUE TITLE
Mistake on: /guides/v2.4/rest/tutorials/orders/order-create-order.html

### ISSUE THREAD

**Issue by codemasternode** [magento/devdocs#8041]
## Description:
When i try to make call on POST /rest/<store_code>/V1/carts/mine/payment-information with json body copied from
example in API documentation (and in compliance with shopping-card flow) i get response 400 with body: 
`
{
    "message": "No such entity with %fieldName = %fieldValue",
    "parameters": {
        "fieldName": "cartId",
        "fieldValue": 0
    },
    "trace": ".....some long error message"
}
`
I've put cartId but i result is the same.

**Comment by keharper** [comment]
@codemasternode You will likely need to populate the `paymentMethod.additional_data` object with whatever credit card information the payment processor requires. We can't provide that information.

Closing this ticket because it's a support request.
