### ISSUE TITLE
Information On Cloud "Configuration management for store settings" is confusing 

### ISSUE THREAD

**Issue by BarnyShergold** [magento/devdocs#8049]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/cloud/live/sens-data-over.html

## Description

Information on this page is confusing and is mixing up Application Configurations with Service & Platform Configurations

## Possible solutions

Rework page, possibly creating additional ones, to clarify the information and to remove ambiguity and confusion.

**Comment by BarnyShergold** [comment]
@NadiyaS & @meker12 - I'll be looking at this page soon but please can you log elements of this page that you feel are confusing or incorrect?

**Comment by NadiyaS** [comment]
about **`Consistent configuration`** section. I guess it should be fully rewritten:
> The database contains default configurations for your Magento store. 

All default values stores in config.xml in appropriate module
> When you update configurations in the Magento Commerce Cloud environments using the Magento Admin panel or the Magento CLI bin/magento config:set command, your configuration changes apply to the app/etc/config.php file. 

All changes made in Magento Admin panel are stored in DB only, config.php file is not changed. 
Command `config:set` may write configs as to DB as to config.php as to env.php, depends on the used options. By default this command writes to DB.
> Use the ece-tools command in the remote environment to generate a config.php file:

On installed projects this file already exists, so I would say not to generate file but write configs related to SCD. Probably we even may list of all fields which this command dumps:

        'system/default/general/locale/code',
        'system/default/dev/static/sign',
        'system/default/dev/front_end_development_workflow',
        'system/default/dev/template',
        'system/default/dev/js',
        'system/default/dev/css',
        'system/default/advanced/modules_disable_output',
        'system/stores',
        'system/websites',
Actually, I just noticed, that it will dump all custom configs for stores and websites, and only for default store it dumps fields related to SCD.

To be continued...

**Comment by NadiyaS** [comment]
**`Configuration data`** section:
> The config.php file includes the following settings and configuration values:
> - Configured values for settings entered through the Magento Admin store configuration
> - Extension list
> - Scopes value for static content deployment (the default SCD strategy is quick)

I am not sure what means under `Extension list`. Probably list of modules+extensions? 
Also, if we list all info that this file may contain, I would add list of all stores configured on the project.
>Because Magento Commerce Cloud supports only the Magento production and maintenance modes, the Advanced > Developer section is not accessible in the Admin panel. You can configure additional settings using environment variables.

Seems like the link set in `environment variables` is wrong https://devdocs.magento.com/cloud/project/magento-env-yaml.html as I do not know how we may configure fields from **Advanced > Developer** using .magento.env.yaml. Customer may set values to those configs using `bin/magento config:set`.
@oshmyheliuk could you please confirm that I did not miss something about this case.

Section **`Sensitive data`**:
>  For Cloud projects, we recommend using Magento Commerce Cloud environment variables to store sensitive values. For an example, see Add Magento authentication keys. 

I would change example link as auth key is a custom case. Probably it was added there as example how to add environment variables in Cloud UI, but I would also add link to how to create names for system configurations to set them in environment variables. But I am not sure that we have such link. Maybe this one https://devdocs.magento.com/guides/v2.4/extension-dev-guide/configuration/sensitive-and-environment-settings.html

**Comment by hguthrie** [comment]
@BarnyShergold are you still working on this? I will keep your name on it, but I will remove Nadiya since she provided input.

**Comment by BarnyShergold** [comment]
@hguthrie - I've just not time to commit to this. Hopefully in the new year. You can remove my name if you wish and when I have time I'll "reclaim" the issue.

**Comment by hguthrie** [comment]
Okay, thanks Barny! Just want to free it up in case someone else wants to try. Feel free to grab it back any time 🙂

**Comment by dobooth** [comment]
@bdenham

**Comment by hguthrie** [comment]
I have made these updates during the Cloud guide migration and they will be available soon.
