### ISSUE TITLE
Magento 1.x Reference Rest API, All Resources indicate XML is default format?

### ISSUE THREAD

**Issue by timrsfo** [magento/devdocs#805]
[Resources]((http://devdocs.magento.com/guides/m1x/api/rest/Resources/inventory.html)

1.  I am using Postman to issue Rest commands to Magento. All my response data is returned in Json format. Postman inserts an Accept: */* header. To me this indicates "send me what ever you want" ie default format. I can insert Accept: application/xml and it will return XML, but it doesn't seem like the default. Default XML is shown for all resources. I'm not sure this is super important, t I caught it because I am trying to figure out how to POST/PUT in json format, see next item.
2. There aren't any POST/PUT examples where the body is transmitted in Json. It would be great if you could show at least one example PUT and one POST in Json format. Perhaps, PUT an Address and POST a product.

**Comment by xcomSteveJohnson** [comment]
Answers:

1.  By default we return JSON.
2.  It would be faster if you could submit an example to us. You can use the **Edit this page in GitHub** link on any page to do that. We cannot promise creating such examples for all APIs though. Maybe [this](http://devdocs.magento.com/guides/m1x/api/rest/introduction.html#RESTAPIIntroduction-OutputFormats) is a good place for such an example.

**Comment by timrsfo** [comment]
1. I agree they all default to JSON, but the docs indicate they all default to XML
[REST API: Stock Items](http://devdocs.magento.com/guides/m1x/api/rest/Resources/inventory.htmll)
e.g from above link
Authentication: Admin
Default Format: XML
Parameters :
No Parameters

2. I got thru the JSON, I will upload some examples

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing that out. We'll work on a fix and update you.

**Comment by xcomSteveJohnson** [comment]
@timrsfo Do you have some JSON responses I can use?

**Comment by xcomSteveJohnson** [comment]
Sorry for the delay. Partially fixed now. I changed all the default responses to JSON in the text but most of the examples are XML.

I put a bounty of sorts on it; if you'd like to contribute JSON responses, please do so and I'll mention you by name on the page.

**Comment by timrsfo** [comment]
I am glad to contribute, I will try to get to it by the end of the day

**Comment by timrsfo** [comment]
@xcomSteveJohnson 
Steve, I have some time now, what would you like? and where should I put it?
For example, I am using Postman and RestAssured/JaxRs (both in Eclipse). 
I can give you the GET cmds and responses from Postman

let me know if this is what you can use and I will send the responses.
Postman e.g.: 

`
base_uri = http://dockerized-magento.local
base_path = api/rest

get: {{base_uri}}/{{base_path}}/customers/addresses/{{address_id}}  # get address by addressId
{
  "entity_id": "99",
  "firstname": "Biff",
  "lastname": "Henderson",
  "city": "San Joser",
  "country_id": "US",
  "region": "California",
  "postcode": "94070",
  "telephone": "898-555-1212",
  "street": [
    "66 Hardway Ave"
  ],
  "is_default_billing": 1,
  "is_default_shipping": 0
}
`
# get customer by email
`{{base_uri}}/{{base_path}}/customers?filter[1][attribute]=email&filter[1][in][0]={{valid_customer_email}}  `

# customer address
`{{base_uri}}/{{base_path}}/customers/{{customer_id}}/addresses`

# customer by id
`{{base_uri}}/{{base_path}}/customers/{{customer_id}}`

# get products with limit
`{{base_uri}}/{{base_path}}/products?limit={{prod_limit}}`

**Comment by timrsfo** [comment]
@xcomSteveJohnson
added pull requests for changes to customer and address resources to include json

**Comment by xcomSteveJohnson** [comment]
@timrsfo Thanks! You're not listed as a contributor on these pages:

http://devdocs.magento.com/guides/m1x/api/rest/Resources/resource_customer_addresses.html
http://devdocs.magento.com/guides/m1x/api/rest/Resources/resource_customers.html
http://devdocs.magento.com/guides/m1x/api/rest/get_filters.html 

Closing this issue. If you'd like to contribute some more, reopen.
