### ISSUE TITLE
Migration plan advises to use replicated database - what about incremental updates/changes?

### ISSUE THREAD

**Issue by pascaladriaansen** [magento/devdocs#806]
In [devdocs/guides/v2.0/migration/migration-plan.md](https://github.com/magento/devdocs/blob/develop/guides/v2.0/migration/migration-plan.md) the following is mentioned under Step 3:

> To provide redundancy in the event of unexpected issues, we advise you to replicate your Magento 1.x database and use this Magento 1.x data for your migration

So, for a test migration run I replicated my production Magento 1.x database and entered the details of this replicated database in my config.xml. After some tweaking of some mapping files I got it to run the data migration step correctly, migrating all the data I wanted to migrate. 

Now, I wanted to try out the delta migration. If I understood correctly, the delta migration uses the m2_cl_* tables that are created after the data migration step. However, because the replicated database I used for the data migration is not connected to a Magento store, there are no incremental changes in orders, customers etc. 
I could, of course, connect to my production database for the delta step, but this database doesn't have the m2_cl_* tables, since this database has never been touched by the data-migration-tool.

Am I misunderstanding the tip mentioned above? Should I run both data and delta migration using my live/production database or a replicated database?

**Comment by victor-v-rad** [comment]
Hi @pascaladriaansen 
It is best to create new issues in the dedicated repository 
https://github.com/magento/data-migration-tool/issues
and further conversation should be there. 
In answering to your question is must to know the way you did the replication. If it is Mysql replication (master-slave/master-master) please read the article https://dev.mysql.com/doc/refman/5.7/en/replication-features-triggers.html
As you can see in case of statement-based replication triggers run on your replicated DB and you can run delta migration.
If you just made DB dump and execute `mysql < db.sql` on different server. Then you could run the copy of your Magento 1 store on this server and make some changes in Storefront and run delta migration.

**Comment by xcomSteveJohnson** [comment]
@pascaladriaansen Did you create an issue to get this question answered? Can we close this one?

**Comment by pascaladriaansen** [comment]
@xcomSteveJohnson Hey, I didn't create an issue, but found that @victor-v-rad's answer was enough for me to answer my question. I understood "replication" the wrong way, as I just created a database dump in stead of actually replicating the db usign mysql's replication feature.
