### ISSUE TITLE
Feedback on page: /cloud/cdn/configure-fastly.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8069]
# General issue

## Description:

https://devdocs.magento.com/cloud/cdn/configure-fastly.html#cloud-fastly-creds

```
Use the following methods to find and save the Fastly service ID and API token for your environment:

To view your Fastly credentials:
* IaaS-mounted shared directory—On Pro projects, use SSH to connect to your server and get the Fastly credentials from the /mnt/shared/fastly_tokens.txt file.
```

When Cloud Pro customers submit tickets relating to Fastly not working correctly, their issue often arises simply due to them having configured the wrong Fastly credentials in the affected environment.

## Possible solutions:

Add an alert for Pro customers under that segment that they should make sure to check the /mnt/shared/fastly_tokens.txt file in the correct environment for the Fastly credentials when configuring Fastly because **Staging and Production have separate credentials/Service IDs**.

**Comment by meker12** [comment]
On the same page, see the [Test Fastly credentials](https://devdocs.magento.com/cloud/cdn/configure-fastly.html#test-the-fastly-credentials). Step 4, specifically:

![image](https://user-images.githubusercontent.com/6391769/96273148-a1db1c80-0f94-11eb-8693-40ce3ea812e1.png)
