### ISSUE TITLE
Link to "Magento 2 Samples repository is Broken"

### ISSUE THREAD

**Issue by Emerson-Cardozo** [magento/devdocs#8085]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/config-guide/cron/custom-cron-tut.html

## Description

The link to https://github.com/magento/magento2-samples is broken (404) 

## Possible solutions

Is there another repo link for samples?

**Comment by jeff-matthews** [comment]
Thanks for the report @Emerson-Cardozo.

This also relates to #7958.  

We created a wiki page in this repo to describe the root cause and proposed solution: https://github.com/magento/devdocs/wiki/Archived-code-samples.
