### ISSUE TITLE
Clarify PHTML template component key

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8106]
# General issue

## Description:
https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_init.html

In chapter **Insert a JS component in a PHTML template** -> **Declarative notation** -> _Declarative notation using the data-mage-init attribute_ It says:

> If an object is returned, the initializer tries to find the <component_name> key

But there is no information about where it even tries to lookup the key. How can I create the key so it can be found? Basic informations are missing and the topic remains complelty unclear.

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this

**Comment by DenisSaltanahmedov** [comment]
Hi @dobooth the PR is merged, can you clouse the issue?

**Comment by dobooth** [comment]
Happily! Thanks for the effort.
