### ISSUE TITLE
CSS inheritance is unclear in less themes 

### ISSUE THREAD

**Issue by krisztian-fekete** [magento/devdocs#8107]
# General issue

## Description:

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-guide/css_quick_guide_approach.html
The documentation states:

Simplest way to extend parent styles
To extend the parent theme’s styles in your theme:

In your theme directory, create a web/css/source sub-directory.
Create a _extend.less file there. The path to it looks like following:

<theme_dir>/
│  ├── web/
│  │   ├── css/
│  │   │   ├── source/
│  │   │       ├──_extend.less
...
Add your Less code in this file.
**Extending a theme using _extend.less is the simplest option when you are happy with everything the parent theme has, but want to add more styles.**

However, the above only works if the theme's parent is a Blank. I have a theme (theme A) which is the child of Blank. This has two children, B and C. I added a global style rule to the `_extend.less` file of theme A. This extends its parent (Blank).

Theme B and C also have their own _extend.less files, but this seem to override the parent's, rather than extending it further. So actually, B & C are extending their grandparent (Blank) in this setup.

## Possible solutions:

Clarify in documentation that the `_extend.less` file of subsequent descendants of Blank's child will override the parent theme's `_extend.less` file, rather than extending it.

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
Docs updated
