### ISSUE TITLE
Feedback on page: /guides/v2.4/ext-best-practices/tutorials/dynamic-row-system-config.html

### ISSUE THREAD

**Issue by webkul-ajaysaini** [magento/devdocs#8108]
# General issue

Unable to save configuration for dynamic row if config.xml have default values. Without config.xml file it works.

When admin save configuration it will generate an issue.
**Something went wrong while saving this configuration: Notice: Array to string conversion in** vendor/magento/framework/App/Config/Value.php on line 100

https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/Config/Value.php#L95

In getOldValue() function it return the config value in (string) but we are using config.xml so it returns the array and then try to convert string.

**Comment by erikmarr** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). Thanks for taking the time to create a GitHub issue.
