### ISSUE TITLE
Next steps over "Define your configuration files"

### ISSUE THREAD

**Issue by MaximumP** [magento/devdocs#811]
http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/module-file-structure.html

The topic under the next heading steps over the "Define your configuration files"

**Comment by jcalcaben** [comment]
Thanks for pointing this out! It looks like the navigation is a little out of order. I will fix this.

**Comment by jcalcaben** [comment]
The ordering has been fixed. Closing this issue.
