### ISSUE TITLE
Duplicate bug fix description in B2B release note 2.4.1 page

### ISSUE THREAD

**Issue by amarroni** [magento/devdocs#8110]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/release-notes/b2b-release-notes.html

## Description

A Bug fix description is duplicated:

"When a merchant creates a new shared catalog, permissions are now automatically set to Allow for the Display Product Prices and Add to Cart features in categories when the customer group has been assigned this access in catalog permission settings. Previously, these settings were automatically set to Deny even when catalog permissions were set to Allow."

## Possible solutions

Just edit the content and delete 1.

## Additional information

![duplicate-bug-fix-report](https://user-images.githubusercontent.com/5198527/96911606-72864d00-1477-11eb-9fc6-c8b84dfe38e2.png)

**Comment by jfrontain** [comment]
Thanks, @amarroni! i've removed the redundant description.
