### ISSUE TITLE
B2B installation requires specific version if Magento is not latest

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#8114]
# General issue

Topic: https://devdocs.magento.com/extensions/b2b/

## Description:

When I install B2B onto Magento 2.3.6 with `composer require magento/extension-b2b`, it loads 1.3 version (`Using version ^1.3 for magento/extension-b2b`), which is the version compatible with Magento 2.4. Though it works when I specify a B2B version such as `composer require magento/extension-b2b:1.1.6`.

## Possible solutions:

Update the text and command or add a note that compatible version must be provided in the command, and add a reference link to the topic with a list of compatible versions _Magento - B2B_.

**Comment by srsathish92** [comment]
Related ISSUE: https://github.com/magento/devdocs/issues/8091

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@dshevtsov Can you please tell me the reference link to the topic with a list of compatible versions Magento - B2B?

**Comment by dshevtsov** [comment]
@dobooth can you help with the link?

**Comment by chiranjeevi-cj** [comment]
@dobooth Is the reference link to the topic with a list of compatible versions Magento - B2B available? or need to create?

**Comment by chiranjeevi-cj** [comment]
@dobooth Any update on the link?

**Comment by srsathish92** [comment]
@chiranjeevi-cj Need to update the compatible matrix of B2B & Magento

**Comment by dshevtsov** [comment]
cc @jeff-matthews

**Comment by jeff-matthews** [comment]
@chiranjeevi-cj, you can find B2B in the following compatibility matrix: https://devdocs.magento.com/release/availability.html#compatibility
