### ISSUE TITLE
GraphQL: Rename company-related query names and attributes

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#8117]
# Community engineering issue

Type of Doc:

-  [ ] New topic
-  [x] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/30466

Magento 2 GitHub PR: TBD

Magento 2 version:

-  [x] 2.4

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Update the following query names and other objects/attributes, as directed by https://github.com/magento/architecture/pull/447

checkCompanyEmail > isCompanyEmailAvailable
checkCompanyAdminEmail >   isCompanyAdminEmailAvailable
checkCompanyUserEmail >  isCompanyUserEmailAvailable
~~checkCompanyRoleName >  isCompanyRoleNameAvailable~~ This will be handled in another PR

**Comment by andrewbess** [comment]
@magento I am working on this
