### ISSUE TITLE
Launch Checklist PDF contains Link that doesnt work.

### ISSUE THREAD

**Issue by rtyrell24** [magento/devdocs#8119]
# Bug report
Launch Checklist PDF contains Link that doesn't work.

## Description

https://devdocs.magento.com/cloud/live/site-launch-checklist.html The launch checklist which all Magento Cloud Merchants follow.

FIrst link in PDF The following is a synopsis of our Site launch documentation goes to https://devdocs.magento.com/guides/cloud/live/live.html, which appears dead and displays the following

Page Not Found
Sorry!
The page you are looking for could not be found or the documentation does not exist.

To report a missing page, please submit an issue in our public GitHub repo.

Return to main page

### Steps to reproduce

1.Click https://devdocs.magento.com/cloud/live/site-launch-checklist.html 
2.click first hyperlink Launch checklist https://devdocs.magento.com/download/magento-commerce-cloud-prelaunch-checklist.pdf 
3.download and open PDF
4.Click FIrst link in PDF
5. link goes to https://devdocs.magento.com/guides/cloud/live/live.html which is dead
 

## Possible solutions

Dead link should lead to the following. Should link to the following https://devdocs.magento.com/cloud/live/live.html

**Comment by rtyrell24** [comment]
@magento Please assign this issue.

**Comment by jeff-matthews** [comment]
Thanks for the report @rtyrell24.  

The link in the PDF is wrong. It should be https://devdocs.magento.com/cloud/live/live.html. There has never been a file by the name of `https://devdocs.magento.com/guides/cloud/live/live.html` on the devdocs site, so it's not an issue with redirects.

I'm requesting assistance from the internal owner of that PDF to revise and provide us with a new copy that we can upload to the devdocs site.

**Comment by jeff-matthews** [comment]
I uploaded a revised PDF to devdocs.
