### ISSUE TITLE
Define services in magento.app.yaml in docs

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8146]
# General issue

## Description:

Under Project configuration it states:

.magento.app.yaml—defines how to build and deploy Magento, including services, hooks, cron jobs, and more.
...
.magento/services.yaml—defines the services Magento uses by name and version. For example, this file may include versions of MySQL, PHP extensions, and Elasticsearch. These are referred to as services.

## Possible solutions:

I don't think any services are defined in .magento.app.yaml - if you clicked on the link on .magento.app.yaml, there is no mention of services there (https://devdocs.magento.com/cloud/project/magento-app.html)
- there is a "relationships" section in .magento.app.yaml which defines the relationship between the application and the service but does not explicitly set the service versions

## Additional information:

The definition/configuration of the services are covered in the bullet point for .magento/services.yaml

**Comment by meker12** [comment]
Additional info --  Configuring services for your Cloud environment requires configuration info from services.yaml and .magento.app.yaml.  So technically, the .magento.app.yaml file does determine the services that are built, but the service definition is in the services.yaml file.   

If you look at all the [service setup topics](https://devdocs.magento.com/cloud/project/services.html), the instructions include steps for updating `services.yaml` and the relationships property in the `.magento.app.yaml` file. 


[Service relationships](https://devdocs.magento.com/cloud/project/services.html#service-relationships)

> In Magento Commerce Cloud projects, service relationships configured in the .magento.app.yaml file determine which services are available to your application.
> 
> You can retrieve the configuration data for all service relationships from the $MAGENTO_CLOUD_RELATIONSHIPS environment variable. The configuration data includes service name, type, and version along with any required connection details such as port number and login credentials.
