### ISSUE TITLE
Feedback on page: /guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html

### ISSUE THREAD

**Issue by developerRitesh** [magento/devdocs#8163]
# General issue
Sample module on GitHub link at  the bottom of the page should redirect to a valid page
## Description:
Sample module on GitHub like at  the bottom of the page redirect to  404  page not found on the github it either  should redirect to  relevant page or  the link should  be removed.

Sample module on GitHub like at  the bottom of the page redirect to  404  page 
## Possible solutions:
 it either  should redirect to  relevant page or  the link should  be removed.

**Comment by keharper** [comment]
@developerRitesh We are aware of this problem. You can see a summary at https://github.com/magento/devdocs/wiki/Archived-code-samples  Closing because #7958 first identified the issue, making this a duplicate.
