### ISSUE TITLE
Cannot query field "orders" on type Customer: /guides/v2.4/graphql/queries/customer.html

### ISSUE THREAD

**Issue by AndyMardell** [magento/devdocs#8166]
## Description:

The `orders` field is not available on the `customer` query. As this was only merged 18 days ago, I expect it's an unreleased feature in Magento, however, I can't seem to find a reference to this field anywhere in the Magento 2 project. Can anyone point out the pull request where this feature was/is going to be added?

This was added to the docs in [PR #7436](https://github.com/magento/devdocs/pull/7436)

## Request

```graphql
query {
  customer {
    orders(
      pageSize: 20
    ) {
      items {
        id
        order_date
        total {
          grand_total {
            value
            currency
          }
        }
        status
      }
    }
  }
}
```

## Response

```json
{
  "errors": [
    {
      "message": "Cannot query field \"orders\" on type \"Customer\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by keharper** [comment]
@AndyMardell What version of Magento are you using? We added the `orders` object in 2.4.1.

The public repo doesn't maintain branches for each patch release, but you can see here that `orders` was added 8 months ago.

https://github.com/magento/magento2/blame/2.4-develop/app/code/Magento/SalesGraphQl/etc/schema.graphqls#L24

**Comment by AndyMardell** [comment]
Perfect, thanks @keharper.

My apologies – I was looking in the CustomerGraphQl module for this change and was only running 2.4.0

Thanks for your quick response
