### ISSUE TITLE
Empty topics

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#8177]
# General issue

https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-parent.html
https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-parent.html

## Description:

Empty topics.

## Possible solutions:

Remove the topics or add content.

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by sathiyaaa** [comment]
@dobooth  Can the topic be removed or should the content be added?

**Comment by dobooth** [comment]
Ah! This is a PR where one of our writers was checking the codebase and discovered topics with zero content. We think they are from old(v2.2 or older) where the content was moved to another location but the files were not deleted. There is almost no git history in current versions. We will likely end up just deleting them first but want to do some more checking first. Appreciate you grabbing it but there's not much work to be done here. We will handle it internally. Thanks for asking!
