### ISSUE TITLE
Incorrect line in di.xml

### ISSUE THREAD

**Issue by willjones-stratagem** [magento/devdocs#8178]
# General issue

## Description:

Configure di.xml section is incorrect
https://devdocs.magento.com/guides/v2.4/inventory/source-selection-algorithms.html

## Possible solutions:

Change the following line in di.xml

`<type name="Magento\InventorySourceSelection\Model\SourceSelectionService">`

To the following

`<type name="Magento\InventorySourceSelectionApi\Model\SourceSelectionService">`

**Comment by sathiyaaa** [comment]
@magento I am working on this
