### ISSUE TITLE
XSS escape functions could use some more explanation

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#818]
Hi guys

Regarding this page: http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-security.html

It is mentioned that you can use 4 methods to escape the output to html:
- escapeHtml
- escapeQuote
- escapeUrl
- escapeXssInUrl

But I'm missing some explanation about what each one of those 4 exactly does, and in what cases I have to use one of these.

Would be great if you could add an extra paragraph on that page where you explain this.

Thanks!

**Comment by jcalcaben** [comment]
Thanks for the feedback @hostep! 

I will consult with our developers and add additional information for these methods.

**Comment by tanberry** [comment]
Sure, and there has been some recent work around that... @jcalcaben can you work with @almarchenko to pull in to the 2.1 the work that you did with Igor and Olga on the upcoming 2.1 docs?

**Comment by tanberry** [comment]
oops, yes, both of us replied same time. ;-)

**Comment by jcalcaben** [comment]
@hostep 
The page is now updated with cases on when to use `escapeHTML`, `escapeQuote`, and `escapeXssInUrl`. (`escapeURL` was removed in the doc to favor the more secure `escapeXssInUrl` function)

**Comment by hostep** [comment]
Ok thanks @jcalcaben!
I was especially wondering what the difference was between `escapeURL` and `escapeXssInUrl`, so it's good you removed the less secure one and recommend to always use the second one.

**Comment by tanberry** [comment]
Whoo hoo, thank you @hostep  for all of your help, contributions, and communications with the Magento DevDocs team! Look what I just saw on Twitter, fresh from Poland: 
![image](https://cloud.githubusercontent.com/assets/9368837/18645361/793a4b14-7e72-11e6-8806-dac852d5ad3f.png)
https://twitter.com/tutnix/status/777784527712313344
