### ISSUE TITLE
Feedback on page: /guides/v2.4/install-gde/basics/basics_software.html

### ISSUE THREAD

**Issue by sergey-nechaev** [magento/devdocs#8201]
# General issue

## Description:
This page doesn't really add any information to the devdocs. The https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html page covers everything.

## Possible solutions:

Remove the page.

## Additional information:

It doesn't make sense to support two pages with system requirements.

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@m2-community-project @sergey-nechaev Should I remove the page?
