### ISSUE TITLE
Outdated REST API documentation for Magento 2.1

### ISSUE THREAD

**Issue by meng-tian** [magento/devdocs#821]
The statement:
```
GET operations cannot be performed when you specify all.
```

on http://devdocs.magento.com/guides/v2.1/rest/rest_endpoints.html is no longer valid since Magento 2.1.0. Please refer to magento/magento2@8651be8228b8bfb1ac5910ef16e6146774a02861 for details.

Can you please updated the documentation?

**Comment by keharper** [comment]
Thanks for noticing this. Done. I've also deleted the equivalent sentence from the SOAP documentation.
