### ISSUE TITLE
Clarification for description for attribute "template" in  "Layout instructions" page

### ISSUE THREAD

**Issue by AndresAndreev** [magento/devdocs#8211]
# General issue

## Description:

The description for attribute "template" for **block** states: 

> If the attribute is omitted, the block will not render any output.

But that is only true if the class that implements the rendering of this particular block doesn't already have `$_template` property set up (e.g. _Magento\Theme\Block\Html\Header\Logo_, _Magento\Theme\Block\Html\Breadcrumbs_).

## Possible solutions:

Add information about this exception to the rule.

## Additional information

Full URL to the page: https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.html

**Comment by BarnyShergold** [comment]
@AndresAndreev - Please can you add the full URL to the page? We need this to identify the document to change!

**Comment by AndresAndreev** [comment]
@BarnyShergold Yes, of course! It's added now. Totally forgot about it.

**Comment by BarnyShergold** [comment]
How does this read to you -
"If the attribute is omitted, the block will not render any output unless the block class (or a parent class) has the $_template property defined correctly."

**Comment by AndresAndreev** [comment]
Sounds good to me. 👍

**Comment by BarnyShergold** [comment]
@AndresAndreev - In the pipeline!
