### ISSUE TITLE
add information on how to extend catalog price rule conditions

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#8224]
# New topic request
Could you please add information on how to extend catalog price rules to add custom conditions? 

## Description
Currently in the internet there's not much information about this funcionality but there are lots of questions regarding this subject. On the contrary extending Cart Rules has lots of documentation to find online. 

## Content checklist
It would be great to have an overlay of how to create a new rule condition and merge it with the default conditions. 

-  [ ] The topic provides an overview of how adding a condition works, what interfaces it extends and how it is applied.
-  [ ] The topic provides steps for building the needed classes and interfaces.
-  [ ] The topic contains code samples that shows how a core condition was implemented.

## Additional information/resources

Unfortunately information is very scarce on the web regarding this topic.

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this
