### ISSUE TITLE
Magento 1: tax configuration warning link points to incorrect documentation link

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#823]
Hi guys

Not sure if this is the correct place to report this.

But when in a Magento 1 shop you configure your tax settings slightly wrong you get this message:
![screen shot 2016-09-15 at 10 45 16](https://cloud.githubusercontent.com/assets/85479/18543760/ac4cda4c-7b31-11e6-94f2-0361dd3c768f.png)

The link on 'source' leads to: http://www.magentocommerce.com/knowledge-base/entry/magento-ce-18-ee-113-tax-calc
Which incorrectly redirects you to:
http://docs.magento.com/m1/ce/user_guide/Magento_Community_Edition_User_Guide.html#tax/warning-messages.html

The correct link should be: http://docs.magento.com/m1/ce/user_guide/tax/warning-messages.html

Is this something you can fix on the server side?

Thanks!

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing this out. We'll create an issue to fix the redirect and provide an update here when it's fixed. It usually takes a couple of days.

**Comment by xcomSteveJohnson** [comment]
Should be fixed now. Please check it out and close this if it works correctly.

**Comment by hostep** [comment]
Yes, looks like it is fixed, thanks! :)
