### ISSUE TITLE
Requesting a table for comparing installation methods

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#8237]
# General issue

## Description:

Right now it's not clearly described here that it's recommended to use composer based installation for production. This causes issues like https://github.com/magento/magento2/issues/30920.

## Possible solutions:

Would be good to add recommendation to use composer based installation, maybe compare table similar to https://magento.com/tech-resources/download
![image](https://user-images.githubusercontent.com/1873745/99501742-d91e5e00-2984-11eb-8ae2-5cf8592ff56c.png)

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
Hey @jeff-matthews After our Install Guide refresh, this table on /tech-resources/ is now stale. Who can update this?

**Comment by jeff-matthews** [comment]
@dobooth, Holli Matthews' team (Marketing) owns that page. We would need to create an internal Jira ticket to request updates. @MMyles-Adobe, I know you worked on the redesign. Do you have any suggestions for who we can escalate this feedback to?

**Comment by MMyles-Adobe** [comment]
@jeff-matthews , are you looking for info on who implemented the Tech Downloads comparison table? That was done by Ernest Wong's identity team. This is the Jira ticket for it - [ITIS-7568](https://jira.corp.magento.com/browse/ITIS-7568)

The design is based on this [Spectrum Comparison Table spec](https://spectrum-contributions.corp.adobe.com/page/comparison-table-beta/).

**Comment by jeff-matthews** [comment]
Thanks @MMyles-Adobe! That's what I was thinking of.

**Comment by jeff-matthews** [comment]
This is not a devdocs issue.

**Comment by jeff-matthews** [comment]
@dobooth, my understanding of the reposted issue is that we're being asked to add a table like that to our devdocs; not to refresh the page at https://magento.com/tech-resources/download.

**Comment by MMyles-Adobe** [comment]
@jeff-matthews & @dobooth - if looking to implement a similar table on a devdocs webpage, can probably use [Spectrum CSS](https://opensource.adobe.com/spectrum-css/) to style with similar look, if desired. But could use standard devdocs table styling as well, for consistency.

**Comment by gamarshall** [comment]
Contributor installation guide has been moved here: 
 https://developer.adobe.com/commerce/contributor/guides/install/
Guide is being migrated to ExlLeague -

**Comment by dshevtsov** [comment]
The installation guide was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/overview).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-operations.en/issues) it.
