### ISSUE TITLE
Clarify Fastly set up info about DNS configuration for production

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8261]
# General issue

## Description:

The following text is mentioned in the [Fastly set up](https://devdocs.magento.com/cloud/cdn/configure-fastly.html) topic towards the top of the page:

```
When you are ready to launch your Production site, you must update your DNS configuration to point your production domains to the Fastly service and complete additional configuration tasks. See Launch checklist.
```

Logically speaking, the development settings would be configured first, then the Production settings would later be configured prior to launching.

## Possible solutions:

This section about configuring the Production settings Fastly should be moved under the `development settings` towards the bottom of the page.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
