### ISSUE TITLE
Issue with Zero Checkout Subtotal Magento2.4 

### ISSUE THREAD

**Issue by ajaysingh-webkul** [magento/devdocs#8264]
Step To Reproduce

1 Please Set **Zero Subtotal checkout**  **new order status** to **Processing** ( https://imgur.com/a/mrJQyTN )
2.create a virtual Product with Price 0
3.then add to cart that product and place an order with a total of 0
4. then check order status in admin orders grid ( https://imgur.com/a/syfqkkX )

**Comment by keharper** [comment]
Hi @ajaysingh-webkul. This looks like a code issue. Please open an issue against the code base at https://github.com/magento/magento2
