### ISSUE TITLE
Unable to View the Rest API documentation for Magento version 2.3

### ISSUE THREAD

**Issue by leopinnheiro** [magento/devdocs#8270]
@magento Unable to View the Rest API documentation for Magento version 2.3
http://devdocs.magento.com/swagger/index_23.html

Can anybody provide the resource to view the REST API the documentation for Magento version 2.3?
Thanks.

**Comment by dobooth** [comment]
https://devdocs.magento.com/redoc/2.3/

**Comment by dobooth** [comment]
We might have some links to update here.

**Comment by leopinnheiro** [comment]
Is there a link to access the swagger?

**Comment by jeff-matthews** [comment]
No, we replaced the swagger-ui library with Redoc because the latest version of swagger-ui has an XSS vulnerability.

Technically, both libraries use the same "swagger" (now known as OpenAPI) schema to generate docs.
