### ISSUE TITLE
error in L2 caching documentation 2.3 vs 2.4

### ISSUE THREAD

**Issue by eguardado-one** [magento/devdocs#8272]
# Topic clarification/correction request
Clarification if the documentation for 2.3 should be the same as 2.4
## Topic Link
Related issue
https://github.com/magento/devdocs/issues/8189

2.4 doc
https://devdocs.magento.com/guides/v2.4/config-guide/cache/two-level-cache.html
2.3 doc
https://devdocs.magento.com/guides/v2.3/config-guide/cache/two-level-cache.html

## Description
Clarification if the documentation for 2.3 should be the same as 2.4 for the issue that was brought up.
Does 'frontend' also need to be applied to Magento 2.3 for L2 caching?

2.3 document
'cache' => [
        'default' => [

2.4 document
'cache' => [
    'frontend' => [
        'default' => [

## Possible solutions
Update documentation

The solution should clarify in the documentation that the change for 'frontend' only applies to Magento 2.4.  If not then the documentation should be updated for 2.3 to include 'frontend' in the configuration.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
