### ISSUE TITLE
Feedback on page: /guides/v2.4/comp-mgr/cli/cli-rc1-samp.html

### ISSUE THREAD

**Issue by ParimalSigma** [magento/devdocs#8275]
# General issue

## Description:

In latest Magento 2.4, there should not be var/generation folder

## Possible solutions:

Update Text from "rm -rf var/cache/* var/page_cache/* var/generation/*" to "rm -rf var/cache/* var/page_cache/* generated/*"

**Comment by ParimalSigma** [comment]
@magento I am working on this

**Comment by ParimalSigma** [comment]
@magento add to contributors team

**Comment by Techytt** [comment]
@magento I am working on this

**Comment by Techytt** [comment]
@magento add to contributors team

**Comment by Techytt** [comment]
@magento add to contributors team

**Comment by Techytt** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by Techytt** [comment]
@magento I am working on this
