### ISSUE TITLE
GraphQL: Add coverage for Shopper Assistance

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#8281]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: 

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/30130

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

The shopper assistance feature requires the following updates to the 2.4 GraphQL documentation. Open the PR against the `2.4.2-develop` branch.

* Add documentation for the `generateCustomerTokenAsAdmin` mutation. Include an explanation of the use of customer tokens and that the customer must have enabled the feature.
* Update the input attributes section of the `createCustomerV2` and updateCustomerV2` mutations
* Update the `src/_includes/graphql/customer-output-24.md` file
* Update the `src/_data/toc/graphql.yml` file
* Update the `src/guides/v2.4/guides/graphql/authorization-tokens.md file

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by keharper** [comment]
Fixed in #8303
