### ISSUE TITLE
Updated timestamps on symlinked pages issue

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#829]
Hi guys

Just something I just noticed.
Check the 'Updated' timestamp on the [version 2.0](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/templates/template-security.html) and compare it with the [version 2.1](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/templates/template-security.html).
The page for version 2.0 has: `19 September 2016 (PDT)` and version 2.1 has: `Updated: 22 June 2016 (PDT)` even though they both contain 100% the same content (since they are symlinked).

I guess something is slightly wrong in your publish script and it should also update the timestamps on those symlinked pages.

For other examples:
- [2.0](http://devdocs.magento.com/guides/v2.0/migration/migration-tool-internal-spec.html) vs [2.1](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-internal-spec.html)
- [2.0](http://devdocs.magento.com/guides/v2.0/migration/migration-plan.html) vs [2.1](http://devdocs.magento.com/guides/v2.1/migration/migration-plan.html)

Is not super urgent, but is slightly annoying :)

**Comment by xcomSteveJohnson** [comment]
Do you know how to solve this?

**Comment by hostep** [comment]
No sorry, I have no experience with Jekyll unfortunately.

**Comment by jcalcaben** [comment]
This is a known issue that I am looking for potential solutions for.

**Comment by tanberry** [comment]
I do believe that Mr. @dshevtsov  is working this on an internal ticket. ;-) When he gets back from hiking in the Carpathians. I am NOT jealous. Sigh.

**Comment by xcomSteveJohnson** [comment]
This will probably be replaced by #794 but meanwhile, we're tracking it with MAGEDOC-2527.

**Comment by xcomSteveJohnson** [comment]
@hostep We removed the date entirely in favor of the [What's New on DevDocs](http://devdocs.magento.com/guides/v2.1/magento-devdocs-whatsnew.html) page. Closing.
