### ISSUE TITLE
Need to change `generation` to `generated` in command

### ISSUE THREAD

**Issue by chiranjeevi-cj** [magento/devdocs#8292]
# General issue

Affected file: src/guides/v2.4/install-gde/trouble/tshoot_wrong-mysql.html

## Description

In the latest Magento 2.4, there should not be a var/generation folder

## Possible solutions

Update Text from "rm -rf var/cache/* var/page_cache/* var/generation/" to "rm -rf var/cache/ var/page_cache/* generated/*"

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
@sathiyaaa Any progress on this issue?

**Comment by dobooth** [comment]
Looks like we removed that page in the Install Guide refresh effort.
