### ISSUE TITLE
Move and update the content from Magento Support KB to DevDocs

### ISSUE THREAD

**Issue by almarchenko** [magento/devdocs#8297]
In Magento Support Knowledge Base there's an article, which would better belong in Magento Devdocs: 
https://support.magento.com/hc/en-us/articles/360005032794 
So it would be great to "move" it to Devdocs, and updating if required.
High-level steps to complete this issue:

1. Take a look at the article and verify it's content. 
2. Create a new article in the relevant section of the Devdocs repo and copy the updated content from Support KB article. 
 
(this request is approved by Support KB team)

**Comment by jeff-matthews** [comment]
I discussed this with @almarchenko and agree that the KB article is out of scope for the Magento Knowledge Base (KB) and in scope for devdocs.

We already have a tutorial on devdocs that is similar, but not exact: https://devdocs.magento.com/guides/v2.4/howdoi/customize_product.html

**Comment by BarnyShergold** [comment]
@magento I am working on this

**Comment by jeff-matthews** [comment]
@almarchenko, the topic will be published on devdocs soon (~30 minutes). After it's published, you should set up a redirect from the KB article to https://devdocs.magento.com/guides/v2.4/howdoi/admin/customize_admin.html.
