### ISSUE TITLE
Undocumented breaking change in 2.3.6 - \Magento\Sales\Model\Order\Pdf\Invoice class 

### ISSUE THREAD

**Issue by pixel-paul** [magento/devdocs#8299]
### Summary (*)
After upgrading from 2.3.5-p1 to 2.3.6 an undocumented breaking change was introduced to the \Magento\Sales\Model\Order\Pdf\Invoice class. This prevents invoices from being printed if the class has been extended.

Ref: https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/reference.html

### Examples (*)
Before (2.3.5-p1):

```
public function __construct(
....
\Magento\Framework\Locale\ResolverInterface $localeResolver,
....

public function getPdf($invoices = []) {
..............
if ($invoice->getStoreId()) {
    $this->_localeResolver->emulate($invoice->getStoreId());
    $this->_storeManager->setCurrentStore($invoice->getStoreId());
 }
.........
if ($invoice->getStoreId()) {
    $this->_localeResolver->revert();
 }

```
After (2.3.6):
```
/**
* @var \Magento\Store\Model\App\Emulation
*/
private $appEmulation;

public function __construct(
....
\Magento\Store\Model\App\Emulation $appEmulation,
....

if ($invoice->getStoreId()) {
    $this->appEmulation->startEnvironmentEmulation(
    $invoice->getStoreId(),
     \Magento\Framework\App\Area::AREA_FRONTEND,
    true
    );
    $this->_storeManager->setCurrentStore($invoice->getStoreId());
}
......................
if ($invoice->getStoreId()) {
    $this->appEmulation->stopEnvironmentEmulation();
}
```
Because of this change and the introduction of a private function, extending this class has significantly changed.

### Proposed solution
Ensure breaking changes are documented

---
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

**Comment by erikmarr** [comment]
@maghamed can you please take a look at this issue and recommend someone who can help with documentation?

**Comment by dshevtsov** [comment]
NOTE
The reported change wasn't detected by our automation. See #8316 
This should be considered at magento/magento-semver#34.

**Comment by hostep** [comment]
If people end up here from a search engine, here's how we solved the constructor problem if you have a module which needs to support both Magento 2.3.5 and 2.3.6: https://github.com/magento/magento2/issues/30684#issuecomment-722602562

**Comment by jfrontain** [comment]
@pixel-paul, thanks for bringing this issue to our attention. I've updated the 2.3.6 release notes and will close this issue now. Let us know if we need to add additional information -- we want to get this right! Thanks again.

**Comment by pixel-paul** [comment]
@jfrontain - thanks for updating the breaking changes. I'm sure that will help people with updating. For me, this wasn't operationally a big deal, although I had to spend quite a bit of time debugging etc. to figure out the problem and then a solution. 

I appreciate on such a big project, keeping track of all the breaking changes must be a major challenge,  however it's still not clear why such a change was made on a minor point release. Are you are following semver 2? If so, you _can't_ 'BC Break' a minor release or patch version......

**Comment by jfrontain** [comment]
Actually, @pixel-paul, I wrote too quickly and mixed up this BiC with another issue. I'm re-opening this issue and will follow up today. Tracking these types of changes is a challenge, and we appreciate your help and patience.

**Comment by jfrontain** [comment]
Okay, the 2.3.6 release notes have been updated. Here's the PR: https://github.com/magento-commerce/devdocs/pull/2164
