### ISSUE TITLE
Update references to Payment sample module

### ISSUE THREAD

**Issue by qaniel** [magento/devdocs#8304]
# General issue

You are providing old version support of Magento and archived repo for code base on creating a custom payment method

## Description:

Affected page: /guides/v2.4/payments-integrations/base-integration/integration-intro.html

In the following text on the documentation:

To simplify the development of new payment integration, Magento developed the [Payment sample module](https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway). It contains all required infrastructure and you can use it as a starting point.

The link provided on **Payment sample module** link points to an outdated repo (even archived and 5yo) when specifying that the documentation if for Magento 2.4

## Possible solutions:

Create or Point such link to a recent version of the Payment sample module

## Additional information:

NOPE

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@dobooth Is there any working repo for the Payment sample module? If there, Can you please share the link. 
Thank You.

**Comment by chiranjeevi-cj** [comment]
@keharper @dobooth Is there any working repo for the Payment sample module?
Thank You.

**Comment by dobooth** [comment]
@chiranjeevi-cj Thanks for taking this. There is no new or update sample payment modules. We may as well remove that line from the docs.

**Comment by Viper9x** [comment]
@magento I am working on this
