### ISSUE TITLE
bug in documentation for memcached

### ISSUE THREAD

**Issue by strauss69400** [magento/devdocs#831]
Hi,
there is  a bug in the documentation about installation of memcached : 
http://devdocs.magento.com/guides/v2.0/config-guide/memcache/memcache_ubuntu.html

it must to replace this code by that 
`
if (class_exists('Memcache')) {
    $meminstance = new Memcache();
} else {
    $meminstance = new Memcached();
}

$meminstance->addServer("127.0.0.1", 11211);

$result = $meminstance->get("test");

if ($result) {
    echo $result;
} else {
    echo "No matching key found.  Refresh the browser to add it!";
    $meminstance->set("test", "Successfully retrieved the data!") or die("Couldn't save anything to memcached...");
}`

**Comment by xcomSteveJohnson** [comment]
Can you provide more detail?

**Comment by strauss69400** [comment]
The var $mem must be replaced by $meminstance.that s all!!

**Comment by xcomSteveJohnson** [comment]
@strauss69400 Should be fixed now, close this if so.
