### ISSUE TITLE
Change var/generation/ to generated/ globally

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#8338]
# General issue

## Description:

In Magento 2.4.0, the `var/generation` directory was changed to `generated`.

## Possible solutions:

Globally update references to `var/generation/*` and `generation/* to `generated/*` in all 2.4.x docs.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@jeff-matthews I have changed almost every place. Correct me if iam wrong. Below added PR for those fix
https://github.com/magento/devdocs/pull/8291
https://github.com/magento/devdocs/pull/8279

**Comment by jeff-matthews** [comment]
Thanks @chiranjeevi-cj! It looks like you did.
