### ISSUE TITLE
GraphQL: Miscellaneous requisition list mutations

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#8341]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: 

Magento 2 GitHub PR: https://github.com/magento/partners-magento2b2b/pull/448

Magento 2 version:

-  [ ] 2.4

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

The following requisition list mutations were not listed in #7990 or #7991, but still need to be documented:

addProductsToRequisitionList
updateRequisitionListItems
deleteRequisitionListItems

addRequisitionListItemsToCart
clearCustomerCart

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by keharper** [comment]
Closed via #8354
