### ISSUE TITLE
404 on Javascript Developer Guide

### ISSUE THREAD

**Issue by gamerboy** [magento/devdocs#836]
On [Javascript developer guide](http://devdocs.magento.com/guides/v2.1/javascript-dev-guide/bk-javascript-dev-guide.html) there is a 404 on this link: [disable all the default scripts and their load by RequireJS](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/javascript/custom_js.html#disable_default_js). 

Best regards,
Andrea

**Comment by almarchenko** [comment]
Thanks! Will fix this asap

**Comment by almarchenko** [comment]
Fixed! 
@gamerboy  thanks for reporting!
