### ISSUE TITLE
Container started using Docker Compose terminates with unexpected error

### ISSUE THREAD

**Issue by Serializator** [magento/devdocs#8370]
# Bug report

## Description

When using `docker-compose up` the container is terminated with the error below.

```
jekyll_1  | /usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /srv/jekyll/Gemfile.lock. (Gem::GemNotFoundException)
jekyll_1  | To update to the latest version installed on your system, run `bundle update --bundler`.
jekyll_1  | To install the missing version, run `gem install bundler:1.17.3`
jekyll_1  |     from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
jekyll_1  |     from /usr/local/bin/bundle:23:in `<main>'
```

### Steps to reproduce

- Clone the repository
- Run `docker-compose up`

## Expected result

Container is started without any issues.

## Possible solutions

Use `jekyll/jekyll:3` as the Docker image in the Docker Compose configuration.

**Comment by dshevtsov** [comment]
cc @hguthrie

**Comment by hguthrie** [comment]
Hi there! I will take a look at this. Thanks @dshevtsov

**Comment by hguthrie** [comment]
This is not exactly a bug. The simple docker compose YAML that is in our repo points to `jekyll/jekyll:latest`. The[ latest image uses ruby version 2.7.0](https://hub.docker.com/r/jekyll/jekyll/tags?page=1&ordering=last_updated), which is probably what is causing the errors you see. Devdocs is using [Ruby 2.6.6](https://github.com/magento/devdocs/blob/master/.ruby-version). You can change the docker-compose file to use `jekyll/jekyll:3.8.6` and it works.

**Comment by hguthrie** [comment]
The `docker-compose.yaml` file was provided by a contributor and is a nice, quick solution to use Docker. We do not have time to enhance this file, but anyone that does have the time and familiarity with Docker is welcome to create a more robust version. I am closing this issue.
