### ISSUE TITLE
Feedback on page: /cloud/before/before-workspace-ssh.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8372]
# General issue

## Description:

This section describes 2 methods of adding an SSH key:
https://devdocs.magento.com/cloud/before/before-workspace-ssh.html#ssh-add-to-account

* Using the Magento Commerce Cloud CLI
* Using the Magento Commerce Cloud Web Interface

There should be one additional method: Using the Cloud account dashboard.

Also, add another section about what to do if you have added a new SSH key

### **Add a key using the Cloud account dashboard**
You will add your SSH public key to your Cloud account.
1. Go to https://accounts.magento.cloud
2. Click on **Account Settings**
3. Under SSH keys, click on ``Add a public key``
4. Have another user on the project (with the Contributor role - at minimum) to redeploy each active environment you will have access to - this will install/upload your SSH key to the environment

### Updating your SSH key
If you have added a new SSH key into your Cloud account, you will have to redeploy each active environment that you currently have access to - this will install/upload your new key to the environment

**Comment by sathiyaaa** [comment]
@magento I am working on this
