### ISSUE TITLE
GraphQL: Update earlier requisition list PR

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#8376]
# Community engineering issue

Type of Doc:

-  [ ] New topic
-  [X] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: 
Magento 2 GitHub PR: https://github.com/magento/partners-magento2b2b/pull/448

Magento 2 version:

-  [x] 2.4.2

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

#8093 was correct at the time it was merged, but it was merged long before the code was finalized. The documentation added in that PR is now out of date.

Update the following topics are described below. All are located in the `src/guides/v2.4/graphql/mutations` directory:

**Important:** Create your branch off of the `requisition-lists` branch.

`create-requisition-list.md` - The syntax has changed, and the output is a `RequisitionList` object. Update all parts of the topic. The requisition object is located at `src/_includes/graphql/requisition-list.md`.

`delete-requisition-list.md` - The syntax has changed, and the output contains a `RequisitionList` object. Update all parts of the topic.

`rename-requisition-list.md` - This mutation was replaced with the `updateRequisitionList` mutation. Rename the file, make any necessary schema updates, and update all cross-references to it (including the TOC file).

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by keharper** [comment]
Fixed by #8381
