### ISSUE TITLE
404 on Composer Integration

### ISSUE THREAD

**Issue by sakiss** [magento/devdocs#838]
That page gives a 404 error
http://devdocs.magento.com/guides/v2.1/extension-dev-guide/composer-integration.html

The link comes from that page:
http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/required-configuration-files.html

**Comment by jcalcaben** [comment]
Thanks for pointing this out! I will fix it.

**Comment by jcalcaben** [comment]
It should point to this page:
http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/composer-integration.html

**Comment by jcalcaben** [comment]
Link is now fixed. Thanks for reporting this @sakiss!
