### ISSUE TITLE
Incorrect instructions for crontab errors

### ISSUE THREAD

**Issue by poprasad** [magento/devdocs#8392]
# General issue

## Description:

under https://devdocs.magento.com/cloud/configure/setup-cron-jobs.html#verify-cron-configuration-on-pro-projects it says:
 
If the crontab -l command returns a Command not found error, contact your Customer Technical Advisor (CTA) or Customer Success Manager (CSM) about enabling the auto-crons self-service configuration option on your Magento Commerce Cloud project.

## Possible solutions:
But I believe the infrastructure team would need to contacted to enable the auto-crons. Depending on the type of Pro – i.e.  if it’s wings and pro but with no auto-cron then should this section be updated to “Submit a ticket to enable auto crons”?

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by hguthrie** [comment]
@bdenham Is this still in progress?
