### ISSUE TITLE
Update PHP settings on performance best practices software page

### ISSUE THREAD

**Issue by pkodithuwakku** [magento/devdocs#8394]
# General issue

## Description:

The recommendation provided in https://support.magento.com/hc/en-us/articles/360050422532 article contradicts with the 
recommendation given in https://devdocs.magento.com/guides/v2.4/performance-best-practices/software.html#php-settings. In Magento cloud environments  opcache.enable_cli setting has to be set to 0, without that the changes in .magento.env.yaml are not get updated into app/etc/env.php file.

## Possible solutions:

Can we add a note in this https://devdocs.magento.com/guides/v2.4/performance-best-practices/software.html#php-settings document to mentioned that this opcache.enable_cli setting has to be set 0 in Magento cloud environments.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@chiranjeevi-cj @bdenham - Now that the linked PR has been closed and for the closure reasons, can this issue now also be closed?

**Comment by hguthrie** [comment]
Closed. Recent Cloud release address opcache.enable_cli default.
