### ISSUE TITLE
Set up multiple websites or stores on Cloud

### ISSUE THREAD

**Issue by bzahariev** [magento/devdocs#8411]
# Topic clarification/correction request

## Topic Link
https://devdocs.magento.com/cloud/project/project-multi-sites.html

## Possible solutions
Have a more simple and easy to understand and follow approach.
The attached file contains a recipe that has been followed successfully by several customers who had failed to follow the current text. It can be given either as an example or used to rework the current devdocs topic.

## Additional information
[multistore.txt](https://github.com/magento/devdocs/files/5712739/multistore.txt)

**Comment by hguthrie** [comment]
@bdenham Are you or will you be working on this or can we free this up for someone else?

**Comment by bdenham** [comment]
Yes, I can work on this starting Wednesday of this week. But if someone wants to start sooner, feel free to unassign me now. Thanks for the nudge!

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-cloud-service/user-guide/configure-store/multiple-sites).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-cloud-service.en/issues) it.
