### ISSUE TITLE
Feedback on page: /cloud/configure/import-url-rewrites.html

### ISSUE THREAD

**Issue by bhaveshpp** [magento/devdocs#8431]
# General issue

## Description:

The module is not available  I have tried to install it but could not find a matching version of the package
![image](https://user-images.githubusercontent.com/41717838/102857286-27c08b80-444e-11eb-908a-f33768123afc.png)

**Comment by dobooth** [comment]
This is more of a support issue than a docs issue. https://support.magento.com/hc/en-us/articles/360019088251-Submit-a-support-ticket
