### ISSUE TITLE
UI Components: Documentation of exports, imports, links, and listens Needed

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#844]
The UI Component guide has sections for the base [`uiClass`](http://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_uiclass_concept.html) object/class, and the base [`uiElement`](http://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_uielement_concept.html) object/class.  This is good.

However, the documentation provided doesn't go far enough.  In particular are these two sections.

> Also it declares communications between components if needed.
> 
> The initLinks() method implements component communication by using links.js. initLinks() introduces processing of the exports, imports, links and listens properties.

are all there is w/r/t to the import and export features of these objects, and this import/export system seems super important. 

Based on some of my own poking around the system, the `imports` and `exports` properties appear to be a system that allows programmers to 
1. Specify their object exports certain data, which will allow
2. Other objects to automatically **import** data properties from other objects.

However -- **how** this system works is still pretty unclear, and without a clear guide on how it works, developers will be left making wild guesses at how Magento's core objects behave, and aren't likely to adopt these constructs into their own code. 

I would assume the `links` and `listens` properties have similar, "object wide" implications.  These need to be documented. 

Similarly, the `defaults` concept needs fleshing out as well -- it's not clear from the existing guide that setting defaults on a class object will automatically populate data properties of new objects instantiated from that class.

**Comment by tanberry** [comment]
HI @astorm, thanks for those in-depth comments. Very pertinent phrase here: "... making wild guesses at how Magento's core objects behave, and aren't likely to adopt these constructs into their own code." We do indeed want the best practice constructs broadly utilized. 

So this very task you described above sounds like a good candidate or a How Topic: describe the steps by which a programmer can instruct an object to export certain data, and enable/instruct other objects to import data from that other object. Correct?

I'm thinking that some of those details will be covered in our planned topics on data (retrieving it from DB, populating the UI comps, etc). But agreed,  it would help to add some info right there in the topics about uiClass and uiElement, where we cover the initLinks() method....specifically about the "exports, imports, links and listens properties". 

And we will add some info about what setting defaults does.

Thanks!

**Comment by almarchenko** [comment]
internal issue magetwo-59999

**Comment by astorm** [comment]
Link of possible interest and relevance for folks looking for answers while the official docs are worked on: http://alanstorm.com/magento_2_uiclass_data_features/

**Comment by tanberry** [comment]
Thanks @astorm , we do appreciate you helping us fill the gaps. Check your Inbox, please, regarding a plan for a West Coast Doc Sprint for UI Components. Looking forward to a reply, thanks!

**Comment by almarchenko** [comment]
@astorm I do not why I missed closing this issue, the doc is published long ago!
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_linking_concept.html
Sorry for that!
Please reopen the issue of we missed something.
