### ISSUE TITLE
Update the checkout tutorial to show how to reorder billing/shipping address forms

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#8446]
# General issue

Affected page: /guides/v2.4/howdoi/checkout/checkout_overview.html

There is some very important information that would benefit a lot of users in the checkout customization. It's a very popular question that is needed in our country but as I see online there is a lot of interest online from other users as well but there's no official guidance on how to do it. 
The needed action is to reorder the billing and shipping address form, moving the billing address form above the shipping address form as it was in Magento 1.

## Description:

Currently Magento 2 is offering only shipping step then billing step and the possibility to fill in the shipping information and if you want it to differ, the billing information can be changed on the payment step. 

The use case is when we need to add some information which is tied to the billing address (e.g. our country requires not only VAT ID but also a few extra fields) which are all related to billing information e.g. type of receipt document, tax department etc etc. 

It's vital for the checkout process for the user to first select the type of receipt document and then fill in the billing information and finally the shipping information if it changes. 

These fields wouldn't apply to shipping information. 

Currently the user is only able to add the shipping information and then choose to change the billing information at payment step but this forces double form filling on their part leading to a bad checkout experience as well as other vital issues. 

E.g. they won't realize that they can order with a different type of receipt document and lose conversions.

## Possible solutions:

There should be a full guide of the steps needed to implement this change in the checkout workflow to accomodate different business needs. Currently everyone is working blindly on this. 
The guide on adding a new step doesn't help on this. 

## Additional information:

The final structure of the checkout fields Steps would be 

Step 1: Shipping/Billing Step

1.1 custom billing information fields
1.2 billing address form
1.3 checkbox -> my shipping address is the same as my billing address. 
1.4 shipping address form
1.5 Shipping Methods

Step 2: Payment Step

2.1 Payment Methods 

Do you think it would be possible to add further explanations on the docs on how to achieve such a customization task?

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-php/issues) it.
