### ISSUE TITLE
 Hello, if I ask, do I have a friend to help me install magento 

### ISSUE THREAD

**Issue by bybilgili** [magento/devdocs#8451]
Hello, if I ask, do I have a friend to help me install magento     whatsapp : +905415159595

**Comment by bybilgili** [comment]
Can you install it via remote assistance program

**Comment by bybilgili** [comment]
magento 2,4 
Can you install it via remote assistance program

**Comment by BarnyShergold** [comment]
This is not the place to ask this question - this is DEVDOCS. I can recommend that you join the Magento Community Engineering Slack channel and posting to #general 

Closing as this is not a DEVDOCS issue
