### ISSUE TITLE
Correction on https://magento.redoc.ly/2.4.1-admin/tag/productsattributes

### ISSUE THREAD

**Issue by andrewmortiz** [magento/devdocs#8461]
# Topic clarification/correction request
Options > Value under POST /V1/products/attributes listed as required; however, this doesn't seem to be correct.
## Topic Link

https://magento.redoc.ly/2.4.1-admin/tag/productsattributes

## Description
![image](https://user-images.githubusercontent.com/18596805/103446455-7e477a00-4c45-11eb-8988-c06078215b79.png)

## Possible solutions

Remove the required flag on that value.

## Additional information

Can be quickly tested on swagger by removing the field under the default json example

`curl -X POST "FILTERED" -H  "accept: application/json" -H  "Content-Type: application/json" -H  "Authorization: Bearer FILTERED" -d "{  \"attribute\": {    \"extension_attributes\": {      \"is_pagebuilder_enabled\": true    },    \"is_wysiwyg_enabled\": true,    \"is_html_allowed_on_front\": true,    \"used_for_sort_by\": true,    \"is_filterable\": true,    \"is_filterable_in_search\": true,    \"is_used_in_grid\": true,    \"is_visible_in_grid\": true,    \"is_filterable_in_grid\": true,    \"position\": 0,    \"apply_to\": [      \"string\"    ],    \"is_searchable\": \"string\",    \"is_visible_in_advanced_search\": \"string\",    \"is_comparable\": \"string\",    \"is_used_for_promo_rules\": \"string\",    \"is_visible_on_front\": \"string\",    \"used_in_product_listing\": \"string\",    \"is_visible\": true,    \"scope\": \"string\",    \"attribute_id\": 0,    \"attribute_code\": \"string\",    \"frontend_input\": \"select\",    \"entity_type_id\": \"string\",    \"is_required\": true,    \"options\": [      {        \"label\": \"string\",        \"sort_order\": 0,        \"is_default\": true,        \"store_labels\": [          {            \"store_id\": 0,            \"label\": \"string\"          }        ]      }    ],    \"is_user_defined\": true,    \"default_frontend_label\": \"string\",    \"frontend_labels\": [      {        \"store_id\": 0,        \"label\": \"string\"      }    ],    \"note\": \"string\",    \"backend_type\": \"string\",    \"backend_model\": \"string\",    \"source_model\": \"string\",    \"default_value\": \"string\",    \"is_unique\": \"string\",    \"frontend_class\": \"string\",    \"validation_rules\": [      {        \"key\": \"string\",        \"value\": \"string\"      }    ],    \"custom_attributes\": [      {        \"attribute_code\": \"string\",        \"value\": \"string\"      }    ]  }}"`

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by keharper** [comment]
@andrewmortiz @sathiyaaa This is a code problem and devdocs can't fix this.

We autogenerate the schema and make some programmatic edits for displaying on ReDoc.  These edits don't touch the technical details of the schema. The following screenshot shows the same issue in the native Swagger, so the problem isn't with our edits.

![Screen Shot 2021-01-04 at 9 10 04 AM](https://user-images.githubusercontent.com/11652541/103549509-1a9f9580-4e6d-11eb-9c35-75835ce6a2c8.png)

Most likely, the schema references the EavDataAttributeOptionInterface in multiple places, and the `value` and `label` attributes are truly required in some other endpoint.

We will not make manual edits to the schema. If you can find the reason the `value` attribute is incorrectly labeled as required, please open an issue against the code.
