### ISSUE TITLE
GraphQL: Document CORS support

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#8465]
# Community engineering issue

Type of Doc:

-  [ ] New topic
-  [x] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/31195

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/31484

Magento 2 version:

-  [x] 2.4

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

### Do not start working on this issue until Magento has approved PR https://github.com/magento/magento2/pull/31484

Add documentation that describes GraphQL CORS support.

CORS support was originally a feature targeted for 2.4.2, but Magento did not merge that code into mainline. You can use the text in #7629 as a starting point, if the code in https://github.com/magento/magento2/pull/31484 is compatible. (#7815 reverted those doc updates.)

## Additional information

CORS support is a 2.4.3 feature. Create your PR off of the `2.4.3-develop` branch.

~~As of the moment I'm writing this issue, there is no `2.4.3-develop` branch. If the `2.4.3-develop` branch exists when you start working on this issue, create your PR against it. Otherwise, create the PR against the `2.4.2-develop` branch with the knowledge that it will need to be rebased.~~

If this iteration of CORS support does not warrant a new topic, then be sure to break the symlink using the `rake symlink:replace_at path=src/guides/v2.4/graphql/send-request.md` command.

**Comment by G-Arvind** [comment]
@magento I am working on this

**Comment by keharper** [comment]
@G-Arvind If you've started working on this issue, be aware that there is now a `2.4.3-develop` branch.

**Comment by keharper** [comment]
This PR also contains documentation that was backed out. 

https://github.com/magento/merchdocs/pull/637/

**Comment by keharper** [comment]
@G-Arvind A Magento development team is finishing the original PR. Do you want to submit a devdocs PR to cover the work that you completed, or would you prefer that I do all the work to complete this issue.

If you want to start the work and get the credit for it:

1. Add the content that was originally committed in #7629, making any updates.
2. Update the `env.php` reference, located at `src/guides/v2.4/config-guide/prod/config-reference-envphp.md`. Where applicable, you can re-use the text provided in magento/merchdocs#637.

Please let me know your decision by Thursday, February 25.
