### ISSUE TITLE
GraphQL: Add docs for routes query and RoutableInterface

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#8466]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/31196

Magento 2 GitHub PRs:
- https://github.com/magento/magento2/pull/31490
- https://github.com/magento/partners-magento2ee/pull/445

Magento 2 version:

-  [x] 2.4

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

### Do not start working on this issue until Magento has approved PR https://github.com/magento/magento2/pull/31490

1. Add the `routes` query.
2. Add a new topic for RoutableInterface.
3. Break the symlink for the `urlResolver` query and mark the 2.4 version as deprecated.
4. Update the `*Product` type documentation (BundleProduct, ConfigurableProduct, etc.) as well as the `CmsPage` and `CategoryTree` documentation to indicate support for the RoutableInterface.
5. Update the list of cached queries in `graphql/caching.md`.

## Additional information

The RoutableInterface is a 2.4.3 feature. Create your PR against the `2.4.3-develop` branch.

Use the `rake symlink:replace_at path=src/guides/v2.4/graphql/queries/url-resolver.md` command to break the symlink.

**Comment by KrishnaK-Z** [comment]
@magento I am working on this

**Comment by keharper** [comment]
Not sure why this is still open. Work was completed long ago.
