### ISSUE TITLE
Feedback on page: /cloud/reference/cli-ref-topic.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8471]
# General issue

## Description:

https://devdocs.magento.com/cloud/reference/cli-ref-topic.html

This point should be clarified:
```
 You can install and use this utility for all Magento Commerce Cloud Starter and Pro Integration environments.
```

Merchants think it means that it can be **installed on all environments.** which is not the case

## Possible solutions:

Change it to 
```
You would have to install this on your local workstation, and you can use this utility for all Magento Commerce Cloud Starter and Pro Integration environments. 
```

**Comment by dineshvb** [comment]
@magento I am working on this
