### ISSUE TITLE
Feedback on page: /guides/v2.4/graphql/queries/customer-orders.html

### ISSUE THREAD

**Issue by shashankparikh** [magento/devdocs#8479]
# General issue
Can't able to fetch orders while using customer query.
## Description:
query {
  customer {
    orders(
      pageSize: 20
    ) ...

gives the error of orders in customer query.

gives the error of orders in customer query.

**Comment by keharper** [comment]
@shashankparikh Support for the order history in the `customer` query was added in 2.4.1. I ran the query on the a 2.4.2 build (I don't have a 2.4.1 build handy), and the code sample works. You opened this issue against the `customerOrders` query. That code sample still works as well, although the query has been deprecated.

Reopen this issue if I haven't addressed the problem. If you do, provide more details about the problem and update the title to indicate which query you're talking about.
