### ISSUE TITLE
missing "(optional)" ?

### ISSUE THREAD

**Issue by cottton** [magento/devdocs#848]
> Defines whether the product ID or SKU is passed in the 'product' parameter

Shouldnt this parameter be marked as **(optional)** ?

https://github.com/magento/devdocs/blob/develop/guides/m1x/api/soap/catalog/catalogProductAttributeMedia/catalog_product_attribute_media.info.html#L67

**Comment by xcomSteveJohnson** [comment]
Did you omit the endpoint and verify the service works?

**Comment by xcomSteveJohnson** [comment]
@cottton Reminder, please update us.

**Comment by xcomSteveJohnson** [comment]
Closing for lack of response. Feel free to reopen.
