### ISSUE TITLE
Notification flag (string) ?

### ISSUE THREAD

**Issue by cottton** [magento/devdocs#849]
> string | notify | Notification flag (optional)

Shouldnt this be an **int**?

https://github.com/magento/devdocs/blob/develop/guides/m1x/api/soap/sales/salesOrder/sales_order.addComment.html#L65

**Comment by xcomSteveJohnson** [comment]
I'm told the WSDL specifies string. Can we close this?

**Comment by xcomSteveJohnson** [comment]
Closing, feel free to reopen if you still have questions.
