### ISSUE TITLE
How do we fix 

### ISSUE THREAD

**Issue by monstro805** [magento/devdocs#8510]
https://github.com/magento/devdocs/blob/b97c8712478ca8b0b3ce49c6bb8f1cfae54c63b5/.github/workflows/linter.yml#L47

**Comment by monstro805** [comment]
hello how do we fix this issue ???

**Comment by BarnyShergold** [comment]
@monstro805 - You haven't actually said what the problem is and why its a problem.

**Comment by BarnyShergold** [comment]
Closing this as it doesn't actually report a problem. @monstro805, please reopen if you update it.
