### ISSUE TITLE
Feedback on page: /cloud/deploy/smart-wizards.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8527]
# General issue

## Description:

It appears that the Smart Wizards may no longer be available in the latest update of ECE Tools (2002.1.4)

## Possible solutions:

Verify the version compatibility and add a notice about which version(s) of ECE Tools this applies to

**Comment by hguthrie** [comment]
@ak77-prime  Are you receiving some error that indicates the commands are no longer available? The Cloud guide represents the latest version of the Cloud tools.
The Wizard commands are still in the [2002.1 development branch of the ece-tools repository](https://github.com/magento/ece-tools/tree/2002.1/src/Command/Wizard), as well as their latest `develop` branch, so not sure what you are experiencing.

**Comment by ak77-prime** [comment]
I tried running the command on some cloud merchant's servers - they are on ECE Tools 2002.1.4 - but it gives an error There are no commands defined in the "wizard" namespace

e.g., in the uyjy6h7avtxes_stg environment

Anthony Chico
technical SUPPORT ENGINEER
Magento CUSTOMER ENGINEERING
T +1 424.258.3354  |  C +1 626.400.3699
anchico@adobe.com<mailto:anchico@adobe.com>
3640 Holdrege Ave, Los Angeles, CA, 90016, USA
[cid:image001.png@01D6F3F6.A5EF8310]


[cid:image004.png@01D6F3F6.A5F4B330][cid:image003.png@01D6F3F6.A5EF8310]

**Comment by BarnyShergold** [comment]
@ak77-prime @hguthrie 
I can confirm that there is no problem with Wizards on ECE-TOOLS 2002.1.4 - I just upgraded a test instance, deployed and checked.

Normally when an expected namespace disappears it means there is a bug somewhere that prevents it from being listed ir run.

My recommendation is that this is NOT a DevDocs issue and so should be closed and @ak77-prime needs to raise it with Magento as there may be a build issue. Cloud server logs should also be checked.

BTW @ak77-prime - What is the full output of running ./vendor/bin/ece-tools on the server?

**Comment by dobooth** [comment]
@ak77-prime Closing this for now. We can verify this internally before opening an issue.
