### ISSUE TITLE
Feedback on page: /guides/v2.4/extension-dev-guide/plugins.html

### ISSUE THREAD

**Issue by bogdan-tomi** [magento/devdocs#8532]
# General issue

## Description:

Regarding prioritizing plugins (https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html#prioritizing-plugins), the sort order of after plugins is not the specified "Following the execution flow, starting from lowest to highest sortOrder in the current sequence plugins loop.", but rather **highest to lowest** instead.

Also, all the examples should be reviewed, as they also misrepresent the actual order of execution.

**Comment by korovitskyi** [comment]
Hi, @bogdan-tomi .
Information of this article part is actual.
You can see the message `The around plugin’s method affects the flow of all plugins that are executed after it.` there.
If using `around` it may destructure prioritizing of the plugin.
You can see it at **Scenario B (with a callable around)**.
Methods will call there by the next steps:
1) PluginA::beforeDispatch()
2) PluginB::beforeDispatch()
3) PluginB::aroundDispatch() 
4) PluginC::beforeDispatch()
5) PluginC::afterDispatch()
6) PluginA::afterDispatch()
7) PluginB::afterDispatch()
