### ISSUE TITLE
All inlined scripts for v2.4+ should use secureRenderer

### ISSUE THREAD

**Issue by Leland** [magento/devdocs#8546]
# Topic clarification/correction request

## Topic Link

* https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_init.html#init_script
* https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_loader.html#loader_init
* https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget-trim-input.html#initialize-the-triminput-widget

etc.

## Description

Given that Magento 2.4 begins the usage of Content Security Policies, the Devdocs are an _excellent place_ to begin promoting it.

The best way to do that, I think, might be to first move all inlined/imperatively declared scripts to take advantage of the secure renderer: https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html#whitelist-an-inline-script-or-style

**Comment by dobooth** [comment]
Closing this. See note in #8576.
