### ISSUE TITLE
[2.4.2] Document the new `--no-parent` flag in the static content deploy command

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#8561]
# Topic clarification/correction request

## Topic Link

- https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-static-view.html

## Description

This [pull request](https://github.com/magento/magento2/pull/30090) added a new `--no-parent` flag to the `setup:static-content:deploy` command to significantly improve its performance.
And this will be included in Magento 2.4.2

## Possible solutions

Describe the new `--no-parent` flag in all places where you describe the `setup:static-content:deploy` flags

## Additional information

Please read through all the comments in the pull request, the initial description no longer makes much sense. The implementation had to be changed a few times while the author worked on the pull request.

**Comment by dobooth** [comment]
@ihor-sviziev I was hoping you could contribute a bit here, seeing as you wrote the code. If you have a chance, that would be great.

**Comment by ihor-sviziev** [comment]
@dobooth will see if I'll have some free time - maybe will contribute. Anyway feel free to work on it if you wish

**Comment by ihor-sviziev** [comment]
@dobooth will see if I'll have some free time - maybe will contribute. Anyway feel free to work on it if you wish

**Comment by ihor-sviziev** [comment]
Hi @hostep,
It seems like this issue already fixed by https://github.com/magento/devdocs/pull/8765.

**Comment by hostep** [comment]
Ah right, I thought this issue was going to get auto-closed by that PR, but that didn't happen apparently.

Let me manually close it then.

Thank you again @chandru-199! 🙂

**Comment by keharper** [comment]
Thanks @hostep The PR description didn't include a phrase like `fixes <issue num>`.
