### ISSUE TITLE
Checkout Customisation instructions do not work

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8563]
# General issue

## Description:

Feedback on page: /guides/v2.4/howdoi/checkout/checkout_edit_form.html

I tried to apply the information from the [documentation ](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_edit_form.html)to add a logo to the payment method.
But it does not work and nothing has changed. The instructions seem to be wrong.

Details can be found [here](https://github.com/magento/magento2/issues/31833).

**Comment by Viper9x** [comment]
@magento I am working on this

**Comment by Viper9x** [comment]
Hi @Eddcapone 
As I've commented in your issue on [magento 2 repository](https://github.com/magento/magento2/issues/31833)
You've done the wrong way.
The purpose of the document page you applied is "Add a custom template for a form field on Checkout page"
But your task is to customize the payment method.

I've tested the example on the document page and got successful.

**Comment by gamarshall** [comment]
Is this still an issue?

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/add-template/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-php/issues) it.
