### ISSUE TITLE
Instructions for disabling component are not clear enough

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8564]
# General issue

## Description:

Feedback on page: /guides/v2.4/howdoi/checkout/checkout_customize.html

In the [documentation ](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_customize.html)it says:

![image](https://user-images.githubusercontent.com/16349349/105827832-c0ed3f80-5fc2-11eb-8822-e6b539a4df06.png)

So I tried it by disabling the amazon pay button at the top:

![image](https://user-images.githubusercontent.com/16349349/105827999-f09c4780-5fc2-11eb-94c4-eab812eaf724.png)

I used this [extension](https://github.com/ho-nl/magento2-Ho_Templatehints), to figure out that the KnockoutJS path for the button is at **checkout.steps.shipping-step.shippingAddress**:

![image](https://user-images.githubusercontent.com/16349349/105828440-6bfdf900-5fc3-11eb-8b76-9991732148c1.png)

So I applied the information from the documentation to disable the component. It does not explain that we have to put it into jsLayout, but I think this is logical.

app\design\frontend\company\fresh\\**Amazon_Payment\layout\checkout_index_index.xml**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="checkout.root">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="checkout" xsi:type="array">
                            <item name="children" xsi:type="array">
                                <item name="steps" xsi:type="array">
                                    <item name="children" xsi:type="array">
                                        <item name="shipping-step" xsi:type="array">
                                            <item name="children" xsi:type="array">
                                                <item name="shippingAddress " xsi:type="array">
                                                    <item name="config" xsi:type="array">
                                                        <item name="componentDisabled" xsi:type="boolean">true</item>
                                                    </item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```

Then I executed `rm -r pub/static/frontend/* var/view_preprocessed/* && bin/magento cache:flush` and cleared the browser cache, but the button is still showing

**Comment by gixid192** [comment]
You have trailing space in your code ` <item name="shippingAddress "`, that's the reason it does not disable.

**Comment by Eddcapone** [comment]
Ohh... Sorry for this. I am closing the issue. Unfortunatelly there was no error showing to point this out. Thank you!
