### ISSUE TITLE
Article should start with illustration

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8565]
# General issue

## Description:
Feedback on page: /guides/v2.4/howdoi/checkout/checkout_form.html

The article should start with the illustration to let us know about the main goal of these instructions.
It would be much easier to understand.

## Possible solutions:

Move the illustration from the bottom of the page to the top for more clarity.

**Comment by shrielenee** [comment]
Hello @Eddcapone --- Is this a request to move the illustration that currently exists at the bottom of the page to the top? Or is this a request for another illustration?

**Comment by Eddcapone** [comment]
@shrielenee , yes, in my oppinion it would be much better, because we will understand what this is all about.

**Comment by shrielenee** [comment]
@Eddcapone I didn't quite understand your reply. I'm going to assume that you are requesting that we move the current illustration from the bottom of the page to the top. If I'm incorrect, please respond. Thanks!

**Comment by Eddcapone** [comment]
Exactly. I ask you to place it at the top, so we initially understand what the article is all about.
