### ISSUE TITLE
Illustrative example needed

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8566]
# General issue

## Description:

Feedback on page: /guides/v2.4/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.html

I've read through it but I dont fully understand the example.
What exactly is the code doing? From my understanding a form is created, but where can I see it?
Please make it easier to understand for beginners and add some screenshots to it.

**Comment by shrielenee** [comment]
On internal review, we should potentially remove the first level Overview heading as it is not needed.

**Comment by gixid192** [comment]
@Eddcapone could you give more information about what you want?
To me the guide provides basic information and it demonstrates with code and explanation well.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/frontend-core/ui-components/concepts/xml-declaration/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-frontend-core/issues) it.
