### ISSUE TITLE
Need example for new_component_declaration topic

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8570]
# General issue

## Description:

Feedback on page: [/guides/v2.4/ui_comp_guide/howto/new_component_declaration.html](https://devdocs.magento.com/guides/v2.4/ui_comp_guide/howto/new_component_declaration.html)

The article needs an example so we can understand the process.

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/frontend-core/ui-components/howto/new-component-declaration/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-frontend-core/issues) it.
