### ISSUE TITLE
Example not working - more information needed

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8571]
# General issue

## Description:

Feedback on page: /guides/v2.4/ui_comp_guide/components/ui-container.html

There is not enough information provided to be able to test the example.
Where do we have to add the code?

I created a layout file for the checkout for testing and added the code into it:

**app\design\frontend\company\fresh\Magento_Checkout\layout\checkout_index_index.xml**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <container name="container_name">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="template" xsi:type="string">ui/form/components/complex</item>
                    <item name="sortOrder" xsi:type="number">10</item>
                    <item name="label" xsi:type="string">Container Label</item>
                    <item name="additionalClasses" xsi:type="string">sample-additional-class</item>
                    <item name="text" xsi:type="string" translate="true"><![CDATA[
                        <p>
                            Container Text.
                        </p>
                    ]]></item>
                </item>
            </argument>
            <field name="sort_direction"
                   sortOrder="20"
                   formElement="select">
                <settings>
                    <dataType>text</dataType>
                    <label translate="true">Sort Direction</label>
                    <dataScope>data.sort_direction</dataScope>
                </settings>
                <formElements>
                    <select>
                        <settings>
                            <options class="Vendor\Module\Model\Source\Config\SortDirection" />
                            <caption translate="true">-- Please Select --</caption>
                        </settings>
                    </select>
                </formElements>
            </field>
        </container>
    </body>
</page>
```

But I get this error:

**1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'argument': This element is not expected. Expected is one of ( block, container, referenceBlock, referenceContainer, uiComponent ).
Line: 3753**

So either your example is not working or you missed some important steps in the instructions.

**Comment by Viper9x** [comment]
@magento I am working on this

**Comment by Viper9x** [comment]
> Where do we have to add the code?

It's ** #UI Component**, not a layout element so it must be put inside UI component file.
The Container UI component must be located in the scope of _<fieldset>_ node
Ref: vendor/magento/module-inventory-catalog-admin-ui/view/adminhtml/ui_component/product_form.xml

I'll update devdocs page.
