### ISSUE TITLE
Could not find a matching version of package magento/extension-b2b.

### ISSUE THREAD

**Issue by viveknetsmartz** [magento/devdocs#8572]
# General issue
Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

## Description:

Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

## Possible solutions:
![Screenshot from 2021-01-27 13-19-38](https://user-images.githubusercontent.com/72607995/105979560-d5603380-60b9-11eb-8227-5addb94b5780.png)

## Additional information:

I am trying to install the B2B extension on the magento2.4.1 version and getting this issue added below.

Error Comes 
"Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable)."

**Comment by BarnyShergold** [comment]
@viveknetsmartz - this is not a DEVDOCS issue. You have a technical issue. You should either raise this with Magento Support (please remember that B2B is for COMMERCE only) or you could ask on either #general or #b2b on the Magento Community Slack channel. It would be good to post you "require" section of the composer.json to give more info.

Closing this ISSUE as it is not a DEVDOC issue.
