### ISSUE TITLE
Feedback on page: /guides/v2.4/install-gde/install/cli/install-cli.html

### ISSUE THREAD

**Issue by lipsa-git** [magento/devdocs#8574]
# General issue

**Comment by lipsa-git** [comment]
![image](https://user-images.githubusercontent.com/55824806/106002435-183aff00-60ec-11eb-96fd-8c231e4ab364.png)



not able to proceed to next step . How can i proceed to next?

**Comment by lipsa-git** [comment]
Hi Team, Can get a quick support on this.

**Comment by chickenland** [comment]
Magento 2.4 dropped the UI installation - you need to install via CLI.

**Comment by BarnyShergold** [comment]
As the page indicated refers to Magento CLI and the issue raiser is querying the UI installation which has now been dropped (which is also indicated as being the installation method in the screenshot) there is no issue that needs addressing on the DevDocs itself, so I am closing this issue.
