### ISSUE TITLE
CSP RenderTag missing in JS Resource Docs

### ISSUE THREAD

**Issue by PivitParkour94** [magento/devdocs#8576]
# Bug report

## Description
The issue is that as of Magento 2.4.x the Magento_CSP module is meant to be used, which means all phtml templates that render JS script tags should be done via the `$csp->renderTag('script', [], $scriptString, false);` method.

### Steps to reproduce

1. Look at JS resource docs
1. See it's a copy of the 2.3 documentation
1. Laugh a little

## Expected result

Look at 2.4 docs, expect to see the CSP specific method for rendering.

## Possible solutions
This request is to update the JS Resource devdoc to add in a little something explaining how to acomodate the CSP rendering.

## Additional information
This issue is very clear by looking at how the Captcha template is rendered differently between Magento 2.3.5 and Magento 2.4.0
https://github.com/magento/magento2/blob/2.3.5/app/code/Magento/Captcha/view/adminhtml/templates/default.phtml
https://github.com/magento/magento2/blob/2.4.0/app/code/Magento/Captcha/view/adminhtml/templates/default.phtml#L49

Noting the `$scriptString` variable.

It's difficult to justify spending the dev time to modify our modules, when the suggested way of doing things, currently doesn't align with how Core actually do things.
Hopefully if people start seeing ways to accommodate the CSP rendering, the provided solutions in Forums will be linking to the dev docs, rather than saying "Just disable the Magento_CSP module" as it currently is.

**Comment by PivitParkour94** [comment]
the specific page I am referring to is https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js-resources.html

**Comment by PivitParkour94** [comment]
Found a related issue #8546

**Comment by dobooth** [comment]
Closing this issue and #8546. The renderTag can't capture all instances of unsafe, in-line scripts, so we don't want to use it in docs as a recommended method.

**Comment by Leland** [comment]
> The renderTag can't capture all instances of unsafe, in-line scripts, so we don't want to use it in docs as a recommended method

Given that the [Dev Docs also mention](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html#whitelist-an-inline-script-or-style):

> Stores that have unsafe-inline disabled for style-src and script-src (default for Magento 2.4) inline scripts and styles must be whitelisted

...it seems odd that the actual code snippets used throughout the docs wouldn't follow this practice, right? IMO, the docs should provide real, usable code to devs – rather than leaving the conversion of them to a secureRender-equivalent as an exercise to the reader.

**Comment by PivitParkour94** [comment]
Yeah definitely agree @Leland 
I'd hope that as a dev I can go to the dev docs, copy and paste the code and then modify it for my needs, or at least have a clear understanding of what changes I need to make in the modules I am building

**Comment by PivitParkour94** [comment]
In the examples, could we have the snippet instead of 

```
<script>
   require([
      'jquery',
      'slick',
      'domReady!'
   ], function ($) {
      $(".my-list").slick({
         dots: true,
         infinite: true,
         speed: 300,
         slidesToShow: 4,
         slidesToScroll: 1
      });
   });
</script>
```

We could show how it COULD be rendered using the CSP renderer
```
<?php
$scriptString = <<<script
     require([
      'jquery',
      'slick',
      'domReady!'
   ], function ($){
$(".my-list").slick({
         dots: true,
         infinite: true,
         speed: 300,
         slidesToShow: 4,
         slidesToScroll: 1
      });
   });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
```

Then we could have a linked note saying something like "having inline scripts is not as preferable as loading the script in using the mage-init attribute or custom x-magento-init tag (see <link to info about that>)

If that is in fact how we're wanting JS dev to be used in the future, it's still a bit foggy on what we SHOULD actually be implementing in our modules. I think this could clear it up well.

What do you think?
@dobooth
