### ISSUE TITLE
?

### ISSUE THREAD

**Issue by monstro805** [magento/devdocs#8579]
https://github.com/magento/devdocs/blob/b97c8712478ca8b0b3ce49c6bb8f1cfae54c63b5/.github/workflows/linter.yml#L47

**Comment by keharper** [comment]
@dshevtsov Would you take a look at this issue and probably close it?

**Comment by dshevtsov** [comment]
We've had one already https://github.com/magento/devdocs/issues/8510.

@monstro805 please provide more information about your issue if you want it to be resolved.
