### ISSUE TITLE
Feedback on page: /guides/v2.4/howdoi/checkout/checkout_new_field.html - Misleading snippet

### ISSUE THREAD

**Issue by barbazul** [magento/devdocs#8581]
# General issue

## Description:

Step 2 snippet acceses the custom_field value with `shippingAddress.customAttributes['custom_field']`.
However, following instructions in Step one, `shippingAddress.customAttributes`is actually an array like the following:

```
[
  {
    attribute_code: 'custom_field',
    value: <actual value>
  }
]
```

## Possible solutions:

Array.find could be used to locate the corresponding object and extract the value

```
var attribute = shippingAddress.customAttributes.find(
  function (element) {
   return element.attribute_code === 'custom_field';
  }
);

shippingAddress['extension_attributes']['custom_field'] = attribute.value;
```

**Comment by dineshvb** [comment]
@magento I am working on this
