### ISSUE TITLE
Wrong bash commands in devdocs

### ISSUE THREAD

**Issue by molneek** [magento/devdocs#859]
1. Go to http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-php5.65-install-ubuntu14
2. Find install PHP 5.5 instruction. 

Expect result: Find bash commands for PHP 5.5 installation
Actual result: Got  bash commands for PHP 5.6 installation

**Comment by xcomSteveJohnson** [comment]
Oops! Sorry about that!

Fixed now, please close this issue if you're satisfied.
