### ISSUE TITLE
GraphQL: Add mutations for managing gift registry registrants

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#8603]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/28586

Magento 2 GitHub PR: https://github.com/magento/partners-magento2ee/pull/280

Magento 2 version:

-  [x] 2.4.3

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add new topics that cover the following mutations

addGiftRegistryRegistrants
removeGiftRegistryRegistrants
updateGiftRegistryRegistrants

Acceptance Criteria:

* The PR must be submitted from a local branch off of the devdocs `gift-registry` branch
* Each topic must contain an example that uses the gift registry provided with the Luma sample data
* The GraphQL TOC file must be updated to include the new topics.

## Additional information

See #8600 if you're unsure about file locations, naming conventions, standards, etc.

**Comment by andrewbess** [comment]
@magento I am working on this

**Comment by keharper** [comment]
Assigning to myself due to time constraints. I discussed this with @andrewbess beforehand.

**Comment by keharper** [comment]
#8749 was rolled into https://github.com/magento-commerce/devdocs/pull/2115
