### ISSUE TITLE
Feedback on page: /guides/v2.4/soap/bk-soap.html

### ISSUE THREAD

**Issue by chickenland** [magento/devdocs#8604]
# General issue

## Description:

The overview for catalog SOAP API endpoint includes the notation * against a number of endpoints, however, it doesn't make any reference to what this means on those endpoints.

## Possible solutions:

Add a definition against the *.

**Comment by BarnyShergold** [comment]
@meker12 @jeff-matthews @dshevtsov - I've checked this page and there are "*" next  to some API endpoints in the catalog section and it looks like they mean "refer to footnote" but there is none on the page. It is not clear in anyway what the "*" is for.

As you are the only people with changes to this page please can you take a look and let us know what the "*" is for?

**Comment by jeff-matthews** [comment]
It's not clear what the asterisks represent. I don't see anything in the history that sheds any light an it either. @keharper, do you know?

**Comment by dshevtsov** [comment]
Looks like some text had been lost since 2.2 https://github.com/magento/devdocs/commit/355970339af9e9fc89616606c59e777403d6bbd1#diff-b92ea9c2ab16aa9506f5bfb81a533a2c905ddc35fe875937ffd3fe9759caf0dfR18

**Comment by dshevtsov** [comment]
FYI [Tags](https://github.com/magento/devdocs/tags) are very helpful to explore older versions.

**Comment by BarnyShergold** [comment]
As 2.1 & 2.2 are now unsupported versions, can these "*" not just be removed?

**Comment by dshevtsov** [comment]
I agree. @keharper, do you approve such removal?
