### ISSUE TITLE
Feedback on page: /cloud/cdn/configure-fastly.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8608]
# General issue

## Description:

https://devdocs.magento.com/cloud/cdn/configure-fastly.html#update-dns-configuration-with-development-settings

Add a note that custom domains are not supported for Starter projects

``Starter projects:``
* mcprod.<your-domain>.com

## Possible solutions:

```You cannot specify a custom domain in Staging for your Starter project```

**Comment by dineshvb** [comment]
@magento I am working on this
