### ISSUE TITLE
https://devdocs.magento.com/safe-upgrade-tool/introduction.html [Missing]

### ISSUE THREAD

**Issue by shaneherman** [magento/devdocs#8616]
# General issue

This page has gone missimg:

https://devdocs.magento.com/safe-upgrade-tool/introduction.html

## Description:

Expected for page to be there as this was an announced tool / page.

## Possible solutions:

Provide more details if tool will be available or not.

**Comment by jeff-matthews** [comment]
@shaneherman, the correct URL is https://devdocs.magento.com/upgrade-compatibility-tool/introduction.html. 

@danidelcar, please investigate why the redirect isn't working.

**Comment by shaneherman** [comment]
Thanks @jeff-matthews .. Google has the above page Indexed so appreciate fixing the Redirect.

**Comment by danidelcar** [comment]
I'll look into it today, thanks for the alert!

> @shaneherman, the correct URL is https://devdocs.magento.com/upgrade-compatibility-tool/introduction.html.
> 
> @danidelcar, the redirect isn't working because there's a syntax error in the file's metadata. You're missing an underscore between "redirect" and "from". See my comments in #8573.
> 
> The correct syntax is:
> 
> ```
> redirect_from:
>   - /safe-upgrade-tool/introduction.html
> ```

thanks @jeff-matthews

**Comment by danidelcar** [comment]
created PR to fix issue, thanks @jeff-matthews & @shaneherman
