### ISSUE TITLE
Grunt less compiling in Docker environment

### ISSUE THREAD

**Issue by bdenham** [magento/devdocs#8624]
# New topic request

## Description

Add a topic to the cloud side of frontend development, specifying that the Grunt `.less` transpiler needs to be run from inside the containers. As it stands now, there is no good documentation for css transpiling via Grunt in the Docker environment.

## What the new topic should cover

-  [x] The new topic should provide an explanation of how Grunt transpiling of `.less` files works.
-  [x] The new topic should provide steps for using Grunt to transpile `.less` within the container.
-  [x] The new topic contains samples that show what to expect from successful processing.

**Comment by goivvy** [comment]
@bdenham Is it still needed?

**Comment by goivvy** [comment]
@magento I am working on this

**Comment by hguthrie** [comment]
Hi @goivvy  If you are still working on this, let me know. I am making updates to the Docker documentation, not for Grunt less compiling per se, but I want to make sure your changes fit in with our planned updates.
