### ISSUE TITLE
Version numbers for ece-tools and cloud patches did not update

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8626]
# General issue

## Description:

The VERSION column isn't updated - ECE Tools is currently on 2002.1.5, for example

## Possible solutions:

Please double-check all the versions

**Comment by bdenham** [comment]
@ak77-prime, thanks for reporting this. The variables that control these version numbers are set correctly as you can see here defined here: https://github.com/magento/devdocs/blob/e8b61b8f080a18a6a7102236e8822abef51ef21e/src/_data/var.yml#L28 and used here: https://github.com/magento/devdocs/blob/master/src/cloud/release-notes/cloud-tools.md.

We might need to do a clean/full production build to get them to resolve correctly. @jeff-matthews can do that if this is the issue.

**Comment by jeff-matthews** [comment]
I'm running a full build/deploy now.

**Comment by jeff-matthews** [comment]
That seems to have fixed the issue: https://devdocs.magento.com/cloud/release-notes/cloud-tools.html

<img width="1079" alt="Screen Shot 2021-02-04 at 7 52 35 AM" src="https://user-images.githubusercontent.com/13662379/106902065-034b0680-66be-11eb-9899-a32cf7bfa186.png">
