### ISSUE TITLE
Code Generators are not generating the factories and we do not have a complete code

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#8651]
# Topic clarification/correction request

## Topic Link

Topic: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/code-generation.html

From [Hotjar ](https://insights.hotjar.com/sites/806243/feedback/responses/38638?frid=58728834)

## Description

Magento 2.3 Code Generators are not generating the factories and we do not have a complete code with all the factory files to serve as a reference. This is blocking database development.

**Comment by dobooth** [comment]
Not enough information to work with on this issue.
