### ISSUE TITLE
Better explanation about Inventory asynchronous reindex

### ISSUE THREAD

**Issue by shrielenee** [magento/devdocs#8656]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/release-notes/backward-incompatible-changes/#magento-functional-testing-framework-mftf

From [Hotjar](https://insights.hotjar.com/sites/806243/feedback/responses/38638?frid=58141137) (including contact email to notify reporter that changes were made)

## Description

regarding "Inventory asynchronous reindex" Which state prevents the collisions mentioned? This section needs better explanation with regard to what the two options do. I can try to make presumptions based on my understanding of these two words.. but they can apply to different facets of a system, and thusly, that would be unwise without better understanding.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/development/backward-incompatible-changes/highlights/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-php/issues) it.
