### ISSUE TITLE
What does "Magento Code" mean?

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8658]
# General issue

## Description:

Feedback on page: /guides/v2.4/config-guide/deployment/pipeline/build-system.html

I am confused about what the author means with "Magento Code" for example:

"_Retrieve the Magento code from source control._"

Is "Magento Code" meaning the code in the vendor folder? Or also code from custom themes or modules?

**Comment by dobooth** [comment]
Hi Edward. You have been busy lately! Thanks for the contributions. I think we can just close this one. It's pretty clear what the  Magento code is...the next line it `git clone`.

**Comment by Eddcapone** [comment]
@dobooth , Hello, no it still remains unclear. Do you mean the code in vendor/magento or also lib, setup, app/design etc?
