### ISSUE TITLE
After Install magento permission don't work

### ISSUE THREAD

**Issue by Gouravchawla** [magento/devdocs#866]
The permissions given in the below document doesn't seem to work and almost everywhere I see on the web there are permissions mentioned which are different than these.

https://github.com/magento/devdocs/blob/ce5bff93d4d5a92e0f034383aa197267bbb12648/guides/m1x/install/installer-privileges_after.html

Could someone confirm if this is just me or are these actually wrong permissions?

**Comment by xcomSteveJohnson** [comment]
We published these permissions on the advice of our information security team. It's very doubtful at this point that anyone is going to do any research on Magento 1.x.

This is also a duplicate of #553 so closing this and we'll provide any updates in the other issue.

**Comment by Gouravchawla** [comment]
Oh, I didn't realize there was already an issue created about this. And I'm using Magento 1.8 and having issue with security so was looking for resources on this. The guide was there on the official site so, I trusted this but it lead to a disaster.

Anyways, thanks for the quick response.

**Comment by xcomSteveJohnson** [comment]
I wish I had a better answer. The only thing we can advise for sure is do not use 777 permissions in production.
