### ISSUE TITLE
Missing information about the usecase of the command `bin/magento dev:source-theme:deploy`

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8664]
# General issue

## Description:

Feedback on page: [/guides/v2.4/config-guide/cli/config-cli-subcommands-less-sass.html](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-less-sass.html)

Unclear why this command exist. There is no explanation. Whats the usecase?

It just says "Use this command to create symlinks to LESS files."
but does not explain why and in which usecase it is recommended or needed to create symlinks to the LESS files.

Resource: command present in the [CLI reference](https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html#devsource-themedeploy)

**Comment by Santoshziffity** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
Basically it's create symlinks all your less/sass files to pub/static but not compile to css yet. That's all
This command rarelly use (Default you should go to grunt workflow or basic run static-content:deploy). Only one use case for this is when you create new less file with styles and you want to sync that file to your theme

**Comment by erikmarr** [comment]
@Santoshziffity Are you still working on this?

**Comment by hguthrie** [comment]
Due to no response, I am removing the assignee to allow someone else an opportunity to work on this issue.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cli/create-symlinks).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-operations.en/issues) it.
