### ISSUE TITLE
How to stop queue workers for magento commerce?

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8666]
# General issue

## Description:

Feedback on page: /guides/v2.4/config-guide/deployment/pipeline/example/shared-configuration.html

In the documentation it says "If you use Magento Commerce, stop queue workers. TBD".
but there is no explanation on how it is done and no background information why this has to be done.
There should be a link pointing to an article with more information.

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
