### ISSUE TITLE
Public userguide has github.corp.magento.com URL

### ISSUE THREAD

**Issue by sammarcus** [magento/devdocs#867]
Over at the [2.0 Release Notes for CE](http://docs.magento.com/m2/ce/user_guide/magento/release-notes-ce-2.0.html) the CHANGELOG link goes to **github.corp.magento.com** .

Can this be updated to https://github.com/magento/magento2/blob/develop/CHANGELOG.md ?

(I'm not seeing where to open a PR for the user guide itself?)

**Comment by xcomSteveJohnson** [comment]
@ccondra Can you fix this?

**Comment by ccondra** [comment]
Thanks so much for sending this along. For the user guide, the best way to report issues is to use the Feedback link at the bottom of that page.  That's one of the first things I see in the morning!  I'll fix this today, and it'll go live with the next batch of updates.

**Comment by tanberry** [comment]
Thanks @ccondra ! And thanks @sammarcus for letting us know! Closing this now.
