### ISSUE TITLE
Feedback on page: /guides/v2.4/config-guide/elasticsearch/configure-magento.html

### ISSUE THREAD

**Issue by gitpankajsharma** [magento/devdocs#8670]
# General issue
**Configure Elasticsearch within Magento**: HTML Issue in the description column.
## Description:
Elasticsearch Server Hostname: HTML `</br>` tag in the description
Elasticsearch Server Port: HTML `</br>`  tag in the description

## Possible solutions:
Add space before and after `</br>` tag or remove this tag.

**Comment by dineshvb** [comment]
@magento I am working on this
