### ISSUE TITLE
Build System Setup: Claim that magento database connection is not needed is wrong!

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8682]
# General issue

## Description:

Feedback on page: /guides/v2.4/config-guide/deployment/pipeline/build-system.html

In the [documentation ](https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/build-system.html)it says:

> The build system does not need any of the following:
> Magento database connection

So I removed the db section of my app/etc/env.php, but if I execute `php bin/magento setup:static-content:deploy -f` then I get:

**Fatal: No Database connection**

**Comment by Santoshziffity** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
Seem docs have updated here
https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/build-system.html

**Comment by erikmarr** [comment]
Agree this does look fixed, but I couldn't find an associated PR. @Santoshziffity were you able to fix this?

**Comment by hostep** [comment]
@Eddcapone: you can run the command without a database if the necessary config data exists in your `app/etc/config.php` file. Please first try to execute `bin/magento app:config:dump scopes themes` on your dev system (where you do have a database connection), and then try it again.

If this fixes your issue, maybe this hint can be added to the documentation page?
