### ISSUE TITLE
Real Company Name "OrangeCo" should not be used in documentation

### ISSUE THREAD

**Issue by BarnyShergold** [magento/devdocs#8695]
## Description
The name OrangeCo is used quite heavily in DevDocs. This is a real company name in many territories and should not be used for possible legal and respect issues.

## Possible solutions

Replace ALL instances of OrangeCo with ExampleCorp. (as this has been used elsewhere)

I am happy to undertake this fix but want to discuss and agree that it should be done first.

**Comment by keharper** [comment]
Great idea. Thanks.

**Comment by BarnyShergold** [comment]
@magento I am working on this
