### ISSUE TITLE
Feedback on page: /cloud/docker/docker-development.html

### ISSUE THREAD

**Issue by sdzhepa** [magento/devdocs#8731]
# General issue

## Description:

Based on several reports, the link for the " sign yourself up" (https://tinyurl.com/engcom-slack) in

> Magento Community Engineering Slack organization–For support, questions, or discussion, chat with us in the #cloud-docker and #cloud channels. To join, send a request to engcom@adobe.com or sign yourself up using Slack.

Is expired and leads to the _"This link is no longer active"_

## Possible solutions:

Should be updated with https://opensource.magento.com/slack

**Comment by BarnyShergold** [comment]
@sdzhepa I've just tested the tinyurl and it is working perfectly fine.
@dobooth - Should we replace this tinyurl with the real URL just in case it does expire or for the fact that for some it is not working?

**Comment by dobooth** [comment]
Likely. I don't know why we would have a tinyUrl in our docs. Perhaps @meker12 can get this in #8728.

**Comment by sdzhepa** [comment]
Hello @BarnyShergold and @dobooth 

This link https://tinyurl.com/engcom-slack could work because you already signed in to this slack.
But in the case of the first sign-up, it does not work.
To check it just try to open this link in the incognito browser mode.

Looks like _tinyurl_ link was used a long time ago but later it was changed to the new one. 
In engcom we usually refer all email request to join slack to this page  https://opensource.magento.com/slack-channels and link https://opensource.magento.com/slack

Additional information 
I also noticed that it is not only one place with _tinyurl_ the same on https://devdocs.magento.com/community/resources/resources.html#community-engineering-slack

I think the best approach is
- clone DevDoc code
- Search in IDE old link _tinyurl.com/engcom-slack_
- Replace it with the new one.

I will try to propose PR to fix it but not sure today or next week

**Comment by sdzhepa** [comment]
Update

Let me investigate this issue. Seems some configuration in slack was updated

**Comment by sdzhepa** [comment]
fyi: @BarnyShergold @dobooth @meker12 

I have investigated this issue discussed and confirmed with Community Engineering
> https://tinyurl.com/engcom-slack is broken for years
> new url: https://opensource.magento.com/slack

I create PR to fix this issue in all places https://github.com/magento/devdocs/pull/8734
