### ISSUE TITLE
Page Builder 404 (Page Not Found)

### ISSUE THREAD

**Issue by wgtgithub** [magento/devdocs#8733]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/page-builder/docs/how-to/how-to-use-pagebuilder-for-product-attributes.html

## Description

This page is not found

## Additional information

"How to use Page Builder for product attributes | Magento 2 ..." as searched google

**Comment by bdenham** [comment]
Hey @wgtgithub! You are our 404th customer! Congratulations! 

Sorry about that! Your page is now here: https://devdocs.magento.com/page-builder/docs/administration/use-for-product-attributes.html

We _just_ finished a complete a reorganization of the Page Builder docs site (last night) for easier discovery and access to topics of interest. How's that working out for you? :) 

In all seriousness, we are reindexing our devdocs site today to ensure that Page Builder searches will provide the new links to topics. Unfortunately, for any outside links to Page Builder docs, we cannot use page redirects to keep the old links working as we would do for our main devdocs site. The Page Builder docs are in a separate repo and for a variety of reasons, we cannot use page redirects to solve these problems. 

We are working towards a solution, but until then, if you encounter more 404s (Page Not Found), either use the devdocs search (after we reindex) or go to Page Builder's main page to look in the new TOC on the left: https://devdocs.magento.com/page-builder/docs/index.html

We will be communicating these changes to various channels today. So please change any bookmarks you may have and bear with us. Thanks!

**Comment by BarnyShergold** [comment]
@bdenham -  based on what you have said, are you happy for this issue to be closed as it doesn't need 'fixing'?

**Comment by bdenham** [comment]
Very true, @BarnyShergold! Closed!

**Comment by wgtgithub** [comment]
Hi there, you can close this issue cause I checked the URL already
Thanks
