### ISSUE TITLE
Broken Installation Guide link

### ISSUE THREAD

**Issue by mggioffre** [magento/devdocs#8740]
# General issue

## Description:

The link to the Magento 2 installation guide no longer works (https://community.magento.com/t5/Installing-Magento-2-x/Documentation-for-Installing-Magento-2/td-p/10957)

## Possible solutions:

Update the Installation Guide link

## Additional information:
![image](https://user-images.githubusercontent.com/4570038/109091645-2d9f4b00-76e3-11eb-829b-268a5cb648c4.png)

**Comment by dobooth** [comment]
Thanks for the issue, @mggioffre . This link from 6 years ago points to version 1 docs,  which we no longer publish.
The current Install Guide is. https://devdocs.magento.com/guides/v2.4/install-gde/install-flow-diagram.html
