### ISSUE TITLE
Getting bash: line 1: Not: command not found error for Magento Cloud

### ISSUE THREAD

**Issue by pmsteil** [magento/devdocs#8775]
# General issue

## Description:

When I try to run this command 

```
curl -sL https://github.com/magento/magento-cloud-docker/releases/download/1.2.0/init-docker.sh | bash -s -- --php 7.4 --host magento241.cloud --add-host yes
```

I get this error:

```bash: line 1: Not: command not found```

## Possible solutions:

The command would work :)

## Additional information:

I am a Magento Cloud customer.  I have cloned the git repo from the magento cloud.

When I try to access this url in my browser:
https://github.com/magento/magento-cloud-docker/releases/download/1.2.0/init-docker.sh

I get a 404

**Comment by pmsteil** [comment]
I was able to find and use this url that worked:

```https://raw.githubusercontent.com/magento/magento-cloud-docker/develop/bin/init-docker.sh```

**Comment by BarnyShergold** [comment]
This is not a DEVDOCS issue. Specifically the issue relates to accessing the magento/magento-cloud-docker repository.

If this is still an issue, please raise on the repository issues. 

Closing this issue due to this reason.
