### ISSUE TITLE
docker-compose run --rm deploy commands failing, docs issue?

### ISSUE THREAD

**Issue by pmsteil** [magento/devdocs#8777]
# General issue

## Description:

I am following instructions on this page:
https://devdocs.magento.com/cloud/docker/docker-mode-developer.html

These two commands are failing:

```
+ docker-compose run --rm deploy cloud-deploy
Creating wdmagentocloud_deploy_run ... done
Running "deploy" hook.
Could not open input file: ./vendor/bin/ece-tools
returned non-zero exit status 1

```
```
+ docker-compose run --rm deploy magento-command deploy:mode:set developer
Creating wdmagentocloud_deploy_run ... done
Could not open input file: /app/bin/magento

```
## Possible solutions:

These should work or tell me why they didn't work.

## Additional information:

I have all the docker instances getting initialized properly

```
docker-compose start
Starting elasticsearch ... done
Starting redis         ... done
Starting generic       ... done
Starting db            ... done
Starting deploy        ... done
Starting fpm           ... done
Starting build         ... done
Starting mailhog       ... done
Starting web           ... done
Starting varnish       ... done
Starting tls           ... done
```

and docker-sync is up and working properly also.

I am running on MacOS 10.15.7

**Comment by shrielenee** [comment]
Pinging @bdenham ---Hey @pmsteil Is this a docs issue? I'm finding some info in the Magento Forums and also on Stack Exchange and am curious if you have checked there for help.

* https://community.magento.com/t5/Magento-2-x-Version-Upgrades/Could-not-open-input-file-bin-magento/td-p/112857
* https://magento.stackexchange.com/questions/299941/error-while-updating-ece-tools-version-magento-2-2-6

Can y'all verify if this can be fixed by troubleshooting via other resources? And if so, do we need to make changes to the documentation to note anything important?

**Comment by pmsteil** [comment]
Well, I am trying to follow the docs to get the docker environment up and running and it isn't working for me.  So not sure what is missing, but didn't know where else to ask about this. :)

**Comment by dshevtsov** [comment]
@shiftedreality, @bdenham can you please check whether this is a documentation issue or local environment issue?

**Comment by shiftedreality** [comment]
@pmsteil I would need a few more things:

1. Have you installed dependencies from https://devdocs.magento.com/cloud/docker/docker-installation.html and have `./bin/magento` present locally?
2. Was there any issues after starting `docker-sync`? It usually may take few minutes for the initial sync which may be not really obvious from `docker-sync` output

**Comment by pmsteil** [comment]
> @pmsteil I would need a few more things:
> 
> 1. Have you installed dependencies from https://devdocs.magento.com/cloud/docker/docker-installation.html and have `./bin/magento` present locally?
Yes, I followed those instructions and successfully ran:
curl -sL https://raw.githubusercontent.com/magento/magento-cloud-docker/develop/bin/init-docker.sh | bash -s -- --php 7.4 --host magento2.docker --add-host yes

> 2. Was there any issues after starting `docker-sync`? It usually may take few minutes for the initial sync which may be not really obvious from `docker-sync` output.  No, it took a few minutes and it seemed to sync everything up.


When I do a docker-compose ps, I get this:
```
             Name                           Command                  State                           Ports                     
-------------------------------------------------------------------------------------------------------------------------------
wdmagentocloud_build_1           /docker-entrypoint.sh bash       Exit 0                                                       
wdmagentocloud_db_1              docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:55011->3306/tcp                       
wdmagentocloud_deploy_1          /docker-entrypoint.sh bash       Exit 0                                                       
wdmagentocloud_elasticsearch_1   /docker-entrypoint.sh            Up (healthy)   9200/tcp, 9300/tcp                            
wdmagentocloud_fpm_1             /docker-entrypoint.sh php- ...   Up (healthy)   9000/tcp                                      
wdmagentocloud_generic_1         /docker-entrypoint.sh bash       Exit 0                                                       
wdmagentocloud_mailhog_1         MailHog                          Up             0.0.0.0:1025->1025/tcp, 0.0.0.0:8025->8025/tcp
wdmagentocloud_redis_1           docker-entrypoint.sh redis ...   Up (healthy)   0.0.0.0:55010->6379/tcp                       
wdmagentocloud_tls_1             /docker-entrypoint.sh ngin ...   Up             0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp      
wdmagentocloud_varnish_1         docker-varnish-entrypoint  ...   Up             80/tcp                                        
wdmagentocloud_web_1             /docker-entrypoint.sh ngin ...   Up             443/tcp, 80/tcp         
```

**Comment by shiftedreality** [comment]
This all looks good, could you also check what's inside of containers?

`docker-compose run --rm build bash -c "ls -la /app"`

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.
 
If you believe that the reported problem needs further review, please open a new issue. Thank you for your continued collaboration and assistance!
