### ISSUE TITLE
Space between button on page survey section 

### ISSUE THREAD

**Issue by aryandesssigner** [magento/devdocs#8782]
# Bug report

## Description

There is no space between button on page survey section 

### Steps to reproduce

1. Open any page of devdoc
2. At the end of the page, you can find survey button

## Expected result

![image](https://user-images.githubusercontent.com/73813417/110117840-72ac3700-7ddf-11eb-9d82-47e34143a3c6.png

**Comment by shrielenee** [comment]
FIx merged, closing
