### ISSUE TITLE
Cache Compression topic is not covered

### ISSUE THREAD

**Issue by aboritskiy** [magento/devdocs#8785]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html

## Description

There is no description of cache compression settings on the page, though some of the cache compression settings show up in configuration examples.
Besides that, there is seem to be very little information out there about recommended redis settings, at least googling doesn't allow to find a reasonable advice.

## Possible solutions

Extend documentation describing those settings and their effects

```
--cache-backend-redis-compress-data=1
--cache-backend-redis-compression-lib=gzip

--page-cache-redis-compress-data=1
--page-cache-redis-compression-lib=gzip
```

In short: `--cache-backend-redis-compress-data=1` doesn't work if `--cache-backend-redis-compression-lib=gzip` is not specified, despite the fact that cli help says that it is optional and will pick compression automatically, well, it doesn't seem to be the case at least on `2.3.5`, `2.4.0` and `2.4.1`

Also activating cache compression for both default and page cache backends, reduces redis memory usage by 3-4 times.

## Additional information

I can also provide a bit of background about my benchmarks that led me to the insights above.

One more insight: some people say that page cache is already gzipped, though the place in the code that I was able to find doesn't seem to be ever called, so I'm not sure if page cache compression is a good thing or not, but it does give a win on redis memroy usage.

```
Magento\PageCache\Model\App\PageCachePlugin
```

## Actual question

Should I proceed with pull-request to the docs expanding the insights above a bit?

**Comment by dobooth** [comment]
Hi @aboritskiy Thanks for the well documented issue. We would be thrilled if you would create a PR around this.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cache/redis/redis-pg-cache).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-operations.en/issues) it.
