### ISSUE TITLE
Question about which mysql extension to use

### ISSUE THREAD

**Issue by medigeek** [magento/devdocs#8788]
# General issue

## Description:

Feedback on page: /guides/v2.4/install-gde/prereq/php-settings.html

In the [guide](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/php-settings.html#verify-installed-extensions) the command line recommends:

```
yum -y install php74u-pdo php74u-mysqlnd php74u-opcache php74u-xml php74u-gd php74u-devel php74u-mysql php74u-intl php74u-mbstring php74u-bcmath php74u-json php74u-iconv php74u-soap
```

Note **php74u-mysql** and **php74u-mysqlnd**.  Trying to install both mysql and mysqlnd will result in an error, at least in AMI Linux 2 (yum-based Amazon Linux in AWS).

## Possible solutions:

The guide should recommend only one, out of which php74u-mysqlnd would be the best option to choose from.

**Comment by mrtuvn** [comment]
may we don't need to install `php74u-mysql`

**Comment by mrtuvn** [comment]
[PHP Modules]
amqp
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
ionCube Loader
json
libxml
mbstring
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SourceGuardian
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
the ionCube PHP Loader + ionCube24

**Comment by mrtuvn** [comment]
Maybe you should use mysqli instead

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/php-settings).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-operations.en/issues) it.
