### ISSUE TITLE
Instructions to create an integration direct the user to a deprecated function

### ISSUE THREAD

**Issue by ncasebolt-sourcebooks** [magento/devdocs#8790]
# General issue

## Description:

The "[Create an integration](https://devdocs.magento.com/guides/v2.4/get-started/create-integration.html)" page directs users to install an integration using `$this->integrationManager->processIntegrationConfig`. This method appears to be deprecated in favor of `$this->integrationManager->processConfigBasedIntegrations`. This obsolete information requires the user to spend time investigating core code to discover this.

## Possible solutions:

Edit the page so as to direct the user to the correct function.

**Comment by ncasebolt-sourcebooks** [comment]
So after wrestling with this thing off and on, it appears I *must* use the deprecated function, unless there's a method in some other class. `processConfigBasedIntegrations` never did work for me. Can this section be clarified in general so we're not reliant on deprecated functions?

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/webapi/get-started/create-integration/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-webapi/issues) it.
