### ISSUE TITLE
Module Reference Guide Page Doesn't have Edit on Github Feature

### ISSUE THREAD

**Issue by charles-tychons** [magento/devdocs#8797]
# New feature request
Module Reference Guide Page Doesn't have "Edit on Github" and "Log an Issue" features.

## Description
Even though it is not a new functionality for DevDocs, But the feature is missing in a section of pages. 
All the pages having opportunity to contribute on Dev Docs using  "Edit on Github" and "Log an Issue" links. But all the pages under **Module Reference Guide** section doesn't have "Edit on Github" and "Log an Issue" links.

## Expected result
Devdocs users are allowed to contribute on **Module Reference Guide** pages also.

## Benefits
As like other pages in Devdocs, users will have the opportunity to contribute on **Module Reference Guide** pages also.

## Possible solutions
By including the "Edit on Github" and "Log an Issue" links will resolve.

**Comment by BarnyShergold** [comment]
@dobooth - The content for the "MRG" is stored in a different area from the main pages - `_data/codebase/v2_3/mrg/ee` and it's stored in `.yml` files, not `.md` - is it even possible to add the "Edit Github" / "Log an issue"? Does this come from Github itself as I can't find the texts "Edit Github" / "Log an issue" in the DevDocs repo

**Comment by dobooth** [comment]
The MRG is an example of auto-generated content. We have automation we run at each release that pulls in the content of each module's README file from the magento2 codebase. This data is store in the YML file in the devdocs codebase and our Jekyll instance processes the data and template files to create the guide. You can see the work around it being captured in https://github.com/magento/devdocs/issues/4451.

**Comment by dobooth** [comment]
Therefore, I will close this issue, but glad we had the opportunity to explain.
