### ISSUE TITLE
Information missing - How to include custom template from theme?

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8802]
# General issue

## Description:

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email.html

I have a custom template in THEME/Magento_Email/email/usp_block.html

How can I include it in another template?

I tried it with `{{template config_path="design/email/usp_block_template"}}`
and `{{template config_path="design/email/usp_block"}}` but it says `Email template '' is not defined.`

Please add the missing information. Thx.

**Comment by mrtuvn** [comment]
Maybe you don't have to do that (include external template). Include block in your email
I think the suitable way is create custom template email and call it inside admin. Modify later and add your content you want. Add content, variables.v.v
Default magento not support include external block template. Sorry if i got something wrong here. Some lacks of ignorance

**Comment by Eddcapone** [comment]
I don't have the time to try it out at the moment unfortunatelly. I will report back asap. Thx!

**Comment by jhadobe** [comment]
@Eddcapone Is this still an issue? If you still need assistance, please create a ticket in the new repo: 
https://github.com/AdobeDocs/commerce-frontend-core/pulls

This page is now located at:
https://developer.adobe.com/commerce/frontend-core/guide/templates/email/

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/frontend-core/guide/templates/email/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-frontend-core/issues) it.
