### ISSUE TITLE
Feedback on page: /guides/v2.4/frontend-dev-guide/css-topics/theme-ui-lib.html

### ISSUE THREAD

**Issue by singvar** [magento/devdocs#8814]
# General issue

## Description:

The page magento-devdocs.github.io/ is no longer available

## Possible solutions:

Re-enable the specified page.

## Additional information:

The devdoc page is no longer available.
It was possible to use the documentation built into the project, but examples from it are not displayed correctly in the browser. In general, they are not visible.

**Comment by BarnyShergold** [comment]
Pages on the domain magento-devdocs.github.io are not be maintained by this team or this repo. We only maintain on devdocs.magento.com

I'm therefore closing this issue. If you have more detailed information as to the content you are trying to reference, please reopen issue.
