### ISSUE TITLE
Need more example in REST tutorial

### ISSUE THREAD

**Issue by demwarlord** [magento/devdocs#8818]
# General issue

## Description:

Related page: https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-shipment.html

There is a mention about bundles and simples, but no information about configurables. I think It means the same principle for configurable, but it would be great if you confirm this. I mean that one has to "ship" only top-level (parent) order_item_id also for configurable product items.
Also it is not clear about partial shipment. What if I ship top-level configurable only half of qty. What I have to do next time to fullfill the order completely: make shipment on the same configurable order_item_id with the rest of qty?
Thank you in advance!

**Comment by dobooth** [comment]
Thanks for filing, @demwarlord

**Comment by dobooth** [comment]
@keharper Any feedback on this issue?

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/webapi/rest/tutorials/orders/order-create-shipment/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-webapi/issues) it.
