### ISSUE TITLE
Uncached query call to customAttributeMedadata

### ISSUE THREAD

**Issue by damienwebdev** [magento/devdocs#8819]
# General issue

## Description:
https://devdocs.magento.com/guides/v2.4/graphql/queries/products.html#ProductFilterInput is strictly wrong and direct one to make an uncached query call to `customAttributeMetadata`.

## Possible solutions:
You should instead prefer https://develop.pwa-venia.com/graphql?query=query+GetFilterInputsForCategory%7B__type%28name%3A%22ProductAttributeFilterInput%22%29%7BinputFields%7Bname+type%7Bname+__typename%7D__typename%7D__typename%7D%7D&operationName=GetFilterInputsForCategory&variables=%7B%7D

like PWA Studio does.

**Comment by dshevtsov** [comment]
@keharper, are you still working on this?

**Comment by damienwebdev** [comment]
@dshevtsov @keharper this doc is also wrong. The original call should be cached and the other shouldn't be allowed. PWA studio is doing something incorrect to accommodate the poor performance of `customAttributeMetadata`

**Comment by damienwebdev** [comment]
cc: @cpartica
