### ISSUE TITLE
Feedback on page: /guides/v2.4/ui_comp_guide/components/ui-insertform.html

### ISSUE THREAD

**Issue by hunterallen** [magento/devdocs#8824]
# General issue

## Description:

Under "**Configuration Options**", the option "**autoRender**" is described as
> When set to true, the Form component is automatically rendered during InsertForm initialization. Otherwise, insertListing’s render method should be called to render the Form.

*InsertListing** should be corrected to  **InsertForm**. 

## Possible solutions:

**InsertListing** should be corrected to  **InsertForm**.

**Comment by Viper9x** [comment]
@magento I am working on this
