### ISSUE TITLE
BundleOrderItem interface causes Warning: implode(): Invalid arguments passed (v2.4/graphql/interfaces/order-item-interface.html)

### ISSUE THREAD

**Issue by chrisfyrtarn** [magento/devdocs#8839]
# General issue
BundleOrderItem interface causes `Warning: implode(): Invalid arguments passed`

## Description:

GraphQL Query "Customer/Orders/Items" containing this example: 
```
...on BundleOrderItem {
    bundle_options {
        id
    }
}
```

Causes Invalid arguments error to be returned:

```
{
      "debugMessage": "Warning: implode(): Invalid arguments passed in /var/www/html/magento/vendor/magento/module-bundle-graph-ql/Model/Resolver/Order/Item/BundleOptions.php on line 151",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 42,
          "column": 13
        }
      ],
      "path": [
        "customer",
        "orders",
        "items",
        0,
        "items",
        0,
        "bundle_options"
      ]
    }
```

## Possible solutions:

GraphQL response contains the intended summary of bundle items with no errors.

## Additional information:
```
Magento 2.4.2
```

**Comment by BarnyShergold** [comment]
@chrisfyrtarn I've checked this and I can't see why this is a DevDocs issue. It looks more like you are reporting a bug with the behaviour of the GraphQL.

Please open an issue on magento/magento2 and report this there.

I am closing the issue for now. If you consider that there is a DOCS issue, please re-open and let us know what is wrong with the DOCS
