### ISSUE TITLE
 Dynamic Rows Component Documentation

### ISSUE THREAD

**Issue by zyukov** [magento/devdocs#884]
https://devdocs.magento.com/guides/v2.1/ui-components/ui_dynamic_rows.html page not fount.

**Comment by xcomSteveJohnson** [comment]
This is intentional. We've recently replaced the UI components documentation that used to be located at the `/ui-components` URI with this: http://devdocs.magento.com/guides/v2.1/ui_comp_guide/bk-ui_comps.html

The two sets of content might not be equivalent. You can still find your topic in the `/v2.0` directory though.

Let us know if you  have any questions or concerns.

**Comment by zyukov** [comment]
Thank you for your responce. I try to find information about dynamic rows component, so I tried to find it in /2.0 directory. Still can't find it there.

**Comment by xcomSteveJohnson** [comment]
I looked at the history and apparently this file never existed in `v2.0` and I removed all the 2.1 HTML files for the `ui-components` path.

Assign to @almarchenko to comment further because she authored this topic. Maybe the name of the topic is different in 2.1?

**Comment by zyukov** [comment]
Hello @almarchenko ! 
Can you help me please, I am looking for information about dynamic rows component. It was some info https://devdocs.magento.com/guides/v2.1/ui-components/ui_dynamic_rows.html, but now there is no page. So xcomSteveJohnson told me, that you authored this topic in v2.0 and may be can help with it

**Comment by almarchenko** [comment]
Hi @zyukov!
I'm terribly sorry I didn;t address this earlier.
It's very strange, but I cannot find nor the 2.0 nor the 2.1 version of the doc, though it definitely existed at some moment.
I'm now investigating the situation.
Meanwhile, if your questions about the component are still actual, you can post them here and I'll try to get answers from our devs asap.

**Comment by rasimov** [comment]
Hi @almarchenko!
I agree with @zyukov, lack of the documentation causes some difficulties in development.
Could you please provide any information about these attributes: 
* `dataScope` (in Magento, this attribute usually has `data.links` value, but I can't see `data` in `getData` output, usually `links` is defined at the top level of array returned by `getData`, I mean 
```
{<product_id>: {"product":<product object>, "links":["name_of_dynamicRows_component":[<array of products>]]}}} 
```
Here is an example how it is implemented https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Related.php#L210

* `links`, which usually is
```
'links' => [
     'insertData' => '${ $.provider }:${ $.dataProvider }'
],
```
so what ${ $.dataProvider } means here, sub source for general form source ${ $.provider } ? if yes, how can I define it?

I don't want to use `dynamicRows` in scope of product, I want to use it and `insertListing` component for completely different custom entity.

**Comment by josefbehr** [comment]
Here it is, I found it: https://github.com/magento/devdocs/commit/814e6c9b5babbe6866d4e5b1283824403bf69425

**Comment by almarchenko** [comment]
@zyukov @josefbehr 
It is still not very clear to me, why we removed it in the new 2.1 UI comps guide, but I've created an internal ticket MAGETWO-69108 to verify the info and add it.  Thank you for raising this issue!
Meanwhile, we added a bunch of new topics, and there's one for Dynamic Rows, describing its config settings:
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-dynamicrows.html
