### ISSUE TITLE
Please explain new 'media-content:sync' and 'media-gallery:sync' commands from Magento 2.4.1

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#8845]
# New topic request

## Description

Magento 2.4.1 introduced these two new commands:
- `bin/magento media-content:sync`
- `bin/magento media-gallery:sync`

These are currently only mentioned on https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html but their explanation is very generic and basically doesn't say anything:
> - Synchronize content with assets
> - Synchronize media storage and media assets in the database

But that doesn't explain what these command are for specifically and when and for what reasons you should use them.

## Content checklist

See above

**Comment by jeff-matthews** [comment]
@gabrieldagama & @tkacheva, is this something you can help us with? I didn't see these commands in the feature list for internal release tracking for 2.4.1.

**Comment by gabrieldagama** [comment]
Hi @jeff-matthews, I believe @sivaschenko would be the best person to answer that!

**Comment by dobooth** [comment]
@sivaschenko Any updates around this?

**Comment by sivaschenko** [comment]
@dobooth not updates as of now, unfortunately. Do you have a suggestion of the place where this information can be added?

**Comment by hostep** [comment]
@sivaschenko: maybe you can already explain a little bit what these commands are used for, so we can find the correct page in devdocs where it can be added? Currently we don't understand what these commands do or what they are related to.

Maybe https://docs.magento.com/user-guide/system/media-storage.html or https://docs.magento.com/user-guide/cms/media-gallery.html? This is just guessing as I have no idea what these commands are about.

**Comment by sivaschenko** [comment]
https://docs.magento.com/user-guide/cms/media-gallery.html is a merchdocs page, but I cannot find a proper place in the devdocs

**Comment by keharper** [comment]
@hostep @sivaschenko we would likely need to create a new topic under [Command line configuration](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli.html). @BarnyShergold I see you participated in the code review for [PR-29753](https://github.com/magento/magento2/pull/29753). Any ideas?

**Comment by dobooth** [comment]
Hi @sivaschenko We think this would be best added to the codebase, in the command implementation code. This way, it will be pull into our auto-generated reference guide. If you could add it there, that would be very helpful. https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html

**Comment by dobooth** [comment]
Closing this issue. Once the codebase change is made, the CLI reference will autogenerate the docs. @hostep if you could open an issue on this in the codebase and link this issue, that would be great.

**Comment by hostep** [comment]
@dobooth: I'm not sure if this can be explained in a single line, I think the explanation might be more complex then just adding a single line description in the command summary which is usually pretty short:

<img width="1341" alt="Screenshot 2021-09-30 at 21 15 59" src="https://user-images.githubusercontent.com/85479/135517013-a6d78062-330b-499f-b379-e3296b8c647e.png">

And opening an issue on the magento2 repo often leads to it being ignored for years. At least here on devdocs, things tend to move much quicker.


@sivaschenko: even if we have not found a place to put the description in devdocs, could you still try to explain the purpose of these 2 commands here in github? So that people who search more info can just find it through a search engine even if it doesn't get included in devdocs eventually?

Thanks!
