### ISSUE TITLE
Remove "Deleted" Section from the document which will not allow to perform that activity

### ISSUE THREAD

**Issue by emilmathew** [magento/devdocs#8856]
# Topic clarification/correction request

 https://omsdocs.magento.com/specifications/#magento.inventory.aggregate_management
![image](https://user-images.githubusercontent.com/45308572/113663186-395d3480-96c7-11eb-976c-7eaa82064cf6.png)

## Description
As per the engineering team - "It can not be done by MOM API or other ways at this moment. It is a technical restriction from the MOM side and "We don't advise to delete aggregate once the client is launched, even in Staging
The aggregate is linked to sources, stock and even sales channel and exists in config API. If this aggregate has been already used, it will be too complicated to delete it and could lead to letting the system in an inconsistent state. Also, Having sources and aggregates not used, is not impacting the system at all."

So I guess better to delete this section as the new customers are trying to perform this activity and it always misleading them.
![image](https://user-images.githubusercontent.com/45308572/113663074-ff8c2e00-96c6-11eb-8715-6c92dc681bba.png)

 Should be deleted as merchant/customer can not perform this task.

## Possible solutions

 Remove the "Deleted" section from the document, I personally think is not necessary.

**Comment by danidelcar** [comment]
This is already in the OMS ENG backlog, will open PR in OMS when necessary. Closing as per not correct repo, thanks @emilmathew
