### ISSUE TITLE
Update DNS configuration topic

### ISSUE THREAD

**Issue by SalyersAdobe** [magento/devdocs#8871]
Suggestion for: https://devdocs.magento.com/cloud/cdn/configure-fastly.html#update-dns-configuration-with-development-settings

Users often visit this article while completing their Launch Checklist to go live on production
Recommendation:
Under the  "2. Add ACME challenge CNAME records for domain validation and pre-provisioning of Production SSL/TLS certificates,"
can we provide a disclaimer that the records listed are only examples/placeholders and that user should contact their CTA or Magento Support to confirm the correct ACME challenge records for their account?

Issue:
I've seen a few times now users assume that they need to use the records listed in the article - it prevents proper domain provisioning and often results in extra or unnecessary troubleshooting time. If we put a disclaimer I think it would help get customers to the right place.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-cloud-service/user-guide/cdn/setup-fastly/fastly-configuration).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-cloud-service.en/issues) it.
