### ISSUE TITLE
Customize PHP.INI section is incorrect and does not work

### ISSUE THREAD

**Issue by jcam** [magento/devdocs#8877]
# Bug report

## Description

The devdocs section about customizing php.ini (https://devdocs.magento.com/cloud/project/magento-app-php-ini.html) has a validation check of looking at /etc/php5/fpm/php.ini to ensure that the customizations were applied.

This does not exist, as current builds are using php 7.3.
In addition, the customizations do not get added to the php7.3 php.ini.
Is there a new set of instructions that need to be added here?

### Steps to reproduce

1. First Step
1. Second Step
1. Etc.

## Expected result

Following the instructions on the Customize PHP.INI page will result in customized php.ini settings.

**Comment by BarnyShergold** [comment]
I've also found that on an Integration environment for PHP7.4 there is no /etc/php5/fpm folder and php.ini is in a odd place.
@dobooth - Can we have a Cloud Architect confirm where the php.ini files are for PRO/Starter - Prod/Stage/Integration - PHP7.2/7.3/7.4

We could create a table to show this

**Comment by dobooth** [comment]
@BarnyShergold seems a reasonable request.
