### ISSUE TITLE
Remote storage: nginx config resolver 

### ISSUE THREAD

**Issue by robolmos** [magento/devdocs#8881]
# Remote storage AWS S3 nginx config resolver directive feedback

feedback on page: /guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html
Topic: https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html#configure-nginx

## Description:

Having "resolver 8.8.8.8" in the nginx config seems odd as a default instead of using the host's default resolver.

## Possible solutions:

Remove the "resolver 8.8.8.8" directive from the config example.

## Additional information:

I imagine typically AWS S3 usage would from within AWS or another provider's "S3 API" compatible internal service. Thus in most cases it's odd to ask Google's Public DNS name server what an S3 endpoint should be, which would return a public/internet-routable IP (and incur additional latency and cost in some cases) instead of an internal IP.

**Comment by shiftedreality** [comment]
Hello @robolmos 

The resolver is needed to serve data from public DNS in this directive:

`proxy_pass https://s3.amazonaws.com/$bucket$uri;`

Here is some more info: https://distinctplace.com/2017/04/19/nginx-resolver-explained/

**Comment by dobooth** [comment]
Seems like this is as-designed. Closing issue. Please reopen if this is not the case.
