### ISSUE TITLE
Set docroot - remove mention of setup wizard in 2.37

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#8897]
# General issue

## Description:

The Web Setup Wizard was removed from the code in 2.4.0 and is being removed in 2.3.7. The [Set the docrooot](https://devdocs.magento.com/cloud/before/before-setup-env-install.html#set-the-docroot) section refers to the wizard:

> Set the docroot to the /magento directory until you complete all setup. If you change the docroot to /magento/pub prior to completion, you will encounter issues running the Web Setup Wizard.

## Possible solutions:

Remove the second sentence.

**Comment by EvheniiaKolkhiieva** [comment]
Hi @bdenham, thank you for assigning!

This suggestion was implemented, could you please check and approve PR? https://github.com/magento/devdocs/pull/8905
