### ISSUE TITLE
Update software.md

### ISSUE THREAD

**Issue by vsvizev** [magento/devdocs#8902]
## Purpose of this pull request

Fix MySQL 'innodb_thread_concurrency' variable spelling error.

## Affected DevDocs pages

-  https://devdocs.magento.com/guides/v2.3/performance-best-practices/software.html

## Links to Magento source code

-  https://github.com/magento/devdocs/blob/master/src/guides/v2.3/performance-best-practices/software.md

**Comment by dobooth** [comment]
Close as dupe.
