### ISSUE TITLE
Example missing on how to enter a version - Feedback on page: /extensions/b2b/

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8908]
# General issue

## Description:

https://devdocs.magento.com/extensions/b2b/

I try to install the B2B module, it just says that I have to execute this command and enter my version:

    composer require magento/extension-b2b:<version>

I looked at[ this table](https://devdocs.magento.com/release/availability.html#compatibility) to figure out the version I need.
Then I tried:

    composer require magento/extension-b2b:2.4.2
    
 But I get 

**[InvalidArgumentException]
  Could not find package magento/extension-b2b in a version matching 2.4.2**
  
So this documentation obviously needs a guide, since it misses some important information about the version.

## Possible solutions:

Add guide

**Comment by AntonEvers** [comment]
Hi @Eddcapone, B2B 1.3.1 is the B2B version that is compatible with Magento 2.4.2.
![Screen Shot 2021-04-30 at 13 36 29](https://user-images.githubusercontent.com/1489129/116690115-34835c00-a9b9-11eb-8ed7-554044dc66e7.png)

**Comment by Eddcapone** [comment]
I see, thank you. I thought we have to enter the magento version. The documentation should show an example on what to select for magento 2.4.2

**Comment by AntonEvers** [comment]
Hi @Eddcapone, the risk with that, is that multiple versions can be compatible, and the definition can differ per installation.
For instance, currently you can install B2B `1.1.0` up to `1.3.0` with Magento `2.3.0` to `2.4.1`. You might define this as:
```
composer require "magento/extension-b2b:1.3.0"
composer require "magento/extension-b2b:>=1.1.0 <1.3.0"
composer require "magento/extension-b2b:~1.0"
composer require "magento/extension-b2b:>=1.3"
composer require "magento/extension-b2b:1.3.*
```
And more.

Currently only B2B version 1.3.1 is compatible with Magento 2.4.2. However, B2B 1.3.2 or 1.4.0 might also be compatible with 2.4.2 in the future. Depending on whether you want composer to automatically install the next B2B major, minor or patch version when it comes out, you can require B2B differently.

If the docs would give an example of installing B2B with Magento 2.4 in a specific way, that would not be right for everyone and it would be outdated as soon as a new B2B version comes out.
