### ISSUE TITLE
Updated open source "System requirements" table has some inaccuracies and can be improved

### ISSUE THREAD

**Issue by robolmos** [magento/devdocs#8912]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

## Description

System requirements are a bit confusing now. The page says: _"This table notes software versions that were officially tested and supported at the time of the Magento version’s release."_

M2.4.2 release notes says: _"Redis 6.x is now supported. Magento 2.4.x remains compatible with Redis 5.x."_

But the system requirements table only shows Redis 6.x. Is M2.4.2 tested against Redis 5.x or only 6.x?

This isn't the only issue, there's a version confusion with Varnish (why does it change from 6.x to 6.5.1 then back), and Elasticsearch versions too.

## Possible solutions

I think if Redis 5.x is compat/supported for M2.4.2, it should be noted. If it's not being tested, it should be listed, but with a superscript to say that.

I'm not sure what to do about Varnish. 6.0.x LTS should be the minimum for all of them I think.

## Additional information

It'd be nice to know what versions of all requirements are actively being tested in Magento's environment, that way they can be  My guess is Cloud's services versions would be the closest for what's actively tested, but I'm not sure.

**Comment by dobooth** [comment]
@jeff-matthews Any thoughts here?

**Comment by jeff-matthews** [comment]
Confirmed. Varnish 6.5.1 should be 6.x.

**Comment by robolmos** [comment]
> Compatible is not the same as supported. By design, the table only lists _tested and supported_ versions; not compatible versions. I think adding compatible versions in addition to supported might make the table harder to read. I think the point here is that you should use supported and tested versions for optimal results.
> Cc: @chernenm

Alrighty, based on that there's still some improvements for the table. 

From the M2.4.2 release notes it says:

1. "Elasticsearch 7.9.x is now supported" -- so the table should be using 7.9 instead of 7.x ?

2. "Magento 2.4.2 has been tested with Varnish 6.4" -- so the table should be using 6.4 instead of 6.x ?

The minor versions for other software that's being tested would be nice to know too. Eg, Redis 6.0.0 or newer like 6.0.7?

Thanks

**Comment by jeff-matthews** [comment]
Confirmed with Product Management. We should add the minor versions that we tested with for each release.

**Comment by jeff-matthews** [comment]
@robolmos, I just merged a PR that adds minor versions for most major system requirements. It will be published within the hour.

I was unable to locate versions for some of the earlier 2.3.x releases, but I got as close as I could with the limited resources that are available. I'm going to close this issue, but please feel free to open a new one if you have more info to share.
