### ISSUE TITLE
Feedback on page: /guides/v2.4/install-gde/install/cli/install-cli-subcommands-deployment.html

### ISSUE THREAD

**Issue by crosslightde** [magento/devdocs#8928]
# General issue

## Description:

`bin/magento setup:config:set` updates env.php, which in turn causes a fatal error, because file contents doesn't match database content. In developer mode, this is handled by automatically importing the file into the database. But in production mode, this causes a critical error and thus a full shutdown of the shop.

## Possible solutions:

Add a hint to the documentation, that in production mode the shop will not automatically import the settings, and that `bin/magento app:config:import` needs to be run additionally.

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
