### ISSUE TITLE
Update ulimit terminology

### ISSUE THREAD

**Issue by KrisShannon** [magento/devdocs#8941]
# General issue

Affected topic: /guides/v2.4/comp-mgr/prereq/prereq_compman-ulimit.html

## Description:

The page talks about `ulimit` as though it is only the open files limit.  There are many legitimate reasons for needing the other user limits increased and presenting this file open limit as **_the_** `ulimit` will create confusion when developers reading this documentation are interacting with hosting providers.

## Possible solutions:

Most places in the page which mention "`ulimit`" could be replaced with  "open files `ulimit`"

## Additional information:

I work at a hosting provider and it took a bit of back and forth with our customer before they pointed to this page and I could understand what they were after.

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
