### ISSUE TITLE
Add or Update validation rules into the checkout address form fields.

### ISSUE THREAD

**Issue by rajesh-mage** [magento/devdocs#8942]
# New topic request

## Description

The Customize Checkout section has lots of topics to discuss the customization of checkout functionality. PFA.

![checkout](https://user-images.githubusercontent.com/82952634/118499627-bf4bb100-b744-11eb-8c14-ca61ad63d29d.png) 

But there is no information about change or update checkout address field validation rule. 

This topic refers to add or update the validation rules into the checkout address form fields.

## Possible solutions

Add instruction to override validation field rules.

**Comment by dobooth** [comment]
Hi @rajesh-mage. What does PFA stand for? We are curious.

**Comment by rajesh-mage** [comment]
> Hi @rajesh-mage. What does PFA stand for? We are curious.

PFA stands for - Please Find the Attachment

**Comment by rajesh-mage** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
See #9009 for the abandoned PR.

**Comment by dshevtsov** [comment]
The Checkout topics were [migrated](https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-php/issues) it.
