### ISSUE TITLE
Create UiGrid component At Front End 

### ISSUE THREAD

**Issue by rajesh-mage** [magento/devdocs#8945]
# New topic request

## Description

We have the option to create a UiGrid component at the Frontend. Could we add a new topic to create the UiGrid component at Front End? 

For Example:
The following topic discusses the UiGrid component create at Back End(Admin Side).
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/admin-grid.html

**Comment by rajesh-mage** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@rajesh-mage - We've not heard anything on this issue from you for about 3 months, can you let us know how you are getting on?

**Comment by hguthrie** [comment]
Removing @rajesh-mage as assignee so that someone else can work on it if they like.
If you decide to create a PR, just refer to this issue. Thanks!

**Comment by nitish-ranjan05** [comment]
@magento I am working on this

**Comment by dshevtsov** [comment]
The documentation was [migrated](https://developer.adobe.com/commerce/php/development/components/add-admin-grid/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-php/issues) it.
