### ISSUE TITLE
Add details about urlResolver redirectCode

### ISSUE THREAD

**Issue by damienwebdev** [magento/devdocs#8946]
# General issue

Affected page: /guides/v2.4/graphql/queries/url-resolver.html

## Description:

There is no information on what the `type` field returns when the `redirectCode` is non-zero.

## Possible solutions:

Document it.

## Additional information:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/UrlRewriteGraphQl/Model/Resolver/AbstractEntityUrl.php#L131

**Comment by damienwebdev** [comment]
cc: @cpartica

**Comment by keharper** [comment]
@damienwebdev The description on that page states

Contains 0 when there is no redirect error. A value of 301 indicates the URL of the requested resource has been changed permanently, while a value of 302 indicates a temporary redirect

Are you looking for additional information?

This query will be deprecated in 2.4.3, in favor of the `routes` query. The text for the equivalent field, `redirect_code`, has the same description. I'll update it if you can recommend enhancements.

**Comment by keharper** [comment]
Ack. I misread the request. The description for both versions of `type` is One of PRODUCT, CATEGORY, or CMS_PAGE. I'll update both places when I get more details.

**Comment by damienwebdev** [comment]
@keharper sorry, my docs request was vague.

The issue at hand is what is the value of `type` when the `redirectCode` is non-zero.

Is the `type` the `type` of the **original** url or is it the type of the url you're being redirected to?

In the `zero` case, and in the route-not-found case, this is obvious, but no so much in a redirect case.

**Comment by BarnyShergold** [comment]
@keharper @damienwebdev  - As we are now on 2.4.3 and the page in question says this query is deprecated, I am closing this issue. It can be re-opened if required.

**Comment by damienwebdev** [comment]
Read the new doc. LGTM. Confirm solved.

**Comment by BarnyShergold** [comment]
> Read the new doc. LGTM. Confirm solved.

LGTM?

Thanks for the confirm
