### ISSUE TITLE
Is anonymous API info out of date?

### ISSUE THREAD

**Issue by Techbrunch** [magento/devdocs#8947]
# General issue
Affected page:  /guides/v2.4/rest/anonymous-api-security.html

## Description:

> Magento 2 allows some web APIs to be accessed by unauthenticated (anonymous) users. Many of these APIs allow a customer to have a robust shopping experience on the website without having to log in.

> For this reason, by default, Magento 2 now prevents anonymous users from accessing the APIs that could reveal sensitive information. When the feature is enabled, the user must have administrator privileges to execute the affected APIs.

Does this also affect the GraphQL API ?

## Possible solutions:

If this setting does not affect the GraphQL API then I think it should be specified on this page.

A new setting should probably added to protect similar endpoint in the GraphQL API.

If the setting also affect the GraphQL API which would make sense, please update the documentation.

**Comment by dobooth** [comment]
@keharper

**Comment by keharper** [comment]
I'll take a look

**Comment by BarnyShergold** [comment]
@keharper - How's it going on this issue?

**Comment by keharper** [comment]
@Techbrunch the setting does not apply to GraphQL. The product manager is aware of this request and will look into it further. Closing the issue because the docs are correct.
