### ISSUE TITLE
Right navigation display problems on System Requirements page

### ISSUE THREAD

**Issue by webkul-ajaysaini** [magento/devdocs#8948]
# General issue
Layout issue: https://prnt.sc/133v685

**Comment by ccondra** [comment]
@bdenham @jeff-matthews   -- What do you think is the best way to address this?

**Comment by jeff-matthews** [comment]
Yeah, that happens for any page that contains a large table. It only seems to happen at specific screen widths (between 1201 and 1470 pixels). I'm sure there's a CSS fix for it, but it's a very low priority. The update would need to be made in the theme: https://github.com/magento-devdocs/devdocs-theme.

**Comment by dobooth** [comment]
Going to close this. As Jeff said, only happens for a narrow range of widths.
