### ISSUE TITLE
List of all validation rules and examples for custom form

### ISSUE THREAD

**Issue by rajesh-mage** [magento/devdocs#8951]
# New topic request

## Description

Add all the list of validation rules and examples for the Form Validation section. 

The Form validation section already has some topics about Custom Validation Rules and Form Validation. PFA.

![validation-rules](https://user-images.githubusercontent.com/82952634/118817853-4f1e6600-b8d1-11eb-902a-9d5612cc583a.png)

In this issue, I requested to add a new topic to discuss about all the list of custom form validation rules and examples.

**Comment by rajesh-mage** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@rajesh-mage  - We've not heard anything on this issue from you for about 3 months, can you let us know how you are getting on?

**Comment by hguthrie** [comment]
Removing @rajesh-mage as assignee so that someone else can work on it if they like.
If you decide to create a PR, just refer to this issue. Thanks!

**Comment by goivvy** [comment]
@magento I am working on this

**Comment by goivvy** [comment]
@hguthrie Done, please review - https://github.com/magento/devdocs/pull/9356
