### ISSUE TITLE
How to integrate React component in a Magento page

### ISSUE THREAD

**Issue by nidheesh-thooleri** [magento/devdocs#8960]
# New topic request

## Description
Step to Configure React component in a Magento page.

In some situations, it will be a good feature to integrate the react component in some part of the Magento pages, for example, the Live Order status tracking progress bar in the Order details page.

So by using a base module with webpack configuration we can integrate a component in 
Magento. This Base module contains the react resource details, react-related imports, etc.

So I request to add a new topic to detail that how to integrate the react component on the Magento page.

**Comment by jcalcaben** [comment]
Hi @nidheesh-thooleri have you looked into PWA Studio? http://pwastudio.io/

It lets you build a React-based storefront on top of a Magento backend.

**Comment by nidheesh-thooleri** [comment]
> Hi @nidheesh-thooleri have you looked into PWA Studio? http://pwastudio.io/
> 
> It lets you build a React-based storefront on top of a Magento backend.

> @jcalcaben yea, got it...

**Comment by nidheesh-thooleri** [comment]
@jcalcaben So it won't be a valuable one I guess too, It is better to close the ticket correct?

**Comment by dobooth** [comment]
Closing.
