### ISSUE TITLE
Reorder Checkout Fields

### ISSUE THREAD

**Issue by shunmugakumaran** [magento/devdocs#8966]
# New topic request

## Description

In Customize Checkout documentation we have a list of available customizations PFA

![Reorder Checkout](https://user-images.githubusercontent.com/84446887/119642498-69f45b80-be38-11eb-83c7-34fc1844c8b7.png)

In this issue, I requested to add a new topic to discuss the reorder checkout input fields with examples,
**Sometimes depending on the country, the order of the address fields is important. So they need to be on a specific order.**

**Comment by shunmugakumaran** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@shunmugakumaran  - We've not heard anything on this issue from you for about 3 months, can you let us know how you are getting on?

**Comment by dshevtsov** [comment]
The Customize Checkout documentation was [migrated](https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/).
If the issue is still relevant, please feel free to [reopen](https://github.com/AdobeDocs/commerce-php/issues) it.
