### ISSUE TITLE
Create the bundle product using REST API

### ISSUE THREAD

**Issue by shunmugakumaran** [magento/devdocs#8968]
# New topic request

## Description

In the rest tutorials documentation, there is no example to create a bundle product using the rest API

![Create bundle pr](https://user-images.githubusercontent.com/84446887/119644096-213da200-be3a-11eb-8f17-9f9c211f0600.png)

So I requested to add a new topic to discuss the bundle product creation using rest API with examples.

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by shunmugakumaran** [comment]
@magento i am working on this

**Comment by keharper** [comment]
@shunmugakumaran Did you open this issue with the expectation of creating the PR to fix the issue. @EvheniiaKolkhiieva claimed the issue a few hours after you opened it.

**Comment by shunmugakumaran** [comment]
@keharper Yes to fix this issue I have opened & I am looking for the status to change from grooming but it has been assigned to @EvheniiaKolkhiieva and then the label has been charged to dev in progress

**Comment by EvheniiaKolkhiieva** [comment]
Hi @shunmugakumaran , the "dev in progress" is a correct label in case someone is working on fixing the problem. Please clarify if you want to create a topic on your own about creating the bundle product using REST API?
 If yes - I will unassigned myself, that you finish this; If not, I will soon create a new topic required in the scope of this task
Thank you! 😊

**Comment by shunmugakumaran** [comment]
Yes, I am already working on it..! @EvheniiaKolkhiieva :)

**Comment by EvheniiaKolkhiieva** [comment]
Got it, thank you @shunmugakumaran :)

**Comment by BarnyShergold** [comment]
@shunmugakumaran  - We've not heard anything on this issue from you for about 3 months, can you let us know how you are getting on?

**Comment by hguthrie** [comment]
Is this related to #8988 ? I don't think the smart reference worked in the PR, so making the connection here.

**Comment by keharper** [comment]
Unassigned due to inactivity

**Comment by goivvy** [comment]
@BarnyShergold @keharper Is someone working on it? I see a PR but it's closed due to inactivity? Do you want me to take over?
