### ISSUE TITLE
Add full paths to routes files

### ISSUE THREAD

**Issue by threed-factory-store** [magento/devdocs#8976]
# General issue

The "Example of routing usage" section needs to include the path and filename for all of the example files.

Affected page: /guides/v2.4/extension-dev-guide/routing.html

## Description:

As a new Magento developer, I already find it almost impossible to debug routing issues.  This is one of the few examples that shows mixed case Module and Vendor names, but it doesn't show the corresponding paths and filenames.

## Possible solutions:

Declaring a new route in [Module]/[Vendor]/etc/adminhtml/routes.xml:
< content of routes.xml file>

## Additional information:

Please provide Magento developers with tools to debug issues related to routing.  I can't test my code if I can't even get to it.

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
