### ISSUE TITLE
Tutorial for updating the product image by SKU using rest API

### ISSUE THREAD

**Issue by shunmugakumaran** [magento/devdocs#8986]
# New topic request

## Description

In the rest tutorials documentation, there is no example to update a product image using the rest API by SKU

We can add a new tutorial under the rest tutorials with example

**Comment by shunmugakumaran** [comment]
@magento I am working on this

**Comment by goivvy** [comment]
@bdenham @shunmugakumaran Do you need help with it? It's been almost a year

**Comment by goivvy** [comment]
@magento I am working on this

**Comment by jeff-matthews** [comment]
Hi @goivvy!

The REST tutorials have moved to https://developer.adobe.com/commerce/webapi/rest/tutorials/. 

This is the source repo: https://github.com/AdobeDocs/commerce-webapi.

We'd still appreciate your contribution, but please work on it in the new repo.

**Comment by goivvy** [comment]
@jeff-matthews  OK, working on it.

**Comment by goivvy** [comment]
@jeff-matthews You wouldn't mind if in addition to how to update an image, I also add pages on how to create an images, get a list of all images and delete an image.

**Comment by keharper** [comment]
@goivvy  Yeah, that'd be great. (I'm speaking on behalf of Jeff.)
