### ISSUE TITLE
There is no information on how to disable or override a mixin

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#8989]
# General issue

## Description:

Feedback on page: /guides/v2.4/javascript-dev-guide/javascript/js_mixins.html

I need to disable a third party mixin and replace it with my own. But there are no informations on how to disable a mixin and it seems to be impossible to replace it with another one.

Please add more informations to the documentation about this mather.

## Additional information:

https://magento.stackexchange.com/questions/338137/magento-2-override-mixin-with-another-mixin/339319?noredirect=1#comment480694_339319

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
