### ISSUE TITLE
Additional resources for Fastly timeout modification

### ISSUE THREAD

**Issue by shaneherman** [magento/devdocs#9005]
# General issue
There are additional details that can be helpful for customers to modify Fastly Timeout parameters for customers receiving 503's beyond just modifying Admin timeout.

https://devdocs.magento.com/cloud/cdn/trouble-fastly.html#errors

Please consider linking pointing them to the below 

https://github.com/fastly/fastly-magento2/blob/master/Documentation/Guides/Edge-Modules/EDGE-MODULE-INCREASE-TIMEOUTS-LONG-JOBS.md

## Description:

This document only describes how to extend timeout for Admin and not other URL / Endpoints
https://devdocs.magento.com/cloud/cdn/configure-fastly-customize-cache.html#extend-fastly-timeout

## Possible solutions:

Extend documentation on the section
https://devdocs.magento.com/cloud/cdn/configure-fastly-customize-cache.html#extend-fastly-timeout

to include instructions on how to modify timeouts for other URL/s besides just Admin
 
https://github.com/fastly/fastly-magento2/blob/master/Documentation/Guides/Edge-Modules/EDGE-MODULE-INCREASE-TIMEOUTS-LONG-JOBS.md

**Comment by jhadobe** [comment]
@magento import code to magento-devdocs/devdocs
