### ISSUE TITLE
Wrong .lib-font-face parameters in _typography.less

### ISSUE THREAD

**Issue by surajraikwar** [magento/devdocs#9006]
When I put 
.lib-font-face(
    @family-name: 'ClearSans',
    @font-path: "@{baseDir}fonts/ClearSans",
    @font-format: 'ttf',
    @font-type: 'truetype'
);

I get errors that font-format and font-type is not valid

## Possible solutions:
Remove @font-type and @font-format from doc

**Comment by dobooth** [comment]
@surajraikwar Is this referenced in a devdocs topic? Where are you seeing this?

**Comment by mrtuvn** [comment]
Can you add more screenshot or steps to reproduce
![Screenshot from 2021-06-18 17-28-41](https://user-images.githubusercontent.com/1908873/122547713-a8a5bc00-d05a-11eb-853c-933ab5ba6725.png)

**Comment by mrtuvn** [comment]
![Screenshot from 2021-06-18 17-36-03](https://user-images.githubusercontent.com/1908873/122548533-ae4fd180-d05b-11eb-9d14-20d76aa1fef1.png)

**Comment by dobooth** [comment]
Closing for lack of details.
