### ISSUE TITLE
Link to lifestyle doesn't work on the Events and Observers page

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#901]
Hi

The link to `lifestyle` on the [Events and Observers page]( http://devdocs.magento.com/guides/v2.1/extension-dev-guide/events-and-observers.html#subscribing-to-events) doesn't seem to work.

The term `lifestyle` was changed to `lifecycle` in this PR: https://github.com/magento/devdocs/pull/167

But on the [Extension lifecycle page](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/prepare/lifecycle.html), I find no reference to the term `shared` which is used on the [Events and Observers page]( http://devdocs.magento.com/guides/v2.1/extension-dev-guide/events-and-observers.html#subscribing-to-events), while it used to exist if you look at PR https://github.com/magento/devdocs/pull/167

So I'm all confused now 😕

**Comment by jcalcaben** [comment]
Hi @hostep 

The content you are looking for is now in the [di.xml file](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/di-xml-file.html#object-lifestyle-configuration) documentation.

I will fix the link. Sorry for the confusion!

**Comment by hostep** [comment]
Thanks @jcalcaben!

Btw: the internal link on that di.xml page to the `Object Lifestyle Management` section is also broken ;)
It points to `#object-lifestyle-management` instead of the correct `#object-lifestyle-configuration`

**Comment by jcalcaben** [comment]
Thanks for pointing that out! Both links are fixed now.

I'll look into the search results issue.
