### ISSUE TITLE
crud eav attribute sets using rest api services

### ISSUE THREAD

**Issue by shunmugakumaran** [magento/devdocs#9011]
# New topic request

## Description

- To read the attribute sets list.
- To read the single attribute sets list by :attributeSetId
- To create the attribute sets.
- To update the single attribute sets list by :attributeSetId
- To delete the single attribute sets list by :attributeSetId

![manage-attribute-sets](https://user-images.githubusercontent.com/84446887/122763208-b443ed80-d2bb-11eb-8e18-9ac7f739b3e1.png)

**Comment by keharper** [comment]
@shunmugakumaran Which REST endpoints do you want described in detail?

**Comment by shunmugakumaran** [comment]
> @shunmugakumaran Which REST endpoints do you want described in detail?

pls find the rest endpoints below here

**GET    /V1/eav/attribute-sets/list
GET    /V1/eav/attribute-sets/:attributeSetId
DELETE /V1/eav/attribute-sets/:attributeSetId
POST   /V1/eav/attribute-sets
PUT    /V1/eav/attribute-sets/:attributeSetId**

**Comment by shunmugakumaran** [comment]
@keharper above endpoints we can describe in details..!

**Comment by shunmugakumaran** [comment]
@magento I am working on this

**Comment by dshevtsov** [comment]
The documentation was [migrated](https://developer.adobe.com/commerce/webapi/rest/tutorials/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-webapi/issues>.
