### ISSUE TITLE
How to add adminhtml theme to grunt config?

### ISSUE THREAD

**Issue by Eddcapone** [magento/devdocs#9013]
# General issue

## Description:

Feedback on page: /guides/v2.4/frontend-dev-guide/themes/admin_theme_create.html

There is no information on how to add our custom adminhtml theme to the grunt configuration file **dev\tools\grunt\configs\local-themes.js**

**Comment by erikmarr** [comment]
@Eddcapone did you see this topic?
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/css_debug.html#add_theme

**Comment by Eddcapone** [comment]
@erikmarr, Yes, and I don't get it to work. This is my config so far:

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

'use strict';

/**
 * Define Themes
 *
 * area: area, one of (frontend|adminhtml|doc),
 * name: theme name in format Vendor/theme-name,
 * locale: locale,
 * files: [
 * 'css/styles-m',
 * 'css/styles-l'
 * ],
 * dsl: dynamic stylesheet language (less|sass)
 *
 */
module.exports = {
    company_backend: {
        area: 'adminhtml',
        name: 'company/fresh',
        locale: 'de_DE',
        files: [
            ??? Unclear what do I need to enter here for adminhtml, not described in the documentation ???
        ],
        dsl: 'less'
    }
};

**Comment by dobooth** [comment]
@BarnyShergold Any thoughts around this?

**Comment by danidelcar** [comment]
Hi @BarnyShergold did you get to clarify @Eddcapone doubts about this issue?, thanks!

**Comment by hguthrie** [comment]
Hi @Eddcapone It looks like you want to know where to find custom theme CSS files? When you create or add a custom theme, it should have the  `<magento-root>/app/design/adminhtml/<vendor-name>/<admin-theme>/<module>/web/*` directory structure. So are you saying it does not or you can't find it?

The following topic illustrates the typical theme structure: https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-structure.html

And when I look at `adminhtml` themes, looks like the path is not quite the same as the one you mentioned that you searched:
https://github.com/magento/magento2/tree/2.4/app/design/adminhtml/Magento/backend/Magento_Analytics/web

Can you verify?

**Comment by hguthrie** [comment]
Closing this issue for lack of clarification. If this is still a concern, you can create a new issue and provide us with more information. Thanks!
