### ISSUE TITLE
Clarify guidelines on maximum websites and stores customers can configure on cloud

### ISSUE THREAD

**Issue by shaneherman** [magento/devdocs#9014]
# General issue

## Description:

https://devdocs.magento.com/cloud/project/project-multi-sites.html

Customers are abusing the Cloud limits for Configurable Websites which cause us to incur cost and can impact overall performance.

Example - Support Ticket:

https://magento.zendesk.com/agent/tickets/401192
This customer has 86 Domains in staging and 184 in Prod.
 
Our Internal Performance Documentation recommends a maximum of 50 stores.
https://fieldreadiness-adobe.highspot.com/items/5fca71bc81171778d2bbe0eb?lfrm=srp.0

## Possible solutions:
Consider working with Adobe / Magento Product Management to post a section on this page that gives general guidelines of Maximum Websites and Stores to be configured based on GMV Tier or just set a known limit of 50. I would recommend talking with Jeff Lathan about this topic.

**Comment by hguthrie** [comment]
Interesting. Thanks for pointing this out! I am making some inquiries.

**Comment by BarnyShergold** [comment]
But there websites where the client is legit using more than 50+ stores. I know a client with 1 domain but over 56 storeviews.

I was informed elsewhere that you are allowed 15 as 'default' then are supposed to pay a small licence increase for "packs of 10" but this is done on the honour system in that there is no actual way to check except by "audit"?

Perhaps a clearer guide on fair use and what to do if a site genuinely needs to exceed limits?

**Comment by hguthrie** [comment]
I am marking this waiting for response because I have some questions to internal person and waiting to get the info and set aside some time to fix this.
