### ISSUE TITLE
Would be good to visualize Magento versions release dates and EOL

### ISSUE THREAD

**Issue by sivaschenko** [magento/devdocs#9027]
# New feature request

## Description

Would be great to add some visualization of Magento versions release dates and EOL to https://devdocs.magento.com/release/released-versions.html page similar to https://www.php.net/supported-versions.php

![image](https://user-images.githubusercontent.com/2028541/123847177-2ea0ed00-d90e-11eb-8bf1-473a952c741d.png)

## Expected result

A diagram similar to the diagram in https://www.php.net/supported-versions.php is added to https://devdocs.magento.com/release/released-versions.html page to visualize Magento versions release dates and EOL

![image](https://user-images.githubusercontent.com/2028541/123847210-3c567280-d90e-11eb-9cd1-9cd2be1aa4e1.png)

## Benefits

Easier and more user-friendly perception of data.

**Comment by dobooth** [comment]
@dshevtsov What do you think about this? I know you mentioned a lack of end-of-support dates...

**Comment by dshevtsov** [comment]
> @dshevtsov What do you think about this? I know you mentioned a lack of end-of-support dates...

@dobooth, thank you for letting me know. Yes, lack of certainty regarding end-of-support dates makes visualization design challenging.

@bdenham, @jcalcaben, @belbiy, do we have support for such visualization on the website?

**Comment by belbiy** [comment]
No, we would have to either:

1.  Use some kind of data visualization widget like https://developers.google.com/chart/interactive/docs/gallery/timeline 
2. Or generate SVG on the build time, i believe it's what php.net is doing. 

I dont have enough SVG knowledge and cant help with 2, but i think it would be relatively easy to pick some kind of data visualization library that we can use to generate such chart.

**Comment by dobooth** [comment]
Looks like we can't really pull this off without EOL dates. Closing until we have another solution.

**Comment by sivaschenko** [comment]
@dobooth we do have end-of-support dates for Major releases in the json https://github.com/magento/devdocs/blob/master/src/_data/core-releases.json
