### ISSUE TITLE
System requirements page suggest to install everything

### ISSUE THREAD

**Issue by xxorax** [magento/devdocs#9029]
# Bug report

## Description

The requirement page should list the minimal requirements to run Magento 2, instead of, the first paragraph (under *System requirements* show the versions compatibilities table of all the software Magento **could** use.

### Steps to reproduce

https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

## Expected result

Got the list of the **minimal requirements**, and so not all the software Magento **could** use.

## Possible solutions

- Add "optionnal" column to the table (yes/no).
- Move the table down in the page, in a "Version compatibilities" paragraph

**Comment by dobooth** [comment]
We have gone over this table many times and we can only really recommend versions that were specifically tested for the release. We are reluctant to make changes to this format.

**Comment by xxorax** [comment]
I don't mean this table need to be changed, but surely it needs to be moved somewhere else than at the top of the *System requirements* paragraph (where this table is not, it's a software compatibility table) and whereas the [Miscaleous](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#miscellaneous) paragraph actually try to define the minimum system requirement...

And the sentence just before the table does not help:

> This table notes software versions that were officially tested and supported at the time of the Magento version’s release. Newer versions of **required software** may work but have not been tested.

So it's even not ambiguous: you need to install both Apache and Nginx.

I invite you to make a survey on your side to convince yourself.

**Comment by xxorax** [comment]
By the way, this requirement page also mention releases that does not exists... :foggy:
