### ISSUE TITLE
Feedback on page: /guides/v2.4/frontend-dev-guide/layouts/layout-create.html

### ISSUE THREAD

**Issue by rustavellyne** [magento/devdocs#9037]
# Can i declare block inside page layout xml?
Documentation said that page layouts can include only containers but in example we see that block also can be icnluded or it just a mistake?
## Description:

[quote from documentation](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-types.html)

> A page layout file defines the page wireframe, for example, one-column layout. Technically page layout is an .xml file defining the structure inside the <body> section of the HTML page markup. Page layouts feature only containers. All page layouts used for page rendering should be declared in the page layout declaration file.

but in [example](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-create.html) you set block inside of page layout, is this mistake?

<img width="1045" alt="Screenshot 2021-07-03 at 21 33 12" src="https://user-images.githubusercontent.com/33631491/124363823-58c41900-dc46-11eb-9c38-ca1058c1d62b.png">

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
