### ISSUE TITLE
Magento 2.1.x technology stack requirements page

### ISSUE THREAD

**Issue by gamerboy** [magento/devdocs#904]
Hi,

from the [Magento 2.0.x technology stack requirements page](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements-2.0-tech.html) if i try to change the Magento version to 2.1 using the top-right select i get a **Page Not Found error**.
If i change manually the url to http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html everything works fine.
Same error from version 2.1 to 2.0.

Wrong links in the select dropdown list.

```
<ul class="dropdown-menu dropdown-menu-left">
    <li><a class="dropdown-item" href="/guides/v2.0/install-gde/system-requirements-2-1.tech.html">Version 2.0</a></li>
    <li><a class="dropdown-item" href="/guides/v2.1/install-gde/system-requirements-2-1.tech.html">Version 2.1</a></li>
</ul>
```

Best regards,
Andrea.

**Comment by xcomSteveJohnson** [comment]
Sorry about that, fixed now. I tried to get too fancy with the URLs. Please try it and close this if it works for you.

**Comment by gamerboy** [comment]
It's working now. Thanks!
