### ISSUE TITLE
GitHub action to build PR as a site and serve temporarily for reviewing

### ISSUE THREAD

**Issue by drpayyne** [magento/devdocs#9041]
# New feature request

## Description

We should probably have a GitHub action to build PR sites triggered manually by a reviewer comment like `@magento build site` and a jekyll build should be run async and subsequently comment the public URL which would be valid for an or so.

## Expected result

- Comment a key phrase (manual triggering of build if and when required)
- Check if comment was by reviewer of the PR (is this possible? if yes, we can limit anyone triggering the build)
- Build site using GitHub actions
- Serve PR on a temporary public URL (maybe 30 minutes or so?)

## Benefits

Allows reviewer to visualize the page apart from the usual code review and pulling PR locally, building site, testing it. This helps reviewers test PRs even on mobile on-the-fly.

## Possible solutions

A GitHub action just like the one in the core Magento repo

**Comment by dshevtsov** [comment]
That would be a nice feature, but our team doesn't have sufficient resources for this kind of automation unfortunately.
