### ISSUE TITLE
No more "Add Block Names to Hints". User docs should be updated

### ISSUE THREAD

**Issue by engcom-November** [magento/devdocs#9047]
# Topic clarification/correction request
Remove "Add Block Names to Hints" and add "Add Block Class Type to hints" where ever required in the docs. 
## Topic Link
https://docs.magento.com/user-guide/configuration/advanced/developer.html
https://docs.magento.com/user-guide/system/template-path-hints.html

## Description
Admin -> Stores -> Configuration -> Advanced -> Developer -> Debug section -> "Add Block Names to Hints" option was removed from here long back but the docs are outdated and have to be updated accordingly.

## Possible solutions

Remove "Add Block Names to Hints" and add "Add Block Class Type to hints" where ever required in the docs. 

## Additional information
Please find the below GitHub commit to check further details about the changes made related to this feature.
https://github.com/magento/magento2/commit/7238228429b1
![image](https://user-images.githubusercontent.com/60198231/125300878-11294580-e348-11eb-8c18-29409fcdee1c.png)

**Comment by hguthrie** [comment]
@engcom-November  This issue belongs in the Commerce User Guide ( https://github.com/magento/merchdocs ) repo. You can click "Log an Issue" at the top of the topic to log an issue in that repo.

**Comment by engcom-November** [comment]
@hguthrie Thanks for the clarification. Created below issue under [merchdocs](https://github.com/magento/merchdocs) repo.
https://github.com/magento/merchdocs/issues/1381

**Comment by hguthrie** [comment]
Great! thanks @engcom-November  I'll close this issue.
