### ISSUE TITLE
Feedback on page: /guides/v2.4/javascript-dev-guide/widgets/widget_alert.html

### ISSUE THREAD

**Issue by arnopp** [magento/devdocs#9049]
# General issue

## Description:

The requirejs dependency list in "Example2: standalone initialization" is missing a comma after 'Magento_Ui/js/modal/alert'

## Possible solutions:

Add a comma after 'Magento_Ui/js/modal/alert' in "Example2: standalone initialization"

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
