### ISSUE TITLE
Documentation page down

### ISSUE THREAD

**Issue by harshu108** [magento/devdocs#905]
The page at this link:http://devdocs.magento.com/guides/v2.0/extension-dev-guide/extension_attributes/adding-attributes.html

This page keeps redirecting to itself repeatedly

![image](https://cloud.githubusercontent.com/assets/14261945/20473033/f6ff4ab6-afe3-11e6-85dc-a177ad5c7a1c.png)

**Comment by jcalcaben** [comment]
Thanks for pointing this out! I will be looking into it.
