### ISSUE TITLE
Modify cart query example

### ISSUE THREAD

**Issue by denchev** [magento/devdocs#9052]
# General issue
None existing field is passed to cart query

## Description:

In the example cart query is requested a field called "pickup_location_code" that doesn't exist. When I run the query agains Magento 2.4.2 version I get the following error:

`{
  "errors": [
    {
      "message": "Cannot query field \"pickup_location_code\" on type \"ShippingCartAddress\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 34,
          "column": 7
        }
      ]
    }
  ]
}`

Looking at the code of the documentation it looks like it was added with this commit https://github.com/magento/devdocs/issues/7375

## Possible solutions:

This field is only available if you have enabled Multi stock inventory. I think this field should be moved away from the example and left in the available input/output attributes.

**Comment by keharper** [comment]
I agree with this. `pickup_location_code` can be removed from the example.
