### ISSUE TITLE
Feedback on page: /guides/v2.4/rest/asynchronous-web-endpoints.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9053]
# General issue

## Description:

The link here is not valid:

The [REST API documentation](https://devdocs.magento.com/redoc/2.4/) provides a list of all current synchronous Magento API routes.

## Possible solutions:

https://magento.redoc.ly/

**Comment by ZhovnirMaria** [comment]
@magento I am working on this
