### ISSUE TITLE
More details needed in the Add a New Field topic

### ISSUE THREAD

**Issue by mts527** [magento/devdocs#9058]
# Topic clarification/correction request

## Topic Link

https://github.com/magento/devdocs/blob/master/src/guides/v2.4/howdoi/checkout/checkout_new_field.md

## Description

It should provide all the steps to save the field value. For example in the `customer_address_entity`, `order_address` and `quote_address` tables. And possibly how to retrieve them later in the customer account section when editing existing address(es).

## Possible solutions

Provide information about how to save a custom new field value to specific tables. Or link to corresponding guide which would continue this topic accordingly to create a complete implementation guide.

**Comment by nitish-ranjan05** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@nitish-ranjan05 - We've not heard anything on this issue from you for a about a month, can you let us know how you are getting on?

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/add-address-field/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-php/issues>.
