### ISSUE TITLE
Create a new layout example doesn't work as expected

### ISSUE THREAD

**Issue by silviaball** [magento/devdocs#9059]
# General issue

Affected page:
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-create.html

## Description:

I replicated the code exactly as you wrote. The layout in the drop-down appears in the backend. But no footer tag with "page-footer-bottom" class is displayed in the frontend

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this
