### ISSUE TITLE
Fix Cloud Pro integration branch description

### ISSUE THREAD

**Issue by novikor** [magento/devdocs#9062]
# General issue

## Description:

A number of PaaS containers for Cloud Pro is confusing.

https://devdocs.magento.com/cloud/architecture/pro-architecture.html:

> Integration—Provides a single environment branch, and you can create one additional, environment branch. 
This allows for up to **two active** branches deployed to Platform-as-a-Service (PaaS) containers.

https://devdocs.magento.com/cloud/architecture/pro-develop-deploy-workflow.html#develop:

> You can create up to four additional branches for developing your custom code, extensions, and third party integrations. This allows for a maximum of **five active** branches deployed to Platform-as-a-Service (PaaS) containers.

https://magento-u.magento.com/magento-u/Free-Intro-to-Magento-Commerce-Cloud/web-free-intro-to-magento-commerce-cloud-raw-fv6qFSHv/content/index.html#/lessons/zLyv-85EA5n19YQK3bcVMxFmeulnUf7h:

![image](https://user-images.githubusercontent.com/26086561/127065764-243ebe6d-f63b-409b-9fe4-a318125ddc1e.png)

## Possible solutions:

Update https://devdocs.magento.com/cloud/architecture/pro-architecture.html with **5** branches instead of **2**.

Thank you for taking the time to report this issue!
GitHub Issues should only be created for problems/topics related to this project's codebase.

Before submitting this issue, please make sure you are complying with our Code of Conduct:
https://github.com/magento/devdocs/blob/master/.github/CODE_OF_CONDUCT.md

Issues that do not comply with our Code of Conduct or do not contain enough information may be closed at the maintainers' discretion.

Feel free to remove this section before creating this issue.
-->

**Comment by BarnyShergold** [comment]
@novikor - Actually the correct number is 2. A while back it was reduce from 5 to 2 to give the 2 active branches 4x the resources the environments had when you could have 5.

So it's actually the "pro-develop-deploy-workflow.html" page that needs updating as well as the Magento U.

@dobooth - we can correct the devdocs, but how do we correct https://magento-u.magento.com/magento-u/Free-Intro-to-Magento-Commerce-Cloud/web-free-intro-to-magento-commerce-cloud-raw-fv6qFSHv/content/index.html#/lessons/zLyv-85EA5n19YQK3bcVMxFmeulnUf7h ?

**Comment by meker12** [comment]
That's correct. I have a PR to submit the fix today.

**Comment by hguthrie** [comment]
> @dobooth - we can correct the devdocs, but how do we correct https://magento-u.magento.com/magento-u/Free-Intro-to-Magento-Commerce-Cloud/web-free-intro-to-magento-commerce-cloud-raw-fv6qFSHv/content/index.html#/lessons/zLyv-85EA5n19YQK3bcVMxFmeulnUf7h ?

Magento U owns that content. We will have to do a little reconnoitering to find their process.

**Comment by meker12** [comment]
Update completed and published - [commit](https://github.com/magento/devdocs/commit/d06726585d42e9f47b9a11584ec26a0d77c3187b) and updated in [Cloud Guide](https://devdocs.magento.com/cloud/architecture/pro-develop-deploy-workflow.html).
