### ISSUE TITLE
Broken link in Cloud docker web container section

### ISSUE THREAD

**Issue by amarroni** [magento/devdocs#9064]
# General issue

Feedback on https://devdocs.magento.com/cloud/docker/docker-containers-service.html#web-container

configurations files like doesn't exist anymore. 

## Description:
Reviewing the information how to customize NGINX configuration files. under the step 2 you should copy some files to a custom folder.
Template files link doesn't exist. Show a 404 page not found under github.

## Possible solutions:
change the link to the correct github page.

## Additional information:
Here is a screenshot of the problem.

![image](https://user-images.githubusercontent.com/5198527/127207473-44a48eaf-627f-4614-b992-9a4fed808bb8.png)

**Comment by hguthrie** [comment]
Thanks for letting us know. Looks like there is a typo in the URL. Should point to:
https://github.com/magento/magento-cloud-docker/tree/develop/images/nginx/1.19/etc

**Comment by amarroni** [comment]
Hi @hguthrie cool! anytime!
I can create a commit if you want.

Best,
Alejandro.

**Comment by hguthrie** [comment]
Yeah! That would be great @amarroni

**Comment by amarroni** [comment]
@hguthrie I created the PR #9065
