### ISSUE TITLE
Display is not a valid attribute on a XML block element

### ISSUE THREAD

**Issue by LeanderFS** [magento/devdocs#9072]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_block

## Description

The documentation on this page states that the attribute `display` can be used to control the visibility of a block element. Upon trying to use this attribute an exception is thrown.

`Element 'block', attribute 'display': The attribute 'display' is not allowed.`

## Possible solutions

Looking at the xsd validation for `block`, it seems that `display` is not a valid attribute at this moment. Thus I'd suggest removing the reference to the attribute on the documentation until the attribute is either implemented in the code, or implemented in the xsd validation.

**Comment by hguthrie** [comment]
Thanks for pointing this out. We will research.

**Comment by hguthrie** [comment]
Display was added in #6477
In that ticket, they reference the location in the code. Can you verify this does not work? Perhaps this is not a Docs issue?

**Comment by LeanderFS** [comment]
I will double check this and get back to you @hguthrie

**Comment by shrielenee** [comment]
@LeanderFS  Any news on this? Thanks!

**Comment by hguthrie** [comment]
No news could be good news. I am closing this for lack of response. If you continue to have concerns, you can open a new issue with further details and reference this closed issue. Thanks for taking the time to help improve the documentation!
