### ISSUE TITLE
Unsupported Version While Running the devdocs at local via docker setup

### ISSUE THREAD

**Issue by yogicse** [magento/devdocs#9076]
# Unsupported Version 3.7 While Running the devdocs at local via docker setup

## Description

After Followed the detail step from https://github.com/magento/devdocs/wiki/Build-DevDocs-with-Docker 
getting Error 

### Steps to reproduce

1. Setup the Docker 
1. Clone the Devdoc Repository at local machine
1. Navigate to devdocs and run command docker-compose up
1. Found Error as below
```
root@mss-d-4:/var/www/html/Magento2021/devdocs# git branch
* master
root@mss-d-4:/var/www/html/Magento2021/devdocs# docker -v
Docker version 20.10.7, build f0df350
root@mss-d-4:/var/www/html/Magento2021/devdocs# docker-compose up
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
root@mss-d-4:/var/www/html/Magento2021/devdocs# 
```

## Expected result

Run the docker container and up the website on below urls

jekyll_1  |       Generating... 
jekyll_1  |                     done in 157.026 seconds.
jekyll_1  |  Auto-regeneration: enabled for 'src'
jekyll_1  | LiveReload address: http://0.0.0.0:35729
jekyll_1  |     Server address: http://0.0.0.0:4000/
jekyll_1  |   Server running... press ctrl-c to stop.

## Possible solutions

Change the version as per suggested one.

## Additional information

Environment
1. Ubuntu 18.04.5 LTS 64 bit
2. Docker version 20.10.7, build f0df350

**Comment by yogicse** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@yogicse this was assigned to you a month ago but nothing has been actioned. Are you still going to update this or can we close this issue?

**Comment by BarnyShergold** [comment]
due to the response given on the 5th Aug and that no reponse has been given by the issue creator, this issue is being closed. It can be re-opened if required.
