### ISSUE TITLE
looking for a downloadable open api schema

### ISSUE THREAD

**Issue by padisah** [magento/devdocs#9080]
# General issue
do not found a free downloadable schema, but face authentication requirement for a specific installation
## Description:
I would generate Java classes from Magento Rest API's responses, but I need a json format openapi schema for that.

Magento documentation doesn't provide it as a general, free resource. I got an url, for a specific installation:
doc: https://devdocs.magento.com/guides/v2.4/rest/generate-local.html
http://<magento_host>/rest/<store_code>/schema
...and not sure what format it would respond, if I had a working authentication

## Possible solutions:
make it accessible on magento documentation as a simple, downloadable json file (which only depends on Magento version)

## Additional information:

I am not developing Magento, but a 3rd party app, that would integrate to Magento, and connect it through the REST API. I don't even have a Magento installation anywhere.

**Comment by keharper** [comment]
@padisah Contact me via the Community Engineering Slack space. My ID is `keharper`

See [this page](https://devdocs.magento.com/community/resources.html) for more info about joining Slack.

**Comment by keharper** [comment]
Closing due to lack of response. Feel free to reopen
