### ISSUE TITLE
Feedback on page: /guides/v2.4/release-notes/2-4-2-p2.html

### ISSUE THREAD

**Issue by krisdass** [magento/devdocs#9083]
# General issue
Link to Quick Start and Install Patch is not pointed correctly.
## Description:
In Installation and upgrade instructions, Quickstart and Install guide is pointed to wrong/broken url

Quickstart and install is pointed to  http://127.0.0.1:4000/guides/v2.4/install-gde/composer.html.
## Possible solutions:
Point to the correct url so that we can see the patch install options

## Additional information:
![Magento2-Patch-link-issue](https://user-images.githubusercontent.com/2673673/128970241-19ae0b95-9d83-4e4a-ab51-64ba48079c47.png)

**Comment by BarnyShergold** [comment]
@magento I am working on this
