### ISSUE TITLE
Incorrect description in release notes

### ISSUE THREAD

**Issue by Chandresh22** [magento/devdocs#9087]
Page affected: /guides/v2.4/release-notes/open-source-2-4-3.html

# General issue
In Reviews Github link wrong
## Description:

in section Reviews : https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html#reviews
4th line **Administrators can now sort product reviews on the Product Reviews section of the product edit page as expected**
has Github link  [GitHub-26301](https://github.com/magento/magento2/issues/26301)  which is not related to the reviews sorting.

## Possible solutions:

in Reviews sections 4th line instead of  [GitHub-26301](https://github.com/magento/magento2/issues/26301) may be this was the right [Github-30270](https://github.com/magento/magento2/issues/30270)

**Comment by keharper** [comment]
@jfrontain Can you take a look at this?

**Comment by Chandresh22** [comment]
hello @jfrontain i will check. it updated thank you

**Comment by BarnyShergold** [comment]
@keharper & @jfrontain - This has been fixed already

**Comment by dobooth** [comment]
Fixed.
