### ISSUE TITLE
EE APIs have no documentation

### ISSUE THREAD

**Issue by skukla** [magento/devdocs#909]
I am seeing more and more potential merchants ask about Magento's API coverage.  Given that the majority of EE merchants are integrating with third-party systems, and there are notable feature differences, it would be great to have these documented.

**Note:** It would also be good to document B2B-specific APIs as well when those are released.

**Comment by keharper** [comment]
I'll see if I can push out a list of EE APIs today.

**Comment by keharper** [comment]
I appended the EE REST APIs to the current list. 

http://devdocs.magento.com/guides/v2.1/rest/list.html
http://devdocs.magento.com/guides/v2.0/rest/list.html
