### ISSUE TITLE
Magento release dates for 2022 are missing

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#9090]
# Bug report

## Description

Take a look at the [upcoming releases](https://devdocs.magento.com/release/index.html) document.
Magento 2.4.3 got released yesterday, but now we don't have an idea of when Magento 2.4.4 will get released.

It would be nice if the new release dates that are already know for 2022 could get added to that page.

### Steps to reproduce

See above

## Expected result

Finding release dates for upcoming Magento versions in 2022

**Comment by jeff-matthews** [comment]
Hi @hostep!

I actually have a branch with some 2022 dates that may help expedite this request. I just need internal approval to merge and publish. I'll go ask for an update and get back to you.

Cc: @chernenm

**Comment by jeff-matthews** [comment]
The schedule is still under internal review, but more info will be provided soon. Stay tuned.

**Comment by hostep** [comment]
Okay, thanks Jeff 🙂

**Comment by hostep** [comment]
@BarnyShergold: The initial question wasn't answered, so it would be best if the issue only got closed when the new dates get published, so I (and the people watching this thread) get notified by it.

**Comment by jeff-matthews** [comment]
We plan to publish an update in mid-September.

**Comment by jeff-matthews** [comment]
@hostep. We just published updates.

**Comment by hostep** [comment]
Alright, awesome, thanks!

So, Magento is switching from 4 releases to 2 releases per year for non-security releases. Interesting...

I'm also wondering what those unannounced releases will be? Magento 2.5? Magento LTS? ...
