### ISSUE TITLE
Clarify pricing fields for orders and order items

### ISSUE THREAD

**Issue by braders** [magento/devdocs#9092]
# New topic request

## Description

In the sales_order and sales_order_item, quote and quote_item tables there are a large number of fields related to pricing. These are exposed over the API and may also be read or set by Magento modules. In some cases it's not clear exactly what values these fields should contain, especially when factoring in the large range of VAT and currency options which Magento supports. 

## Content checklist

I'd like to see documentation added which describes for each column:

- What value it contains/ how it is calculated
- If it contains VAT or not (and whether this depends on the VAT setup)
- Whether the price stored is for a single line item, or for the total of the row (for the sales_order_item, quote_item tables).

In addition, the documentation should explain the difference between the base and standard columns (e.g. price vs base_price).

This could be well presented as a series of tables.

**Comment by shrielenee** [comment]
@braders Do you mean this for the REST API docs? Can you point us to the area or guide this content would make sense? Thanks!

**Comment by BarnyShergold** [comment]
@braders please comeback with some feedback on this issue as it's been nearly 2 weeks since we requested further information. Otherwise issue will be closed.

**Comment by dobooth** [comment]
Closing. Please reopen if you have more information to share on this.
