### ISSUE TITLE
Images in CONTRIBUTING.md are broken

### ISSUE THREAD

**Issue by braders** [magento/devdocs#9093]
# Bug report

Navigate to https://github.com/magento/devdocs/blob/master/.github/CONTRIBUTING.md. Observe that 3 image files are returning 404 errors, and are therefore not displayed. 

 - https://devdocs.magento.com/common/images/contribute-prerequisites.png
 - https://devdocs.magento.com/common/images/contribute-write-submit-pr.png
 - https://devdocs.magento.com/common/images/contribute-feedback-link.png

## Expected result

The highlighted images should be updated to point to the correct URLs. Ideally these images should live within the repo, to reduce the chance of future breakage.

**Comment by BarnyShergold** [comment]
@dobooth - these were removed in this commit about 1 month ago : https://github.com/magento/devdocs/commit/c7ab350c8f0166b2fcdeab14ad19736ef85abb7f

Can you restore these? If you have no time I can reach back into the commits, find the files and re-add
