### ISSUE TITLE
Update Cloud Meta-Package Constraints

### ISSUE THREAD

**Issue by BarnyShergold** [magento/devdocs#9094]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/cloud/project/ece-tools-upgrade-project.html#metapackage
https://devdocs.magento.com/cloud/project/project-upgrade.html

## Description

The constraint numbers for the metapackage don't need to be set as : >=current_version <next_version

eg `"magento/magento-cloud-metapackage":">=2.3.4 <2.3.5"`

This is because the Cloud metapackage require does this -
```
           "require": {
                "fastly/magento2": "^1.2.34",
                "magento/ece-tools": "^2002.1.0",
                "magento/module-paypal-on-boarding": "~100.4.0",
                "magento/product-enterprise-edition": ">=2.4.2 <2.4.3"
            },

```

## Possible solutions
Change all instances of `"magento/magento-cloud-metapackage":">=2.x.y <2.x.z"` to `"magento/magento-cloud-metapackage":"2.x.y"`

Reword https://devdocs.magento.com/cloud/project/ece-tools-upgrade-project.html#metapackage to reflect.

**Comment by hguthrie** [comment]
The "Upgrade to ece-tools" topic and "metapackage" section is a one-time only set of steps. It is for older projects that are not yet using the ece-tools package.

**Comment by BarnyShergold** [comment]
True but people are seeing it and getting confused between "Upgrade ECE-TOOLS" and "Upgrade Magento".

ALso the main page (https://devdocs.magento.com/cloud/project/project-upgrade.html) and this is a) wrong in my view and b) refers to the ""Upgrade to ece-tools" topic and "metapackage" section"

So I do think a bit of clean up & clarification is needed. 😄

**Comment by hguthrie** [comment]
Ece-tools never requires an upgrade, only an update, which is in this topic:
https://devdocs.magento.com/cloud/project/ece-tools-update.html

The link from the project upgrade topic clearly states "that does not contain the ece-tools package, then you must upgrade" otherwise you only have to "update".

I'm sorry this seems confusing to some. I will research whether this method of upgrading the project is required anymore, and then will clean up accordingly. Thanks!

**Comment by YPyltiai** [comment]
@BarnyShergold it should be a range because the idea behind it is that customers can easily pick up security patches once those come out without fixing constraints. You can put a harder dependencies too but ECE-Tools not always had `^` either in constraint, it was less flexible in earlier versions.

**Comment by BarnyShergold** [comment]
@YPyltiai - What I am saying that because of the way metapackage has it's "Require" section defined you DON'T need a range.
If you put - "magento/magento-cloud-metapackage":"2.4.3" then when it first comes out you will get 2.4.3 - However when p1 is released, if you run "composer update" then it will be upgrade AUTOMATICALLY to 2.4.3-p1 - no changes necessary.

You ONLY need the main version number, all security patches will be installed as and when you run update.
