### ISSUE TITLE
Missing information on page: /guides/v2.4/install-gde/system-requirements.html & /guides/v2.4/install-gde/prereq/php-settings.html

### ISSUE THREAD

**Issue by shane-clickingmad** [magento/devdocs#9099]
# General issue

## Description:

ext-sodium was added as a requirement as of release 2.3.2 but is missing from the current PHP system requirements

## Possible solutions:

Add ext-sodium to both /guides/v2.4/install-gde/system-requirements.html & /guides/v2.4/install-gde/prereq/php-settings.html

## Additional information:

Its not possible to complete Magento install without this extension, and a site that is migrated to a new version of PHP or which lacks this extension essentially breaks user login without exception.

**Comment by jeff-matthews** [comment]
I think https://github.com/magento-commerce/devdocs/pull/2470 will resolve this.

**Comment by dshevtsov** [comment]
Closed via https://github.com/magento-commerce/devdocs/commit/3ab7dec1903b5b4309ffdaa1b6e8b20eee7c5088
