### ISSUE TITLE
New topic for creating custom REST Api

### ISSUE THREAD

**Issue by nitish-ranjan05** [magento/devdocs#9117]
# New topic request

## Description

In the rest tutorial documentation, there is no example to create a custom rest API

We can add a new topic under the rest tutorials with examples

**Comment by nitish-ranjan05** [comment]
@magento I am working on this

**Comment by hguthrie** [comment]
@nitish-ranjan05 Do you still plan to create a new PR with the changes that @keharper requested? If so, you can assign yourself to this issue again. We look forward to your updates!

**Comment by nitish-ranjan05** [comment]
@magento I am working on this
