### ISSUE TITLE
Feedback on page: /live-search/release-notes.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9125]
# General issue

## Description:

Some customers are having issues with Live Search not working - in many of those cases, the customer is using Adobe Commerce (both On-Prem and on cloud architecture) with the B2B extension.

## Possible solutions:

Update the following and add an exclusion stating that there is currently no Live Search support for B2B extension (I don't have any roadmap information)

```
* Compatible with Adobe Commerce (EE): 2.4.x
* Compatible with Adobe Commerce on cloud infrastructure (ECE): 2.4.x
```

## Additional information:

**Comment by ccondra** [comment]
At this time, Live Search does not support B2B.  See note added to [Install Live Search](https://devdocs.magento.com/live-search/install.html).  Thank you!
