### ISSUE TITLE
Feedback on page: /guides/v2.4/comp-mgr/cli/cli-upgrade.html

### ISSUE THREAD

**Issue by hostep** [magento/devdocs#9132]
# General issue

## Description:

About the page: https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html#manage-packages

The instructions for retrieving a list of all available Magento versions via composer doesn't work anymore with composer v2
It currently suggest to use the `--all` flag. But it should suggest the `--available` flag. This `--available` flag also works fine with composer v1, so it sounds like a good solution.

Issue got discovered in https://github.com/magento/magento2/issues/34026

## Possible solutions:

Change the `--all` flag to the `--available` flag.

**Comment by nitish-ranjan05** [comment]
@magento I am working on this
