### ISSUE TITLE
 Merge JS and Bundling setting confusion

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/devdocs#9133]
# Bug report

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html
"To configure JavaScript bundling, you must disable Javascript file merging. Bundling will not work as the merging of files excludes bundling"

https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-js-bundling.html
"Enabling merging without also enabling bundling is not useful because Magento uses RequireJS. If you don’t enable bundling, Magento only merges RequireJS and its configuration. When you enable both bundling and merging, Magento creates a single JavaScript file"

## Description

The first desceiption is misleading that if we enable merge then bundling is skipped while the second description confirms the difference when we enable both merge and bundling.

_What is the issue/current behavior?_

### Steps to reproduce

_(OPTIONAL) What needs to be done to replicate this issue? Provide Gist if needed._

1. First Step
1. Second Step
1. Etc.

## Expected result

_When this issue is resolved, what is the expected result/behavior?_

## Possible solutions

_(OPTIONAL) What would a solution for this issue look like?_

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Additional information

_(OPTIONAL) What other information can you provide about this issue?_

**Comment by onlinebizsoft** [comment]
@dobooth

**Comment by bdenham** [comment]
@onlinebizsoft, I believe the first description is describing the settings available in the Admin UI. And the second is referring to changing the RequireJS files. Can you explain what you would expect for the first topic description?

**Comment by onlinebizsoft** [comment]
@bdenham in the first one, it says "Bundling will not work as the merging of files excludes bundling" -> it means if we enable merge then bundling do nothing?
In the second one, it says "When you enable both bundling and merging, Magento creates a single JavaScript file" -> means merging and bundling can work together and output a single JS file for whole site.

Here is another opinion which do agree with me
![image](https://user-images.githubusercontent.com/22501570/134470793-5e681188-3ea1-4704-8e98-3f41db09e283.png)

**Comment by bdenham** [comment]
Got it. Good catch. Thanks for clarifying. If you are interested in submitting a PR for the fix, that would be great.  Regardless, thanks for alerting us to the discrepancy.

**Comment by dshevtsov** [comment]
The topics were migrated to:
- <https://developer.adobe.com/commerce/frontend-core/guide/themes/js-bundling/>
- <https://experienceleague.adobe.com/en/docs/commerce-operations/performance-best-practices/performance-best-practices/advanced-js-bundling>

If the issue is still relevant, please feel free to reopen it in the corresponding repository:
- <https://github.com/AdobeDocs/commerce-frontend-core/issues>
- <https://github.com/AdobeDocs/commerce-operations.en/issues>
