### ISSUE TITLE
ESI varnish request for block 

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/devdocs#9134]
# New topic request
Adding a section to explain about ESI request in Magento and setting ttl for block in layout

## Description
https://medium.com/@sivaschenko/5-block-types-from-caching-point-of-view-in-magento-2-cfdfc329d7dc

_What topic is missing from documentation?_

ESI
Block is ESI if it’s declaration in the layout XML has ttl attribute. ESI blocks are actual only if full page cache application is set to Varnish. Such blocks are fetched by separate Varnish request, cached and invalidated independently from the page.
Use when the block:
is supposed to be invalidated much-much more frequently than pages where this block is rendered
is supposed to be invalidated much-much less frequently than pages where this block is rendered
How to use:
Add TTL attribute to block declaration in layout
<block class="MyBlock" ttl="3600"/>

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

- ...

## Content checklist

_List specific information or details to include in this topic._

_Use the following checklist template as a starting point:_

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains examples that shows ____.
- [ ] The tutorial should walk-through a complicated process.
- [ ] Other (please specify)

## Additional information/resources

_(OPTIONAL) Any information you already know or other online resources that cover this topic._

**Comment by onlinebizsoft** [comment]
@dobooth @sivaschenko

**Comment by bdenham** [comment]
@onlinebizsoft, we only mention ESI in relation to Fastly caching. Where do you envision this topic be added?

**Comment by onlinebizsoft** [comment]
@bdenham I dont know where it should be added. But the document is lacking information about this and it should be added.

The technical information were mentioned in the above article

**Comment by goivvy** [comment]
@magento I am working on this

We can add a new ESI topic under 'Configure and use Varnish' chapter https://devdocs.magento.com/guides/v2.4/config-guide/varnish/config-varnish.html

@dobooth @bdenham What do you think?


General syntax, examples and current restrictions (ESI is only served via HTTP) could be mentioned.
