### ISSUE TITLE
Incorrect version for ElasticSearch is mentioned in "Install and Configure Elastic" article

### ISSUE THREAD

**Issue by okobchenko** [magento/devdocs#914]
According to composer.json file Magento 2 supports elastic of ~2.0 versions, meanwhile documentation says it M2 support 1.0 and 2.0 versions. Please remove 1.0 version from documentation.

Link to article: http://devdocs.magento.com/guides/v2.1/config-guide/elasticsearch/es-overview.html

**Comment by xcomSteveJohnson** [comment]
Fixed. Please verify and close this if you're satisfied.

**Comment by xcomSteveJohnson** [comment]
Closing.
