### ISSUE TITLE
Update Install and Configure Recommendations

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9141]
# General issue

Affected page:  /recommendations/install-configure.html

## Description:

Add a note indicating that the API Keys must be generated in the account of the Adobe Commerce license holder.

## Possible solutions:

Similar to https://devdocs.magento.com/live-search/install.html#configure-api-keys 

The Adobe Commerce API key and its associated private key are required to connect Product Recommendations to an installation of Adobe Commerce. The API key is generated and maintained in the account of the Adobe Commerce license holder, who can share it with the developer or SI. The developer can then create and manage the SaaS environments on behalf of the license-holder. 

## Additional information:

This is indicated at https://docs.magento.com/user-guide/system/saas.html

To use Commerce Services, such as Product Recommendations or Live Search, the license-holder must generate these keys in order to pass entitlement validation. These keys can then be passed to the systems integrator or development team that manages the Commerce Services projects and environments on behalf of the license-holder. If you are a solution integrator, you are also entitled to use these services for your own needs. In that case, the signer of the Commerce partner contract should generate the keys.

**Comment by bdenham** [comment]
@eriksmarr Just making you aware of this issue if you were not already. :)

**Comment by erikmarr** [comment]
Thanks @ak77-prime! I have a PR with the change ready to go.
