### ISSUE TITLE
Tech Stack topic isn't redirecting

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#9146]
# General issue

## Description:

The https://devdocs.magento.com/guides/v2.4/architecture/tech-stack.html page doesn't redirect to https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html like it should.

## Possible solutions:

The source file should include a redirect for https://devdocs.magento.com/guides/v2.4/architecture/tech-stack.html just like the [2.3 version of the file](https://github.com/magento/devdocs/blob/master/src/guides/v2.3/install-gde/system-requirements.md).

**Comment by dshevtsov** [comment]
There is disparity in versions in the description. It says that 2.4 link has to redirect to 2.3 topic.

**Comment by nitish-ranjan05** [comment]
@magento I am working on this
