### ISSUE TITLE
Missing Adobe Schemas in Snowplow Chrome plugin in Product Recs docs

### ISSUE THREAD

**Issue by przmak** [magento/devdocs#9152]
# General issue

Snowplow Chrome extension, missing adobe schemas

## Description:

1) Install the Snowplow Chrome plugin into chrome browser 
2) Go to a magento website (tested on Magento 2.3.3-p2 ) with product recommendations
3) Open chrome developer tools -> Snowplow Debugger

Schemas Errors:

```
Schema : iglu:com.adobe.magento.entity/magento-js-tracker/jsonschema/1-0-0
Data validity : NOT FOUND
magentoJsVersion : "5.0.4"
magentoJsBuild : "2-1626709058-v4.0.0-rc.1-38-g80d6835"
```

```
Schema : iglu:com.adobe.magento.entity/shopper/jsonschema/1-0-0
Data validity : NOT FOUND
shopperId : "guest"
```

```
Schema : iglu:com.adobe.magento.entity/magento-extension/jsonschema/1-0-0
Data validity : NOT FOUND
magentoExtensionVersion : "6.1.0"
```

```
Schema : iglu:com.adobe.magento.entity/experiment/jsonschema/1-0-1
Data validity : NOT FOUND
experimentName : "aa-2019-12-12"
variantName : "control"
```

```
Schema : iglu:com.adobe.magento.entity/storefront-instance/jsonschema/3-0-0
Data validity : NOT FOUND
```

## Possible solutions:

Either remove the topic about Snowplow Chrome extension or fix the documentation

## Additional information:

Looks like not only I got the problem
https://magento.stackexchange.com/questions/344873/magento-recommendations-module-and-snowplow-schemas-issue

**Comment by shrielenee** [comment]
@erikmarr Is this truly a docs issue? Do you have insight into this issue?

**Comment by erikmarr** [comment]
HI @przmak thanks for your feedback! This is expected behavior. Basically those schemas are internal, not public. So the Snowplow Chrome plugin won't be able to validate the events with the private schema. This has no impact on actual functionality. It just shows that message in the Chrome plugin. I will clarify this in the docs. Thanks again.
