### ISSUE TITLE
Research creating canonical link for docs in Module Reference Guide

### ISSUE THREAD

**Issue by kai687** [magento/devdocs#9171]
# General issue
Feedback on page:  /guides/v2.4/mrg/module-catalog-permissions.html
Consider adding a canonical, or 'latest' link for your docs. This makes maintaining docs that link to your docs easier.

## Description:

I have to choose between linking to the 2.3, or 2.4 versions of this page.
If you update this page to 2.5, my link should still work, but it's no longer up to date.

## Possible solutions:

Have a canonical link, like: `/guides/mrg/module-catalog-permissions.html` that would always route to the latest available version of this document. OR: `/guides/latest/mrg/module-catalog-permissions.html`.

**Comment by dshevtsov** [comment]
> This makes maintaining docs that link to your docs easier.
@kai687, do you mean README's from the magento2 codebase?

**Comment by dshevtsov** [comment]
On devdocs, we should keep v2.x versioning, to allow versioned links from the in-code documentation for Commerce's source code. It means, we should have both 2.4 and 'latest' links. I can see only two solutions at the moment:
1. Global redirect: `/guides/v2.4 -> /guides/latest`. This is no good for Google indexes as I understand.
2. Virtual source files for `/guides/latest` that will replicate `/guides/v2.4` source file tree. Two options here: symlinks or pages without files (generated by a custom plugin for Jekyll). This will increase the number of real pages and their generation time on about ~1/3.

cc @jeff-matthews

**Comment by dshevtsov** [comment]
The content was moved to <https://developer.adobe.com/commerce/php/module-reference/>. No versioning there.
