### ISSUE TITLE
Payment field not written to the database

### ISSUE THREAD

**Issue by luke-vitale** [magento/devdocs#9178]
# General issue

## Description:
Extra Payment Field doesn't add to the database.

https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_payment_new_field.html

## Possible solutions:

The extra fields would get added to the database.

## Additional information:

No fields are added it seems to be an issue in the purchaseorder-method.js

**Comment by keharper** [comment]
@ajithkumar-maragathavel I'm not sure if you're the original author of this topic. If you are, can you take a look at this issue?

**Comment by ajith107** [comment]
> @ajithkumar-maragathavel I'm not sure if you're the original author of this topic. If you are, can you take a look at this issue?

Sure. I will check this one. Thanks
