### ISSUE TITLE
Should there be a OnePage checkout creation tutorial

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#919]
I have searched how to create OnePage checkout from magento.stackexchange.com but all who have asked about it have not get any answer. I also found module that allowed it and is free to download. But when i looked inside the module I notice that the developer has overriding many html and js files. 

Is it really necessary (what if Magento 2 decides to change those files) ? Because many people needs it and there is huge possibility to do it badly ( Too many unnecessary overriding files ) then why Magento 2 does not have any tutorial how to merge two steps Shipping and Payment to one? It has tutorial how to create new step but not  a way to create oneStep checkout?

I know that there are many modules that can be bought but after looking inside that one module what contained so much overriding files i don't trust any of them. Also i can not hope any help from magento.stackexchange.com.

Can someone please add official tutorial to magento devdocs how to do it!

**Comment by almarchenko** [comment]
Hi @user3748173 !

Here are our docs about customizing checkout:
http://devdocs.magento.com/guides/v2.1/howdoi/checkout/checkout_overview.html
It is not a complete tutorial yet, but answers a lot of questions about checkout customization.
Hope it will be helpful!

We are working now on a list of required tutorials, so we will add your request to this list!
Please let me know if I can close the issue.

**Comment by user3748173** [comment]
I know about the docs how to customize the checkout and have learned a lot from them. But I have found just that lot of questions about the checkout are without any answers in magento.stackexchange.com.

Also should not there be some Rules how to Customise Magento 2? I mean how much is normal to override files in the module so it will not disturb updating Magento and how many should treat Changing the vendor/magento/... html files in 2 Magento checkout? Reading some code I also found That one module in the developer had copied the layout of the XML file completely to the module and changes made in it? Is it good idea or not considerin updating? **To sum up: how can the developer estimate change impact made by the new module** (Module 2 Readiness for changes in magento core code) she/he creates?

I have had some troubles also by customising shipping-method, when i tried to add dropdown to it . It seemed strange to me that magento has decreased dropdown menus in layout and I could not find the reason why magento 2 tries to avoid them. But i think i found my answer in one of the stackexchange.com forums (UX in mobile users). I just thought to mention it in hire because **when it is really intentional then it should be doc in best ux practices** (when i was wondering around in magento.stackexchange.com i found some previous questions about how to add dropdown to checkout-methods block in magento 1.x and some modules have created that are using it in magento 1.x) 

**By the way thank you for adding my request to this list!**

**Comment by almarchenko** [comment]
@user3748173 
"Also should not there be some Rules how to Customise Magento 2? "
We have a lot of recommendations and best practices in a separate book:
http://devdocs.magento.com/guides/v2.1/ext-best-practices/bk-ext-best-practices.html

Regarding core files overriding, the golden rule is the following:
"You should never edit the core code because code changes occur between version upgrades and any changes you make will get overwritten. Try achieving your desired behavior with plugins, overriding interface preferences, and event observers."
Core files can be extended and overridden in custom modules. Unless the changes are NOT done in core files, this should not cause problems with updates.
