### ISSUE TITLE
app/etc/config.php tracking in VCS - docs conflict with links to .gitignore

### ISSUE THREAD

**Issue by df2k2** [magento/devdocs#9194]
# Track app/etc/config.php or not?

## Topic Link

https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-gitignore.html

## Description

The references to .gitignore found here: https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-gitignore.html and https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-gitignore.html are:

* https://raw.githubusercontent.com/magento/magento2/2.4/.gitignore
* https://raw.githubusercontent.com/magento/magento2/2.3/.gitignore

Which contain a reference to ignore `app/etc/config.php` : https://github.com/magento/magento2/blob/2.4-develop/.gitignore#L18

**However, there are several statements throughout devdocs that would lead to an assumption that this app/etc/config.php file would not be set for ignore by VCS in .gitignore for 2.3 and 2.4 CE:**

**Reference 1: https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/production-system.html**

> * Make sure all of the following are included in source control:
>   * app/etc/config.php

**Reference 2: https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/example/shared-configuration.html**

> Generate the shared configuration file, app/etc/config.php, in your development system and transfer it using source control to your build system as discussed in this section

**Reference 3: https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/technical-details.html**

> Manage the shared configuration
> The shared configuration is stored in app/etc/config.php, which should be in source control.

**Reference 4: https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-most.html**

>  The magento app:config:dump command writes these values to the shared configuration file, app/etc/config.php, which should be in source control.

## Possible solutions

One of:

* make it clear that `app/etc/config.php` needs to be explicitly added to VCS tracking 
* Remove the line ignoring `app/etc/config.php` from the .gitignore file,

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/files/config-reference-gitignore).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-operations.en/issues>.
