### ISSUE TITLE
Feedback on page: /guides/v2.4/mrg/module-quick-order.html

### ISSUE THREAD

**Issue by WebKenth** [magento/devdocs#9197]
# General issue

Module is not available, while documentation state that it is

## Description:

Looking at https://github.com/magento/magento2/tree/2.4.3-p1/app/code/Magento
I see no QuickOrder module, but it is listed in the documentation as available ?

## Possible solutions:

Either change the documentation to correctly correct which modules are available or make it available ;)

## Additional information:

`This topic is generated and maintained through automation, so we do not accept direct contributions from pull requests on GitHub.`
^ Since it is an automated documentation, maybe it is a bug in the generation of this list?

**Comment by keharper** [comment]
@WebKenth The Module Reference Guide includes modules from the magento2ce, magento2ee, magento2b2b repos, plus any repos that are required to install those three products. QuickOrder is part of the B2B repo.
