### ISSUE TITLE
Please select a valid payment method.

### ISSUE THREAD

**Issue by shoosah** [magento/devdocs#920]
After creating card via 'cart.create', I set payment via 'cart_payment.method'. I used the following code sample and it only works when I set payment method to "purchaseorder" ("method" => "purchaseorder"). Otherwise, it throws faultcode:1008(Please select a valid payment method).

$proxy = new SoapClient('http://magentohost/api/soap/?wsdl');
$sessionId = $proxy->login('apiUser', 'apiKey');

$shoppingCartId = $proxy->call( $sessionId, 'cart.create', array( 'magento_store' ) );

$paymentMethod = array(
	"method" => "checkmo"
);

$resultPaymentMethod = $proxy->call(
	$sessionId,
	"cart_payment.method",
	array(
		$shoppingCartId,
		$paymentMethod
	)
);

Reference: http://devdocs.magento.com/guides/m1x/api/soap/checkout/cartPayment/cart_payment.method.html

**Comment by xcomSteveJohnson** [comment]
Referred to Support for assistance.

**Comment by xcomSteveJohnson** [comment]
@shoosah Support would like to know what version of Magento 1.x you're using. This appears to be a known issue being tracked by SUPEE-4952.

**Comment by shoosah** [comment]
@xcomSteveJohnson It is version 1.9.0.1. If it's a known issue, then I was wondering how I can differentiate between different payments like CC and Paypal in Magento.

**Comment by xcomSteveJohnson** [comment]
@shoosah I don't know the answer to your question. SUPEE-4952 resulted in a patch to EE 1.14.0.1 but Magento Support doesn't usually patch CE.

Suggest you post a question on [Magento Forums](https://community.magento.com) and see if you can get more help there.

**Comment by shoosah** [comment]
@xcomSteveJohnson I asked the question on https://community.magento.com/t5/Programming-Questions/Please-select-a-valid-payment-method-version-1-9-0-1/m-p/55551#M6867
I'd suggest that you close this issue since it is a known issue and the solution is a patch in a later version.
