### ISSUE TITLE
Feedback on page: /guides/v2.4/ui_comp_guide/components/ui-insertlisting.html

### ISSUE THREAD

**Issue by LeonElephant** [magento/devdocs#9211]
# General issue

## Description:

Sorting on id changes the ids and name to the last value

## Possible solutions:

-

## Additional information:

https://www.loom.com/share/7d838daffc6c420f99e6c3a5fcc21083

**Comment by dobooth** [comment]
Hi @LeonElephant That does seem troubling. As it appears to be a bug in code and not within the documentation. We suggest you contact support for this issue: https://support.magento.com/hc/en-us
