### ISSUE TITLE
SSL certifiate is not valid

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#922]
Right now in google index we have pages on http & https protocols. After going to https link we have incorrect ssl certificate warning.
 

**Steps to reproduce**
1. Go to https://www.google.com/search?q=magento+2+vault
2. Click on link that starts from https://devdocs.magento.com/

**Actual result**
We have incorrect ssl certificate

**Expected result**
We should have correct SSL certificate

**Comment by xcomSteveJohnson** [comment]
devdocs is not an SSL site. We don't know why some search links are returned with the incorrect `https://` scheme.

If you change the scheme to `http://`, the links work.

Closing.
