### ISSUE TITLE
Checkout tutorial lists invalid code.

### ISSUE THREAD

**Issue by zexperto** [magento/devdocs#9221]
# General issue

Affected page: /guides/v2.4/howdoi/checkout/checkout_form.html

## Description:

Implement the same custom checkout form into billing-step, with the below path does not work 
**billing-step(children)->payment(children)->payments-list(children)->before-place-order(children)**

## Additional information:

When implement this on Billing step instead of shipping step we got the below error
and to reproduce the issue you should activate  "Purchase Order" payment method  then  click on **Place Order**
most probably that's because there is another form for the Purchase Order Number
![image](https://user-images.githubusercontent.com/2926032/139081677-ef5bfe96-bf0c-436f-af2c-daed60086062.png)

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/add-form/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-php/issues>.
