### ISSUE TITLE
Need clarification for opcache.enable_cli=1 

### ISSUE THREAD

**Issue by barnato-v** [magento/devdocs#9222]
# Topic clarification/correction request

## Topic Link

devdocs article https://devdocs.magento.com/guides/v2.3/performance-best-practices/software.html#php-settings (link from this articles) recommends
opcache.enable_cli=1 

but this differs for recommendations in support.magento.com

## Description

devdocs article https://devdocs.magento.com/guides/v2.3/performance-best-practices/software.html#php-settings (link from this articles) recommends
opcache.enable_cli=1 - but the support article https://support.magento.com/hc/en-us/articles/360050422532 recommends opcache.enable_cli=0? Trying to work out why we have different information and what are the best settings for the Opcache module?

## Possible solutions

clarify optimism settings for OpCache module - maybe it is different for on-premises vs cloud?

## Additional information

https://jira.corp.magento.com/browse/KB-951

**Comment by barnato-v** [comment]
@hguthrie Can I ask for a contact name for the performance team?

**Comment by keharper** [comment]
@meker12 Can you recommend a development resource?

**Comment by meker12** [comment]
There was a fix for the problem described in the [KB article](https://support.magento.com/hc/en-us/articles/360050422532)  introduced in [ece-tools 2002.1.5](https://devdocs.magento.com/cloud/release-notes/ece-release-notes.html#v200215).  

Work done by Cloud team [MCLOUD-7015](https://jira.corp.magento.com/browse/MCLOUD-7015)  -- [GitHub PR](https://github.com/magento-commerce/ece-tools/pull/13) as part of a PHP tuning epic. Check with @arhiopterecs or @oshmyheliuk.

```Flushing the opcache—Added support for the opcache.enable_cli PHP option to flush the OPcache before running the deploy hook. This configuration resets the cache configuration to ensure that the current configuration settings are applied on each deployment.```

If customers are running 2002.1.5 or later, they shouldn't have to change the opcache.enable_cli setting to zero.
