### ISSUE TITLE
Add note about additional DB users in cloud

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9244]
# General issue

## Description:

https://devdocs.magento.com/cloud/project/services-mysql.html

Add a note that this is a self-service task only in the Integration/Development branches (for Pro projects, and all branches for Starter projects.)

You will have to submit a Support ticket to request the additional DB user in Staging and Production for Pro projects.

## Possible solutions:

```
You can set this up yourself in the Integration/Development branches (for Pro projects only) and all branches for Starter projects.

You will have to submit a Support ticket to request the additional DB user in Staging and Production for Pro projects.
```

**Comment by dobooth** [comment]
@hguthrie
