### ISSUE TITLE
Setting up custom domains on Cloud Pro

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9245]
## Description:

https://devdocs.magento.com/cloud/project/project-multi-sites.html

This article doesn't provide much clarity about setting up custom domains for Staging and Production environments in Cloud Pro.

## Possible solutions:

- Cloud Pro:
You must open a Support ticket to request new domains to be added to the cluster. Note: you could add the domains to Fastly yourself, but you will still have to open a ticket to configure Nginx.

- Starter
1. You can either add the domain to Fastly in Production yourself or open a ticket to request this.
2. You will also have to add the domain to the Domains tab at <region>magento.cloud/projects/<Project ID>/edit

## Additional information:

[Managing domains in Fastly using the extension](https://devdocs.magento.com/cloud/cdn/configure-fastly-customize-cache.html#manage-domains)

**Comment by BarnyShergold** [comment]
@ak77-prime - we can add a small section to the top of the page entitled "Adding New Domains"
I don't have access to a Starter Project - so where did you get the info about a Domains tab? Also that link "magento.cloud/projects//edit" - doesn't exist, where's that from? If you have access can you post a couple of screenshots so I can see what you are referring to?

**Comment by dobooth** [comment]
@hguthrie

**Comment by hguthrie** [comment]
The topic does state that Pro users "can create a Support ticket and include “enable self-service routes” in your request."
We can change that notice to contain more clear information, but the Domains can be added in the magento.app.yaml file. I don't think you have to add them using the interface if they are defined in the configuration file. Unless there is something very different about Pro...

**Comment by ak77-prime** [comment]
This was what I had entered:

```
<region>magento.cloud/projects/<Project ID>/edit
```

It was strippd

**Comment by BarnyShergold** [comment]
@hguthrie @ak77-prime - You cannot add new domains to be recognised and handled by the platform using configuration files. You can use routes.yaml to manage added domains but not to add them to the system.

PRO REQUIRES that you contact Support and submit a ticket to have them added (this is also required to ensure SSL covers the domains)

If you go to the Domains tab on a PRO project you ALWAYS see this - 
![domains](https://user-images.githubusercontent.com/1592991/142014987-cc71de42-2bd2-4f0d-9c09-8bf03bf02253.png)

Even when the site is fully live.

For clarity & simplicity, I propose -

```
### Cloud Pro

- You must open a Support ticket to request new domains to be added to the cluster. 

### Starter

- You can either add the domain to Fastly in Production yourself or open a ticket to request this.
- You will also have to add the domain to the Domains tab at https://<zone>.magento.cloud/projects/<project ID>/edit

```

**Comment by hguthrie** [comment]
Thanks @BarnyShergold for the clarification. I was indeed thinking about the steps based on the multi-sites topic, which was born out of a presentation devs did some time ago. We do not have much, if anything, about the actual domain tab of the UI.
