### ISSUE TITLE
GraphQL: Add docs for assignCustomerToGuestCart mutation

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#9248]
# Community engineering issue

Type of Doc:

-  [x] New topic
-  [ ] Topic Update, Devdoc link:
-  [ ] Other

Magento 2 GitHub Issue: https://github.com/magento/magento2/issues/32615

Magento 2 GitHub PR: https://github.com/magento/magento2/pull/33106

Magento 2 version:

-  [x] 2.4

Notifications of Changes:

-  [ ] Changes to Admin interface?
-  [ ] New software requirements?
-  [x] New REST endpoints or updated GraphQL query syntax?
-  [ ] New command line option?

## Content

Add documentation for the `assignCustomerToGuestCart` mutation. The new topic must include a general description of the mutation, the syntax, a working example, and the output fields. The `mergeCarts` documentation can be used as a template for this new topic.

Place the topic in the `src/guides/v2.4/graphql/mutations` directory. 

Also add a link to the new topic in TOC file at `src/_data/toc/graphql.yml`

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by keharper** [comment]
Fixed in #9252
