### ISSUE TITLE
Class Magento\SampleMinimal\Cron\Test does not exist

### ISSUE THREAD

**Issue by afmv** [magento/devdocs#926]
Hi everyone, i follow this tutorial but i can't execute correctly. It give me this error "Class Magento\SampleMinimal\Cron\Test does not exist"

http://devdocs.magento.com/guides/v2.0/config-guide/cron/custom-cron-tut.html

When i execute cron:run it show a error in the DB in the table cron_schedule.

**Comment by xcomSteveJohnson** [comment]
Make sure this file does exist: `/var/www/html/magento2/app/code/Magento/SampleMinimal/Cron/Test.php`

**Comment by afmv** [comment]
Hi, Thks for the reply. I'm already solved the problem... For some reason when i save the file the extension .php wasn't saved.

**Comment by xcomSteveJohnson** [comment]
@afmv Are you able to complete the procedure?

**Comment by afmv** [comment]
Hi. I'm completed the procedure.

I'm opened a question in magento forum. Can you help if you know how?
https://community.magento.com/t5/Programming-Questions/ERP-Integration/m-p/55536#U55536

**Comment by xcomSteveJohnson** [comment]
@afmv Because you've completed the procedure, closing. Feel free to reopen if you still have questions.
