### ISSUE TITLE
Add correction to File systems access permissions topic

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/devdocs#9261]
# General issue

Affected topic: /guides/v2.4/config-guide/prod/prod_file-sys-perms.html

## Description:

Please look at https://github.com/magento/magento2/issues/13225 - this is documentation issue

**Comment by keharper** [comment]
@ihor-sviziev We need clear instructions about what needs to be changed. Reading through the comments of magento/magento2#13225, it looks like a code bug more than a docs bug.

**Comment by ihor-sviziev** [comment]
@keharper, when js/css merging is enabled - the folder `pub/static/_cache` even in production mode should be created and writable.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/deployment/file-system-permissions).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-operations.en/issues>.
