### ISSUE TITLE
Clarify how to store extension attributes in the database

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#9262]
# General issue

Affected topic: /guides/v2.4/extension-dev-guide/extension_attributes/adding-attributes.html

## Description:

The article is not clarifying whether we should create our own table column for scalar attributes manually for example via db_schema.xml or via an InstallSchema setup script to persist the extension attribute value in the database. 

## Possible solutions:

Clarify what a developer needs to do to store the extension attribute in the database.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/development/components/add-attributes/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-php/issues>.
