### ISSUE TITLE
Clarify who can manage Cloud users

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9263]
# General issue

Affected topic: /cloud/project/user-admin.html

## Description:

Update the article to indicate that users with the Admin role can no longer manage users [using the CLI] or click on the Users tab when configuring their assigned environment(s). 

[Under this section](https://devdocs.magento.com/cloud/project/user-admin.html#cloud-user-mg-cli)

```
To add a user and assign roles:

1. Use the CLI to add the user.

magento-cloud user:add

...
```

[And under this section](https://devdocs.magento.com/cloud/project/user-admin.html#cloud-user-webinterface) - only Super Users will be able to add an environment-level user [or project-level - although that's always been the case anyway.]

```
Add an environment-level user:

1. In the Project Web UI, select the environment. Then, click Configure environment.
<image: Configure the environment>

2. Click the Users tab, and then click Add User.

...
```

## Possible solutions:

Add a box/note like this:

```
Only Super Users will be able to manage the users in any environment. 

To grant a particular user access to the Users tab when configuring the environment, another Super User - or the Account Owner - must assign that user the Super User role.
```

## Additional information:

For security reasons [as of Nov 24, 2021], Platform.SH is now disallowing Admin users from being able to manage users in their assigned environment(s)

**Comment by gamarshall** [comment]
Fixed by magento-commerce/devdocs#2919
