### ISSUE TITLE
Typo needs fixing

### ISSUE THREAD

**Issue by Vitalii-Plechak** [magento/devdocs#9264]
# Typo issue

## Description:

https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget-multiselect.html

Typo in the text on the "Multiselect Widget" page.

Typo in the "The RedirectUrl widget has the following options:" sentence, expected result is the "The Multiselect widget has the following options:" sentence.

![image](https://user-images.githubusercontent.com/60887814/143425591-a792d040-d68d-46d5-b243-fda409ebeb0d.png)

## Actual result

"The RedirectUrl widget has the following options:"

## Expected result

"The Multiselect widget has the following options:"

## Possible solutions:

The typo should be corrected.

**Comment by Viper9x** [comment]
@magento I am working on this
