### ISSUE TITLE
Stuck Deployments - Commerce Cloud

### ISSUE THREAD

**Issue by BarnyShergold** [magento/devdocs#9265]
# New topic request

## Description

Commerce Cloud builds sometimes get stuck and until cleared, no further deployments can be actioned (even on other environments on the same project)

Most of the time developers have to raise a ticket to support to clear. The stuck deployment can be caused by issues with code or services. Often the developer can clear the deployment themselves by killing stuck processes.

## Proposed Solution
Create a new page under https://devdocs.magento.com/cloud/live/stage-prod-live.html

This will detail how a developer might clear a stuck deployment, which logs to check to see where the deployment has gotten stuck and for certain "getting stuck reasons" (eg Magento_AMQP might get stuck in setup:upgrade if there are issues with the RabbitMQ service) . 

We can encourage support engineers & developers to report build issues that can be resolved by the developer and add to this section.

The aim is to allow developers to self-serve in some instances and not have to raise a support ticket and wait.

**Comment by hguthrie** [comment]
The Support site already has a stuck deployment article: https://support.magento.com/hc/en-us/articles/360040986912

Creating a topic in the cloud guide dedicated to troubleshooting is not ideal, but can link to the KB article in strategic places.
