### ISSUE TITLE
unfollowed standards

### ISSUE THREAD

**Issue by ttnnkkrr** [magento/devdocs#927]
Feedback on page: /guides/v2.1/extension-dev-guide/object-manager.html

> Magento prohibits the direct use of the ObjectManager in your code because it hides the real dependencies of a class. See usage rules.

and then you say 

> You may notice in the Magento 2 codebase that some core classes still call the ObjectManager directly.
> This  code needs porting or exist for backward compatibility purposes.
> They are not tacit endorsements of using the ObjectManager directly.

Yet you make it nearly impossible to build code without it by having poor documentation of you object model and by in your own sample codebase doing the very thing you recommend against

**Comment by jeff-matthews** [comment]
We understand your frustration, but it's still important that people understand that Magento code only uses this to support backward incompatible changes. No action on devdocs required.
