### ISSUE TITLE
Cloud: Provide example of adding location headers

### ISSUE THREAD

**Issue by edwinjacobs-pon** [magento/devdocs#9275]
# General issue

https://devdocs.magento.com/cloud/project/magento-app-properties.html

## Description:

Section Web > Location describes that you can add headers however there is no example provided, my guess would be something like this
"/my-location"
  headers:
    "My-Custom-Header": "header-value"

## Possible solutions:

Provide an example in the examples section

## Additional information:

My case is that I need to serve files without file extension. In the current situation nginx adds header
Content-Type: application/octet-stream which I need to adjust.

**Comment by hguthrie** [comment]
Moved issue to new repository.
