### ISSUE TITLE
Clarify if crons are disabled in Maintenance mode

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/devdocs#9279]
# General issue

Does maint mode disable cron?

## Description:

Feedback for: https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-maint.html

**Comment by danidelcar** [comment]
Hi @LiamKarlMitchell you have some information here: https://devdocs.magento.com/cloud/configure/setup-cron-jobs.html#disable-cron-jobs that mentions in some cases you might want to manually disable cron jobs before you complete maintenance tasks. There is a forum topic that covers a similar issue here: https://community.magento.com/t5/Magento-1-x-Technical-Issues/Disable-Cronjobs-when-maintenance-flag-is-set/td-p/27743.

Hope it clarifies your question!, thanks!

**Comment by dobooth** [comment]
Let us know if any of the docs needs updating around this.
