### ISSUE TITLE
Some pages are broken in new layout

### ISSUE THREAD

**Issue by Vinai** [magento/devdocs#928]
For example http://devdocs.magento.com/guides/v2.1/extension-dev-guide/test/test_js-unit.html

The header doesn't look like on the other pages and no menu entry can be selected (Firefox and Chrome Desktop).

<img width="1059" alt="Broken Header" src="https://cloud.githubusercontent.com/assets/72463/21175912/e1986b36-c1e4-11e6-982f-61ab27be795e.png">

**Comment by dshevtsov** [comment]
@Vinai good catch! Will fix! Thanks!

**Comment by xcomSteveJohnson** [comment]
@dshevtsov I'm fixing it now. I'm adding a redirect from the old page to the correct page.

**Comment by dshevtsov** [comment]
@xcomSteveJohnson the [Navigation link](https://github.com/magento/devdocs/blob/develop/_includes/navigation.html#L68) must be fixed also.

**Comment by xcomSteveJohnson** [comment]
The link is correct in the `develop` branch. There is an unexplained delay in synchronizing the internal GitHub repo with the public repo. Most likely the issue goes away when synchronization resumes.

**Comment by xcomSteveJohnson** [comment]
@Vinai Fully fixed now with a redirect to the correct URL. Please close if you're satisfied.

**Comment by xcomSteveJohnson** [comment]
Closing
