### ISSUE TITLE
Remove or update Domain terminology from Domain layer topic

### ISSUE THREAD

**Issue by allsilaevex** [magento/devdocs#9281]
# General issue

Feedback for : https://devdocs.magento.com/guides/v2.4/architecture/archi_perspectives/domain_layer.html

## Description:

Page has a link to glossary for the term "domain". Term referred to does not refer to the context of the page.

## Possible solution

Create new glossary term for "domain layer", or remove the glossary link within this topic.

**Comment by BarnyShergold** [comment]
@hguthrie - If "Domain Layer" is defined as the business layer and encapsulates the business logic and data, then the page itself is defining this. We could add "Domain Layer" to the glossary for a wider use but in the case of this page, isn't it rather circular and thus redundant? I say, just remove the link, what do you think?

**Comment by Viper9x** [comment]
@magento I am working on this
