### ISSUE TITLE
Feedback on page: /cloud/project/services.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9296]
# General issue

## Description:

https://devdocs.magento.com/cloud/project/services.html#service-versions

The version compatibility grid is not accurate, specifically the MariaDB version - the 2.4 column indicates 10.2-10.4 are supported - but it should be further broken down into 2.4.0 (which supports all those versions,) and 2.4.1-2.4.3 (supports 10.4 only)

## Possible solutions:

Take the cue from https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

## Additional information:

**Comment by hguthrie** [comment]
The information in the install guide is not exactly the same compatibility for the Cloud infrastructure. The Cloud guide takes the "cue" from ece-tools and is usually updated or verified on release.
