### ISSUE TITLE
Getting an error when running the REST configurable product tutorial

### ISSUE THREAD

**Issue by rajatpatil572** [magento/devdocs#9299]
Affected page: /guides/v2.3/rest/tutorials/configurable-product/define-config-product-options.html

I get the error when I try to map

{"message":"The child product doesn't have the \"%1\" attribute value. Verify the value and try again.","parameters":["gender"]}

**Comment by DenisSaltanahmedov** [comment]
@magento I am working on this

**Comment by DenisSaltanahmedov** [comment]
The tutorial is correct, I have tested all steps, I think in this case we have wrong 'attribute_id', I added a PR with additional info to prevent the case.
Thank you.
