### ISSUE TITLE
Bug with currency symbol in magento 2.4.3

### ISSUE THREAD

**Issue by leduydong94** [magento/devdocs#9305]
# General issue

## Description:

I tried using Euro as my currency, and I noticed, when I visit the product page, the currency symbol appears 1s after the page loads, then disappears, I checked in the vendor magento, I noticed in file /vendor/magento/module-directory/Model/Currency.php the function getOutputFormat is returning '%s' instead of '€%s', so when javascript (file /Magento_Catalog/js /price-box.js) format price, price formatted is already without symbols, I think it's a bug. I have attached the error video link. Please help me check again.
Error: https://www.loom.com/share/37046d17879247108adbc71f0fa58628

**Comment by leduydong94** [comment]
@magento I am working on this

**Comment by BarnyShergold** [comment]
@leduydong94 - This is not a DEVDOCS issue but one with code, so this is the wrong place to raise it. You should create an issue on the magnto/magento2 repo.

I am therefore closing this issue. 

Thank you!

**Comment by leduydong94** [comment]
> @leduydong94 - This is not a DEVDOCS issue but one with code, so this is the wrong place to raise it. You should create an issue on the magnto/magento2 repo.
> 
> I am therefore closing this issue.
> 
> Thank you!

Ok, I'll create on the magento/magento2 repo. 
Thank you!
