### ISSUE TITLE
Add Security info to Availability page

### ISSUE THREAD

**Issue by katmoon** [magento/devdocs#9307]
# General issue

Affected page:  https://devdocs.magento.com/release/availability.html

https://github.com/magento-commerce/security-package versions compatibility information is missed on this page
as well as https://github.com/magento-commerce/security-package-ee
and https://github.com/magento-commerce/security-package-b2b

## Possible solutions:

Please add similar information for the packages mentioned above

**Comment by BarnyShergold** [comment]
@dobooth - I'm not sure this is actually needed. 
**magento/security-package** is included as part of **magento/product-community-edition** 
**magento/security-package-ee** - doesn't seem to be installable via composer - I'm getting the "invalid package" error when I try to include this on a Cloud project.
**magento/security-package-b2b** is included as part of the B2B repo **magento/extension-b2b**

So the relevant versions of the security packages should be included with the version of Magento being used.

Can you review this?

**Comment by dobooth** [comment]
Hi @katmoon Sorry for the delay in reply here. What do you think about Barney's comment? Are these extension pulled in via  parent extensions?

**Comment by katmoon** [comment]
Rechecked that the packages are indeed installed with the ee and b2b edition. Thank you @BarnyShergold  and @dobooth

**Comment by dobooth** [comment]
Thanks all. Closing the issue.
