### ISSUE TITLE
2.1 docs lack information about filter UI component

### ISSUE THREAD

**Issue by schmengler** [magento/devdocs#931]
In the 2.0 docs there is a section about "listing/grid secondary components" like the filter component: http://devdocs.magento.com/guides/v2.0/ui-components/ui-secondary-filter.html

There seems to be nothing like this for Magento 2.1

Also, examples for common tasks to **extend** these components would be useful, like:

- add a new attribute to the grid filters
- add a custom calculated filter

To add a new customer attribute to the customer grid and make it filterable I needed to follow these steps, which I figured out by the help of stack exchange (esp. [this](http://magento.stackexchange.com/questions/126820/magento-2-how-to-add-a-custom-column-in-customer-grid/150103#150103) question) and trial and error - the devdocs did not help me:

- create `view/adminhtml/ui_component/customer_listing.xml` to add a **column** component
- create the column component PHP class which extends `Magento\Ui\Component\Listing\Columns\Column`
- create `etc/indexer.xml` to add the attribute to the `customer_grid` index and define it as filterable
- set `is_used_in_grid` to true for the attribute

Examples like this would be very helpful IMHO

**Comment by almarchenko** [comment]
@schmengler Thank you for your input!
This is absolutely true. Adding all the lacking info in the UI component guide for 2.1 is one of our priorities. And adding a filterable attribute is in the list of How tos. Here's the outline http://devdocs.magento.com/guides/v2.1/ui_comp_guide/ui_comp_outline_proposed.html
And the information you provided is very useful.

**Comment by almarchenko** [comment]
Hi @@schmengler 
We are now much closer to publishing more UI components docs for 2.1 
I've used the info you provided in our draft for the Filters component.
Thank you again for the input, I will close the issue.
Please feel free to reopen it if needed.
