### ISSUE TITLE
Provide more information about creating custom attributes

### ISSUE THREAD

**Issue by zhartaunik** [magento/devdocs#9323]
## Topic Link

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/extension_attributes/adding-attributes.html

## Description

The information in this article describes the way how to create extension attributes for the system entity. On attempt to create ext attribute for the custom entity user will face with troubles.

## Possible solutions

Add the details that the custom entity should have get/setExtensionAttributes methods. And how these methods should be created.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/development/components/add-attributes/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-php/issues>.
