### ISSUE TITLE
Bug report - elestic search engine seems not to be working

### ISSUE THREAD

**Issue by mistcooling** [magento/devdocs#9326]
products not showing on our website - developer says issue is elastic search engine

**Comment by mistcooling** [comment]
website is  : www.mistcooling.com

**Comment by dobooth** [comment]
Hi @mistcooling. This doesn't sound like a docs issue. For a real time production issue, you might want to contact Magento support (https://support.magento.com/hc/en-us/search?utf8=%E2%9C%93&query=elasticsearch) or active forums such as StackOverflow. If it is a bug with Magento, you can file an issue at https://github.com/magento/magento2
