### ISSUE TITLE
Request for a topic update on including head scripts / styles

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#9339]
## Topic Link

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/css-themes.html

## Description

Please add an example of how to add css with preload in the head section. 
Currently we can add scripts or stylesheets with the classic way of 

```
        <script src="Vendor_Module::path_to.js" defer="true" />
        <css src="Vendor_Module::path_to.css"/>
```

But there's no clear way to add preloaded css 

So how would we be able to do something like this?

```html
<head>
  <meta charset="utf-8">
  <title>JS and CSS preload example</title>

  <link rel="preload" href="style.css" as="style">
  <link rel="preload" href="main.js" as="script">

  <link rel="stylesheet" href="style.css">
</head>

<body>
  <h1>bouncing balls</h1>
  <canvas></canvas>

  <script src="main.js" defer></script>
</body>

```

## Possible solutions

It should give a clear example of adding a css and a js file using rel="preload"

**Comment by danidelcar** [comment]
Hi @dshevtsov do you think you could help with this issue?, or point to the right person to address it? Thanks!

**Comment by danidelcar** [comment]
Thanks Dima!

**Comment by JesperHerrloff** [comment]
In the layout xml file it should be possible link with attributes both rel and as

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/frontend-core/guide/css/themes/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-frontend-core/issues>.
