### ISSUE TITLE
Add error info to addProductsToCart mutation

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#9340]
## Topic Link

https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-cart.html

## Description

Add error information similar to what's present on [updateCartItems](https://devdocs.magento.com/guides/v2.4/graphql/mutations/update-cart-items.html#errors).

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/add-products/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-webapi/issues>.
