### ISSUE TITLE
Deprecated method shown in incorrect version

### ISSUE THREAD

**Issue by benn1988** [magento/devdocs#9345]
## Topic Link

[https://devdocs.magento.com/guides/v2.4/extension-dev-guide/view-models.html](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/view-models.html)

## Description

The 2.4 version is a symlink to the 2.3. In 2.4 for other pages, the $block->escape methods have been update to use the $escaper, since using it from $block has been deprecated, but on this page, it still shows $block->escape

## Possible solutions

Create a new version for 2.4 with updated escape methods.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/development/components/view-models/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-php/issues>.
