### ISSUE TITLE
Hi @SmpromoStars. Thank you for your report.

### ISSUE THREAD

**Issue by SmpromoStars** [magento/devdocs#9351]
Hi @SmpromoStars. Thank you for your report. 
To speed up processing of this issue, make sure that you provided sufficient information. 

Add a comment to [assign the issue](https://devdocs.magento.com/contributor-guide/contributing.html#assigning-an-issue): `@magento I am working on this` 

---
-  Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

_Originally posted by @m2-assistant[bot] in https://github.com/magento/devdocs/issues/9350#issuecomment-1032124766_

**Comment by danidelcar** [comment]
this was automatically generated and linked to 9350. closing it
