### ISSUE TITLE
Correct instructions for running GraphQL functional tests

### ISSUE THREAD

**Issue by keharper** [magento/devdocs#9353]
## Description

Affected page: https://devdocs.magento.com/guides/v2.4/graphql/functional-testing.html#run-functional-tests

Update the path for running the tests as described at the bottom of https://github.com/magento/magento2/issues/32252

**Comment by sprankhub** [comment]
Please mind that this also affects integration tests.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/webapi/get-started/web-api-functional-testing/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-webapi/issues>.
