### ISSUE TITLE
Missing attribute under layout instructions

### ISSUE THREAD

**Issue by bassplayer7** [magento/devdocs#936]
Each XML element listed in the allowed layout instruction table has a list of available attributes. The table is here: http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/layouts/layout-types.html#layout-types-page. It appears that the `src_type` is not listed as an available attribute. The attribute doesn't append the site's asset location URL to the value of the `src` attribute. As a result, it is important in facilitating external resources (like Google Fonts). 

Ultimately, I found the attribute shown here: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-manage.html#layout_markup_css.

**Comment by almarchenko** [comment]
@bassplayer7  Thank you for the observation! 
Will correct this, internal issue 63040

**Comment by almarchenko** [comment]
@bassplayer7 I've updated the doc, thank you!
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/layouts/layout-types.html

**Comment by bassplayer7** [comment]
Very good. Thank you @almarchenko!
