### ISSUE TITLE
Create a new query for get a detail requisition with graphql

### ISSUE THREAD

**Issue by oasis1992** [magento/devdocs#9365]
## Topic Link
https://devdocs.magento.com/guides/v2.4/graphql/queries/customer.html#customerAttributes

## Description
Is difficult  manage cache of requisitions list between views

## Possible solutions
The solution for me is create a new query 'getRequisition(requisitionId: ID!)', this would improve the manage cache

**Comment by dobooth** [comment]
Thanks for the issue, @oasis1992. This sounds like you want a new GraphQL query, rather than an update to the docs. You should open an issue to the magento2 [codebase](https://github.com/magento/magento2/issues).
