### ISSUE TITLE
Order Status Change

### ISSUE THREAD

**Issue by Xiaoyi-ji-11** [magento/devdocs#9372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://magento.redoc.ly/2.4.3-admin/tag/orders#operation/salesOrderRepositoryV1GetListGet

### What's wrong with the content?

The order status enum changed without notice.
<img width="624" alt="image" src="https://user-images.githubusercontent.com/88681868/156036030-2d45c681-b396-4ff5-8b66-f7ada118b6d1.png">
The predefined order status shows in this website doesn't have status "prepare_for_shipment"
[](https://docs.magento.com/user-guide/sales/order-status.html)

**Comment by keharper** [comment]
@Xiaoyi-ji-11 We need more information to proceed with this issue. 

The REST documentation is autogenerated, and enum values are not listed. I did a quick search in `2.4-develop` branch of the magento2 repo for `prepare_for_shipment`, but I found nothing. So, I can't verify that the enum changed in our codebase. It's possible that an extension added it.

If you can find the new enum value in the Magento repos, please open an issue against this page.

https://docs.magento.com/user-guide/sales/order-status.html

I'll leave this issue open for now, but probably this is a merchdocs issue.
