### ISSUE TITLE
Adding an environment-level user from the Cloud UI

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/project/user-admin.html#cloud-user-webinterface

### What's wrong with the content?

The instructions under this section are incorrect:

``Add a environment-level user:``

The same steps are to be used as in ``Add an project-level user:`` above - i.e., ``In the Project Web UI, click the settings icon in the top navigation bar.``

This can no longer be done on the environment-level using those instructions.

### What changes do you propose?

1. In the Project Web UI, click the settings icon in the top navigation bar.
2. Click Add User
3. Complete the Add User form - specify which environment(s) the user is to be added to

![image](https://user-images.githubusercontent.com/68703716/156859879-bc99ad4e-a440-4299-b2c2-71ad561a8bb1.png)

**Comment by erikmarr** [comment]
@hguthrie is there any missing information in this issue or can we move this to ready for dev?

**Comment by hguthrie** [comment]
Okay, I looked into this more. There is a bug in the UI. Because of a project we are working on, the workaround will have to be in the docs for now. @gamarshall Can you address this?

**Comment by gamarshall** [comment]
Addressing this issue.
