### ISSUE TITLE
Conflicting content in OpCache timestamp validation item

### ISSUE THREAD

**Issue by alejandro-rgp** [magento/devdocs#9377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/optimal-dev-environment.html

### What's wrong with the content?

In the last part of this documentation page (Opcache timestamp validation item), the text says that you should on the Opcache timestamp validation for development, but in the next line, it says that it's impossible to work in a development environment with Opcache on. This is contradictory.

It also says that it's important to turn on revalidation, but in the php.ini file, there are two revalidation options along with the timestamp Opcache option. It's ambiguous not to specify which one if not both, should we turn on (or off).

### What changes do you propose?

First, it's important to clarify for the text purpose if this option should be on or off. If this option should be on, then it's simply a matter of changing the "with" of the second sentence from "without".

It should look like this, I think:
Opcache timestamp validation should always be on for development. Development is impossible **without** Opcache on and revalidation _(specifying which revalidation must be turned on and if there are some recommended values)_ off because any PHP modification would require a cache reset.

**Comment by alejandro-rgp** [comment]
@magento I am working on this

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/php/development/build/development-environment/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-php/issues>.
