### ISSUE TITLE
The Cloud documentation on crons should cover how the jobs are run across the cluster

### ISSUE THREAD

**Issue by mpchadwick** [magento/devdocs#9384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

I think the DevDocs should cover how cron execution is split across the server cluster. My understanding is as follows (I'm only really interested in / aware of Pro production)

- On a traditional 3 server cluster the crons can be executed on any given node and are distributed across the cluster
- In a scaled environment, crons are executed on the three non-web nodes and are distributed across those nodes

It seems like how this works should be documented here, so calling this out as a gap as I couldn't find any info on it.

This seems like a logical home for this info: https://devdocs.magento.com/cloud/configure/setup-cron-jobs.html

**Comment by hguthrie** [comment]
@mpchadwick Thanks for calling out this gap in the Cloud docs. Great timing! We are in the process of evaluating the cron job content, and I am going to add your suggestions to our internal discussion. I hope to provide some exciting updates to this in the near future.

**Comment by hguthrie** [comment]
I am moving this issue to the new repository: https://github.com/AdobeDocs/commerce-cloud-service.en/issues/17
