### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by adamlavery** [magento/devdocs#9387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-insertlisting.html

### What's wrong with the content?

Take for example this bit of code taken from module-catalog\Ui\DataProvider\Product\Form\Modifier\Related.php

```
                        'dataProvider' => $dataProvider,
                        'map' => [
                            'id' => 'entity_id',
                            'name' => 'name',
                            'status' => 'status_text',
                            'attribute_set' => 'attribute_set_text',
                            'sku' => 'sku',
                            'price' => 'price',
                            'thumbnail' => 'thumbnail_src',
                        ],
                        'links' => [
                            'insertData' => '${ $.provider }:${ $.dataProvider }',
                            '__disableTmpl' => ['insertData' => false],
                        ],

```

Where is 'map' or 'links' described or references in this? How are we meant to know what it is and how/why we use it if you don't document everything related to this component? Are we to guess at it's purpose and config?

### What changes do you propose?

Complete the documentation so we have at least half a chance of working out how to correctly use the massively over-engineered UI components.

### Anything else that can help to cover this?

Invest a significantly more amount of time in your documentation because this is wasting significant amounts of our time trying to figure it out.

**Comment by hguthrie** [comment]
Hi @adamlavery To answer your question about the `links` property, it can be found in the [Linking properties concept](https://devdocs.magento.com/guides/v2.4/ui_comp_guide/concepts/ui_comp_linking_concept.html#links-property). The rest of your question may be answered by taking a closer look at the [DynamicRows configuration options](https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-dynamicrows.html#configuration-options).

**Comment by adamlavery** [comment]
Hi @hguthrie, I've taken another closer look the DynamicRows doc and nope, still can't see anything about the map property. Before posting I tried searching all Magento code for other instances that might explain it - nothing. Try searching the web - nothing.

I get that UI components are a difficult concept to explain clearly - it's an amorphous mass of endless config permutations that can be (and are) implemented in a variety of ways, even within Magento core. That's probably why docs are incomplete and instead just reference a few disjointed examples.

It's not just the docs that are lacking - the implementation is too. The config has to be entered correctly and if we get something wrong the best we get is some cryptic code failure that tells us nothing or more often we get nothing at all. The UI component doesn't render or doesn't work but there's no error or log anywhere to give us a clue as to what's wrong.

All in all, 2/10 for UI components.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/frontend-core/ui-components/components/insert-listing/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-frontend-core/issues>.
