### ISSUE TITLE
Explain URN Highlighter use in Visual Studio Code

### ISSUE THREAD

**Issue by adamlavery** [magento/devdocs#9388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-urn.html

### What's wrong with the content?

Briefly mentions Visual Studio Code and then nothing else.

### What changes do you propose?

 Explain how to enable this for VS Code, along with the missing --ide command options.

### Anything else that can help to cover this?

No, just properly documented is fine.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cli/urn-highlighter).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-operations.en/issues>.
