### ISSUE TITLE
mismatched permissions in examples

### ISSUE THREAD

**Issue by ekuusela** [magento/devdocs#939]
Feedback on page: /guides/v2.1/install-gde/prereq/file-system-perms.html

Under the heading **To set ownership and permissions for a one-user system:** there's an example for setting the permissions:

```
cd <your Magento install dir>
find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \;
find var vendor pub/static pub/media app/etc -type d -exec chmod u+w {} \;
chmod u+x bin/magento
```

but the one-liner version that follows adds the write permission to group instead of owner:

```
cd /var/www/html/magento2 && find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \; && chmod u+x bin/magento
```

**Comment by xcomSteveJohnson** [comment]
@ekuusela Fixed now. Please check and close if you're happy with the solution.
