### ISSUE TITLE
system-requirements : error in composer version in Magento >= 2.4.2 

### ISSUE THREAD

**Issue by tales-desde-mileto** [magento/devdocs#9390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

Composer versions in system-requirements.html

### What's wrong with the content?

Incorrect composer version in version >= 2.4.2
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html
Table: src/_includes/install/system-requirements-table.md

2.4.5 | 2.4.4 | 2.4.3-p2 | 2.4.3     | 2.4.2 works with composer 2
But in last doc we can read: composer 1
Or, perhaps, both version.
Now, if we read this, and we want to install 2.4.3p2 and have composer 2, according to this manual, I would say that it is not compatible. But it is compatible.

Is compatible from 2.4.2:
In doc:
https://devdocs.magento.com/guides/v2.4/release-notes/commerce-2-4-2.html
we can read:
------------
Magento 2.4.2 is now compatible with Composer 2.x. We recommend that merchants migrate to Composer 2.x. Although you can install this release using Composer 1.x, Composer 1.x will soon reach end-of-life. For an overview of Composer 2.x features, see [Composer 2.0 is now available!](https://blog.packagist.com/composer-2-0-is-now-available/)
------------
Then, if 2.4.2 works with both version: composer 1 and 2. Not only 1.

In previous versions of this doc, they show this value: composer 2. This is the commit.
diff --git a/src/_includes/install/system-requirements-table.md b/src/_includes/install/system-requirements-table.md
index 423a41db83..9764877222 100644
--- a/src/_includes/install/system-requirements-table.md
+++ b/src/_includes/install/system-requirements-table.md

### What changes do you propose?

Put all versions, like php row, there are values like: "7.2,7.3"
Then, in composer row, if works with version 1 and 2, show both.

**Comment by jeff-matthews** [comment]
Hi @tales-desde-mileto,

According to our engineering team, Adobe has not officially tested Composer 2 on versions earlier than 2.4.4. So although Composer 2 may be "compatible" with those versions, it does not necessarily mean that Adobe "supports" it. We try to make that clear in the introductory paragraph before the table:

> This table shows versions of third-party software dependencies that Adobe has tested with specific Adobe Commerce and Magento Open Source releases. Adobe only supports the combination of system requirements described in the following table.
>
> For example, 2.4.3 is fully tested with MariaDB 10.4. Adobe recommends that you upgrade to MariaDB 10.4 before upgrading to 2.4.3.

**Comment by tales-desde-mileto** [comment]
Hi @jeff-matthews 
Thanks for your answer.

But, then, the release notes of 2.4.2 are not correct:
https://devdocs.magento.com/guides/v2.4/release-notes/commerce-2-4-2.html
"Magento 2.4.2 is now compatible with Composer 2.x. We recommend that merchants migrate to Composer 2.x. Although you can install this release using Composer 1.x, Composer 1.x will soon reach end-of-life."

Based on this documentation and the previous version of system-requirements, since 2.4.2 I am using composer 2 in all my projects, so far, no problems. I will keep a close eye on this topic in case I find compatibility errors.

**Comment by jeff-matthews** [comment]
Technically, the release notes are correct.  2.4.2 is compatible with Composer 2, but that's not the same thing as supported. The system requirements page lists supported software only.

**Comment by hostep** [comment]
For the record https://github.com/magento/devdocs/pull/9425 does not fix this issue, no idea why this automatically linked?
