### ISSUE TITLE
Better explanation of datasource vs dataprovider

### ISSUE THREAD

**Issue by adamlavery** [magento/devdocs#9394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/ui_comp_guide/concepts/ui_comp_data_source.html

### What's wrong with the content?

_Remember that this data provider is still, technically speaking, a completely separate UI Component. To fully link it to the “base” component, there are a few things that need to happen so that the “base” UI component’s javascript can use the data provided by the data provider._

Why are we asked to remember a concept that has just been introduced? This is the first mention that the data provider is a separate UI component. What does that mean, why is that the case and how does it affect our config and use of the data provider? Better explanation needed along with concrete example of how this applies in the real world. e.g. what exactly is the "base" component in your example?

_A good way to keep configuration data out of the javascript is to declare a “provider” in the base component’s XML..._

Is it a good way or a required way? If a good way, why is it good and what's the alternative? If required then state it's required.

_This example declares the name of the data provider class and will be output in the JSON that contains the UI component’s configuration. It can then be used to locate the data source component. This is essentially declaring a variable that will be available to a javascript class._

Is this right? The example doesn't declare the name of the data provider class. It declares the name of the data provider. The data provider element declares the name of the data provider class. Let's assume we don't call the datasource and dataprovider the same thing e.g. [ComponentName].[ComponentName]_data_source. Let's say we name the datasource ..._data_source and we name the data provider as ..._data_provider (which would be more sensible). In that case is the provider element referring to [ComponentName].[ComponentName]_data_source or is it referring to [ComponentName].[ComponentName]_data_provider? Logic would suggest the latter.

### What changes do you propose?

Improve the document by answering the questions posed above,.

### Anything else that can help to cover this?

Further clarification is required on where we can declare and use a data source. It's become clear through trial and (sometimes) error (mostly nothing at all) that we can't just declare datasources willy nilly. There is some limitation on where these can be declared. 

Let's take for example a mod to the product_form. Say we're adding extra data to a product in the form of multiple values e.g. products are available only in number of fixed quantities, not any quantity. We need to capture a set of fixed quantities so we use a dynamicRow component with the data stored in a custom table. So we define a product_form.xml in our module in which we need to include our custom data source. Doesn't work - breaks the product form. Lots of examples include defining a data source in the module product_form.xml, including in the Dev Docs themselves. But these all just copy the datasource from the core product_form.xml. That's not required because it's already defined in the core XML and all that's doing is overriding with the same values in the module XML.

Try to add the custom datasource in the module's product_form.xml and you break the product page. Don't include it and you get no data into the custom UI element. 

This suggest that there are restrictions on where a data source can be specified. I'm guessing top-level Form and Listing only. Assuming so, why isn't this mentioned? Because the top-level product_form already has a datasource, we can't then include one in a module product_form. Which begs the question - what's the point of all the examples of modules supplying product_form additions when there's no way, through the XML, to retrieve the data with a data provider?

I've concluded that the way round this is to rename my product_form.xml to quantities_form.xml and then use a modifier with insertForm to insert that into the product_form. Maybe that'll work to allow me to use my data provider as the docs suggest.

Almost everything about UI components is largely guesswork because the docs are woefully lacking and the core you reference is a mass of uncommented code which doesn't follow the guidelines you lay down. For example, you suggest modifiers are only used for adding things like validation that can't be done through the XML definition, otherwise XML should be used. In that case why does the core use what appears to be a random mix of XMLs and modifiers to implement the forms? Look at related, up-sells & cross-sells; much of the form meta data is added with modifiers instead of XML. Why? Code is uncommented so no way to know the reasoning.

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/frontend-core/ui-components/concepts/data-source/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-frontend-core/issues>.
