### ISSUE TITLE
Outdated terms of service link

### ISSUE THREAD

**Issue by stefan-sedlak** [magento/devdocs#9395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/marketplace/sellers/account-setup-process.html

### What's wrong with the content?

Link [terms of service](https://magento.com/legal/terms/marketplace-xcelerate) is outdated and redirects to [Legacy Magento Terms](https://www.adobe.com/legal/terms/enterprise-licensing/magento-legacy-terms.html).

### What changes do you propose?

Update link to actual terms of service.

**Comment by BarnyShergold** [comment]
There are now two T & Cs to sign.

Please can these be confirmed and I'll update the page here and also any other places the outdated link appears
@stefan-sedlak @dobooth 


[Xcelerate & Marketplace Master Terms](https://magento.com/legal/terms/marketplace-xcelerate-master)
https://magento.com/legal/terms/marketplace-xcelerate-master

[Xcelerate & Marketplace Development terms](https://magento.com/legal/terms/marketplace-xcelerate-developer).
https://magento.com/legal/terms/marketplace-xcelerate-developer
