### ISSUE TITLE
Clarification of an example configuration

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/env/variables-deploy.html#cron_consumers_runner

### What's wrong with the content?

I have a customer that actually used consumer1 and consumer2 in their configuration as if they are actual consumers

### What changes do you propose?

Add a note that consumer1 and consumer2 are examples.

From https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-queue.html#view-a-list-of-available-message-queue-consumers:

```
To obtain a list of the available consumers, run this command:

bin/magento queue:consumer:list
```

**Comment by hguthrie** [comment]
Thanks for letting us know. I fixed this in the migration, so will be available soon in new docs.
