### ISSUE TITLE
Passing store code to URL is returning data for all stores

### ISSUE THREAD

**Issue by datacubed** [magento/devdocs#9405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

Fetch sales data by store code

### What's wrong with the content?

The docs say you should do: client.com/rest/<store code>/V1/orders?<filters>

When we do this for 1 of our clients <store code> is ignored and we get all their different stores' datas. This can be seen in the "items" array where the field "store_id" for some is 1, and others 2, 3 or 4.
Those ids appears to line up with their Magento config of having a different store per location.

Should the docs explain why this can/is happening? Or is this a bug somewhere?

### What changes do you propose?

Either fix the bug, or help us understand why <store code> isnt working correctly with this current setup.

**Comment by keharper** [comment]
@datacubed which page needs updating?

**Comment by danidelcar** [comment]
Hi @datacubed you are welcome to reopen this issue again if you still need help with it. Closing it due to no response
