### ISSUE TITLE
Completely secure installation missing explanation details

### ISSUE THREAD

**Issue by boban-dj** [magento/devdocs#9410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

Here:

 [https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-store.html#instgde-cli-fully-secure](url)

The document says:  "More details about these parameters can be found later in this topic."
But that is missing. There should be this example:

`bin/magento setup:store-config:set --base-url="https://myshop.com/" --base-url-secure="https://myshop.com/" --use-secure=1 --use-secure-admin=1
bin/magento cache:flush`

**Comment by Viper9x** [comment]
@boban-dj document says: "**More details** about these parameters can be found later in this topic."
The document did that, you can see these parameters have been described in the table at the end of the topic:
![Screen Shot 2022-05-07 at 14 05 36](https://user-images.githubusercontent.com/5556060/167243084-1e1ef71e-6c93-4a27-b055-76c32086520c.png)

@keharper I think this topic should be closed.

**Comment by boban-dj** [comment]
fine
