### ISSUE TITLE
Read-only apparently not supported

### ISSUE THREAD

**Issue by adamlavery** [magento/devdocs#9411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/pattern-library/getting-user-input/form_elements/form_elements.html#read-only-form-data

### What's wrong with the content?

Doc says there should be an option to set a field read-only (as opposed to disabled). But appears this never made it into the actual code. Or it did but was broken at some point and not fixed. 

### What changes do you propose?

Do UI components actually support  a read-only attribute or not? If they do, how is it enabled? If not, remove it from the docs.

### Anything else that can help to cover this?

While you're about it, this would be a reasonable place to actually include the relevant XML config that is required for such components, because this information isn't anywhere else.

**Comment by adamlavery** [comment]
Ok, so there is a way to do it: set elementTmpl to 'ui/form/element/text'. Somehow we're supposed to relate a text component to a read-only element. This doc should state that to create a read-only element, use the Text component, which happens to also be an input component! Cross reference this page to explain it: https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-text.html

**Comment by Viper9x** [comment]
@keharper the purpose of this topic is to describe Admin Design Pattern Library: Getting User Input - Form Elements.
This topic does not intend to guide how to implement the feature.
So, we don't need to modify this page and this issue should be closed, isn't it?

**Comment by adamlavery** [comment]
@Viper9x does what the doc describes work? Regardless of what it's meant to show - if what it describes doesn't actually work then there should be a note like "This is what should be available but it doesn't work so here's how to actually do it...".

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/admin-developer/pattern-library/getting-user-input/form-elements/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-admin-developer/issues>.
