### ISSUE TITLE
Make Backup RPO More Clear

### ISSUE THREAD

**Issue by shherman** [magento/devdocs#9413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/architecture/pro-architecture.html#backup-and-disaster-recovery

### What's wrong with the content?

Customers are unclear on what recovery points we store between Days 1 thru 3.
Per the table below it seems like we keep a backup every hour for the first 72 hours when really we keep only 1 backup per hour for the first day and then every 6 days for days 2 and 3.

https://devdocs.magento.com/cloud/architecture/pro-architecture.html#backup-and-disaster-recovery

### Anything else that can help to cover this?

![Screen Shot 2022-04-14 at 1 20 18 PM](https://user-images.githubusercontent.com/87450313/163452811-54bc61fa-4db0-4500-958e-2a15bd50d276.png)

**Comment by hguthrie** [comment]
@shherman This does seem to always be a point of confusion. Even though we make it fairly clear in the paragraph that introduces the table, we understand that the first line of the table can be confusing. Thanks for pointing this out and we will do our best to improve it.

On a separate note, please refrain from using direct names in our GitHub issues. If needed, we will reach out to the subject matter experts in our teams.

**Comment by hguthrie** [comment]
This has been updated and we are waiting on some feedback.
