### ISSUE TITLE
Incorrect information - does not apply to all implementations

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/live/sens-data-initial.html#configure

### What's wrong with the content?

These steps do not apply to Adobe Commerce Cloud - the section is not available:

```
In the Integration environment, you can log in to the Admin panel to modify system configuration settings for stores, websites, modules or extensions, static file optimization, and system values related to static content deployment. See [Configuration data](https://devdocs.magento.com/cloud/live/sens-data-over.html#configuration-data).
...
6. In the left navigation pane, click Advanced > Developer.
7. In the right pane, expand Template Settings.
8. Clear the Use default value checkbox next to the Minify Html list.
9. From the Minify Html list, click No
```

### What changes do you propose?

Add the caveat that the following steps do not apply to Adobe Commerce Cloud - they should be following this instead: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-config-mgmt-set.html#config-cli-config-file 

### Anything else that can help to cover this?

https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-config-mgmt-set.html#config-cli-config-file

**Comment by dobooth** [comment]
@gamarshall Can you take a look at this?

**Comment by hguthrie** [comment]
I don't see this anymore. If it is still a problem, you can open a JIRA for Devdocs or a GitHub issue in the new Cloud guide repository.
