### ISSUE TITLE
Missing content for create custom rest api

### ISSUE THREAD

**Issue by ravirajm10** [magento/devdocs#9418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

Tried to access the page but seems content is missing.

https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/create-custom-rest-api.html
<img width="1511" alt="Screenshot 2022-04-19 at 12 27 24" src="https://user-images.githubusercontent.com/19620035/163944341-e26c237e-7dcf-40c9-b365-62ae9165b481.png">

Kindly check .
Thanks

**Comment by bhargav-bvi** [comment]
@magento I am working on this

**Comment by bhargav-bvi** [comment]
@magento add to contributors team

**Comment by bhargav-bvi** [comment]
@magento add to contributors team

**Comment by dobooth** [comment]
This page is part of our migration policy. We are fixing the 404 today.
