### ISSUE TITLE
Bad minimum version of composer

### ISSUE THREAD

**Issue by jakubfrieb** [magento/devdocs#9426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

### What's wrong with the content?

You mentioned that minimum version of composer is 2.x for magento 2.4.4. and php 8.1 but .. with composer 2.0.12 I am getting deprecation errors so its not possible run bin/magento command (without supressing some error logging)

### What changes do you propose?

I've fixed it with install 2.2.x composer version .. and from composer git it seems that was fixed starting by 2.1.4 (see https://github.com/composer/composer/issues/10008)

**Comment by jeff-matthews** [comment]
Fixed in https://github.com/magento/devdocs/commit/0c67a578d3154952861ae09ee4127cca9d62d6de
