### ISSUE TITLE
Need clarification the difference between Extending and Overriding

### ISSUE THREAD

**Issue by adamlavery** [magento/devdocs#9432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-guide/css_quick_guide_approach.html

### What's wrong with the content?

Uses terms Extend and Override without explaining what these mean in terms of what style rules result. CSS itself has no concept of Extend vs Override. It simply reads CSS files and uses the most specific rule that applies to the element.

I'm guessing that Extending preserves all the rules of the parent i.e. combines the parent's LESS file with the child's. That would then mean Overriding uses the child LESS file only and ignore the parent's. If so this should be explained. 

Further explanation of the difference between the _extend.less and _theme.less files should given or at least cross-referenced here. Perhaps it would be clear if the above was explained clearly.

Finally, there's a confusing section on Blank:

_"However, the above only works if the theme’s parent is a Blank."_

What does that means and how do we know if the parent theme we're using "is a Blank"? Should this say "is Blank"? If so how to check if the theme we're using is a child of Blank or a fully independent "root" theme would be useful.

### What changes do you propose?

Clarify the points above. Will make this a much more useful document for people who find it when looking to change styles via a child theme.

### Anything else that can help to cover this?

???

**Comment by danidelcar** [comment]
Hi @omiroshnichenko do you have any suggestions as to how to approach this issue?, thanks!

**Comment by adamlavery** [comment]
"However, the above only works if the theme’s parent is a Blank." should be "...is Blank"!

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/frontend-core/guide/css/quickstart/customize-styles/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-frontend-core/issues>.
