### ISSUE TITLE
Configure XDebug wiki has incorrect information

### ISSUE THREAD

**Issue by gjohnadobe** [magento/devdocs#9443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/howtos/debug.html#enable

### What's wrong with the content?

The document states -

"You can enable Xdebug directly to all Starter environments and Pro Integration environments. For Pro Staging and Production, you need to update this file and enter a [Support ticket](https://devdocs.magento.com/cloud/trouble/trouble.html) to have it enabled. We enable Xdebug on those environments for you."

Pro Staging and Production this is now enabled by default

### What changes do you propose?

You could say "For Pro Staging and Production, Xdebug is enabled by default. You will need to configure it per https://devdocs.magento.com/cloud/howtos/debug.html#pro-debug"

**Comment by BarnyShergold** [comment]
I can categorically state that XDEBUG is NOT enabled by default on Cloud Pro Production & Staging.

Even if the .magento.app.yaml has xdebug listed in the runtime > extensions and has been deployed, it is REQUIRED that a ticket is raised to support to actually activate XDEBUG.

I am therefore closing this issue as the current documentation is correct.

**Comment by hguthrie** [comment]
Thank you for confirming that @BarnyShergold 👍

**Comment by BarnyShergold** [comment]
@magento I am working on this
