### ISSUE TITLE
Explain that the PHP version needs to be 

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/project/project-upgrade.html#application-upgrade

### What's wrong with the content?

This needs clarification:

```
For Pro projects, you must create a [Support ticket](http://support.magento.com/) to install or update services in Staging and Production environments. Indicate the service changes needed and include your updated .magento.app.yaml and services.yaml files in the ticket. It can take up to 48 hours for the Cloud infrastructure team to update your project.
```

PHP is not considered a service and the customer must upgrade PHP themselves: https://devdocs.magento.com/cloud/project/magento-app-php-application.html 

### What changes do you propose?

Add a note:

```
You would upgrade PHP yourself by [updating .magento.app.yaml](https://devdocs.magento.com/cloud/project/magento-app-php-application.html ) - this is not done by the Infastructure team.

That said, you should indicate on the ticket that you would be upgrading PHP as well - as the Infrastructure team might have to upgrade PHP-specific extensions to support the new version (such as the New Relic agent) - once you have upgraded the PHP version.
```

**Comment by dobooth** [comment]
@gamarshall @hguthrie Actionable?

**Comment by hguthrie** [comment]
I am working on this very topic right now to update extensions. Will include this issue, too. Thanks!

**Comment by hguthrie** [comment]
Update, I haven't forgotten about this issue. I made the change in a branch that has some other PHP-related fixes, and those fixes have been in a debated review. I may be able to merge this change in the next day or so.
