### ISSUE TITLE
Amendment / Correction to HTTP Access control

### ISSUE THREAD

**Issue by nlh-ddunn** [magento/devdocs#9446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/project/project-webint-basic.html#project-conf-env-set

### What's wrong with the content?

HTTP access control, when enabled via the Commerce Cloud UI will break Fastly caching (and related functionality like image optimization)

### What changes do you propose?

A notice or warning regarding this that it should only be used for integration / developer branches (ie: any branch that does not have Fastly) and that access control on production / staging should be done on Fastly itself

https://github.com/fastly/fastly-magento2/blob/master/Documentation/Guides/BLOCKING.md

### Anything else that can help to cover this?

https://www.fastly.com/blog/how-solve-anything-vcl-part-3-authentication-and-feature-flags-edge
 
Authentication
**_To date, there has not been a method to serve authenticated and authorized content out of cache_**, which greatly limits the value of a content delivery network for this type of content and hurts performance and scalability. With Fastly and VCL, once a user has been authenticated, the authorization and the content can be cached, providing extremely fast and scalable content delivery.
 
Bold + Italics for emphasis

**Comment by dobooth** [comment]
@gamarshall Easy fix here?
