### ISSUE TITLE
Page Not Found for Change message queue from MySQL to AMQP link

### ISSUE THREAD

**Issue by engcom-Hotel** [magento/devdocs#9447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html

### What's wrong with the content?

The link mentioned in the text `Change message queue from MySQL to AMQP` is not working and redirecting to a 404 page.

### What changes do you propose?

Please correct the link or remove the text if it is not required.

**Comment by erikmarr** [comment]
@engcom-Hotel thanks for your feedback! Looks like the link is working now.
