### ISSUE TITLE
No developer level documentation on how to programmatically (in code) create a custom attribute input type

### ISSUE THREAD

**Issue by rparsi-boxycharm** [magento/devdocs#9452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

I've searched the available magento developer documentation regarding attribute input types.
Specifically I'm looking for developer docs illustrating how to create a custom attribute input type in code,
that can be used as the renderer for (also in code) custom entity attributes.

For example, how to extend `Magento_Ui/js/dynamic-rows` to create a new custom attribute input type with custom rendering.

**Comment by goivvy** [comment]
@keharper Will a new menu page inside https://experienceleague.adobe.com/docs/commerce-admin/catalog/product-attributes/product-attributes.html be OK? Right after 'Add attribute to a product' I could add a page 'Create a custom attribute input type'. Will it belong there?

**Comment by jeff-matthews** [comment]
@goivvy, I'll defer to @keharper, but I don't think that _Admin User Guide_ is the right place for developer tutorials. I think this would make more sense as a tutorial in the [_PHP Developer Guide_](https://developer.adobe.com/commerce/php/tutorials/). What do you think?

**Comment by goivvy** [comment]
@jeff-matthews I agree.

@magento I am working on this

**Comment by keharper** [comment]
@goivvy I had forgotten there was a tutorials section in the _PHP Developer Guide_ and was looking for a place under "Component Development" to insert the info requested in this issue. The tutorial section would be perfect. Please consider adding links in [EAV and extension attributes](https://developer.adobe.com/commerce/php/development/components/attributes/) or anywhere else to your new tutorial.

**Comment by goivvy** [comment]
@keharper OK. I'm still working on it.

**Comment by jeff-matthews** [comment]
@goivvy, use https://github.com/AdobeDocs/commerce-php

**Comment by jeff-matthews** [comment]
@rparsi-boxycharm, 

@goivvy created a new topic to address your request in https://github.com/AdobeDocs/commerce-php/pull/150. Could you please take a look and share your feedback?

**Comment by dshevtsov** [comment]
This repository is not supported anymore.
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-php/issues>.
