### ISSUE TITLE
Details required on how to specify an empty array of consumers

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/env/variables-deploy.html#cron_consumers_runner

### What's wrong with the content?

```
consumers—An array of strings specifying which consumer(s) to run. An empty array runs all consumers.
```

It doesn't explain how to specify an empty array.

### What changes do you propose?

It can be explained using this example (instead of listing out the individual consumers):

``
consumers: []
``

**Comment by hguthrie** [comment]
@ak77-prime I actually have a ticket staged on our team board. I will add your comments from this GH issue to that ticket. Thanks!
