### ISSUE TITLE
Fix References to MongoDB in Magento Cloud CLI Documentation

### ISSUE THREAD

**Issue by shherman** [magento/devdocs#9463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/reference/cli/magento-cloud.html#servicemongodump

### What's wrong with the content?

Per Customer Support we believe that MongoDB is not supported on Commerce Cloud.
We believe we need to remove mention of MongoDB on this 2.3 and 2.4 Document

### What changes do you propose?

Remove mention of Mongo Services Options
Examples:

https://devdocs.magento.com/guides/v2.4/reference/cli/magento-cloud.html#servicemongodump
https://devdocs.magento.com/guides/v2.4/reference/cli/magento-cloud.html#servicemongoexport
https://devdocs.magento.com/guides/v2.4/reference/cli/magento-cloud.html#servicemongorestore
https://devdocs.magento.com/guides/v2.4/reference/cli/magento-cloud.html#servicemongoshell

### Anything else that can help to cover this?

N/A

**Comment by hguthrie** [comment]
@shherman  The reference page is generated based on magento-cloud CLI output. For example, when I use the CLI to list commands, they show as follows:

```
service
  service:list (services)                            List services in the project
  service:mongo:dump (mongodump)                     Create a binary archive dump of data from MongoDB
  service:mongo:export (mongoexport)                 Export data from MongoDB
  service:mongo:restore (mongorestore)               Restore a binary archive dump of data into MongoDB
  service:mongo:shell (mongo)                        Use the MongoDB shell
  service:redis-cli (redis)                          Access the Redis CLI
```

I will bring this up with the team to see what we can do.

**Comment by hguthrie** [comment]
@gamarshall Did you finish researching this?

**Comment by hguthrie** [comment]
I am closing this issue. The CLI is generated from a YAML dump. If the CLI needs changing, then can create an internal ticket.
