### ISSUE TITLE
JSON extension for PHP 8.x is not needed

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

In https://devdocs.magento.com/cloud/project/magento-app-php-application.html#php-extensions, under the list of ``INSTALLED EXTENSIONS THAT CANNOT BE UNINSTALLED`` - json would have to removed from .magento.app.yaml if the PHP version being upgraded to is 8.0 or newer, otherwise, it would throw a deployment error when you push the file:

```
E: Error parsing configuration files:
    - applications: Uncaught exception: The "json" extension is not supported for php:8.1
        at <script>:109:12
                      throw("The \"" + unsupported_extensions[0] + "\" extension is not supported for " + service.type);
                      ^

E: Error: Invalid configuration files, aborting build
```

**Comment by hguthrie** [comment]
The evaluation and work scheduled is in MCLOUD-8760

**Comment by hguthrie** [comment]
Am closing this issue since it has an internal ticket.
