### ISSUE TITLE
widget_accordion.html page improvement suggestion

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#947]
**How about you make more noticeable this section in tutorial:** 

<h3>Initialize accordion in a template</h3>
The accordion widget can be initialized using the data-mage-init attribute or <script> element, as described in JavaScript initialisation.
<h2></h2>
The link where tutorial is located: [link](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_accordion.html#collaps_active)

Reason: when i read the tutorial, then it was quite hard to notice.

**Comment by almarchenko** [comment]
@user3748173 
Thank you for your feedback!
I think that with the new devdocs design this section will become more noticeable, thanks to the ON THIS PAGE widget with the page TOC. It is located on the right when you open a page.
