### ISSUE TITLE
Incorrect notation used in the composer command to upgrade the application version

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/project/project-upgrade.html#application-upgrade

### What's wrong with the content?

1. Change to your application root directory and set the upgrade version using the version constraint syntax.

```
composer require "magento/magento-cloud-metapackage":">=CURRENT_VERSION <NEXT_VERSION" --no-update
```

### What changes do you propose?

Since the instruction was to **set the upgrade version**, so the command should be changed to

```
composer require "magento/magento-cloud-metapackage":">=UPGRADE_VERSION <NEXT_VERSION" --no-update
```

Where NEXT_VERSION can be:
1. Let's say the latest release is 2.4.4 (UPGRADE_VERSION) - then specify the next version as 2.4.5
2. Let's say the latest release is 2.4.5 and you want to upgrade to 2.4.4-p1 - specify the next version as 2.4.4-p2

**Comment by hguthrie** [comment]
This notation has been the same since ece-tools was released. I'm hesitant to change it now. However, I have clarified in the new documentation. There is a topic where the meta package constraints are explained in detail, so I will link to that for further understanding.
