### ISSUE TITLE
Add mention of 6-hour cooldown period for Pro Staging / Production storage increases

### ISSUE THREAD

**Issue by MeatPopsicle** [magento/devdocs#9474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

In the article: https://devdocs.magento.com/cloud/project/manage-disk-space.html
Namely the **Allocate disk space** section - https://devdocs.magento.com/cloud/project/manage-disk-space.html#allocate-disk-space.

I believe that there should be a notice that any storage increases of Pro Staging / Production environments performed by the Infrastructure team have a 6-hour cooldown period. For this reason, we usually recommend increasing in 10GB increments.

I've not found this information publicly available anywhere and think that merchants should be warned this is the case.

For example, editing the existing note to something like the following:
> You can change disk space allocation on Pro Integration and Starter environments only. You must submit a support ticket to change disk space allocation on Pro Production and Staging environments - please note that those increases have a 6-hour cooldown period and as such we recommend performing them in 10GB increments at minimum.

A reference ZenDesk ticket where platform have confirmed this: https://magento.zendesk.com/agent/tickets/527116.

Let me know if you require any further information at all.

**Comment by hguthrie** [comment]
Thank you for pointing this out! 
We will take a look.
