### ISSUE TITLE
WebApi - OAuth Login: HMAC-SHA1 is not a supported method. Magento docs should be updated.

### ISSUE THREAD

**Issue by engcom-November** [magento/devdocs#9478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

OAuth based Authentication

### What's wrong with the content?

The [documentation](https://developer.adobe.com/commerce/webapi/get-started/authentication/oauth-errors/) and code implementation do not match. In other [documentation](https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-oauth/) and in code, it states that the OAuth Signature method must be HMAC-SHA256 but in the above document, HMAC-SHA1 is mentioned as the supported signature method.

### What changes do you propose?

HMAC-SHA1 should be replaced with HMAC-SHA256 in this [docs](https://developer.adobe.com/commerce/webapi/get-started/authentication/oauth-errors/) and wherever applicable

### Anything else that can help to cover this?

**Comment by dshevtsov** [comment]
This repository is no longer supported.
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-webapi/issues>.
