### ISSUE TITLE
Order placed and Order History Using Graphql

### ISSUE THREAD

**Issue by farmketprocess** [magento/devdocs#9482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

if we place order using graphql then order placed successfully but its not updated in order history of customer . 

order placed : 
https://devdocs.magento.com/guides/v2.4/graphql/mutations/place-order.html

Order history query : 
https://devdocs.magento.com/guides/v2.4/graphql/queries/customer-orders.html

but dont update in the list customer orders list

**Comment by dobooth** [comment]
@farmketprocess We are going to close this as it sounds like a code issue and not a doc issue Please reopen if it is indeed a problem in the docs. Contact support if you suspect a bug: https://support.magento.com/hc/en-us.

**Comment by farmketprocess** [comment]
no code issue was their
