### ISSUE TITLE
Available patches not visible because of Error: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by lakshmana** [magento/devdocs#9490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/quality-patches/tool.html#patch-grid

### What's wrong with the content?

Available patches not visible because of the following error
`Error: Unexpected token < in JSON at position 1`
<img width="242" alt="image" src="https://user-images.githubusercontent.com/3132026/182402236-2e3c5f1a-2739-4581-a3f6-4552405131fe.png">

### What changes do you propose?

Available patches should be visible by fixing the following error
`Error: Unexpected token < in JSON at position 1`
<img width="242" alt="image" src="https://user-images.githubusercontent.com/3132026/182402236-2e3c5f1a-2739-4581-a3f6-4552405131fe.png">

**Comment by hguthrie** [comment]
@lakshmana  We don't see the same error. Which browser are you using? Have you tried clearing the cache?
Were you using the search field? We cannot reproduce, so let us know if this is still an issue.

**Comment by lakshmana** [comment]
Hi @hguthrie  it seems all good now. We can close this task.
