### ISSUE TITLE
Add a configurable product to a cart - Specify a parent and a child SKU : Given example is not working as expected

### ISSUE THREAD

**Issue by rmsundar1** [magento/devdocs#9493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-cart.html#add-a-configurable-product-to-a-cart

### What's wrong with the content?

I have tried the example given under `Specify a parent and a child SKU`, however, it's not adding the product as a configurable product into the cart instead it's adding the product as a simple product.

I looked into the code and there is no logic to get the configurable option based on the `parent_sku` and `sku` param

### What changes do you propose?

I would suggest removing this section and adding it back once its handled in code level

**Comment by dobooth** [comment]
@keharper Any thoughts here?

**Comment by keharper** [comment]
I'll try to find time to look at this issue. I don't work in this area any more, so it might be a while.

**Comment by hguthrie** [comment]
@keharper Do you need a little more time?

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/add-products/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-webapi/issues>.
