### ISSUE TITLE
Documentation contains lots of "Smart Quotes" / Microsoft-encoded quotes

### ISSUE THREAD

**Issue by mbacklas** [magento/devdocs#950]
For example, http://devdocs.magento.com/guides/m1x/api/soap/checkout/cartPayment/cart_payment.method.html contains in it's code examples multi instances of improper quote marks (“) which will break PHP - if you copy and past from the code examples it will not work correctly. Is there any reason this is written this way - or is it safe for me to replace all those improperly encoded characters?

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing that out. I do not know the history of how this was authored. You can replace these at will.

If I can find a way to globally search/replace, I'll fix them.

**Comment by mbacklas** [comment]
I do believe I have it sorted with a find replace I did - if I can grab some time here at the end of the day I'll do a pull and run it again and send a request over. Thanks!

**Comment by mbacklas** [comment]
Opening until I actually get it on here

**Comment by xcomSteveJohnson** [comment]
@mbacklas I just did a search-replace that found 64 instances of curly quotes across 14 files. I just need to validate it before I merge with develop.

Does that number sound about right to you?

**Comment by xcomSteveJohnson** [comment]
@mbacklas I merged a fix for 64 occurrences in 14 files. Please let me know if you find other instances of smart quotes.

**Comment by mbacklas** [comment]
@xcomSteveJohnson I also got 64 for the forward smart quotes - did you check for the ending quotes as well, since they user a different character? (”)

**Comment by xcomSteveJohnson** [comment]
That's a good point. Yes, I searched for both sets of quotes so you're correct, should be 128 occurrences in 14 files.

**Comment by mbacklas** [comment]
That sounds about right - I've noticed there are a few others in the /guides/v2.0/ - I haven't searched the other but my guess is a few slipped into /guides/v2.1/ and /guides/v2.2/ as well. However it seems those might be harder to dig through due to their directory structure - many images are being pulled up in my find and replace (Notepad++ is showing images as blobs). If you have a better method than I do to do a find and replace might not be a bad idea to search those as well. Thanks for the fast changes!

**Comment by xcomSteveJohnson** [comment]
If it helps, I use Sublime Text 2. To do the replace, I just copy to the clipboard each character and replace with `"`. Pretty simple.

Yegods! I just did a search across all guides and found almost 400 of them. I'll let the other writers know.

**Comment by mbacklas** [comment]
Sounds good! Thanks for all the help today - I knew those quotes looks suspect!

**Comment by xcomSteveJohnson** [comment]
@mbacklas Update: We're now down to 85 instances of smart quotes. We're asking the writers to remove those soon. I'll update this when we're done.

**Comment by mbacklas** [comment]
Great work!

**Comment by xcomSteveJohnson** [comment]
@mbacklas I believe we've removed all of them. Closing. Please reopen if you find some more.

**Comment by mbacklas** [comment]
Thanks for all the hard work!
