### ISSUE TITLE
Change to` composer require` command on 2.4.5 upgrade

### ISSUE THREAD

**Issue by meker12** [magento/devdocs#9502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/project/project-upgrade.html.

### What's wrong with the content?

While upgrading the Cloud verions, we encountered the following issues:

###  Requiring magento-cloud-metapackage

When running composer require in local env, we ran the command from the docs:

`composer require "magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --no-update`

Composer returned the following errors:

#### Error 1
`ERROR: 'composer require' does not function properly for magento/product-community-edition, magento/product-enterprise-edition, or magento/magento-cloud-metapackage metapackages as of Composer 2.1.6. Use 'require-commerce' instead `
and

#### Error 2 

`Could not find a magento/project package matching "magento/magento-cloud-metapackage >=2.4.5 <2.4.6" for PHP version 8.1.9 `

We checked that the version was correct in the [Magento Cloud Metapackage](https://github.com/magento-commerce/magento-cloud-metapackage/blob/2.4.5/composer.json)

To make it work we had to run:

`composer require-commerce "magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --update-with-dependencies`

The second error appeared again but it was ignored. This second error was not reproduced when building the 2.4.5 commerce test instance.

### JSON extension not required for PHP 8.1

The json extension is not needed anymore because it is already included in PHP 8.1, so there is no need to keep it in `.magento.app.yaml file`.

### What changes do you propose?

Update the  `composer-require` command -- or add a note about needing to use `require-commerce` . 

If needed, update the [Required PHP Settings](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/php-settings.html) to indicate that the json extension is not required if you are using PHP 8.1.

**Comment by BaDos** [comment]
@meker12 hi,

Can you provide more information regarding composer issue `composer require "magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --no-update`?

I use php 8.1, composer 2.2.4, template 2.4.4
run the command `composer require "magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --no-update` and it works, any errors and warnings

Could you tell me which version you tried to upgrade from?

**Comment by hguthrie** [comment]
We are closing this ticket because there has been no response to our request. If you think this issue needs further review, reopen the issue with the additional information.

**Comment by asim-blueprintprep** [comment]
@BaDos I'm not the original poster, but I have the same issue as above.

PHP:8.1.1
Composer: 2.3.4
Magento: 2.4.4

Running `composer require "magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --no-update`

Throws:

`ERROR: 'composer require' does not function properly for magento/product-community-edition, magento/product-enterprise-edition, or magento/magento-cloud-metapackage metapackages as of Composer 2.1.6. Use 'require-commerce' instead.`

So I run:

`composer require -commerce"magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --no-update`

Throws:

`Could not find a magento/project package matching "magento/magento-cloud-metapackage >=2.4.5 <2.4.6" for PHP version 8.1.1 `

**Comment by asim-blueprintprep** [comment]
@BaDos 

`php8 /usr/local/bin/composer22 --version`
`Composer version 2.2.18 2022-08-20 11:33:38`


`php8 /usr/local/bin/composer22 require "magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --no-update`

       
`ERROR: 'composer require' does not function properly for magento/product-community-edition, magento/product-enterprise-edition, or magento/magento-cloud-metapackage metapackages as of Composer 2.1.6. Use 'require-commerce' instead.`

`php8 /usr/local/bin/composer22 require-commerce "magento/magento-cloud-metapackage":">=2.4.5 <2.4.6" --no-update`


`Deprecation Notice: VersionSelector::findBestCandidate with ignored platform reqs as bool|array is deprecated since Composer 2.2, use an instance of PlatformRequirementFilterInterface instead. in phar:///usr/local/bin/composer22/src/Composer/Package/Version/VersionSelector.php:81
Could not find a magento/project package matching "magento/magento-cloud-metapackage >=2.4.5 <2.4.6" for PHP version 8.1.1                                                                                                                                                              
Update of composer.json with Adobe Commerce Cloud >=2.4.5 <2.4.6 changes failed, reverting ./composer.json to its original content from before the magento/project root update.
Root composer.json updates cannot run without a valid target metapackage
Running native execute...
./composer.json has been updated`

**Comment by shunmugakumaran** [comment]
Hello,

we are trying to upgrade to 2.4.6-p2 (latest release) from 2.4.6-p1 commerce

but we are facing the below issue says 
                                                                                                                                                                                                           **Could not find a magento/project package matching "magento/magento-cloud-metapackage 2.4.6"**

Kindly help us

![Screenshot from 2023-08-09 17-07-43](https://github.com/magento/devdocs/assets/84446887/61a73a10-01a4-4a15-93e7-5719c747b9a6)

**Comment by hguthrie** [comment]
> Hello,
> 
> we are trying to upgrade to 2.4.6-p2 (latest release) from 2.4.6-p1 commerce

@shunmugakumaran  The templates were updated yesterday: https://github.com/magento-commerce/magento-cloud/tree/2.4.6
I would verify you have all the updated files, that you are using Composer 2.2.21, and make another attempt.

@BaDos  Do you have any recommendations?

**Comment by shunmugakumaran** [comment]
we are using composer version 2.2.11 @hguthrie 

we are stuck on this help us

**Comment by shunmugakumaran** [comment]
I am using docker inside the container i am running the command @hguthrie

**Comment by hguthrie** [comment]
Yes, you need to use the Composer that is compatible with the [Cloud template](https://github.com/magento-commerce/magento-cloud/tree/2.4.6). See [the Commerce on Cloud guide about installing composer](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure/app/properties/properties.html#installing-and-using-composer-2).

If you are having difficulties with your deployment, it's best to reach out to your Customer Technical Advisor or [submit an Adobe Commerce Support ticket](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html#submit-ticket).

**Comment by shunmugakumaran** [comment]
Hi @hguthrie it is still in lower development. . we can't able tp update even we switch to composer version 2.2.21.. Kindly  help us

**Comment by mikedubinsky** [comment]
@shunmugakumaran I had a similar "...could not find a magento/project package matching..." error message and updating composer with `bin/root composer self-update 2.2.21` did not resolve fix the error, but simply running `composer update` **did update** to the latest (2.4.6p2/2.4.5p4) patch. Does it work for you?

**Comment by lano-vargas** [comment]
Same here `ERROR: 'composer require' does not function properly for magento/product-community-edition, magento/product-enterprise-edition, or magento/magento-cloud-metapackage metapackages as of Composer 2.1.6. Use 'require-commerce' instead.`
./composer.json has been updated. composer file was updated successfully and the upgrade also works correctly. However not sure why this error is spitting out still!

**Comment by kirubakaran-balu** [comment]
> Hello,
> 
> we are trying to upgrade to 2.4.6-p2 (latest release) from 2.4.6-p1 commerce
> 
> but we are facing the below issue says **Could not find a magento/project package matching "magento/magento-cloud-metapackage 2.4.6"**
> 
> Kindly help us
> 
> ![Screenshot from 2023-08-09 17-07-43](https://user-images.githubusercontent.com/84446887/259393691-61a73a10-01a4-4a15-93e7-5719c747b9a6.png)

I had similar issue, able to reproduce when trying to upgrade from 2.4.5-p1 to 2.4.6-p2. `composer require` was working fine instead `composer require-commerce`, some issue persist when trying to use `require-commerce`
