### ISSUE TITLE
instructions assume that the shell being used is bash and since MacOS 10.15 (catalina) zsh is the default shell 

### ISSUE THREAD

**Issue by straheyatadobe** [magento/devdocs#9503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

steps 3-4 assume its Bash but if the user is using zsh, the path isn't updated and the cli wont be found

### Expected behavior

na

### Steps to reproduce

na

### Environment

- Browser:
- OS: Macos 12.5.1 Monterey

**Comment by gamarshall** [comment]
@straheyatadobe We do not support macOS as a platform.  Please add link to where this topic resides.

**Comment by hguthrie** [comment]
We are closing this ticket because there has been no response to our request. If you think this issue needs further review, reopen it.
