### ISSUE TITLE
Cloud Patches version not updated on main ECE Tools page 

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

The table in https://devdocs.magento.com/cloud/release-notes/cloud-tools.html doesn't reflect the updated versions that are shown when you click on [cloud-patches](https://devdocs.magento.com/cloud/release-notes/mcp-release-notes.html) which should be 1.0.18

**Comment by hguthrie** [comment]
That page causes problems sometimes. @gamarshall can you make sure this page gets updated with the next release?

**Comment by jeff-matthews** [comment]
I think the [file](https://github.com/magento/devdocs/blob/master/src/_data/var.yml#L41) has been updated, but we need to do a full-site deployment since the change is only one character.

**Comment by jeff-matthews** [comment]
The full site deployment worked. Table now shows expected version.
