### ISSUE TITLE
Error 404 on Javascript Developer Guilde

### ISSUE THREAD

**Issue by tuanhaviet22** [magento/devdocs#9516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

- In the page [Javascript Developer Guilde](https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/bk-javascript-dev-guide.html) when click redirect to new doc version, all links return 404 error, include sub-topic: widget, javascript 

![image](https://user-images.githubusercontent.com/46513483/191725422-c2a55626-a2d8-4a41-9c7e-bde3f4edbed0.png)

**Comment by tuanhaviet22** [comment]
@magento I am working on this

**Comment by tuanhaviet22** [comment]
@magento add to contributors team

**Comment by tuanhaviet22** [comment]
So, what next step?!

**Comment by jeff-matthews** [comment]
Thanks for letting us know @tuanhaviet22. There seems to be a problem with the new location. I think the link is correct, but the page is unavailable. I'm redeploying the site and will confirm.

**Comment by jeff-matthews** [comment]
@tuanhaviet22, the site is back up and the link now resolves as exxpected.
