### ISSUE TITLE
Missing reference on how to install PWA Studio modules in Adobe Commerce

### ISSUE THREAD

**Issue by facundocapua** [magento/devdocs#9517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

In GraphQL documentation related to `attributesMetadata` query found in [here](https://devdocs.magento.com/guides/v2.4/graphql/queries/attributes-metadata.html) it is missing the steps to follow to get the PWA Modules installed in Magento.

I have also check the link at the top of that same page saying "PWA Studio only. [Learn more.](https://docs.magento.com/user-guide/getting-started.html#product-editions)" and there are no guide on how to get that query available in an Adobe Commerce Project.

I have also checked PWA Studio Installation guide that can be found [here](https://developer.adobe.com/commerce/pwa-studio/tutorials/) but it is oriented to Storefront development and not Adobe Commerce setup.

**Comment by facundocapua** [comment]
I have found it's described as the second step in this [page](https://developer.adobe.com/commerce/pwa-studio/tutorials/production-deployment/adobe-commerce/#add-required-adobe-commerce-extensions)

It's a bit confusing since that page is a guide on how to deploy PWA studio within Adobe Commerce Cloud and if I'm not mistaken those modules are necessary for any PWA Studio installation independently on where it is being deployed.

**Comment by dobooth** [comment]
@bdenham Care to take a look at this one?

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/webapi/graphql/schema/attributes/queries/attributes-metadata/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-webapi/issues>.
