### ISSUE TITLE
The procedure for managing domains on the project is partially incorrect

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/cdn/configure-fastly-customize-cache.html#manage-domains

### What's wrong with the content?

For Starter projects, use the Domains option to add and manage the Fastly domain configuration for your store. Before adding a domain to your project, you must submit a [Adobe Commerce Support ticket](https://support.magento.com/hc/en-us/articles/360019088251) to add the domain to your Cloud configuration. You can add the domain to Fastly after Magento confirms your request.

For Pro plan projects, you must submit a [Adobe Commerce support ticket](https://support.magento.com/hc/en-us/articles/360019088251) to update the Fastly domain configuration for your project.

The above is only partially correct. The steps below that begin with **To manage Fastly domain configuration from the Admin** apply to both Starter and Pro - but Pro projects must submit a request to complete the Nginx configuration.

In addition, Step 5 is incorrect:

```
You can only specify domains that have already been added to your Cloud infrastructure configuration.
```

### What changes do you propose?

For both Starter and Pro projects, you can use the Domains option to add and manage the Fastly domain configuration for your store. 

- For **Starter** projects, you must also go to your Project URL under the Domains tab and add the domain there, e.g., https://us-3.magento.cloud/projects/<project Id>/edit
- For **Pro** projects, if you are adding a domain to your project, you must submit a [Adobe Commerce Support ticket](https://support.magento.com/hc/en-us/articles/360019088251) to add the domain to your Cloud configuration. 

**To manage Fastly domain configuration from the Admin:**
...
Step 5 - if the pre-existing domain(s) has been configured on a different Fastly account, you must submit a ticket to request for ``Domain Delegation`` before you can proceed with specifying the domains.

**Comment by dobooth** [comment]
@hguthrie Something you want to handle?

**Comment by hguthrie** [comment]
I think this was addressed last month. @meker12 can we close this?
