### ISSUE TITLE
Stale links to topics migrated to Adobe domains

### ISSUE THREAD

**Issue by engcom-November** [magento/devdocs#9523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature should be added?

Update the devdocs links which are migrated to Adobe domains
Example: The link points to https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog, which was moved to https://developer.adobe.com/commerce/contributor/guides/code-contributions/

### What is the expected behavior?

Example: This link navigation redirected to below link directly: https://docs.magento.com/user-guide/catalog/inventory-product-alerts.html  : 

https://experienceleague.adobe.com/docs/commerce-admin/inventory/configuration/product-alerts/alert-setup.htmlhy

### How will this feature improve the user experience?

Direct access to documentations

**Comment by jeff-matthews** [comment]
Hi @engcom-November,

Thanks for the report. I'm not sure exactly where the link you reference appears in devdocs, but we are currently working on updating the navigation on the devdocs home page to point to new locations.

We will not implement redirects on devdocs until we've finished migrating all content. See https://community.magento.com/t5/News-Announcements/Community-Monthly-Update-February-2022/td-p/492851#toc-hId-828475519 for more information.
