### ISSUE TITLE
docs(graphql): ConfigurableProductOptions.use_default is documented incorrectly

### ISSUE THREAD

**Issue by engcom-November** [magento/devdocs#9526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/graphql/interfaces/configurable-product.html

### What's wrong with the content?

use_default: Boolean @doc(description: "Indicates whether the option is the default.")
This doc is incorrect and unclear

### What changes do you propose?

Change the doc to read more similarly to ConfigurableProductOptionsValues.use_default_value (the real purpose of the node).

use_default_value: Boolean @doc(description: "Indicates whether to use the default_label.")
As that's the actual purpose of the flag.

**Comment by keharper** [comment]
@damienwebdev If you have any idea what this field really does, leave a message here. It's going to be difficult to find an internal developer who knows.

**Comment by damienwebdev** [comment]
```gql
type ConfigurableProductOptions @doc(description: "Defines configurable attributes for the specified product.") {
    use_default: Boolean @doc(description: "Indicates whether the option is the default.")
}

type ConfigurableProductOptionsValues @doc(description: "Contains the index number assigned to a configurable product option.") {
    use_default_value: Boolean @doc(description: "Indicates whether to use the default_label.")
}
```

I'm pretty sure (not 100% that these two values are similar in intent, but at different levels.

Consider the following attribute structure:

```json
{
  code: "test_attribute",
  label: "Test Attribute",
  use_default: false
  values: [
    {
      uid: "1",
      label: "Green"
      store_label: "Green", 
      default_label: "Some better name but specific to this product",
      use_default_value: false
    }
  ]
}
```

In reality, the behind the scenes data structure looks like:
```json
{
  code: "test_attribute",
  label: "Test Attribute",
  store_label: "Some other language", 
  default_label: "Some better name but specific to this product",
  use_default: false
  values: [
    {
      uid: "1",
      label: "Green"
      store_label: "Green", 
      default_label: "Some better name but specific to this product",
      use_default_value: false
    }
  ]
}
```

I believe (unfortunately) that GraphQl is over-exposing the values: on  `ConfigurableProductOptionsValues`

```bash
ConfigurableProductOptionsValues {
   store_label: "Green", <-- Not relevant
   default_label: "Some better name but specific to this product" <-- Not relevant
   use_default_value: false <-- Not relevant
}

ConfigurableProductOptions { 
  label: "Test Attribute",
  store_label: "Some other language",  <-- Not relevant
  default_label: "Some better name but specific to this product", <-- Not relevant
  use_default: false <-- Not relevant
}
```

**Comment by dshevtsov** [comment]
The topic was [migrated](https://developer.adobe.com/commerce/webapi/graphql/schema/products/interfaces/types/configurable/).
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-webapi/issues>.
