### ISSUE TITLE
Upgrading PHP might require additional prep work

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

Upgrading of the PHP version is done by the merchant per https://devdocs.magento.com/cloud/project/magento-app-php-application.html

However, in some cases, the project's OS may not support the PHP version and would require an OS upgrade by the Infrastructure team before the customer would be able to proceed.

* Recommend adding the following before the [Extension support](https://devdocs.magento.com/cloud/project/magento-app-php-application.html#extension-support) section:

[Submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket) if you aren't able to successfully upgrade PHP.

* In addition, the [Extension support](https://devdocs.magento.com/cloud/project/magento-app-php-application.html#extension-support) section should say:

[Submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket) to install these PHP extensions in Production (Pro and Starter plans) and Staging (Pro plan only)

* Lastly, add another section:

To setup PHP to execute only SourceGuardian protected scripts **in all environments**, the following option must be set in the php.ini file: 

```
[SourceGuardian]
sourceguardian.restrict_unencoded = "1"
```

Source: [Section 3.5 of the SourceGuardian documentation](https://sourceguardian.com/demofiles/files/SourceGuardian%20for%20Linux%20User%20Manual.pdf)

**Comment by hguthrie** [comment]
Recently addressed this in the new repository. Should update in next business day or two.
