### ISSUE TITLE
Advanced notice required for upgrading in a live Production site

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/project/services.html

### What's wrong with the content?

Need to be more explicit that it requires a minimum 48 hour notice for upgrades in live Production

```
For Pro projects, you must create a [Support ticket](https://support.magento.com/hc/en-us) to install or update services in Staging and Production environments. Indicate the service changes needed and include your updated .magento.app.yaml and services.yaml files and PHP version in the ticket. It can take up to 48 hours for the Cloud infrastructure team to update your project.
```

### What changes do you propose?

For Pro projects, you must create a [Support ticket](https://support.magento.com/hc/en-us) to install or update services in Staging and Production environments. Indicate the service changes needed and include your updated .magento.app.yaml and services.yaml files and PHP version in the ticket. It can take up to 48 hours for the Cloud infrastructure team to update your project, and you must provide at least 48 hours' notice for a live Production site.

**Comment by hguthrie** [comment]
Okay, will be more explicit. Thanks!
