### ISSUE TITLE
Clarity around "....On macOS or Windows" on the "Synchronizing data in a Docker developer environment" doc

### ISSUE THREAD

**Issue by aingham** [magento/devdocs#9536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/docker/docker-syncing-data.html

### What's wrong with the content?

This topic talks about the best configurations depending on OS, but it would be really helpful here if when it talks about "Windows" it clarified whether this is regardless of whether WSL is being used or not. 

### What changes do you propose?

For example, when it says....

> On macOS or Windows hosts, this option results in extremely slow performance in the Docker environment.

Does this mean Windows regardless of whether WSL being used? If so then it could read...

> On macOS or Windows hosts (both Windows native and Windows WSL 1 or 2), this option results in extremely slow performance in the Docker environment.

### Anything else that can help to cover this?

I think I've seen other pages that this could be clarified on. So many people are using WSL now that I think this would be really helpful. It might also be necessary in some cases to distinguish between WSL 1 and 2, as these behave quite differently in terms of the file system.

Many thanks for considering this.

**Comment by hguthrie** [comment]
I moved this issue to the new commerce-cloud-tools repo.
