### ISSUE TITLE
Sendgrid transactional email credits/limits

### ISSUE THREAD

**Issue by gjohnadobe** [magento/devdocs#9539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/cloud/project/sendgrid.html#transactional-email-credits

### What's wrong with the content?

It seems somewhat contradictory.

The first paragraph -
"The 12,000 transactional email threshold refers to the number of transactional email messages that you can send on a monthly basis from Adobe Commerce on cloud infrastructure Pro Production, Integration, and Staging branches. The threshold is designed to protect against sending spam and potentially damaging your email reputation."

This seems to read that there is a limit of 12,000 emails

The document then states -
"There are no hard limits on the number of emails that can be sent in Production, as long as the Sender Reputation score is over 95%"

I've had customers query this and don't have a firm answer. Is there a limit? What happens if the limit is reached? Are they notified when the limit is reached or do they have to wait for email to stop working and then search the mail logs (per the document) 

### What changes do you propose?

Please check and clarify Sendgrid limits -

1. are there limits?
2. are the limits for Production soft or hard?
3. what happens if the limit is breached
4. is the customer notified automatically if the limit is breached

### Anything else that can help to cover this?

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/emails-not-being-sent-sendgrid-credits-exceeded.html?lang=en

This article states -

"There are no hard limits on the number of emails that can be sent in Production, as long as the Sender Reputation is over 95%. The reputation is affected by the number of bounced/rejected emails and whether DNS-based spam registries have flagged your domain as a potential spam source. In Production, a total of 12,000 emails are allocated per day, but that number can be extended based on the average number of emails that have been sent in the prior five days."

**Comment by BarnyShergold** [comment]
@hguthrie I can concur that this piece of documentation is contradictory and is not clear. Please can the 12,000 limit on PRODUCTION be confirmed or rejected? (We know it is correct for Staging & Integration)

Thanks

**Comment by hguthrie** [comment]
I copied this issue to the new repo: https://github.com/AdobeDocs/commerce-cloud-service.en/issues/5
