### ISSUE TITLE
Varnish 7.0 already unsupported

### ISSUE THREAD

**Issue by lopf** [magento/devdocs#9540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

### What's wrong with the content?

Varnish 7.0 is listed as the latest tested Varnish version for Magento >= 2.4.4 but Varnish 7.0 is already EOL. This leads to people wanting to install Varnish in a version which is already not supported anymore.

This is a followup of https://github.com/magento/magento2/issues/35536 which documents that the admin backend doesn't even provide the Varnish 7.0 configuration template.

### What changes do you propose?

Stick to a Varnish LTS release (currently 6.0) until a feature of a newer version is required.

**Comment by jeff-matthews** [comment]
Thanks for the report @lopf.

Since the latest version of the docs in this repo have moved, please report issues in the new repo.

https://github.com/AdobeDocs/commerce-operations.en/blob/main/help/installation/system-requirements.md
