### ISSUE TITLE
MySQL version >= 8.0.29 is no longer compatible with Magento

### ISSUE THREAD

**Issue by diwipl** [magento/devdocs#9543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

### What's wrong with the content?

The system requirements page 
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

Mentions MySQL 8.0 being compatible.

Unfortunately, MySQL starting with version 8.0.29 is no longer compatible until Magento 2.4.6 is released. 
More info here: https://github.com/magento/magento2/issues/35671 

### What changes do you propose?

It would be good to update requirements for Magento versions <= 2.4.5 and inform that only MySQL versions >= 8.0 and <= 8.0.29 are supported.

**Comment by diwipl** [comment]
Dear @jeff-matthews 

Thank you for the information. I will create an issue in the other repository.

**Comment by jeff-matthews** [comment]
Moved to https://github.com/AdobeDocs/commerce-operations.en/issues/84
