### ISSUE TITLE
Support documentation link about Command line tool doesn't work

### ISSUE THREAD

**Issue by OscarMerino** [magento/devdocs#9544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the cloud instances page, Support dropdown > Command line tool > Page not found https://devdocs.magento.com/guides/v2.4/cloud/before/before-workspace-cli.htmlthe 

### Expected behavior

Command line tool documentation

### Steps to reproduce

In the cloud instances page, Support dropdown > Command line tool >

### Environment

- Browser: Chrome

**Comment by jeff-matthews** [comment]
@OscarMerino,

I'm not sure where you found that link, but if you go to this [link](https://devdocs.magento.com/cloud/before/before-workspace-cli.html) (remove `guide/v2.4/`, you'll be redirected to the [correct location](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/develop/overview.html) on Experience League.

Is the link you're reporting on the cloud Project Web Interface? Can you please provide a screenshot?

**Comment by OscarMerino** [comment]
Sure @jeff-matthews 

In the Magento cloud environment I'm assigned (https://eu-4.magento.cloud/projects/55rzwkmk3qnfu/environments/master), on the top right there's a "Support" dropdown 


<img width="203" alt="Screenshot 2023-02-27 at 16 20 27" src="https://user-images.githubusercontent.com/10073809/221610765-56dc1bcb-f8ff-46cd-b5c3-430ba4c26c71.png">

**Comment by jeff-matthews** [comment]
Thanks for the screenshot @OscarMerino! 

I'll have to escalate this to a different team since it's not something that we can change on the doc site. That link has never existed, so it's not as if we changed something and failed to add a redirect.

**Comment by hguthrie** [comment]
Hi there!
For content about the `magento-cloud` CLI tool, you can read [Cloud CLI](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/dev-tools/cloud-cli.html) in the Commerce on Cloud Infrastructure Guide _Developer Tools_ section.
In the meantime, I am reviewing the linking for the Project Web UI. We cannot make these changes, but I can research them and file a report. Thanks for letting us know.

**Comment by OscarMerino** [comment]
This is the page I get from `magento-cloud`
<img width="975" alt="Screenshot 2023-03-10 at 17 02 47" src="https://user-images.githubusercontent.com/10073809/224364402-03ee0b5b-12c2-4df8-a7f2-f544d9dff3a0.png">

**Comment by hguthrie** [comment]
I created a new ticket for the CLI "docs" command update. Thanks!

**Comment by hguthrie** [comment]
Closing this issue because the other team will not be making any updates to the UI. There is a new Cloud Console available in beta, soon to be widely available. You can read about [Cloud Console](https://experienceleague.adobe.com/docs/commerce-cloud-service/start/cloud-console.html) in the _Commerce on Cloud Infrastructure guide_.
