### ISSUE TITLE
Stop Geo Locate please. Make it disabled by default.

### ISSUE THREAD

**Issue by JesperHerrloff** [magento/devdocs#9546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature should be added?

A option to translate the content on devdocs example:
https://experienceleague.adobe.com/docs/commerce-operations/tools/data-migration/migrate-data/overview.html

GeoLocation seems cool but its annoying as I constantly have to append lang=en to read documentation. Who on earth reads devdocs on Swedish? I have never ever met a professional developer that prefers reading technical references in Swedish. 

### What is the expected behavior?

Ability to decide on our own when the site should be translated. 

### How will this feature improve the user experience?

This feature is improving usability by make it less annoying to read the documentation.

I promise if you ask 100 developers 98 of them will prefer english language for technical documentations.

### What would a solution for this issue look like?

Disable IP geolocation. You could have it activated for everything but technical information.

**Comment by hguthrie** [comment]
The documentation is located in Experience League, so this is no longer the ideal place to create an issue. For the link you indicated, you can create an issue in the following repository:
https://github.com/AdobeDocs/commerce-operations.en

Regarding localization, are you not able to select a language preference?
<img width="260" alt="Screenshot 2023-03-03 at 08 28 31" src="https://user-images.githubusercontent.com/5817319/222746574-fea41577-3ded-418e-9afd-eb05d368eccb.png">

**Comment by JesperHerrloff** [comment]
Yes I am able to change via menu. But why do I need to change every time, thats annoying. 

Regarding this is not correct place to create an issue. Please visit this link:

https://devdocs.magento.com/guides/v2.3/migration/migration-tool-internal-spec.html

Change version to 2.4 and you will be redirected to Experience League :( 

But ofcourse I will add a Issue there to.

**Comment by hguthrie** [comment]
Thank you for the extra information. I have forwarded your concerns to our localization team, and we will look closer at the v2.3 experience.

**Comment by dshevtsov** [comment]
The issue has moved to https://github.com/AdobeDocs/commerce-operations.en/issues/85
