### ISSUE TITLE
Missing changes in 2.4.6

### ISSUE THREAD

**Issue by Nuranto** [magento/devdocs#9549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

In 2.4.6 releases notes, and in 2.4.6 breaking changes list, I did not see the fact that `catalog/seo/generate_category_product_rewrites` default value has been changed from 1 to 0.

Lucky me I found out before pushing 2.4.6 live. It could have cause seo issues.

https://github.com/magento/magento2/commit/78976ed4a52045872089e235b33a6ab13913c299

Another thing missing (breaking change) : Zend_Json cannot be used anymore.

**Comment by jeff-matthews** [comment]
Hi @Nuranto,

Thanks for the report. I'm looking into it now.

For future reference, backward incompatible changes documentation has moved:

- **Web page:** https://developer.adobe.com/commerce/php/development/backward-incompatible-changes/
- **Repo:** https://github.com/AdobeDocs/commerce-php/tree/main/src/pages/development/backward-incompatible-changes

I'll move this issue, but please report new issues in the new repo.
