### ISSUE TITLE
Component Manager link is not working

### ISSUE THREAD

**Issue by nikolalardev** [magento/devdocs#955]
Feedback on page: /guides/v2.1/extension-dev-guide/intro/intro-composer-gloss.html

When you click on Component Manager link you are redirect to here http://devdocs.magento.com/guides/v2.1/comp-mgr/compman-start.html

And I get: Page Not Found

**Comment by xcomSteveJohnson** [comment]
Fixed now. Please close this if you're satisfied.

**Comment by nikolalardev** [comment]
Fixed.
