### ISSUE TITLE
Add a page about adding layered navigation to custom product collections

### ISSUE THREAD

**Issue by ioweb-gr** [magento/devdocs#9551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

In Magento 1 it was pretty straightforward how to create your own custom collections with layered navigation or how to override categories' product collection to achieve tailored listing for specific use cases. 

In Magento 2 there is no documentation on how to achieve this and searching online you can only find scattered examples where nothing is fully working. EIther the product count is wrong, either the results are wrong or the toolbard is not working. 

I think many merchants would like to be able to show custom pages like new products / sale products / products grouped by an attribute and getting the collection is easy. 

However showing the product list with layered navigation is a totally different story 

Just take a search here and you'll see what I mean 

https://magento.stackexchange.com/search?q=custom+product+collection

Dozens of unanswered questions about the topic and answers that are not working.

Realistically speaking, it's worth a topic on it's own in the documentation in my humble opinion. 

Two distinct use cases are coming to mind

1. Custom Product Collection displayed by a controller similar to a category with layered navigation
2. Modifying a category's product collection and layered navigation to add some custom filtering to provide chosen products that will sell better.  

Would it be possible to give us some insight on how to achieve this?

**Comment by dshevtsov** [comment]
The documentation migrated to [Adobe Commerce Developer Documentation](https://developer.adobe.com/commerce/docs/).

If the issue is still relevant, please feel free to reopen it in the [related project](https://github.com/topics/adobe-commerce-devsite).
