### ISSUE TITLE
Missing page for Need help adding keys? On Add SSH Key step

### ISSUE THREAD

**Issue by pax-by** [magento/devdocs#9552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

Missing page https://devdocs.magento.com/guides/v2.4/cloud/before/before-workspace.html 

Link used on magento cloud panel, like that: https://eu-5.magento.cloud/projects/*/environments/master/ssh

![Monosnap Magento 2023-07-26 15-25-50](https://github.com/magento/devdocs/assets/18660054/b6e88487-5c8d-43b2-9507-935701b4d9da)

**Comment by hguthrie** [comment]
Reviewed the redirect for the SSH topic and found that the old topic URL is actually the following and redirects as expected:
https://devdocs.magento.com/cloud/before/before-workspace-ssh.html

The Cloud guide was not versioned. The Cloud UI was incorrectly updated at some point with a version in the docs URL. I reviewed the Cloud console and I no longer see a link to docs in the SSH Keys section of Account settings, but there are still open tickets on links to docs. Nothing more we can do here. Thanks for reporting!
