### ISSUE TITLE
Wrong procedure in Magento Commerce Cloud Github integration

### ISSUE THREAD

**Issue by richiardc** [magento/devdocs#9553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/dev-tools/integrations/github.html

### What's wrong with the content?

The section about Enable the GitHub integration isn't correct. 
Now the param --base-url is no longer required indeed if you specify this parameter the procedure returns an error repository: Unable to connect to GitHub: repository not found. 

That parameter is to be considered required only if the base url is custom I think.

Also the add webhook section is no longer needed in case of direct integration with repository located on github.com. In fact, it is automatically enabled by the previous command.

### What changes do you propose?

Modify the documentation with previous suggestion.

**Comment by hguthrie** [comment]
Closing this issue; I moved this issue to the [Cloud guide repository](https://github.com/AdobeDocs/commerce-cloud-service.en/issues/33) for more awareness.
