### ISSUE TITLE
Tab attribute type reference not working on 2.4.x

### ISSUE THREAD

**Issue by mandrills** [magento/devdocs#9554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/files/config-reference-systemxml.html?lang=en

### What's wrong with the content?

When the type attribute is added to the tab in system.xml, an error is reported when executing set:up.
![image](https://github.com/magento/devdocs/assets/14126358/b6645622-ccc9-4d59-8696-3a7c5f07fedf)
Code show as below
![image](https://github.com/magento/devdocs/assets/14126358/dec0d882-6f2e-4e80-9224-9ac0d83c45e4)

**Comment by hguthrie** [comment]
This repository is no longer updated. Moved this issue to the new repository for further investigation.
https://github.com/AdobeDocs/commerce-operations.en/issues/105

**Comment by mandrills** [comment]
thx.
