### ISSUE TITLE
div with classname "nav-container" is fixed abnormally

### ISSUE THREAD

**Issue by RajShukla1** [magento/devdocs#9555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
shot from 2023-09-14 14-33-39](https://github.com/magento/devdocs/assets/75747452/7b0b8caf-823e-4cac-8955-2f47f519aee1)

### Expected behavior

The div should either be hidden itself or there should be option to hide it while reading other content of the page
![Screen
![Ss](https://github.com/magento/devdocs/assets/75747452/f628bea1-55bf-4258-9cf9-e3217d2b0edb)

steps to reproduce

just open https://devdocs.magento.com/ this URL

### Environment

- Browser:
- OS:

**Comment by dshevtsov** [comment]
@RajShukla1, thank you for your feedback. https://devdocs.magento.com/ is not supported anymore. All documentation was migrated to the [Adobe Experience League](https://experienceleague.adobe.com/docs/commerce.html) and [Adobe Developer](https://developer.adobe.com/commerce/) websites.
