### ISSUE TITLE
Rabbitmq / Magento2.4.7 required version inconsistency

### ISSUE THREAD

**Issue by Nuranto** [magento/devdocs#9559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements

### What's wrong with the content?

On [requirements page](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements), RabbitMQ required version is 3.12 for M2.4.7.

On [2.4.7 release notes page](https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/magento-open-source/2-4-7), it says 3.13

### What changes do you propose?

I don't know which one is correct, so idk.

### Anything else that can help to cover this?

-

**Comment by dshevtsov** [comment]
This repository is not supported anymore.
If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-operations.en/issues>.
