### ISSUE TITLE
POST /V1/customers api issue

### ISSUE THREAD

**Issue by engcom-Delta** [magento/devdocs#9561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature should be added?

API Documentation: https://developer.adobe.com/commerce/webapi/rest/tutorials/orders/order-create-customer/

But the api works if the endpoint is: <magento_url>/<store_view_code>/rest/V1/customers (client project)
![image](https://github.com/user-attachments/assets/3848c0d0-725a-4a71-b805-b4b801d3088e)

Please refer the ticket - https://github.com/magento/magento2/issues/38994

### What is the expected behavior?

https://example.magento.test//rest/<store_code>/V1/customers api should work

### How will this feature improve the user experience?

**Preconditions and environment**

- Magento version 2.4.5-P8
- Should have at least one website

**Steps to reproduce**

- Create an integration and get the access token
- Using the token, make a call to POST /V1/customers API to create customer

**Expected result**
https://example.magento.test//rest/<store_code>/V1/customers api should work
**Actual result**
Getting 400 Bad request error:
{
"message": "Specified request cannot be processed."
}
![image](https://github.com/user-attachments/assets/df78a701-dd95-49b0-8d9c-3ebe96b7b23d)
**Additional information**
API Documentation: https://developer.adobe.com/commerce/webapi/rest/tutorials/orders/order-create-customer/
But the api works if the endpoint is: <magento_url>/<store_view_code>/rest/V1/customers (client project)

![image](https://github.com/user-attachments/assets/284a5acf-aa62-4466-a5f5-43879f86d1c4)

**Comment by keharper** [comment]
@engcom-Delta you're opening an issue in an outdated repo. Please reference https://github.com/AdobeDocs/commerce-webapi instead. (See the top-level README for this repo for confirmation.)

**Comment by dshevtsov** [comment]
Closing this issue since this repository is not supported anymore due to documentation migration.
@engcom-Delta Please reopen it in https://github.com/AdobeDocs/commerce-webapi as pointed out by @keharper.
