### ISSUE TITLE
Lack of clarity regarding global 3rd party javascript library inclusion

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#957]
When I refer to this [page](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js-resources.html), specifically this section:
```JavaScript resources can be specified as follows:

Library level for all libraries in Magento code base (lib/web)
```
Is it even possible in M2 to add additional files to `<docRoot>/lib/web` and then pull that in via require.js? Say I wanted to add a library to `<docRoot>/lib/web/js/custom.js` ... how would I refer to `lib/web/js/custom` in my *custom theme's* requirejs-config.js file? Most of the examples are relating to custom modules, and javascript which is within the custom modules web/js scope.

**Comment by almarchenko** [comment]
@ryantfowler thank you for feedback! 
I'll get in touch with developers and get back to your question.

**Comment by almarchenko** [comment]
Internal issue 63023

**Comment by almarchenko** [comment]
@ryantfowler 
Thanks for drawing our attention to this topic. Looks like it needs enhancements, and I'm working on it. Meanwhile, the quick answer to your question:
We strongly recommend third party developers not to put custom files in web/lib. 
You can put them in custom modules (the files will be available for other modules and themes), or in custom theme (the files will be available for inheriting themes only).

**Comment by ryantfowler** [comment]
Thank you got your response with clarity regarding the situation. Yes,
information on this would be good in the documents.

I'd go do far as to suggest that a section of the docs be dedicated to
"common actions a M1 front-end dev won't be able to do in M2". Thinking
through what's there might also highlight areas that are lacking in the
current docs.

Thank you

**Comment by almarchenko** [comment]
@ryantfowler 
Thank you for the idea!

**Comment by almarchenko** [comment]
@ryantfowler 
Do you mind if I close this ticket? 
I've created a new internal one for improving the doc.

**Comment by ryantfowler** [comment]
Not at all

**Comment by xcomSteveJohnson** [comment]
From earlier comments, it looks like this should have been closed. Feel free to reopen if that's not correct.
