### ISSUE TITLE
Suggestion to a documentation (Errors caused by modules)

### ISSUE THREAD

**Issue by user3748173** [magento/devdocs#958]
Sorry if it not the right place, but I have another suggestion based on posts i have seen in magento.stackexchange.com/. 

I have worked with Wordpress and common knowledge in that CMS is that if something is not working then it is probably caused by plugin(in magento it is modules). To locate where exactly the problem is, it is advised:  ["If you can access the Administration Screens try deactivating all of your Plugins and then reactivating them one by one."](https://codex.wordpress.org/Common_WordPress_Errors)

I have not found what is Magento advise in that situation, some of the posts would be more detailed if beginner users (not developers) would follow some kind of tutorial to locate more precisely the module that is causing the problem they are facing. This would also help them to solve the problem they are facing.

I don't know any other place where to post this topic to get a good discussion on this subject. Sorry if that kind of doc already exists or if i am just trashing this repository, please tell me if i am doing so.

**Comment by xcomSteveJohnson** [comment]
@user3748173 This is good feedback, thanks. What is the difference between beginning users and developers in your opinion?

Can you give an example of where this has worked for you? Are you currently facing such an issue?

**Comment by user3748173** [comment]
No I am not  facing such an issue, but when i have looked at some magento.stackexchange.com/ questions _(two separate days, accidentally skipping through new posts. I spotted same issue - too little information provided to answer both were caused by Magento version upgrade)_ then some guide how to narrow down issue (or module) that is causing the problem in module by Magento version upgrade would be nice. I am not saying the Wordpress solution is suitable to Magento it is just example how Wordpress has solved similar problem.

Example error: `region.js:59 Uncaught TypeError: Cannot read property 'indexedOptions' of undefined`. This error is not telling much.

The more quicker user who has bought or downloaded free module can figure out where the problem is (in what module) the quicker he/she can get a solution to problem (from magento.stackexchange.com/  or original module developers). 

(He/she can then at least provide some information about module functionality in forum - does the module write over any layout element...). 

May be the problem is altogether in theme files. Is there any possibilities (action) to filter that out?

In my previous comment I meant users who does not have previous programming experiences, not beginner users. Sorry for that confusion.

**Comment by xcomSteveJohnson** [comment]
Tracking with internal issue MAGETWO-62896. We'll need engineering input for this.

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to create a new issue if necessary. Thank you for continued collaboration and assistance!
