### ISSUE TITLE
Routing page for magento 2.x display old magento 1.x way?

### ISSUE THREAD

**Issue by maxfootball18** [magento/devdocs#959]
Feedback on page: /guides/v2.0/extension-dev-guide/routing.html

Basically, is there a reason why creating multiple actions for one controller doesn't work like in the Doc:

    public function createAction()
    {
        $this->_forward('noroute');
    }

    public function forgotpasswordAction()
    {
        $this->_forward('noroute');
    }

but I came across this somewhere on the web: 

>  In Magento 2, each controller class have only one action method named execute whereas in Magento 1, we can have multiple actions in same controller. 

[http://ashutoshpandey.in/creating-controller-in-magento-2/](url)

Could have save some time figuring that thing in the doc instead on the web and by digging in the code ... :(

**Comment by jcalcaben** [comment]
This issue has been addressed in #1161 

Thanks @maxfootball18  for reporting it and @VincentMarmiesse for the PR!
