### ISSUE TITLE
Misleading examples of private data in configuration guide

### ISSUE THREAD

**Issue by ekuusela** [magento/devdocs#960]
Feedback on page: /guides/v2.1/config-guide/cache/cache-priv-priv.html

> Examples of private content include the wishlist, shopping cart, customer name, and addresses. Private content should be limited to a small portion of the total content on a page.

I inspected my local storage after modifying addresses and selecting some of them for shipping and so on but I can't find the actual addresses in that private content. Only data related to addresses are the IDs of the currently selected addressed (`selectedBillingAddress`, `selectedShippingAddress`) and text filled into forms (`shippingAddressFromData`, `newCustomerBillingAddress`, `newCustomerShippingAddress`).

**Comment by xcomSteveJohnson** [comment]
We need input from @antonkril on this.

**Comment by antonkril** [comment]
Addresses here were provided as an example of private content. Not all private content is stored in local storage, only the content required by private data blocks rendered in browser. Actual address information is not required by blocks, so it's not loaded to local storage.

**Comment by xcomSteveJohnson** [comment]
@ekuusela Does this answer your question? If not, what remaining questions do you have?

**Comment by xcomSteveJohnson** [comment]
@ekuusela Any update?

**Comment by ekuusela** [comment]
No further questions.
