### ISSUE TITLE
Add XML Naming Convention to Code Standards

### ISSUE THREAD

**Issue by bassplayer7** [magento/devdocs#964]
There is currently no naming convention in place for layout XML files. This isn't really a syntax problem as there are few defined requirements on what you can and cannot do with the layout XML naming. However, I have noticed a pattern in various places in Magento and have found it to work very well in my own development. On [Twitter](https://twitter.com/bassplayer_7/status/814140503327473664), 
I received one reply, @gazjoy, and they agreed with my sentiment as well.

My suggestion is to formalize the following XML naming convention (which I could submit a PR for if there is interest):

- Attribute `name`: namespace approach, all lowercase, and separated by `.` (periods).
   - Example: `parent.child.grandchild.descendant`
   - Example `header.actions.search`
- Attribute `as`: all lowercase, separated by `_` (underscore), and concise because it is only scoped to the current block.
    - Example: `search_box`

While it is brief, I believe that it would be helpful to formalize and standardize on a best practice naming convention in those files. While much of Magento core appears to follow that approach, it certainly is not followed 100%. By baking this as a concrete best practice, it very well could help other developers in the same way that naming conventions such as BEM have helped front end web developers.

Feedback on page: /guides/v2.1/coding-standards/bk-coding-standards.html

**Comment by xcomSteveJohnson** [comment]
Sure, please send us a PR. Thanks!

**Comment by bassplayer7** [comment]
Great. I'll do that.

**Comment by almarchenko** [comment]
@eug123 @MomotenkoNatalia 
Guys, do we have internal naming conventions for XML files?

**Comment by jcalcaben** [comment]
PR Link: https://github.com/magento/devdocs/pull/1078

**Comment by almarchenko** [comment]
@bassplayer7 What I found out is that currently we don't have these internal standards. 
We need the opinion and decision of architects on this. 
@antonkril  perhaps you can help? Should Magento start following these standards?

**Comment by hguthrie** [comment]
Awaiting feedback on the pull request.

**Comment by hguthrie** [comment]
The related pull request was closed based on architecture discussions, see https://github.com/magento/architecture/wiki/October-31,-2018
