### ISSUE TITLE
Very poor documentartion

### ISSUE THREAD

**Issue by jbecerra-topgroup** [magento/devdocs#966]
Feedback on page: /guides/v2.0/ui-components/ui-form.html

Please improve the information about ui_components.

I need examples on defining field validations in forms using ui_components

There is nothing about fieldsets and fields

Thanks

**Comment by BenSpace48** [comment]
Agreed, this doesn't look great on either Github or the devdoc, it looks like a custom parser isn't playing nice. For example:

```
{% highlight xml %} ... {% endhighlight %}
```

- https://github.com/magento/devdocs/blob/develop/guides/v2.1/ui_comp_guide/components/ui-form.md
- http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-form.html

**Comment by jbecerra-topgroup** [comment]
Some example of validations using ui_components:

`<field name="MyField">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="sortOrder" xsi:type="number">100</item>
                    <item name="dataType" xsi:type="string">string</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="label" xsi:type="string" translate="true">Myfield</item>
                    <item name="validation" xsi:type="array">
                        <item name="required-entry" xsi:type="boolean">true</item>
                        <item name="validate-number-range" xsi:type="string">-90-90</item>
                    </item>
                    <item name="notice" xsi:type="string" translate="true">decimal number: from  -90 to  90</item>
                </item>
            </argument>
        </field>`  
This work!

But this not:

 `<item name="pattern" xsi:type="**string**"><![CDATA[/[A]{2,5}/]]></item>`

Why? in: validation.js, line 425

`"pattern": [
            function (value, element, param) {
                return this.optional(element) || param.test(value);
            },
            'Invalid format.'
        ],`

The value of 'param' is a string, not a regular expresion, so it fail. What xsi:type I must use?

Thanks again

**Comment by almarchenko** [comment]
@jbecerra-topgroup Thank you for your feedback!
Creating the better docs about UI components is in our priorities, and we definitely will improve the docs.

Regarding your particular question about validation, I think better chances for getting the answer are if you post it on  [Magento 2 GitHub](https://github.com/magento/magento2/issues), [Magento forum](https://community.magento.com/), or [stackexchange](http://magento.stackexchange.com/).

**Comment by almarchenko** [comment]
@BenSpace48 
Hi! Thank you for your feedback.
Could you plz specify what exactly is wrong/broken on 
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-form.html ?
Cause for me all code samples look ok.

**Comment by BenSpace48** [comment]
@almarchenko - The code blocks are ok on the devdocs but the link to form.js isn't being parsed, it's in the overview section.

I presume this:

![screen shot 2017-01-06 at 13 41 12](https://cloud.githubusercontent.com/assets/8895777/21719443/cdb96f46-d415-11e6-9c5a-c70075c86479.png)

Should look like this:

The following is the Form component constructor: [form.js](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Ui/view/base/web/js/form/form.js)

------


It is being rendered inside a code block, I've created a [pull request](https://github.com/magento/devdocs/compare/develop...BenSpace48:patch-4) to fix it.

**Comment by almarchenko** [comment]
@BenSpace48  Thank you, now I see!
Thanks for the PR! I'll happily merge it once it is ready! (now it looks like in progress)

**Comment by BenSpace48** [comment]
@almarchenko Do you mean in progress with me or with Magento?

**Comment by BenSpace48** [comment]
Never mind, I didn't actually create it. Oops.

The actual PR is here - https://github.com/magento/devdocs/pull/976

**Comment by almarchenko** [comment]
@BenSpace48  I merged it. Thanks for your input!

**Comment by almarchenko** [comment]
@jbecerra-topgroup  Do you mind if I close the issue for now?

**Comment by xcomSteveJohnson** [comment]
Closing due to age. Feel free to reopen if you still have issues.
