### ISSUE TITLE
media not restored from db when accessing images directly

### ISSUE THREAD

**Issue by markus2810** [magento/devdocs#970]
I have db media storage configured and it seems working fine on a first glance. But when I delete the media files in the pub folder in the file system, the files are not loaded from the db when the files are accessed directly. e.g. domain.com/pub/media/wysiwyg/home.jpg.
When I go over content->edit page->insert image. The file is loaded from the db and placed under ub/media/wysiwyg/home.jpg on the file system. After that, the direct access works again. I would expect the same load from db mechanism when the file is access directly using the url.

Am I missing something? Is this known issue?

I am using magento 2.1.2

**Comment by xcomSteveJohnson** [comment]
Closing, feel free to reopen if you still have questions.
