### ISSUE TITLE
Unclear documentation about --base-url-secure on CLI setup

### ISSUE THREAD

**Issue by scottsb** [magento/devdocs#971]
Twice on the CLI install page the following statement is included:

> To have a fully secure site, you must enable both `--use-secure=1` and `--base-url-secure=1`.

However, the `--base-url-secure` argument is described like this:

> Secure base URL to use to access your Magento Admin and storefront in the following format: `http[s]://<host or ip>/<your Magento install dir>/`

Either the `--base-url-secure` argument also accepts a binary value (`1`) whose meaning should be explained, or else the statement about "fully secure site" requirements is wrong. My suspicion is that the statement is actually supposed to be about `--use-secure-admin` like this:

> To have a fully secure site, you must enable both `--use-secure=1` and `--use-secure-admin=1`.

If somebody confirms this, I can submit a PR fix.

**Comment by xcomSteveJohnson** [comment]
@scottsb Thanks for pointing it out. I'll talk with engineering and get back to you.

**Comment by xcomSteveJohnson** [comment]
To the following topics, I _added_ a new section toward the beginning titled "Completely secure installation" that discusses the options you need to set and _removed_ it from the table, where it was easy to miss.

I still have a question to whether or not `base-url` must be `https://` and will add that if necessary.

Affected topics:

http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-install.html

http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html

http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-subcommands-store.html

http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-store.html

Please check and close this if everything is correct.

**Comment by scottsb** [comment]
This looks good. (As far as I know `base-url` would not need to be `https://` itself as well, but I'm only ankle-deep in Magento 2, with the depth of my experience on Magento 1.)
