### ISSUE TITLE
Incorrect validation rules specified in --backend-frontname documentation

### ISSUE THREAD

**Issue by scottsb** [magento/devdocs#972]
The documentation for `--backend-frontname` states:

> The Admin URI can contain alphanumeric values, the underscore character (_), and the dash character (-) only. It can be up to 255 characters in length.

However, the regex for this argument in `Magento\Backend\Setup\ConfigOptionsList:: validate()` is `/^[a-zA-Z0-9_]+$/`, which does not allow for dashes (or, more precisely, hyphens).

Also, the validator doesn't actually limit this to 255 characters in length. I can't imagine why you'd possibly want it longer than that, but the statement should probably be removed since it's not actually accurate. (The only possibility is if this is enforced somewhere deeper in the Magento code itself, past the actual install script.)

**Comment by xcomSteveJohnson** [comment]
Fixed, please check:

http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html

http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-install.html

http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-subcommands-deployment.html

http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-deployment.html

Please close this if it's correct.

**Comment by scottsb** [comment]
The update about the characters looks good.

What was your thought on the 255 character limit (or lack thereof)?

**Comment by xcomSteveJohnson** [comment]
Sorry, I missed that. I'll check.

**Comment by xcomSteveJohnson** [comment]
The character limit of 255 isn't true and I removed it. Please check:

http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html

**Comment by scottsb** [comment]
Looks good.
