### ISSUE TITLE
Accurate Message Queue documentation?

### ISSUE THREAD

**Issue by cbartak-rivet** [magento/devdocs#974]
Feedback on page: /guides/v2.1/config-guide/mq/config-mq.html

Is this documentation accurate and up-to-date? The structure of the example XML differs slightly from the sample data https://github.com/magento/magento2-samples/tree/master/sample-module-sample-message-queue. For instance, queue.xml uses a consumerInstance property (which references a non-existent class), and that property is absent in the sample data.

This documentation also lacks an example of _asynchronous_ messaging, which is an important aspect of this topic.

**Comment by keharper** [comment]
@cbartak-rivet , consumerInstance was added for 2.1 and subsequently deferred to 2.2. I'll remove it from the docs, since it shouldn't be there. I'll ask Development for a working asynch example.

**Comment by keharper** [comment]
I take that back. `consumerInstance` is a valid parameter--I looked in the wrong xsd file when I made that statement.

The `consumerInstance` parameter in the example in `config-mq.html` points to a valid class in EE. Are you using CE or EE?

**Comment by cbartak-rivet** [comment]
@keharper - Thanks for the follow-up. After digging through core for a while I also found that consumerInstance was a valid attribute (the class referenced exists too...not sure why I missed that). Please ignore that part of the comment.

I think an async example would be a good addition. There should also be a section on listing and starting consumers, as is mentioned in the MySQL MQ documentation page: http://devdocs.magento.com/guides/v2.1/config-guide/mq/manage-mysql.html. Maybe this part should be broken out into its own page and linked to from both the MySQL Message Queue and Rabbit MQ pages, since it's universal.

In the end I was successful at setting up a working asynchronous message queue on EE 2.1 once I pieced everything together.

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to create a new issue if necessary. Thank you for continued collaboration and assistance!
