### ISSUE TITLE
Expanding module name standards description

### ISSUE THREAD

**Issue by alankent** [magento/devdocs#978]
Feedback on page: /guides/v2.1/extension-dev-guide/build/composer-integration.html

It would be good to clarify further the difference between a "project" and a "product". The following needs to be confirmed, but my recollection is a "project" package is a template used by the "composer create-project" command. So it contains a recommended skeleton project structure. We have one for CE and EE that sets up default composer.json, .gitignore, etc files.  The "product" package is the real software. So when you run "composer create-project" you will be a new directory containing a template composer.json file pointing at the "product" package.

Towards the bottom of the page in terms of package names, it would be good to be a little clearer. http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/composer-integration.html#package-name - in particular, "type-prefix is a type of component in a Magento-specific domain" I would list the actual prefixes there ("module", "theme", etc). There are not many options. (See below question regarding "extension metapackage" type-prefix.)

I would also include somewhere around there a description of how extensions are structured. That is, an extension has a metapackage pointing to the modules. In that case, what is the recommended naming convention for the metapackage and modules? Using "module-" as a type-prefix does not feel right for the metapackage. Do we use "extension-" or "metapackage-" is a "type prefix" (see previous paragraph).

Thanks!
Alan

**Comment by jcalcaben** [comment]
Thanks for the feedback @alankent !

I have updated the documentation as you suggested. Let me know if I missed anything!

**Comment by xcomSteveJohnson** [comment]
Closing due to lack of response. Feel free to reopen if you still have qusetions.
