### ISSUE TITLE
Migration path 2.x

### ISSUE THREAD

**Issue by stalniy** [magento/devdocs#980]
It looks like a bad joke :)) are there plans for kind of tech article explaining of how to migrate 1.x extension to 2.x?

Feedback on page: /guides/v2.0/howdoi/migrate/migrate-extensions.html

**Comment by xcomSteveJohnson** [comment]
We have a [code migration toolkit](https://github.com/magento/code-migration) you can use to get started. Do you have another question? If not we'll close this one.

**Comment by jeff-matthews** [comment]
We added more documentation about extending the data migration tool to specifically help migrate extensions: http://devdocs.magento.com/guides/v2.2/migration/extend-the-tool.html
