### ISSUE TITLE
ambiguity on Redis requirements

### ISSUE THREAD

**Issue by valugi** [magento/devdocs#981]
Feedback on page: /guides/v2.0/install-gde/system-requirements-tech.html

> Magento can utilize the following technologies:
> Redis version 3.0 for page caching and session storage (the latter supported by Magento version 2.0.6 and later only)

I want to clarify if the *can* is a *must*, or I can use Redis 2.8.19, which is the standard EPEL version today. Can I use version 2+ or is 3.0 a minimum accepted version?

**Comment by choukalos** [comment]
Helo @valugi we use Colin's redis adapter ([link](https://github.com/colinmollenhour/Cm_Cache_Backend_Redis)) which supports Redis 2.4+ .  We only tested with Redis 3+ and didn't test prior versions.  M2 probably works with Redis 2.4+, please give it a shot and let us know your experience.

**Comment by xcomSteveJohnson** [comment]
Closing due to no response. Please reopen if you still have questions.

**Comment by valugi** [comment]
I do not understand why this is closed without an answer. And how difficult is to clarify? I do not want to make mean comments but again and again the big problem with Magento is the lack of proper docs.

**Comment by xcomSteveJohnson** [comment]
Your answer is [here](https://github.com/magento/devdocs/issues/981#issuecomment-271463285). Did you try a 2.x Redis version?

**Comment by valugi** [comment]
Sorry but that is not an official documented answer, but an opinion. My question was precise in wording and I would like to have a precise answer in the official documentation. The documentation should specify minimum requirements and official supported version of the software it REQUIERES for the EE version. I can try all existing versions, but then what is the need of the documentation? Maybe all users that install Magento should first try various versions to see if they work or not?
