### ISSUE TITLE
Missing : Magento CE 1.9.1.0 Release Notes

### ISSUE THREAD

**Issue by CodeMuz** [magento/devdocs#983]
[http://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html](http://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html)

The above page is missing section for the link:
**_[Magento CE 1.9.1.0 Release Notes](http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#magento/release-notes-ce-1.9.1.html)_**

**Comment by xcomSteveJohnson** [comment]
Updated the link, thanks for catching that. Please close this if it's correct.
