### ISSUE TITLE
Can I have a list of all the bugs that being fixed as part of release 2.1.3

### ISSUE THREAD

**Issue by angelamettas** [magento/devdocs#988]
Feedback on page: /guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html

**Comment by xcomSteveJohnson** [comment]
You mean this? http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html#functional-fixes-and-enhancements

**Comment by angelamettas** [comment]
No, because that says there is over 90 bugs and issues being fixed in this
version and doesnt list all of them - i want the full list of what bugs are
being fixed

On 13 January 2017 at 09:38, Steve Johnson <notifications@github.com> wrote:

> You mean this? http://devdocs.magento.com/guides/v2.1/release-notes/
> ReleaseNotes2.1.3CE.html#functional-fixes-and-enhancements
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__devdocs.magento.com_guides_v2.1_release-2Dnotes_ReleaseNotes2.1.3CE.html-23functional-2Dfixes-2Dand-2Denhancements&d=DgMCaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=T3dnJQf-UuAYsYOalozBUnNS2jgrI7-IfGNJRZlHc1Q&s=uoB5tWdFqpXk1XUi2OWnl18PkIuvgu3od1cmr6LF2Vk&e=>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magento_devdocs_issues_988-23issuecomment-2D272306458&d=DgMCaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=T3dnJQf-UuAYsYOalozBUnNS2jgrI7-IfGNJRZlHc1Q&s=m-PnxyUaJ4wwaL-XWeQlqIhqp8WWtkcSiX9Jz_FYNzE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AX7ZMvXVLj8UaZ7svvkF4KOE45sPq-2DvGks5rRqtbgaJpZM4LiUSw&d=DgMCaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=T3dnJQf-UuAYsYOalozBUnNS2jgrI7-IfGNJRZlHc1Q&s=Cpph8bbUbfiIcLgOwCi4_Kywg5Wj-odjQGmXEULv644&e=>
> .
>



-- 
[image: Fairfax Media]
Angela Metcalfe | Business Analyst| Fairfax Media
t 02  | m 0402 154423| Angela.Metcalfe@fairfaxmedia.com.au

-- 
The information contained in this e-mail message and any accompanying files 
is or may be confidential. If you are not the intended recipient, any use, 
dissemination, reliance, forwarding, printing or copying of this e-mail or 
any attached files is unauthorised. This e-mail is subject to copyright. No 
part of it should be reproduced, adapted or communicated without the 
written consent of the copyright owner. If you have received this e-mail in 
error please advise the sender immediately by return e-mail or telephone 
and delete all copies. Fairfax Media does not guarantee the accuracy or 
completeness of any information contained in this e-mail or attached files. 
Internet communications are not secure, therefore Fairfax Media does not 
accept legal responsibility for the contents of this message or attached 
files.

**Comment by hostep** [comment]
@angelamettas, something like this might help: https://github.com/magento/magento2/compare/2.1.2...2.1.3

**Comment by xcomSteveJohnson** [comment]
@angelamettas Do you have the info you need? Can we close this?

**Comment by angelamettas** [comment]
I have never gotten this information, I'm just referred back to the release
notes which just have general information

On 26 January 2017 at 06:24, Steve Johnson <notifications@github.com> wrote:

> @angelamettas
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_angelamettas&d=DwMCaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=tZDYyAKANNhDJo2ldrGhOjHL_qK6Sm82WTnQdWeAkNo&s=CQTw0Sk2W-N_qNf-BAAw4lDfeCehn4B7X_pznAPalVE&e=>
> Do you have the info you need? Can we close this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magento_devdocs_issues_988-23issuecomment-2D275206571&d=DwMCaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=tZDYyAKANNhDJo2ldrGhOjHL_qK6Sm82WTnQdWeAkNo&s=THs_w1BXFF6Mb4zb-Gtra7H0aHTJDwJMqAkkA6iZglI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AX7ZMsgfzbfsiOlCihzkjlvUNBYTrddhks5rV6FWgaJpZM4LiUSw&d=DwMCaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=tZDYyAKANNhDJo2ldrGhOjHL_qK6Sm82WTnQdWeAkNo&s=gZbsvK10sfGySVna2o39dNUMy4cqV5ggxeh3woDwHXc&e=>
> .
>



-- 
[image: Fairfax Media]
Angela Metcalfe | Business Analyst| Fairfax Media
t 02  | m 0402 154423| Angela.Metcalfe@fairfaxmedia.com.au

-- 
The information contained in this e-mail message and any accompanying files 
is or may be confidential. If you are not the intended recipient, any use, 
dissemination, reliance, forwarding, printing or copying of this e-mail or 
any attached files is unauthorised. This e-mail is subject to copyright. No 
part of it should be reproduced, adapted or communicated without the 
written consent of the copyright owner. If you have received this e-mail in 
error please advise the sender immediately by return e-mail or telephone 
and delete all copies. Fairfax Media does not guarantee the accuracy or 
completeness of any information contained in this e-mail or attached files. 
Internet communications are not secure, therefore Fairfax Media does not 
accept legal responsibility for the contents of this message or attached 
files.

**Comment by jfrontain** [comment]
hi @angelamettas, my apologies for the delay in responding to your question. Release notes do not cover each fixed issue in a release, but we strive to document the following: 

* every contribution made by a community member, no matter how small

* every bug fix with an associated GitHub issue

* every bug of a P0 and P1 severity level that affects customer-facing code.

We don’t document the many fixes that improve our internal processes.
