### ISSUE TITLE
Example of Moving header links is out of date for 2.1

### ISSUE THREAD

**Issue by Ctucker9233** [magento/devdocs#989]
Feedback on page: /guides/v2.1/frontend-dev-guide/layouts/layout-practice.html

The information in this example seems out of date or incomplete. If the instructions are followed, the developer is left with an unsightly bullet list of links and some of the links are duplicated. One appears in the bullet list and one appears in its original format. A more concise and thorough guide would be appreciated.

Some changes:
Update example code for 2.1 structure. I could not find the file to place the markup needed for a dropdown menu anywhere
Site where files used in the guide are found in source code
Don't assume the developer knows what classes or ids to use when adding styles
Since Luma theme already has this functionality, perhaps configuring the guide to show how to configure this functionality for the blank theme would be easier. ie what files to change, which lines to change, where to find those files.

**Comment by almarchenko** [comment]
@Ctucker9233  Thank you for the feedback!
I've created an internal issue 63240 to update the topic.

**Comment by Ctucker9233** [comment]
@almarchenko Happy to help!

**Comment by almarchenko** [comment]
@Ctucker9233  We've updated the page
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/layouts/layout-practice.html

Thank you for your feedback!
