### ISSUE TITLE
Document using x-magento-init and data-mage-init in dynamic content

### ISSUE THREAD

**Issue by timneutkens** [magento/devdocs#992]
The following gist should be in the devdocs 👍 
https://gist.github.com/timneutkens/004f8ac0f963068fa718e8397877194e

**Comment by almarchenko** [comment]
HI @timneutkens 
Thanks for your input!
I'll consult with our JS devs!

**Comment by timneutkens** [comment]
Great, thanks! 👍

**Comment by almarchenko** [comment]
@timneutkens 
I've create an internal issue MAGETWO-63395 to add this info.
Thanks again for your input!

**Comment by timneutkens** [comment]
Thank you 🙂

**Comment by timneutkens** [comment]
Any updates on this? Going through my open issues list to clean up. I can add it myself if you want 👌🏻

**Comment by almarchenko** [comment]
@timneutkens We still didn't manage to find resources to cover this.
>I can add it myself if you want  
That would be fantastic! Then we would only need an hour or two of dev time to review, which is much easier. 
Please let us know if you need any assistance! Here's our [Devdocs Contributor Guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing_docs.html) with guidelines and tips.
Thank you!

**Comment by timneutkens** [comment]
Not using Magento anymore, so I'm going to close this.
