### ISSUE TITLE
Regarding this 

### ISSUE THREAD

**Issue by manojs229** [magento/devdocs#996]
Feedback on page: /guides/v2.0/frontend-dev-guide/layouts/layout-practice.html

Hi Please tell me , its fine working for it show only after login . but i want dropdown for sign in and create an account under my accont text . so i can add in my project . plz let me know how can i do this.

Regards
Manoj Sonawane

**Comment by almarchenko** [comment]
Hi @manojs229 thank you for your feedback.
I think better chances for getting the answer are if you post your question on  [Magento 2 GitHub](https://github.com/magento/magento2/issues), [Magento forum](https://community.magento.com/), or [stackexchange](http://magento.stackexchange.com/).

**Comment by xcomSteveJohnson** [comment]
Closing. Feel free to reopen if you still have a question for us.
