### ISSUE TITLE
Update cataloginventory_stock_item resource to account for multi-warehouse

### ISSUE THREAD

**Issue by james-mcdonald-serato** [magento/devdocs#997]
Hey team. 

It appears there is currently no way to update stock attributes for specific warehouses via the API. It seems that a stock item must be a global qty. 

Can we include a specified warehouse in the catalogInventoryStockItemUpdateEntity ?

Regards

**Comment by keharper** [comment]
Unfortunately, this feature doesn't exist. It's been discussed, but work on it has been deferred.

**Comment by james-mcdonald-serato** [comment]
Thanks @keharper.

I understand I can specify a store view via the cataloginventory_stock_item.update call, and ALSO include the catalogInventoryStockItemUpdateEntity array.

If a specific warehouse is associated ONLY with a particular store view, would that be sufficient to update the qty in that warehouse? I'm trying this call now and am receiving a True response but can't see any changes made when viewing the magento backend

**Comment by maghamed** [comment]
Hi @james-mcdonald-serato ,
For now Magento doesn't support multi warehouse functionality.
So, business logic relies on the assumption that Magento is a single stock.
Potentially using APIs you could create Several Stocks (StockInterface) and assign different amount of products to them, creating StockItems for each of that stock (Stock item has Stock_Id - referring to specific stock and Product_Id - referring to specific product).
But business logic now written in a way to use the only stock item assigned to default stock.
So, if we have two or more stocks and products assigned to them, we don't sum up these quantities to provide compound value on front-end. 

So, there are next possibilities to get Multi Warehouse functionality:

- build it by yourself as an extension, that will require to overwrite existing implementation of CatalogInventory module
- use Single Stock Magento, but synchronize it with ERP or other Product Inventory system, which will make deduction on each specific warehouse.
